Коротин Егор. Вариант 14. Минимальное значение элементов матрицы.
learning-process/ppc-2024-autumn pull request #100
Opened 2024-11-01 13:31 UTC by KorotinEgor

seq: Матрица представлена в памяти в виде одномерного массива, для нахождения минимального элемента матрицы, создаётся временная переменная, изначально равная левому верхнему элементу матрицы, потом она поочерёдно сравнивается со всеми остальными элеметами матрицы. Если значение временной переменной оказывается больше выбранного элемента, она присвваивает значение этого элемента.
mpi: Матрица представлена так же как и в seq, затем главный процесс разбивает её на n условно равных участков, где n - количество процессов, затем каждый процесс независимо вычисляет минимальный элемент в своей части матрицы по алгоритму, описанному в seq, после чего главный процесс собирает все минимумы, полученнные остальными процессами и выбирает из них самый минимальный элемент.

2024-11-02 09:23 UTC, IljarSmirnov commented on tasks/seq/korotin_e_min_val_matrix/src/ops_seq.cpp
> +  std::this_thread::sleep_for(20ms);
it's an unnecessary line

2024-11-02 09:23 UTC, IljarSmirnov commented on tasks/seq/korotin_e_min_val_matrix/func_tests/main.cpp
> +  ASSERT_EQ(res, min_val[0]);
you should use ASSERT_NEAR or ASSERT_DOUBLE_EQ to compare double

2024-11-02 09:23 UTC, IljarSmirnov commented on tasks/seq/korotin_e_min_val_matrix/perf_tests/main.cpp
> +  ASSERT_EQ(1, min_val[0]);
you should use ASSERT_NEAR or ASSERT_DOUBLE_EQ to compare double

2024-11-02 09:23 UTC, IljarSmirnov commented on tasks/seq/korotin_e_min_val_matrix/perf_tests/main.cpp
> +  ASSERT_EQ(1, min_val[0]);
you should use ASSERT_NEAR or ASSERT_DOUBLE_EQ to compare double

2024-11-02 09:23 UTC, IljarSmirnov commented on tasks/mpi/korotin_e_min_val_matrix/src/ops_mpi.cpp
> +  std::this_thread::sleep_for(20ms);
it's an unnecessary line

2024-11-02 09:23 UTC, IljarSmirnov commented on tasks/mpi/korotin_e_min_val_matrix/func_tests/main.cpp
> +    ASSERT_EQ(reference[0], min_val[0]);
similarly, you should use ASSERT_NEAR or ASSERT_DOUBLE_EQ to compare double

2024-11-02 11:32 UTC, SergeyBoRss commented on tasks/mpi/korotin_e_min_val_matrix/include/ops_mpi.hpp
> +#include <string>
The includ is not used

2024-11-02 11:32 UTC, SergeyBoRss commented on tasks/mpi/korotin_e_min_val_matrix/src/ops_mpi.cpp
> +#include <string>
The inclusion is not used

2024-11-02 11:32 UTC, SergeyBoRss commented on tasks/mpi/korotin_e_min_val_matrix/src/ops_mpi.cpp
> +  for (unsigned i = 0; i < taskData->inputs_count[0]; i++) {
You can use std::copy

2024-11-02 11:32 UTC, SergeyBoRss commented on tasks/seq/korotin_e_min_val_matrix/src/ops_seq.cpp
> +  for (unsigned i = 0; i < taskData->inputs_count[0]; i++) {
You can use std::copy

2024-11-02 13:16 UTC, KorotinEgor commented on tasks/seq/korotin_e_min_val_matrix/src/ops_seq.cpp
> +  std::this_thread::sleep_for(20ms);
fixed

2024-11-02 13:16 UTC, KorotinEgor commented on tasks/seq/korotin_e_min_val_matrix/func_tests/main.cpp
> +  ASSERT_EQ(res, min_val[0]);
fixed

2024-11-02 13:16 UTC, KorotinEgor commented on tasks/seq/korotin_e_min_val_matrix/perf_tests/main.cpp
> +  ASSERT_EQ(1, min_val[0]);
fixed

2024-11-02 13:16 UTC, KorotinEgor commented on tasks/seq/korotin_e_min_val_matrix/perf_tests/main.cpp
> +  ASSERT_EQ(1, min_val[0]);
fixed

2024-11-02 13:17 UTC, KorotinEgor commented on tasks/mpi/korotin_e_min_val_matrix/src/ops_mpi.cpp
> +  std::this_thread::sleep_for(20ms);
fixed

2024-11-02 13:17 UTC, KorotinEgor commented on tasks/mpi/korotin_e_min_val_matrix/func_tests/main.cpp
> +    ASSERT_EQ(reference[0], min_val[0]);
fixed

2024-11-02 13:17 UTC, KorotinEgor commented on tasks/mpi/korotin_e_min_val_matrix/include/ops_mpi.hpp
> +#include <string>
fixed

2024-11-02 13:17 UTC, KorotinEgor commented on tasks/mpi/korotin_e_min_val_matrix/src/ops_mpi.cpp
> +#include <string>
fixed

2024-11-02 13:17 UTC, KorotinEgor commented on tasks/mpi/korotin_e_min_val_matrix/src/ops_mpi.cpp
> +  for (unsigned i = 0; i < taskData->inputs_count[0]; i++) {
fixed

2024-11-02 13:17 UTC, KorotinEgor commented on tasks/seq/korotin_e_min_val_matrix/src/ops_seq.cpp
> +  for (unsigned i = 0; i < taskData->inputs_count[0]; i++) {
fixed

2024-11-02 13:42 UTC, SergeyBoRss approved these changes

2024-11-02 13:58 UTC, IljarSmirnov approved these changes

2024-11-03 02:44 UTC, aobolensk requested changes

2024-11-03 02:44 UTC, aobolensk commented on tasks/mpi/korotin_e_min_val_matrix/src/ops_mpi.cpp
> +std::vector<double> korotin_e_min_val_matrix_mpi::getRandomMatrix(const unsigned rows, const unsigned columns,
Please, move test functions to the test module

2024-11-03 09:48 UTC, aobolensk approved these changes

2024-11-03 09:58 UTC, KorotinEgor commented on tasks/mpi/korotin_e_min_val_matrix/src/ops_mpi.cpp
> +std::vector<double> korotin_e_min_val_matrix_mpi::getRandomMatrix(const unsigned rows, const unsigned columns,
fixed

2024-11-04 00:59 UTC, merged