Козлова Екатерина. Задача 1. Вариант 26. Проверка лексикографической упорядоченности двух строк.
learning-process/ppc-2024-autumn pull request #101
Opened 2024-11-01 13:38 UTC by KatyaKozlova

### Описание последовательной задачи:
Последовательная версия задачи заключается в определении, упорядочены ли две строки в лексикографическом порядке. Проверяется каждая строка. Если в любой момент текущий символ больше следующего, строка считается неупорядоченной лексикографически. В результат записывается вектор из двух чисел, результатов проверки лексикографического порядка первой и второй строки соответственно. Если строка упорядочена записывается 1, не упорядочена - 0.
### Описание параллельной задачи:
Параллельная версия выполняет ту же задачу, но с использованием MPI для распределения вычислений между несколькими процессами. Входные строки передаются всем процессам, при этом главный процесс получает строки и отправляет их остальным процессам через broadcast. Каждый процесс получает часть символов строк и выполняет проверку их упорядоченности. Строки разделяются на подстроки в зависимости от количества процессов. Проверяется лексикографическая упорядоченность для подстрок. Главный процесс анализирует полученные результаты и определяет, отсортированы ли строки в целом.

2024-11-02 11:36 UTC, Gn4ik requested changes

2024-11-02 11:36 UTC, Gn4ik commented on tasks/mpi/kozlova_e_lexic_order/src/ops_mpi.cpp
> +#include <random>
why are you using this

2024-11-02 11:36 UTC, Gn4ik commented on tasks/seq/kozlova_e_lexic_order/src/ops_seq.cpp
> +std::vector<int> LexicographicallyOrdered(const std::string& str1, const std::string& str2) {
make this function private

2024-11-02 13:14 UTC, KatyaKozlova commented on tasks/mpi/kozlova_e_lexic_order/src/ops_mpi.cpp
> +#include <random>
fix

2024-11-02 13:14 UTC, KatyaKozlova commented on tasks/seq/kozlova_e_lexic_order/src/ops_seq.cpp
> +std::vector<int> LexicographicallyOrdered(const std::string& str1, const std::string& str2) {
fix

2024-11-02 13:29 UTC, Gn4ik approved these changes

2024-11-02 13:37 UTC, aobolensk approved these changes

2024-11-03 09:11 UTC, KoshkinMatvey approved these changes

2024-11-04 01:01 UTC, allnes requested changes

2024-11-04 01:01 UTC, allnes commented on tasks/mpi/kozlova_e_lexic_order/src/ops_mpi.cpp
> +  for (int i = 0; i < 2; i++) boost::mpi::broadcast(world, input_strings[i], 0);
please use mpi functions only in run()

2024-11-04 11:15 UTC, KatyaKozlova commented on tasks/mpi/kozlova_e_lexic_order/src/ops_mpi.cpp
> +  for (int i = 0; i < 2; i++) boost::mpi::broadcast(world, input_strings[i], 0);
fix

2024-11-04 21:42 UTC, allnes approved these changes

2024-11-04 21:42 UTC, merged