Петров Олег. Задача 1. Вариант 5. Нахождение числа чередований знаков значений соседних элементов вектора
learning-process/ppc-2024-autumn pull request #102
Opened 2024-11-01 14:10 UTC by ValeraDanger

2024-11-01 18:02 UTC, mateusxap commented on tasks/mpi/petrov_o_num_of_alternations_signs/func_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
remove the comment

2024-11-01 18:08 UTC, mateusxap commented on tasks/mpi/petrov_o_num_of_alternations_signs/src/ops_mpi.cpp
> +
input_size can be obtained on each process and without using broadcast

2024-11-01 18:08 UTC, mateusxap commented on tasks/mpi/petrov_o_num_of_alternations_signs/src/ops_mpi.cpp
> +    // boost::mpi::scatterv(world, chunk.data(), distribution, 0);
remove comment

2024-11-01 18:09 UTC, mateusxap commented on tasks/mpi/petrov_o_num_of_alternations_signs/src/ops_mpi.cpp
> +#include <algorithm>
remove unused includes

2024-11-01 18:11 UTC, mateusxap commented on tasks/mpi/petrov_o_num_of_alternations_signs/func_tests/main.cpp
> +TEST(Sequential, TestAlternations_Simple) {
add tests with random data

2024-11-01 18:43 UTC, ValeraDanger commented on tasks/mpi/petrov_o_num_of_alternations_signs/func_tests/main.cpp
> +TEST(Sequential, TestAlternations_Simple) {
done

2024-11-01 18:43 UTC, ValeraDanger commented on tasks/mpi/petrov_o_num_of_alternations_signs/src/ops_mpi.cpp
> +#include <algorithm>
done

2024-11-01 18:43 UTC, ValeraDanger commented on tasks/mpi/petrov_o_num_of_alternations_signs/src/ops_mpi.cpp
> +    // boost::mpi::scatterv(world, chunk.data(), distribution, 0);
done

2024-11-01 18:43 UTC, ValeraDanger commented on tasks/mpi/petrov_o_num_of_alternations_signs/func_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
done

2024-11-01 18:53 UTC, mateusxap requested changes

2024-11-01 18:59 UTC, ValeraDanger commented on tasks/seq/petrov_o_num_of_alternations_signs/func_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
done

2024-11-01 18:59 UTC, ValeraDanger commented on tasks/seq/petrov_o_num_of_alternations_signs/include/ops_seq.hpp
> +// Copyright 2023 Nesterov Alexander
done

2024-11-01 19:00 UTC, ValeraDanger commented on tasks/seq/petrov_o_num_of_alternations_signs/src/ops_seq.cpp
> +// Copyright 2024 Nesterov Alexander
done

2024-11-01 19:07 UTC, mateusxap approved these changes

2024-11-02 11:35 UTC, SergeyBoRss approved these changes
Good job, already reviewed, bugs fixed

2024-11-02 13:37 UTC, aobolensk requested changes

2024-11-02 14:52 UTC, ValeraDanger commented on tasks/mpi/petrov_o_num_of_alternations_signs/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, input_size, 0);  // Чтобы значение было доступно везде
Done

2024-11-02 18:06 UTC, ValeraDanger commented on tasks/mpi/petrov_o_num_of_alternations_signs/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, input_size, 0);  // Чтобы значение было доступно везде
done

2024-11-03 03:55 UTC, aobolensk approved these changes

2024-11-04 02:24 UTC, allnes requested changes

2024-11-04 09:03 UTC, ValeraDanger commented on tasks/seq/petrov_o_num_of_alternations_signs/include/ops_seq.hpp
> +using namespace std::chrono_literals;
Removed

2024-11-04 09:03 UTC, ValeraDanger commented on tasks/mpi/petrov_o_num_of_alternations_signs/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
Removed

2024-11-04 09:03 UTC, ValeraDanger commented on tasks/mpi/petrov_o_num_of_alternations_signs/src/ops_mpi.cpp
> +  return taskData->outputs_count[0] == 1;
Fixed

2024-11-05 00:42 UTC, aobolensk requested changes

2024-11-05 00:42 UTC, aobolensk commented on tasks/mpi/petrov_o_num_of_alternations_signs/func_tests/main.cpp
> +TEST(petrov_o_num_of_alternations_signs_seq, TestAlternations_AllPositive) {
I wonder why you've added seq tests here

2024-11-06 18:22 UTC, merged