Холин Кирилл. Задача 1. Вариант 8. Поиск наиболее отличающихся по значению соседних элементов вектора.
learning-process/ppc-2024-autumn pull request #103
Opened 2024-11-01 15:29 UTC by Kirius257

Описание алгоритмов
Последовательная программа:

Объявляются локальные переменные под хранение наибольшей разницы между соседними элементами вектора и текущий индекс элемента вектора, по которому можно вычислить наибольшую разницу.
Получаем итератор текущий(итератор начала),итератор после текущего и итератор после конца.
В цикле while обходим вектор, пока не дойдём до конца, и находим разницу по модулю между двумя соседними элементами, на которые указывают итератор после текущего и текущий итератор.
Результатом работы цикла будет индекс левого соседнего элемента и наибольшая разница по значению между двумя соседними элементами вектора
Параллельная программа

Отдаём вектор процессу с рангом 0 и вычисляем долю элементов для распределения остальным процессам,.
Применяем операцию MPI_Bcast, чтобы отослать вычисленную долю данных вектора процессам.
Используем коллективную операцию распределения различающихся данных MPI_Scatter для распределения всем процессам равных по размеру, но различных по элементам частей вектора в соответствующие буферы данных.
Каждый процесс посчитает, следуя алгоритму вычисления, приведённого ранее, максимальную разницу(назовём её максимальной дельтой) в своём подвекторе. и упакует результаты в соответствующие буферы данных.
Используем коллективную операцию MPI_Reduce и в качестве одного из её параметров выберем операцию MPI_MAX, которая найдёт максимум среди всех максимальных дельт, отправляемых процессами.
В качестве результата MPI_Reduce в соответствующей переменной будет храниться искомый результат задачи.

2024-11-01 16:51 UTC, kmichaelk commented
Do not cheat - you changed the input data so that the tests now pass without fixing the solution itself.
Rollback changes that modify test data and random vector generation.

2024-11-01 16:52 UTC, kmichaelk commented on tasks/mpi/kholin_k_vector_neighbor_diff_elems/func_tests/main.cpp
>      global_vec = std::vector<int>(count_size_vector);
Revert this changes

2024-11-01 16:53 UTC, kmichaelk requested changes
Rollback changes that modify test data and random vector generation.
Refer to https://github.com/learning-process/ppc-2024-autumn/pull/95#discussion_r1825765431

2024-11-01 17:01 UTC, Kirius257 commented
> Do not cheat - you changed the input data so that the tests now pass without fixing the solution itself.

Fixed! Sorry for the confusion! I had to change the data to test a different test functionality. Here is the corrected version

2024-11-01 17:11 UTC, kmichaelk commented
You still haven't rolled back the changed vector filling algorithm in tests and that's the only reason why tests started passing. That's not a solution.

2024-11-01 17:20 UTC, Kirius257 commented
> Rollback changes that modify test data and random vector generation.

All right. Could you please specify exactly what in which code sections you would like to see? I'm having trouble deciding.

2024-11-01 17:39 UTC, Kirius257 commented
> You still haven't rolled back the changed vector filling algorithm in tests and that's the only reason why tests started passing. That's not a solution.

Check, please. I changed how it was before.  Fixed?

2024-11-01 17:44 UTC, kmichaelk commented
Yes, now the error is reproducible again and you need to fix it

2024-11-01 22:50 UTC, Kirius257 commented
> Yes, now the error is reproducible again and you need to fix it

Fixed! I see what you mean. The maximum could be at the junction of data blocks that we share between processes. I changed some tests a bit to check that the problem is really over.

2024-11-01 23:10 UTC, kmichaelk approved these changes

2024-11-02 12:56 UTC, KolodkinGrigorii commented on tasks/mpi/kholin_k_vector_neighbor_diff_elems/include/ops_mpi.hpp
> +    // std::cout << "global vec is ";
Remove this comments

2024-11-02 12:59 UTC, KolodkinGrigorii commented on tasks/seq/kholin_k_vector_neighbor_diff_elems/include/ops_seq.hpp
> +class MostDiffNeighborElements : public ppc::core::Task {
Rename to TestTaskSequential

2024-11-02 13:00 UTC, kmichaelk commented on tasks/seq/kholin_k_vector_neighbor_diff_elems/include/ops_seq.hpp
> +class MostDiffNeighborElements : public ppc::core::Task {
This is not mandatory

2024-11-02 13:19 UTC, Kirius257 commented on tasks/seq/kholin_k_vector_neighbor_diff_elems/include/ops_seq.hpp
> +class MostDiffNeighborElements : public ppc::core::Task {
I agree with kmichaelk, but if you ask for it, I will correct it. Fixed

2024-11-02 13:20 UTC, Kirius257 commented on tasks/mpi/kholin_k_vector_neighbor_diff_elems/include/ops_mpi.hpp
> +    // std::cout << "global vec is ";
Yeah, apparently I didn't clean up all the comments from last time. Thanks for the comment! Fixed

2024-11-02 13:37 UTC, aobolensk requested changes

2024-11-02 13:37 UTC, aobolensk commented on tasks/mpi/kholin_k_vector_neighbor_diff_elems/include/ops_mpi.hpp
> +  MPI_Scatter(input_.data(), delta_n, mpi_type_elem, local_input_.data(), delta_n, mpi_type_elem, 0, MPI_COMM_WORLD);
Move everything related to MPI to ::run()

2024-11-02 14:03 UTC, KolodkinGrigorii approved these changes

2024-11-02 15:00 UTC, Kirius257 commented on tasks/mpi/kholin_k_vector_neighbor_diff_elems/include/ops_mpi.hpp
> +  MPI_Scatter(input_.data(), delta_n, mpi_type_elem, local_input_.data(), delta_n, mpi_type_elem, 0, MPI_COMM_WORLD);
Fixed! However, I left MPI_Comm_rank and MPI_Comm_size for data processing on the null process, as it is very important.

2024-11-03 03:57 UTC, aobolensk requested changes

2024-11-03 03:57 UTC, aobolensk commented on tasks/mpi/kholin_k_vector_neighbor_diff_elems/include/ops_mpi.hpp
> +    std::cout << "I'm proc 0" << "and my local_input data is ";
```suggestion
```

2024-11-03 03:57 UTC, aobolensk commented on tasks/mpi/kholin_k_vector_neighbor_diff_elems/include/ops_mpi.hpp
> +    std::cout << "I'm" << ProcRank << " proc " << "and my local_input data is ";
```suggestion
```

2024-11-03 03:57 UTC, aobolensk approved these changes

2024-11-04 02:26 UTC, allnes approved these changes

2024-11-04 02:26 UTC, merged