Смирнов Илья. Задача 1. Вариант 19. Интегрирование методом прямоугольников.
learning-process/ppc-2024-autumn pull request #104
Opened 2024-11-01 15:31 UTC by IljarSmirnov

seq:
Считается интеграл для функции f на отрезке [left, right]. 
Для этого отрезок разбивается на n прямоугольников, у каждого из них ищется длина.
Затем берется значение функции в точке середины прямоугольника и умножается на длину прямоугольника.
Полученное значение прибавляется к результирующей сумме.

mpi:
Потокам передаются границы отрезка и количество прямоугольников.
Общий отрезок интегрирования делится по количеству потоков: получаются границы self_left, self_right
Относительно этих границ каждый поток разбивает отрезок на n частей и вычисляет интеграл аналогично последовательному случаю
После расчетов результаты суммируются с помощью reduce

2024-11-02 10:06 UTC, SergeyBoRss commented on tasks/mpi/smirnov_i_integration_by_rectangles/func_tests/main.cpp
you need to add tests with a null pointer

2024-11-02 11:10 UTC, KorotinEgor commented on tasks/seq/smirnov_i_integration_by_rectangles/src/ops_seq.cpp
> +  }
You don't need to multiply everything by "len_of_rect" every time, you can multiply by "len_of_rect" after the loop ends

2024-11-02 12:55 UTC, IljarSmirnov commented on tasks/mpi/smirnov_i_integration_by_rectangles/include/ops_mpi.hpp
> +#include <string>
fixed

2024-11-02 12:55 UTC, IljarSmirnov commented on tasks/mpi/smirnov_i_integration_by_rectangles/src/ops_mpi.cpp
> +#include <string>
fixed

2024-11-02 12:55 UTC, IljarSmirnov commented on tasks/mpi/smirnov_i_integration_by_rectangles/func_tests/main.cpp
done

2024-11-02 12:55 UTC, IljarSmirnov commented on tasks/mpi/smirnov_i_integration_by_rectangles/src/ops_mpi.cpp
> +    return -1;
fixed

2024-11-02 12:56 UTC, IljarSmirnov commented on tasks/mpi/smirnov_i_integration_by_rectangles/src/ops_mpi.cpp
> +    }
fixed

2024-11-02 12:56 UTC, IljarSmirnov commented on tasks/mpi/smirnov_i_integration_by_rectangles/src/ops_mpi.cpp
> +    }
fixed

2024-11-02 12:56 UTC, IljarSmirnov commented on tasks/mpi/smirnov_i_integration_by_rectangles/src/ops_mpi.cpp
> +    return -1;
fixed

2024-11-02 12:56 UTC, IljarSmirnov commented on tasks/mpi/smirnov_i_integration_by_rectangles/src/ops_mpi.cpp
> +  }
fixed

2024-11-02 12:56 UTC, IljarSmirnov commented on tasks/seq/smirnov_i_integration_by_rectangles/src/ops_seq.cpp
> +    return -1;
fixed

2024-11-02 12:56 UTC, IljarSmirnov commented on tasks/seq/smirnov_i_integration_by_rectangles/src/ops_seq.cpp
> +  }
fixed

2024-11-02 14:54 UTC, KorotinEgor approved these changes

2024-11-02 15:27 UTC, SergeyBoRss approved these changes

2024-11-03 02:53 UTC, aobolensk requested changes

2024-11-03 02:53 UTC, aobolensk commented on tasks/mpi/smirnov_i_integration_by_rectangles/src/ops_mpi.cpp
> +  return true;
Move all data transfer to ::run()

2024-11-03 02:53 UTC, aobolensk commented on tasks/mpi/smirnov_i_integration_by_rectangles/src/ops_mpi.cpp
> +double smirnov_i_integration_by_rectangles::TestMPITaskSequential::seq_integrate_rect(double (*func)(double),
Why do you need seq_integrate_rect here ?

2024-11-03 09:48 UTC, IljarSmirnov commented on tasks/mpi/smirnov_i_integration_by_rectangles/src/ops_mpi.cpp
> +  return true;
fixed

2024-11-03 09:48 UTC, IljarSmirnov commented on tasks/mpi/smirnov_i_integration_by_rectangles/src/ops_mpi.cpp
> +double smirnov_i_integration_by_rectangles::TestMPITaskSequential::seq_integrate_rect(double (*func)(double),
fixed
The function was used in mpi func tests. However, its use in this context is not strictly necessary. So, calculations are left in sequential run().

2024-11-03 09:48 UTC, aobolensk approved these changes

2024-11-04 02:27 UTC, allnes approved these changes

2024-11-04 02:27 UTC, merged