Бессонов Егор. Задача 21. Интегрирование – метод Монте-Карло.
learning-process/ppc-2024-autumn pull request #108
Opened 2024-11-01 16:36 UTC by nCUXe

**SEQ:**
Метод _pre_processing()_ извлекает границы интегрирования _a_ и _b_, а также количество случайных точек _num_points_ из входных данных.
Интегрирование:
Метод _run()_ выполняет следующие действия:
- Инициализирует генератор случайных чисел.
- Генерирует num_points случайных значений x в диапазоне [a, b].
- Для каждого x вычисляет значение функции и суммирует результаты.
- Вычисляет итоговый результат интегрирования как произведение диапазона интегрирования (b - a) на среднее значение вычисленных функций.

**MPI**
Метод _run()_ выполняет следующие действия на каждом процессе:
- Определяет количество точек _num_points_for_process_, которое необходимо обработать текущему процессу, учитывая общее количество процессов и возможный остаток.
- Генерирует num_points_for_process случайных значений x в диапазоне [a, b].
- Вычисляет_ значение функции для каждого x и суммирует результаты в переменную _sum._
_Сбор результатов:_
- reduce() суммирует все результаты.
- В корневом процессе вычисляется итоговый результат интегрирования как (b - a) * (res / num_points)

2024-11-02 11:01 UTC, emilien-gus commented on tasks/mpi/bessonov_e_integration_monte_carlo/src/ops_mpi.cpp
> +#include <vector>
remove not necessary include

2024-11-02 11:02 UTC, emilien-gus commented on tasks/mpi/bessonov_e_integration_monte_carlo/src/ops_mpi.cpp
> +#include <vector>
also do it for all other files.

2024-11-02 12:32 UTC, nCUXe commented on tasks/mpi/bessonov_e_integration_monte_carlo/src/ops_mpi.cpp
> +#include <vector>
fixed

2024-11-02 13:22 UTC, emilien-gus approved these changes

2024-11-02 15:09 UTC, SergeyBoRss commented on tasks/mpi/bessonov_e_integration_monte_carlo/func_tests/main.cpp
Add tests with very small interval and very large, for example (0.1; 0.2) and (-60; 50).

2024-11-02 20:19 UTC, nCUXe commented on tasks/mpi/bessonov_e_integration_monte_carlo/func_tests/main.cpp
added

2024-11-02 20:46 UTC, SergeyBoRss approved these changes

2024-11-03 02:53 UTC, aobolensk requested changes

2024-11-03 02:53 UTC, aobolensk commented on tasks/mpi/bessonov_e_integration_monte_carlo/src/ops_mpi.cpp
> +  return true;
Please, move data transfer to ::run()

2024-11-03 09:51 UTC, aobolensk approved these changes

2024-11-04 02:29 UTC, allnes approved these changes

2024-11-04 02:29 UTC, merged