Шляков Максим. Задача 1. Вариант 17. Нахождение минимальных значений по строкам матрицы
learning-process/ppc-2024-autumn pull request #109
Opened 2024-11-01 20:24 UTC by maximchhek

Этапы последовательной части:
1.Подготовка структуры для матрицы и результата.
2.Заполнение матрицы.
3.Поиск минимумов в каждой строке с обновлением минимального значения.
3.Сохранение найденных значений в выходной массив.

Этапы MPI части:
1.Главный процесс загружает матрицу и распределяет строки между всеми процессами.
2.Каждый процесс выполняет поиск минимальных значений в своём наборе строк.
3.Все процессы отправляют свои результаты главному процессу.
4.Главный процесс собирает результаты и сохраняет их в конечный массив.

2024-11-02 09:45 UTC, SergeyBoRss commented on tasks/mpi/shlyakov_m_min_value_of_row/src/ops_mpi.cpp
> +  bool flag = true;
You can get rid of the variable

2024-11-02 09:45 UTC, SergeyBoRss commented on tasks/mpi/shlyakov_m_min_value_of_row/src/ops_mpi.cpp
> +#include <thread>
you can get rid of this import

2024-11-02 09:45 UTC, SergeyBoRss commented on tasks/mpi/shlyakov_m_min_value_of_row/src/ops_mpi.cpp
> +    row[std::rand() % sz_col] = INT_MIN;
You can use the newer std::random_device

2024-11-02 09:45 UTC, SergeyBoRss commented on tasks/seq/shlyakov_m_min_value_of_row/perf_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
Duplication

2024-11-02 09:45 UTC, SergeyBoRss commented on tasks/seq/shlyakov_m_min_value_of_row/src/ops_seq.cpp
> +#include <thread>
you can get rid of this import

2024-11-02 09:45 UTC, SergeyBoRss commented on tasks/seq/shlyakov_m_min_value_of_row/src/ops_seq.cpp
> +  bool flag = true;
you can get rid of the variable

2024-11-02 09:45 UTC, SergeyBoRss commented on tasks/seq/shlyakov_m_min_value_of_row/src/ops_seq.cpp
> +    row[std::rand() % sz_col] = INT_MIN;
You can use the newer std::random_device

2024-11-02 11:26 UTC, maximchhek commented on tasks/mpi/shlyakov_m_min_value_of_row/src/ops_mpi.cpp
> +  bool flag = true;
fixed

2024-11-02 11:26 UTC, maximchhek commented on tasks/mpi/shlyakov_m_min_value_of_row/src/ops_mpi.cpp
> +#include <thread>
fixed

2024-11-02 11:26 UTC, maximchhek commented on tasks/seq/shlyakov_m_min_value_of_row/perf_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
fixed

2024-11-02 11:26 UTC, maximchhek commented on tasks/seq/shlyakov_m_min_value_of_row/src/ops_seq.cpp
> +#include <thread>
fixed

2024-11-02 11:26 UTC, maximchhek commented on tasks/seq/shlyakov_m_min_value_of_row/src/ops_seq.cpp
> +  bool flag = true;
fixed

2024-11-02 11:50 UTC, SergeyBoRss approved these changes

2024-11-02 13:11 UTC, Svoloch2940194 commented on tasks/mpi/shlyakov_m_min_value_of_row/src/ops_mpi.cpp
> +  if (((!taskData->inputs.empty() && !taskData->outputs.empty()) &&
add check outputs_count[0] == inputs_count[0]

2024-11-02 13:12 UTC, Svoloch2940194 commented on tasks/seq/shlyakov_m_min_value_of_row/src/ops_seq.cpp
> +  if (((!taskData->inputs.empty() && !taskData->outputs.empty()) &&
add check outputs_count[0] == inputs_count[0]

2024-11-02 13:12 UTC, Svoloch2940194 commented on tasks/mpi/shlyakov_m_min_value_of_row/func_tests/main.cpp
> +
add test then outputs_count[0] != inputs_count[0]

2024-11-02 13:46 UTC, maximchhek commented on tasks/mpi/shlyakov_m_min_value_of_row/src/ops_mpi.cpp
> +  if (((!taskData->inputs.empty() && !taskData->outputs.empty()) &&
fixed

2024-11-02 13:46 UTC, maximchhek commented on tasks/seq/shlyakov_m_min_value_of_row/src/ops_seq.cpp
> +  if (((!taskData->inputs.empty() && !taskData->outputs.empty()) &&
fixed

2024-11-02 13:46 UTC, maximchhek commented on tasks/seq/shlyakov_m_min_value_of_row/func_tests/main.cpp
> +
fixed

2024-11-02 13:46 UTC, maximchhek commented on tasks/mpi/shlyakov_m_min_value_of_row/func_tests/main.cpp
> +
fixed

2024-11-02 14:59 UTC, Svoloch2940194 approved these changes

2024-11-03 03:18 UTC, aobolensk requested changes

2024-11-03 03:18 UTC, aobolensk commented on tasks/mpi/shlyakov_m_min_value_of_row/src/ops_mpi.cpp
> +  int ex = sz_row % world.size();
Move data transfer part to ::run() method

2024-11-03 03:18 UTC, aobolensk commented on tasks/seq/shlyakov_m_min_value_of_row/src/ops_seq.cpp
> +    row[std::rand() % sz_col] = INT_MIN;
Is this line needed?

2024-11-03 09:07 UTC, maximchhek commented on tasks/seq/shlyakov_m_min_value_of_row/src/ops_seq.cpp
> +    row[std::rand() % sz_col] = INT_MIN;
I forgot to add a random vector to the random matrix

Fixed

2024-11-03 09:51 UTC, aobolensk approved these changes

2024-11-03 09:53 UTC, Svoloch2940194 approved these changes

2024-11-04 02:30 UTC, merged