Крылов Михаил. Задача 1. Вариант 5. Нахождение числа чередований знаков значений соседних элементов вектора
learning-process/ppc-2024-autumn pull request #11
Opened 2024-10-14 03:48 UTC by kmichaelk

**Описание последовательной задачи.** Нахождение числа чередований знаков значений соседних элементов вектора происходит в один проход за линейное время, алгоритм проверки реализован как конечный автомат с двумя состояниями, соответствующими положительному и отрицательному знаковым диапазонам. В начале обработки текущего элемента состояние соответствует знаку предыдущего.

**Описание MPI задачи**. На элементарном уровне алгоритм аналогичен алгоритму, применяемой в последовательной задаче. Каждому процессу рассылаются равномерные объемы данных при помощи `scatterv` с выравниванием в случае, если общий объем данных не делится на количество процессов нацело. Для избавления от необходимости дополнительных проверок чисел на стыке в координирующем процессе после редуцирования частичных результатов, в каждый процесс, за исключением последнего, присылается еще и первый подлежащий обработке процессом следующего ранга элемент путем сдвига границы блока памяти.

2024-10-23 18:27 UTC, aobolensk requested changes

2024-10-23 18:27 UTC, aobolensk commented on tasks/seq/krylov_m_num_of_alternations_signs/func_tests/main.cpp
> +      std::make_tuple(129, std::vector<CountType>{0, /* . */}, 1),
Just curious, what do `/* . */` comments represent?

2024-10-23 18:27 UTC, aobolensk commented on tasks/mpi/krylov_m_num_of_alternations_signs/include/ops_mpi.hpp
> +
```suggestion
```

2024-10-23 18:27 UTC, aobolensk commented on tasks/seq/krylov_m_num_of_alternations_signs/include/ops_seq.hpp
> +
```suggestion
```

2024-10-23 18:32 UTC, kmichaelk commented on tasks/seq/krylov_m_num_of_alternations_signs/func_tests/main.cpp
> +      std::make_tuple(129, std::vector<CountType>{0, /* . */}, 1),
Visual differentiation of sign change

2024-10-24 12:12 UTC, aobolensk approved these changes

2024-10-25 18:04 UTC, allnes approved these changes

2024-10-25 18:04 UTC, merged

2024-10-25 18:29 UTC, allnes commented
@kmichaelk please remove sleep, insrease point when remove it

2024-10-25 18:57 UTC, kmichaelk commented
Missed it. #42