Савченко Максим. Задача 1. Вариант 14. Минимальное значение элементов матрицы.
learning-process/ppc-2024-autumn pull request #110
Opened 2024-11-01 21:20 UTC by MaxikGuy

**Описание последовательного решения:**
- Матрица хранится как одномерный вектор с общим числом элементов rows*columns.
- Выполняется последовательный обход элементов матрицы, в процессе которого находится минимальное значение.

**Описание решения с использованием MPI:**
- Матрица хранится как одномерный вектор с общим числом элементов rows*columns.
- Матрица делится на части, соответствующие количеству процессов.
- Каждый процесс получает свой сегмент данных и выполняет поиск минимального значения внутри него.
- Финальное минимальное значение вычисляется через операцию reduce, которая проходит по промежуточным результатам всех процессов и находит наименьшее из них.

2024-11-02 07:29 UTC, MaximChizhov requested changes
please make a case in the tests when one row and "m" columns are accepted, as well as when one column and "n" rows are accepted

2024-11-02 13:56 UTC, SingularityNN requested changes
there is no test covering the case where the matrix has 0 or fewer rows/columns

2024-11-02 13:56 UTC, SingularityNN commented on tasks/seq/savchenko_m_min_matrix/src/ops_seq_savchenko.cpp
> +using namespace std::chrono_literals;
Please delete this line of code, it is not needed here

2024-11-02 13:56 UTC, SingularityNN commented on tasks/mpi/savchenko_m_min_matrix/src/ops_mpi_savchenko.cpp
> +using namespace std::chrono_literals;
Please delete this line of code, it is not needed here

2024-11-03 06:23 UTC, MaximChizhov approved these changes

2024-11-03 09:50 UTC, aobolensk commented on tasks/mpi/savchenko_m_min_matrix/include/ops_mpi_savchenko.hpp
> +std::vector<int> getRandomMatrix(size_t rows, size_t columns, int min, int max);
Please, move test functions to the test module

2024-11-03 09:50 UTC, aobolensk commented on tasks/mpi/savchenko_m_min_matrix/src/ops_mpi_savchenko.cpp
> +
Please, move data transfer to ::run() function

2024-11-03 12:21 UTC, SingularityNN approved these changes

2024-11-03 14:16 UTC, MaxikGuy commented on tasks/mpi/savchenko_m_min_matrix/include/ops_mpi_savchenko.hpp
> +std::vector<int> getRandomMatrix(size_t rows, size_t columns, int min, int max);
done

2024-11-03 14:16 UTC, MaxikGuy commented on tasks/mpi/savchenko_m_min_matrix/src/ops_mpi_savchenko.cpp
> +
done

2024-11-03 14:20 UTC, aobolensk approved these changes

2024-11-04 02:31 UTC, allnes approved these changes

2024-11-04 02:31 UTC, merged