Васильев Сергей. Задача 1. Вариант 7. Нахождение наиболее близких соседних элементов вектора.
learning-process/ppc-2024-autumn pull request #111
Opened 2024-11-01 21:24 UTC by venn2713

### Последовательная реализация
- **Класс**: `FindClosestNeighborsSequential`
- **Описание**: Последовательная версия алгоритма находит минимальную разницу между соседними элементами вектора. 
- **Алгоритм**:
  - В методе `pre_processing` вектор входных данных инициализируется из `taskData`, задается начальное значение `min_diff_` как максимально возможное, а также начальные индексы `index1_` и `index2_` устанавливаются в `-1`.
  - В методе `run` осуществляется проход по всем парам соседних элементов, вычисляется разница, и, если она меньше текущей минимальной разницы, обновляются `min_diff_`, `index1_` и `index2_`.
  - Метод `post_processing` записывает результат (минимальная разница и индексы) в выходной буфер.
- **Результат**: Алгоритм возвращает минимальную разницу между соседними элементами и соответствующие индексы.

### MPI реализация
- **Класс**: `FindClosestNeighborsParallelMPI`
- **Описание**: Параллельная версия с использованием MPI распределяет вычисления между процессами для повышения производительности на больших объемах данных.
- **Алгоритм**:
  - **Распределение данных**: В `pre_processing` данные разбиваются между процессами. Главный процесс (ранг 0) делит вектор на подмассивы, добавляя элементы на границах подмассивов для корректного вычисления минимальных разниц между соседними элементами. Остальные процессы получают свои подмассивы с помощью MPI `send` и `recv`.
  - **Локальные вычисления**: В `run` каждый процесс вычисляет минимальную разницу для своего подмассива. Если разница между соседними элементами меньше текущего минимума, обновляются `min_diff_`, `index1_` и `index2_`.
  - **Сбор результатов**: После завершения локальных вычислений каждый процесс передает свой результат главному процессу (ранг 0) с помощью `boost::mpi::gather`. Главный процесс затем находит глобальный минимум среди всех локальных результатов.
  - **Запись результата**: В `post_processing` главный процесс записывает финальные значения `min_diff_`, `index1_`, и `index2_` в выходной буфер.
- **Используемые MPI-функции**:
  - `boost::mpi::broadcast` — для рассылки размера вектора всем процессам.
  - `boost::mpi::send` и `recv` — для отправки подмассивов процессам.
  - `boost::mpi::gather` — для сбора локальных минимальных значений на главном процессе.
- **Результат**: Главный процесс (ранг 0) получает минимальную разницу и индексы элементов с этой разницей по всему вектору.

2024-11-01 22:31 UTC, kmichaelk approved these changes

2024-11-03 10:40 UTC, tyurinm approved these changes

2024-11-03 10:45 UTC, korablev-vm approved these changes

2024-11-03 23:47 UTC, hasanyanovk approved these changes

2024-11-03 23:50 UTC, aobolensk requested changes

2024-11-03 23:50 UTC, aobolensk commented on tasks/mpi/vasilev_s_nearest_neighbor_elements/include/ops_mpi.hpp
> +std::pair<std::vector<int>, std::vector<int>> partitionArray(int amount, int num_partitions);
Please, move test functions to the test module

2024-11-03 23:50 UTC, aobolensk commented on tasks/mpi/vasilev_s_nearest_neighbor_elements/src/ops_mpi.cpp
> +    input_[i] = tmp_ptr[i];
Use std::copy

2024-11-03 23:50 UTC, aobolensk commented on tasks/mpi/vasilev_s_nearest_neighbor_elements/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, amount, 0);
Please move data transfer to the ::run() function

2024-11-03 23:50 UTC, aobolensk commented
Three approves above are invalidated, please request two more students review

2024-11-04 01:24 UTC, KorneevaEkaterina approved these changes

2024-11-04 01:32 UTC, ARBUZNIJ approved these changes

2024-11-04 01:32 UTC, ARBUZNIJ commented on tasks/seq/vasilev_s_nearest_neighbor_elements/src/ops_seq.cpp
> +  for (unsigned i = 0; i < taskData->inputs_count[0]; i++) {
It's better ti use here std::copy

2024-11-04 18:45 UTC, allnes approved these changes

2024-11-05 00:40 UTC, aobolensk approved these changes

2024-11-05 00:40 UTC, merged