Седова Ольга. Задача 1. Вариант 13. Максимальное значение элементов матрицы.
learning-process/ppc-2024-autumn pull request #112
Opened 2024-11-01 21:35 UTC by Sedova-Olga

Описание последовательного решения
Последовательное решение задачи поиска максимального элемента в матрице matrix размера rows x cols основано на прохождении по всем элементам матрицы и сравнении их с текущим максимальным значением.
Инициализация:
Начальное значение максимального элемента (max) устанавливается равным первому элементу матрицы (matrix[0]).
Итерация по элементам матрицы:
Проходим по всем элементам матрицы, используя вложенные циклы по строкам (rows) и столбцам (cols).
Внутри циклов сравниваем текущий элемент matrix[i][j] с max.
Если matrix[i][j] больше max, то max обновляется значением matrix[i][j].
Возврат результата:
После прохождения по всем элементам матрицы возвращаем значение max, которое содержит максимальное значение в матрице.

Описание параллельного решения:
Разделение данных: 
Входная матрица разбивается на равные части (с учетом остатка) между процессами. Каждый процесс получает свою часть данных.
Нахождение локального максимума: 
Каждый процесс находит максимальный элемент в своей части входных данных.
Сбор результатов: 
Используется коллективная операция MPI_Reduce с операцией MPI_MAX. Эта операция позволяет найти глобальный максимум из всех локальных максимумов, найденных на каждом процессе.
Запись результата: 
Процесс с рангом 0 получает глобальный максимум и записывает его в выходные данные.

2024-11-02 09:15 UTC, Sedova-Olga commented on tasks/mpi/sedova_o_max_of_vector_elements/src/ops_mpi.cpp
> +  MPI_Comm_size(MPI_COMM_WORLD, &size);
Fixed

2024-11-02 09:16 UTC, Sedova-Olga commented on tasks/mpi/sedova_o_max_of_vector_elements/src/ops_mpi.cpp
> +
Fixed

2024-11-02 09:21 UTC, Sedova-Olga commented on tasks/mpi/sedova_o_max_of_vector_elements/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
fixed

2024-11-02 09:22 UTC, Sedova-Olga commented on tasks/mpi/sedova_o_max_of_vector_elements/src/ops_mpi.cpp
> +  return (world.rank() != 0) || ((taskData->outputs_count[0] == 1) && (!taskData->inputs.empty()));
fixed

2024-11-02 12:09 UTC, m1likus commented
Пожалуйста, отлаживайся в своем репозитории и не нагружай и не клади машины гитхаба в учебном репозитории. Если упал workflow - его можно отменить

2024-11-02 12:09 UTC, ascannel commented
please stop littering actions, many builds fail because of thousands of your commits

2024-11-02 12:12 UTC, MatveyKurakin reviewed
I agree with the comments, stop littering the actions, I can't push the commit

2024-11-02 12:33 UTC, Sedova-Olga commented
остановила все процессы, спасибо

2024-11-02 18:44 UTC, m1likus commented on tasks/mpi/sedova_o_max_of_vector_elements/func_tests/main.cpp
> +    vladimirova_j_max_of_vector_elements_mpi::TestMPITaskParallel testMpiTaskParallel(taskDataPar);
Vladimirova?

2024-11-03 12:15 UTC, 0P4RY5H commented
# Duty plagiarism check reminder

After you were [caught plagiarizing](https://github.com/learning-process/ppc-2024-autumn/pull/112#discussion_r1826656314), **you closed this PR** and **opened a new one** - #143.

I came and reported plagiarism, after which you immediately, silently **closed your second PR**. After some time, probably hoping that no one else would come and no one would look into the old one, **you opened another one** - third in a row (!) - #146.

I came again, and you finally started looking for excuses - without answering the question about plagiarism, you started answering my question about reopening PR - supposedly so that the "system" (what system?) doesn't fall. You said that you are closing a PR to test locally (FYI, locally means on your computer, not in your fork). And that's right. **BUT, you see that workflows in your fork is red, WHY reopen the PR in this repository?** The only explanation is to hide traces of plagiarism.

Now that the plagiarism report in this PR has been drowned out by the flood of your useless commits, you reopen it.

## About the commits 

Ladies and gentlemen, look at the commits that @Sedova-Olga do - https://github.com/learning-process/ppc-2024-autumn/pull/112/commits/8d015c1cafcf385563649e14b6c2dd94770c4309 for example. All of your commits has the same weird name "Initial structure" and differ in that you remove and re-add the same lines/tests back and forth.

That means you don't even test it locally on your computer! I bet you don't even know how to launch an MPI program.

### After pushing a new commit, the workflow for the old one is not canceled - with your garbage commits you have clogged the entire queue, interfering with other students, including my long-lost friends.

You don't even understand what you're doing, you're trying to turn green by trial and error!

Damn, your commit was never green, you have more red than the USSR cities on May Day.

# I demand you to be punished for blatant plagiarism and abusing CI, not allowing other students to be tested

If you open a new PR, I will come to it too. Don't try to escape.

#### @allnes @aobolensk

2024-11-03 12:23 UTC, m1likus commented
> # Duty plagiarism check reminder
> After you were [caught plagiarizing](https://github.com/learning-process/ppc-2024-autumn/pull/112#discussion_r1826656314), **you closed this PR** and **opened a new one** - #143.
> 
> I came and reported plagiarism, after which you immediately, silently **closed your second PR**. After some time, probably hoping that no one else would come and no one would look into the old one, **you opened another one** - third in a row (!) - #146.
> 
> I came again, and you finally started looking for excuses - without answering the question about plagiarism, you started answering my question about reopening PR - supposedly so that the "system" (what system?) doesn't fall. You said that you are closing a PR to test locally (FYI, locally means on your computer, not in your fork). And that's right. **BUT, you see that workflows in your fork are red, WHY reopen the PR in this repository?** The only explanation is to hide traces of plagiarism.
> 
> Now that the plagiarism report in this PR has been drowned out by the flood of your useless commits, you reopen it.
> 
> ## About the commits
> Ladies and gentlemen, look at the commits that @Sedova-Olga do - [8d015c1](https://github.com/learning-process/ppc-2024-autumn/commit/8d015c1cafcf385563649e14b6c2dd94770c4309) for example. All of your commits has the same weird name "Initial structure" and differ in that you remove and re-add the same lines/tests back and forth.
> 
> That means you don't even test it locally on your computer! I bet you don't even know how to launch an MPI program.
> 
> ### After pushing a new commit, the workflow for the old one is not canceled - with your garbage commits you have clogged the entire queue, interfering with other students, including my long-lost friends.
> You don't even understand what you're doing, you're trying to turn green by trial and error!
> 
> Damn, your commit was never green, you have more red than the USSR cities on May Day.
> 
> # I demand you to be punished for blatant plagiarism and abusing CI, not allowing other students to be tested
> If you open a new PR, I will come to it too. Don't try to escape.
> 
> #### @allnes @aobolensk
> Plagiarism proof commit hash - [24555d0](https://github.com/learning-process/ppc-2024-autumn/commit/24555d089948c201c290b3cf06f2093be504048e)
> 
> Original code source - #70

Absolutely agreed.

2024-11-03 12:24 UTC, kmichaelk commented
A delightful investigation!

> You don't even understand what you're doing, you're trying to turn green by trial and error!

@Sedova-Olga, what did you want to achieve by https://github.com/learning-process/ppc-2024-autumn/pull/112/commits/0850d8c274b9e7e93de8e5b53fef906d4440368d?

You're literally don't understand what you're doing.

2024-11-03 12:37 UTC, m1likus commented
> Absolutely agreed.

I also have a couple of questions about naming variables, because I've already seen almost the same names when I reviewed a person

2024-11-03 12:45 UTC, Sedova-Olga commented
я делаю по примеру, грубить никому не хочу, общую систему actions я не забиваю, поэтому просьба отстать мягко говоря

2024-11-03 12:47 UTC, 0P4RY5H commented
> я делаю по примеру

Как говорится, русским языком - делаю по примеру чужой работы, да, все верно - это и называется плаигат.

> общую систему actions я не забиваю

Это утверждение не соответствует действительности.

2024-11-03 12:48 UTC, Sedova-Olga commented
и да, столбцы, колонки и матрицы в основном английском однозначны, я хочу спокойно доработать над задачей, без ваших ненужных комментариев

2024-11-03 12:49 UTC, 0P4RY5H commented
> без ваших ненужных комментариев

Вы уже дискредитированы, их больше и не требуется

2024-11-03 12:50 UTC, Sedova-Olga commented
при открытом пр все встают в очередь при коммитах, и идёт задержка по несколько часов

2024-11-03 12:55 UTC, kmichaelk commented
Вы делаете коммит на каждый чих, даже если очевидно, что не то, что тесты не пройдут - такой код в принципе не соберется. Это говорит о том, что локально - у себя на машине - вы его вообще не запускаете и не пробуете этого сделать.

Более того, если внимательно пройтись по списку коммитов, вы часто удаляете какие-то строки и возвращаете назад без изменений с интервалом в максимум два коммита.

Джобы, инициированные для "старых" коммитов не отменяются новыми автоматически, в моменте у вас было и по 5 активных джоб - вы забиваете очередь в буквальном смысле мусором, как и сказал @0P4RY5H.

2024-11-03 12:58 UTC, Sedova-Olga commented
я делаю по примеру Александра

2024-11-03 13:02 UTC, aobolensk commented
> # Duty plagiarism check reminder
> After you were [caught plagiarizing](https://github.com/learning-process/ppc-2024-autumn/pull/112#discussion_r1826656314), **you closed this PR** and **opened a new one** - #143.
> 
> I came and reported plagiarism, after which you immediately, silently **closed your second PR**. After some time, probably hoping that no one else would come and no one would look into the old one, **you opened another one** - third in a row (!) - #146.
> 
> I came again, and you finally started looking for excuses - without answering the question about plagiarism, you started answering my question about reopening PR - supposedly so that the "system" (what system?) doesn't fall. You said that you are closing a PR to test locally (FYI, locally means on your computer, not in your fork). And that's right. **BUT, you see that workflows in your fork are red, WHY reopen the PR in this repository?** The only explanation is to hide traces of plagiarism.
> 
> Now that the plagiarism report in this PR has been drowned out by the flood of your useless commits, you reopen it.
> 
> ## About the commits
> Ladies and gentlemen, look at the commits that @Sedova-Olga do - [8d015c1](https://github.com/learning-process/ppc-2024-autumn/commit/8d015c1cafcf385563649e14b6c2dd94770c4309) for example. All of your commits has the same weird name "Initial structure" and differ in that you remove and re-add the same lines/tests back and forth.
> 
> That means you don't even test it locally on your computer! I bet you don't even know how to launch an MPI program.
> 
> ### After pushing a new commit, the workflow for the old one is not canceled - with your garbage commits you have clogged the entire queue, interfering with other students, including my long-lost friends.
> You don't even understand what you're doing, you're trying to turn green by trial and error!
> 
> Damn, your commit was never green, you have more red than the USSR cities on May Day.
> 
> # I demand you to be punished for blatant plagiarism and abusing CI, not allowing other students to be tested
> If you open a new PR, I will come to it too. Don't try to escape. There's a better chance you'll switch to NixOS than I will stay behind.
> 
> #### @allnes @aobolensk
> Plagiarism proof commit hash - [24555d0](https://github.com/learning-process/ppc-2024-autumn/commit/24555d089948c201c290b3cf06f2093be504048e)
> 
> Original code source - #70

Plagiarism check will be performed in any case. Thank you for noticiing, we will check that

2024-11-03 13:02 UTC, aobolensk commented
> > я делаю по примеру
> 
> Как говорится, русским языком - делаю по примеру чужой работы, да, все верно - это и называется плаигат.
> 
> > общую систему actions я не забиваю
> 
> Это утверждение не соответствует действительности.

As for this part. Please note that for now this is not true. Her jobs have been cancelled: https://github.com/learning-process/ppc-2024-autumn/actions?query=actor%3ASedova-Olga

No active jobs as of now

2024-11-03 13:03 UTC, aobolensk commented
@DSolo03 Please behave and in external and internal discussions! Please avoid insults. Plagiarism version will be checked and your report will be considered

2024-11-03 13:06 UTC, 0P4RY5H commented
Being accused of ignorance is not an insult.

2024-11-03 13:07 UTC, DSolo03 commented
> @DSolo03

I have nothing to do with it O_o

2024-11-03 13:08 UTC, aobolensk commented
> > @DSolo03
> 
> I have nothing to do with it O_o

Oh, sorry, your nickname started with 0x... Mistype

2024-11-03 13:08 UTC, m1likus commented
> > > я делаю по примеру
> > 
> > 
> > Как говорится, русским языком - делаю по примеру чужой работы, да, все верно - это и называется плаигат.
> > > общую систему actions я не забиваю
> > 
> > 
> > Это утверждение не соответствует действительности.
> 
> As for this part. Please note that for now this is not true. Her jobs have been cancelled: https://github.com/learning-process/ppc-2024-autumn/actions?query=actor%3ASedova-Olga
> 
> No active jobs as of now

150 workflow runs... 50 test launches...

2024-11-03 13:09 UTC, 0P4RY5H requested changes

2024-11-03 13:09 UTC, 0P4RY5H commented on tasks/mpi/sedova_o_max_of_vector_elements/func_tests/main.cpp
Your tests do not check anything actually expect passing of validation

2024-11-03 13:09 UTC, allnes commented
> Being accused of ignorance is not an insult.

Please be more polite.
In any event, this correspondence in this requisition violates university protocols of behavior.

2024-11-03 13:13 UTC, aobolensk commented
> > > > я делаю по примеру
> > > 
> > > 
> > > Как говорится, русским языком - делаю по примеру чужой работы, да, все верно - это и называется плаигат.
> > > > общую систему actions я не забиваю
> > > 
> > > 
> > > Это утверждение не соответствует действительности.
> > 
> > 
> > As for this part. Please note that for now this is not true. Her jobs have been cancelled: https://github.com/learning-process/ppc-2024-autumn/actions?query=actor%3ASedova-Olga
> > No active jobs as of now
> 
> 150 workflow runs... 50 test launches...

That is true, we have cancelled all jobs today. I agree that this was too long, and it interrupted work of other students. But in any case, we should not bully other people. We have discussed that in the public chat, mitigated consequences as much as it is possible. Now we have longer queue, that is true, but you need to understand that submitting your patch for the first time on the day before deadline is kinda risky.

2024-11-03 13:22 UTC, kmichaelk commented
He definitely was wrong about going nuclear on that but he is right that it is hard to argue with the fact that doing a commit with a minimum diff every couple of minutes is wrong

2024-11-03 13:29 UTC, Sedova-Olga commented
они все были сняты по моей просьбе, когда я узнала об этом

2024-11-03 13:32 UTC, 0P4RY5H commented
> He definitely was wrong about going nuclear

It's easy to say that when your PR isn't hanging around waiting in the last days before a deadline.

2024-11-03 13:34 UTC, 0P4RY5H commented
> они все были сняты по моей просьбе, когда я узнала об этом

They still consumed some time, slowing down the queue, even if they *later* got cancelled - don't trigger them unless you're sure you'll get through them.

2024-11-03 13:43 UTC, kmichaelk commented
#163

2024-11-03 14:37 UTC, aobolensk commented
> > они все были сняты по моей просьбе, когда я узнала об этом
> 
> They still consumed some time, slowing down the queue, even if they _later_ got cancelled - don't trigger them unless you're sure you'll get through them.

In any case, the queue is almost empty as of now. Majority has passed already.

Let's stop this discussion

2024-11-03 14:38 UTC, aobolensk commented
> > He definitely was wrong about going nuclear
> 
> It's easy to say that when your PR isn't hanging around waiting in the last days before a deadline.

To be honest, in any case, it was a big risk that was taken by the students. Deadlines were prolonged by 1 week

2024-11-03 16:59 UTC, kmichaelk requested changes
Please, add parallel tests for larger matrices, specifically with one having 1 rows and 5 cols - it will not pass

2024-11-03 20:44 UTC, kmichaelk requested changes

2024-11-03 20:44 UTC, kmichaelk commented on tasks/mpi/sedova_o_max_of_vector_elements/func_tests/main.cpp
> +TEST(sedova_o_max_of_vector_elements_mpi, Test5) {
This test does not run - you perform only validation.

Fix your code to make it run and return correct answer without segfaulting.

2024-11-03 22:41 UTC, Sedova-Olga commented on tasks/mpi/sedova_o_max_of_vector_elements/func_tests/main.cpp
> +TEST(sedova_o_max_of_vector_elements_mpi, Test5) {
написала тесты на большие матрицы

2024-11-03 23:55 UTC, aobolensk requested changes

2024-11-03 23:55 UTC, aobolensk commented on tasks/seq/example/include/ops_seq.hpp
> +  explicit TestTaskSequential(std::shared_ptr<ppc::core::TaskData> taskData_) : Task(std::move(taskData_)) {};
Please, do not modify the example

2024-11-03 23:55 UTC, aobolensk commented on tasks/mpi/sedova_o_max_of_vector_elements/func_tests/main.cpp
> +TEST(sedova_o_max_of_vector_elements_mpi, Test1) { ASSERT_NO_THROW(generate_random_vector(10, 10)); }
Please add more tests for different matrix configurations

2024-11-04 00:10 UTC, kmichaelk requested changes
You did not add an actual test involving 5x1 matrix as I suggested, also `Test_1000_1000` is randomly failing.

Please, add a real 5x1 matrix test - it will no longer cause segfaults, but will fail randomly.

2024-11-04 03:17 UTC, Sedova-Olga commented on tasks/seq/example/include/ops_seq.hpp
> +  explicit TestTaskSequential(std::shared_ptr<ppc::core::TaskData> taskData_) : Task(std::move(taskData_)) {};
Sorry

2024-11-04 08:24 UTC, AnastasiaRezantseva approved these changes

2024-11-04 11:43 UTC, kmichaelk requested changes
Again, you still did not add the test I suggested to add.

Add a random test involving 5x1 matrix and it will fail randomly in 1 of 5 cases and will result in a red master.

**Your other tests involving large matrices also still fail randomly, but with lower reproduction rate - this should not be merged into master.**

Hint: add a test with this matrix specifically - 1 row, 5 cols: `{1,1,1,1,5}`. It will fail constantly.

The test with 5x1 matrix you've added is a dummy, you don't run it and do only validation & preprocessing.

2024-11-04 13:10 UTC, Sedova-Olga commented on tasks/mpi/sedova_o_max_of_vector_elements/func_tests/main.cpp
> +TEST(sedova_o_max_of_vector_elements_mpi, Test1) { ASSERT_NO_THROW(generate_random_vector(10, 10)); }
added

2024-11-04 18:07 UTC, VasenkovAA approved these changes

2024-11-04 18:41 UTC, allnes requested changes

2024-11-04 18:41 UTC, allnes commented on tasks/seq/sedova_o_max_of_vector_elements/src/ops_seq.cpp
> +using namespace std::chrono_literals;
for whar do you use it?

2024-11-05 23:45 UTC, aobolensk requested changes

2024-11-05 23:45 UTC, aobolensk commented on tasks/mpi/sedova_o_max_of_vector_elements/func_tests/main.cpp
> +std::vector<int> generate_random_vector(size_t size, size_t value) {
Please wrap it with namespace to avoid collision with different students

2024-11-05 23:45 UTC, aobolensk commented on tasks/mpi/sedova_o_max_of_vector_elements/perf_tests/main.cpp
> +std::vector<int> generate_random_vector(size_t size, size_t value) {
Same

2024-11-06 15:24 UTC, aobolensk approved these changes

2024-11-06 18:24 UTC, allnes approved these changes

2024-11-06 20:30 UTC, Astra-chan-desu commented
Validation in _mpi looks off, fix it

2024-11-06 20:36 UTC, VladimirSdobnov approved these changes

2024-11-06 20:36 UTC, VladimirSdobnov commented on tasks/seq/sedova_o_max_of_vector_elements/src/ops_seq.cpp
> +}
I think in the "pre_processing" function in "ops_mpi.cpp" and "ops_seq.cpp" it is better to replace references to the taskData field with variables

2024-11-06 20:38 UTC, VladimirSdobnov commented on tasks/seq/sedova_o_max_of_vector_elements/src/ops_seq.cpp
> +}
I think in the "pre_processing" function in "ops_mpi.cpp" and "ops_seq.cpp" it is better to replace references to the TaskData field with variables

2024-11-06 20:46 UTC, Sedova-Olga commented
@Astra-chan-desu fixed

2024-11-06 20:49 UTC, Astra-chan-desu approved these changes

2024-11-06 21:03 UTC, VladimirSdobnov approved these changes
All ok

2024-11-06 23:51 UTC, merged

2024-11-07 15:44 UTC, 0P4RY5H commented
> Revert - https://github.com/learning-process/ppc-2024-autumn/pull/248

I'm shocked, shocked, shocked I tell you!

![image](https://github.com/user-attachments/assets/f0e501ee-632e-47eb-a8c3-729f09235273)

Получается, таки можно с двумя несодержательными аппрувами влететь, даже если на ошибку указывают?

Слава богу я закончил этот курс год назад, но месяц назад меня вновь занесло в этот вновь созданный репозиторий - было очень весело, спасибо ребят!

2024-11-07 15:46 UTC, m1likus commented
@0P4RY5H погоди не уходи, там еще две задачи в будущем, будет еще веселее

2024-11-07 17:36 UTC, Sedova-Olga commented
Там просто надо обновиться до мастера, если ты закончил этот курс, то не лезь в наш год

2024-11-07 17:36 UTC, Sedova-Olga commented
И да, оставь свои комментарии при себе

2024-11-28 23:32 UTC, Sedova-Olga commented
@0P4RY5H сорри за эту ситуацию, была не права