Гусейнов Эмил. Задача 1. Вариант 26. Проверка лексикографической упорядоченности двух строк.
learning-process/ppc-2024-autumn pull request #114
Opened 2024-11-01 22:13 UTC by emilien-gus

Последовательное решение:
Проверяем символы с одинаковыми индексами в словах на неравенство. Если окажется, что i-ый символы не совпадают, то, в случае если символ в первом слове лексиграфически больше символа во втором слове, то первое слово больше, иначе - первое слово меньше. Мы движемся по словам с помощью цыкла, пока не достигнем конца наименьшего слова. Если находим несоответсвие в символе, то записывыем результат и выходим из цыкла. Если цикл пройден полностью, то возможно 3 варианта. Первый - слова одинаковы(длины слов равны), второй - первое слово является префиксом второго слова(первое слово меньше), третий - второе слово префикс первого(первое слово больше).

Паралельное решение:
Каждый поток получает свои отрезки слов, делают проверки в циклах, потом собираем отдельные результаты в массив, где соблюдается нумерация потоков. В этом массиве сохранены локальные результаты проверки каждого сегмента. Двигаясь по этому массив ищем локальные результаты, указывающие на отличия в сегменте. Если находим такой результат, то заканчиваем поиск и сохраняем рузультат. Если же все участки совпадают, то проверяем слова на, то является ли одно слово префиксом другого. Проверка на префикс делается с помощью сравнение длин слов.

2024-11-02 09:34 UTC, nCUXe commented
add TEST with empty string

2024-11-02 13:36 UTC, Tanya-Yasakova commented on tasks/seq/guseynov_e_check_lex_order_of_two_string/src/ops_seq.cpp
> +  for (size_t i = 0; i < std::min(input_[0].size(), input_[1].size()); i++) {
Remove length into a separate variable

2024-11-02 13:36 UTC, Tanya-Yasakova commented on tasks/mpi/guseynov_e_check_lex_order_of_two_string/src/ops_mpi.cpp
> +  for (size_t i = 0; i < std::min(input_[0].size(), input_[1].size()); i++) {
Remove length into a separate variable

2024-11-02 13:38 UTC, Tanya-Yasakova commented on tasks/mpi/guseynov_e_check_lex_order_of_two_string/include/ops_mpi.hpp
> +#include <boost/mpi/collectives.hpp>
Remove some

2024-11-02 13:38 UTC, Tanya-Yasakova commented on tasks/seq/guseynov_e_check_lex_order_of_two_string/src/ops_seq.cpp
> +#include <thread>
remove

2024-11-02 13:40 UTC, emilien-gus commented on tasks/seq/guseynov_e_check_lex_order_of_two_string/func_tests/main.cpp
fixed

2024-11-02 14:09 UTC, Tanya-Yasakova approved these changes

2024-11-02 14:10 UTC, Tanya-Yasakova approved these changes

2024-11-02 14:10 UTC, Tanya-Yasakova approved these changes

2024-11-02 14:11 UTC, Tanya-Yasakova approved these changes

2024-11-02 14:12 UTC, Tanya-Yasakova approved these changes

2024-11-02 14:28 UTC, nCUXe approved these changes

2024-11-03 03:21 UTC, aobolensk requested changes

2024-11-03 03:21 UTC, aobolensk commented on tasks/mpi/guseynov_e_check_lex_order_of_two_string/src/ops_mpi.cpp
> +  res_ = 0;
Please, move data transfer to ::run()

2024-11-03 03:21 UTC, aobolensk commented on tasks/mpi/guseynov_e_check_lex_order_of_two_string/func_tests/main.cpp
> +TEST(guseynov_e_check_lex_order_of_two_string_mpi, Test_empty_strings) {
Please, add random strings test

2024-11-03 22:50 UTC, emilien-gus commented on tasks/mpi/guseynov_e_check_lex_order_of_two_string/func_tests/main.cpp
> +TEST(guseynov_e_check_lex_order_of_two_string_mpi, Test_empty_strings) {
fixed

2024-11-03 23:55 UTC, aobolensk approved these changes

2024-11-04 02:33 UTC, allnes approved these changes

2024-11-04 02:33 UTC, merged