Ясакова Татьяна. Задача 1. Вариант 14. Минимальное значение элементов матрицы.
learning-process/ppc-2024-autumn pull request #115
Opened 2024-11-01 22:20 UTC by Tanya-Yasakova

Последовательное решение:
- последовательный перебор всех элементов матрицы

Паралельное решение:
- при считывании данных из taskData матрица преобразуется в развернутую
(объединенную в один вектор)
- развернутая матрица делится на сегменты по количеству процессов для обеспечения равномерного распределения данных
- каждый сегмент передается процессам, 
- каждый процесс находит минимум в своем сегменте данных
- reduce проходит по всем процессам и выбирает минимальный из
промежуточных результатов

2024-11-02 13:11 UTC, Tanya-Yasakova commented on tasks/mpi/yasakova_t_min_of_vector_elements/func_tests/main_yasakova.cpp
> +
add tests

2024-11-02 13:14 UTC, Tanya-Yasakova commented on tasks/mpi/yasakova_t_min_of_vector_elements/src/ops_mpi_yasakova.cpp
> +using namespace std::chrono_literals;
I removed

2024-11-02 14:06 UTC, emilien-gus commented on tasks/mpi/yasakova_t_min_of_vector_elements/include/ops_mpi_yasakova.hpp
> +#include <vector>
remove not necessary includes

2024-11-02 14:06 UTC, emilien-gus commented on tasks/mpi/yasakova_t_min_of_vector_elements/src/ops_mpi_yasakova.cpp
> +#include <vector>
remove not necessary includes

2024-11-02 14:06 UTC, emilien-gus commented on tasks/seq/yasakova_t_min_of_vector_elements/include/ops_seq_yasakova.hpp
> +#include <string>
you don't use strings

2024-11-02 15:13 UTC, Tanya-Yasakova commented on tasks/mpi/yasakova_t_min_of_vector_elements/include/ops_mpi_yasakova.hpp
> +#include <vector>
remove

2024-11-02 15:13 UTC, Tanya-Yasakova commented on tasks/mpi/yasakova_t_min_of_vector_elements/src/ops_mpi_yasakova.cpp
> +#include <vector>
remove

2024-11-02 15:13 UTC, Tanya-Yasakova commented on tasks/seq/yasakova_t_min_of_vector_elements/include/ops_seq_yasakova.hpp
> +#include <string>
remove

2024-11-02 16:38 UTC, emilien-gus approved these changes

2024-11-02 17:51 UTC, AnastasiaRezantseva commented on tasks/mpi/yasakova_t_min_of_vector_elements/src/ops_mpi_yasakova.cpp
> +std::vector<int> yasakova_t_min_of_vector_elements_mpi::RandomVector(int size, int minimum, int maximum) {
move methods RandomVector and RandomMatrix into tests,  they used only there

2024-11-02 20:34 UTC, AnastasiaRezantseva approved these changes

2024-11-03 03:22 UTC, aobolensk requested changes

2024-11-03 03:22 UTC, aobolensk commented on tasks/mpi/yasakova_t_min_of_vector_elements/src/ops_mpi_yasakova.cpp
> +  return true;
Please, move data transfer to ::run()

2024-11-03 10:08 UTC, Tanya-Yasakova commented on tasks/mpi/yasakova_t_min_of_vector_elements/src/ops_mpi_yasakova.cpp
> +  return true;
move data transfer to ::run()

2024-11-03 14:14 UTC, aobolensk approved these changes

2024-11-04 02:33 UTC, allnes approved these changes

2024-11-04 02:33 UTC, merged