Береснев Антон. Задача 1. Вариант 18. Нахождение минимальных значений по столбцам матрицы.
learning-process/ppc-2024-autumn pull request #116
Opened 2024-11-02 00:03 UTC by novi40k1

seq: ищу минимумы перебором

mpi: отдаю процессам равное количество столбцов, кроме основного (ему +остаток). Они находят минимумы для своих столбцов и отправляют в глобальный ответ.

2024-11-03 03:27 UTC, aobolensk requested changes

2024-11-03 03:27 UTC, aobolensk commented on tasks/mpi/beresnev_a_min_values_by_matrix_columns/include/ops_mpi.hpp
> +
Please, move this to the test module

2024-11-03 11:17 UTC, novi40k1 commented on tasks/mpi/beresnev_a_min_values_by_matrix_columns/include/ops_mpi.hpp
> +
corrected

2024-11-03 14:16 UTC, aobolensk commented on tasks/mpi/beresnev_a_min_values_by_matrix_columns/src/ops_mpi.cpp
> +  local_input_ = std::vector<int>(n_ * col_on_pr);
Please, move data transfer to ::run()

2024-11-03 14:58 UTC, novi40k1 commented on tasks/mpi/beresnev_a_min_values_by_matrix_columns/src/ops_mpi.cpp
> +  local_input_ = std::vector<int>(n_ * col_on_pr);
corrected

2024-11-03 23:57 UTC, aobolensk approved these changes

2024-11-04 02:35 UTC, allnes requested changes

2024-11-04 02:35 UTC, allnes commented on tasks/mpi/beresnev_a_min_values_by_matrix_columns/src/ops_mpi.cpp
> +bool beresnev_a_min_values_by_matrix_columns_mpi::TestMPITaskParallel::pre_processing() {
please use all mpi functions in run()

2024-11-04 16:29 UTC, novi40k1 commented on tasks/mpi/beresnev_a_min_values_by_matrix_columns/src/ops_mpi.cpp
> +bool beresnev_a_min_values_by_matrix_columns_mpi::TestMPITaskParallel::pre_processing() {
corrected

2024-11-04 20:34 UTC, Ivan-Lysov requested changes
Please remove unused sections of code

2024-11-04 20:34 UTC, Ivan-Lysov commented on tasks/mpi/beresnev_a_min_values_by_matrix_columns/include/ops_mpi.hpp
> +  std::string ops;
Please remove unused variable

2024-11-04 20:34 UTC, Ivan-Lysov commented on tasks/mpi/beresnev_a_min_values_by_matrix_columns/include/ops_mpi.hpp
> +#include <vector>
please remove unused lib

2024-11-04 21:12 UTC, novi40k1 commented on tasks/seq/beresnev_a_min_values_by_matrix_columns/src/ops_seq.cpp
> +using namespace std::chrono_literals;
all corrected

2024-11-04 21:41 UTC, Ivan-Lysov approved these changes

2024-11-04 21:43 UTC, allnes approved these changes

2024-11-05 12:42 UTC, Alexey2013 commented on tasks/mpi/beresnev_a_min_values_by_matrix_columns/src/ops_mpi.cpp
> +         taskData->inputs_count[0] == (uint32_t) reinterpret_cast<int*>(taskData->inputs[1])[0] *
Use static cast, it's safer

2024-11-05 12:42 UTC, Alexey2013 commented on tasks/seq/beresnev_a_min_values_by_matrix_columns/src/ops_seq.cpp
> +         taskData->inputs_count[0] == (uint32_t) reinterpret_cast<int*>(taskData->inputs[1])[0] *
Here too

2024-11-05 13:57 UTC, novi40k1 commented on tasks/seq/beresnev_a_min_values_by_matrix_columns/src/ops_seq.cpp
> +         taskData->inputs_count[0] == (uint32_t) reinterpret_cast<int*>(taskData->inputs[1])[0] *
all corrected

2024-11-05 14:02 UTC, Alexey2013 approved these changes

2024-11-06 00:16 UTC, aobolensk approved these changes

2024-11-06 00:17 UTC, merged