Хованский Дмитрий. Задача 1. Вариант 3. Максимальное значение элементов вектора.
learning-process/ppc-2024-autumn pull request #118
Opened 2024-11-02 00:39 UTC by Kvoks

Задача нахождения максимального элемента в векторе заключается в том, чтобы определить наибольшее значение среди элементов одномерного вектора целых чисел. Для корректного выполнения алгоритма входные данные должны содержать хотя бы один элемент, а результат должен быть представлен единственным числом.

Описание последовательной задачи:

1.Инициализация данных: Входной вектор инициализируется значениями из входных данных.

2.Поиск максимального элемента: Выполняется проход по вектору, начиная с первого элемента. Для каждого элемента сравнивается текущее максимальное значение с текущим элементом вектора. Если текущий элемент больше, он становится новым максимальным значением.

3.Обработка результата: После завершения прохода по вектору максимальное значение сохраняется и возвращается в выходные данные.

Описание MPI задачи:

1.Разделение данных: Процесс с рангом 0 делит входной вектор на блоки, равномерно распределяя их между всеми процессами. Каждый процесс получает свою часть вектора для обработки.

2.Вычисления: Каждый процесс обрабатывает свой блок данных, выполняя поиск максимального значения в пределах своего блока.

3.Сбор результатов: Все процессы возвращают свои частичные результаты (максимальные значения для своих блоков) процессу 0. Для объединения результатов используется операция reduce, которая находит общее максимальное значение.

4.Обработка результата: Процесс с рангом 0 собирает и возвращает итоговое максимальное значение как результат выполнения задачи.

2024-11-02 12:14 UTC, ChastovSlava approved these changes
"// Copyright 2023 Nesterov Alexander" was noticed in the files. It is recommended to replace or remove it.

2024-11-02 12:28 UTC, StroganovM approved these changes
replace the for loop with std::copy()
https://github.com/Kvoks/ppc-2024-autumn/blob/ac03f233481dfd44f74acd8cf14f82145fc20051/tasks/mpi/khovansky_d_max_of_vector_elements/src/ops_mpi.cpp#L27-L36

2024-11-02 15:06 UTC, ChastovSlava approved these changes
all fixed

2024-11-02 17:33 UTC, StroganovM reviewed
good code

2024-11-02 17:36 UTC, StroganovM approved these changes
all fixed

2024-11-03 03:31 UTC, aobolensk requested changes

2024-11-03 03:31 UTC, aobolensk commented on tasks/mpi/khovansky_d_max_of_vector_elements/include/ops_mpi.hpp
> +
Please, remove

2024-11-03 03:32 UTC, aobolensk requested changes

2024-11-03 03:32 UTC, aobolensk commented on tasks/mpi/khovansky_d_max_of_vector_elements/src/ops_mpi.cpp
> +  }
Please, move data transfer to ::run()

2024-11-03 09:52 UTC, aobolensk approved these changes

2024-11-03 09:54 UTC, Kvoks commented on tasks/mpi/khovansky_d_max_of_vector_elements/include/ops_mpi.hpp
> +
fixed

2024-11-03 09:54 UTC, Kvoks commented on tasks/mpi/khovansky_d_max_of_vector_elements/src/ops_mpi.cpp
> +  }
it was like that in the example, but I fixed it

2024-11-04 02:36 UTC, allnes approved these changes

2024-11-04 02:36 UTC, merged