Грудзин Константин. Задача 1. Вариант 7. Нахождение наиболее близких по значению соседних элементов вектора.
learning-process/ppc-2024-autumn pull request #126
Opened 2024-11-02 06:27 UTC by Konstantin-Grudzin

**Основная идея:**
Представим ответ в виде пары чисел - значения и самого индекса. Если мы по определению сравнения пар будем брать минимум, мы получим самый левый индекс с минимальным значением.

**Последовательная реализация:**
Мы проходимся по массиву и находим минимальный элемент среди пар "абсолютная разница соседних" и индексом.

**Реализация MPI:**
Мы разделяем наши массивы на несколько равных частей и отдаем каждому процессу свою часть массива.
Он вычисляет минимум и с помощью операции reduce передает эту информацию главному процессу. Т.к мы проверяем ещё и следующий элемент, каждому процессу добавляем по одному дополнительному элементу. Чтобы избежать выход за массивы, а также корректно вычислять ответ, передаем каждому потоку точку его старта и размер действительных данных.

2024-11-02 06:53 UTC, EgorDormidontov approved these changes

2024-11-02 07:06 UTC, Napkin-AI requested changes

2024-11-02 07:06 UTC, Napkin-AI commented on tasks/seq/grudzin_k_nearest_neighbor_elements/src/ops_seq.cpp
> +    res = std::min(res, {abs(input_[i] - input_[i + 1]), i});
implicit cast is bad practice

2024-11-02 07:10 UTC, Konstantin-Grudzin commented on tasks/seq/grudzin_k_nearest_neighbor_elements/src/ops_seq.cpp
> +    res = std::min(res, {abs(input_[i] - input_[i + 1]), i});
fixed

2024-11-02 07:29 UTC, Napkin-AI approved these changes

2024-11-02 11:40 UTC, kmichaelk requested changes

2024-11-02 11:40 UTC, kmichaelk commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/src/ops_mpi.cpp
> +  start = world.rank() * delta;
You're sending more data that you actually have and filling the gaps with zero values, using crutches later and reducing the performance - same suggestion applies: https://github.com/learning-process/ppc-2024-autumn/pull/77#discussion_r1823352852

2024-11-02 13:31 UTC, Konstantin-Grudzin commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/src/ops_mpi.cpp
> +  start = world.rank() * delta;
I don’t entirely agree that this is a problem, and here’s why:

1. In our lecture, we were told that data can (and sometimes even should) be distributed evenly.
2. We need to use additional specialized code to cover this case (if there are no more than 8 processes, we’ll be writing code for 7 cases).
3. The amount of 'extra memory' I’m using will equal 1-2 elements in the vector (allocating it takes roughly the same time as allocating memory within other processes and checking the processor for 'zero' vectors).
Based on this, I don’t see a need to change this implementation.

2024-11-02 13:31 UTC, Konstantin-Grudzin commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/src/ops_mpi.cpp
> +  start = world.rank() * delta;
In my local machine i don't see any major boost for modified realisation

2024-11-02 13:37 UTC, aobolensk approved these changes

2024-11-03 09:49 UTC, Konstantin-Grudzin commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/src/ops_mpi.cpp
> +  start = world.rank() * delta;
@aobolensk, sorry for bothering you, but requester don't reply me for long time

2024-11-03 12:55 UTC, Konstantin-Grudzin commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/src/ops_mpi.cpp
> +  start = world.rank() * delta;
@kmichaelk, sorry for mentioning, but you don't reply for a very long time, so maybe you miss my comments?

2024-11-03 16:06 UTC, kmichaelk commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/src/ops_mpi.cpp
> +  start = world.rank() * delta;
Missed it. I don't think it's too important, but it's more significant from the code quality, not from the performance view.

2024-11-03 16:09 UTC, kmichaelk approved these changes

2024-11-03 16:28 UTC, Konstantin-Grudzin commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/src/ops_mpi.cpp
> +  start = world.rank() * delta;
Code quality is very relative, for me code quality - it's simple read of code. Let's think of it like it's real sitution: if you launch task with more number processes than your usual amount of data size, it's your (like user) fault. My code will work correctly in an extreme situation - this is what I wanted. It is not my responsibility as a programmer to be response for the rational use of my code.

2024-11-03 16:41 UTC, kmichaelk commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/src/ops_mpi.cpp
> +  start = world.rank() * delta;
> Code quality is very relative, for me, code quality - it's simple read of code.

Code quality in terms of architecture, not in terms of literal code quality. 

Resizing the buffer to make it store extra data is quite dirty because you have to take it into the account later. You also consume and transmit extra data as I said previously - it is negligible in the current case with numbers, but if you want to process some giant atomic units, then this is a big problem.

Regarding the reading simplicity, you also confusing readers by hiding your real intentions by adding that extra data.

A much better and cleaner solution in this case would be to push the extra data into one of the processes, or use `scatterv` for variadic data distribution.

Also, the overhead of your solution may increase as the number of processes approaches inf, but that's theoretical only.

> if you launch task with more number processes than your usual amount of data size, it's your (like user) fault

That's not the case. You can imagine it as a some kind of a web-service backend that accepts any valid data and process it.

2024-11-04 02:36 UTC, allnes approved these changes

2024-11-04 02:36 UTC, merged