Куракин Матвей. Задача 1. Вариант 17. Нахождение минимальных значений по строкам матрицы.
learning-process/ppc-2024-autumn pull request #127
Opened 2024-11-02 07:24 UTC by MatveyKurakin

Описание последовательного алгоритма:
- Проходим по каждому элементу строки и определяем её минимум

Описание MPI алгоритма:
- Нулевой процесс распределяет данные среди всех процессов. Он делит матрицу, представленную как вектор, на части. Количество частей равно количеству процессов.
- На этапе run() каждый процесс сам определяет границы строк и находит их минимумы. Если строка разбита на несколько процессов, то каждый процесс ищет минимум на своем участке, а затем, с помощью reduce, результат собирается в 0 процессе.

2024-11-02 08:31 UTC, Alexey2013 commented on tasks/mpi/kurakin_m_min_values_by_rows_matrix/src/ops_mpi.cpp
> +    return *taskData->inputs[1] != 0 && *taskData->inputs[2] != 0 && *taskData->inputs[1] == taskData->outputs_count[0];
There is no check in the validation about how many elements have arrived

2024-11-02 08:32 UTC, ascannel requested changes

2024-11-02 08:56 UTC, MatveyKurakin commented on tasks/mpi/kurakin_m_min_values_by_rows_matrix/src/ops_mpi.cpp
> +    return *taskData->inputs[1] != 0 && *taskData->inputs[2] != 0 && *taskData->inputs[1] == taskData->outputs_count[0];
fixed

2024-11-02 08:56 UTC, MatveyKurakin commented on tasks/mpi/kurakin_m_min_values_by_rows_matrix/src/ops_mpi.cpp
> +  internal_order_test();
fixed

2024-11-02 09:03 UTC, Alexey2013 approved these changes

2024-11-02 09:14 UTC, ascannel approved these changes

2024-11-02 10:41 UTC, kmichaelk requested changes

2024-11-02 10:41 UTC, kmichaelk commented on tasks/mpi/kurakin_m_min_values_by_rows_matrix/func_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
Incomplete solution.

Supply test data with `count_rows = 5, size_rows = 1, global_mat = {5, 5, 5, 5, 5}`.

2024-11-02 12:16 UTC, MatveyKurakin commented on tasks/mpi/kurakin_m_min_values_by_rows_matrix/func_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
I added a test, found a bug and tried to fix it.

2024-11-02 12:49 UTC, kmichaelk commented on tasks/mpi/kurakin_m_min_values_by_rows_matrix/func_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
Seems like it's fixed now
Another problem you have: https://github.com/learning-process/ppc-2024-autumn/pull/77#discussion_r1823352852

2024-11-02 12:49 UTC, kmichaelk approved these changes

2024-11-02 13:37 UTC, aobolensk approved these changes

2024-11-04 02:37 UTC, allnes approved these changes

2024-11-04 02:38 UTC, merged