Лопатин Илья. Задача 1. Вариант 24. Подсчёт числа слов в строке.
learning-process/ppc-2024-autumn pull request #128
Opened 2024-11-02 07:27 UTC by ascannel

performance tests fixes

2024-11-02 07:36 UTC, MatveyKurakin commented on tasks/mpi/lopatin_i_count_words/src/countWordsMPI.cpp
> +  boost::mpi::broadcast(world, chunkSize, 0);
pre_processing() is needed to prepare data, for example, to convert rgb pixels to bgr.
MPI functions should be used in run()

2024-11-02 07:50 UTC, ascannel commented on tasks/mpi/lopatin_i_count_words/src/countWordsMPI.cpp
> +  boost::mpi::broadcast(world, chunkSize, 0);
i dont agree with you, i think this is still data preparation, as required by pre_processing function

need @aobolensk to resolve dispute

2024-11-02 08:25 UTC, Alexey2013 reviewed
Add a test to check words exactly 3 characters long. Situation when the number of characters is less than the number of processes.

2024-11-02 09:03 UTC, Alexey2013 approved these changes

2024-11-02 09:25 UTC, aobolensk commented on tasks/mpi/lopatin_i_count_words/src/countWordsMPI.cpp
> +  boost::mpi::broadcast(world, chunkSize, 0);
Matvey's comment is correct, pre-processing and post-processing is something that is agnostic towards technology we use. So if we run sequential code, pre-processing and post-processing should be the same, because this is not algorithm implementation detail. In contrast, broadcasting is something that is required specifically for running this on MPI: in case of sequential implementation or thread level parallelism, we will not require data broadcasting in such case. So it is fair to compare algorithms that are using different parallelism technologies with data transfer time included.

2024-11-02 11:02 UTC, kmichaelk requested changes

2024-11-02 11:02 UTC, kmichaelk commented on tasks/mpi/lopatin_i_count_words/func_tests/countWordsFuncTests.cpp
> +#include <gtest/gtest.h>
Incomplete solution.

Make a test with `abcd f` as input and run it on 4 processes.

2024-11-02 12:23 UTC, ascannel commented on tasks/mpi/lopatin_i_count_words/func_tests/countWordsFuncTests.cpp
> +#include <gtest/gtest.h>
don't you think this is too specific a situation? with a different number of processes or a slightly different input string everything works.

2024-11-02 12:26 UTC, kmichaelk commented on tasks/mpi/lopatin_i_count_words/func_tests/countWordsFuncTests.cpp
> +#include <gtest/gtest.h>
No. This is a perfectly valid input data and you should be able to process it correctly.

2024-11-02 12:29 UTC, ascannel commented on tasks/mpi/lopatin_i_count_words/func_tests/countWordsFuncTests.cpp
> +#include <gtest/gtest.h>
or could you tell me how to fix my code to avoid such errors

2024-11-02 12:57 UTC, MatveyKurakin approved these changes

2024-11-02 13:37 UTC, aobolensk approved these changes

2024-11-02 13:52 UTC, korablev-vm commented
I agree with @kmichaelk, you really should add more tests. Similarly, this is presented in works with vectors - empty, of 1,2,3... elements, etc. If the data is really being sent incorrectly, then it will take 10 minutes to solve this for you. A non-working master is a problem for 120 people, as it was yesterday.

2024-11-03 04:15 UTC, aobolensk commented
> I agree with @kmichaelk, you really should add more tests. Similarly, this is presented in works with vectors - empty, of 1,2,3... elements, etc. If the data is really being sent incorrectly, then it will take 10 minutes to solve this for you. A non-working master is a problem for 120 people, as it was yesterday.

I agree with Vladlen, consider adding more tests. Anyway, you're currently not impacted by 1st task deadline

2024-11-04 02:38 UTC, allnes approved these changes

2024-11-04 02:38 UTC, merged