Ковалев Константин. Задача 1. Вариант 6. Нахождение числа нарушений упорядоченности соседних элементов вектора.
learning-process/ppc-2024-autumn pull request #129
Opened 2024-11-02 08:26 UTC by ARBUZNIJ

Задача состоит в подсчёте количества нарушений упорядоченности числового вектора. (приведённая версия считает количество нарушений упорядоченности = 0 для упорядоченного по возрастанию вектора)

Последовательная реализация инициализирует вектор данными, а затем проходит по нему в цикле, сравнивая каждый элемент с последующим. Если один элемент больше следующего, увеличивается счётчик.

В параллельной версии вектор делится на части, и каждый процесс обрабатывает свою часть. Каждый из них подсчитывает нарушения в своей части локально, а затем все результаты собираются и суммируются на главном процессе.

2024-11-03 12:38 UTC, hasanyanovk commented on tasks/mpi/kovalev_k_num_of_orderly_violations/func_tests/main.cpp
> +}
don't use try/catch here and move `ASSERT_EQ` into `if` block

2024-11-03 12:46 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_num_of_orderly_violations/func_tests/main.cpp
> +}
It's too late to review - not even all tests have passed. try/catch here 4 debugging

2024-11-03 13:14 UTC, hasanyanovk commented on tasks/mpi/kovalev_k_num_of_orderly_violations/func_tests/main.cpp
> +}
You asked in a conversation, i'm answering

2024-11-03 14:26 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_num_of_orderly_violations/func_tests/main.cpp
> +}
Onece I've heard the story about an angel coming down right from the Sky and fixing any understandable and even incomprehensible bugs. I didn't even hope to meet him, but it happened. Thank you so much, dear sir.

2024-11-03 16:06 UTC, Applejack2004 requested changes

2024-11-03 16:06 UTC, Applejack2004 commented on tasks/mpi/kovalev_k_num_of_orderly_violations/perf_tests/main.cpp
> +    double max = 1000000;
One more  implicit cast.

2024-11-03 16:06 UTC, Applejack2004 commented on tasks/mpi/kovalev_k_num_of_orderly_violations/src/sourse.cpp
> +    // Initialization global_vector <T> with input data
Remove all extraneous comments from the code (except those within namespaces).

2024-11-03 16:06 UTC, Applejack2004 commented on tasks/seq/kovalev_k_num_of_orderly_violations/func_tests/main.cpp
> +  in[0] = 500 - alpha;
One more cast. 500 is int

2024-11-03 16:06 UTC, Applejack2004 commented on tasks/seq/kovalev_k_num_of_orderly_violations/perf_tests/main.cpp
> +  // Create data
Remove all extraneous comments from the code (except those within namespaces).

2024-11-03 16:06 UTC, Applejack2004 commented on tasks/seq/kovalev_k_num_of_orderly_violations/src/sourse.cpp
> +  // Init vector<T> of size n
Remove all extraneous comments from the code (except those within namespaces).

2024-11-03 17:12 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_num_of_orderly_violations/func_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
Done

2024-11-03 17:12 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_num_of_orderly_violations/include/header.hpp
> +// Copyright 2023 Nesterov Alexander
Done

2024-11-03 17:12 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_num_of_orderly_violations/perf_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
Done

2024-11-03 17:12 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_num_of_orderly_violations/src/sourse.cpp
> +// Copyright 2023 Nesterov Alexander
Done

2024-11-03 17:12 UTC, ARBUZNIJ commented on tasks/seq/kovalev_k_num_of_orderly_violations/func_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
Done

2024-11-03 17:13 UTC, ARBUZNIJ commented on tasks/seq/kovalev_k_num_of_orderly_violations/include/header.hpp
> +// Copyright 2023 Nesterov Alexander
Done

2024-11-03 17:13 UTC, ARBUZNIJ commented on tasks/seq/kovalev_k_num_of_orderly_violations/perf_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
Done

2024-11-03 17:13 UTC, ARBUZNIJ commented on tasks/seq/kovalev_k_num_of_orderly_violations/src/sourse.cpp
> +// Copyright 2024 Nesterov Alexander
Done

2024-11-03 17:13 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_num_of_orderly_violations/func_tests/main.cpp
> +  // Create data
As you wish

2024-11-03 17:13 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_num_of_orderly_violations/include/header.hpp
> +  size_t n = 0, l_res = 0, g_res = 0;  // counters initialisation
As you wish

2024-11-03 17:13 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_num_of_orderly_violations/perf_tests/main.cpp
> +  // Create TaskData
As you wish

2024-11-03 17:13 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_num_of_orderly_violations/src/sourse.cpp
> +  int scratter_length = n / size;  // minimum length to each process
As you wish

2024-11-03 17:13 UTC, ARBUZNIJ commented on tasks/seq/kovalev_k_num_of_orderly_violations/func_tests/main.cpp
> +  // Create TaskData
As you wish

2024-11-03 17:13 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_num_of_orderly_violations/func_tests/main.cpp
> +  size_t result = 0;
Doubtfully. It's better to use non-negative counter if negative is impossible by condition

2024-11-03 17:13 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_num_of_orderly_violations/func_tests/main.cpp
> +  std::vector<size_t> out(1, 0);
Doubtfully. It's better to use non-negative counter if negative is impossible by condition

2024-11-03 17:13 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_num_of_orderly_violations/perf_tests/main.cpp
> +#include <vector>
Fixed

2024-11-03 17:13 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_num_of_orderly_violations/perf_tests/main.cpp
> +    double max = 1000000;
Fixed

2024-11-03 17:13 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_num_of_orderly_violations/perf_tests/main.cpp
> +    double max = 1000000;
Fixed

2024-11-03 17:13 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_num_of_orderly_violations/src/sourse.cpp
> +    // Initialization global_vector <T> with input data
As you wish

2024-11-03 17:13 UTC, ARBUZNIJ commented on tasks/seq/kovalev_k_num_of_orderly_violations/func_tests/main.cpp
> +  in[0] = 500 - alpha;
Fixed

2024-11-03 17:13 UTC, ARBUZNIJ commented on tasks/seq/kovalev_k_num_of_orderly_violations/perf_tests/main.cpp
> +  // Create data
As you wish

2024-11-03 17:13 UTC, ARBUZNIJ commented on tasks/seq/kovalev_k_num_of_orderly_violations/src/sourse.cpp
> +  // Init vector<T> of size n
As you wish

2024-11-03 17:13 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_num_of_orderly_violations/func_tests/main.cpp
> +  for (size_t i = 0; i < length; i++) in[i] = i * 2;
Here I want to gain correctly ordered array, then in certain places I disturb the order. Randomizer is also used in another tests (too big to random them manually)

2024-11-03 17:13 UTC, ARBUZNIJ commented on tasks/seq/kovalev_k_num_of_orderly_violations/func_tests/main.cpp
> +  for (size_t i = 0; i < length; i++) in[i] = i * 2;
Here I want to gain correctly ordered array, then in certain places I disturb the order. Randomizer is also used in another tests (too big to random them manually). You meant old-fashioned randomising there? My fault.

2024-11-03 17:13 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_num_of_orderly_violations/func_tests/main.cpp
> +
Added

2024-11-03 17:22 UTC, Applejack2004 approved these changes

2024-11-03 17:23 UTC, isharamygina approved these changes

2024-11-04 00:03 UTC, aobolensk requested changes

2024-11-04 00:03 UTC, aobolensk commented on tasks/mpi/kovalev_k_num_of_orderly_violations/src/sourse.cpp
> +  boost::mpi::scatter(world, glob_v.data(), loc_v.data(), scratter_length, 0);
Please move data transfer to ::run()

2024-11-04 01:50 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_num_of_orderly_violations/func_tests/main.cpp
> +}
Randomized tests added

2024-11-04 01:51 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_num_of_orderly_violations/src/sourse.cpp
> +  boost::mpi::scatter(world, glob_v.data(), loc_v.data(), scratter_length, 0);
Done

2024-11-04 13:56 UTC, aobolensk approved these changes

2024-11-04 18:46 UTC, allnes approved these changes

2024-11-04 18:46 UTC, merged