Тюрин Михаил. Задача 1. Вариант 25. Подсчет числа предложений в строке.
learning-process/ppc-2024-autumn pull request #130
Opened 2024-11-02 08:31 UTC by tyurinm

Последовательная версия: На вход подается строка. Последовательный алгоритм проходит по строке и считает количество предложений, определяя их окончания по символам точки, восклицательного или вопросительного знака. Результатом является целое число — общее количество предложений в строке.

Параллельная версия (MPI): Строка равномерно делится между всеми процессами с использованием MPI broadcast. Каждый процесс подсчитывает предложения в своей части строки, а затем результаты объединяются с помощью MPI reduce. Итоговый результат — общее количество предложений.

2024-11-03 06:52 UTC, korablev-vm requested changes

2024-11-03 06:52 UTC, korablev-vm commented on tasks/mpi/tyurin_m_count_sentences_in_string/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, input_str_, 0);
It is necessary to transfer the MPI functionality to run()

2024-11-03 06:52 UTC, korablev-vm commented on tasks/seq/tyurin_m_count_sentences_in_string/perf_tests/main.cpp
> +  std::string input_str = "This is the first sentence. And this is the second! Finally, the third?";
Longer strings should be used in perf tests.

2024-11-03 10:35 UTC, venn2713 approved these changes

2024-11-03 10:43 UTC, korablev-vm approved these changes

2024-11-03 11:27 UTC, hasanyanovk approved these changes

2024-11-03 11:52 UTC, kmichaelk approved these changes

2024-11-04 00:06 UTC, aobolensk requested changes

2024-11-04 00:06 UTC, aobolensk commented on tasks/mpi/tyurin_m_count_sentences_in_string/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, input_str_, 0);
Do you transfer the whole string to all processes?

2024-11-04 18:52 UTC, allnes commented
@venn2713 @hasanyanovk @kmichaelk yours approvals will not be accepted

2024-11-04 19:02 UTC, allnes requested changes

2024-11-04 19:02 UTC, allnes commented on tasks/mpi/tyurin_m_count_sentences_in_string/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, total_length, 0);
please calculate segment_size one time and broadcast it

2024-11-04 20:10 UTC, kalyakinaa commented on tasks/seq/tyurin_m_count_sentences_in_string/perf_tests/main.cpp
> +const size_t count_strings = 1000;
I think, for the sake of the experiment's integrity, it would be logical to make the count_strings the same in seq/perf_tests and mpi/perf_tests, however, it is not necessary.

2024-11-04 20:14 UTC, tyurinm commented on tasks/seq/tyurin_m_count_sentences_in_string/perf_tests/main.cpp
> +const size_t count_strings = 1000;
fixed

2024-11-04 20:14 UTC, tyurinm commented on tasks/mpi/tyurin_m_count_sentences_in_string/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, total_length, 0);
fixed

2024-11-04 20:17 UTC, allnes approved these changes

2024-11-04 20:19 UTC, tyurinm commented on tasks/mpi/tyurin_m_count_sentences_in_string/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, input_str_, 0);
fixed

2024-11-04 20:21 UTC, kalyakinaa approved these changes

2024-11-05 00:39 UTC, aobolensk approved these changes

2024-11-05 00:39 UTC, merged