Одинцов Михаил. Вариант 27 Подсчет числа несовпадающих символов двух строк
learning-process/ppc-2024-autumn pull request #131
Opened 2024-11-02 09:32 UTC by odincovm

Последовательная версия: мы сортируем строки, так чтобы если длины не равны то длина 1 была больше, чем вторая. Затем проходимся по циклу и на каждой итерации сравниваем символы, если различны то к ответу прибавляем 2, если 2 строка закончилась мы идем дальше по 1 строке на каждой итерации прибавляя по единице

В параллельной версии алгоритм меняется тем, что мы уравниваем длины строк и разницу прибавляем к ответу. Затем разбиваем строки на несколько частей и по частям отдаем их потокам и проходим тот же алгоритм, что и а последовательной версии

2024-11-02 10:18 UTC, kmichaelk requested changes

2024-11-02 10:18 UTC, kmichaelk commented on tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/func_tests/main.cpp
> +  memcpy(str2, "udjgjeqpqgsgrejngjnrgjrj", 25);
```suggestion
  char str1[] = "lsjgjeqwqjfiijsnbhjfwfej";
  char str2[] = "udjgjeqpqgsgrejngjnrgjrj";
```

2024-11-02 10:18 UTC, kmichaelk commented on tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/func_tests/main.cpp
> +    delete[] str2;
```suggestion
```

2024-11-02 10:18 UTC, kmichaelk commented on tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/src/ops_mpi.cpp
> +    char* str2 = new char[loc_size + 1];
You leak this memory

2024-11-02 10:18 UTC, kmichaelk commented on tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/src/ops_mpi.cpp
> +  size_t size_2 = strlen(local_input[1]);
Use `std::string` or `std::vector<char>` as a container

2024-11-02 10:18 UTC, kmichaelk commented on tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/func_tests/main.cpp
> +  boost::mpi::communicator com;
You're using both `boost::mpi` and the original MPI C API simultaneously

2024-11-02 10:18 UTC, kmichaelk commented on tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/func_tests/main.cpp
> +  char str2[] = "qellowhwmvpt";
Prefer using `std::string` over this

2024-11-02 10:18 UTC, kmichaelk commented on tasks/seq/Odintsov_M_CountingMismatchedCharactersStr/src/ops_seq.cpp
> +  for (size_t i = 0; i < strlen(input[0]); i++) {
`strlen` in a loop is a poor practice as it is being invoked each iteration

2024-11-02 10:18 UTC, kmichaelk commented on tasks/seq/Odintsov_M_CountingMismatchedCharactersStr/func_tests/main.cpp
> +  memcpy(str2, "asdfg", 6);
Same

2024-11-02 10:18 UTC, kmichaelk commented on tasks/seq/Odintsov_M_CountingMismatchedCharactersStr/func_tests/main.cpp
> +  memcpy(str2, "qwert", 6);
Same

2024-11-02 10:18 UTC, kmichaelk commented on tasks/seq/Odintsov_M_CountingMismatchedCharactersStr/func_tests/main.cpp
> +  memcpy(str2, "qello", 6);
Same

2024-11-02 10:18 UTC, kmichaelk commented on tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/src/ops_mpi.cpp
> +    if (i < size_2) {
This can be rewritten more efficiently by iterating over both strings simultaneously

2024-11-02 10:21 UTC, kmichaelk commented on tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/func_tests/main.cpp
> +
Tests with randomly generated data is missing - you need to pass it to the parallel solution and compare the result with the sequential one

2024-11-02 12:01 UTC, kmichaelk commented on tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/func_tests/main.cpp
> +  boost::mpi::communicator com;
.

2024-11-02 14:48 UTC, kmichaelk commented on tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/src/ops_mpi.cpp
> +}
```suggestion
std::string Odintsov_M_CountingMismatchedCharactersStr_mpi::get_random_str(int sz) {
  const char characters[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  std::string str(sz);

  std::srand(std::time(nullptr));

  for (size_t i = 0; i < sz; ++i) {
    // Генерируем случайный индекс
    int index = std::rand() % (sizeof(characters) - 1);
    str[i] = characters[index];
  }

  return str;
}
```

2024-11-02 14:50 UTC, kmichaelk commented on tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/func_tests/main.cpp
> +  std::memcpy(str2, s2.c_str(), s2.size());
Use your `s1` and `s2` directly, no need in that
The underlying buffer can be accessed via `.data()`

2024-11-02 15:13 UTC, kmichaelk commented on tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/src/ops_mpi.cpp
> +    str2.resize(loc_size);
```suggestion
    std::string str1(loc_size);
    std::string str2(loc_size);
```

2024-11-02 18:15 UTC, kmichaelk approved these changes

2024-11-02 18:39 UTC, ermilovad requested changes
Add more tests with random string generation.

2024-11-02 19:36 UTC, kmichaelk commented on tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/src/ops_mpi.cpp
> +  com.barrier();
```suggestion
  reduce(com, loc_res, ans, std::plus(), 0);
```

2024-11-02 20:44 UTC, ermilovad approved these changes

2024-11-03 03:33 UTC, aobolensk requested changes

2024-11-03 03:33 UTC, aobolensk commented on tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/func_tests/main.cpp
> +
Please, check empty strings (one string empty, two strings empty, ...)

2024-11-03 13:52 UTC, aobolensk commented on tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/func_tests/main.cpp
> +
Why test for stings of the len 1 were removed?

2024-11-03 14:21 UTC, aobolensk approved these changes

2024-11-03 14:21 UTC, aobolensk commented on tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/include/ops_mpi.hpp
> +std::string get_random_str(size_t sz);
Please, move to the test module

2024-11-03 14:50 UTC, odincovm commented on tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/include/ops_mpi.hpp
> +std::string get_random_str(size_t sz);
what need to move? get_random_str?

2024-11-04 02:39 UTC, allnes approved these changes

2024-11-04 02:39 UTC, merged