Петров Артём. Задача 1. Вариант 7. Нахождение наиболее близких соседних элементов вектора.
learning-process/ppc-2024-autumn pull request #132
Opened 2024-11-02 09:49 UTC by ArtemPch

Последовательная версия:
В последовательной версии алгоритма мы сначала проходим по массиву и сравниваем каждую пару соседних элементов, чтобы определить минимальное расстояние между ними. Мы инициализируем переменные для хранения минимального расстояния и соответствующей пары элементов. На каждой итерации цикла мы вычисляем абсолютное расстояние между текущим элементом и следующим элементом. Если это расстояние меньше текущего минимального, мы обновляем минимальное расстояние и запоминаем пару элементов. После завершения цикла мы сохраняем найденную пару в выходные данные.

Параллельная версия:
В параллельной версии алгоритма мы сначала делим массив на несколько подмассивов в зависимости от количества доступных потоков. Каждый поток обрабатывает свой подмассив, выполняя тот же алгоритм, что и в последовательной версии, для нахождения ближайших соседей в своей части массива. После того как все потоки завершили свою работу, мы собираем результаты от каждого потока и сравниваем минимальные расстояния, чтобы определить глобальную минимальную пару. Если одна из частей массива меньше, чем остальные, это минимальное значение передается корневому процессу для дальнейшей обработки.

2024-11-03 09:41 UTC, LizochkaSpring commented on tasks/mpi/petrov_a_nearest_neighbor_elements/func_tests/main.cpp
> +    std::cout << reference_neighbors[1] << " " << global_neighbors[1] << std::endl;
remove unnecessary conclusions, and in other tests

2024-11-03 10:41 UTC, WladislawFilatew commented on tasks/mpi/petrov_a_nearest_neighbor_elements/src/ops_mpi.cpp
> +  }
The data transfer must be in the run method

2024-11-03 23:06 UTC, WladislawFilatew approved these changes

2024-11-03 23:10 UTC, LizochkaSpring approved these changes

2024-11-04 00:08 UTC, aobolensk requested changes

2024-11-04 00:08 UTC, aobolensk commented on tasks/mpi/petrov_a_nearest_neighbor_elements/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
Please move test functions to the test module

2024-11-04 00:08 UTC, aobolensk commented on tasks/mpi/petrov_a_nearest_neighbor_elements/src/ops_mpi.cpp
> +    input_[i] = tmp_ptr[i];
std::copy

2024-11-04 00:08 UTC, aobolensk commented on tasks/mpi/petrov_a_nearest_neighbor_elements/src/ops_mpi.cpp
> +      input_[i] = tmp_ptr[i];
std::copy

2024-11-04 00:08 UTC, aobolensk commented
Two approves above are not valid. Please ask for 2 more peer reviews

2024-11-04 10:54 UTC, Semyon1104 commented on tasks/mpi/petrov_a_nearest_neighbor_elements/src/ops_mpi.cpp
> +  int local_min_distance = std::numeric_limits<int>::max();
was it possible to declare a variable in hpp as local_input_?

2024-11-04 10:54 UTC, Semyon1104 commented on tasks/mpi/petrov_a_nearest_neighbor_elements/include/ops_mpi.hpp
> +  std::pair<int, int> closest_pair_;
it's cool that std::pair was used here

2024-11-04 10:54 UTC, Semyon1104 commented on tasks/mpi/petrov_a_nearest_neighbor_elements/func_tests/main.cpp
> +  }
in your seq implementation, the algorithm is looking for the first elements with the minimum identical difference, are you sure that the parallel version is also looking for the first occurrence of this difference? after all, the elements themselves may be different

2024-11-04 19:04 UTC, allnes requested changes

2024-11-04 19:04 UTC, allnes commented on tasks/seq/petrov_a_nearest_neighbor_elements/src/ops_seq.cpp
> +  }
please check it in validation()

2024-11-05 06:24 UTC, ArtemPch commented on tasks/mpi/petrov_a_nearest_neighbor_elements/include/ops_mpi.hpp
> +  std::pair<int, int> closest_pair_;
The use of std::pair<int, int> in the closest_pair_ variable is because the problem requires finding a pair of nearest neighbors (elements) in an array of numbers, and the std::pair<int, int> type is ideal for storing two related values ​​− in this case, two numbers that make up such a pair.

2024-11-05 06:25 UTC, ArtemPch commented on tasks/mpi/petrov_a_nearest_neighbor_elements/src/ops_mpi.cpp
> +  int local_min_distance = std::numeric_limits<int>::max();
Yes, you can declare the local_input_ variable in the header file (hpp)

2024-11-05 06:31 UTC, ArtemPch commented on tasks/mpi/petrov_a_nearest_neighbor_elements/func_tests/main.cpp
> +  }
In the sequential version, the algorithm goes through each element of the array one by one, and if the current difference between adjacent elements is less than the minimum found before, the algorithm updates the minimum distance and saves the pair of elements. In the parallel version, the data is divided between processes, and each process finds its own local minimum pair, after which a reduction operation is performed to find the global minimum pair.

2024-11-05 06:36 UTC, ArtemPch commented on tasks/mpi/petrov_a_nearest_neighbor_elements/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
Ready

2024-11-05 06:36 UTC, ArtemPch commented on tasks/seq/petrov_a_nearest_neighbor_elements/src/ops_seq.cpp
> +  }
Ready

2024-11-05 13:28 UTC, aobolensk approved these changes

2024-11-05 16:55 UTC, Semyon1104 approved these changes

2024-11-05 18:12 UTC, DZaytsev4 commented on tasks/mpi/petrov_a_nearest_neighbor_elements/src/ops_mpi.cpp
> +}
You can shorten this code

2024-11-05 18:17 UTC, ArtemPch commented on tasks/mpi/petrov_a_nearest_neighbor_elements/src/ops_mpi.cpp
> +}
ok, I'm right there

2024-11-05 18:21 UTC, ArtemPch commented on tasks/seq/petrov_a_nearest_neighbor_elements/src/ops_seq.cpp
> +  }
Check, please

2024-11-05 18:30 UTC, ArtemPch commented on tasks/mpi/petrov_a_nearest_neighbor_elements/src/ops_mpi.cpp
> +}
ready, in progress

2024-11-05 20:14 UTC, DZaytsev4 approved these changes

2024-11-06 18:25 UTC, allnes approved these changes

2024-11-06 18:25 UTC, merged