Цацын Александр. Задача 1. Вариант 9.  Скалярное произведение векторов.
learning-process/ppc-2024-autumn pull request #133
Opened 2024-11-02 11:49 UTC by KAPUSHA228

**Описание последовательной задачи**
Создаем 2 вектора определённого размера. В цикле перемножаем их координаты и сохраняем ответ в переменной.
**Описание параллельной задачи**
Создаём 2 вектора определённого размера. Определяем долю того что будут делать новые процессы (delta) и распределяем им соответствующую работу.

2024-11-04 11:22 UTC, petr1core commented on tasks/mpi/tsatsyn_a_vector_dot_product/perf_tests/main.cpp
> +std::vector<int> toGetRandomVector(int size) {
Незачем каждый раз писать функцию получения случайного вектора каждый раз перед её использованием в тестах. Следует добавить её прототип в пространство имён в include/ops_mpi.hpp и реализовать её в src/ops_mpi.cpp
*Опционально. Для генерации можно также использовать std::uniform_int_distribution.

2024-11-04 11:26 UTC, petr1core commented on tasks/mpi/tsatsyn_a_vector_dot_product/func_tests/main.cpp
> +// TEST(tsatsyn_a_vector_dot_product_mpi, Test_Negative_Validation) {
Убрать не важные комменты

2024-11-04 13:11 UTC, Egor1dzeN commented on tasks/mpi/tsatsyn_a_vector_dot_product/perf_tests/main.cpp
> +std::vector<int> toGetRandomVector(int size) {
Преподаватели пишут, что не нужно в ops_mpi.hpp оставлять эту функцию
![image](https://github.com/user-attachments/assets/d646c708-4efc-4a9c-a88d-9955ee889aa6)

2024-11-04 13:16 UTC, Egor1dzeN commented on tasks/mpi/tsatsyn_a_vector_dot_product/func_tests/main.cpp
> +  boost::mpi::communicator world;
добавь тесты с Sequential реализацией для большего покрытия тестами

2024-11-04 13:20 UTC, Egor1dzeN requested changes
add tests with Sequential implementation for more test coverage

2024-11-04 13:28 UTC, Egor1dzeN requested changes

2024-11-04 13:28 UTC, Egor1dzeN commented on tasks/mpi/tsatsyn_a_vector_dot_product/func_tests/main.cpp
> +TEST(tsatsyn_a_vector_dot_product_mpi, Test_Scalar_Positive_Value) {
add tests with Sequential implementation for more test coverage

2024-11-04 18:05 UTC, petr1core approved these changes
Finally!  🥇

2024-11-04 19:35 UTC, Egor1dzeN-learn approved these changes
I think the job is done right, you did a good job.

2024-11-04 20:47 UTC, Egor1dzeN approved these changes

2024-11-06 18:39 UTC, allnes approved these changes

2024-11-06 23:51 UTC, aobolensk approved these changes

2024-11-06 23:52 UTC, merged