Садиков Иван. Задача 1. Вариант 13. Сумма значений по столбцам матрицы
learning-process/ppc-2024-autumn pull request #135
Opened 2024-11-02 14:05 UTC by Sean0450

Описание последовательного решения:
Входные данные транспонируются и записываются в вектор matrix. С помощью цикла по количеству столбцов проходим по вектору matrix и при помощи std::accumulate получаем сумму по каждому столбцу. Данные записываются в вектор sum.

Описание параллельного решения:
Входные данные транспонируются и записываются в вектор matrix. Далее высчитываем delta - количество столбцов, выделяемое каждому процессу. Если количество столбцов не делится между процессами нацело, оставшиеся столбцы передаются последнему процессу. Каждый из процессов проходит по своим столбцам при помощи std::accumulate и записывает результат в вектор local_input. Позднее все векторы объединяются в один, который передается в ответ.

2024-11-02 19:44 UTC, korablev-vm requested changes

2024-11-02 19:44 UTC, korablev-vm commented on tasks/seq/sadikov_I_sum_values_by_columns_matrix/src/ops_seq.cpp
> +std::vector<double> sadikov_I_Sum_values_by_columns_matrix_seq::Randvector(size_t size) {
It is necessary to transfer this function to the test file, at the same time you will solve the problem with codecov

2024-11-02 20:22 UTC, korablev-vm commented on tasks/seq/sadikov_I_sum_values_by_columns_matrix/src/ops_seq.cpp
> +std::vector<double> sadikov_I_Sum_values_by_columns_matrix_seq::Randvector(size_t size) {
I looked again. My mistake, the function is no longer used even in tests. So you can just delete

2024-11-02 20:37 UTC, Sean0450 commented on tasks/seq/sadikov_I_sum_values_by_columns_matrix/src/ops_seq.cpp
> +std::vector<double> sadikov_I_Sum_values_by_columns_matrix_seq::Randvector(size_t size) {
Fixed, thank you

2024-11-02 20:54 UTC, korablev-vm approved these changes

2024-11-02 20:55 UTC, kmichaelk approved these changes

2024-11-04 00:12 UTC, aobolensk requested changes

2024-11-04 00:12 UTC, aobolensk commented on tasks/mpi/sadikov_I_sum_values_by_columns_matrix/include/ops_mpi.h
> +std::vector<int> getRandomVector(size_t size);
Please move test functions to the test module

2024-11-04 00:12 UTC, aobolensk commented on tasks/mpi/sadikov_I_sum_values_by_columns_matrix/func_tests/main.cpp
> +}
Please add tests for empty matrix, one row, one column, one element, etc.

2024-11-04 00:13 UTC, aobolensk commented
Please ask for 2 more peer reviews

2024-11-04 10:19 UTC, vitaliyvoroshilov commented on tasks/mpi/sadikov_I_sum_values_by_columns_matrix/func_tests/main.cpp
> +  boost::mpi::communicator world;
As I understand, this is a test for sequentional version, so there is no need to create a communicator here

2024-11-04 10:19 UTC, vitaliyvoroshilov commented on tasks/mpi/sadikov_I_sum_values_by_columns_matrix/func_tests/main.cpp
> +}
You missed ASSERT_EQ() function here

2024-11-04 10:23 UTC, vitaliyvoroshilov commented on tasks/mpi/sadikov_I_sum_values_by_columns_matrix/func_tests/main.cpp
> +  boost::mpi::communicator world;
Also of course no need to check world.rank()

2024-11-04 10:23 UTC, Sean0450 commented on tasks/mpi/sadikov_I_sum_values_by_columns_matrix/include/ops_mpi.h
> +std::vector<int> getRandomVector(size_t size);
Fixed

2024-11-04 10:24 UTC, Sean0450 commented on tasks/mpi/sadikov_I_sum_values_by_columns_matrix/func_tests/main.cpp
> +  boost::mpi::communicator world;
Fixed

2024-11-04 11:21 UTC, vitaliyvoroshilov approved these changes

2024-11-04 12:07 UTC, kalyakinaa approved these changes

2024-11-04 13:59 UTC, aobolensk commented on tasks/mpi/sadikov_I_sum_values_by_columns_matrix/func_tests/main.cpp
> +  boost::mpi::communicator world;
Not completely, definitions are still there

2024-11-04 14:00 UTC, aobolensk commented on tasks/mpi/sadikov_I_sum_values_by_columns_matrix/include/ops_mpi.h
> +std::vector<int> getRandomVector(size_t size);
Not completely, definitions are still there

2024-11-04 16:12 UTC, Sean0450 commented on tasks/mpi/sadikov_I_sum_values_by_columns_matrix/include/ops_mpi.h
> +std::vector<int> getRandomVector(size_t size);
My bad. Now fixed completely

2024-11-04 19:06 UTC, allnes requested changes

2024-11-04 19:06 UTC, allnes commented on tasks/mpi/sadikov_I_sum_values_by_columns_matrix/src/mpi_src.cpp
> +using namespace std::literals::chrono_literals;
for what do you use it?

2024-11-04 19:31 UTC, Sean0450 commented on tasks/mpi/sadikov_I_sum_values_by_columns_matrix/src/mpi_src.cpp
> +using namespace std::literals::chrono_literals;
Accidentally copied it. Fixed

2024-11-05 00:36 UTC, aobolensk approved these changes

2024-11-05 00:36 UTC, merged