Фролова Елизавета. Задача 1. Вариант 22. Подсчет числа буквенных символов в строке
learning-process/ppc-2024-autumn pull request #137
Opened 2024-11-02 15:02 UTC by ElizavetaFrolova

2024-11-02 15:20 UTC, ElizavetaFrolova commented
Описание последовательного решения (seq):
Входные данные записываются в строку input_. С помощью цикла выполняется обход строки при обнаружении буквенного символа счетчик увеличивается на единицу.
Выходные данные: число- количество буквенных символов в строке.
Описание параллельной задачи:
Входная строка равномерно делится между процессами. В случае если длина строки не кратна количеству процессов , оставшиеся символы добавляются к подстроке нулевого процесса. В каждом процессе происходит подсчет буквенных символов далее эти значения суммируются (при помощи reduce).

2024-11-03 14:25 UTC, MaximChizhov requested changes

2024-11-03 14:25 UTC, MaximChizhov commented on tasks/mpi/frolova_e_num_of_letters/src/ops_mpi.cpp
> +
delete line 8 and 11, you are not using these dependencies

2024-11-03 14:25 UTC, MaximChizhov commented on tasks/seq/frolova_e_num_of_letters/src/ops_seq.cpp
> +
delete line 4 and 6, you are not using these dependencies

2024-11-03 14:55 UTC, MaxikGuy commented on tasks/mpi/frolova_e_num_of_letters/include/ops_mpi.hpp
> +std::string GenStr(int n);
Please, move all GenStr() functions to test files

2024-11-03 16:59 UTC, MaxikGuy approved these changes

2024-11-03 18:51 UTC, MaximChizhov approved these changes

2024-11-04 00:20 UTC, aobolensk approved these changes

2024-11-04 02:40 UTC, allnes approved these changes

2024-11-04 02:40 UTC, merged