Кошкин Матвей. Задача 1. Вариант 9. Скалярное произведение векторов
learning-process/ppc-2024-autumn pull request #141
Opened 2024-11-02 19:06 UTC by KoshkinMatvey

Описание последовательной задачи: 
Задача состоит в том, чтобы выполнить поэлементное умножение двух векторов. Каждый элемент первого вектора умножается на соответствующий элемент второго вектора, и полученные произведения суммируются. В итоге получаем значение скалярного произведения
Описание MPI задачи:
Задан двумерный вектор целых чисел, содержащий два входных вектора. Эти векторы разделяются на равные части в соответствии с количеством процессов. Каждый процесс получает свою часть данных, где выполняется поэлементное умножение соответствующих элементов двух векторов. После этого произведения в каждом процессе суммируются, а результаты передаются на нулевой процесс, там они суммируются, для получения итогового произведения

2024-11-02 22:04 UTC, KoshkinMatvey commented on tasks/mpi/koshkin_m_scalar_product_of_vectors/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, count_processes_, 0);
fixed, ty bro

2024-11-03 09:32 UTC, Gn4ik requested changes

2024-11-03 09:32 UTC, Gn4ik commented on tasks/mpi/koshkin_m_scalar_product_of_vectors/func_tests/main.cpp
> +std::vector<int> generateRandomVector(int v_size) {
Add this function to your namespace, and implement it in a cpp file.

2024-11-03 09:32 UTC, Gn4ik commented on tasks/seq/koshkin_m_scalar_product_of_vectors/func_tests/main.cpp
> +std::vector<int> generateRandomVector(int v_size) {
also in this tests

2024-11-03 10:11 UTC, KoshkinMatvey commented on tasks/mpi/koshkin_m_scalar_product_of_vectors/func_tests/main.cpp
> +std::vector<int> generateRandomVector(int v_size) {
fixed

2024-11-03 10:12 UTC, KoshkinMatvey commented on tasks/seq/koshkin_m_scalar_product_of_vectors/func_tests/main.cpp
> +std::vector<int> generateRandomVector(int v_size) {
fixed

2024-11-03 10:19 UTC, Gn4ik approved these changes

2024-11-03 13:24 UTC, kmichaelk approved these changes

2024-11-04 14:11 UTC, aobolensk requested changes

2024-11-04 14:11 UTC, aobolensk commented on tasks/mpi/koshkin_m_scalar_product_of_vectors/include/ops_mpi.hpp
> +int calculateDotProduct(const std::vector<int>& vec_1, const std::vector<int>& vec_2);
Please, move test functions to the test module

2024-11-04 14:11 UTC, aobolensk commented on tasks/mpi/koshkin_m_scalar_product_of_vectors/func_tests/main.cpp
> +}
These two tests do not really test MPI parallelized part

2024-11-04 14:11 UTC, aobolensk commented on tasks/mpi/koshkin_m_scalar_product_of_vectors/func_tests/main.cpp
> +
Please, add empty vector test (you have them in seq run)

2024-11-04 19:08 UTC, allnes requested changes

2024-11-04 19:08 UTC, allnes commented on tasks/mpi/koshkin_m_scalar_product_of_vectors/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
what do you use it for?

2024-11-04 20:10 UTC, allnes approved these changes

2024-11-04 20:17 UTC, KoshkinMatvey commented on tasks/mpi/koshkin_m_scalar_product_of_vectors/include/ops_mpi.hpp
> +int calculateDotProduct(const std::vector<int>& vec_1, const std::vector<int>& vec_2);
fixed

2024-11-04 20:18 UTC, KoshkinMatvey commented on tasks/mpi/koshkin_m_scalar_product_of_vectors/func_tests/main.cpp
> +}
fixed

2024-11-04 20:18 UTC, KoshkinMatvey commented on tasks/mpi/koshkin_m_scalar_product_of_vectors/func_tests/main.cpp
> +
fixed

2024-11-05 00:33 UTC, aobolensk approved these changes

2024-11-05 00:33 UTC, merged