Ануфриев Даниил. Задача 1. Вариант 3. Максимальное значение элементов вектора.
learning-process/ppc-2024-autumn pull request #142
Opened 2024-11-02 19:07 UTC by sk1er52

seq: Итерация по элементам вектора и сравнение с максимальным элементом в данный момент.
mpi: 
Код параллельно находит максимальный элемент вектора, распределяя его по MPI процессам. scatterv раздает части вектора, каждый процесс находит свой локальный максимум, а reduce определяет глобальный максимум на процессе 0, который затем записывается в выходные данные.

2024-11-02 19:15 UTC, mateusxap requested changes

2024-11-02 19:15 UTC, mateusxap commented on tasks/seq/anufriev_d_max_of_vector_elements/func_tests/main_anufriev.cpp
> +TEST(anufriev_d_max_of_vector_elements, regularVector) {
please add test with random vector in seq test

2024-11-02 19:30 UTC, sk1er52 commented on tasks/seq/anufriev_d_max_of_vector_elements/func_tests/main_anufriev.cpp
> +TEST(anufriev_d_max_of_vector_elements, regularVector) {
fixed

2024-11-02 20:58 UTC, mateusxap approved these changes
great job!

2024-11-03 11:02 UTC, Chiks37 approved these changes

2024-11-04 19:10 UTC, allnes approved these changes

2024-11-04 19:10 UTC, merged