Сидорина Полина. Задача 1. Вариант 26. Проверка лексикографической упорядоченности двух строк.
learning-process/ppc-2024-autumn pull request #145
Opened 2024-11-02 20:58 UTC by PolinaSidorina

Последовательная задача:
Сравнивается по два элемента каждой строки последовательно до того, пока не найдутся первые два разных символа. Затем определяется, какой из этих символов больше, и сравниваются строки целиком. Если первая строка больше - выводится 1, если вторая - 0.

Параллельная задача:
Каждая из двух строк делится на меньшие строки одинакового размера, количество таких строк зависит от числа процессов. Соответственно каждая строка отправляется в свой процесс, где происходит сравнение элементов по алгоритму последовательной задачи. На выходе процесса 0 - вторая строка больше, 1 - первая строка больше, 2 - строки одинаковые. Если процесс закончился не с выходом 2, то результат записывается как окончательный и сравнение заканчивается.

2024-11-03 17:37 UTC, Sean0450 approved these changes

2024-11-04 19:13 UTC, allnes commented on tasks/mpi/sidorina_p_check_lexicographic_order/src/ops_mpi.cpp
> +bool sidorina_p_check_lexicographic_order_mpi::TestMPITaskParallel::pre_processing() {
please use mpi functionality in run()

2024-11-05 13:31 UTC, aobolensk requested changes

2024-11-05 13:31 UTC, aobolensk commented on tasks/mpi/sidorina_p_check_lexicographic_order/func_tests/main.cpp
> +  std::vector<std::vector<char>> str_ = {{'e', 'f', 'g', 'z'}, {'e', 'f', 'g', 'p'}};
All tests are using string of the same length, no tests for corner cases

2024-11-06 15:26 UTC, aobolensk approved these changes

2024-11-06 18:26 UTC, allnes approved these changes

2024-11-06 18:26 UTC, merged