Алпутов Иван. Задача 1. Вариант 8. Нахождение наиболее отличающихся по значению соседних элементов вектора.
learning-process/ppc-2024-autumn pull request #147
Opened 2024-11-02 22:17 UTC by Applejack2004

Последовательный алгоритм поиска пары элементов с максимальной разницей
Алгоритм последовательно перебирает все соседние пары элементов вектора, вычисляя абсолютную разницу между ними и отслеживая максимальную найденную разницу и соответствующую пару элементов. В результате возвращается пара элементов с наибольшей разницей по модулю.

Параллельный (MPI) алгоритм поиска пары элементов с максимальной разницей
Входной вектор распределяется между процессами MPI с помощью MPI_Scatterv. Каждый процесс находит пару соседних элементов с максимальной разницей в своей части вектора, а также проверяет разницу на границах с соседними процессами, обмениваясь граничными элементами (MPI_Send, MPI_Recv). С помощью MPI_Reduce и пользовательской операции сравнения определяется глобальная максимальная разница. MPI_Broadcast используется для синхронизации размеров подзадач между процессами. В результате главный процесс возвращает пару элементов с наибольшей разницей по модулю во всем векторе.

2024-11-04 21:10 UTC, VladislavPoroshin approved these changes

2024-11-04 21:51 UTC, VladislavPoroshin commented on tasks/mpi/alputov_i_most_different_neighbor_elements/func_tests/main.cpp
> +TEST(alputov_i_most_different_neighbor_elements_mpi, Test_0) {
Please make the names of the tests so that they reflect the essence of the test a little. (For example, if you use random generation, reflect this in the name: Test_rand_vector_size_ans)

2024-11-04 21:53 UTC, VladislavPoroshin commented on tasks/mpi/alputov_i_most_different_neighbor_elements/func_tests/main.cpp
> +TEST(alputov_i_most_different_neighbor_elements_mpi, Test_0) {
Please make the names of the tests so that they reflect the essence of the test a little. (For example, if you use random generation, reflect this in the name: Test_rand_vector_size_ans)

2024-11-04 21:56 UTC, VladislavPoroshin requested changes
Please make the names of the tests so that they reflect the essence of the test a little. (For example, if you use random generation, reflect this in the name: Test_rand_vector_size_ans)

2024-11-04 22:22 UTC, Applejack2004 commented on tasks/mpi/alputov_i_most_different_neighbor_elements/func_tests/main.cpp
> +TEST(alputov_i_most_different_neighbor_elements_mpi, Test_0) {
fixed

2024-11-04 22:31 UTC, VladislavPoroshin approved these changes

2024-11-05 13:33 UTC, aobolensk requested changes

2024-11-05 13:33 UTC, aobolensk commented on tasks/mpi/alputov_i_most_different_neighbor_elements/func_tests/main.cpp
> +TEST(alputov_i_most_different_neighbor_elements_mpi, EmptyInput_ReturnsFalse) {
Please, add non-random tests as well including ones that explicitly cover some cases (all equal elements, ...)

2024-11-05 16:24 UTC, ValeraDanger commented on tasks/seq/alputov_i_most_different_neighbor_elements/src/ops_seq.cpp
> +using namespace std::chrono_literals;
can be removed

2024-11-05 16:24 UTC, ValeraDanger commented on tasks/mpi/alputov_i_most_different_neighbor_elements/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
can be removed

2024-11-05 16:24 UTC, ValeraDanger commented on tasks/mpi/alputov_i_most_different_neighbor_elements/src/ops_mpi.cpp
> +#include <thread>
unused include

2024-11-05 16:24 UTC, ValeraDanger commented on tasks/seq/alputov_i_most_different_neighbor_elements/src/ops_seq.cpp
> +#include <thread>
unused include

2024-11-05 16:24 UTC, ValeraDanger commented on tasks/seq/alputov_i_most_different_neighbor_elements/func_tests/main.cpp
> +  std::cout << in[0] << " " << in[1] << std::endl;
Debug info, I suppose. Can be removed

2024-11-05 18:26 UTC, Applejack2004 commented on tasks/seq/alputov_i_most_different_neighbor_elements/func_tests/main.cpp
> +  std::cout << in[0] << " " << in[1] << std::endl;
fixed

2024-11-05 18:26 UTC, Applejack2004 commented on tasks/seq/alputov_i_most_different_neighbor_elements/src/ops_seq.cpp
> +#include <thread>
fixed

2024-11-05 18:26 UTC, Applejack2004 commented on tasks/mpi/alputov_i_most_different_neighbor_elements/src/ops_mpi.cpp
> +#include <thread>
fixed

2024-11-05 18:26 UTC, Applejack2004 commented on tasks/mpi/alputov_i_most_different_neighbor_elements/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
fixed

2024-11-05 18:26 UTC, Applejack2004 commented on tasks/seq/alputov_i_most_different_neighbor_elements/src/ops_seq.cpp
> +using namespace std::chrono_literals;
fixed

2024-11-05 18:29 UTC, ValeraDanger approved these changes

2024-11-05 19:46 UTC, Applejack2004 commented on tasks/mpi/alputov_i_most_different_neighbor_elements/func_tests/main.cpp
> +TEST(alputov_i_most_different_neighbor_elements_mpi, EmptyInput_ReturnsFalse) {
Tests have been added.

2024-11-06 00:18 UTC, aobolensk approved these changes

2024-11-06 18:27 UTC, allnes approved these changes

2024-11-06 18:27 UTC, merged