Малышев Владимир. Задача 1. Вариант 21. Метод интегрирования Монте-Карло
learning-process/ppc-2024-autumn pull request #148
Opened 2024-11-02 22:47 UTC by dangerulya

2024-11-05 13:05 UTC, KADCHDR requested changes

2024-11-05 13:05 UTC, KADCHDR commented on tasks/seq/malyshev_v_monte_carlo_integration/src/ops_mpi.cpp
> +  num_samples = static_cast<int>(100 / epsilon);
Please use the adaptive approach to calculate num_samples, it will be more accurate

2024-11-05 13:07 UTC, dangerulya commented on tasks/seq/malyshev_v_monte_carlo_integration/src/ops_mpi.cpp
> +  num_samples = static_cast<int>(100 / epsilon);
in work

2024-11-05 13:41 UTC, KADCHDR approved these changes

2024-11-05 13:53 UTC, myffii requested changes

2024-11-05 13:53 UTC, myffii commented on tasks/mpi/malyshev_v_monte_carlo_integration/src/ops_mpi.cpp
> +  return true;
do the same as KADCHDR suggested but for mpi.

and rename seq files from ops_mpi to sec_mpi

2024-11-05 13:53 UTC, dangerulya commented on tasks/mpi/malyshev_v_monte_carlo_integration/src/ops_mpi.cpp
> +  return true;
in work

2024-11-05 15:05 UTC, dangerulya commented on tasks/mpi/malyshev_v_monte_carlo_integration/src/ops_mpi.cpp
> +  return true;
fixed

2024-11-05 15:07 UTC, myffii approved these changes

2024-11-06 18:40 UTC, allnes requested changes

2024-11-06 18:40 UTC, allnes commented on tasks/mpi/kudryashova_i_vector_dot_product/func_tests/vectorDotProductMPIFuncTests.cpp
> +#include <boost/mpi/environment.hpp>
please don't add not own files

2024-11-06 18:50 UTC, dangerulya commented on tasks/mpi/kudryashova_i_vector_dot_product/func_tests/vectorDotProductMPIFuncTests.cpp
> +#include <boost/mpi/environment.hpp>
fixed

2024-11-08 18:53 UTC, dangerulya commented on tasks/mpi/kudryashova_i_vector_dot_product/func_tests/vectorDotProductMPIFuncTests.cpp
> +#include <boost/mpi/environment.hpp>
now I think I fixed it correctly

2024-11-09 11:52 UTC, aobolensk requested changes

2024-11-09 11:52 UTC, aobolensk commented on tasks/mpi/malyshev_v_monte_carlo_integration/func_tests/main.cpp
> +
Please, add tests for functions other than `x * x`

2024-11-09 14:27 UTC, dangerulya commented on tasks/mpi/malyshev_v_monte_carlo_integration/func_tests/main.cpp
> +
tests reworked

2024-11-10 00:53 UTC, allnes approved these changes

2024-11-10 00:54 UTC, aobolensk approved these changes

2024-11-10 00:54 UTC, merged