Белов Артём. Задача 1. Вариант 13. Максимальное значение элементов матрицы
learning-process/ppc-2024-autumn pull request #149
Opened 2024-11-02 23:28 UTC by belovtut

**Описание последовательной задачи:**

Поскольку матрица реализована в виде одномерного массива (по условию задачи), то алгоритм последовательно обходит вектор и ищет максимальный элемент в матрице (в векторе) с помощью `std::max_element`.

**Описание параллельной задачи (MPI):**

Размеры матрицы, входной массив данных и массив для записи результата помещаются root-процессом в структуру `TaskData`. Распределение данных по процессам происходит равномерно, для каждого процесса вычисляется количество элементов и смещения относительно начала массива.
Затем с помощью `boost::scatterv` root-процесс рассылает данные процессам, а все остальные процессы принимают свой "кусок" данных от корневого, также с помощью `scatterv`.
Каждый процесс находит локальный максимум среди своей части элементов. После чего root процесс, используя `reduce`, собирает с остальных процессов локальные максимумы, и с помощью  функтора `std::max()` определяет конечный (глобальный) максимум.

2024-11-03 09:30 UTC, kalyakinaa commented on tasks/mpi/belov_a_max_value_of_matrix_elements/include/ops_mpi.hpp
> +std::vector<T> MaxValueOfMatrixElementsParallel<T>::generate_random_matrix(int rows, int cols) {
I think it's worth moving this function to the test modules.

2024-11-03 09:56 UTC, hasanyanovk commented on tasks/seq/belov_a_max_value_of_matrix_elements/func_tests/main.cpp
> +TEST(belov_a_max_value_of_matrix_elements_seq, Test_Max_Value_Positive_Integers) {
You might add tests for empty matrix to increase tests coverage by `codecow`

2024-11-03 09:58 UTC, belovtut commented on tasks/mpi/belov_a_max_value_of_matrix_elements/include/ops_mpi.hpp
> +std::vector<T> MaxValueOfMatrixElementsParallel<T>::generate_random_matrix(int rows, int cols) {
Sounds reasonable, function moved. Thank you.

2024-11-03 10:03 UTC, belovtut commented on tasks/seq/belov_a_max_value_of_matrix_elements/func_tests/main.cpp
> +TEST(belov_a_max_value_of_matrix_elements_seq, Test_Max_Value_Positive_Integers) {
Added tests for a 0 rows matrix and for a 0 columns matrix. Thank you!

2024-11-03 10:07 UTC, kalyakinaa approved these changes

2024-11-03 11:43 UTC, kmichaelk approved these changes

2024-11-03 18:38 UTC, hasanyanovk approved these changes

2024-11-04 16:58 UTC, belovtut commented on tasks/mpi/belov_a_max_value_of_matrix_elements/perf_tests/main.cpp
> +    res[i] = static_cast<T>(gen() % 1000);
fixed

2024-11-04 19:16 UTC, allnes requested changes

2024-11-04 19:16 UTC, allnes commented on tasks/mpi/belov_a_max_value_of_matrix_elements/include/ops_mpi.hpp
> +  int remainder = rows_ * cols_ % size;
please calculate delta and remainder one time, and broadcast it instead rows and cals

2024-11-05 11:44 UTC, belovtut commented on tasks/mpi/belov_a_max_value_of_matrix_elements/include/ops_mpi.hpp
> +  int remainder = rows_ * cols_ % size;
fixed

2024-11-05 13:38 UTC, aobolensk approved these changes

2024-11-06 18:28 UTC, allnes approved these changes

2024-11-06 18:28 UTC, merged