Тышкевич Артем. Задача 1. Вариант 6. Нахождение числа нарушений упорядоченности соседних элементов вектора.
learning-process/ppc-2024-autumn pull request #150
Opened 2024-11-02 23:46 UTC by artich02

В последовательной реализации вектор инициализируется, затем выполняется проход по массиву с поэлементным сравнением. При этом вектор нулевого размера воспринимается, как ошибка на этапе валидации. Если текущий элемент больше следующего, счётчик нарушений увеличивается.

В параллельной версии (MPI) вектор делится на части, и каждый процесс обрабатывает свою часть в отдельном буфере. Root-процесс распределяет данные, и каждый non-root процесс подсчитывает нарушения локально. Для корректного учёта нарушений на границах подмассивов используется смещение данных на один элемент. По завершении вычислений результаты собираются и суммируются в root-процессе.

2024-11-03 10:08 UTC, ovVrLFg8ks requested changes

2024-11-03 10:08 UTC, ovVrLFg8ks commented on tasks/mpi/tyshkevich_a_num_of_orderly_violations/func_tests/main.cpp
> +#include "mpi/tyshkevich_a_num_of_orderly_violations/include/ops_mpi.hpp"
Add tests for zero-sized input

2024-11-03 10:11 UTC, ovVrLFg8ks requested changes

2024-11-03 10:11 UTC, ovVrLFg8ks commented on tasks/mpi/tyshkevich_a_num_of_orderly_violations/func_tests/main.cpp
> +#include "mpi/tyshkevich_a_num_of_orderly_violations/include/ops_mpi.hpp"
Add tests for zero-sized input

2024-11-03 13:08 UTC, artich02 commented on tasks/mpi/tyshkevich_a_num_of_orderly_violations/func_tests/main.cpp
> +#include "mpi/tyshkevich_a_num_of_orderly_violations/include/ops_mpi.hpp"
added test

2024-11-03 13:11 UTC, ovVrLFg8ks approved these changes

2024-11-03 13:29 UTC, artich02 commented
> I've noticed several files have unnecessary or indirect include directives, which obscure dependencies. Please review all include directives in the modified files to ensure each file includes only the headers it actually needs.

removed the unnecessary

2024-11-03 19:03 UTC, andreychh approved these changes

2024-11-04 14:28 UTC, aobolensk requested changes

2024-11-04 14:28 UTC, aobolensk commented on tasks/mpi/tyshkevich_a_num_of_orderly_violations/func_tests/main.cpp
> +std::string VecToStrTY(std::vector<int> v) {
Do we need this copied by value?

2024-11-04 14:28 UTC, aobolensk commented on tasks/seq/tyshkevich_a_num_of_orderly_violations/perf_tests/main.cpp
> +  int size = 999;
Too small size for perf test

2024-11-04 17:03 UTC, artich02 commented
@aobolensk I fixed the code based on your comments. But it was not my fault that macos-clang-build crashed. This can be seen from the last two commits.

2024-11-04 19:18 UTC, allnes requested changes

2024-11-04 19:18 UTC, allnes commented on tasks/mpi/tyshkevich_a_num_of_orderly_violations/src/ops_mpi.cpp
> +  }
please check it in validation() function

2024-11-04 19:50 UTC, artich02 commented on tasks/mpi/tyshkevich_a_num_of_orderly_violations/src/ops_mpi.cpp
> +  }
@allnes I can make inputs_count > 0, but I will be forced to remove the test for zero size?

2024-11-04 20:12 UTC, allnes commented on tasks/mpi/tyshkevich_a_num_of_orderly_violations/src/ops_mpi.cpp
> +  }
please remove it, because yours task for size = 0 is not relevant

2024-11-04 21:46 UTC, allnes approved these changes

2024-11-05 00:33 UTC, aobolensk requested changes

2024-11-05 00:33 UTC, aobolensk commented on tasks/seq/tyshkevich_a_num_of_orderly_violations/func_tests/main.cpp
> +TEST(tyshkevich_a_num_of_orderly_violations_seq_ftest, Test_10) {
Please add some more tests from MPI version here as well

2024-11-05 00:33 UTC, aobolensk commented on tasks/mpi/tyshkevich_a_num_of_orderly_violations/src/ops_mpi.cpp
> +std::vector<int> tyshkevich_a_num_of_orderly_violations_mpi::getRandomVector(int sz) {
Please, move to the test module

2024-11-06 00:19 UTC, aobolensk commented on tasks/mpi/tyshkevich_a_num_of_orderly_violations/src/ops_mpi.cpp
> +std::vector<int> tyshkevich_a_num_of_orderly_violations_mpi::getRandomVector(int sz) {
Exclude getRandomVector declarations from header as well

2024-11-06 09:23 UTC, artich02 commented on tasks/mpi/tyshkevich_a_num_of_orderly_violations/src/ops_mpi.cpp
> +std::vector<int> tyshkevich_a_num_of_orderly_violations_mpi::getRandomVector(int sz) {
@aobolensk Done

2024-11-06 15:29 UTC, merged