Наседкин Егор. Задача 1. Вариант 16. Нахождение максимальных значений по столбцам матрицы.
learning-process/ppc-2024-autumn pull request #151
Opened 2024-11-02 23:46 UTC by myffii

Нахождение максимальных значений по каждому столбцу матрицы с использованием параллельных вычислений (Microsoft MPI) или последовательной обработки (seq)

2024-11-05 12:54 UTC, KADCHDR requested changes

2024-11-05 12:54 UTC, KADCHDR commented on tasks/seq/nasedkin_e_matrix_column_max_value/src/ops_seq.cpp
> +      }
pls use std::max_element too

2024-11-05 12:56 UTC, myffii commented on tasks/mpi/nasedkin_e_matrix_column_max_value/src/ops_mpi.cpp
> +      }
thx, fixed

2024-11-05 12:56 UTC, myffii commented on tasks/seq/nasedkin_e_matrix_column_max_value/src/ops_seq.cpp
> +      }
fixed 2

2024-11-05 13:05 UTC, keshaproger requested changes

2024-11-06 13:55 UTC, keshaproger approved these changes

2024-11-06 15:08 UTC, KADCHDR approved these changes

2024-11-06 18:43 UTC, allnes requested changes

2024-11-06 18:43 UTC, allnes commented on .clang-format
> -ColumnLimit: 120
please don't change not own files

2024-11-06 18:43 UTC, allnes commented on ppc_build/CMakeCache.txt
> +# For build in directory: d:/ppctemp/ppc-2024-autumn/ppc_build
please don't add temp files

2024-11-06 18:43 UTC, allnes commented on tasks/mpi/nasedkin_e_matrix_column_max_value/src/ops_mpi.cpp
> +  broadcast(world, numRows, 0);
please calculate one time delta and extra and broadcast it instead numCols and numRows

2024-11-08 00:36 UTC, aobolensk requested changes

2024-11-08 00:36 UTC, aobolensk commented on tasks/mpi/nasedkin_e_matrix_column_max_value/src/ops_mpi.cpp
> +    delta = numCols / world.size();
Please, move MPI data transfer to ::run() function

2024-11-09 02:21 UTC, aobolensk approved these changes

2024-11-10 00:54 UTC, allnes approved these changes

2024-11-10 00:54 UTC, merged