Строганов Михаил. Задача 1. Вариант 22. Нахождение числа буквенных символов в строке.
learning-process/ppc-2024-autumn pull request #153
Opened 2024-11-03 00:59 UTC by StroganovM

Данный проект реализует задачу подсчета символов в строке двумя методами: последовательным и параллельным с использованием MPI. Цель проекта — сравнить производительность и корректность обоих подходов, протестировав их с использованием различных данных.

Основные компоненты:

Тесты: Для обоих методов используются тесты на базе gtest для оценки корректности и производительности реализации.

Функции подсчета символов: Реализация включает функции для генерации случайных строк и непосредственного подсчета символов, а также классы для запуска задач в последовательной и параллельной среде.

Цель:
Проект демонстрирует преимущества и недостатки параллельной обработки по сравнению с последовательной, позволяя оценить, насколько MPI может ускорить выполнение задачи при обработке больших объемов данных.

2024-11-03 10:57 UTC, ChastovSlava approved these changes
Rename all "// Copyright 2023 Nesterov Alexander" on "// Copyright 2024 Stroganov Mikhail".

2024-11-03 10:57 UTC, Kvoks approved these changes
in my opinion everything is fine

2024-11-04 14:32 UTC, aobolensk requested changes

2024-11-04 14:32 UTC, aobolensk commented on tasks/mpi/stroganov_m_count_symbols_in_string/include/ops_mpi.hpp
> +int countOfSymbols(std::string& str);
Please, move test functions to the test module

2024-11-04 14:32 UTC, aobolensk commented on tasks/seq/stroganov_m_count_symbols_in_string/func_tests/main.cpp
> +
Please, add the test for the string length == 1

2024-11-04 14:32 UTC, aobolensk commented on tasks/mpi/stroganov_m_count_symbols_in_string/src/ops_mpi.cpp
> +  }
Please, move all data transfer related stuff to ::run()

2024-11-04 14:32 UTC, aobolensk commented
Please, get 2 more peer reviews

2024-11-04 16:11 UTC, VasenkovAA commented
Have you tried adding tests for 1, 2, 3, 4 characters per line?

2024-11-04 19:22 UTC, allnes requested changes

2024-11-04 19:22 UTC, allnes commented on tasks/seq/stroganov_m_count_symbols_in_string/src/ops_seq.cpp
> +using namespace std::chrono_literals;
what do you use it for?

2024-11-04 19:45 UTC, StroganovM commented on tasks/seq/stroganov_m_count_symbols_in_string/src/ops_seq.cpp
> +using namespace std::chrono_literals;
nowhere, removed it

2024-11-04 20:13 UTC, allnes approved these changes

2024-11-04 20:57 UTC, StroganovM commented on tasks/mpi/stroganov_m_count_symbols_in_string/include/ops_mpi.hpp
> +int countOfSymbols(std::string& str);
fixed

2024-11-04 20:57 UTC, StroganovM commented on tasks/seq/stroganov_m_count_symbols_in_string/func_tests/main.cpp
> +
add test =(

2024-11-04 20:57 UTC, StroganovM commented on tasks/mpi/stroganov_m_count_symbols_in_string/src/ops_mpi.cpp
> +  }
fixed

2024-11-04 21:13 UTC, ChastovSlava approved these changes
good job😺

2024-11-04 21:55 UTC, VasenkovAA approved these changes

2024-11-05 07:26 UTC, Kvoks approved these changes
good job

2024-11-05 13:40 UTC, aobolensk approved these changes

2024-11-05 13:40 UTC, merged