Громов Алексей. Задача 1. Вариант 1. Сумма элементов вектора.
learning-process/ppc-2024-autumn pull request #158
Opened 2024-11-03 09:09 UTC by DSFKnight

**Последовательная задача (seq)**: Последовательная задача выполняется в классе `SumOfVector`, где элементы входного вектора суммируются с помощью простого цикла. Перед запуском происходит валидация данных и их предварительная обработка. В процессе вычисления каждый элемент вектора добавляется к общей сумме, которая затем сохраняется в выходных данных.
**Параллельная задача (mpi)**: В классе `MPISumOfVectorParallel` входной вектор делится на части между процессами. Каждый процесс выполняет вычисления на своей части данных с использованием `std::accumulate` или других функций, таких как `std::max_element` и `std::min_element`, в зависимости от типа операции. После локальных вычислений результаты собираются с помощью MPI-функции `reduce`.

2024-11-04 09:37 UTC, artich02 requested changes
Some of the includes don't work. Fix them.

2024-11-04 09:41 UTC, kmichaelk requested changes

2024-11-04 09:41 UTC, kmichaelk commented on tasks/mpi/gromov_a_sum_of_vector_elements/perf_tests/main.cpp
> +      std::make_shared<gromov_a_sum_of_vector_elements_mpi::MPISumOfVectorParallel>(taskDataPar, "+");
Check carefully - the "+" operation you use here is not implemented, so this test basically compares 0 with 0 and succeeds, as in your previous PR

2024-11-04 13:13 UTC, artich02 approved these changes
gj

2024-11-04 13:29 UTC, DSFKnight commented on tasks/mpi/gromov_a_sum_of_vector_elements/func_tests/main.cpp
> +  std::vector<int> global_vec = {-10, -20, 0, 15, 30};
I can do it, but the tests fail when using -30. Maybe you know how to fix this issue?

2024-11-04 16:57 UTC, kmichaelk requested changes

2024-11-04 16:57 UTC, kmichaelk commented on tasks/mpi/gromov_a_sum_of_vector_elements/src/ops_mpi.cpp
> +    }
Not quite right solution, you still have a flaw in data distribution logic resulting in dropping elements if amount of data is not divisible by number of processes, try adding a test with `{-10, -20, 0, -30, 15}` as input data

2024-11-04 19:24 UTC, allnes requested changes

2024-11-04 19:24 UTC, allnes commented on tasks/mpi/gromov_a_sum_of_vector_elements/src/ops_mpi.cpp
> +    vec[i] = gen() % 100;
please use negative values too

2024-11-04 19:24 UTC, allnes commented on tasks/mpi/gromov_a_sum_of_vector_elements/src/ops_mpi.cpp
> +bool gromov_a_sum_of_vector_elements_mpi::MPISumOfVectorParallel::pre_processing() {
please move all mpi functions to run()

2024-11-04 19:24 UTC, allnes commented on tasks/seq/gromov_a_sum_of_vector_elements/src/ops_seq.cpp
> +using namespace std::chrono_literals;
what do you use it for?

2024-11-05 19:12 UTC, kmichaelk approved these changes

2024-11-07 13:38 UTC, aobolensk approved these changes

2024-11-07 15:05 UTC, allnes requested changes

2024-11-07 15:05 UTC, allnes commented on tasks/mpi/gromov_a_sum_of_vector_elements/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
what do you use it for?

2024-11-07 15:05 UTC, allnes commented on tasks/mpi/gromov_a_sum_of_vector_elements/src/ops_mpi.cpp
> +bool gromov_a_sum_of_vector_elements_mpi::MPISumOfVectorParallel::pre_processing() {
it hasn't changed

2024-11-07 18:37 UTC, allnes approved these changes

2024-11-07 18:37 UTC, merged