Тараканов Денис. Задача 1. Вариант 20. Интегрирование - метод трапеций.
learning-process/ppc-2024-autumn pull request #161
Opened 2024-11-03 11:40 UTC by Chiks37

**seq:** 
Интегрируем от a до b с шагом h. На каждом шаге рассчитывает площадь трапеции и добавляет её к итоговому результату. По завершении результат сохраняется в выходной переменной.
**mpi:**
Каждому процессу даём по некоторому множеству трапеций, по которым процесс и будет проходиться, выполняя стандартный последовательный алгоритм. В конце суммируем результат со всех потоков в одну переменную.

2024-11-03 11:43 UTC, mateusxap requested changes

2024-11-03 11:43 UTC, mateusxap commented on tasks/seq/tarakanov_d_integration_the_trapezoid_method/func_tests/main.cpp
> +  // ASSERT_EQ(1, 1);
please remove the comment

2024-11-03 11:49 UTC, mateusxap requested changes

2024-11-03 11:49 UTC, mateusxap commented on tasks/mpi/tarakanov_d_integration_the_trapezoid_method/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, a, 0);
please add everything related to mpi function in run

2024-11-03 11:52 UTC, mateusxap requested changes

2024-11-03 11:52 UTC, mateusxap commented on tasks/mpi/tarakanov_d_integration_the_trapezoid_method/src/ops_mpi.cpp
> +#include <thread>
remove unused lib

2024-11-03 11:55 UTC, mateusxap requested changes

2024-11-03 11:55 UTC, mateusxap commented on tasks/mpi/tarakanov_d_integration_the_trapezoid_method/func_tests/main.cpp
> +TEST(tarakanov_d_integration_the_trapezoid_method_mpi_func_tests, Test_Integration3) {
please add test with random data

2024-11-03 14:33 UTC, Chiks37 commented on tasks/seq/tarakanov_d_integration_the_trapezoid_method/func_tests/main.cpp
> +  // ASSERT_EQ(1, 1);
fixed

2024-11-03 14:34 UTC, Chiks37 commented on tasks/mpi/tarakanov_d_integration_the_trapezoid_method/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, a, 0);
fixed

2024-11-03 14:34 UTC, Chiks37 commented on tasks/mpi/tarakanov_d_integration_the_trapezoid_method/src/ops_mpi.cpp
> +#include <thread>
fixed

2024-11-03 14:54 UTC, Chiks37 commented on tasks/mpi/tarakanov_d_integration_the_trapezoid_method/include/ops_mpi.hpp
> +  double a{}, b{}, h{}, /*local_res{},*/ local_a{};
fixed

2024-11-03 14:54 UTC, Chiks37 commented on tasks/seq/tarakanov_d_integration_the_trapezoid_method/perf_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
fixed

2024-11-03 14:54 UTC, Chiks37 commented on tasks/seq/tarakanov_d_integration_the_trapezoid_method/include/ops_seq.hpp
> +#include <string>
fixed

2024-11-03 17:56 UTC, sk1er52 approved these changes

2024-11-03 18:08 UTC, mateusxap approved these changes

2024-11-04 19:29 UTC, allnes requested changes

2024-11-04 19:29 UTC, allnes commented on tasks/seq/tarakanov_d_integration_the_trapezoid_method/src/ops_seq.cpp
> +using namespace std::chrono_literals;
what do you use it for?

2024-11-04 20:16 UTC, allnes approved these changes

2024-11-07 23:35 UTC, aobolensk approved these changes

2024-11-07 23:35 UTC, merged