Иванов Михаил. Задача 1. Вариант 20. Интегрирование – метод трапеций.
learning-process/ppc-2024-autumn pull request #162
Opened 2024-11-03 12:38 UTC by misha-ivanov

**Алгоритм интегрирования методом трапеций подразумевает:**
1) Разделение отрезка интегрирования на N равных частей
2) Получение значения функции в точках начала и конца i-ой части отрезка
3) Определение площади трапеции, образованной 4-мя точками, полученными в шаге 1 и 2
4) Суммирование площадей трапеций

**Последовательная версия:** поиск длины i-ого отрезка (`step`), последовательный проход по каждому отрезку длины `step` в заданном диапазоне интегрирования (от a до b) и получение площадей трапеций. Так как площадь i-ой трапеции равна `(h_i + h_(i + 1)) / 2 * step`, то можно вынести за пределы цикла, суммирующего площади трапеций, операции: (`/ 2 * step`)

**Параллельная версия:** получение входных параметров для 0-ого процесса, расчёт step, передача через `broadcast` во все остальные процессы значений: a, b, n, step. Каждый процесс в цикле рассчитывает сумму оснований i-ой трапеции, где: 
`i = proc_rank + j * communicator_size`, 
`j++` при `j_0 = 0`;
После окончания цикла данные собираются через reduce и оператор `std::plus<>()` в общую сумму `result` и к ней применяется операция: (`/ 2 * step`)

2024-11-03 13:56 UTC, MaxikGuy requested changes
There is no tests in seq/func_tests and mpi/func_tests when borders are equal to each other. Please, add it.

2024-11-03 13:56 UTC, MaxikGuy requested changes
Add the tests in seq/func_tests and mpi/func_tests where result is higher than any large number (10000 or 100000)

2024-11-03 15:23 UTC, MishaRysev commented on tasks/mpi/ivanov_m_integration_trapezoid/func_tests/main.cpp
> +}
add tests when result = 0 and result < 0

2024-11-03 15:23 UTC, MishaRysev commented on tasks/mpi/ivanov_m_integration_trapezoid/include/ops_mpi.hpp
> +  double a_{}, b_{};
variables of type double can be declarated in one line (28 line for example)

2024-11-03 15:23 UTC, MishaRysev commented on tasks/seq/ivanov_m_integration_trapezoid/func_tests/main.cpp
> +}
add tests when result = 0 and result < 0

2024-11-03 15:23 UTC, MishaRysev commented on tasks/seq/ivanov_m_integration_trapezoid/include/ops_seq.hpp
> +  double a_{}, b_{};
variables of type double can be declarated in one line (22 line for example)

2024-11-03 18:57 UTC, MaxikGuy approved these changes

2024-11-03 19:26 UTC, MishaRysev approved these changes

2024-11-04 19:34 UTC, allnes requested changes

2024-11-04 19:34 UTC, allnes commented on tasks/mpi/ivanov_m_integration_trapezoid/src/ops_mpi.cpp
> +  if (a_ > b_) std::swap(a_, b_);
Do you take into account the sign of the integrand when rearranging the limits of integration?

2024-11-04 19:34 UTC, allnes commented on tasks/seq/ivanov_m_integration_trapezoid/src/ops_seq.cpp
> +using namespace std::chrono_literals;
what do you use it for?

2024-11-04 21:09 UTC, misha-ivanov commented on tasks/mpi/ivanov_m_integration_trapezoid/src/ops_mpi.cpp
> +  if (a_ > b_) std::swap(a_, b_);
Got it and have already fixed it

2024-11-04 21:10 UTC, misha-ivanov commented on tasks/seq/ivanov_m_integration_trapezoid/src/ops_seq.cpp
> +using namespace std::chrono_literals;
Fixed: some useless includes were deleted

2024-11-04 21:48 UTC, allnes approved these changes

2024-11-05 00:29 UTC, merged