Cancel workflows for stale commits automatically
learning-process/ppc-2024-autumn pull request #163
Opened 2024-11-03 13:43 UTC by kmichaelk

2024-11-03 13:43 UTC, kmichaelk commented
@aobolensk

2024-11-03 13:49 UTC, aobolensk commented
To be in equal position for everyone, let us merge this in 10 days (last day when you can get points for the 1st task). November, 13.

2024-11-03 13:49 UTC, aobolensk requested changes

2024-11-03 13:49 UTC, aobolensk commented on .github/workflows/perf-statistic.yml
> +
```suggestion
```
Please revert this change for perf stats, it is not correct to have it there

2024-11-03 19:02 UTC, allnes approved these changes
Agree with @aobolensk, we will wait 13th November.

2024-11-04 00:25 UTC, aobolensk approved these changes

2024-11-04 00:39 UTC, aobolensk commented
@kmichaelk LGTM, thanks. If you don't mind, please consider adding your infrastructure related changes to the main repository: https://github.com/learning-process/parallel_programming_course . This will be useful for the next term when repo will be re-created and for next year students.

Thanks in advance!

2024-11-04 00:47 UTC, kmichaelk commented
Of course.

I'd also suggest to get rid of extensive use of `std::shared_ptr` - e.g., in the case with `TaskData`, its lifetime is not tied to the lifetime of the memory it points to and I don't think it is needed at all.

2024-11-13 00:12 UTC, merged