Суворов Дмитрий. Задача 1. Вариант 1. Сумма элементов вектора.Suvorov d sum of vector elements
learning-process/ppc-2024-autumn pull request #166
Opened 2024-11-03 15:24 UTC by suvorovDm-1

Описание последовательной задачи:
В последовательной задаче в функции run() для суммирования элементов вектора используется функция std::accumulate.
Тесты проверяют работу с векторами разного размера, сумму элементов нулевого вектора, пустого вектора, вектора с единственным элементом.

Описание MPI задачи:
В MPI задаче в каждом процессе создается отдельный буфер с данными, куда root-процесс скидывает части исходного вектора используя scatterv(). Кроме того, корректно обрабатывается случай некратного количества процессов и элементов в векторе. В оставшихся процессах (всех, кроме root) задача сводится к использованию std::accumulate, как в последовательной задаче. После завершения обработки все данные суммируются в root процесс с помощью reduce. 
В тестах проверяется:
1. Работа с вектором, количество элементов которого больше числа процессов.
2. Работа с пустым вектором.
3. Работа с нулевым вектором.
4. Работа с вектором, содержащим единственный элемент.
5. Работа с вектором, количество элементов которого равно количеству процессов.
6. Работа с вектором, количество элементов которого меньше числа процессов.
7. Работа с вектором, количество элементов которого кратно количеству процессов.
8. Работа с вектором, количество элементов которого не кратно количеству процессов.

2024-11-03 20:18 UTC, Torcna approved these changes
I like that in this implementation, tests here cover all of the situations, even when the number of proc is greater than number of elems in vector. This version of distribution of input elements ensures us, that there will be no issues with algorithm, that we can see at the MPI description.

2024-11-04 03:00 UTC, allnes commented
@Torcna approve is not accepted

2024-11-04 10:19 UTC, ascannel requested changes

2024-11-04 14:00 UTC, korablev-vm requested changes

2024-11-04 14:00 UTC, korablev-vm commented on tasks/mpi/suvorov_d_sum_of_vector_elements/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
The function is for tests, it is not required to declare it here.

2024-11-04 14:00 UTC, korablev-vm commented on tasks/mpi/suvorov_d_sum_of_vector_elements/src/ops_mpi.cpp
> +  std::vector<int> vec(sz);
The implementation of this function must be transferred to the test files

2024-11-04 19:35 UTC, allnes commented on tasks/mpi/suvorov_d_sum_of_vector_elements/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
what do you use it for?

2024-11-04 19:38 UTC, allnes commented on tasks/seq/suvorov_d_sum_of_vector_elements/src/vec.cpp
> +using namespace std::chrono_literals;
what do you use it for?

2024-11-05 11:44 UTC, suvorovDm-1 commented on tasks/seq/suvorov_d_sum_of_vector_elements/func_tests/main.cpp
> +TEST(suvorov_d_sum_of_vector_elements_seq, Test_Sum_With_Empte_Vector) {
The test running before the specified one - checks work with a vector in which all elements are equal to 0. And the specified test - checks work with an empty vector in which there are no elements

2024-11-05 12:04 UTC, GrayPirat commented on tasks/seq/suvorov_d_sum_of_vector_elements/func_tests/main.cpp
> +TEST(suvorov_d_sum_of_vector_elements_seq, Test_Sum_With_Empte_Vector) {
Ok, I agree now

2024-11-05 12:15 UTC, KseniyaBeskhmelnova approved these changes
Now the implementation of the task meets all the requirements. All comments have been taken into account. Tests cover all functionality of the solution👍

2024-11-05 12:29 UTC, suvorovDm-1 commented on tasks/mpi/suvorov_d_sum_of_vector_elements/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
These lines are really not used and need to be deleted.

2024-11-05 12:29 UTC, suvorovDm-1 commented on tasks/seq/suvorov_d_sum_of_vector_elements/src/vec.cpp
> +using namespace std::chrono_literals;
These lines are really not used and need to be deleted.

2024-11-05 12:36 UTC, GrayPirat approved these changes

2024-11-05 12:51 UTC, korablev-vm approved these changes

2024-11-05 14:09 UTC, aobolensk approved these changes

2024-11-06 18:30 UTC, allnes approved these changes

2024-11-06 18:30 UTC, merged