Кудряшова Ирина. Задача 1. Вариант 9. Скалярное произведение векторов
learning-process/ppc-2024-autumn pull request #167
Opened 2024-11-03 16:04 UTC by Irina2004-tech

Fixed seq_perf_tests
https://github.com/learning-process/ppc-2024-autumn/pull/69

2024-11-04 19:45 UTC, allnes approved these changes

2024-11-05 00:25 UTC, aobolensk approved these changes

2024-11-05 09:20 UTC, ArinaTs approved these changes

2024-11-05 09:20 UTC, ArinaTs commented on tasks/seq/kudryashova_i_vector_dot_product/func_tests/vectorDotProductSeqFuncTests.cpp
> +TEST(kudryashova_i_vector_dot_product_seq, check_empty_vectors) {
add a test for vectors of length 1 to seq

2024-11-05 16:20 UTC, ascannel requested changes

2024-11-05 16:20 UTC, ascannel commented on tasks/mpi/kudryashova_i_vector_dot_product/func_tests/vectorDotProductMPIFuncTests.cpp
> +    ASSERT_EQ(reference[0], result[0]);
why do you need two identical checks?

2024-11-05 16:20 UTC, ascannel commented on tasks/mpi/kudryashova_i_vector_dot_product/func_tests/vectorDotProductMPIFuncTests.cpp
> +    ASSERT_EQ(reference[0], result[0]);
and also here

2024-11-05 16:25 UTC, Irina2004-tech commented on tasks/seq/kudryashova_i_vector_dot_product/func_tests/vectorDotProductSeqFuncTests.cpp
> +TEST(kudryashova_i_vector_dot_product_seq, check_empty_vectors) {
done

2024-11-05 17:07 UTC, ascannel approved these changes

2024-11-05 18:06 UTC, ArinaTs commented on tasks/seq/kudryashova_i_vector_dot_product/func_tests/vectorDotProductSeqFuncTests.cpp
> +TEST(kudryashova_i_vector_dot_product_seq, check_empty_vectors) {
Good job. I agree with that

2024-11-06 15:32 UTC, merged