Леонтьев Никита. Задача 1. Вариант 1. Сумма элементов вектора.
learning-process/ppc-2024-autumn pull request #168
Opened 2024-11-03 17:03 UTC by NeiroYT

Описание последовательной задачи:
Для суммирования всех элементов вектора используется стандартная функция std::accumulate. Тестами проверен данный функционал для разного числа элементов и проведены замеры времени выполнения.

Описание MPI задачи:
Вектор разделяется на части, параллельно для каждой части выполняется std::accumulate. Затем все результаты сложения складываются. Тестами проверена работоспособность данной схемы, а так же произведены замеры производительности в сравнении с последовательной реализацией.

2024-11-06 19:08 UTC, allnes commented on tasks/seq/leontev_n_vector_sum/src/ops_seq.cpp
> +using namespace std::chrono_literals;
what do you use it for?

2024-11-07 16:29 UTC, NeiroYT commented on tasks/mpi/leontev_n_vector_sum/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
Fixed

2024-11-07 16:33 UTC, allnes approved these changes

2024-11-08 00:23 UTC, aobolensk requested changes

2024-11-08 00:23 UTC, aobolensk commented on tasks/mpi/leontev_n_vector_sum/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
Please move test functions to the test module

2024-11-08 00:23 UTC, aobolensk commented on tasks/mpi/leontev_n_vector_sum/src/ops_mpi.cpp
> +
Please, move MPI data transfer to ::run()

2024-11-08 14:01 UTC, NeiroYT commented on tasks/mpi/leontev_n_vector_sum/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
Moved

2024-11-08 14:02 UTC, NeiroYT commented on tasks/mpi/leontev_n_vector_sum/src/ops_mpi.cpp
> +
Moved from preprocessing to run

2024-11-08 14:56 UTC, aobolensk approved these changes

2024-11-08 17:17 UTC, BrunoBucCcellati commented on tasks/seq/leontev_n_vector_sum/func_tests/main.cpp
> +  std::vector<float> in(5, 1.f);
Why are you writing 1.f? Vector elements will have the type float  anyway

2024-11-08 17:17 UTC, BrunoBucCcellati commented on tasks/seq/leontev_n_vector_sum/src/ops_seq.cpp
> +template class leontev_n_vector_sum_seq::VecSumSequential<int64_t>;
It makes no sense to consider cases for uint64_t and int64_t

2024-11-09 09:24 UTC, NeiroYT commented on tasks/mpi/leontev_n_vector_sum/func_tests/main.cpp
> +TEST(leontev_n_vec_sum_mpi, sum_mpi_20000elem) {
This doesn't mean these tests are useless

2024-11-09 09:24 UTC, NeiroYT commented on tasks/mpi/leontev_n_vector_sum/src/ops_mpi.cpp
> +#include <algorithm>
Agree

2024-11-09 09:33 UTC, NeiroYT commented on tasks/seq/leontev_n_vector_sum/perf_tests/main.cpp
> +  const int count = 0x1FFFFFF;
Changed to 30000000

2024-11-09 09:35 UTC, NeiroYT commented on tasks/seq/leontev_n_vector_sum/func_tests/main.cpp
> +  std::vector<float> in(5, 1.f);
It's about code-style, i prefer default value to be float

2024-11-09 09:35 UTC, NeiroYT commented on tasks/seq/leontev_n_vector_sum/src/ops_seq.cpp
> +template class leontev_n_vector_sum_seq::VecSumSequential<int64_t>;
Ok

2024-11-09 10:24 UTC, BrunoBucCcellati approved these changes

2024-11-10 20:08 UTC, VladislavPoroshin commented on tasks/mpi/leontev_n_vector_sum/include/ops_mpi.hpp
> +#include <string>
extra includes

2024-11-10 20:08 UTC, VladislavPoroshin commented on tasks/mpi/leontev_n_vector_sum/src/ops_mpi.cpp
> +#include <functional>
extra includes

2024-11-10 20:08 UTC, VladislavPoroshin commented on tasks/seq/leontev_n_vector_sum/include/ops_seq.hpp
> +#include <numeric>
extra includes

2024-11-10 20:18 UTC, NeiroYT commented on tasks/mpi/leontev_n_vector_sum/include/ops_mpi.hpp
> +#include <string>
fixed

2024-11-10 20:18 UTC, NeiroYT commented on tasks/mpi/leontev_n_vector_sum/src/ops_mpi.cpp
> +#include <functional>
fixed

2024-11-10 20:20 UTC, NeiroYT commented on tasks/seq/leontev_n_vector_sum/include/ops_seq.hpp
> +#include <numeric>
fixed

2024-11-10 20:25 UTC, VladislavPoroshin approved these changes

2024-11-11 11:36 UTC, merged