Шкуринская Елена. Задача 1. Вариант 25. Подсчет числа предложений в с…
learning-process/ppc-2024-autumn pull request #169
Opened 2024-11-03 17:12 UTC by sudo-technoir

…троке.

Последовательно: подаётся строка, проходим по ней и считаем число предложений по знакам препинания.
MPI: главный процесс (rank 0) разделяет строку на равные части и передает их всем процессам с помощью MPI broadcast. Последний процесс получает остаток строки, если она не делится равномерно. Каждый процесс считает количество предложений в своей части строки, после этого расчёты объединяются через MPI reduce.

2024-11-07 07:51 UTC, DSolo03 requested changes

2024-11-07 07:51 UTC, DSolo03 commented on tasks/mpi/shkurinskaya_e_count_sentences/src/ops_mpi.cpp
> +  res = 0;
`res` and `local_res` variables already set to zero by their constructors in header 
(`int res{}` and `int local_res{}` respectivly)
so there is no need for redefenition

2024-11-07 18:16 UTC, sudo-technoir commented on tasks/mpi/shkurinskaya_e_count_sentences/func_tests/main.cpp
> +#include <gtest/gtest.h>
done

2024-11-07 18:17 UTC, sudo-technoir commented on tasks/mpi/shkurinskaya_e_count_sentences/include/ops_mpi.hpp
> +#include <numeric>
fixed

2024-11-07 19:17 UTC, NeeMiyuki approved these changes

2024-11-08 07:51 UTC, sudo-technoir commented on tasks/mpi/shkurinskaya_e_count_sentences/src/ops_mpi.cpp
> +  size_t remainder = total_size % world.size();
fixed

2024-11-08 07:53 UTC, sudo-technoir commented on tasks/mpi/shkurinskaya_e_count_sentences/src/ops_mpi.cpp
> +  res = 0;
does not work as it should if not setting it to 0

2024-11-09 12:01 UTC, sudo-technoir commented on tasks/mpi/shkurinskaya_e_count_sentences/func_tests/main.cpp
> +TEST(shkurinskaya_e_count_sentences_mpi, Test_Multiple_Endings) {
fair enough, fixed

2024-11-09 12:02 UTC, sudo-technoir commented on tasks/mpi/shkurinskaya_e_count_sentences/src/ops_mpi.cpp
> +  res = 0;
removed `res=0`

2024-11-09 12:24 UTC, DSolo03 approved these changes

2024-11-10 00:56 UTC, allnes approved these changes

2024-11-10 00:57 UTC, aobolensk requested changes

2024-11-10 00:57 UTC, aobolensk commented on tasks/seq/shkurinskaya_e_count_sentences/func_tests/main.cpp
> +TEST(Sequential, Test_Single_Sentence) {
Please, add random tests here as well

2024-11-10 12:12 UTC, sudo-technoir commented on tasks/seq/shkurinskaya_e_count_sentences/func_tests/main.cpp
> +TEST(Sequential, Test_Single_Sentence) {
done

2024-11-11 11:38 UTC, merged