Соловьев Данила. Задача 1. Вариант 3. Максимальное значение элементов вектора.
learning-process/ppc-2024-autumn pull request #17
Opened 2024-10-18 12:13 UTC by DSolo03

Описание последовательной задачи: Для каждого из элементов вектора, сравниваем его значение со значением переменной, в которой хранится максимальное значение вектора. Если значение данного элемента вектора больше чем значение переменной, то записываем значение данного элемента вектора в переменную.

Описание MPI задачи: Делим входные данные на несколько фрагментов, количество которых является количеством возможных процессов. Каждый из фрагментов, кроме первого, отдаем на исполнение соответствующим процессам. Первый фрагмент будет обработан в том же процессе, что и разделял данные. В каждом из процессов, ищется максимальное значение данного ему фрагмента, соответственно последовательной задачи, и из каждого из процессов, собирается максимальное из всех значений при помощи функции `reduce` с оператором `maximum`. Максимальное значение записывается в переменную `result` и возвращается.

2024-10-27 09:05 UTC, allnes commented on tasks/seq/solovyev_d_vector_max/src/source.cpp
> +  result = solovyev_d_vector_max_mpi::vectorMax(data);
you work inside namespace `solovyev_d_vector_max_mpi`, why do you use this namespace inside namespace

2024-10-27 09:06 UTC, allnes commented on tasks/mpi/solovyev_d_vector_max/src/source.cpp
> +  localResult = solovyev_d_vector_max_mpi::vectorMax(localData);
same question about namespace

2024-10-27 14:36 UTC, aobolensk requested changes

2024-10-27 14:36 UTC, aobolensk commented on tasks/mpi/solovyev_d_vector_max/src/source.cpp
> +}
Please, move all test related functions to the test file

2024-10-27 14:36 UTC, aobolensk commented on tasks/mpi/solovyev_d_vector_max/src/source.cpp
> +  }
Use std::copy for copying the whole vector

2024-10-27 14:36 UTC, aobolensk commented on tasks/mpi/solovyev_d_vector_max/perf_tests/main.cpp
> +    count_size_vector = 12000000;
I suggest adding different sizes for the tests

2024-10-27 16:45 UTC, DSolo03 commented on tasks/seq/solovyev_d_vector_max/src/source.cpp
> +  result = solovyev_d_vector_max_mpi::vectorMax(data);
Fixed, thanks

2024-10-27 16:47 UTC, DSolo03 commented on tasks/mpi/solovyev_d_vector_max/src/source.cpp
> +}
Function `getRandomVector` moved to the tests
Function `vectorMax` used to find vector maximum inside task run, so it's won't moved
Thanks

2024-10-27 16:48 UTC, DSolo03 commented on tasks/mpi/solovyev_d_vector_max/src/source.cpp
> +  }
Fixed, thanks

2024-10-27 16:50 UTC, DSolo03 commented on tasks/mpi/solovyev_d_vector_max/perf_tests/main.cpp
> +    count_size_vector = 12000000;
Adding differents sizes for the tests implies adding more tests to the file
However, submitting part of the manual says that 
> number of tests must be 2 - run_task and run_pipeline. 
so won't changed.
Thanks

2024-10-27 17:03 UTC, DSolo03 commented on tasks/mpi/solovyev_d_vector_max/src/source.cpp
> +  localResult = solovyev_d_vector_max_mpi::vectorMax(localData);
Fixed, thanks

2024-10-28 12:59 UTC, allnes approved these changes

2024-10-30 15:19 UTC, PutinVVV approved these changes

2024-11-01 15:58 UTC, DSolo03 commented on tasks/mpi/solovyev_d_vector_max/func_tests/main.cpp
> +#include "mpi/solovyev_d_vector_max/include/header.hpp"
Fixed, thanks

2024-11-02 00:18 UTC, merged