Кошкин Никита. Задача 1. Вариант 12. Сумма значений по столбцам матрицы.
learning-process/ppc-2024-autumn pull request #173
Opened 2024-11-03 19:29 UTC by NikitaKoshkin

Описание последовательной задачи:
создается двумерный вектор для хранения элементов матрицы. Программа вычисляет сумму для каждого столбца матрицы и сохраняет результаты в отдельный вектор.

Описание MPI задачи: распределяем строки по процессам, и каждый процесс посчитает сумму для определенного набора строк. Итоговые суммы по столбцам собираем на главном процессе.

В pre_processing() храним исходную матрицу в одномерном векторе input_ (размером rows * columns);
2.1) В run() используем broadcast для передачи значений rows (строчки) и columns (столбцы);
2.2) Главный процесс (с ранком 0) делит строки матрицы между процессами, каждому процессу отправляется отрезок данных (несколько строк матрицы) через send();
2.3) Остальные процессы получают свои строки через recv() и сохраняют их в local_input_;
Каждый процесс выполняет суммирование по столбцам на своём куске матрицы (в local_input_) и сохраняет результаты в local_res;
В конце run() через функцию reduce() выполняется суммирование результатов локально обработки (local_res) от всех процессов и сохраняет итоговую сумму по каждому столбцу в векторе res на главном процессе.
Кошкин Никита. Задача 1. Вариант 12. Сумма значений по столбцам матрицы.

2024-11-04 06:33 UTC, m1likus requested changes

2024-11-04 06:33 UTC, m1likus commented on tasks/mpi/koshkin_n_sum_values_by_columns_matrix/src/ops_mpi.cpp
> +std::vector<int> koshkin_n_sum_values_by_columns_matrix_mpi::getRandomVector(int sz) {
Можно перенести этот метод в тесты, потому что только там он используется

2024-11-04 06:33 UTC, m1likus commented on tasks/mpi/koshkin_n_sum_values_by_columns_matrix/func_tests/main.cpp
> +TEST(koshkin_n_sum_values_by_columns_matrix_MPI, Test_SquareMatrixSmall) {
Добавить тест на пустую матрицу

2024-11-04 15:00 UTC, Napkin-AI commented on tasks/seq/koshkin_n_sum_values_by_columns_matrix/func_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
remove comment

2024-11-04 15:00 UTC, Napkin-AI commented on tasks/seq/koshkin_n_sum_values_by_columns_matrix/include/ops_seq.hpp
> +// Copyright 2023 Nesterov Alexander
remove comment

2024-11-04 15:00 UTC, Napkin-AI commented on tasks/seq/koshkin_n_sum_values_by_columns_matrix/perf_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
remove comment

2024-11-04 15:00 UTC, Napkin-AI commented on tasks/seq/koshkin_n_sum_values_by_columns_matrix/src/ops_seq.cpp
> +// Copyright 2024 Nesterov Alexander
remove comment

2024-11-04 15:00 UTC, Napkin-AI commented on tasks/mpi/koshkin_n_sum_values_by_columns_matrix/src/ops_mpi.cpp
> +// Copyright 2023 Nesterov Alexander
remove comment

2024-11-04 15:00 UTC, Napkin-AI commented on tasks/mpi/koshkin_n_sum_values_by_columns_matrix/perf_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
remove comment

2024-11-04 15:01 UTC, Napkin-AI commented on tasks/mpi/koshkin_n_sum_values_by_columns_matrix/include/ops_mpi.hpp
> +// Copyright 2023 Nesterov Alexander
remove comment

2024-11-04 15:01 UTC, Napkin-AI commented on tasks/mpi/koshkin_n_sum_values_by_columns_matrix/func_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
remove comment

2024-11-04 15:36 UTC, m1likus commented on tasks/mpi/koshkin_n_sum_values_by_columns_matrix/include/ops_mpi.hpp
> +  std::vector<int> res, input_, local_input_;
I believe that's fine, it's just about format

2024-11-04 15:37 UTC, m1likus requested changes

2024-11-04 15:37 UTC, m1likus commented on tasks/mpi/koshkin_n_sum_values_by_columns_matrix/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
Delete using namespace, it's not used here at all

2024-11-04 16:02 UTC, NikitaKoshkin commented on tasks/mpi/koshkin_n_sum_values_by_columns_matrix/include/ops_mpi.hpp
> +  std::vector<int> res, input_, local_input_;
he didn't complain about it

2024-11-04 16:22 UTC, NikitaKoshkin commented on tasks/mpi/koshkin_n_sum_values_by_columns_matrix/src/ops_mpi.cpp
> +std::vector<int> koshkin_n_sum_values_by_columns_matrix_mpi::getRandomVector(int sz) {
перенесено

2024-11-04 16:22 UTC, NikitaKoshkin commented on tasks/seq/koshkin_n_sum_values_by_columns_matrix/src/ops_seq.cpp
> +  uint8_t* inputMatrix = taskData->inputs[0];
corrected

2024-11-04 16:22 UTC, NikitaKoshkin commented on tasks/seq/koshkin_n_sum_values_by_columns_matrix/src/ops_seq.cpp
> +      // std::cout << "input_[" << i << "][" << j << "] = " << input_[i][j] << std::endl;
removed

2024-11-04 16:22 UTC, NikitaKoshkin commented on tasks/seq/koshkin_n_sum_values_by_columns_matrix/src/ops_seq.cpp
> +    // std::cout << "res[" << j << "] = " << res[j] << std::endl; // for debugging
removed

2024-11-04 16:22 UTC, NikitaKoshkin commented on tasks/seq/koshkin_n_sum_values_by_columns_matrix/src/ops_seq.cpp
> +  uint8_t* outputSums = taskData->outputs[0];
corrected

2024-11-04 16:22 UTC, NikitaKoshkin commented on tasks/seq/koshkin_n_sum_values_by_columns_matrix/func_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
removed

2024-11-04 16:23 UTC, NikitaKoshkin commented on tasks/seq/koshkin_n_sum_values_by_columns_matrix/include/ops_seq.hpp
> +// Copyright 2023 Nesterov Alexander
removed

2024-11-04 16:23 UTC, NikitaKoshkin commented on tasks/seq/koshkin_n_sum_values_by_columns_matrix/perf_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
removed

2024-11-04 16:23 UTC, NikitaKoshkin commented on tasks/mpi/koshkin_n_sum_values_by_columns_matrix/src/ops_mpi.cpp
> +// Copyright 2023 Nesterov Alexander
removed

2024-11-04 16:23 UTC, NikitaKoshkin commented on tasks/mpi/koshkin_n_sum_values_by_columns_matrix/perf_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
removed

2024-11-04 16:23 UTC, NikitaKoshkin commented on tasks/mpi/koshkin_n_sum_values_by_columns_matrix/func_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
removed

2024-11-04 16:23 UTC, NikitaKoshkin commented on tasks/mpi/koshkin_n_sum_values_by_columns_matrix/src/ops_mpi.cpp
> +  uint8_t* inputMatrix = taskData->inputs[0];
corrected

2024-11-04 16:23 UTC, NikitaKoshkin commented on tasks/mpi/koshkin_n_sum_values_by_columns_matrix/src/ops_mpi.cpp
> +    reinterpret_cast<int*>(outputSums)[j] = res[j];
corrected

2024-11-04 16:23 UTC, NikitaKoshkin commented on tasks/mpi/koshkin_n_sum_values_by_columns_matrix/src/ops_mpi.cpp
> +        input_[i * columns + j] = reinterpret_cast<int*>(inputMatrix)[i * columns + j];
corrected

2024-11-04 16:23 UTC, NikitaKoshkin commented on tasks/mpi/koshkin_n_sum_values_by_columns_matrix/src/ops_mpi.cpp
> +      reinterpret_cast<int*>(outputSums)[j] = res[j];
corrected

2024-11-04 16:23 UTC, NikitaKoshkin commented on tasks/mpi/koshkin_n_sum_values_by_columns_matrix/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
removed

2024-11-04 16:57 UTC, m1likus approved these changes

2024-11-04 17:46 UTC, Napkin-AI approved these changes

2024-11-04 21:23 UTC, NikitaKoshkin commented on tasks/mpi/koshkin_n_sum_values_by_columns_matrix/src/ops_mpi.cpp
> +  int extra_rows = rows % world.size();
updated

2024-11-04 21:45 UTC, allnes approved these changes

2024-11-05 00:27 UTC, aobolensk approved these changes

2024-11-05 00:27 UTC, merged