Махов Михаил. Задача 1. Вариант 27. Подсчет числа несовпадающих символов двух строк.
learning-process/ppc-2024-autumn pull request #174
Opened 2024-11-03 20:33 UTC by SingularityNN

Описание последовательного решения:
Задаются две строки типа std::string, от 0 до длины меньшей строки обходим каждый символ в строках и попарно сравниваем их, увеличиваем счетчик, если обнаруживаем различие. В конце обхода к ответу прибавляем разницу в длинах строк.

Описание MPI решения :
Вычисляем разницу в длинах строк, от большей по длине строки отбрасываем конец, уравнивая длины строк. Каждый процесс получает одинаковый по размеру сегмент из каждой строки и ищет количество различных символов в этом сегменте. Финальный результат вычисляется из суммы результатов каждого процесса и разницы в изначальной длине строк

2024-11-03 22:57 UTC, MaxikGuy requested changes
There is no tests covering the "string with zero size" situation in seq and mpi tests, please add them.

2024-11-04 19:47 UTC, allnes requested changes

2024-11-04 19:47 UTC, allnes commented on tasks/mpi/makhov_m_num_of_diff_elements_in_two_str/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
what do you use it for?

2024-11-04 19:47 UTC, allnes commented on tasks/seq/makhov_m_num_of_diff_elements_in_two_str/src/ops_seq.cpp
> +using namespace std::chrono_literals;
what do you use it for?

2024-11-05 13:49 UTC, aobolensk requested changes

2024-11-05 13:49 UTC, aobolensk commented on tasks/mpi/makhov_m_num_of_diff_elements_in_two_str/func_tests/main.cpp
> +TEST(makhov_m_num_of_diff_elements_in_two_str_mpi, SameEmptySymbolsStrings) {
Please, add random strings tests

2024-11-05 13:49 UTC, aobolensk commented on tasks/mpi/makhov_m_num_of_diff_elements_in_two_str/func_tests/main.cpp
> +}
Please, add empty strings test

2024-11-09 11:13 UTC, aobolensk requested changes

2024-11-09 11:13 UTC, aobolensk commented on tasks/mpi/makhov_m_num_of_diff_elements_in_two_str/perf_tests/main.cpp
> +}
Please, move test functions to the test module

2024-11-09 11:13 UTC, aobolensk commented on tasks/seq/makhov_m_num_of_diff_elements_in_two_str/func_tests/main.cpp
> +TEST(makhov_m_num_of_diff_elements_in_two_str_seq, SameEmptySymbolsStrings) {
Please, extend seq tests as well

2024-11-09 11:53 UTC, SingularityNN commented on tasks/mpi/makhov_m_num_of_diff_elements_in_two_str/perf_tests/main.cpp
> +}
What exactly do you mean by test module? Isn't getRandStr already in the test module - perf_tests?

2024-11-10 00:57 UTC, allnes approved these changes

2024-11-10 00:58 UTC, aobolensk commented on tasks/mpi/makhov_m_num_of_diff_elements_in_two_str/perf_tests/main.cpp
> +}
It should not be defines in implementation header. Test code should be isolated from the actual implementation

2024-11-10 14:18 UTC, MaxikGuy approved these changes

2024-11-10 14:20 UTC, ArtemMakadrai requested changes

2024-11-10 14:20 UTC, ArtemMakadrai commented on tasks/mpi/makhov_m_num_of_diff_elements_in_two_str/include/ops_mpi.hpp
> +int countDiffElem(std::string str1_, std::string str2_);
It is more efficient to pass strings as constant links, especially in the case of long strings.

2024-11-10 14:20 UTC, ArtemMakadrai commented on tasks/seq/makhov_m_num_of_diff_elements_in_two_str/include/ops_seq.hpp
> +int countDiffElem(std::string str1_, std::string str2_);
It is more efficient to pass strings as constant links, especially in the case of long strings.

2024-11-10 16:36 UTC, SingularityNN commented on tasks/mpi/makhov_m_num_of_diff_elements_in_two_str/perf_tests/main.cpp
> +}
fixed

2024-11-10 18:23 UTC, ArtemMakadrai approved these changes

2024-11-11 14:12 UTC, merged