Корнеева Екатерина. Задача 1. Вариант 6. Нахождение числа нарушений упорядоченности соседних элементов вектора.
learning-process/ppc-2024-autumn pull request #175
Opened 2024-11-03 20:53 UTC by KorneevaEkaterina

**seq:** Задача сводится к подсчёту количества «нарушений упорядоченности» в числовой последовательности. Нарушение фиксируется, если предыдущий элемент больше последующего. Тестирование включает проверки на фиксированных наборах данных и случайных последовательностях разного размера, а также перформанс-тесты, которые оценивают скорость работы на больших массивах.

**mpi:** Параллельная версия задачи с использованием MPI также выполняет подсчёт «нарушений упорядоченности», но данные распределяются между процессами, каждый из которых обрабатывает свою часть последовательности. Результаты затем объединяются на основном процессе. Тестирование аналогично охватывает проверку корректности на фиксированных и случайных наборах данных, а также измерение производительности.

2024-11-03 21:15 UTC, kmichaelk requested changes

2024-11-03 21:15 UTC, kmichaelk commented on tasks/mpi/korneeva_e_num_of_orderly_violations/src/ops_mpi.cpp
> +template class korneeva_e_num_of_orderly_violations_mpi::num_of_orderly_violations<double, int>;
Remove this and move the class implementation to header file - templates should be implemented in headers as their code is required to be available at the compile-time

2024-11-03 21:15 UTC, kmichaelk commented on tasks/seq/korneeva_e_num_of_orderly_violations/src/ops_seq.cpp
> +template class korneeva_e_num_of_orderly_violations_seq::OrderlyViolationsCounter<double, int>;
Same

2024-11-03 21:15 UTC, kmichaelk commented on tasks/seq/korneeva_e_num_of_orderly_violations/include/ops_seq.hpp
> +  cntype count_orderly_violations(std::vector<iotype> data);
```suggestion
  cntype count_orderly_violations(const std::vector<iotype>& data);
```

Can be also moved out of the class

2024-11-03 21:15 UTC, kmichaelk commented on tasks/mpi/korneeva_e_num_of_orderly_violations/src/ops_mpi.cpp
> +    int remainder = (input_size < total_processes) ? 0 : input_size % total_processes;
```suggestion
    int remainder = input_size % total_processes;
```

2024-11-03 21:15 UTC, kmichaelk commented on tasks/mpi/korneeva_e_num_of_orderly_violations/src/ops_mpi.cpp
> +    int chunk_size = (input_size < total_processes) ? 1 : input_size / total_processes;
Add tests for 2, 3, 4 as elements count

2024-11-03 21:15 UTC, kmichaelk commented on tasks/mpi/korneeva_e_num_of_orderly_violations/src/ops_mpi.cpp
> +    }
This situation is not possible currently, but I think it would be a subject to change

2024-11-03 21:22 UTC, kmichaelk commented
Some threads has been marked as outdated due to formatting changes, they're still actual actually

2024-11-03 21:38 UTC, kmichaelk commented on tasks/mpi/korneeva_e_num_of_orderly_violations/func_tests/main.cpp
> +  korneeva_e_num_of_orderly_violations_mpi::num_of_orderly_violations<int, int> task(data_seq);
suggestion: use type aliases to make a strong tie between template parameters and input/output types

2024-11-03 22:59 UTC, kmichaelk commented on tasks/mpi/korneeva_e_num_of_orderly_violations/src/ops_mpi.cpp
> +    std::memcpy(dest_ptr, source_ptr, sizeof(iotype) * input_size);
Prefer using `std::copy` to avoid accessing vector's internal buffer

2024-11-03 23:02 UTC, kmichaelk commented on tasks/mpi/korneeva_e_num_of_orderly_violations/src/ops_mpi.cpp
> +  }
You can do that while scattering the data over processes, it should be more clear and less expensive

2024-11-04 19:49 UTC, allnes requested changes

2024-11-04 19:49 UTC, allnes commented on tasks/mpi/korneeva_e_num_of_orderly_violations/src/ops_mpi.cpp
> +  int remainder = (input_size < total_processes) ? 0 : input_size % total_processes;
please calulate it one time and then broadcast

2024-11-04 20:42 UTC, kmichaelk approved these changes

2024-11-05 13:52 UTC, aobolensk requested changes

2024-11-05 13:52 UTC, aobolensk commented on tasks/mpi/korneeva_e_num_of_orderly_violations/include/ops_mpi.hpp
> +  boost::mpi::broadcast(mpi_comm, input_size, 0);
Please, move data transfer to ::run()

2024-11-06 15:34 UTC, aobolensk requested changes

2024-11-06 15:34 UTC, aobolensk commented on tasks/mpi/korneeva_e_num_of_orderly_violations/func_tests/main.cpp
> +TEST(korneeva_e_num_of_orderly_violations_mpi, NoViolations_SingleElement) {
Please, add some random tests

2024-11-06 18:31 UTC, allnes approved these changes

2024-11-07 09:08 UTC, belovtut commented on tasks/mpi/korneeva_e_num_of_orderly_violations/include/ops_mpi.hpp
> +    output_ptr[0] = violation_count_;
no need to use a temporary variable

2024-11-07 09:36 UTC, belovtut approved these changes

2024-11-07 14:01 UTC, aobolensk approved these changes

2024-11-07 14:02 UTC, merged