Ковальчук Александр. Задача 1. Вариант 13.  Максимальное значение элементов матрицы.
learning-process/ppc-2024-autumn pull request #181
Opened 2024-11-04 02:26 UTC by KADCHDR

Решение последовательной задачи:
Проходим по каждой строке матрицы, сравнивая максимальное значение с общим максимальным значением матрицы
Решение MPI задачи:
Матрица разбивается между процессами, каждый процесс находит своё максимальное значение в выделенной ему части матрицы, затем определяется общий локальный максимум.

2024-11-04 02:49 UTC, keshaproger approved these changes
Вроде нормально все

2024-11-04 15:18 UTC, keshaproger requested changes

2024-11-04 15:18 UTC, keshaproger commented on tasks/mpi/kovalchuk_a_max_of_vector_elements/func_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
change: // Copyright 2023 Nesterov Alexandr
to: // Copyright 2024 Kovalchuk Alexandr

2024-11-04 15:20 UTC, keshaproger commented on tasks/mpi/kovalchuk_a_max_of_vector_elements/include/ops_mpi.hpp
> +// Copyright 2023 Nesterov Alexander
change: // Copyright 2023 Nesterov Alexandr
to: // Copyright 2024 Kovalchuk Alexandr

2024-11-04 15:20 UTC, keshaproger requested changes

2024-11-04 15:20 UTC, keshaproger commented on tasks/mpi/kovalchuk_a_max_of_vector_elements/perf_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
change: // Copyright 2023 Nesterov Alexandr
to: // Copyright 2024 Kovalchuk Alexandr

2024-11-04 15:24 UTC, keshaproger requested changes

2024-11-04 15:24 UTC, keshaproger commented on tasks/mpi/kovalchuk_a_max_of_vector_elements/src/ops_mpi.cpp
> +      world.send(proc, 0, input_.data() + delta * proc, delta);
Add buffer check and use:
std::span

2024-11-04 15:55 UTC, antihype320 approved these changes

2024-11-04 19:54 UTC, allnes commented
@antihype320 your review is not accepted

2024-11-04 19:55 UTC, allnes commented
@keshaproger your review is not accepted too

2024-11-04 19:56 UTC, allnes requested changes

2024-11-04 19:56 UTC, allnes commented on tasks/mpi/korablev_v_rect_int_mpi/func_tests/main.cpp
> -}
please don't change not own files

2024-11-04 19:56 UTC, allnes commented on tasks/mpi/kovalchuk_a_max_of_vector_elements/src/ops_mpi.cpp
> +std::vector<int> kovalchuk_a_max_of_vector_elements::getRandomVector(int sz, int min, int max) {
please move this functions to tests files

2024-11-05 12:40 UTC, keshaproger requested changes

2024-11-05 12:40 UTC, keshaproger commented on tasks/mpi/korablev_v_rect_int_mpi/func_tests/main.cpp
> +}
Add one more empty line for fix the bug.

2024-11-05 13:47 UTC, myffii requested changes

2024-11-05 13:47 UTC, myffii commented on tasks/mpi/kovalchuk_a_max_of_vector_elements/func_tests/main.cpp
> +TEST(kovalchuk_a_max_of_vector_elements, Test_Max_10_10) {
add empty matrix test

2024-11-05 13:47 UTC, myffii commented on tasks/seq/kovalchuk_a_max_of_vector_elements/func_tests/main.cpp
> +TEST(kovalchuk_a_max_of_vector_elements_seq, Test_Max_10_10) {
add empty matrix test too

2024-11-05 13:50 UTC, myffii requested changes

2024-11-05 13:50 UTC, myffii commented on tasks/mpi/kovalchuk_a_max_of_vector_elements/src/ops_mpi.cpp
> +  }
add empty matrix check

2024-11-05 13:50 UTC, myffii commented on tasks/mpi/kovalchuk_a_max_of_vector_elements/src/ops_mpi.cpp
> +    local_input_ = std::vector<int>(input_.begin(), input_.begin() + delta);
add empty matrix check

2024-11-05 13:55 UTC, aobolensk requested changes

2024-11-05 13:55 UTC, aobolensk commented on tasks/mpi/kovalchuk_a_max_of_vector_elements/include/ops_mpi.hpp
> +std::vector<std::vector<int>> getRandomMatrix(int rows, int columns, int min = MINIMALGEN, int max = MAXIMUMGEN);
Please, move to test modules

2024-11-05 13:55 UTC, aobolensk commented on tasks/mpi/kovalchuk_a_max_of_vector_elements/perf_tests/main.cpp
> +    int count_columns = 999;
Too small sizes for perf test

2024-11-05 13:55 UTC, aobolensk commented on tasks/mpi/kovalchuk_a_max_of_vector_elements/func_tests/main.cpp
> +TEST(kovalchuk_a_max_of_vector_elements, Test_Max_100_100) {
Too few tests, actually, please test corner cases

2024-11-06 15:37 UTC, aobolensk commented on tasks/mpi/kovalchuk_a_max_of_vector_elements/include/ops_mpi.hpp
> +std::vector<std::vector<int>> getRandomMatrix(int rows, int columns, int min = MINIMALGEN, int max = MAXIMUMGEN);
This part was not fixed

2024-11-06 15:39 UTC, aobolensk approved these changes

2024-11-06 18:10 UTC, keshaproger approved these changes

2024-11-06 18:33 UTC, allnes approved these changes

2024-11-06 18:33 UTC, merged