Коньков Иван. Задача 1. Вариант 24. Подсчет слов в строке.
learning-process/ppc-2024-autumn pull request #187
Opened 2024-11-04 04:28 UTC by keshaproger

**Описание задачи**
**Задача:** Подсчет количества слов в строке с использованием MPI и последовательного подхода.

**Функциональность:**

**MPI:** Реализован параллельный подсчет слов в строке с использованием MPI. Каждый процесс обрабатывает свою часть строки, подсчитывает количество слов в этой части и передает результат на процесс с рангом 0, который суммирует результаты от всех процессов.
**Последовательный подход:** Реализован последовательный подсчет слов в строке. Строка разбивается на слова с использованием потока ввода и подсчитывается количество слов.

**Тестирование:**

**Функциональные тесты:** Проверяют корректность подсчета слов для различных входных строк (пустая строка, строка с одним словом, строка с несколькими словами).
**Тесты производительности:** Оценивают время выполнения задачи для последовательного и параллельного подходов.

2024-11-04 14:53 UTC, KADCHDR requested changes

2024-11-04 14:53 UTC, KADCHDR commented on tasks/mpi/konkov_i_count_words/func_tests/main.cpp
> +  std::string input = "";
It's better this way:  std::string input;

2024-11-04 14:53 UTC, KADCHDR commented on tasks/seq/konkov_i_count_words/func_tests/main.cpp
> +  std::string input = "";
It's better this way too:  std::string input;

2024-11-04 14:53 UTC, KADCHDR commented on tasks/mpi/konkov_i_count_words/src/ops_mpi.cpp
> +
Extra line causing an error Clang-format

2024-11-04 15:39 UTC, KADCHDR approved these changes

2024-11-04 15:41 UTC, antihype320 approved these changes

2024-11-04 19:56 UTC, allnes commented
@antihype320 your review is not accpeted

2024-11-04 19:59 UTC, allnes requested changes

2024-11-04 19:59 UTC, allnes commented on tasks/mpi/konkov_i_count_words/src/ops_mpi.cpp
> +bool konkov_i_count_words_mpi::CountWordsTaskParallel::pre_processing() {
please use all mpi functions in run()

2024-11-04 19:59 UTC, allnes commented on tasks/mpi/konkov_i_count_words/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, input_, 0);
please do not duplicate input in each process

2024-11-05 13:43 UTC, myffii requested changes

2024-11-05 13:43 UTC, myffii commented on tasks/mpi/konkov_i_count_words/src/ops_mpi.cpp
> +  }
You need to remove these lines from pre_processing():
if (world.rank() == 0) {
input_ = *reinterpret_cast<std::string*>(taskData->inputs[0]);
}
and insert them into run() changing world.rank() to rank, since the rank variable is already defined, in order to avoid duplicates:
if (rank == 0) {
input_ = *reinterpret_cast<std::string*>(taskData->inputs[0]);
}

2024-11-05 13:43 UTC, myffii commented on tasks/mpi/konkov_i_count_words/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, input_, 0);
Move the broadcast function from pre_processing() to run():
boost::mpi::broadcast(world, input_, 0);

2024-11-05 13:57 UTC, aobolensk requested changes

2024-11-05 13:57 UTC, aobolensk commented on tasks/mpi/konkov_i_count_words/func_tests/main.cpp
> +TEST(konkov_i_count_words_mpi, Test_Empty_String) {
Too few tests, please add more for corner cases

2024-11-05 13:57 UTC, aobolensk commented on tasks/mpi/konkov_i_count_words/func_tests/main.cpp
> +}
Please, add random test cases as well

2024-11-05 13:57 UTC, aobolensk commented on tasks/mpi/konkov_i_count_words/perf_tests/main.cpp
> +  std::string input = "Hello world this is a test";
Perf tests should be performed on big strings

2024-11-05 13:57 UTC, aobolensk commented on tasks/mpi/konkov_i_count_words/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, input_, 0);
Do not transfer all input data to all processes

2024-11-05 14:09 UTC, keshaproger commented on tasks/mpi/konkov_i_count_words/src/ops_mpi.cpp
> +bool konkov_i_count_words_mpi::CountWordsTaskParallel::pre_processing() {
fixed

2024-11-05 14:21 UTC, keshaproger commented on tasks/mpi/konkov_i_count_words/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, input_, 0);
fix

2024-11-05 14:21 UTC, keshaproger commented on tasks/mpi/konkov_i_count_words/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, input_, 0);
fix

2024-11-05 14:22 UTC, keshaproger commented on tasks/mpi/konkov_i_count_words/src/ops_mpi.cpp
> +  }
fix

2024-11-05 21:29 UTC, keshaproger commented on tasks/mpi/konkov_i_count_words/perf_tests/main.cpp
> +  std::string input = "Hello world this is a test";
fixed

2024-11-05 21:29 UTC, keshaproger commented on tasks/mpi/konkov_i_count_words/func_tests/main.cpp
> +}
added

2024-11-05 21:29 UTC, keshaproger commented on tasks/mpi/konkov_i_count_words/func_tests/main.cpp
> +TEST(konkov_i_count_words_mpi, Test_Empty_String) {
added

2024-11-05 23:05 UTC, keshaproger commented on tasks/mpi/konkov_i_count_words/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, input_, 0);
fixed

2024-11-05 23:14 UTC, keshaproger commented on tasks/mpi/konkov_i_count_words/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, input_, 0);
fixed

2024-11-06 12:55 UTC, myffii approved these changes

2024-11-06 15:40 UTC, aobolensk requested changes

2024-11-06 15:40 UTC, aobolensk commented on tasks/mpi/konkov_i_count_words/func_tests/main.cpp
> +bool konkov_i_count_words_mpi::CountWordsTaskParallel::pre_processing() {
You have implementation in tests module

2024-11-06 18:34 UTC, allnes approved these changes

2024-11-06 18:39 UTC, keshaproger commented on tasks/mpi/konkov_i_count_words/func_tests/main.cpp
> +bool konkov_i_count_words_mpi::CountWordsTaskParallel::pre_processing() {
Mistake, sorry

2024-11-06 23:53 UTC, aobolensk approved these changes

2024-11-06 23:53 UTC, merged