Отурин Александр. Задача 1. Вариант 15. Нахождение максимальных значений по строкам матрицы.
learning-process/ppc-2024-autumn pull request #188
Opened 2024-11-04 05:55 UTC by ovVrLFg8ks

**_Это доработка #75 , который был зареверчен #183_**  

**Описание последовательной задачи:**
Для каждой строки m вычисляется максимум и записывается в вектор максимумов размера m.

**Описание MPI задачи:**
Каждый процесс получает ширину и высоту матрицы (n и m соответственно), процесс 0-го ранга получает матрицу как одномерный вектор и вектор для записи результатов.
Далее в процессе 0-го ранга:
Основываясь на количестве процессов ненулевого ранга запускается цикл, в котором процессам, которым будет послана строка размера n посылается сигнал, затем и сама строка. После в этом же цикле 0-ой процесс получает от ненулевых процессов результат. Если количество процессов превышает кол-во строк в итерации цикла, то им пока что не посылается ничего. После цикла всем процессам посылается сигнал о завершении работы.
В процессах ненулевого ранга:
Запускается цикл, в котором сначала проверяется сигнал о выходе, и если сигнал невыходной, получается строка, у которой вычисляется максимум, который отправляется нулевому процессу.

2024-11-04 09:34 UTC, DSolo03 approved these changes

2024-11-04 11:25 UTC, ovVrLFg8ks commented
![image](https://github.com/user-attachments/assets/5b4e0fb0-34c7-4208-933a-0697df6b8896)
👍

2024-11-04 13:14 UTC, artich02 approved these changes

2024-11-04 15:15 UTC, ovVrLFg8ks commented
test_pipeline_run & test_task_run total results (on my machine):


1000x1000
| world size | time |
| ---------- | ------- |
| 2  | 101ms |
| 3 | 87ms |
| 4 | 87ms |
| 5 | 91ms |
| 6 | 94ms |

2000x2000
| world size | time |
| ---------- | ------- |
| 2  | 597ms |
| 3 | 500ms |
| 4 | 481ms |
| 5 | 450ms |
| 6 | 438ms |

3000x3000
| world size | time |
| ---------- | ------- |
| 2  | 1284ms |
| 3 | 1177ms |
| 4 | 1060ms |
| 5 | 1097ms |
| 6 | 1045ms |

2024-11-04 20:00 UTC, allnes commented
@DSolo03 @artich02 yours approvals iss not accepted

2024-11-04 20:01 UTC, allnes requested changes

2024-11-04 20:01 UTC, allnes commented on tasks/seq/oturin_a_max_values_by_rows_matrix/src/ops_seq.cpp
> +using namespace std::chrono_literals;
what do you use it for?

2024-11-04 21:04 UTC, ovVrLFg8ks commented on tasks/seq/oturin_a_max_values_by_rows_matrix/src/ops_seq.cpp
> +using namespace std::chrono_literals;
`using namespace std::chrono_literals;` is a rudiment from the example/src/ops_seq.cpp

Removed

2024-11-04 21:06 UTC, ovVrLFg8ks commented
> @DSolo03 @artich02 yours approvals iss not accepted

@allnes, Why are theese approvals not accepted? They were participating in #75!

2024-11-04 21:40 UTC, DSolo03 requested changes

2024-11-04 21:40 UTC, DSolo03 commented on tasks/seq/oturin_a_max_values_by_rows_matrix/src/ops_seq.cpp
> +  }
please, use vector constructor instead of loop, like in mpi case

2024-11-05 06:04 UTC, ovVrLFg8ks commented on tasks/seq/oturin_a_max_values_by_rows_matrix/src/ops_seq.cpp
> +  }
Changed

2024-11-05 07:23 UTC, DSolo03 approved these changes

2024-11-06 18:36 UTC, allnes approved these changes

2024-11-06 18:36 UTC, merged