Соловьев Данила. Задача 1. Вариант 3. Максимальное значение элементов вектора.
learning-process/ppc-2024-autumn pull request #190
Opened 2024-11-04 09:04 UTC by DSolo03

_Fixed #17 than was reverted in #179_

Описание последовательной задачи: Для каждого из элементов вектора, сравниваем его значение со значением переменной, в которой хранится максимальное значение вектора. Если значение данного элемента вектора больше чем значение переменной, то записываем значение данного элемента вектора в переменную.

Описание MPI задачи: Делим входные данные на несколько фрагментов, количество которых является количеством возможных процессов. Каждый из фрагментов, кроме первого, отдаем на исполнение соответствующим процессам. Первый фрагмент будет обработан в том же процессе, что и разделял данные. В каждом из процессов, ищется максимальное значение данного ему фрагмента, соответственно последовательной задачи, и из каждого из процессов, собирается максимальное из всех значений при помощи функции reduce с оператором maximum. Максимальное значение записывается в переменную result и возвращается.

2024-11-04 20:02 UTC, allnes requested changes

2024-11-04 20:02 UTC, allnes commented on tasks/mpi/solovyev_d_vector_max/src/source.cpp
> +using namespace std::chrono_literals;
what do you use it for?

2024-11-04 20:02 UTC, allnes commented on tasks/mpi/solovyev_d_vector_max/src/source.cpp
> +  int m = -214748364;
please use std::numeric_limits<T>::min

2024-11-04 21:34 UTC, DSolo03 commented on tasks/mpi/solovyev_d_vector_max/src/source.cpp
> +using namespace std::chrono_literals;
Fixed, thanks

2024-11-04 21:34 UTC, DSolo03 commented on tasks/mpi/solovyev_d_vector_max/src/source.cpp
> +  int m = -214748364;
Fixed, thanks

2024-11-04 21:44 UTC, allnes approved these changes

2024-11-05 08:20 UTC, ovVrLFg8ks requested changes

2024-11-05 08:20 UTC, ovVrLFg8ks commented on tasks/mpi/solovyev_d_vector_max/func_tests/main.cpp
> +  std::cerr << "1 " << world.rank() << std::endl;
Remove std::cerr ftom 27, 36, 42 lines

2024-11-05 09:14 UTC, DSolo03 commented on tasks/mpi/solovyev_d_vector_max/func_tests/main.cpp
> +  std::cerr << "1 " << world.rank() << std::endl;
Fixed, thanks

2024-11-05 09:54 UTC, ovVrLFg8ks approved these changes

2024-11-05 13:59 UTC, aobolensk approved these changes

2024-11-05 16:20 UTC, ascannel requested changes

2024-11-05 16:20 UTC, ascannel commented on tasks/mpi/solovyev_d_vector_max/src/source.cpp
> +  result = 0;
there is no need to set the variable to zero, because it is already set to zero in the result{} constructor

2024-11-05 17:03 UTC, ascannel approved these changes

2024-11-06 15:35 UTC, merged