Бурыкин Михаил. Задача 1. Вариант 24. Подсчёт числа слов в строке.
learning-process/ppc-2024-autumn pull request #192
Opened 2024-11-04 11:20 UTC by WholeHorse

#### Описание последовательного алгоритма:
- Если входные данные присутствуют, они считываются из taskData->inputs[0] и преобразуются в строку input_. Если данные отсутствуют, input_ устанавливается как пустая строка.
- Подсчет слов выполняется вызовом функции count_words(), которая принимает input_ и возвращает число слов. Результат записывается в word_count_.
- Для определения, является ли символ частью слова, используется метод is_word_character(). Он возвращает true, если символ является буквой или апострофом.
- Когда символ является началом нового слова, увеличивается счетчик count, а флаг in_word устанавливается в true. Если обнаружен символ, не являющийся частью слова, флаг in_word сбрасывается.
#### Описание MPI алгоритма:
- На этапе pre_processing():
  - Каждый процесс инициализирует переменную length, хранящую длину входных данных.
  - Процесс с рангом 0 (нулевой процесс) считывает входную строку из taskData->inputs[0] и сохраняет ее в вектор input_, чтобы позже распределить части строки между процессами.
  - Инициализируется счетчик word_count_ для хранения общего количества слов.
- На этапе run():
  - Если длина строки length равна нулю, процесс завершает выполнение без дополнительных операций.
  - В случае, когда в MPI-коммуникаторе участвует только один процесс, весь подсчет слов выполняется этим процессом, который просто подсчитывает символы-разделители слов.
  - Если несколько процессов участвуют, нулевой процесс (с рангом 0) распределяет строку на части для параллельной обработки:
    - Вычисляется размер части строки partSize, которую обрабатывает каждый процесс, за исключением последнего, который может получить более короткую часть, чтобы охватить всю строку.
    - Нулевой процесс отправляет каждому процессу часть строки. Все процессы, включая последний, получают ровно один фрагмент для обработки.
  - Нулевой процесс собирает результаты от всех процессов:
    - Каждый процесс считает количество разделителей слов в своей части строки и отправляет результат обратно нулевому процессу.
    - Нулевой процесс получает результаты от всех процессов, суммирует их, а также добавляет 1 к общему числу слов (так как разделители отделяют слова). 
- Каждый процесс получает свою часть строки (вектор chunk) и проходит по каждому символу, используя функцию is_word_character() для проверки, является ли символ частью слова.
- Процесс увеличивает счетчик для каждого обнаруженного разделителя слов.
- На этапе post_processing():
  - Нулевой процесс записывает итоговое количество слов в taskData->outputs[0] для дальнейшего использования или вывода.

2024-11-04 12:44 UTC, ovVrLFg8ks commented on tasks/mpi/burykin_m_word_count/src/ops_mpi.cpp
> +  }
You can improve code coverage with 
```suggestion
#if defined(_MSC_VER) && !defined(__clang__)
  if (world.size() == 1) {
    for (int i = 0; i < length; i++) {
      if (!is_word_character(input_[i])) word_count_++;
    }
    word_count_++;
    return true;
  }
#endif
```

2024-11-04 12:44 UTC, ovVrLFg8ks commented on tasks/mpi/burykin_m_word_count/src/ops_mpi.cpp
> +  if (world.rank() > length) {
Add test with short vector (size<5?) to better cover this

2024-11-04 13:06 UTC, WholeHorse commented on tasks/mpi/burykin_m_word_count/src/ops_mpi.cpp
> +  if (world.rank() > length) {
done

2024-11-04 13:22 UTC, ovVrLFg8ks approved these changes

2024-11-04 14:12 UTC, DSFKnight approved these changes

2024-11-04 15:20 UTC, DSFKnight requested changes
"is_word_character" function is not covered in the tests.

2024-11-04 15:29 UTC, WholeHorse commented
> "is_word_character" function is not covered in the tests.

done

2024-11-04 15:54 UTC, DSFKnight approved these changes

2024-11-04 20:04 UTC, allnes requested changes

2024-11-04 20:04 UTC, allnes commented on tasks/seq/burykin_m_word_count/src/ops_seq.cpp
> +using namespace std::chrono_literals;
what do you use it for?

2024-11-04 20:18 UTC, allnes approved these changes

2024-11-05 00:27 UTC, aobolensk approved these changes

2024-11-05 00:28 UTC, merged