Revert "Гордеева Таисия. Задача 1. Вариант 16. Нахождение максимальных значений по столбцам матрицы"
learning-process/ppc-2024-autumn pull request #193
Opened 2024-11-04 11:30 UTC by TayaGordeeva

Reverts learning-process/ppc-2024-autumn#180

Ошибка заключалась в том, что один из тестов отрабатывал больше 1 секунды. Собственно, так тест работал из-за большого размера матрицы. Ошибка исправлена

**Описание программы.**
Программа вычисляет максимальное значение в каждом столбце матрицы.

_-Последовательная задача:_
изначально максимальное значение равно первому элементу текущего столбца; происходит сравнение текущего максимального значения с каждым элементом из соответствующего столбца - если значение элемента больше, то оно становится максимальным значением
результат: вектор с максимальными значениями для каждого столбца

_-MPI задача:_
матрица разбивается на кол-во процессов
каждый процесс ищет максимум в каждом столбце своих данных
результаты процессов отправляются на главный процесс и объединяются
результат: вектор максимальных значений для каждого столбца

2024-11-04 20:06 UTC, allnes requested changes

2024-11-04 20:06 UTC, allnes commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
what do you use it for?

2024-11-04 20:06 UTC, allnes commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/src/ops_mpi.cpp
> +  broadcast(world, cols, 0);
please broadcast delta instead rows and cols

2024-11-04 20:06 UTC, allnes commented on tasks/seq/gordeva_t_max_val_of_column_matrix/src/ops_seq.cpp
> +using namespace std::chrono_literals;
what do you use it for?

2024-11-06 04:02 UTC, TayaGordeeva commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
deleted

2024-11-06 04:02 UTC, TayaGordeeva commented on tasks/seq/gordeva_t_max_val_of_column_matrix/src/ops_seq.cpp
> +using namespace std::chrono_literals;
deleted

2024-11-06 04:03 UTC, TayaGordeeva commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/src/ops_mpi.cpp
> +  broadcast(world, cols, 0);
rewritten, now delta instead rows and cols

2024-11-07 18:18 UTC, SergeyBoRss commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/include/ops_mpi.hpp
> +#include <string>
You can delete it

2024-11-07 18:38 UTC, allnes approved these changes

2024-11-08 00:23 UTC, aobolensk approved these changes

2024-11-08 13:49 UTC, Applejack2004 requested changes

2024-11-08 13:49 UTC, Applejack2004 commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/src/ops_mpi.cpp
> +#include <string>
Unused

2024-11-08 13:49 UTC, Applejack2004 commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/src/ops_mpi.cpp
> +  // int cols = input_[0].size();
Delete the commented lines.

2024-11-08 15:05 UTC, TayaGordeeva commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/include/ops_mpi.hpp
> +#include <string>
done

2024-11-08 15:05 UTC, TayaGordeeva commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/src/ops_mpi.cpp
> +#include <string>
deleted

2024-11-08 15:05 UTC, TayaGordeeva commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/src/ops_mpi.cpp
> +  // int cols = input_[0].size();
done

2024-11-08 22:52 UTC, Applejack2004 approved these changes

2024-11-09 03:02 UTC, merged