Сдобнов Владимир. Задача 1. Вариант 10. Сумма элементов матрицы.
learning-process/ppc-2024-autumn pull request #194
Opened 2024-11-04 12:35 UTC by VladimirSdobnov

_**Последовательная задача**_
Переводим матрицу в вектор и по итератору складываем элементы полученного вектора

**_Параллельная задача_**
Переводим матрицу в вектор. Высчитываем размер и смещение векторов, которые потом рассылаем по прочим процессам с помощью функции 'scatterv'. В каждом процессе по итератору считаем сумму элементов переданного вектора. В конце объединяем результаты процессов с помощью функции 'reduce'

2024-11-04 12:43 UTC, emilien-gus reviewed
It is worth adding negative validation checks with empty input and output data to mpi tests

2024-11-04 20:00 UTC, VladimirSdobnov commented
> It is worth adding negative validation checks with empty input and output data to mpi tests

I will add it with the following commit

2024-11-04 20:13 UTC, nCUXe commented on tasks/mpi/Sdobnov_V_sum_of_vector_elements/src/ops_mpi.cpp
> +bool Sdobnov_V_sum_of_vector_elements::SumVecElemParallel::run() {
In ops_mpi.cpp in the "run" function, for a parallel solution, it is desirable to store the local rank and number of processes in separate variables, rather than calling the rank() and size() methods for world

2024-11-04 20:15 UTC, VladimirSdobnov commented on tasks/mpi/Sdobnov_V_sum_of_vector_elements/src/ops_mpi.cpp
> +bool Sdobnov_V_sum_of_vector_elements::SumVecElemParallel::run() {
Accepted, I will fix it with the following commit

2024-11-04 21:16 UTC, emilien-gus approved these changes

2024-11-05 07:55 UTC, nCUXe approved these changes

2024-11-05 14:03 UTC, aobolensk requested changes

2024-11-05 14:03 UTC, aobolensk commented on tasks/mpi/Sdobnov_V_sum_of_vector_elements/include/ops_mpi.hpp
> +int vec_elem_sum(const std::vector<int>& vec);
Please, move to test modules

2024-11-05 14:03 UTC, aobolensk commented
Please, collect 2 more peer reviews

2024-11-05 17:29 UTC, VladimirSdobnov commented
> Please, collect 2 more peer reviews

From students?

2024-11-05 17:30 UTC, VladimirSdobnov commented on tasks/mpi/Sdobnov_V_sum_of_vector_elements/include/ops_mpi.hpp
> +int vec_elem_sum(const std::vector<int>& vec);
Fix with nexp commit

2024-11-05 18:23 UTC, m1likus reviewed
Add tests with 1x1 matrix and 5x1 so you test the right matrix into submatrixes division

2024-11-05 18:23 UTC, m1likus commented on tasks/mpi/Sdobnov_V_sum_of_vector_elements/src/ops_mpi.cpp
> +std::vector<int> Sdobnov_V_sum_of_vector_elements::generate_random_vector(int size, int lower_bound, int upper_bound) {
As soon as you use functions "generate_random_smth" you can transfer it to tests.cpp

2024-11-05 18:23 UTC, m1likus commented on tasks/mpi/Sdobnov_V_sum_of_vector_elements/src/ops_mpi.cpp
> +  res_ = 0;
you already have int res_{}; in hpp file, so you already initialized this variable

2024-11-05 18:23 UTC, m1likus commented on tasks/seq/Sdobnov_V_sum_of_vector_elements/src/ops_seq.cpp
> +  return res;
Same with this functions, you use them only in tests

2024-11-05 18:29 UTC, m1likus commented on tasks/seq/Sdobnov_V_sum_of_vector_elements/src/ops_seq.cpp
> +  res_ = 0;
Fix here too, you already initialized this

2024-11-05 18:38 UTC, hasanyanovk commented on tasks/mpi/Sdobnov_V_sum_of_vector_elements/src/ops_mpi.cpp
> +std::vector<int> Sdobnov_V_sum_of_vector_elements::generate_random_vector(int size, int lower_bound, int upper_bound) {
> As soon as you use functions "generate_random_smth" you can transfer it to tests.cpp

![image](https://github.com/user-attachments/assets/5b0caeab-5242-4bab-8551-ff70a93d836a)

2024-11-05 18:48 UTC, m1likus commented on tasks/mpi/Sdobnov_V_sum_of_vector_elements/src/ops_mpi.cpp
> +std::vector<int> Sdobnov_V_sum_of_vector_elements::generate_random_vector(int size, int lower_bound, int upper_bound) {
> > As soon as you use functions "generate_random_smth" you can transfer it to tests.cpp
> 
> ![image](https://private-user-images.githubusercontent.com/112872816/383273274-5b0caeab-5242-4bab-8551-ff70a93d836a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MzI3NTMsIm5iZiI6MTczMDgzMjQ1MywicGF0aCI6Ii8xMTI4NzI4MTYvMzgzMjczMjc0LTViMGNhZWFiLTUyNDItNGJhYi04NTUxLWZmNzBhOTNkODM2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxODQ3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzA1ODdlOGU1YTkzOGFhNjA2NmYxOTgzMDYwMjUzNGE2ZDEyYjZhMTUxOGM4MzAxYjIzYmMwMzFmYWVhNWJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uOpZTyxwaEFN9B_K7VSJ4FVSeGzX2ehTv8pC0pyvJMM)

👍👍👍

2024-11-05 18:57 UTC, VladimirSdobnov commented
> Add tests with 1x1 matrix and 5x1 so you test the right vector into subvectors division

I will make all the changes alone with the next commit

2024-11-06 10:28 UTC, m1likus approved these changes
You fixed everything I suggested, well done

2024-11-06 15:40 UTC, aobolensk approved these changes

2024-11-06 18:35 UTC, allnes approved these changes

2024-11-06 18:35 UTC, merged