Аникин Максим. Задача 1. Вариант 27. Подсчет числа несовпадающих символов двух строк.
learning-process/ppc-2024-autumn pull request #196
Opened 2024-11-04 13:30 UTC by decl1

Seq:
Необоходимо проходиться по меньшей строке, и сравнить символы двух строк, если они различны, прибавляем единицу к результату. Разницу в размерах строк, суммируем.
MPI:
Строка разделяется на сегменты одинаковой длины, кол-во сегментов равно количеству процессов MPI. Сегменты распределяются между процессами, внутри которого работает Seq алгоритм

2024-11-04 20:07 UTC, allnes requested changes

2024-11-04 20:07 UTC, allnes commented on tasks/seq/anikin_m_summ_of_different_symbols/src/ops_seq.cpp
> +using namespace std::chrono_literals;
what do you use it for?

2024-11-05 11:51 UTC, decl1 commented on tasks/seq/anikin_m_summ_of_different_symbols/src/ops_seq.cpp
> +using namespace std::chrono_literals;
fixed

2024-11-08 15:13 UTC, aobolensk requested changes

2024-11-09 20:23 UTC, DSolo03 requested changes

2024-11-09 20:23 UTC, DSolo03 commented on tasks/mpi/anikin_m_summ_of_different_symbols/src/ops_mpi.cpp
> +  result_ = 0;
For MPI case it is not necessary to set `result_` to 0, since `boost::mpi::reduce` later rewrites it's result in it anyway

2024-11-09 20:23 UTC, DSolo03 commented on tasks/mpi/anikin_m_summ_of_different_symbols/src/ops_mpi.cpp
> +}
Is it okay, that seq solution and mpi solution different? Looks like mpi solution doesn't work with strings with different lengths

2024-11-10 00:58 UTC, allnes approved these changes

2024-11-29 22:18 UTC, closed without merging