Поликанов Виталий. Задание 1. Вариант 3. Максимальное значение в векторе
learning-process/ppc-2024-autumn pull request #197
Opened 2024-11-04 14:04 UTC by polikanovv

Последовательная версия
Идем по массиву и ищем максимальный элемент
MPI
Делим вектор на число процессов, в каждом вычисляем максимум и среди них находим максимальный

2024-11-04 20:08 UTC, allnes requested changes

2024-11-04 20:08 UTC, allnes commented on tasks/mpi/polikanov_v_max_of_vector_elements/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
what do you use it for?

2024-11-04 20:08 UTC, allnes commented on tasks/mpi/polikanov_v_max_of_vector_elements/src/ops_mpi.cpp
> +std::vector<int> polikanov_v_max_of_vector_elements::getRandomVector(int sz, int lower, int upper) {
please move this function to tests files

2024-11-04 20:08 UTC, allnes commented on tasks/seq/polikanov_v_max_of_vector_elements/src/ops_seq.cpp
> +using namespace std::chrono_literals;
what do you use it for?

2024-11-05 19:20 UTC, polikanovv commented on tasks/mpi/polikanov_v_max_of_vector_elements/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
fixed

2024-11-05 19:20 UTC, polikanovv commented on tasks/mpi/polikanov_v_max_of_vector_elements/src/ops_mpi.cpp
> +std::vector<int> polikanov_v_max_of_vector_elements::getRandomVector(int sz, int lower, int upper) {
fixed

2024-11-05 19:20 UTC, polikanovv commented on tasks/seq/polikanov_v_max_of_vector_elements/src/ops_seq.cpp
> +using namespace std::chrono_literals;
fixed

2024-11-07 07:58 UTC, DSolo03 requested changes

2024-11-07 07:58 UTC, DSolo03 commented on tasks/mpi/polikanov_v_max_of_vector_elements/func_tests/main.cpp
> +}
Please, add this function to your namespace.

2024-11-07 07:58 UTC, DSolo03 commented on tasks/seq/polikanov_v_max_of_vector_elements/src/ops_seq.cpp
> +  }
I suggest using std::copy or vector constructor instead of a loop

2024-11-07 08:17 UTC, polikanovv commented on tasks/mpi/polikanov_v_max_of_vector_elements/func_tests/main.cpp
> +}
![image](https://github.com/user-attachments/assets/1dc74b45-3e2f-45be-85c4-bc904865e9c0)

2024-11-07 08:18 UTC, polikanovv commented on tasks/mpi/polikanov_v_max_of_vector_elements/func_tests/main.cpp
> +}
Teachers are asking you to do the opposite

2024-11-07 08:36 UTC, DSolo03 commented on tasks/mpi/polikanov_v_max_of_vector_elements/func_tests/main.cpp
> +}
Teacher asked to move function from source to tests, but not from namespace. You see, if someone else also add function with same name in test without namespace, then build will crash because of conflict. Just wrap function with 
`
namespace <namespace_name>{
<function>
}
`
That should be enough

2024-11-07 10:58 UTC, polikanovv commented on tasks/seq/polikanov_v_max_of_vector_elements/src/ops_seq.cpp
> +  }
fixed

2024-11-07 10:59 UTC, polikanovv commented on tasks/mpi/polikanov_v_max_of_vector_elements/func_tests/main.cpp
> +}
Yes, you're right, fixed

2024-11-07 18:52 UTC, KAPUSHA228 approved these changes

2024-11-08 00:25 UTC, aobolensk requested changes

2024-11-08 00:25 UTC, aobolensk commented on tasks/seq/polikanov_v_max_of_vector_elements/func_tests/main.cpp
> +    vec[i] = gen() % 100;
Please, test negative numbers as well

2024-11-08 00:25 UTC, aobolensk commented on tasks/mpi/polikanov_v_max_of_vector_elements/func_tests/main.cpp
> +TEST(polikanov_v_max_of_vector_elements_MPI, Test_Valid_false) {
Please, add emptry array test

2024-11-10 00:59 UTC, allnes approved these changes

2024-11-10 01:01 UTC, aobolensk requested changes

2024-11-10 01:01 UTC, aobolensk commented on tasks/mpi/polikanov_v_max_of_vector_elements/func_tests/main.cpp
> +  int lower = 0;
Please, add tests with negative numbers as well

2024-11-10 10:18 UTC, polikanovv commented on tasks/mpi/polikanov_v_max_of_vector_elements/func_tests/main.cpp
> +  int lower = 0;
added

2024-11-10 13:06 UTC, aobolensk approved these changes

2024-11-10 13:07 UTC, merged