Золотарева Арина. Задача 1. Вариант 24. Подсчет числа слов в строке.
learning-process/ppc-2024-autumn pull request #198
Opened 2024-11-04 17:36 UTC by andrewmeow

Описание последовательной задачи:
Создаем строку, в которой содержится текст и инициализируем счётчик слов и флаг in_word, который показывает, находимся ли мы внутри слова. Проходим по каждому символу строки: если символ — пробел, то сбрасываем флаг in_word, указывая, что мы вышли из слова. Если символ не пробел и флаг in_word сброшен, значит, начинается новое слово — увеличиваем счётчик слов и устанавливаем флаг in_word в true.

Описание параллельной задачи:
Создаем строку, в которой содержится текст, и делим её на несколько частей, в зависимости от числа доступных процессов(delta). Для каждого процесса определяем долю строки, которую он будет обрабатывать. Каждый процесс подсчитывает количество слов в своей части строки. Также мы учитываем, что слово может попасть к потоку не целым. Затем результаты от каждого процесса собираются и суммируются для получения общего количества слов.

2024-11-04 21:01 UTC, KAPUSHA228 requested changes
добавить .data() и .size() по примеру строчки выше

2024-11-04 21:08 UTC, andrewmeow commented on tasks/mpi/zolotareva_a_count_of_words/func_tests/main.cpp
> +    taskDataPar->outputs.emplace_back(reinterpret_cast<uint8_t *>(&global_count));
.data() поправила, размер константный всегда 1 по задаче

2024-11-04 22:26 UTC, DZaytsev4 commented on tasks/mpi/zolotareva_a_count_of_words/src/ops_mpi.cpp
> +  return taskData->outputs_count[0] == 1;
Можешь добавить проверку на пустую строку

2024-11-04 23:04 UTC, KAPUSHA228 commented on tasks/mpi/zolotareva_a_count_of_words/func_tests/main.cpp
> +    taskDataPar->outputs.emplace_back(reinterpret_cast<uint8_t *>(&global_count));
тогда всё ок

2024-11-04 23:11 UTC, KAPUSHA228 approved these changes

2024-11-05 19:25 UTC, andrewmeow commented on tasks/mpi/zolotareva_a_count_of_words/src/ops_mpi.cpp
> +  return taskData->outputs_count[0] == 1;
добавила

2024-11-05 20:12 UTC, DZaytsev4 approved these changes

2024-11-07 15:21 UTC, allnes requested changes

2024-11-07 15:21 UTC, allnes commented on tasks/mpi/zolotareva_a_count_of_words/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
please remove it

2024-11-07 15:21 UTC, allnes commented on tasks/mpi/zolotareva_a_count_of_words/src/ops_mpi.cpp
> +  std::this_thread::sleep_for(20ms);
please remove it

2024-11-07 15:21 UTC, allnes commented on tasks/seq/zolotareva_a_count_of_words/src/ops_seq.cpp
> +  std::this_thread::sleep_for(20ms);
please remove it

2024-11-07 15:21 UTC, allnes commented on tasks/seq/zolotareva_a_count_of_words/src/ops_seq.cpp
> +using namespace std::chrono_literals;
please remove it

2024-11-07 15:21 UTC, allnes commented on tasks/mpi/zolotareva_a_count_of_words/src/ops_mpi.cpp
> +  std::this_thread::sleep_for(20ms);
please remove it

2024-11-07 17:55 UTC, andrewmeow commented on tasks/mpi/zolotareva_a_count_of_words/src/ops_mpi.cpp
> +  std::this_thread::sleep_for(20ms);
ready

2024-11-07 18:09 UTC, allnes approved these changes

2024-11-08 00:25 UTC, aobolensk requested changes

2024-11-08 00:25 UTC, aobolensk commented on tasks/mpi/zolotareva_a_count_of_words/perf_tests/main.cpp
> +TEST(mpi_zolotareva_a_count_of_words_perf_test, test_pipeline_run) {
Please, add some random tests as well

2024-11-08 16:57 UTC, andrewmeow commented on tasks/mpi/zolotareva_a_count_of_words/perf_tests/main.cpp
> +TEST(mpi_zolotareva_a_count_of_words_perf_test, test_pipeline_run) {
ready

2024-11-08 19:28 UTC, aobolensk approved these changes

2024-11-09 03:02 UTC, merged