Зайцев Денис. Задача 1. Вариант 5. Нахождение числа чередований знаков значений соседних элементов вектора
learning-process/ppc-2024-autumn pull request #199
Opened 2024-11-04 19:21 UTC by DZaytsev4

**Последовательное выполнение**
1. Создание вектора
2. Проходим по каждому элементу и сравниваем с предыдущим отличаются ли они знаком, если да, то добавляем к результату 1
3. Вывод результата

**Параллельное выполнение**
1. Создание вектора, и разбиение его на части, если кол-во элементов не делится ровно на кол-во процессов, то остаток элементов идет последнему процессу
2. Каждый процесс последовательно проверяет свой локальный вектор, и границ
3. Суммируются локальные результаты и выводится общий.

2024-11-04 21:56 UTC, andrewmeow requested changes

2024-11-04 21:56 UTC, andrewmeow commented on tasks/mpi/zaytsev_d_num_of_alternations_signs/src/ops_mpi.cpp
> +    auto* tmp_ptr = reinterpret_cast<int*>(taskData->inputs[0]);
you can use std::copy

2024-11-04 22:00 UTC, andrewmeow requested changes

2024-11-04 22:00 UTC, andrewmeow commented on tasks/mpi/zaytsev_d_num_of_alternations_signs/src/ops_mpi.cpp
> +      input_[i] = tmp_ptr[i];
you can use std::copy

2024-11-04 22:35 UTC, DZaytsev4 commented on tasks/mpi/zaytsev_d_num_of_alternations_signs/src/ops_mpi.cpp
> +      input_[i] = tmp_ptr[i];
ready

2024-11-04 22:39 UTC, andrewmeow approved these changes

2024-11-05 18:16 UTC, ArtemPch commented on tasks/mpi/zaytsev_d_num_of_alternations_signs/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
you use this in functional tests, move them there

2024-11-05 18:28 UTC, ArtemPch commented on tasks/mpi/zaytsev_d_num_of_alternations_signs/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
you don't use some include and namespace

2024-11-05 20:16 UTC, DZaytsev4 commented on tasks/mpi/zaytsev_d_num_of_alternations_signs/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
ready

2024-11-05 20:40 UTC, ArtemPch approved these changes

2024-11-07 15:24 UTC, allnes requested changes

2024-11-07 15:24 UTC, allnes commented on tasks/mpi/zaytsev_d_num_of_alternations_signs/src/ops_mpi.cpp
> +bool zaytsev_d_num_of_alternations_signs_mpi::TestMPITaskParallel::pre_processing() {
please move all mpi functions to run()

2024-11-07 16:13 UTC, DZaytsev4 commented on tasks/mpi/zaytsev_d_num_of_alternations_signs/src/ops_mpi.cpp
> +bool zaytsev_d_num_of_alternations_signs_mpi::TestMPITaskParallel::pre_processing() {
ready

2024-11-07 16:16 UTC, allnes approved these changes

2024-11-08 00:31 UTC, aobolensk requested changes

2024-11-08 00:31 UTC, aobolensk commented on tasks/mpi/zaytsev_d_num_of_alternations_signs/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
Please, move test functions to the test module

2024-11-08 02:54 UTC, DZaytsev4 commented on tasks/mpi/zaytsev_d_num_of_alternations_signs/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
ready

2024-11-08 15:12 UTC, aobolensk approved these changes

2024-11-08 15:12 UTC, merged