Кораблев Владлен. Задача 1. Вариант 19.  Интегрирование методом прямоугольников
learning-process/ppc-2024-autumn pull request #20
Opened 2024-10-18 18:46 UTC by korablev-vm

SEQ: 
Реализован метод средних прямоугольников. 
1) Исходный отрезок разбивается на n частей, каждая из которых имеет длину (a-b)/n
2) На каждом отрезке выбирается середина
3) Вычисление функции в выбранной точке (для каждого отрезка), умножение полученного результата на длину отрезка
4) Суммирование полученных значений
Точность алгоритма прямо пропорциональна количеству разбиений (n)

MPI:
1) Распределение данных с помощью broadcast - передача границ интегрирования и количества шагов всем процесса
2) Равномерное распределение интеграла примерно поровну (с учетом не целого деления) между процессами
3) Подсчет локального результата каждым процессом
4) reduce частичных результатов

2024-10-18 19:41 UTC, kmichaelk approved these changes

2024-10-18 19:43 UTC, kmichaelk requested changes

2024-10-18 19:43 UTC, kmichaelk commented on tasks/mpi/korablev_v_rect_int_mpi/include/ops_mpi.hpp
> +  double local_result_{};
Можно перенести внутрь `RectangularIntegrationParallel::run`

2024-10-22 09:06 UTC, hasanyanovk approved these changes
Nice solution to integrete functions

2024-10-22 16:52 UTC, kmichaelk approved these changes

2024-10-24 12:56 UTC, aobolensk approved these changes

2024-10-25 18:23 UTC, merged