Дормидонтов Егор. Задача 1. Вариант 18. Нахождение минимальных значений по столбцам матрицы.
learning-process/ppc-2024-autumn pull request #200
Opened 2024-11-04 19:36 UTC by EgorDormidontov

Описание программы.
Программа вычисляет минимальное значение в каждом столбце матрицы.
1.Seq задача:
Мы проходимся по каждому столбцу и находим минимум, после чего добавляем найденное в вектор результатов.
2.MPI задача:
- матрица разбивается на кол-во процессов
- каждый процесс ищет минимум в каждом столбце своих данных
- результаты процессов отправляются на главный процесс 
- Там они объединяются
- Получаем вектор минимальных значений по каждому столбцу

2024-11-05 11:41 UTC, Konstantin-Grudzin requested changes

2024-11-05 11:41 UTC, Konstantin-Grudzin commented on tasks/mpi/dormidontov_e_min_value_by_columns_mpi/func_tests/main.cpp
> +  boost::mpi::communicator world;
You don't need to declare a communicator in test case

2024-11-05 11:41 UTC, Konstantin-Grudzin commented on tasks/mpi/dormidontov_e_min_value_by_columns_mpi/func_tests/main.cpp
> +  boost::mpi::communicator world;
You don't need to declare a communicator in test case

2024-11-05 11:41 UTC, Konstantin-Grudzin commented on tasks/mpi/dormidontov_e_min_value_by_columns_mpi/perf_tests/main.cpp
> +  boost::mpi::communicator world;
You don't need to declare a communicator in test case

2024-11-05 11:41 UTC, Konstantin-Grudzin commented on tasks/mpi/dormidontov_e_min_value_by_columns_mpi/perf_tests/main.cpp
> +  boost::mpi::communicator world;
You don't need to declare a communicator in test case

2024-11-05 11:41 UTC, Konstantin-Grudzin commented on tasks/mpi/dormidontov_e_min_value_by_columns_mpi/src/ops_mpi.cpp
> +    res_[j] = 10000000;
It's Better to use maximum of data type,instead of current value

2024-11-05 11:41 UTC, Konstantin-Grudzin commented on tasks/mpi/dormidontov_e_min_value_by_columns_mpi/src/ops_mpi.cpp
> +        input_[j + cs * i] = reinterpret_cast<int*>(taskData->inputs[0])[i * (cs) + j];
use std::copy (it's more efficient way)

2024-11-05 11:41 UTC, Konstantin-Grudzin commented on tasks/mpi/dormidontov_e_min_value_by_columns_mpi/src/ops_mpi.cpp
> +  std::vector<int> locmin(cs, 10000);
use maximum of data type

2024-11-05 11:41 UTC, Konstantin-Grudzin commented on tasks/mpi/dormidontov_e_min_value_by_columns_mpi/src/ops_mpi.cpp
> +      prs = rsperpro + (i < unfitrs ? 1 : 0);
it's not very safe to use ternary operator

2024-11-05 11:41 UTC, Konstantin-Grudzin commented on tasks/mpi/dormidontov_e_min_value_by_columns_mpi/src/ops_mpi.cpp
> +      world.send(i, 2, input_.data() + a, prs * cs);
what is this tag used for (it's not an issue,but better to fix it)

2024-11-05 11:41 UTC, Konstantin-Grudzin commented on tasks/mpi/dormidontov_e_min_value_by_columns_mpi/src/ops_mpi.cpp
> +    world.recv(0, 2, minput_.data(), locrs * cs);
what is this tag used for (it's not an issue,but better to fix it)

2024-11-05 11:41 UTC, Konstantin-Grudzin commented on tasks/mpi/dormidontov_e_min_value_by_columns_mpi/perf_tests/main.cpp
> +  }
make a function that generates a random matrx

2024-11-06 07:33 UTC, EgorDormidontov commented on tasks/mpi/dormidontov_e_min_value_by_columns_mpi/src/ops_mpi.cpp
> +      world.send(i, 2, input_.data() + a, prs * cs);
I don`t that an issue, i wrote it to have more clarity.It does not affect the programm

2024-11-06 07:34 UTC, EgorDormidontov commented on tasks/mpi/dormidontov_e_min_value_by_columns_mpi/src/ops_mpi.cpp
> +    world.recv(0, 2, minput_.data(), locrs * cs);
I don`t that an issue, i wrote it to have more clarity.It does not affect the programm

2024-11-06 11:28 UTC, NikitaKoshkin requested changes

2024-11-06 13:03 UTC, NikitaKoshkin approved these changes

2024-11-06 13:38 UTC, Konstantin-Grudzin approved these changes

2024-11-06 16:12 UTC, aobolensk requested changes

2024-11-06 16:12 UTC, aobolensk commented on tasks/mpi/dormidontov_e_min_value_by_columns_mpi/perf_tests/main.cpp
> +  int cs = 777;
Too small size for perf test

2024-11-06 17:27 UTC, EgorDormidontov commented on tasks/mpi/dormidontov_e_min_value_by_columns_mpi/perf_tests/main.cpp
> +  int cs = 777;
Thank you for noticing. Fixed the issue.

2024-11-07 14:01 UTC, aobolensk approved these changes

2024-11-07 15:12 UTC, allnes approved these changes

2024-11-07 15:12 UTC, merged