Малышев Антон. Задача 1. Вариант 11. Сумма значений по строкам матрицы
learning-process/ppc-2024-autumn pull request #201
Opened 2024-11-04 20:34 UTC by lolipolovkovith

Seq: 
1. Данные валидируются (количество строк матрицы должно совпадать с размером выхода)
2. Данные построчно копируются из 'taskData'
3. Строки суммируются с помощью `std::accumulate`
4. Результат копируется в `taskData`

MPI: 
1. Данные нулевого процесса валидируются (количество строк матрицы должно совпадать с размером выхода)
2. Данные нулевого процесса построчно копируются из 'taskData'
3. Вычисляются размеры передаваемых данных процессам. Неделящийся остаток будет отправлен последнему процессу
4. Данные рассылаются с помощью `scatterv`
5. Локальные строки суммируются с помощью `std::accumulate`
6. Локальные результаты собираются с помощью `gatherv` копируется в 'taskData' 
7. Собранные результаты копируются в `taskData`

2024-11-05 04:47 UTC, ermolaevv commented on tasks/mpi/malyshev_a_sum_rows_matrix/src/ops_mpi.cpp
> +  }
It may not be effective to give all the remaining work to the last process. It might be worth considering distributing it among several processes.

2024-11-05 05:17 UTC, lolipolovkovith commented on tasks/mpi/malyshev_a_sum_rows_matrix/src/ops_mpi.cpp
> +  }
edited

2024-11-05 07:19 UTC, ermolaevv approved these changes
Please, update the request description due to the changes

2024-11-05 20:19 UTC, andreychh reviewed
The current function test names (`test_run_1`, `test_run_2`, etc.) are not specific and don't clearly indicate each test's purpose. Please rename them to clarify what each test verifies.

2024-11-06 18:35 UTC, lolipolovkovith commented
> The current function test names (`test_run_1`, `test_run_2`, etc.) are not specific and don't clearly indicate each test's purpose. Please rename them to clarify what each test verifies.

Fixed @andreychh

2024-11-07 15:25 UTC, allnes requested changes

2024-11-07 15:25 UTC, allnes commented on tasks/mpi/malyshev_a_sum_rows_matrix/src/ops_mpi.cpp
> +  uint32_t ext = rows_ % world.size();
please calculate delat and ext once, and then broadcat it instead rows and cols

2024-11-07 17:30 UTC, lolipolovkovith commented on tasks/mpi/malyshev_a_sum_rows_matrix/src/ops_mpi.cpp
> +  uint32_t ext = rows_ % world.size();
fixed

2024-11-07 18:09 UTC, allnes approved these changes

2024-11-08 00:31 UTC, aobolensk approved these changes

2024-11-08 00:31 UTC, merged