Шульпин Илья. Задача 1. Вариант 19. Интегрирование методом Монте-Карло
learning-process/ppc-2024-autumn pull request #202
Opened 2024-11-04 20:57 UTC by NeeMiyuki

2024-11-04 21:04 UTC, NeeMiyuki commented
Accidently got the variant number wrong at commit time

2024-11-06 10:36 UTC, m1likus requested changes

2024-11-06 10:36 UTC, m1likus commented on tasks/mpi/shulpin_monte_carlo_integration/src/monte_carlo_integral.cpp
> +using namespace std::chrono_literals;
As long as you don't use it here, please delete

2024-11-06 10:36 UTC, m1likus commented on tasks/seq/shulpin_monte_carlo_integration/src/monte_carlo_integral.cpp
> +using namespace std::chrono_literals;
Same here

2024-11-06 10:36 UTC, m1likus commented on tasks/mpi/shulpin_monte_carlo_integration/func_tests/main.cpp
> +#include <gtest/gtest.h>
Add test for empty input and check if validation returns false

2024-11-06 13:36 UTC, NeeMiyuki commented on tasks/mpi/shulpin_monte_carlo_integration/src/monte_carlo_integral.cpp
> +using namespace std::chrono_literals;
removed

2024-11-06 13:37 UTC, NeeMiyuki commented on tasks/seq/shulpin_monte_carlo_integration/src/monte_carlo_integral.cpp
> +using namespace std::chrono_literals;
removed

2024-11-06 15:20 UTC, sudo-technoir commented
не тот вариант задачи указан

2024-11-06 16:10 UTC, NeeMiyuki commented
исправлено

2024-11-06 16:11 UTC, sudo-technoir approved these changes

2024-11-06 16:37 UTC, sudo-technoir approved these changes

2024-11-06 19:34 UTC, m1likus approved these changes

2024-11-07 15:28 UTC, allnes requested changes

2024-11-07 15:28 UTC, allnes commented on tasks/mpi/shulpin_monte_carlo_integration/src/monte_carlo_integral.cpp
> +bool shulpin_monte_carlo_integration::TestMPITaskParallel::pre_processing() {
please move all mpi functions to run()

2024-11-09 11:18 UTC, aobolensk requested changes

2024-11-09 11:18 UTC, aobolensk commented on tasks/seq/shulpin_monte_carlo_integration/perf_tests/main.cpp
> +  int N = 10000;
Make more iterations better for perf tests

2024-11-09 15:20 UTC, m1likus commented on tasks/mpi/shulpin_monte_carlo_integration/func_tests/main.cpp
> +#define ESTIMATE 1e-3
I'm just curious - why are constants better than defines here?

2024-11-10 01:00 UTC, allnes approved these changes

2024-11-10 01:03 UTC, aobolensk commented on tasks/mpi/shulpin_monte_carlo_integration/func_tests/main.cpp
> +#define ESTIMATE 1e-3
constexpr values is the C++ way of using constants. defines are more of a C way, because they don't have a concept of constexpr'ness. Macro expansion is better to be used in the places where you need defines' metaprogramming capabilities. We have a built-in language feature for using constants that is more safe (it checks semantics of the variable, it does not perform just pure text replacement and so on)

2024-11-10 01:03 UTC, aobolensk approved these changes

2024-11-10 01:05 UTC, merged