Зайцев Артем. Задача 1. Вариант 4. Минимальный элемент вектора.
learning-process/ppc-2024-autumn pull request #204
Opened 2024-11-05 03:34 UTC by aortemon

### Последовательная реализация
Принять, что первый элемент вектора, если он не нулевой, является текущим минимальным найденным.
Сравнить текущий минимальный элемент с очередным непроверенным элементом вектора, начиная со второго.
При достижении конца вектора текущий минимальный элемент будет минимальным элементом во всем векторе.
### Параллельная реализация
Разбить вектор на подвекторы длины, равной соотношению длины исходного вектора к количеству выделенных потоков.
В каждом потоке запустить последовательную реализацию алгоритма для соответствующего подвектора.
С помощью `boost::mpi::reduce()` найти наименьший элемент среди минимумов, полученных в каждом потоке.

2024-11-05 03:48 UTC, aortemon commented
I've closed my previous PR #189 due to some issues with builds and tests.

@Sean0450 I've added tests for singleton vectors as you requested in #189.

@kmichaelk Thank you for your advice about `std::copy()` given in previous PR. I will use it for upcoming jobs, but not this one, so as not to burden the repo's workers with another commit.

2024-11-05 04:58 UTC, Sean0450 approved these changes

2024-11-05 16:47 UTC, kmichaelk approved these changes

2024-11-07 15:29 UTC, allnes requested changes

2024-11-07 15:29 UTC, allnes commented on tasks/mpi/zaitsev_a_min_of_vector_elements/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
please remove it

2024-11-07 15:29 UTC, allnes commented on tasks/seq/zaitsev_a_min_of_vector_elements/src/ops_seq.cpp
> +using namespace std::chrono_literals;
please remove it

2024-11-07 15:29 UTC, allnes commented on tasks/mpi/zaitsev_a_min_of_vector_elements/src/ops_mpi.cpp
> +std::vector<int> zaitsev_a_min_of_vector_elements_mpi::getRandomVector(int sz, int minRangeValue, int maxRangeValue) {
please move it to tests files

2024-11-07 18:46 UTC, allnes approved these changes

2024-11-08 00:33 UTC, aobolensk requested changes

2024-11-08 00:33 UTC, aobolensk commented on tasks/mpi/zaitsev_a_min_of_vector_elements/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz, int minRangeValue, int maxRangeValue);
Please, move test function to the test module

2024-11-08 00:33 UTC, aobolensk commented on tasks/mpi/zaitsev_a_min_of_vector_elements/perf_tests/main.cpp
> +  std::vector<int32_t> global_min(1, maxRangeValue + 1);
Please, add test for negative values as well

2024-11-08 01:01 UTC, aortemon commented on tasks/mpi/zaitsev_a_min_of_vector_elements/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz, int minRangeValue, int maxRangeValue);
Moved

2024-11-08 01:03 UTC, aortemon commented on tasks/mpi/zaitsev_a_min_of_vector_elements/perf_tests/main.cpp
> +  std::vector<int32_t> global_min(1, maxRangeValue + 1);
Tests have been added, already existed ones have been corrected for the case you specified

2024-11-09 03:03 UTC, aobolensk approved these changes

2024-11-09 03:03 UTC, merged