Сорокин Андрей. Задача 1. Вариант 26. Проверка лексикографической упорядоченности двух строк.
learning-process/ppc-2024-autumn pull request #21
Opened 2024-10-19 09:04 UTC by AndreySorokin7

Описание последовательной задачи:
Последовательный одновременный поэлементный проход по двум строкам с поиском первых двух различных символов с последующим определением большего из них. Отсюда выявлением большей строки с выводом 0 или 1.
0 - str1<str2
1 - str1>str2

Описание MPI задачи:
Массив строк (std::vector<std::vector<char>>) разделяется на две отдельные строки. Каждая строка делится на равновеликие сегменты по числу процессов и каждый из полученных сегментов отправляется в свой процесс. В каждом процессе происходит сравнение элементов, как это описано в последовательной задаче и на выходе выдают одно из трёх значений. 0 и 1 несут ту же суть, что и раньше, а значение 2 означает идентичность строк, работа с которыми осуществлялась внутри процессов. После завершения всех процессов происходит последовательный поиск по процессам.
Значение первого процесса, значение которого не равно 2, записывается как результат и проход останавливается. Это необходимо, так нужно зафиксировать самое первое отличие глобальных строк.

2024-10-19 11:12 UTC, ermolaevv commented on tasks/mpi/sorokin_a_check_lexicographic_order_of_strings/src/ops_mpi.cpp
> +  std::this_thread::sleep_for(20ms);
На парах говорилось, что не следует приостанавливать выполнение потока
```suggestion
```

2024-10-19 11:12 UTC, ermolaevv commented on tasks/mpi/sorokin_a_check_lexicographic_order_of_strings/src/ops_mpi.cpp
> +  std::this_thread::sleep_for(20ms);
```suggestion
```

2024-10-19 11:12 UTC, ermolaevv commented on tasks/seq/sorokin_a_check_lexicographic_order_of_strings/src/ops_seq.cpp
> +  std::this_thread::sleep_for(20ms);
```suggestion
```

2024-10-19 11:12 UTC, ermolaevv commented on tasks/mpi/sorokin_a_check_lexicographic_order_of_strings/include/ops_mpi.hpp
> +  int res{};
Имена приватных полей класса должны оканчиваться нижним подчёркиванием ( _ ). В других классах также есть подобная  ошибка именования.

2024-10-19 11:26 UTC, Semyon1104 commented on tasks/mpi/sorokin_a_check_lexicographic_order_of_strings/func_tests/main.cpp
> +TEST(sorokin_a_check_lexicographic_order_of_strings_mpi, Test_Basic2) {
please change the names of the tests

2024-10-19 12:17 UTC, AndreySorokin7 commented on tasks/mpi/sorokin_a_check_lexicographic_order_of_strings/func_tests/main.cpp
> +TEST(sorokin_a_check_lexicographic_order_of_strings_mpi, Test_Basic2) {
fixed

2024-10-19 12:17 UTC, AndreySorokin7 commented on tasks/mpi/sorokin_a_check_lexicographic_order_of_strings/include/ops_mpi.hpp
> +  int res{};
fixed

2024-10-19 12:17 UTC, AndreySorokin7 commented on tasks/seq/sorokin_a_check_lexicographic_order_of_strings/src/ops_seq.cpp
> +  std::this_thread::sleep_for(20ms);
fixed

2024-10-19 12:17 UTC, AndreySorokin7 commented on tasks/mpi/sorokin_a_check_lexicographic_order_of_strings/src/ops_mpi.cpp
> +  std::this_thread::sleep_for(20ms);
fixed

2024-10-19 12:17 UTC, AndreySorokin7 commented on tasks/mpi/sorokin_a_check_lexicographic_order_of_strings/src/ops_mpi.cpp
> +  std::this_thread::sleep_for(20ms);
fixed

2024-10-19 12:44 UTC, ermolaevv approved these changes

2024-10-20 15:57 UTC, Semyon1104 approved these changes

2024-10-23 18:17 UTC, aobolensk requested changes

2024-10-23 18:17 UTC, aobolensk commented on tasks/mpi/sorokin_a_check_lexicographic_order_of_strings/func_tests/main.cpp
> +}
Please add the test with equal strings

2024-10-23 18:39 UTC, AndreySorokin7 commented on tasks/mpi/sorokin_a_check_lexicographic_order_of_strings/func_tests/main.cpp
> +}
added

2024-10-24 12:17 UTC, aobolensk approved these changes

2024-10-25 18:16 UTC, allnes approved these changes

2024-10-25 18:16 UTC, merged

2024-10-29 16:15 UTC, hasanyanovk commented
You have the same problem as @Alexey2013, check  tests with number of processes: 3, 5, 7, 8