lavrentyev_mpi_new
learning-process/ppc-2024-autumn pull request #212
Opened 2024-11-05 09:05 UTC by mahor13

2024-11-05 17:44 UTC, KolodkinGrigorii approved these changes

2024-11-05 19:17 UTC, MishaRysev approved these changes

2024-11-07 16:09 UTC, allnes commented
@KolodkinGrigorii @MishaRysev yours review is not accepted

2024-11-07 16:10 UTC, allnes requested changes

2024-11-07 16:10 UTC, allnes commented on tasks/mpi/lavrentyev_a_alternation_count/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
please remove it

2024-11-07 16:10 UTC, allnes commented on tasks/seq/lavrentyev_a_alternation_count/src/ops_seq.cpp
> +using namespace std::chrono_literals;
please remove it

2024-11-07 17:29 UTC, mahor13 commented on tasks/seq/lavrentyev_a_alternation_count/src/ops_seq.cpp
> +using namespace std::chrono_literals;
fixed

2024-11-07 17:29 UTC, mahor13 commented on tasks/mpi/lavrentyev_a_alternation_count/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
fixed

2024-11-07 18:47 UTC, allnes approved these changes

2024-11-07 19:03 UTC, nCUXe commented on tasks/mpi/lavrentyev_a_alternation_count/func_tests/main.cpp
> +      global_vec.push_back(number);
fix this part of the code, only negative numbers are generated here

2024-11-07 19:40 UTC, VladimirSdobnov reviewed
All the comments presented are relevant not only for a parallel solution, but also for a sequential one. Changes need to be made to both solutions

2024-11-07 19:40 UTC, VladimirSdobnov commented on tasks/mpi/lavrentyev_a_alternation_count/func_tests/main.cpp
> +TEST(Parallel_Operations_MPI, Test_vector_with_one_elem) {
I think the meaning of this test contradicts the description of the input data of the task

2024-11-07 19:40 UTC, VladimirSdobnov commented on tasks/mpi/lavrentyev_a_alternation_count/func_tests/main.cpp
> +TEST(Parallel_Operations_MPI, Test_vector_with_zero) {
The name of the test does not reflect its meaning

2024-11-07 19:40 UTC, VladimirSdobnov commented on tasks/mpi/lavrentyev_a_alternation_count/func_tests/main.cpp
> +TEST(Parallel_Operations_MPI, Test_big_vector_with_zero) {
In the test for a vector with zeros, there are no zeros in the input vector)

2024-11-07 19:40 UTC, VladimirSdobnov commented on tasks/mpi/lavrentyev_a_alternation_count/func_tests/main.cpp
> +TEST(Parallel_Operations_MPI, Big_vec_with_zero) {
You should also come up with another name for this test

2024-11-07 19:40 UTC, VladimirSdobnov commented on tasks/mpi/lavrentyev_a_alternation_count/src/ops_mpi.cpp
> +}
It is necessary to extend the validity check also to the input data and add tests for empty and incorrect input data

2024-11-08 00:33 UTC, aobolensk approved these changes

2024-11-15 17:57 UTC, venn2713 commented on tasks/mpi/lavrentyev_a_alternation_count/src/ops_mpi.cpp
> +  return taskData->outputs_count[0] == 1;
It seems like your validation doesn't cover enough edge cases.

2024-11-15 17:57 UTC, venn2713 commented on tasks/seq/lavrentyev_a_alternation_count/src/ops_seq.cpp
> +  return taskData->outputs_count[0] == 1;
Similarly, it is not enough

2024-11-15 17:57 UTC, venn2713 commented on tasks/seq/lavrentyev_a_alternation_count/func_tests/main.cpp
> +  ASSERT_EQ(testTaskSequential.validation(), true);
You can use ASSERT_TRUE in such situations

2024-12-17 17:39 UTC, venn2713 approved these changes

2024-12-19 10:46 UTC, VladimirSdobnov approved these changes

2024-12-19 12:31 UTC, nCUXe approved these changes

2024-12-20 16:31 UTC, merged