Черных Андрей. Задача 1. Вариант 5. Нахождение числа чередований знаков значений соседних элементов вектора.
learning-process/ppc-2024-autumn pull request #22
Opened 2024-10-19 10:20 UTC by andreychh

**Задача нахождения числа чередований знаков значений соседних элементов вектора** заключается в том, чтобы подсчитать количество переходов между положительными и отрицательными числами в одномерном векторе целых чисел. Для корректного выполнения алгоритма входные данные должны содержать как минимум два элемента, а результат должен быть представлен единственным числом.

Параллельная версия алгоритма использует библиотеку MPI для распределения вычислений между несколькими процессами.

### Описание последовательной задачи:

1. Выполняется проход по вектору от начала до предпоследнего элемента.
2. Для каждой пары соседних элементов проверяется, произошла ли смена знака. Это делается с помощью операции XOR (если результат меньше нуля, значит знаки разные).
3. Каждый раз, когда смена знака обнаружена, счетчик увеличивается на единицу.
4. По завершении прохода по вектору значение счетчика становится результатом выполнения задачи — общим количеством чередований знаков.

### Описание MPI задачи:

1. **Разделение данных:**
    - Процесс с рангом 0 делит входной вектор на блоки. Все блоки, кроме последнего, включают первый элемент следующего блока, чтобы сохранить информацию о возможном чередовании знаков на границе блоков.
    - Каждый блок отправляется соответствующему процессу.
2. **Вычисления:**
    - Каждый процесс обрабатывает свой блок данных, подсчитывая количество чередований знаков внутри него.
3. **Сбор результатов:**
    - Каждый процесс возвращает частичный результат (количество чередований знаков в его блоке) процессу 0 с помощью операции `reduce`, которая суммирует все частичные результаты.
4. **Обработка результата:**
    - Процесс с рангом 0 собирает и возвращает итоговое количество чередований как результат выполнения задачи.

2024-10-27 09:14 UTC, allnes approved these changes

2024-10-27 14:40 UTC, aobolensk requested changes

2024-10-27 14:40 UTC, aobolensk commented on tasks/mpi/chernykh_a_num_of_alternations_signs/perf_tests/main.cpp
> +    input = std::vector<int>(30'000'000, 0);
Use different sizes for your tests

2024-10-27 14:40 UTC, aobolensk commented on tasks/mpi/chernykh_a_num_of_alternations_signs/src/ops_mpi.cpp
> +}
Move test function to test file

2024-10-28 21:12 UTC, andreychh commented on tasks/mpi/chernykh_a_num_of_alternations_signs/perf_tests/main.cpp
> +    input = std::vector<int>(30'000'000, 0);
Fixed in commit 5322001. Thanks

2024-10-29 00:02 UTC, aobolensk approved these changes

2024-10-29 06:11 UTC, korablev-vm approved these changes

2024-10-30 14:23 UTC, sergkon314 approved these changes

2024-10-30 16:33 UTC, merged