Наумов Богдан Задача 1 вариант 18 Нахождение минимальных значений по столбцам матрицы
learning-process/ppc-2024-autumn pull request #221
Opened 2024-11-05 17:18 UTC by BogdanNaumov

Задача заключается в нахождении минимальных значений в каждом столбце матрицы целых чисел. Входные данные представляют собой двумерный массив чисел, и результатом работы программы должен быть одномерный массив, содержащий минимальные элементы по каждому столбцу.

Последовательная версия алгоритма:

На этапе предобработки входные данные преобразуются в двумерный массив, где строки и столбцы задаются исходными размерами. Массив результата инициализируется минимальными значениями для каждого столбца.
Алгоритм проходит по каждому столбцу и находит минимальный элемент, сравнивая значения элементов столбца.
После выполнения алгоритма результат сохраняется в выходном массиве.

Версия алгоритма с использованием MPI:

Разделение данных: Процесс с рангом 0 получает исходную матрицу и делит ее на части по столбцам между всеми процессами. Каждый процесс получает свою часть столбцов, а процесс с рангом 0 также получает дополнительную часть, если количество столбцов не делится нацело на количество процессов.

Вычисления: Каждый процесс ищет минимальные значения в своей части столбцов. Алгоритм сравнивает элементы столбцов и сохраняет минимальные значения для каждого столбца.

Сбор результатов: Процесс с рангом 0 собирает частичные результаты от всех процессов и объединяет их в итоговый массив.

Обработка результата: После сбора всех результатов, минимальные значения по каждому столбцу сохраняются в выходном массиве.

2024-11-07 13:47 UTC, WladislawFilatew commented on tasks/mpi/naumov_b_min_colum_matrix/src/ops_mpi.cpp
> +}
Transfer these functions to tests

2024-11-07 14:53 UTC, BogdanNaumov commented on tasks/mpi/naumov_b_min_colum_matrix/src/ops_mpi.cpp
> +}
fixed

2024-11-07 16:13 UTC, allnes requested changes

2024-11-07 16:13 UTC, allnes commented on tasks/mpi/naumov_b_min_colum_matrix/src/ops_mpi.cpp
> +  int extra = cols % world.size();
please calculate delta and extra once and then broadcast it insted rows and cols

2024-11-07 16:13 UTC, allnes commented on tasks/seq/naumov_b_min_colum_matrix/src/ops_seq.cpp
> +using namespace std::chrono_literals;
please remove it

2024-11-07 16:59 UTC, BogdanNaumov commented on tasks/mpi/naumov_b_min_colum_matrix/src/ops_mpi.cpp
> +  int extra = cols % world.size();
fixed

2024-11-07 16:59 UTC, BogdanNaumov commented on tasks/seq/naumov_b_min_colum_matrix/src/ops_seq.cpp
> +using namespace std::chrono_literals;
fixed

2024-11-07 17:00 UTC, allnes approved these changes

2024-11-07 17:05 UTC, WladislawFilatew approved these changes

2024-11-08 12:47 UTC, BogdanNaumov commented on tasks/mpi/naumov_b_min_colum_matrix/include/ops_mpi.hpp
> +std::vector<std::vector<int>> getRandomMatrix(int rows, int columns);
fixed

2024-11-08 17:24 UTC, ArtemPch commented on tasks/mpi/naumov_b_min_colum_matrix/perf_tests/main.cpp
> +}
since you use the upper function only in the lower one, combine them

2024-11-08 17:49 UTC, BogdanNaumov commented on tasks/mpi/naumov_b_min_colum_matrix/perf_tests/main.cpp
> +}
fixed

2024-11-08 18:35 UTC, ArtemPch approved these changes

2024-11-08 19:05 UTC, BogdanNaumov commented on tasks/mpi/naumov_b_min_colum_matrix/include/ops_mpi.hpp
> +std::vector<std::vector<int>> getRandomMatrix(int rows, int columns);
Check, please

2024-11-09 03:04 UTC, aobolensk approved these changes

2024-11-09 03:04 UTC, merged