Капустин Иван. Задача 1. Вариант 16. Нахождение максимальных элементов по столбцам матрицы.
learning-process/ppc-2024-autumn pull request #222
Opened 2024-11-05 19:26 UTC by kapustinI

Задача заключается в нахождении максимальных значений в каждом столбце матрицы. Входные данные представлены в виде двумерного массива, а результатом работы программы должен быть одномерный массив, содержащий максимальные элементы по каждому столбцу.

В последовательной версии алгоритма входная матрица преобразуется в двумерный массив, массив результата инициализируется минимальными значениями для корректного поиска максимума. Алгоритм проходит по каждому столбцу, сравнивая значения элементов для нахождения максимального, после чего сохраняет результаты в выходном массиве.

В версии алгоритма с использованием MPI процесс с рангом 0 получает исходную матрицу и разделяет её на части по столбцам для распределения между процессами. Каждый процесс вычисляет максимальные значения в своей части, после чего результаты собираются процессом с рангом 0 и объединяются в итоговый массив максимальных значений.

2024-11-07 06:55 UTC, hasanyanovk commented on tasks/mpi/kapustin_i_max_cols/src/avg_mpi.cpp
> +  }
You might use std::copy or .assign

2024-11-07 06:57 UTC, hasanyanovk commented on tasks/seq/kapustin_i_max_cols/src/avg_seq.cpp
> +// return true;
Remove commented code

2024-11-07 08:30 UTC, kapustinI commented on tasks/mpi/kapustin_i_max_cols/src/avg_mpi.cpp
> +  }
fixed

2024-11-07 08:31 UTC, hasanyanovk approved these changes

2024-11-07 16:15 UTC, allnes requested changes

2024-11-07 16:15 UTC, allnes commented on tasks/mpi/kapustin_i_max_cols/src/avg_mpi.cpp
> +  broadcast(world, input_.data(), column_count * row_count, 0);
please don't send whole input data every process

2024-11-09 11:21 UTC, aobolensk requested changes

2024-11-10 21:31 UTC, kapustinI commented on tasks/mpi/kapustin_i_max_cols/func_tests/main.cpp
> +    int val = gen() % 100000;
fixed

2024-11-10 21:31 UTC, kapustinI commented on tasks/seq/kapustin_i_max_cols/src/avg_seq.cpp
> +    input_[i] = matrix_data[i];
fixed

2024-11-10 21:31 UTC, kapustinI commented on tasks/seq/kapustin_i_max_cols/func_tests/main.cpp
> +TEST(kapustin_i_max_column_task_seq, test_square_M_3_3) {
fixed

2024-11-10 21:31 UTC, kapustinI commented on tasks/mpi/kapustin_i_max_cols/src/avg_mpi.cpp
> +  broadcast(world, input_.data(), column_count * row_count, 0);
fixed

2024-11-10 21:33 UTC, kapustinI commented on tasks/seq/kapustin_i_max_cols/func_tests/main.cpp
> +TEST(kapustin_i_max_column_task_seq, test_square_M_3_3) {
@aobolensk ready

2024-11-10 21:33 UTC, kapustinI commented on tasks/mpi/kapustin_i_max_cols/src/avg_mpi.cpp
> +  broadcast(world, input_.data(), column_count * row_count, 0);
@allnes ready

2024-11-11 11:39 UTC, allnes approved these changes

2024-11-11 14:14 UTC, aobolensk approved these changes

2024-11-11 14:14 UTC, merged