Чернова Наталья. Задача 1. Вариант 24. Подсчет числа слов в строке
learning-process/ppc-2024-autumn pull request #230
Opened 2024-11-06 11:37 UTC by ChernovaNatalya

**Описание последовательной задачи.**
Входные данные - строка, в которой нужно найти количество входящих слов.
Выходные данные - целочисленное значение - количество слов в строке.

**Описание параллельной задачи.**
Разделяем строку на несколько подстрок и поручаем эту задачу нескольким потокам. Разделение происходит равномерно. Затем каждый поток считает число слов в своей части строки. В итоге всё суммируется с помощью reduce.

2024-11-06 11:52 UTC, VasenkovAA approved these changes

2024-11-06 11:52 UTC, VasenkovAA commented on tasks/mpi/chernova_n_word_count/src/ops_mpi.cpp
> +  std::cout << world.size() << std::endl;
and you're sure these are the ones you want in the final version?

2024-11-06 19:44 UTC, VlJulia requested changes

2024-11-06 19:44 UTC, VlJulia commented on tasks/mpi/chernova_n_word_count/src/ops_mpi.cpp
> +}
Why ">=0"? Also what if the string is empty?

2024-11-06 21:46 UTC, VlJulia approved these changes

2024-11-06 22:10 UTC, ChernovaNatalya commented on tasks/mpi/chernova_n_word_count/src/ops_mpi.cpp
> +  std::cout << world.size() << std::endl;
fixed it

2024-11-06 22:12 UTC, ChernovaNatalya commented on tasks/mpi/chernova_n_word_count/src/ops_mpi.cpp
> +}
You're right. I fixed it and also added a test to check for empty strings.

2024-11-07 16:18 UTC, allnes approved these changes

2024-11-07 16:20 UTC, allnes requested changes

2024-11-07 16:20 UTC, allnes commented on tasks/mpi/chernova_n_word_count/func_tests/main.cpp
> +    ASSERT_FALSE(testTaskParallel.validation());
I think empty string has 0 words

2024-11-07 21:02 UTC, ChernovaNatalya commented on tasks/mpi/chernova_n_word_count/func_tests/main.cpp
> +    ASSERT_FALSE(testTaskParallel.validation());
fixed it

2024-11-09 11:26 UTC, aobolensk requested changes

2024-11-09 11:26 UTC, aobolensk commented on tasks/mpi/chernova_n_word_count/include/ops_mpi.hpp
> +
Please move test functions to the tests module

2024-11-09 11:26 UTC, aobolensk commented on tasks/seq/chernova_n_word_count/func_tests/main.cpp
> +  std::string testString = "This is a test phrase           ";
Please, add random tests

2024-11-09 11:26 UTC, aobolensk commented on tasks/mpi/chernova_n_word_count/func_tests/main.cpp
> +    in.push_back(testString[j]);
You can use std::copy or analogs here

2024-11-09 12:40 UTC, ChernovaNatalya commented on tasks/mpi/chernova_n_word_count/include/ops_mpi.hpp
> +
Sorry, but I can't move this function to the test module. I use this function to process the string in the algorithm itself. I have test functions that I use only in test module, but they are declared only there (function generateWords in perf_tests).

2024-11-09 15:31 UTC, ChernovaNatalya commented on tasks/seq/chernova_n_word_count/func_tests/main.cpp
> +  std::string testString = "This is a test phrase           ";
Fixed it

2024-11-09 23:45 UTC, kmichaelk requested changes

2024-11-09 23:45 UTC, kmichaelk commented on tasks/mpi/chernova_n_word_count/src/ops_mpi.cpp
> +  input_ = clean_string(input_);
Do you process the whole string by single worker before actual task run? This time is comparable to the time it takes to count the number of words in a line in a single process, and taking into account the `erase` calls and reallocation overhead, it even exceeds it in the worst case - it defeats the purpose of parallelizing the task.

2024-11-10 01:03 UTC, allnes approved these changes

2024-11-10 01:09 UTC, aobolensk commented on tasks/mpi/chernova_n_word_count/include/ops_mpi.hpp
> +
Are you sure that this is correct?

2024-11-11 14:17 UTC, aobolensk approved these changes

2024-11-11 14:18 UTC, merged