Варфоломеев Григорий. Задача 1. Вариант 15. Нахождение максимальных значений по строкам матрицы.
learning-process/ppc-2024-autumn pull request #231
Opened 2024-11-06 12:44 UTC by petr1core

### Описание
#### Sequential
Последовательная реализация алгоритма нахождения максимальных значений в каждой строке матрицы выполняется линейно. Она проходит по каждой строке матрицы, используя функцию `std::max_element` для поиска максимального значения в строке, и сохраняет результат в вектор `res_vec`. Этот подход прост и эффективен для небольших матриц, но может быть медленным для больших матриц.
***
#### Parallel
Параллельная реализация алгоритма нахождения максимальных значений в каждой строке матрицы с использованием `MPI` и `Boost `для распределения работы между несколькими процессами. Главный процесс отправляет строки матрицы другим процессам, которые вычисляют максимальные значения и возвращают результаты обратно. Главный процесс собирает результаты и сохраняет их в результирующий вектор.

2024-11-06 16:32 UTC, andrewmeow requested changes
Следует убрать лишние комментарии и повысить покрытие кода (добавь тестов по MPI)

2024-11-06 16:34 UTC, andrewmeow requested changes
Следует убрать лишние комментарии и повысить покрытие кода (добавь тестов по MPI)

2024-11-06 19:35 UTC, andrewmeow approved these changes

2024-11-07 05:37 UTC, KAPUSHA228 approved these changes

2024-11-07 16:21 UTC, allnes commented on tasks/mpi/varfolomeev_g_matrix_max_rows_vals/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
please remove it

2024-11-07 16:21 UTC, allnes commented on tasks/seq/varfolomeev_g_matrix_max_rows_vals/src/ops_seq.cpp
> +using namespace std::chrono_literals;
please remove it

2024-11-07 19:48 UTC, petr1core commented on tasks/mpi/varfolomeev_g_matrix_max_rows_vals/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
Removed

2024-11-07 19:49 UTC, petr1core commented on tasks/seq/varfolomeev_g_matrix_max_rows_vals/src/ops_seq.cpp
> +using namespace std::chrono_literals;
Also removed

2024-11-09 11:31 UTC, aobolensk requested changes

2024-11-09 11:31 UTC, aobolensk commented on tasks/mpi/varfolomeev_g_matrix_max_rows_vals/include/ops_mpi.hpp
> +
Please, remove this from the code not related to tests

2024-11-09 11:31 UTC, aobolensk commented on tasks/mpi/varfolomeev_g_matrix_max_rows_vals/perf_tests/main.cpp
> +  int size_n = 1000;
Please, increase it for perf tests

2024-11-09 11:31 UTC, aobolensk commented on tasks/seq/varfolomeev_g_matrix_max_rows_vals/func_tests/main.cpp
> +TEST(varfolomeev_g_matrix_max_rows_vals_seq, Test_in_empty) {
Please, add more tests for seq implementation

2024-11-09 19:12 UTC, petr1core commented on tasks/seq/varfolomeev_g_matrix_max_rows_vals/func_tests/main.cpp
> +TEST(varfolomeev_g_matrix_max_rows_vals_seq, Test_in_empty) {
Changes are now implemented as suggested

2024-11-10 01:03 UTC, allnes approved these changes

2024-11-10 01:10 UTC, aobolensk approved these changes

2024-11-10 01:10 UTC, merged