Федоров Матвей. Задача1. Вариант 6. Нахождение числа нарушений упорядоченности соседних элементов вектора
learning-process/ppc-2024-autumn pull request #234
Opened 2024-11-06 13:55 UTC by Matthewsoul124

### Последовательная задача

**Входные данные:** Вектор целых чисел.

**Выходные данные:** Целочисленное значение - количество нарушений упорядоченности соседних элементов вектора.

**Описание:**

1. Инициализируем счетчик нарушений нулем.
2. Проходим по всем соседним парам элементов вектора.
3. Если текущий элемент больше следующего, увеличиваем счетчик на единицу.
4. Возвращаем значение счетчика.

### Параллельная задача

**Входные данные:** Вектор целых чисел.

**Выходные данные:** Целочисленное значение - количество нарушений упорядоченности соседних элементов вектора.

**Описание:**

1. Разделяем вектор на несколько подвекторов равномерно.
2. Создаем несколько потоков, каждый из которых обрабатывает свой подвектор.
3. Каждый поток считает количество нарушений упорядоченности в своем подвекторе.
4. Используем операцию reduce для суммирования результатов всех потоков.
5. Возвращаем итоговое значение.

2024-11-06 18:41 UTC, petr1core requested changes
fix excess in example, minor formatting (commented code)

2024-11-06 18:41 UTC, petr1core commented on tasks/seq/fyodorov_m_num_of_orderly_violations/perf_tests/main.cpp
> +// }
Again, no need for this comment

2024-11-06 18:41 UTC, petr1core commented on tasks/seq/fyodorov_m_num_of_orderly_violations/src/ops_seq.cpp
> +*/
Clean-up

2024-11-06 20:53 UTC, petr1core approved these changes
✔ GJ! 👌

2024-11-06 21:17 UTC, KAPUSHA228 requested changes

2024-11-06 21:17 UTC, KAPUSHA228 commented on tasks/mpi/fyodorov_m_num_of_orderly_violations/func_tests/main.cpp
> +
добавь больше тестов для покрытия

2024-11-06 23:06 UTC, KAPUSHA228 approved these changes

2024-11-07 16:26 UTC, allnes commented on tasks/mpi/example/perf_tests/main.cpp
> +    count_size_vector = 12;
please don't change not own files

2024-11-07 16:26 UTC, allnes commented on tasks/mpi/fyodorov_m_num_of_orderly_violations/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
please remove it

2024-11-07 16:26 UTC, allnes commented on tasks/mpi/fyodorov_m_num_of_orderly_violations/src/ops_mpi.cpp
> +    vec[i] = gen() % 100;
please use negative values

2024-11-07 16:26 UTC, allnes commented on tasks/mpi/fyodorov_m_num_of_orderly_violations/src/ops_mpi.cpp
> +std::vector<int> fyodorov_m_num_of_orderly_violations_mpi::getRandomVector(int sz) {
please move random generator to tests files

2024-11-08 11:24 UTC, Matthewsoul124 commented on tasks/mpi/example/perf_tests/main.cpp
> +    count_size_vector = 12;
I got it done. All changes have been made.

2024-11-09 11:34 UTC, aobolensk requested changes

2024-11-09 11:34 UTC, aobolensk commented on tasks/mpi/example/perf_tests/main.cpp
> +    count_size_vector = 12;
Please, do not modify the common code

2024-11-09 11:34 UTC, aobolensk commented on tasks/mpi/fyodorov_m_num_of_orderly_violations/perf_tests/main.cpp
> +      global_vec[i] = i;
use random data for perf test

2024-11-09 11:34 UTC, aobolensk commented on tasks/mpi/fyodorov_m_num_of_orderly_violations/func_tests/main.cpp
> +std::vector<int> RandomVector(int sz) {
Still to few tests, consider adding more tests (including non-random tests)

2024-11-10 01:06 UTC, allnes approved these changes

2024-11-10 18:02 UTC, Matthewsoul124 commented on tasks/mpi/fyodorov_m_num_of_orderly_violations/func_tests/main.cpp
> +std::vector<int> RandomVector(int sz) {
I got it done. All changes have been made.

2024-11-11 14:20 UTC, aobolensk approved these changes

2024-11-11 14:20 UTC, merged