fix Revert "Коровин Никита. Задача 1. Вариант 17. Нахождение минимальных значений по строкам матрицы."
learning-process/ppc-2024-autumn pull request #236
Opened 2024-11-06 17:55 UTC by Kitos87

#159 

fix revert: исправил размер входных данных для матрицы в тестах (ошибка была связана со временем)

**Описание последовательной задачи:**

Схема нахождения минимальных значений по строкам матрицы включает следующие шаги:

- подготовка структуры для матрицы и результата.
- загрузка данных.
- поиск минимумов в каждой строке с обновлением минимального значения.
- сохранение найденных значений в выходной массив.

**Описание MPI задачи:**

Общая схема включает следующие шаги:

- Главный процесс загружает матрицу и распределяет строки между всеми процессами.
- Каждый процесс выполняет локальный поиск минимальных значений в своём наборе строк.
- Все процессы отправляют свои результаты главному процессу.
- Главный процесс собирает результаты и сохраняет их в итоговый массив.

2024-11-06 18:27 UTC, ermolaevv commented on tasks/mpi/korovin_n_min_val_row_matrix/perf_tests/main.cpp
> +
It looks like you accidentally deleted the timer in the performance tests

2024-11-06 18:27 UTC, ermolaevv commented on tasks/mpi/korovin_n_min_val_row_matrix/perf_tests/main.cpp
> +
Same

2024-11-06 18:36 UTC, SergeyBoRss commented on tasks/mpi/korovin_n_min_val_row_matrix/src/ops_mpi.cpp
> +  broadcast(world, cols, 0);
remove from pre-processing

2024-11-06 18:36 UTC, SergeyBoRss commented on tasks/mpi/korovin_n_min_val_row_matrix/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
not used in this file

2024-11-06 19:33 UTC, Kitos87 commented on tasks/mpi/korovin_n_min_val_row_matrix/perf_tests/main.cpp
> +
fixed

2024-11-06 19:33 UTC, Kitos87 commented on tasks/mpi/korovin_n_min_val_row_matrix/perf_tests/main.cpp
> +
fixed

2024-11-06 19:33 UTC, Kitos87 commented on tasks/mpi/korovin_n_min_val_row_matrix/src/ops_mpi.cpp
> +  broadcast(world, cols, 0);
fixed

2024-11-06 19:33 UTC, Kitos87 commented on tasks/mpi/korovin_n_min_val_row_matrix/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
fixed

2024-11-06 19:36 UTC, ermolaevv approved these changes

2024-11-07 16:28 UTC, allnes requested changes

2024-11-07 16:28 UTC, allnes commented on tasks/mpi/korovin_n_min_val_row_matrix/src/ops_mpi.cpp
> +  int extra = rows % world.size();
please calculate delta and extra once and broadcast it only instead rows and cols

2024-11-07 16:28 UTC, allnes commented on tasks/seq/korovin_n_min_val_row_matrix/src/ops_seq.cpp
> +using namespace std::chrono_literals;
please remove it

2024-11-07 21:42 UTC, Kitos87 commented on tasks/mpi/korovin_n_min_val_row_matrix/src/ops_mpi.cpp
> +  int extra = rows % world.size();
Fixed

2024-11-07 21:42 UTC, Kitos87 commented on tasks/seq/korovin_n_min_val_row_matrix/src/ops_seq.cpp
> +using namespace std::chrono_literals;
Fixed

2024-11-09 11:34 UTC, aobolensk approved these changes

2024-11-10 01:04 UTC, allnes approved these changes

2024-11-10 01:04 UTC, merged