<commit>
learning-process/ppc-2024-autumn pull request #237
Opened 2024-11-06 18:38 UTC by isharamygina

2024-11-08 13:23 UTC, VladislavPoroshin commented on tasks/mpi/sharamygina_i_most_different_neighbor_elements/include/ops_mpi.hpp
> +#include <numeric>
extra includes

2024-11-08 13:23 UTC, VladislavPoroshin commented on tasks/mpi/sharamygina_i_most_different_neighbor_elements/src/ops_mpi.cpp
> +#include <random>
extra includes

2024-11-08 14:52 UTC, KorotinEgor approved these changes

2024-11-08 14:53 UTC, VladislavPoroshin approved these changes

2024-11-09 11:40 UTC, aobolensk requested changes

2024-11-09 11:40 UTC, aobolensk commented on tasks/mpi/sharamygina_i_most_different_neighbor_elements/func_tests/main.cpp
> +TEST(sharamygina_i_most_different_neighbor_elements_mpi, wrong_test) {
Please, add tests with non-random inputs as well

2024-11-09 11:40 UTC, aobolensk commented on tasks/seq/sharamygina_i_most_different_neighbor_elements/func_tests/main.cpp
> +TEST(sharamygina_i_most_different_neighbor_elements_seq, random_test) {
Please, add more tests for seq

2024-11-09 13:53 UTC, isharamygina commented on tasks/mpi/sharamygina_i_most_different_neighbor_elements/func_tests/main.cpp
> +TEST(sharamygina_i_most_different_neighbor_elements_mpi, wrong_test) {
fixed

2024-11-09 13:54 UTC, isharamygina commented on tasks/seq/sharamygina_i_most_different_neighbor_elements/func_tests/main.cpp
> +TEST(sharamygina_i_most_different_neighbor_elements_seq, random_test) {
fixed

2024-11-10 01:10 UTC, allnes requested changes

2024-11-10 01:10 UTC, allnes commented on tasks/seq/sharamygina_i_most_different_neighbor_elements/src/ops_seq.cpp
> +using namespace std::chrono_literals;
please remove it

2024-11-10 01:10 UTC, allnes commented on tasks/mpi/sharamygina_i_most_different_neighbor_elements/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
please remove it

2024-11-10 01:11 UTC, aobolensk approved these changes

2024-11-11 11:39 UTC, allnes approved these changes

2024-11-11 11:39 UTC, merged