Дурыничев Дмитрий. Задача 1. Вариант 8. Нахождение наиболее отличающихся по значению соседних элементов вектора.
learning-process/ppc-2024-autumn pull request #249
Opened 2024-11-07 15:22 UTC by ofuuse

### Описание алгоритмов
### Последовательная программа:

1. Инициализация и валидация:

Проверяется, что входной массив содержит не менее двух элементов (иначе расчет разницы невозможен) и что есть место для записи двух элементов результата.

2. Предобработка:

Загружаем массив целых чисел из структуры taskData и сохраняем его в вектор input.
Инициализируем вектор result размером в два элемента для хранения результата (элементов с наибольшей разницей).

3. Вычисление максимальной разницы:

Устанавливаем начальные значения для наибольшей разницы maxDiff и для пары элементов с этой разницей.
Проходим по вектору input, начиная со второго элемента, и на каждой итерации вычисляем разницу diff по модулю между текущим элементом и предыдущим.
Если diff больше maxDiff, обновляем maxDiff и сохраняем элементы текущей пары в result, таким образом отслеживая пару соседних элементов с наибольшей разницей.

4. Постобработка:

Сохраняем результат (два элемента с максимальной разницей) в выходной массив taskData->outputs.

### Параллельная программа:

1. Инициализация и валидация:

Проверяется, что входной массив содержит не менее двух элементов и что в выходном массиве можно хранить два элемента результата.
Только процесс с рангом 0 выполняет данную проверку.

2. Предобработка (распределение данных между процессами):

Процесс с рангом 0 загружает вектор input из структуры taskData.
Рассчитывается размер подмассива (chunk_size), который будет обрабатываться каждым процессом, исходя из общего количества процессов и размера вектора input.
Процесс с рангом 0 отправляет каждому процессу соответствующую часть вектора с помощью boost::mpi::send, включая смещение (начальный индекс) этой части в исходном векторе.

3. Локальный расчет в каждом процессе:

Каждый процесс принимает свою часть данных (chunk) и начальный индекс chunkStart.
Каждый процесс находит в своем подмассиве пару соседних элементов с наибольшей разницей, сохраняя результат в виде структуры chunk_result, содержащей индексы пары элементов и величину разницы между ними.

4. Сбор данных с процессов и вычисление глобального результата:

С помощью функции boost::mpi::reduce, пара элементов с максимальной разницей выбирается среди всех подмассивов. Оператор MPI_MAX находит максимальное значение разницы, и итоговый результат сохраняется в result.
Процесс с рангом 0 получает глобальный результат.

5. Постобработка:

Процесс с рангом 0 сохраняет итоговый результат (два элемента с максимальной разницей) в выходной массив taskData->outputs.

2024-11-07 16:25 UTC, WholeHorse commented on tasks/mpi/durynichev_d_most_different_neighbor_elements/func_tests/main.cpp
> +#include <vector>
better to move includes in header

2024-11-07 16:32 UTC, ofuuse commented on tasks/mpi/durynichev_d_most_different_neighbor_elements/func_tests/main.cpp
> +#include <vector>
Done

2024-11-07 16:32 UTC, ofuuse commented on tasks/mpi/durynichev_d_most_different_neighbor_elements/perf_tests/main.cpp
> +#include <boost/serialization/map.hpp>
Removed

2024-11-07 16:33 UTC, allnes requested changes

2024-11-07 16:33 UTC, allnes commented on tasks/mpi/durynichev_d_most_different_neighbor_elements/src/ops_mpi.cpp
> +std::vector<int> durynichev_d_most_different_neighbor_elements_mpi::getRandomVector(size_t size) {
please move it tests files

2024-11-07 16:39 UTC, ofuuse commented on tasks/mpi/durynichev_d_most_different_neighbor_elements/src/ops_mpi.cpp
> +std::vector<int> durynichev_d_most_different_neighbor_elements_mpi::getRandomVector(size_t size) {
Moved

2024-11-07 16:44 UTC, WholeHorse approved these changes

2024-11-07 17:00 UTC, allnes approved these changes

2024-11-07 17:04 UTC, artich02 approved these changes

2024-11-07 17:12 UTC, ofuuse commented on tasks/mpi/durynichev_d_most_different_neighbor_elements/include/ops_mpi.hpp
> +
Deleted

2024-11-08 00:35 UTC, aobolensk requested changes

2024-11-08 00:35 UTC, aobolensk commented on tasks/mpi/durynichev_d_most_different_neighbor_elements/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(size_t size);
Please, move it to the test module

2024-11-08 00:35 UTC, aobolensk commented on tasks/mpi/durynichev_d_most_different_neighbor_elements/func_tests/main.cpp
> +TEST(durynichev_d_most_different_neighbor_elements_mpi, default_vector) {
Please, add more tests for different corner cases (including the tests with fixed data)

2024-11-08 09:04 UTC, ofuuse commented on tasks/mpi/durynichev_d_most_different_neighbor_elements/func_tests/main.cpp
> +TEST(durynichev_d_most_different_neighbor_elements_mpi, default_vector) {
Added 6 tests

2024-11-08 09:04 UTC, ofuuse commented on tasks/mpi/durynichev_d_most_different_neighbor_elements/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(size_t size);
Moved

2024-11-08 10:50 UTC, ofuuse commented on tasks/mpi/durynichev_d_most_different_neighbor_elements/func_tests/main.cpp
> +TEST(durynichev_d_most_different_neighbor_elements_mpi, default_vector) {
Added

2024-11-08 11:26 UTC, ofuuse commented on tasks/mpi/durynichev_d_most_different_neighbor_elements/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(size_t size);
Moved

2024-11-09 03:05 UTC, aobolensk approved these changes

2024-11-09 03:05 UTC, merged