Golovkin integration rectangular method
learning-process/ppc-2024-autumn pull request #254
Opened 2024-11-07 17:21 UTC by Mxaqq

Данная задача далась мне нелегко. С функционалом самого метода проблем не было. И seq реализация тоже не вызвала проблем. Основной проблемой было прохождение тестов в Actions на других системах. Проходило только на Windows на остальных процессоры зависали на какой-то определенной итерации Долго думал что можно сделать много у кого спрашивал, запускал на виртуальной машине ubuntu чтобы посмотреть что не так так и не выяснил. Принял решение раскидать все задачи по всем четырем процессам дабы оптимизировать работу, а также ввел обработку зависаний в самих методах validation pre_proces run post_proces. Работает таким образом если процесс не выполняется за определенный срок он просто завершается не мешая следующему процессу. Это было основная сложность.

2024-11-08 07:09 UTC, Semyon1104 commented
You need test coverage 95% at least

2024-11-08 08:07 UTC, Semyon1104 commented on tasks/mpi/golovkin_integration_rectangular_method/include/ops_mpi.hpp
> +
look at the example of the poolquest, mpi also implements the seq version to check the mpi version in tests

2024-11-08 10:42 UTC, KAPUSHA228 commented on tasks/mpi/golovkin_integration_rectangular_method/func_tests/main.cpp
> +/* TEST(golovkin_integration_rectangular_method, test_linear_function) {
убрать лишние комментарии

2024-11-08 16:03 UTC, Mxaqq commented on tasks/mpi/golovkin_integration_rectangular_method/func_tests/main.cpp
> +/* TEST(golovkin_integration_rectangular_method, test_linear_function) {
Сделано

2024-11-09 00:07 UTC, Mxaqq commented on tasks/seq/golovkin_integration_rectangular_method/src/ops_seq.cpp
> +  if (taskData->inputs.size() < 3 || taskData->outputs.empty()) {
ok

2024-11-09 02:23 UTC, Mxaqq commented on tasks/mpi/golovkin_integration_rectangular_method/include/ops_mpi.hpp
> +
fix it

2024-11-10 01:22 UTC, allnes requested changes

2024-11-10 01:22 UTC, allnes commented on tasks/mpi/golovkin_integration_rectangular_method/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
please remove it

2024-11-10 01:22 UTC, allnes commented on tasks/mpi/golovkin_integration_rectangular_method/src/ops_mpi.cpp
> +  broadcast(world, is_valid, 0);
please describe this check

2024-11-10 01:22 UTC, allnes commented on tasks/mpi/golovkin_integration_rectangular_method/src/ops_mpi.cpp
> +  broadcast(world, num_partitions, 0);
please use all mpi functions in run()

2024-11-10 16:18 UTC, Mxaqq commented on tasks/mpi/golovkin_integration_rectangular_method/src/ops_mpi.cpp
> +  broadcast(world, num_partitions, 0);
I fix it

2024-11-10 16:18 UTC, Mxaqq commented on tasks/mpi/golovkin_integration_rectangular_method/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
I fix it

2024-11-10 18:22 UTC, Mxaqq commented on tasks/mpi/golovkin_integration_rectangular_method/src/ops_mpi.cpp
> +  broadcast(world, is_valid, 0);
I wrote a test check for this segment

2024-11-11 11:40 UTC, allnes approved these changes

2024-11-12 15:08 UTC, Mxaqq commented on tasks/mpi/golovkin_integration_rectangular_method/src/ops_mpi.cpp
> +  broadcast(world, lower_bound, 0);
I fix it

2024-11-12 15:09 UTC, Mxaqq commented on tasks/seq/golovkin_integration_rectangular_method/func_tests/main.cpp
> +TEST(golovkin_integration_rectangular_method_seq, Calculate_ZeroToOne) {
Added a couple of additional tests

2024-11-12 15:09 UTC, Mxaqq commented on tasks/seq/golovkin_integration_rectangular_method/func_tests/main.cpp
> +TEST(golovkin_integration_rectangular_method_seq, Calculate_ZeroToOne) {
Added a couple of additional tests

2024-11-12 15:25 UTC, Mxaqq commented on tasks/mpi/golovkin_integration_rectangular_method/src/ops_mpi.cpp
> +  if (world.rank() >= 4) {
I had a problem that processor 0 freezes at the run stage. I have been thinking for a long time how this can be resolved. Since everything went well on my system on one processor. Linux did not work on 4 processors. Processes with rank 4 and higher perform the bulk of the calculations in order to offload process 0. Process 0 manages data synchronization and the collection of final results, minimizing its own computational costs and avoiding overload.

2024-11-13 00:34 UTC, aobolensk commented on tasks/mpi/golovkin_integration_rectangular_method/src/ops_mpi.cpp
> +  if (world.rank() >= 4) {
What about the case when we don't have 5+ processes?

2024-11-13 03:11 UTC, Mxaqq commented on tasks/mpi/golovkin_integration_rectangular_method/src/ops_mpi.cpp
> +  if (world.rank() >= 4) {
I'm ashamed to admit that I didn't think about it. You're really right. I added the condition world.size() < 5 || world.rank() >= 4: If there are less than 5 processes, then all processes perform initialization and participate in calculations. If there are 5 or more processes, only processes with rank 4 and higher perform initialization and calculations. Also, when I added this condition, I saw that two tests were incorrect and deleted them.

2024-11-18 17:40 UTC, Semyon1104 approved these changes

2024-11-18 18:27 UTC, KAPUSHA228 approved these changes

2024-11-19 01:09 UTC, aobolensk approved these changes

2024-11-19 01:10 UTC, merged