Будажапова Екатерина. Задача 1. Вариант 23. Частота символа в строке.
learning-process/ppc-2024-autumn pull request #255
Opened 2024-11-07 18:02 UTC by Save-Yourself

Ищем сколько раз первый символ строки встречается в ней.

2024-11-09 20:10 UTC, DSolo03 requested changes

2024-11-09 20:10 UTC, DSolo03 commented on tasks/mpi/budazhapova_e_count_freq_character/src/count_freq_character_mpi.cpp
> +using namespace std::chrono_literals;
please, don't include `std::chrono_literals` in global namespace, if you don't using it

2024-11-09 20:10 UTC, DSolo03 commented on tasks/mpi/budazhapova_e_count_freq_character/src/count_freq_character_mpi.cpp
> +}
please, put all functions that used only for tests in test files

2024-11-09 21:09 UTC, DSolo03 approved these changes

2024-11-10 01:13 UTC, aobolensk requested changes

2024-11-10 01:13 UTC, aobolensk commented on tasks/mpi/budazhapova_e_count_freq_character/include/count_freq_character_mpi_header.hpp
> +std::string getRandomString(int length);
Please, move test functions to the test module

2024-11-10 01:13 UTC, aobolensk commented on tasks/mpi/budazhapova_e_count_freq_character/perf_tests/count_freq_character_pref_test_mpi.cpp
> +  char symb = 'a';
Consider using random strings for perf tests

2024-11-10 01:13 UTC, aobolensk commented on tasks/mpi/budazhapova_e_count_freq_character/perf_tests/count_freq_character_pref_test_mpi.cpp
> +  std::string global_str(100, 'a');
Perf tests should be performed on largs strings

2024-11-10 01:15 UTC, allnes requested changes

2024-11-10 01:15 UTC, allnes commented on tasks/seq/budazhapova_e_count_freq_character/src/count_freq_character.cpp
> +using namespace std::chrono_literals;
please remove it

2024-11-10 20:18 UTC, StroganovM approved these changes
Add test without symbol in string

2024-11-11 11:41 UTC, allnes approved these changes

2024-12-01 08:30 UTC, aobolensk approved these changes

2024-12-01 08:31 UTC, merged