Вершинина Александра. Задача 1. Вариант 21. Интегрирование – метод Монте-Карло
learning-process/ppc-2024-autumn pull request #258
Opened 2024-11-07 19:11 UTC by sanya2905

Последовательное решение:
Определяем сколько случайных точек попало в нашу область, вычисляем плотность и с помощью нее получаем значение нужного нам интеграла.
Параллельное решение:
Тоже самое, только используется фиксированное число итераций, входные данные рассылаются всем процессам через boost::mpi::broadcast и распараллеливается финальная часть алгоритма.

2024-11-08 20:14 UTC, ermilovad requested changes
Use std::copy

2024-11-08 20:16 UTC, sanya2905 commented
> Use std::copy

fixed :)

2024-11-08 20:16 UTC, ermilovad approved these changes

2024-11-08 21:04 UTC, belovtut requested changes
You specify the number of iterations manually twice, so when you want to change the number, you have to change both lines. You may use constant

2024-11-08 22:38 UTC, sanya2905 commented
> You specify the number of iterations manually twice, so when you want to change the number, you have to change both lines. You may use constant

fixed :)

2024-11-08 23:04 UTC, belovtut approved these changes

2024-11-09 11:43 UTC, aobolensk requested changes

2024-11-09 11:43 UTC, aobolensk commented on tasks/mpi/vershinina_a_integration_the_monte_carlo_method/include/ops_mpi.hpp
> +std::vector<double> getRandomVector(double sz);
Please, move it to test module

2024-11-09 11:43 UTC, aobolensk commented on tasks/seq/vershinina_a_integration_the_monte_carlo_method/func_tests/main.cpp
> +TEST(vershinina_a_integration_the_monte_carlo_method, test1) {
Please, add random tests for seq as well

2024-11-09 11:43 UTC, aobolensk commented on tasks/mpi/vershinina_a_integration_the_monte_carlo_method/perf_tests/main.cpp
> +    count_size_vector = 4;
Perf test should be run on larger sizes

2024-11-09 14:49 UTC, sanya2905 commented on tasks/mpi/vershinina_a_integration_the_monte_carlo_method/perf_tests/main.cpp
> +    count_size_vector = 4;
> Perf test should be run on larger sizes

In my solution the vector can consist of only 4 values: xmin xmax (integration limits), ymin ymax (function limits)

2024-11-09 14:50 UTC, sanya2905 commented on tasks/seq/vershinina_a_integration_the_monte_carlo_method/func_tests/main.cpp
> +TEST(vershinina_a_integration_the_monte_carlo_method, test1) {
> Please, add random tests for seq as well

What should be used as a reference solution?

2024-11-09 21:24 UTC, sanya2905 commented on tasks/mpi/vershinina_a_integration_the_monte_carlo_method/include/ops_mpi.hpp
> +std::vector<double> getRandomVector(double sz);
> Please, move it to test module

fixed :)

2024-11-10 01:14 UTC, allnes requested changes

2024-11-10 01:14 UTC, allnes commented on tasks/seq/vershinina_a_integration_the_monte_carlo_method/src/ops_seq.cpp
> +using namespace std::chrono_literals;
please remove it

2024-11-10 01:14 UTC, allnes commented on tasks/mpi/vershinina_a_integration_the_monte_carlo_method/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
please remove it

2024-11-10 01:14 UTC, allnes commented on tasks/seq/vershinina_a_integration_the_monte_carlo_method/src/ops_seq.cpp
> +  for (count = 0; count < 100000; count++) {
please parametrize iterations count

2024-11-10 01:15 UTC, aobolensk commented on tasks/seq/vershinina_a_integration_the_monte_carlo_method/func_tests/main.cpp
> +TEST(vershinina_a_integration_the_monte_carlo_method, test1) {
Integral value that is can be calculated using math formula

2024-11-10 01:16 UTC, aobolensk commented on tasks/mpi/vershinina_a_integration_the_monte_carlo_method/perf_tests/main.cpp
> +    count_size_vector = 4;
Yes, but you need to be able to customize iterations count.

See https://github.com/learning-process/ppc-2024-autumn/pull/258#discussion_r1835557138 as well

2024-11-10 21:17 UTC, sanya2905 commented on tasks/seq/vershinina_a_integration_the_monte_carlo_method/func_tests/main.cpp
> +TEST(vershinina_a_integration_the_monte_carlo_method, test1) {
> Integral value that is can be calculated using math formula

fixed :)

2024-11-10 21:18 UTC, sanya2905 commented on tasks/seq/vershinina_a_integration_the_monte_carlo_method/src/ops_seq.cpp
> +using namespace std::chrono_literals;
> please remove it

fixed :)

2024-11-10 21:18 UTC, sanya2905 commented on tasks/mpi/vershinina_a_integration_the_monte_carlo_method/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
> please remove it

fixed :)

2024-11-10 21:18 UTC, sanya2905 commented on tasks/seq/vershinina_a_integration_the_monte_carlo_method/src/ops_seq.cpp
> +  for (count = 0; count < 100000; count++) {
> please parametrize iterations count

fixed :)

2024-11-10 21:19 UTC, sanya2905 commented on tasks/mpi/vershinina_a_integration_the_monte_carlo_method/perf_tests/main.cpp
> +    count_size_vector = 4;
> Yes, but you need to be able to customize iterations count.
> 
> See [#258 (comment)](https://github.com/learning-process/ppc-2024-autumn/pull/258#discussion_r1835557138) as well

fixed :)

2024-11-11 11:42 UTC, allnes approved these changes

2024-11-11 14:38 UTC, merged