Комшина Дарья. Задача 1. Вариант 4. Минимальное значение элемента в векторе.
learning-process/ppc-2024-autumn pull request #259
Opened 2024-11-08 00:22 UTC by MikasaAkc

Алгоритм использует линейный поиск, который проходит по всем элементам массива и сравнивает каждый элемент с текущим минимальным значением.

Описание последовательной задачи.
Данная программа осуществляет поиск минимального элемента в заданном векторе целых чисел, применяя последовательный метод.

Описание MPI задачи
Данная программа распределяет задачу поиска минимального элемента в векторе целых чисел между несколькими процессами с использованием MPI. Основные этапы работы аналогичны последовательному подходу, но с использованием параллельных вычислений через MPI.

2024-11-09 17:02 UTC, Dxppi commented on tasks/seq/komshina_d_min_of_vector_elements/func_tests/main.cpp
Add test with a zero vector

2024-11-09 17:06 UTC, MikasaAkc commented on tasks/seq/komshina_d_min_of_vector_elements/func_tests/main.cpp
TEST(komshina_d_min_of_vector_elements_mpi, Empty_Vector) является тестом для проверки пустого(нулевого) вектора.

2024-11-10 01:26 UTC, allnes requested changes

2024-11-10 01:26 UTC, allnes commented on tasks/mpi/komshina_d_min_of_vector_elements/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
please remove it

2024-11-10 01:26 UTC, allnes commented on tasks/seq/komshina_d_min_of_vector_elements/src/ops_seq.cpp
> +using namespace std::chrono_literals;
please remove it

2024-11-10 07:28 UTC, MikasaAkc commented on tasks/mpi/komshina_d_min_of_vector_elements/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
fixed

2024-11-10 07:28 UTC, MikasaAkc commented on tasks/seq/komshina_d_min_of_vector_elements/src/ops_seq.cpp
> +using namespace std::chrono_literals;
fixed

2024-11-10 09:00 UTC, MikasaAkc commented on tasks/seq/komshina_d_min_of_vector_elements/src/ops_seq.cpp
> +using namespace std::chrono_literals;
fixed

2024-11-10 11:06 UTC, PutinVVV approved these changes

2024-11-10 22:42 UTC, NeeMiyuki requested changes

2024-11-10 22:42 UTC, NeeMiyuki commented on tasks/mpi/komshina_d_min_of_vector_elements/include/ops_mpi.hpp
> +#include "core/task/include/task.hpp"
string and numeric are include but there is no sign that they are used and should be revomed. also remove a comment at the first line

2024-11-11 00:17 UTC, MikasaAkc commented on tasks/mpi/komshina_d_min_of_vector_elements/include/ops_mpi.hpp
> +#include "core/task/include/task.hpp"
fixed)

2024-11-11 11:42 UTC, allnes approved these changes

2024-11-11 11:55 UTC, NeeMiyuki approved these changes

2024-11-11 14:40 UTC, aobolensk commented
![image](https://github.com/user-attachments/assets/dd33345d-9887-46a5-b958-31940f16a9b0)

Please cover missing lines with tests

2024-11-11 14:44 UTC, aobolensk requested changes

2024-11-11 14:44 UTC, aobolensk commented on tasks/mpi/komshina_d_min_of_vector_elements/src/ops_mpi.cpp
> +int Min(const std::vector<int>& res) {
Consider using std::min_element

2024-11-11 14:44 UTC, aobolensk commented on tasks/mpi/komshina_d_min_of_vector_elements/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
Please, move test functions to the test module

2024-11-11 20:03 UTC, MikasaAkc commented on tasks/mpi/komshina_d_min_of_vector_elements/src/ops_mpi.cpp
> +int Min(const std::vector<int>& res) {
Fixed

2024-11-11 20:03 UTC, MikasaAkc commented on tasks/mpi/komshina_d_min_of_vector_elements/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
Fixed(deleted because it is not used in tests)

2024-11-12 00:12 UTC, aobolensk approved these changes

2024-11-12 00:12 UTC, merged