Шуравина Оксана. Задача 1. Вариант 21. Интегрирование – метод Монте-Карло.
learning-process/ppc-2024-autumn pull request #266
Opened 2024-11-08 13:40 UTC by shyravina19102004

2024-11-08 20:21 UTC, dasha1112 commented on tasks/mpi/shuravina_o_monte_carlo/func_tests/main.cpp
> +}
Please, add more then one test

2024-11-08 20:21 UTC, dasha1112 commented on tasks/seq/shuravina_o_monte_carlo/func_tests/main.cpp
> +}
Please, add more then one test there too

2024-11-08 21:07 UTC, shyravina19102004 commented on tasks/seq/shuravina_o_monte_carlo/func_tests/main.cpp
> +}
пофиксила

2024-11-08 22:44 UTC, keshaproger requested changes

2024-11-08 22:44 UTC, keshaproger commented on tasks/mpi/shuravina_o_monte_carlo/func_tests/main.cpp
> +  int rank = world.rank();
Unused variable, remove it

2024-11-08 23:02 UTC, keshaproger requested changes

2024-11-08 23:02 UTC, keshaproger commented on tasks/seq/shuravina_o_monte_carlo/include/ops_seq.hpp
> +  void set_function(std::function<double(double)> func) { f_ = func; }
Change: void set_function(std::function<double(double)> func) { f_ = func; }
to: void set_function(std::function<double(double)> func) { f_ = std::move(func); }

2024-11-08 23:21 UTC, shyravina19102004 commented on tasks/seq/shuravina_o_monte_carlo/include/ops_seq.hpp
> +  void set_function(std::function<double(double)> func) { f_ = func; }
fixed

2024-11-08 23:22 UTC, keshaproger approved these changes

2024-11-09 11:46 UTC, aobolensk requested changes

2024-11-09 11:46 UTC, aobolensk commented on tasks/mpi/shuravina_o_monte_carlo/src/ops_mpi.cpp
> +  int num_points = 1000000;
This should be customizable

2024-11-09 11:46 UTC, aobolensk commented on tasks/mpi/shuravina_o_monte_carlo/src/ops_mpi.cpp
> +  auto f = [](double x) { return x * x; };
Is function hardcoded here? This is not correct. You need to support any integrable function here

2024-11-09 11:46 UTC, aobolensk commented on tasks/mpi/shuravina_o_monte_carlo/src/ops_mpi.cpp
> +  double b = 1.0;
This also should be cuatomizable

2024-11-09 11:46 UTC, aobolensk commented on tasks/mpi/shuravina_o_monte_carlo/perf_tests/main.cpp
> +TEST(MonteCarloIntegrationTaskParallel, test_pipeline_run) {
Perf test should be run on more iterations (they are called num_points in your code)

2024-11-09 11:48 UTC, aobolensk commented
Previous approves are not considered valid. Please collect 1 more peer review on top

2024-11-09 17:55 UTC, shyravina19102004 commented on tasks/mpi/shuravina_o_monte_carlo/perf_tests/main.cpp
> +TEST(MonteCarloIntegrationTaskParallel, test_pipeline_run) {
fixed

2024-11-10 01:16 UTC, allnes commented on tasks/mpi/shuravina_o_monte_carlo/src/ops_mpi.cpp
> +  std::uniform_real_distribution<> dis(a_, b_);
please initilize it outside run()

2024-11-10 09:37 UTC, shyravina19102004 commented on tasks/mpi/shuravina_o_monte_carlo/src/ops_mpi.cpp
> +  std::uniform_real_distribution<> dis(a_, b_);
fixed

2024-11-10 10:30 UTC, dasha1112 approved these changes

2024-11-10 13:09 UTC, aobolensk commented on tasks/mpi/shuravina_o_monte_carlo/src/ops_mpi.cpp
> +  auto f = [](double x) { return x * x; };
Tests still contain `x * x` only

2024-11-10 13:10 UTC, aobolensk requested changes

2024-11-10 13:10 UTC, aobolensk commented on tasks/mpi/shuravina_o_monte_carlo/func_tests/main.cpp
> +    std::cerr << "Process " << world.rank() << " caught exception: " << e.what() << std::endl;
Please, do not print in tests

2024-11-10 13:10 UTC, aobolensk commented on tasks/mpi/shuravina_o_monte_carlo/func_tests/main.cpp
> +TEST(MonteCarloIntegrationTaskParallel, Test_Integration) {
Too few tests, you have only one function tested

2024-11-24 01:28 UTC, aobolensk commented
> ## [Codecov](https://app.codecov.io/gh/learning-process/ppc-2024-autumn/pull/266?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=learning-process) Report
> Attention: Patch coverage is `80.59701%` with `13 lines` in your changes missing coverage. Please review.
> 
> > Project coverage is 96.34%. Comparing base [(`5daf9ab`)](https://app.codecov.io/gh/learning-process/ppc-2024-autumn/commit/5daf9ab13b05a0ed91c1162cc013d1e8571de199?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=learning-process) to head [(`e7b2ef2`)](https://app.codecov.io/gh/learning-process/ppc-2024-autumn/commit/e7b2ef2e0383775c72e2b8b3c28ddc8ea6cca1c6?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=learning-process).
> > Report is 168 commits behind head on master.
> 
> [Files with missing lines](https://app.codecov.io/gh/learning-process/ppc-2024-autumn/pull/266?dropdown=coverage&src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=learning-process)	Patch %	Lines
> [tasks/mpi/shuravina_o_monte_carlo/src/ops_mpi.cpp](https://app.codecov.io/gh/learning-process/ppc-2024-autumn/pull/266?src=pr&el=tree&filepath=tasks%2Fmpi%2Fshuravina_o_monte_carlo%2Fsrc%2Fops_mpi.cpp&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=learning-process#diff-dGFza3MvbXBpL3NodXJhdmluYV9vX21vbnRlX2NhcmxvL3NyYy9vcHNfbXBpLmNwcA==)	78.57%	[3 Missing and 3 partials ⚠️ ](https://app.codecov.io/gh/learning-process/ppc-2024-autumn/pull/266?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=learning-process)
> [tasks/seq/shuravina_o_monte_carlo/src/ops_seq.cpp](https://app.codecov.io/gh/learning-process/ppc-2024-autumn/pull/266?src=pr&el=tree&filepath=tasks%2Fseq%2Fshuravina_o_monte_carlo%2Fsrc%2Fops_seq.cpp&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=learning-process#diff-dGFza3Mvc2VxL3NodXJhdmluYV9vX21vbnRlX2NhcmxvL3NyYy9vcHNfc2VxLmNwcA==)	79.16%	[2 Missing and 3 partials ⚠️ ](https://app.codecov.io/gh/learning-process/ppc-2024-autumn/pull/266?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=learning-process)
> [...ks/mpi/shuravina_o_monte_carlo/include/ops_mpi.hpp](https://app.codecov.io/gh/learning-process/ppc-2024-autumn/pull/266?src=pr&el=tree&filepath=tasks%2Fmpi%2Fshuravina_o_monte_carlo%2Finclude%2Fops_mpi.hpp&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=learning-process#diff-dGFza3MvbXBpL3NodXJhdmluYV9vX21vbnRlX2NhcmxvL2luY2x1ZGUvb3BzX21waS5ocHA=)	87.50%	[1 Missing ⚠️ ](https://app.codecov.io/gh/learning-process/ppc-2024-autumn/pull/266?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=learning-process)
> [...ks/seq/shuravina_o_monte_carlo/include/ops_seq.hpp](https://app.codecov.io/gh/learning-process/ppc-2024-autumn/pull/266?src=pr&el=tree&filepath=tasks%2Fseq%2Fshuravina_o_monte_carlo%2Finclude%2Fops_seq.hpp&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=learning-process#diff-dGFza3Mvc2VxL3NodXJhdmluYV9vX21vbnRlX2NhcmxvL2luY2x1ZGUvb3BzX3NlcS5ocHA=)	85.71%	[1 Missing ⚠️ ](https://app.codecov.io/gh/learning-process/ppc-2024-autumn/pull/266?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=learning-process)
> Additional details and impacted files
> [☔ View full report in Codecov by Sentry](https://app.codecov.io/gh/learning-process/ppc-2024-autumn/pull/266?dropdown=coverage&src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=learning-process). 📢 Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=learning-process).
> 
> 🚨 Try these New Features:
> 
> * [Flaky Tests Detection](https://docs.codecov.com/docs/test-result-ingestion-beta) - Detect and resolve failed and flaky tests

It seems your code coverage is too low

2024-11-26 19:30 UTC, shyravina19102004 commented on tasks/mpi/shuravina_o_monte_carlo/func_tests/main.cpp
> +    std::cerr << "Process " << world.rank() << " caught exception: " << e.what() << std::endl;
fixed

2024-12-29 19:38 UTC, closed without merging