Дерябин Максим. Задача 1. Вариант 23. Подсчет частоты символа в строке
learning-process/ppc-2024-autumn pull request #268
Opened 2024-11-08 14:14 UTC by BrunoBucCcellati

SEQ
Подсчет числа вхождений символа в цикле по всем символам строки
MPI 
Подсчет числа вхождений символа в каждой подстроке размера строка.size() / world.size() на каждом процессе, нулевой процесс считает дополнительно число вхождений на остаточной части строки (строка.size() % world.size()). Результаты суммируются с помощью reduce.

2024-11-08 15:58 UTC, NeiroYT requested changes

2024-11-08 18:09 UTC, laganina-cod commented on tasks/mpi/deryabin_m_symbol_frequency/src/ops_mpi.cpp
> +bool deryabin_m_symbol_frequency_mpi::SymbolFrequencyMPITaskSequential::validation() {
please do tests when data validation returns false

2024-11-08 18:09 UTC, laganina-cod commented on tasks/seq/deryabin_m_symbol_frequency/src/ops_seq.cpp
> +bool deryabin_m_symbol_frequency_seq::SymbolFrequencyTaskSequential::validation() {
same point, please do tests when data validation returns false

2024-11-08 20:46 UTC, laganina-cod requested changes
please fix tests

2024-11-09 05:34 UTC, laganina-cod approved these changes

2024-11-09 09:50 UTC, NeiroYT approved these changes

2024-11-09 11:49 UTC, aobolensk approved these changes

2024-11-10 01:08 UTC, allnes approved these changes

2024-11-10 01:08 UTC, merged