add nix flake
learning-process/ppc-2024-autumn pull request #28
Opened 2024-10-20 14:29 UTC by 0P4RY5H

Всем привет! Я использую NixOS.

2024-10-20 14:50 UTC, aobolensk requested changes

2024-10-20 14:50 UTC, aobolensk commented on flake.lock
> +{
No objections to that change, but please add CI checks to verify that (deps could become stale or there will be changes needed in the future). Also, please add a notion on how to use this dev environment in README: split Linux part on Debian/Ubuntu and Nix (I guess there are guys who are using Arch or anything like that, so it'd be useful)

2024-10-20 15:25 UTC, 0P4RY5H commented on flake.lock
> +{
Unfortunately, only one and a half zempekops use NixOS, but such people are very conscientious and will definitely send a patch to update stale deps in such a case :)

2024-10-21 00:09 UTC, aobolensk commented on flake.lock
> +{
Yes, I've faced with NixOS community :)
Ok, let's leave this as is. Thanks for updating the README file. You may consider sending this patch to the template repo for future years students: https://github.com/learning-process/parallel_programming_course

2024-10-21 00:09 UTC, aobolensk approved these changes

2024-10-21 00:22 UTC, merged