Васильев Сергей Задача 2 вариант 15 Ленточная горизонтальная схема
learning-process/ppc-2024-autumn pull request #280
Opened 2024-11-12 16:56 UTC by venn2713

Здесь представлена параллельная реализация умножения матрицы на вектор с использованием полосовой горизонтальной схемы разбиения и MPI. Метод равномерно распределяет строки матрицы между доступными процессами, что позволяет сбалансировать нагрузку и минимизировать накладные расходы на передачу данных.

Основные особенности реализации:

- **Распределение нагрузки**: Функция `calculate_distribution` вычисляет, как распределить строки матрицы между процессами, учитывая ситуации, когда количество процессов превышает количество строк.

- **Параллельное выполнение**: В классе `StripedHorizontalSchemeParallelMPI` входной вектор передается всем процессам. Матрица распределяется так, что каждый процесс получает только свои строки. Затем каждый процесс выполняет локальные вычисления для своей части матрицы и общего вектора.

- **Сбор результатов**: После выполнения локальных вычислений частичные результаты собираются от всех процессов, формируя итоговый вектор.

- **Последовательная версия**: Также реализована последовательная версия (`StripedHorizontalSchemeSequentialMPI`) для сравнения производительности и валидации корректности параллельного решения.

2024-11-12 18:49 UTC, korablev-vm requested changes

2024-11-14 20:09 UTC, hasanyanovk commented on tasks/mpi/vasilev_s_striped_horizontal_scheme/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, distribution, 0);
You mustn't share these two vectors:
`displacement`: it's never used in not root processes
`distribution`: each process can calculate it's own size without `mpi::broadcast`, it's faster than sharing std::vector
or, if you want to share all of these data, you can unite it to the structure, serialize it and use 1 `mpi::broadcast` to share it

2024-11-15 19:28 UTC, venn2713 commented on tasks/mpi/vasilev_s_striped_horizontal_scheme/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, distribution, 0);
I agree, boost::mpi::broadcast(world, displacement, 0) is not needed, but using boost::mpi::broadcast(world, distribution, 0) is justified, from my point of view

2024-11-16 06:56 UTC, korablev-vm approved these changes

2024-11-19 01:21 UTC, aobolensk approved these changes

2024-11-21 14:47 UTC, allnes commented on tasks/mpi/vasilev_s_striped_horizontal_scheme/func_tests/main.cpp
> +  std::uniform_int_distribution<> dist(0, 1000);
please use negative values

2024-11-21 14:47 UTC, allnes commented on tasks/mpi/vasilev_s_striped_horizontal_scheme/perf_tests/main.cpp
> +    num_cols = 1000;
please use 1024

2024-11-21 14:48 UTC, allnes commented on tasks/mpi/vasilev_s_striped_horizontal_scheme/perf_tests/main.cpp
> +    num_cols = 1000;
same please use 1024

2024-11-21 14:49 UTC, allnes commented on tasks/mpi/vasilev_s_striped_horizontal_scheme/func_tests/main.cpp
> +  }
please check it in validation()

2024-11-21 14:52 UTC, allnes commented on tasks/mpi/vasilev_s_striped_horizontal_scheme/func_tests/main.cpp
> +  }
validation need to have same behaviour for all processes

2024-11-21 14:52 UTC, allnes commented on tasks/mpi/vasilev_s_striped_horizontal_scheme/func_tests/main.cpp
> +  int num_rows = 4;
please check prime numbers too

2024-11-25 18:41 UTC, allnes approved these changes

2024-11-25 18:41 UTC, merged