Зиновьев Александр Задача 1 Вариант 12 Сумма значений по столбцам матрицы
learning-process/ppc-2024-autumn pull request #282
Opened 2024-11-13 13:50 UTC by kobych

Здесь представлены последовательная и параллельная реализации суммы значений по столбцам матрицы. **В последовательной** реализуем вложенный цикл, проходя по каждому столбцу матрицы, суммируя значения её элементов. Итоговые суммы помещаются в отдельный вектор. **В параллельной** распределяем столбцы матрицы в зависимости от числа доступных процессов. Определяем величину, которая обозначает количество столбцов, отведенных каждому процессу, а также индекс последнего обрабатываемого столбца для каждого процесса. Каждая группа столбцов суммируется с использованием функции, аналогичной той, что применяется в последовательной версии. Полученные результаты затем консолидируются в общий вектор.

2024-11-13 14:14 UTC, KADCHDR requested changes

2024-11-13 14:14 UTC, KADCHDR commented on tasks/mpi/zinoviev_a_sum_cols_matrix/src/ops_mpi.cpp
> +}
Move this to tests

2024-11-13 14:14 UTC, KADCHDR commented on tasks/seq/zinoviev_a_sum_cols_matrix/include/ops_seq.hpp
> +int createLinearCoordinates(int x, int y, int width);
Move this to tests

2024-11-13 14:14 UTC, KADCHDR commented on tasks/mpi/zinoviev_a_sum_cols_matrix/include/ops_mpi.hpp
> +                                              int endX);
Move this to tests

2024-11-13 14:53 UTC, KADCHDR requested changes

2024-11-13 14:53 UTC, KADCHDR commented on tasks/seq/zinoviev_a_sum_cols_matrix/src/ops_seq.cpp
> +using namespace std::chrono_literals;
Do you use it?

2024-11-13 14:53 UTC, KADCHDR commented on tasks/mpi/zinoviev_a_sum_cols_matrix/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
Do you use it?

2024-11-13 14:58 UTC, kobych commented on tasks/seq/zinoviev_a_sum_cols_matrix/src/ops_seq.cpp
> +using namespace std::chrono_literals;
fixed

2024-11-13 14:59 UTC, kobych commented on tasks/mpi/zinoviev_a_sum_cols_matrix/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
fixed

2024-11-13 15:05 UTC, KADCHDR approved these changes

2024-11-13 20:27 UTC, dasha1112 commented on tasks/mpi/zinoviev_a_sum_cols_matrix/src/ops_mpi.cpp
> +std::vector<int> zinoviev_a_sum_cols_matrix_mpi::generateRandomVector(int sz) {
Your tests are failed because there function generateRandomVector has parametr - int sz, but in include function generateRandomVector has parametr - int size. Thats why tests give an error zinoviev_a_sum_cols_matrix_mpi::generateRandomVector has a definition with different parameter names. Change parametr name - give the parematr only one name.

2024-11-13 20:27 UTC, dasha1112 commented on tasks/mpi/zinoviev_a_sum_cols_matrix/src/ops_mpi.cpp
> +
In functions computeLinearCoordinates and calculateMatrixSumSequential the same problem. Change parametr name - give the parematr only one name.

2024-11-13 22:47 UTC, dasha1112 approved these changes

2024-11-19 01:22 UTC, aobolensk requested changes

2024-11-19 01:22 UTC, aobolensk commented on tasks/mpi/zinoviev_a_sum_cols_matrix/src/ops_mpi.cpp
> +
Please, move test functions to the test module

2024-11-19 01:22 UTC, aobolensk commented on tasks/mpi/zinoviev_a_sum_cols_matrix/src/ops_mpi.cpp
> +  }
Please, move MPI data transfer to ::run()

2024-11-19 01:22 UTC, aobolensk commented on tasks/stl/example/func_tests/main.cpp
> +}
Please, do not modify common files!

2024-11-21 14:57 UTC, allnes commented on tasks/mpi/zinoviev_a_sum_cols_matrix/src/ops_mpi.cpp
> +    vec[i] = gen() % 100;
please use negative values too

2024-11-27 20:25 UTC, kobych commented on tasks/mpi/zinoviev_a_sum_cols_matrix/src/ops_mpi.cpp
> +
fixed

2024-11-27 20:25 UTC, kobych commented on tasks/stl/example/func_tests/main.cpp
> +}
fixed

2024-11-27 20:25 UTC, kobych commented on tasks/mpi/zinoviev_a_sum_cols_matrix/src/ops_mpi.cpp
> +    vec[i] = gen() % 100;
fixed

2024-12-01 20:41 UTC, allnes approved these changes

2024-12-02 17:20 UTC, aobolensk approved these changes

2024-12-02 17:20 UTC, merged