Remove OpenMP impact on other modules
learning-process/ppc-2024-autumn pull request #284
Opened 2024-11-14 00:55 UTC by kmichaelk

Currently OpenMP compilation flags affect all project modules, failing build of #283 (`error: capturing a structured binding is not yet supported in OpenMP` - [log](https://github.com/learning-process/ppc-2024-autumn/actions/runs/11828207401/job/32957882668?pr=283))

2024-11-14 22:01 UTC, kmichaelk commented
Had to also pass compile options to the module lib (`${OpenMP_CXX_FLAGS}` = `-fopenmp`) to make it work with gcc, should work now

2024-11-15 17:21 UTC, kmichaelk commented
@aobolensk

2024-11-15 17:24 UTC, aobolensk requested changes

2024-11-15 17:24 UTC, aobolensk commented on CMakeLists.txt
> +if( USE_OMP )
What is reason of this change?

2024-11-15 17:28 UTC, kmichaelk commented on CMakeLists.txt
> +if( USE_OMP )
I don't think we should enable OpenMP if its flag was not set

2024-11-15 17:29 UTC, kmichaelk commented on CMakeLists.txt
> +if( USE_OMP )
`USE_SEQ` is de facto always true, so OpenMP is always enabled, while this behavior is different with MPI, STL & TBB.

2024-11-15 17:30 UTC, aobolensk commented on CMakeLists.txt
> +if( USE_OMP )
Seq runs allow using OMP for testing and for time measurement for all threads tasks (omp_get_wtime). It will be used in the next term

2024-11-15 17:32 UTC, aobolensk commented on CMakeLists.txt
> +if( USE_OMP )
> `USE_SEQ` is de facto always true, so OpenMP is always enabled

That statement is true, but this is expecte and justified

2024-11-15 17:38 UTC, kmichaelk commented on CMakeLists.txt
> +if( USE_OMP )
Added linking for SEQ

2024-11-15 21:14 UTC, kmichaelk commented
The motivating problem is clang-only btw: such code successfully builds under GCC and MSVC.

The bug in clang that triggered those OpenMPI-compliance checks in pieces of code that does not use omp has been fixed in clang 19.x, but I doubt the fix will be backported to clang 18.x.

That is, if someone (like me, for example) writes a task solution with gcc (or even with MSVC) as compiler, he will find out about this problem only when running workflows, and he will have to redo the solution, which is not good and fair.

2024-11-16 13:11 UTC, kmichaelk commented on CMakeLists.txt
> +if( USE_OMP )
I'm not sure that enabling OpenMP compiler/pragmas support for SEQ is needed though, do you need only `omp_get_wtime` or something more?

2024-11-20 19:13 UTC, MoiseevArt commented
I wanted to use this too, but due to this problem I had to abandon the idea.

2024-11-20 21:33 UTC, kmichaelk commented
Compilers from CI:
gcc 13: https://godbolt.org/z/P6b4TYadz
MSVC 19: https://godbolt.org/z/G47KoTcqb
**clang 18: https://godbolt.org/z/EoKGrG88d**

I think if other modules only need OMP functions (`omp_*`), then using `-fopenmp` for resolving OMP pragmas in them is not needed

@aobolensk

2024-11-20 23:37 UTC, kmichaelk commented
![image](https://github.com/user-attachments/assets/760e8bec-546a-4a28-b615-3c93f1ff6c77)
https://github.com/learning-process/ppc-2024-autumn/actions/runs/11943503959/job/33292671899?pr=284

2024-11-20 23:40 UTC, kmichaelk commented
![image](https://github.com/user-attachments/assets/f3d2a232-3931-4971-b94e-0325b9cbc907)
https://github.com/learning-process/ppc-2024-autumn/actions/runs/11943503959/job/33292671899?pr=284

2024-11-21 15:58 UTC, kmichaelk commented
Gave up on clang tools terrible structured bindings support

![image](https://github.com/user-attachments/assets/85078fd7-a8b3-4ab0-8f95-6241c635bd51)

2024-12-29 20:01 UTC, closed without merging