Чистов Алексей.Задача 2.Вариант 9. Обобщенная передача от всех одному(gather).
learning-process/ppc-2024-autumn pull request #285
Opened 2024-11-15 11:19 UTC by Alexey2013

Реализована функция gather, основанная на структуре, аналогичной двоичному дереву. В этой реализации каждый процесс собирает данные от своих "детей" и передает их "родителю". В итоге корневой процесс (root) агрегирует все данные.

В качестве решаемой задачи выбрана задача сортировки, поскольку она предполагает обработку большого объема данных каждым процессом. В рамках решения каждый процесс сортирует свои данные локально. Затем корневой процесс объединяет отсортированные данные из всех процессов в один общий отсортированный массив.

2024-11-18 19:12 UTC, Ivan-Lysov commented on tasks/mpi/chistov_a_gather_boost/include/gather_boost.hpp
> +}
thid method is outdated.

2024-11-18 19:33 UTC, dima-dimka04 commented on tasks/mpi/chistov_a_gather_boost/src/gather_boost.cpp
> +  }
Did you really need this check? I don't think there will be any differences in one process. So, this block may be deleted.

2024-11-18 19:33 UTC, dima-dimka04 commented on tasks/mpi/chistov_a_gather_my/src/gather_my.cpp
> +  }
Same as previous

2024-11-19 11:53 UTC, Ivan-Lysov approved these changes

2024-11-19 12:10 UTC, dima-dimka04 approved these changes
Seems good now

2024-11-21 01:45 UTC, aobolensk requested changes

2024-11-21 01:45 UTC, aobolensk commented on tasks/mpi/chistov_a_gather_boost/func_tests/gather_boost.cpp
> +}
No need to test such functions, they are not a part of implementation

2024-11-21 01:45 UTC, aobolensk commented on tasks/mpi/chistov_a_gather_boost/func_tests/gather_boost.cpp
> +  if (world.size() == 1) return;
I guess, gather should not do anything if you run in 1 proc environment

2024-11-21 01:45 UTC, aobolensk commented on tasks/mpi/chistov_a_gather_boost/func_tests/gather_boost.cpp
> +
Please, add non-random tests as well

2024-11-21 01:45 UTC, aobolensk commented on tasks/mpi/chistov_a_gather_my/src/sort_my.cpp
> +  std::sort(input_data.begin(), input_data.end());
Why do you use std::sort in pre-processing when your task is basically to sort arrays?

2024-11-21 15:02 UTC, allnes commented on tasks/mpi/chistov_a_gather_my/src/sort_my.cpp
> +template class Sorting<int>;
please add char

2024-11-21 15:02 UTC, allnes commented on tasks/mpi/chistov_a_gather_my/func_tests/sort_my.cpp
> +  const int count_size_vector = 100;
please check prime numbers too

2024-11-21 15:03 UTC, allnes commented on tasks/mpi/chistov_a_gather_my/func_tests/sort_my.cpp
> +  const int count_size_vector = 100;
please check 2^n too

2024-11-21 15:04 UTC, allnes commented on tasks/mpi/chistov_a_gather_my/src/gather_my.cpp
> +template class Gather<int>;
same point, please add char too

2024-11-26 16:25 UTC, Alexey2013 commented on tasks/mpi/chistov_a_gather_my/src/sort_my.cpp
> +    merge_sorted_vectors(gathered_data, count, world.size());
The function of merging sorted vectors does not relate to parallel programming. In it I simply merge already sorted vectors. I thought in the function run() we write the part related to it.

2024-12-01 20:50 UTC, allnes approved these changes

2024-12-02 17:22 UTC, aobolensk approved these changes

2024-12-02 17:23 UTC, merged