Ермолаев Владислав. Задача 2. Вариант 7. Передача от всех одному и рассылка (allreduce)
learning-process/ppc-2024-autumn pull request #286
Opened 2024-11-15 12:16 UTC by ermolaevv

## allreduce
Реализован с использованием k-арного дерева с оптимальным* значением k = 3 . Родитель и потомки узла в дереве определяются итеративно. 
* оптимальным в рамках модели latency-bandwidth

## Тестовая задача: построчная нормализация матрицы
Дисклеймер: mpi часть написана именно так, чтобы использовался __allreduce__
### seq:
- `minmax_element' находит минимальный и максимальный элемент в строке
- каждый элемент нормализуется по методу минимакс   
### mpi: 
- матрица считывается в транспонированном виде
- колонки матрицы рассылаются по процессам
- процессы вычисляют минимумы и максимумы в каждой строке среди полученных колонок
- 2 allreduce собирают и рассылают минимумы и максимумы
- каждый процесс нормализует элементы среди полученных колонок
- gatherv собирает результаты нормализации
- при записи в taskData результаты транспонируются

2024-11-15 16:27 UTC, Kitos87 commented on tasks/mpi/ermolaev_v_allreduce/func_tests/main.cpp
> +}
Please add negative validation tests for seq and mpi as well

2024-11-16 09:59 UTC, ermolaevv commented on tasks/mpi/ermolaev_v_allreduce/func_tests/main.cpp
> +}
fixed

2024-11-18 18:43 UTC, Kitos87 commented on tasks/mpi/ermolaev_v_allreduce_my/include/ops_mpi.hpp
> +  for (_S i = 0; i < over; i++) size[world.size() - i - 1]++;
The current logic distributes the remaining rows **(over)** starting from the end of the vector **size**. This could potentially lead to the last processes (with a higher rank) getting more rows to process. This distribution can cause an imbalance in the load when the last processes are running longer than the rest, which slows down the execution of the program in general. That is, if the number of processes is large, distributing additional rows only between the last processes may cause the program to wait for their completion while the rest of the processes are idle. Are you sure that with such an implementation, efficiency will not be lost?

2024-11-18 18:52 UTC, ermolaevv commented on tasks/mpi/ermolaev_v_allreduce_my/include/ops_mpi.hpp
> +  for (_S i = 0; i < over; i++) size[world.size() - i - 1]++;
Я уверен, что такое распределение данных является эффективным, потому что это позволяет лишний раз не нагружать корневой (нулевой) процесс. К слову распределю я не строки, а колонки матрицы. При большем количестве процессов, чем колонок матрицы, любой алгоритм распределения колонок будет оставлять какое-то количество

2024-11-18 18:52 UTC, ermolaevv commented on tasks/mpi/ermolaev_v_allreduce_my/include/ops_mpi.hpp
> +  for (_S i = 0; i < over; i++) size[world.size() - i - 1]++;
I am sure that such data distribution is effective, because it allows you not to overload the root (null) process once again. By the way, I do not distribute rows, but columns of the matrix. With a larger number of processes than the columns of the matrix, any column allocation algorithm will leave some number of idle processes.

2024-11-19 01:23 UTC, aobolensk requested changes
Please, increase code coverage %

2024-11-19 06:24 UTC, Kitos87 commented on tasks/mpi/ermolaev_v_allreduce_my/include/ops_mpi.hpp
> +  for (_S i = 0; i < over; i++) size[world.size() - i - 1]++;
Yes, I agree, in this case it should work effectively

2024-11-19 06:25 UTC, Kitos87 approved these changes

2024-11-19 19:13 UTC, Yarik3008 commented on tasks/mpi/ermolaev_v_allreduce_my/include/ops_mpi.hpp
> +      std::function<void(const boost::mpi::communicator&, const _T*, int, _T*, boost::mpi::maximum<_T>)> max_func_)
These long types significantly impair the readability of the code. To address this issue, you can create an alias for the type.

2024-11-19 19:19 UTC, ermolaevv commented on tasks/mpi/ermolaev_v_allreduce_my/include/ops_mpi.hpp
> +      std::function<void(const boost::mpi::communicator&, const _T*, int, _T*, boost::mpi::maximum<_T>)> max_func_)
fixed

2024-11-19 19:38 UTC, Yarik3008 approved these changes

2024-11-21 17:02 UTC, ermolaevv commented
> Please, increase code coverage %

@aobolensk, it looks like this is a bug in the pull request message, because everything is fine in the artifact

![image](https://github.com/user-attachments/assets/2782a34a-a472-465e-b2b9-e62adfdcbc10)

2024-11-25 19:06 UTC, allnes commented on tasks/mpi/ermolaev_v_allreduce_my/include/ops_mpi.hpp
> +      input_[i][j] = ptr[i][j];
please use linear form of matrix

2024-11-25 19:14 UTC, ermolaevv commented on tasks/mpi/ermolaev_v_allreduce_my/include/ops_mpi.hpp
> +      input_[i][j] = ptr[i][j];
I hope you mean using a linear matrix in tests and TaskData?

2024-11-26 16:42 UTC, ermolaevv commented on tasks/mpi/ermolaev_v_allreduce_my/include/ops_mpi.hpp
> +      input_[i][j] = ptr[i][j];
fixed

2024-12-01 20:52 UTC, merged

2024-12-08 17:59 UTC, allnes commented on tasks/mpi/ermolaev_v_allreduce_my/include/test_funcs.hpp
> +  if (world.rank() == 0) std::cout << "Run test with " << rows << "x" << cols << " matrix\n";
please remove logging in ci in separate PR

2024-12-08 21:04 UTC, ermolaevv commented on tasks/mpi/ermolaev_v_allreduce_my/include/test_funcs.hpp
> +  if (world.rank() == 0) std::cout << "Run test with " << rows << "x" << cols << " matrix\n";
please merge it #489