Шведова Виталина. Задача 2. Вариант 18. Умножение матриц - ленточная горизонтальная схема A, вертикальное B.
learning-process/ppc-2024-autumn pull request #294
Opened 2024-11-16 20:34 UTC by shvedovav

## Последовательная версия алгоритма

В последовательной версии реализован наивный метод матричного умножения, не требующий отдельного описания. Единственное, что заслуживает внимания - были внесены некоторые отличия в последовательный алгоритм, находящийся в папке mpi - он стал использовать мой класс для матрицы, как и его параллельная версия. Сделано это для удобства тестирования параллельной версии.

## Параллельная версия алгоритма

Для удобства работы используется специальный класс Matrix.

### 1. **Инициализация данных и распределение работы**

- На **нулевом процессе** (root):

  - Получаем входные данные (матрицы \( A \) и \( B \)), их размеры, а также вычисляем количество строк и столбцов для каждой матрицы.
  - Строим вспомогательные структуры данных:
    - Массивы индексов для строк матрицы \( A \) и столбцов матрицы \( B \).
    - Разбиение на части для распределения данных между процессами.
  - Производим разбиение работы на процессы: каждый процесс будет вычислять часть строки результирующей матрицы.

- После инициализации данные (матрицы, индексы) отправляются всем процессам с помощью операции `broadcast`.

### 2. **Распределение работы между процессами**

- Каждый процесс получает свою долю работы. Для этого используется операция `scatterv`, которая распределяет индексы строк и столбцов между процессами.
- Каждый процесс будет работать только с частью матрицы \( A \) и части столбцов матрицы \( B \).

### 3. **Вычисление локальных частей результата**

- Каждый процесс вычисляет часть результирующей матрицы \( C \) на основе локальных данных:
  - Локальная строка матрицы \( A \) и локальные столбцы матрицы \( B \).
  - Для каждой пары индексов строки \( i \) матрицы \( A \) и столбца \( j \) матрицы \( B \) выполняется вычисление скалярного произведения.
  - Полученные локальные результаты сохраняются в локальные векторы.

### 4. **Сбор данных**

- После того как каждый процесс завершит вычисления, локальные результаты нужно собрать на root процессе. Это осуществляется с помощью операции `gatherv`.
- Результаты собираются в итоговый вектор на root процессе, который затем копируется в выходной массив.

### 5. **Запись результатов**

- После завершения вычислений на root процессе (rank 0) данные результирующей матрицы \( C \) копируются в выходной массив.

2024-11-17 08:43 UTC, venn2713 commented on tasks/mpi/shvedova_v_matrix_mult_horizontal_a_vertical_b_mpi/func_tests/main.cpp
> +void matrix_multiply_square_result(const std::vector<int>& a, const std::vector<int>& b, std::vector<int>& result,
It seems you forgot to delete the service function, at least it is not used anywhere

2024-11-17 08:43 UTC, venn2713 commented on tasks/mpi/shvedova_v_matrix_mult_horizontal_a_vertical_b_mpi/func_tests/main.cpp
> +
I think you should add tests that check the functionality of a matrix with a size of 1

2024-11-17 08:47 UTC, korablev-vm requested changes

2024-11-17 08:47 UTC, korablev-vm commented on tasks/mpi/shvedova_v_matrix_mult_horizontal_a_vertical_b_mpi/perf_tests/main.cpp
> +    shvedova_v_matrix_mult_horizontal_a_vertical_b_mpi::matrix_multiply_square_result(global_matrix_a, global_matrix_b,
Here, it is better to use a sequential version instead of an additional function in the same way as with functional tests.

2024-11-17 08:47 UTC, korablev-vm commented on tasks/mpi/shvedova_v_matrix_mult_horizontal_a_vertical_b_mpi/src/ops_mpi.cpp
> +}
A good approach is to limit the amount of input data so as not to additionally check the dimension of the matrices. But it's still worth supplementing validation with zero-size checks.

2024-11-17 14:40 UTC, shvedovav commented on tasks/mpi/shvedova_v_matrix_mult_horizontal_a_vertical_b_mpi/func_tests/main.cpp
> +void matrix_multiply_square_result(const std::vector<int>& a, const std::vector<int>& b, std::vector<int>& result,
fixed

2024-11-17 14:40 UTC, shvedovav commented on tasks/mpi/shvedova_v_matrix_mult_horizontal_a_vertical_b_mpi/func_tests/main.cpp
> +
fixed

2024-11-17 14:40 UTC, shvedovav commented on tasks/mpi/shvedova_v_matrix_mult_horizontal_a_vertical_b_mpi/perf_tests/main.cpp
> +    shvedova_v_matrix_mult_horizontal_a_vertical_b_mpi::matrix_multiply_square_result(global_matrix_a, global_matrix_b,
fixed

2024-11-17 14:40 UTC, shvedovav commented on tasks/mpi/shvedova_v_matrix_mult_horizontal_a_vertical_b_mpi/src/ops_mpi.cpp
> +}
fixed

2024-11-17 14:41 UTC, venn2713 approved these changes

2024-11-17 14:42 UTC, korablev-vm approved these changes

2024-11-19 01:28 UTC, aobolensk requested changes

2024-11-19 01:28 UTC, aobolensk commented on tasks/mpi/shvedova_v_matrix_mult_horizontal_a_vertical_b_mpi/func_tests/main.cpp
> +  std::uniform_int_distribution<> dist(0, 1000);
Consider testing matrices with negative numbers as well

2024-11-21 02:15 UTC, aobolensk approved these changes

2024-11-21 15:07 UTC, allnes commented on tasks/mpi/shvedova_v_matrix_mult_horizontal_a_vertical_b_mpi/func_tests/main.cpp
> +  std::uniform_int_distribution<> dist(-100, 1000);
Please use unbiased range

2024-11-21 15:08 UTC, allnes commented on tasks/mpi/shvedova_v_matrix_mult_horizontal_a_vertical_b_mpi/func_tests/main.cpp
> +TEST(shvedova_v_matrix_mult_horizontal_a_vertical_b_mpi, rec_4x3_3x5) { RunMatrixMultiplicationTest(4, 3, 5); }
please check next cases:
(1, 1, 1)
(7, 11, 13)
(4, 8, 16)

2024-11-25 19:08 UTC, allnes approved these changes

2024-11-25 19:08 UTC, merged