Миронов Арсений. Задача 2. Вариант 5. Передача от одного всем (broadcast).
learning-process/ppc-2024-autumn pull request #298
Opened 2024-11-17 17:33 UTC by Napkin-AI

Основная задача: реализовать ***broadcast***.

Подзадача, решаемая при помощи ***broadcast***:
Даны два массива чисел: ```array```, ```powers``` с размерами ```N```, ```K```.
Далее создаётся ```K``` массивов, ```it``` элемент которого равен ```array[it] ^ powers[it]```
Необходимо найти покомпонентную сумму K массивов. 
Пример:
```array = {1, 3, 5}```
```powers = {1, 2}```

Тогда создаются массивы:
{1, 3, 5} и {1, 9, 25}
А их покомпонентная сумма и будет ответом:
{2, 12, 30}

В задаче используется broadcast для передачи массива ```array``` каждому процессу, а ```powers``` равномерно распределяются по процессам.
Таким образом каждый процесс будет создавать свои массивы и складывает их.

Для объеденения используется ```reduce```

2024-11-19 01:34 UTC, aobolensk requested changes

2024-11-19 01:34 UTC, aobolensk commented on tasks/mpi/mironov_a_broadcast/func_tests/main.cpp
> +TEST(mironov_a_broadcast_mpi, Test_broadcast_1) {
Consider check of transferring random data as well

2024-11-19 01:34 UTC, aobolensk commented on tasks/mpi/mironov_a_broadcast/include/ops_mpi.hpp
> +class ComponentSumPowerBoostImpl : public ppc::core::Task {
It seems, splitting reference implementation and your implementation into different files would be better

2024-11-19 01:34 UTC, aobolensk commented on tasks/mpi/mironov_a_broadcast/src/ops_mpi.cpp
> +  }
Is that needed? Shouldn't this case be covered in the generic solution?

2024-11-19 13:50 UTC, Konstantin-Grudzin requested changes

2024-11-19 13:50 UTC, Konstantin-Grudzin commented on tasks/mpi/mironov_a_broadcast/func_tests/main.cpp
> +
Add tests,that check validation

2024-11-19 13:50 UTC, Konstantin-Grudzin commented on tasks/mpi/mironov_a_broadcast/src/ops_mpi.cpp
> +    if (size2 % world.size()) {
It would be better if you use operators and don't casts for bool

2024-11-19 13:50 UTC, Konstantin-Grudzin commented on tasks/mpi/mironov_a_broadcast/src/ops_mpi.cpp
> +  if (world.rank()) {
Maybe you forgot equals 0?

2024-11-19 13:50 UTC, Konstantin-Grudzin commented on tasks/mpi/mironov_a_broadcast/src/ops_mpi.cpp
> +      res += power < 0 ? 0 : pow(number, power);
Ternery operators it's hard to read, please, change it to if operator

2024-11-19 13:50 UTC, Konstantin-Grudzin commented on tasks/mpi/mironov_a_broadcast/src/ops_mpi.cpp
> +    if (size2 % world.size()) {
Dont' use casts to bool

2024-11-19 13:53 UTC, Napkin-AI commented on tasks/mpi/mironov_a_broadcast/src/ops_mpi.cpp
> +  }
I think it is possible to implement, but it seems to me that my version is better, since in any case these conditions should be, and my code increases the readability of the code and productivity.

2024-11-19 13:58 UTC, Napkin-AI commented on tasks/mpi/mironov_a_broadcast/include/ops_mpi.hpp
> +class ComponentSumPowerBoostImpl : public ppc::core::Task {
Should I use move boost version to folder "seq" or create the second ```main.cpp``` file in folder with perf tests in mpi version?

2024-11-23 15:01 UTC, Napkin-AI commented on tasks/mpi/mironov_a_broadcast/src/ops_mpi.cpp
> +    if (size2 % world.size()) {
fixed

2024-11-23 15:01 UTC, Napkin-AI commented on tasks/mpi/mironov_a_broadcast/src/ops_mpi.cpp
> +      res += power < 0 ? 0 : pow(number, power);
fixed

2024-11-23 15:01 UTC, Napkin-AI commented on tasks/mpi/mironov_a_broadcast/src/ops_mpi.cpp
> +  if (world.rank()) {
fixed

2024-11-23 15:01 UTC, Napkin-AI commented on tasks/mpi/mironov_a_broadcast/src/ops_mpi.cpp
> +    if (size2 % world.size()) {
fixed

2024-11-23 15:01 UTC, Napkin-AI commented on tasks/mpi/mironov_a_broadcast/func_tests/main.cpp
> +
fixed

2024-11-23 18:40 UTC, Napkin-AI commented on tasks/mpi/mironov_a_broadcast/func_tests/main.cpp
> +TEST(mironov_a_broadcast_mpi, Test_broadcast_1) {
Added tests with random vector.

2024-11-23 18:43 UTC, Konstantin-Grudzin commented on tasks/mpi/mironov_a_broadcast/func_tests/main.cpp
> +
Okay,but it better to check every validation condition seperatly,but i don't think this is a neccesary

2024-11-25 19:10 UTC, allnes commented on tasks/mpi/mironov_a_broadcast/func_tests/main.cpp
> +    vec[i] = gen() % mod;
please use negative values too

2024-11-25 19:14 UTC, allnes commented on tasks/mpi/mironov_a_broadcast_custom/src/ops_mpi.cpp
> +  broadcastImpl(world, delta_, 0);
please check different communicators, not only world

2024-11-26 11:13 UTC, Napkin-AI commented on tasks/mpi/mironov_a_broadcast_custom/src/ops_mpi.cpp
> +  broadcastImpl(world, delta_, 0);
Do you mean testing another communicator, not just root?
Do I need to create a communicator in functional tests or can I split ```world``` into, for example, even and odd communicators?

2024-11-26 12:17 UTC, NikitaKoshkin requested changes

2024-11-26 18:49 UTC, Napkin-AI commented on tasks/mpi/mironov_a_broadcast/src/ops_mpi.cpp
> +    if (size2 % world.size()) {
в

2024-11-26 18:50 UTC, Napkin-AI commented on tasks/mpi/mironov_a_broadcast/func_tests/main.cpp
> +
в

2024-11-27 10:34 UTC, Napkin-AI commented on tasks/mpi/mironov_a_broadcast_custom/src/ops_mpi.cpp
> +  broadcastImpl(world, delta_, 0);
I decided to add new functional tests that directly test the ```broadcastImpl``` with different parameters.
I would not want to change the signature of the ```run()``` function and the ```ComponentSumPowerCustomImpl``` class to use a custom communicator, as this would make the code harder to read and could introduce problems beyond the implementation of the ```broadcast```.

2024-11-29 14:11 UTC, NikitaKoshkin approved these changes

2024-12-01 20:54 UTC, allnes approved these changes

2024-12-02 18:19 UTC, Napkin-AI commented on tasks/mpi/mironov_a_broadcast/include/ops_mpi.hpp
> +class ComponentSumPowerBoostImpl : public ppc::core::Task {
Implemented in different files. I apologize for being insistent, but could you check the work?

2024-12-03 03:15 UTC, aobolensk approved these changes

2024-12-03 03:15 UTC, merged