Грудзин Константин. Задача 2. Вариант 7. Реализация allreduce
learning-process/ppc-2024-autumn pull request #299
Opened 2024-11-17 20:03 UTC by Konstantin-Grudzin

## Задача: нахождения количества элементов столбца, равных минимуму данного столбца.
### Решение:
**Последовательная версия:**
Проходимся по столбцам, находим минимум, считаем ответ
**MPI версия:**
Разобьём данную задачу на две подзадачи. Для решения первой части, разделим матрицу между всеми потоками, они же посчитают минимум для каждого столбца, что встретят. После этого, все результаты сравниваются с помощь allreduce и возвращаются всем потокам. Потоки опять идут по своим локальным данным и считают кол-во элементов столбца, равных минимальному, после сливая ответ
### Реализация allreduce
Каждый процесс начинает с того, что инициализирует результат своими значениями, после этого, пытается получить данные от своих детей, если они есть. Когда он их получил и посчитал, он отправляет их своему родителю. Потом опять забирает итоговые данные от своего родителя и отправляет детям.
Основное ускорение достигается за счёт некоторой асинхронности: каждый поток может выполнить какую-то часть работы, не дожидаясь родителя или потомка.

2024-11-19 01:36 UTC, aobolensk requested changes

2024-11-19 01:36 UTC, aobolensk commented on tasks/seq/dormidontov_e_min_value_by_columns_seq/src/ops_seq.cpp
> +}
Please, do not touch files of others

2024-11-19 01:36 UTC, aobolensk commented on tasks/mpi/grudzin_k_all_reduce/src/ops_mpi.cpp
> +    cv2 = new int[n];
Memory leak

2024-11-19 13:36 UTC, Konstantin-Grudzin commented on tasks/seq/dormidontov_e_min_value_by_columns_seq/src/ops_seq.cpp
> +}
So, i don't really sure how can i fix this. Should i just create new branch?

2024-11-19 13:43 UTC, Konstantin-Grudzin commented on tasks/seq/dormidontov_e_min_value_by_columns_seq/src/ops_seq.cpp
> +}
Cause this code are totally equal to original (i can call a athour, to check it,if it needed)

2024-11-19 14:20 UTC, Napkin-AI requested changes

2024-11-19 14:20 UTC, Napkin-AI commented on tasks/mpi/grudzin_k_all_reduce/src/ops_mpi.cpp
> +  return ((taskData->inputs_count.size() >= 2 && taskData->inputs_count[0] != 0 && taskData->inputs_count[1] != 0) &&
Outputs_count can be empty. You should check it before u get the first element.

2024-11-19 14:20 UTC, Napkin-AI commented on tasks/mpi/grudzin_k_all_reduce/src/ops_mpi.cpp
> +    return (((taskData->inputs_count.size() >= 2 && taskData->inputs_count[0] != 0 && taskData->inputs_count[1] != 0) &&
Outputs_count can be empty. You should check it before u get the first element.

2024-11-19 14:20 UTC, Napkin-AI commented on tasks/mpi/grudzin_k_all_reduce/include/ops_mpi.hpp
> +  std::vector<int> res_{};
Where do u use ```ans```?  If you actually use it, rename variables the same as in mpi versions.

2024-11-19 14:20 UTC, Napkin-AI commented on tasks/mpi/grudzin_k_all_reduce/src/ops_mpi.cpp
> +    return (((taskData->inputs_count.size() >= 2 && taskData->inputs_count[0] != 0 && taskData->inputs_count[1] != 0) &&
Outputs_count can be empty. You should check it before u get the first element.

2024-11-19 14:20 UTC, Napkin-AI commented on tasks/mpi/grudzin_k_all_reduce/perf_tests/main.cpp
> +// I use it in local nachine to analize speed,idk shoud  delete it or not so i keep it
As only you need this comment, just remove it from your pull request and save it in local repo

2024-11-23 18:48 UTC, Konstantin-Grudzin commented on tasks/mpi/grudzin_k_all_reduce/src/ops_mpi.cpp
> +    cv2 = new int[n];
fixed

2024-11-23 18:54 UTC, Konstantin-Grudzin commented on tasks/mpi/grudzin_k_all_reduce/src/ops_mpi.cpp
> +    return (((taskData->inputs_count.size() >= 2 && taskData->inputs_count[0] != 0 && taskData->inputs_count[1] != 0) &&
I dont fully agree with you, because my validation checks that output count equals input counts on index 1. So, if it's equal zero, it fails last check.

2024-11-23 19:30 UTC, Napkin-AI approved these changes

2024-11-25 19:17 UTC, allnes commented on tasks/mpi/grudzin_k_all_reduce_boost/func_tests/main.cpp
> +TEST(grudzin_k_all_reduce_boost_mpi, Test_Seq_and_My_Ver_20x30) {
could you check matrix (17x23)

2024-11-25 19:17 UTC, allnes commented on tasks/mpi/grudzin_k_all_reduce_boost/func_tests/main.cpp
> +TEST(grudzin_k_all_reduce_boost_mpi, Test_Seq_and_My_Ver_20x30) {
and 16x32

2024-11-25 19:20 UTC, allnes commented on tasks/mpi/grudzin_k_all_reduce_student/src/ops_mpi.cpp
> +  int delta = size / world.size();
please boradcast delta instead rows and cols

2024-11-27 09:25 UTC, EgorDormidontov requested changes

2024-11-27 09:25 UTC, EgorDormidontov commented on tasks/mpi/grudzin_k_all_reduce_student/src/ops_mpi.cpp
> +    world.send(root >> 1, 0, out_values, n);
Put the result in a variable.Better that way,because u use result twice there.

2024-11-29 07:14 UTC, EgorDormidontov approved these changes

2024-11-29 07:17 UTC, Konstantin-Grudzin commented on tasks/mpi/grudzin_k_all_reduce_student/src/ops_mpi.cpp
> +  int delta = size / world.size();
fixed, but i still need to broadcast colums for my realization

2024-11-29 07:18 UTC, Konstantin-Grudzin commented on tasks/mpi/grudzin_k_all_reduce_boost/func_tests/main.cpp
> +TEST(grudzin_k_all_reduce_boost_mpi, Test_Seq_and_My_Ver_20x30) {
Test added, program works properly

2024-12-01 20:56 UTC, allnes commented on tasks/seq/dormidontov_e_min_value_by_columns_seq/src/ops_seq.cpp
> +}
please add additional empty string in the end of file

2024-12-01 20:57 UTC, allnes approved these changes

2024-12-02 17:50 UTC, aobolensk approved these changes

2024-12-02 17:51 UTC, merged