Дрождинов Дмитрий. Задача 1. Вариант 12. Сумма значений по столбцам матрицы.
learning-process/ppc-2024-autumn pull request #30
Opened 2024-10-21 14:14 UTC by dima-dimka04

**Последовательная задача:** во вложенном цикле проходим по каждому столбцу, суммируем значения элементов, результат записываем в вектор. 

**Параллельная задача:** разделяем матрицу в зависимости от количества столбцов и процессов, рассчитываем delta - количество столбцов, которое получит каждый процесс, а также номер последнего обрабатываемого столбца для каждого процесса. Разделенные столбцы суммируются при помощи функции, используемой в последовательной задаче, результаты собираются функцией gatherv в общий вектор.

2024-10-25 09:16 UTC, Alexey2013 commented on tasks/mpi/drozhdinov_d_sum_cols_matrix/include/ops_mpi.hpp
> +  std::vector<int> input_, local_input_;
```suggestion
  std::vector<int> input_;
``` Please remove unused variables

2024-10-25 09:17 UTC, Alexey2013 commented on tasks/mpi/drozhdinov_d_sum_cols_matrix/include/ops_mpi.hpp
> +  std::vector<int> input_, local_input_;
Please remove unused variables

2024-10-25 09:21 UTC, Alexey2013 commented on tasks/seq/drozhdinov_d_sum_cols_matrix/include/ops_seq.hpp
> +std::vector<int> calculateMatrixSumSequentially(const std::vector<int>& matrix, int xSize, int ySize);
Name the overloaded functions the same

2024-10-25 16:49 UTC, Alexey2013 approved these changes

2024-10-25 17:26 UTC, dima-dimka04 commented on tasks/mpi/drozhdinov_d_sum_cols_matrix/include/ops_mpi.hpp
> +  std::vector<int> input_, local_input_;
done

2024-10-25 17:27 UTC, dima-dimka04 commented on tasks/seq/drozhdinov_d_sum_cols_matrix/include/ops_seq.hpp
> +std::vector<int> calculateMatrixSumSequentially(const std::vector<int>& matrix, int xSize, int ySize);
override function was removed

2024-10-25 17:29 UTC, dima-dimka04 commented on tasks/mpi/drozhdinov_d_sum_cols_matrix/src/ops_mpi.cpp
> +}
done

2024-10-25 21:04 UTC, ascannel commented on tasks/mpi/drozhdinov_d_sum_cols_matrix/src/ops_mpi.cpp
> +}
the `randomVector` function does not generate negative values, and therefore there are no tests for this either

2024-10-26 00:33 UTC, aobolensk requested changes

2024-10-26 00:33 UTC, aobolensk commented on tasks/mpi/example/perf_tests/main.cpp
> +
Please revert

2024-10-26 00:33 UTC, aobolensk commented on tasks/seq/example/src/ops_seq.cpp
> +  std::this_thread::sleep_for(10ms);
Remove sleep

2024-10-26 10:08 UTC, dima-dimka04 commented on tasks/mpi/drozhdinov_d_sum_cols_matrix/src/ops_mpi.cpp
> +}
done
negative values generating in `RandomMatrixTest` too

2024-10-26 10:14 UTC, dima-dimka04 commented on tasks/seq/example/src/ops_seq.cpp
> +  std::this_thread::sleep_for(10ms);
done
the code in the files of the example folder has been restored to its original state

2024-10-26 11:35 UTC, ascannel approved these changes

2024-10-27 09:16 UTC, allnes commented on tasks/mpi/example/func_tests/main.cpp
> +
please don't change not own files

2024-10-27 09:17 UTC, allnes commented on tasks/mpi/example/perf_tests/main.cpp
> +
same, you can't change files not depended on your task

2024-10-27 09:18 UTC, allnes commented on tasks/seq/example/perf_tests/main.cpp
> +
same point about files changes

2024-10-27 09:41 UTC, allnes commented on tasks/seq/example/func_tests/main.cpp
> +}
same point about changes

2024-10-27 09:54 UTC, allnes approved these changes

2024-10-27 09:58 UTC, dima-dimka04 commented on tasks/seq/example/func_tests/main.cpp
> +}
since last commit example files are in correct state

2024-10-27 14:18 UTC, aobolensk approved these changes

2024-10-27 14:21 UTC, merged