Вавилов Виталий. Задача 2. Вариант 27. Повышение контраста.
learning-process/ppc-2024-autumn pull request #300
Opened 2024-11-17 21:17 UTC by Vav1L0N

Задача повышения контраста изображения. 
Код реализует алгоритм линейного повышения контраста изображения. Исходное изображение представлено в виде одномерного массива значений интенсивности пикселей.

Seq реализация:

Выбор минимального и максимального значений интенсивности (p_min и p_max) в массиве. Нормализация значений по формуле: 
```math
\text{output}[i] = \left\lfloor \frac{(\text{input}[i] - p_{\text{min}}) \times 255}{p_{\text{max}} - p_{\text{min}}} \right\rfloor
```
Если все значения равны, нормализация устанавливает весь выходной массив в 0.

MPI реализация:

Мастер-процесс (rank 0) делит данные на фрагменты и распределяет их между процессами с помощью scatterv.
Локальные минимальные и максимальные значения рассчитываются на каждом процессе.
Глобальные p_min и p_max вычисляются с помощью all_reduce.
Нормализация выполняется локально на каждом процессе.
Результаты собираются обратно на мастер-процессе с использованием gatherv.

2024-11-19 01:38 UTC, aobolensk requested changes

2024-11-19 01:38 UTC, aobolensk commented on tasks/mpi/vavilov_v_contrast_enhancement/src/ops_mpi.cpp
> +    input_[i] = data[i];
Use std::copy

2024-11-19 01:40 UTC, aobolensk requested changes

2024-11-19 01:40 UTC, aobolensk commented on tasks/mpi/vavilov_v_contrast_enhancement/func_tests/main.cpp
> +    std::vector<int> input = {10, 20, 30, 40, 50};
Should input array be integer? It seems values are 0..255

2024-11-19 01:40 UTC, aobolensk commented on tasks/mpi/vavilov_v_contrast_enhancement/func_tests/main.cpp
> +TEST(vavilov_v_contrast_enhancement_mpi, ValidInput) {
Please, consider adding random tests as well

2024-11-22 18:05 UTC, Vav1L0N commented on tasks/mpi/vavilov_v_contrast_enhancement/src/ops_mpi.cpp
> +    input_[i] = data[i];
fixed

2024-11-22 18:08 UTC, Vav1L0N commented on tasks/mpi/vavilov_v_contrast_enhancement/func_tests/main.cpp
> +    std::vector<int> input = {10, 20, 30, 40, 50};
Yeah, in this case, using the int type for the input array may be suboptimal. it is better to use uint8_t

2024-11-22 18:08 UTC, Vav1L0N commented on tasks/mpi/vavilov_v_contrast_enhancement/func_tests/main.cpp
> +TEST(vavilov_v_contrast_enhancement_mpi, ValidInput) {
Added

2024-11-22 19:10 UTC, IljarSmirnov reviewed
The rest looks good

2024-11-22 19:10 UTC, IljarSmirnov commented on tasks/seq/vavilov_v_contrast_enhancement/include/ops_seq.hpp
> +#include <string>
unnecessary include

2024-11-22 19:10 UTC, IljarSmirnov commented on tasks/mpi/vavilov_v_contrast_enhancement/func_tests/main.cpp
> +TEST(vavilov_v_contrast_enhancement_mpi, CorrectOutputSize) {
Add test when p_min==p_max

2024-11-22 19:57 UTC, Vav1L0N commented on tasks/seq/vavilov_v_contrast_enhancement/include/ops_seq.hpp
> +#include <string>
fixed

2024-11-22 19:57 UTC, Vav1L0N commented on tasks/mpi/vavilov_v_contrast_enhancement/func_tests/main.cpp
> +TEST(vavilov_v_contrast_enhancement_mpi, CorrectOutputSize) {
Added

2024-11-23 09:28 UTC, VladislavPoroshin requested changes
ok i think it's good

2024-11-23 09:28 UTC, VladislavPoroshin approved these changes

2024-11-24 10:17 UTC, IljarSmirnov approved these changes

2024-11-25 19:26 UTC, allnes commented on tasks/mpi/vavilov_v_contrast_enhancement/func_tests/main.cpp
> +  const size_t size = 1000;
please check algorithm for different height and width too

2024-11-25 21:00 UTC, Vav1L0N commented on tasks/mpi/vavilov_v_contrast_enhancement/func_tests/main.cpp
> +  const size_t size = 1000;
Added tests with different height and width

2024-12-01 20:58 UTC, allnes approved these changes

2024-12-02 17:57 UTC, aobolensk approved these changes

2024-12-02 19:09 UTC, PutinVVV approved these changes

2024-12-02 19:51 UTC, SergeyBoRss commented on tasks/mpi/vavilov_v_contrast_enhancement/func_tests/main.cpp
Add a test with an empty input

2024-12-02 20:55 UTC, Vav1L0N commented on tasks/mpi/vavilov_v_contrast_enhancement/func_tests/main.cpp
added

2024-12-02 22:23 UTC, merged