Васильев Сергей Задача 3 вариант 28 Линейная фильтрация изображений (блочное разбиение). Ядро Гаусса 3x3.
learning-process/ppc-2024-autumn pull request #307
Opened 2024-11-18 19:01 UTC by venn2713

Реализация распределенного алгоритма для линейной фильтрации изображений с использованием ядра Гаусса 3x3. Для повышения производительности применяется блочное разбиение изображения и параллельная обработка с использованием MPI.

---

**Основные особенности реализации**

1. **Блочная обработка изображения**
   - Входное изображение разделяется на блоки, соответствующие рангам процессов в MPI.
   - Каждый процесс получает локальные данные для обработки, соответствующие выделенному блоку.

2. **Алгоритм распределения данных**
   - Реализованы механизмы распределения строк и столбцов изображения между процессами.
   - Используются функции `boost::mpi::scatterv` и `boost::mpi::gatherv` для передачи данных между процессами.

3. **Применение ядра Гаусса 3x3**
   - Для каждого элемента матрицы (пикселя) вычисляется свертка с использованием 3x3 ядра Гаусса.
   - Результаты свертки собираются в результирующую матрицу, исключая края изображения, где невозможно применить фильтр.

---

#### **Реализация ключевых функций**

1. **`pre_processing`**
   - Выполняет подготовку данных для распределения:
     - Извлекает параметры матрицы (строки, столбцы).
     - Разделяет матрицу на блоки с учетом количества процессов.
     - Генерирует индексы для обработки, размеры и смещения данных для каждого процесса.
   - Создаются векторы для хранения промежуточных результатов, которые передаются рабочим процессам.

2. **`run`**
   - Основной этап выполнения:
     - Распределяет данные между процессами (строки матрицы и соответствующие индексы).
     - Выполняет локальную обработку блока данных на каждом процессе:
       - Применяет ядро Гаусса 3x3 к пикселям, используя локальные данные.
       - Учитывает смещения для корректного вычисления координат.
     - Собирает локальные результаты обратно в главном процессе.

3. **Использование MPI**
   - Передача данных между процессами реализована с помощью:
     - `scatterv` для распределения исходной матрицы и индексов.
     - `gatherv` для сбора обработанных данных.
   - Учитываются размеры и смещения данных, чтобы минимизировать накладные расходы.

2024-11-18 20:27 UTC, kmichaelk commented on tasks/mpi/vasilev_s_gaus3x3/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, indices_sizes, 0);
Looks like independent calculation of those vectors by each process would be more performant (also if combined with buffer memory pre-allocation), but this statement requires experimental verification

2024-11-21 08:07 UTC, korablev-vm requested changes

2024-11-21 08:07 UTC, korablev-vm commented on tasks/seq/vasilev_s_gaus3x3/src/ops_seq.cpp
> +  std::cout << std::endl;
What is this line for?

2024-11-21 08:07 UTC, korablev-vm commented on tasks/mpi/vasilev_s_gaus3x3/src/ops_mpi.cpp
> +    // std::cout << std::endl;
You forgot to delete the debugging code

2024-11-21 08:07 UTC, korablev-vm commented on tasks/mpi/vasilev_s_gaus3x3/src/ops_mpi.cpp
> +    // std::cout << std::endl;
same

2024-11-21 08:07 UTC, korablev-vm commented on tasks/mpi/vasilev_s_gaus3x3/src/ops_mpi.cpp
> +    // std::cout << std::endl;
same

2024-11-24 14:49 UTC, venn2713 commented on tasks/mpi/vasilev_s_gaus3x3/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, indices_sizes, 0);
I agree, maybe it is, but I sacrificed possible productivity for my convenience, I confess

2024-11-24 18:05 UTC, korablev-vm approved these changes

2024-11-25 19:38 UTC, allnes commented on tasks/mpi/vasilev_s_gaus3x3/func_tests/main.cpp
> +  std::uniform_real_distribution<double> dist(0.0, 1000.0);
pixel has interval from 0 to 255, where you find interval from 256 to 1000

2024-12-03 20:05 UTC, venn2713 commented on tasks/mpi/vasilev_s_gaus3x3/func_tests/main.cpp
> +  std::uniform_real_distribution<double> dist(0.0, 1000.0);
I apologize, I copied the methods from an old work and did not pay attention at all, I thought too much about the work of the algorithms. Everything is fixed!

2024-12-03 20:05 UTC, venn2713 commented on tasks/mpi/vasilev_s_gaus3x3/func_tests/main.cpp
> +  std::uniform_real_distribution<double> dist(0.0, 1000.0);
Also fixed

2024-12-05 23:26 UTC, allnes approved these changes

2024-12-07 16:36 UTC, aobolensk approved these changes

2024-12-07 16:36 UTC, merged