Морозов Егор. Задача 2. Вариант 2. Задача «Читатели-Писатели»
learning-process/ppc-2024-autumn pull request #308
Opened 2024-11-18 20:07 UTC by Egor1dzeN-learn

**Задача "Читатели и писатели"** — это классическая проблема синхронизации в многопоточном программировании. Она моделирует ситуацию, когда несколько потоков (читателей и писателей) обращаются к общему ресурсу.
В данном случае писатели уменьшают на 1 значение, а читатели увеличивают на 1.
* 0 процесс - буфер, в котором хранятся данные для чтения, записи (переменная типа int)
* Остальные процессы делятся пополам (половина - читатели, половина - писатели)

Если кол-во процессов - нечетное, например - 9, то (1 процесс - буфер, 4 процесса - писатели, 4 процесса - читатели), если четное, например - 8, то (1 процесс - буфер, 3 процесса - писатели, 3 процесса - читатели, 1 процесс - просто стоит, чтобы обеспечить удобное создание тестов (проверка на равенство нулю переменной буфера))

2024-11-22 11:53 UTC, Egor1dzeN-learn commented on tasks/mpi/morozov_e_writers_readers/src/ops_mpi.cpp
> +      } else {
fixed

2024-11-24 01:39 UTC, aobolensk requested changes

2024-11-24 01:39 UTC, aobolensk commented on tasks/mpi/morozov_e_writers_readers/src/ops_mpi.cpp
> +        }
Please, customize workload. +1/-1 is only the example of usage of the buffer

2024-11-24 01:39 UTC, aobolensk commented on tasks/mpi/morozov_e_writers_readers/func_tests/main.cpp
> +
Is it working when world.size() == 1?

2024-11-24 14:57 UTC, Egor1dzeN-learn commented on tasks/mpi/morozov_e_writers_readers/func_tests/main.cpp
> +
Yes, of course
![image](https://github.com/user-attachments/assets/c2a8ca2b-d374-485a-a9b0-d1ec618c8e51)

2024-11-24 15:00 UTC, Egor1dzeN-learn commented on tasks/mpi/morozov_e_writers_readers/src/ops_mpi.cpp
> +        }
I don't quite understand how I can do this, so that all the tests can be written clearly? For the reader and the writer to create methods that somehow change the value of the buffer?

2024-11-24 15:02 UTC, Egor1dzeN-learn commented on tasks/mpi/morozov_e_writers_readers/src/ops_mpi.cpp
> +        }
Just create methods, one of which changes the value according to the formula, and the other just takes the opposite value?

2024-11-25 19:40 UTC, allnes commented on tasks/mpi/morozov_e_writers_readers/src/ops_mpi.cpp
> +    std::this_thread::sleep_for(200ms);
please parametrize this value and check with defferent values too

2024-12-01 21:04 UTC, allnes commented on tasks/mpi/morozov_e_writers_readers/src/ops_mpi.cpp
> +    std::this_thread::sleep_for(200ms);
sleep_for parameter, and please use maximum 50ms

2024-12-02 22:26 UTC, allnes approved these changes

2024-12-03 03:17 UTC, aobolensk approved these changes

2024-12-03 07:06 UTC, korablev-vm approved these changes

2024-12-03 15:22 UTC, 22380240 requested changes

2024-12-03 15:22 UTC, 22380240 commented on tasks/mpi/morozov_e_writers_readers/src/ops_mpi.cpp
> +  broadcast(world, value, 0);
```suggestion
```

-> run

2024-12-03 18:29 UTC, Egor1dzeN-learn commented on tasks/mpi/morozov_e_writers_readers/src/ops_mpi.cpp
> +  broadcast(world, value, 0);
fixed

2024-12-03 18:30 UTC, 22380240 approved these changes

2024-12-04 03:16 UTC, merged