Коровин Никита. Задача 2. Вариант 10. Топология сети передачи данных - "Линейка".
learning-process/ppc-2024-autumn pull request #310
Opened 2024-11-19 15:08 UTC by Kitos87

### **Топология сети передачи данных - "Линейка"**

В данной задаче необходимо реализовать передачу данных, используя топологию сети "Линейка". В этой топологии каждый процесс связан только с соседними процессами, что обеспечивает простую последовательность передачи данных. Например, от процесса 0 к процессу 1, от процесса 1 к процессу 2, и так далее, до процесса n

### Цели:
- Данные должны дойти до получателя без повреждений и изменений
- Выполнить требование — поддержка передачи данных при большой нагрузке, то есть при участии большого количества процессов
- Реализовать возможность передачи данных от любого выбранного процесса-отправителя к любому другому процессу-получателю в пределах одного коммуникатора

### Этапы:

**pre_processing**
- Выбирается отправитель **root** и получатель **dst**, задается количество передаваемых данных **n**
- Отправитель инициализирует данные для отправки и добавляет свой ранг в траекторию

**validation**
- Проверяется, что параметры **root** и **dst** находятся в допустимом диапазоне, данные для отправки и приема существуют, размер данных больше нуля

**run**
- Процесс-отправитель **root** начинает передачу данных следующему процессу в цепочке
- Каждый промежуточный процесс получает данные, добавляет свой ранг в траекторию и пересылает данные дальше по цепочке
- Передача продолжается до тех пор, пока данные не достигнут конечного получателя **dst**

**post_processing**
- Получатель **dst** cохраняет принятые данные и финальную траекторию для последующей проверки корректности

**Также стоит отметить:** 
- Специально создана траектория для проверки правильности маршрута
- Алгоритм поддерживает передачу данных от любого выбранного процесса к любому другому процессу в пределах одного коммуникатора
- В качестве данных используется вектор целых чисел **(int)**, который передается от **root** к **dst**

2024-11-19 16:57 UTC, ermolaevv commented on tasks/mpi/korovin_n_line_topology/func_tests/main.cpp
Your data validation appears to be rather complex, yet there are no tests in place to verify the correctness. Would it be possible for you to consider implementing some tests to ensure the correctness of the validation?

2024-11-19 19:28 UTC, korablev-vm requested changes

2024-11-19 19:28 UTC, korablev-vm commented on tasks/mpi/korovin_n_line_topology/func_tests/main.cpp
> +  }
Try adding a check for the rest of the processes (a stub), it should help get rid of incomplete processes

2024-11-20 03:46 UTC, Kitos87 commented on tasks/mpi/korovin_n_line_topology/func_tests/main.cpp
Fixed. Yes, I added functional tests for each condition in the validation and now the total codecov code coverage has risen to almost 100% Thanks!

2024-11-20 03:48 UTC, Kitos87 commented on tasks/mpi/korovin_n_line_topology/func_tests/main.cpp
> +  }
Fixed. After adding functional tests to check the conditions in the validation, I had the problem you are talking about. Thanks a lot for the advice, and indeed I initially forgot to take into account this situation.

2024-11-20 15:24 UTC, ermolaevv approved these changes

2024-11-20 15:31 UTC, korablev-vm approved these changes

2024-11-21 15:32 UTC, aobolensk requested changes

2024-11-21 15:32 UTC, aobolensk commented on tasks/mpi/korovin_n_line_topology/perf_tests/main.cpp
> +  int n = 10000;
Please, use bigger sizes for perf tests

2024-11-21 15:32 UTC, aobolensk commented on tasks/mpi/korovin_n_line_topology/include/ops_mpi.hpp
> +  static std::vector<int> generate_rnd_vector(int size, int lower_bound = -500, int upper_bound = 500);
Please, move test functions. to the test module

2024-11-21 15:32 UTC, aobolensk commented on tasks/mpi/korovin_n_line_topology/func_tests/main.cpp
> +#include "mpi/korovin_n_line_topology/include/ops_mpi.hpp"
Please, add test with n == 0

2024-11-21 15:32 UTC, aobolensk commented on tasks/mpi/korovin_n_line_topology/func_tests/main.cpp
> +TEST(korovin_n_line_topology_mpi, transfer_data) {
Please, add non random tests as well

2024-11-21 21:09 UTC, Kitos87 commented on tasks/mpi/korovin_n_line_topology/perf_tests/main.cpp
> +  int n = 10000;
Fixed

2024-11-21 21:09 UTC, Kitos87 commented on tasks/mpi/korovin_n_line_topology/include/ops_mpi.hpp
> +  static std::vector<int> generate_rnd_vector(int size, int lower_bound = -500, int upper_bound = 500);
Fixed

2024-11-21 21:10 UTC, Kitos87 commented on tasks/mpi/korovin_n_line_topology/func_tests/main.cpp
> +#include "mpi/korovin_n_line_topology/include/ops_mpi.hpp"
Done

2024-11-21 21:10 UTC, Kitos87 commented on tasks/mpi/korovin_n_line_topology/func_tests/main.cpp
> +TEST(korovin_n_line_topology_mpi, transfer_data) {
Done

2024-11-24 01:39 UTC, aobolensk approved these changes

2024-11-25 19:47 UTC, allnes commented on tasks/mpi/korovin_n_line_topology/func_tests/main.cpp
> +  }
we can work with line which has one point

2024-11-26 18:07 UTC, Kitos87 commented on tasks/mpi/korovin_n_line_topology/func_tests/main.cpp
> +  }
Fixed. Added work with one point in a line

2024-12-01 21:07 UTC, allnes approved these changes

2024-12-01 21:08 UTC, merged