Гнитиенко Кирилл. Задача 2. Вариант 27. Повышение контраста изображения
learning-process/ppc-2024-autumn pull request #312
Opened 2024-11-20 20:03 UTC by Gn4ik

### Описание последовательной задачи:
Изображение представлено вектором целых чисел. Для черно-белых изображений вектор состоит из значений яркости пикселей, а для цветных изображений — из значений для каждого канала (R, G, B) пикселя. Следовательно, размер вектора цветного изображения в 3 раза больше, чем у изображения в оттенках серого. 
Для каждого пикселя (элемента вектора) изображения вычисляется новое значение на основе коэффициента контраста по следующей формуле: 
_new pixel = (pixel − midpoint) × contrast_factor + midpoint_
_midpoint_ — центральное значение яркости (128), _contrast_factor_ — заданный коэффициент контраста.
Коэффициент контраста влияет на то, насколько сильно будут увеличиваться различия между темными и светлыми участками изображения. При обработке цветных изображений каждый пиксель представляет собой три отдельных последовательных элемента вектора, соответствующих красному (R), зеленому (G) и синему (B) каналам. Чтобы увеличить контраст изображения, для каждого компонента отдельно применяется та же формула контраста:

1. Для каждого канала (R, G, B) рассчитывается новое значение с учетом коэффициента.
2. Изменения происходят отдельно для каждого канала.

### Описание параллельной задачи:
Каждый процесс получает рассчитанную для него часть изображения и начинает обрабатывать только эти пиксели. Так, каждый процесс будет выполнять ту же операцию улучшения контраста, что и в последовательной версии, но только для своей части данных.

2024-11-22 20:28 UTC, kmichaelk requested changes

2024-11-22 20:28 UTC, kmichaelk commented on tasks/mpi/gnitienko_k_contrast_enhancement/src/ops_mpi.cpp
> +    image.assign(input_data, input_data + img_size);
```suggestion
    image.assign(input_data, input_data + img_size);
```

2024-11-22 20:28 UTC, kmichaelk commented on tasks/mpi/gnitienko_k_contrast_enhancement/src/ops_mpi.cpp
> +  image.assign(input_data, input_data + input_size);
```suggestion
  res.resize(input_size, 0);
  image.assign(input_data, input_data + input_size);
```

2024-11-22 20:28 UTC, kmichaelk commented on tasks/mpi/gnitienko_k_contrast_enhancement/src/ops_mpi.cpp
> +  }
Do you really need a different approach for handling colorful images? Seems like those loops can be merged into one.

2024-11-23 16:28 UTC, kmichaelk approved these changes

2024-11-24 02:58 UTC, aobolensk requested changes

2024-11-24 02:58 UTC, aobolensk commented on tasks/seq/gnitienko_k_contrast_enhancement/include/ops_seq.hpp
> +std::vector<int> getRandomVector(int sz);
please, move test functions to the test module

2024-11-24 02:58 UTC, aobolensk commented on tasks/mpi/gnitienko_k_contrast_enhancement/perf_tests/main.cpp
> +  double contrast_factor = 2;
Make perf test on random image

2024-11-24 02:58 UTC, aobolensk commented on tasks/mpi/gnitienko_k_contrast_enhancement/func_tests/main.cpp
> +  std::vector<int> img = {120, 240, 185, 100, 255, 0};
Is it necessary to store color component as int? Maybe uint8_t is enough?

2024-11-24 14:20 UTC, Gn4ik commented on tasks/seq/gnitienko_k_contrast_enhancement/include/ops_seq.hpp
> +std::vector<int> getRandomVector(int sz);
fixed

2024-11-25 19:52 UTC, allnes commented on tasks/mpi/gnitienko_k_contrast_enhancement/func_tests/main.cpp
> +    vec[i] = gen() % 255;
you lose 255 value

2024-11-25 19:55 UTC, allnes commented on tasks/mpi/gnitienko_k_contrast_enhancement/func_tests/main.cpp
> +  double contrast_factor = 1.5;
please use different contrast factor and check negativ value

2024-12-01 21:17 UTC, allnes approved these changes

2024-12-03 03:19 UTC, aobolensk approved these changes

2024-12-03 03:20 UTC, merged