Куракин Матвей. Задача 1. Вариант 17. Нахождение минимальных значений по строкам матрицы.
learning-process/ppc-2024-autumn pull request #314
Opened 2024-11-21 07:39 UTC by MatveyKurakin

Описание последовательного алгоритма:
- Проходим по каждому элементу строки и определяем её минимум

Описание MPI алгоритма:
- Нулевой процесс распределяет данные среди всех процессов. Каждому процессу достается целое число строк, если число строк не кратно числу процессов, в матрицу добавляются строки, чтобы число строк было четным.
- На этапе run() каждый процесс ищет минимум своих строк, а затем, с помощью reduce, результат собирается в 0 процессе.

2024-11-24 03:00 UTC, aobolensk requested changes
Is that submitted the second time? Please, mention what was fixed

2024-11-24 07:48 UTC, MatveyKurakin commented on tasks/mpi/kurakin_m_min_values_by_rows_matrix/include/kurakin_min_rows_matrix_ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
If you take the function out of the namespace, then conflicts are possible.
In the example, this function is declared in the namespace.

2024-11-25 19:57 UTC, allnes commented on tasks/mpi/kurakin_m_min_values_by_rows_matrix/src/kurakin_min_rows_matrix_ops_mpi.cpp
> +using namespace std::chrono_literals;
please remove it

2024-11-25 19:57 UTC, allnes commented on tasks/seq/kurakin_m_min_values_by_rows_matrix/src/kurakin_min_rows_matrix_ops_seq.cpp
> +using namespace std::chrono_literals;
please remove it

2024-12-03 03:22 UTC, aobolensk requested changes

2024-12-03 03:22 UTC, aobolensk commented on tasks/mpi/kurakin_m_min_values_by_rows_matrix/include/kurakin_min_rows_matrix_ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
You can wrap it with namespace in test module

2024-12-10 19:05 UTC, aobolensk approved these changes

2024-12-13 15:58 UTC, allnes approved these changes

2024-12-14 08:24 UTC, Alexey2013 commented on tasks/mpi/kurakin_m_min_values_by_rows_matrix/src/kurakin_min_rows_matrix_ops_mpi.cpp
> +  res = std::vector<int>(count_rows, 0);
This part of the code can be removed into the run()

2024-12-14 08:24 UTC, Alexey2013 commented on tasks/seq/kurakin_m_min_values_by_rows_matrix/src/kurakin_min_rows_matrix_ops_seq.cpp
> +  }
same

2024-12-14 08:37 UTC, dima-dimka04 reviewed
`std::copy` is a more convenient and understandable function, use it in the marked places, as well as in the similar code of a sequential task

2024-12-14 08:37 UTC, dima-dimka04 commented on tasks/mpi/kurakin_m_min_values_by_rows_matrix/src/kurakin_min_rows_matrix_ops_mpi.cpp
> +    }
You should use `std::copy()` there

2024-12-14 08:37 UTC, dima-dimka04 commented on tasks/mpi/kurakin_m_min_values_by_rows_matrix/src/kurakin_min_rows_matrix_ops_mpi.cpp
> +  }
`std::copy()` too

2024-12-14 17:44 UTC, Alexey2013 approved these changes

2024-12-14 19:15 UTC, dima-dimka04 approved these changes

2024-12-15 18:45 UTC, merged