Колоколова Дарья. Задача 2. Вариант 19. Метод Гаусса – ленточная горизонтальная схема
learning-process/ppc-2024-autumn pull request #315
Opened 2024-11-21 13:28 UTC by dasha1112

Описание последовательной задачи
На вход подаются два вектора - вектор с коэффициентами неизвестных  (input_coeff) и вектор свободных членов (input_y). После чего из данных матриц собирается расширенная матрица, над которой в дальнейшем и будут производится все вычисления. Далее происходит прямой ход метода Гаусса, где происходит поиск по рядам максимального элемента на необходимой позиции (т.е. сначала ищем среди всех рядов максимальный элемент на первой позиции, потом на второй и т.д.) . После нахождения максимального элемента происходит обмен строк, чтобы максимальный элемент оказался на текущей позиции. Затем код делит элементы ниже ведущего на этот максимальный элемент и вычитает соответствующие значения, чтобы занулить элементы ниже ведущего. На обратном ходе метода Гаусса, рассчитываются значения переменных, начиная с последнего уравнения и двигаясь к первому, где свободный член и значения переменных из предыдущих вычислений используются для нахождения окончательных значений переменных, которые сохраняются в векторе результата.

Описание MPI задачи
На вход так же, как и в последовательной задаче подаются две матрицы - input_coeff и input_y, после чего из данных матриц собирается расширенная матрица и ее строки делятся между процессами (каждому процессу может достаться по несколько строк). Далее происходит прямой ход Гаусса, где нулевой процесс проходится по расширенной матрице в поиске строки с максимальным элементом на необходимой позиции. После нахождения максимального элемента, нулевой процесс отправляет строку с данным элементом всем процессам, которые в свою очередь производят вычисления, благодаря которым занулются все элементы находящиеся на той же позиции, что и максимальный. Таким образом распараллеливание арифметических операций ускоряют работу данного метода. На обратном ходе, как и в последовательной версии рассчитываются значения переменных на нулевом процессе. Результат сохраняется в векторе.

2024-11-21 14:29 UTC, KADCHDR requested changes

2024-11-21 14:29 UTC, KADCHDR commented on tasks/mpi/kolokolova_d_gaussian_method_horizontal/src/ops_mpi.cpp
> +    return false;
тесты падают  из-за этого, тут лучше не использовать конструкцию с if, а просто сделать return (rank_A == rank_Ab)

2024-11-21 15:23 UTC, dasha1112 commented on tasks/mpi/kolokolova_d_gaussian_method_horizontal/src/ops_mpi.cpp
> +    return false;
Thanks! I fixed that and now it working

2024-11-21 16:14 UTC, KADCHDR approved these changes

2024-11-22 01:07 UTC, DSolo03 requested changes

2024-11-22 01:07 UTC, DSolo03 commented on tasks/mpi/kolokolova_d_gaussian_method_horizontal/src/ops_mpi.cpp
> +}
please, move in tests function that used only in tests

2024-11-22 01:07 UTC, DSolo03 commented on tasks/mpi/kolokolova_d_gaussian_method_horizontal/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
why do you including `std::chrono_literals` in namespace if you not using it

2024-11-22 07:33 UTC, dasha1112 commented on tasks/mpi/kolokolova_d_gaussian_method_horizontal/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
Fixed

2024-11-22 10:22 UTC, DSolo03 approved these changes

2024-11-24 03:01 UTC, aobolensk requested changes
Please, increase test coverage

2024-11-25 19:59 UTC, allnes commented on tasks/mpi/kolokolova_d_gaussian_method_horizontal/func_tests/main.cpp
> +  std::uniform_int_distribution<int> dist(1, 100);
please use negative values

2024-11-25 20:01 UTC, allnes commented on tasks/seq/kolokolova_d_gaussian_method_horizontal/perf_tests/main.cpp
> +  }
please use generator for right matrices for perf tests

2024-11-25 23:26 UTC, dasha1112 commented
> Please, increase test coverage
Fixed

2024-11-26 15:49 UTC, dasha1112 commented on tasks/seq/kolokolova_d_gaussian_method_horizontal/perf_tests/main.cpp
> +  }
Fixed

2024-12-01 21:19 UTC, allnes approved these changes

2024-12-03 03:27 UTC, aobolensk approved these changes

2024-12-03 03:28 UTC, merged