Шурыгин Сергей. Задача №2. Вариант №16. Ленточная вертикальная схема
learning-process/ppc-2024-autumn pull request #318
Opened 2024-11-21 19:32 UTC by PutinVVV

1. Последовательная версия алгоритма Реализация стандартного умножения матрицы на вектор: для каждой строки матрицы вычисляется скалярное произведение с вектором.

2. Параллельная версия алгоритма (Вертикальная схема) Основные этапы:

2.1. Инициализация данных

> - Главный процесс (rank 0) получает матрицу m×n и вектор n
> - Вычисляет распределение столбцов между процессами
> - Создает массивы sizes и displs для распределения данных

2.2. Распределение работы

> - Broadcast вектора всем процессам
> - Каждый процесс получает свой набор столбцов матрицы
> - Неиспользуемые процессы (при num_proc > cols) помечаются (size = 0, displacement = -1)

2.3. Вычисления

> - Каждый процесс обрабатывает свои столбцы
> - Вычисляет частичные суммы произведений для каждой строки
> - Использует row-major порядок для доступа к элементам

2.4. Сбор результатов

> - Reduce для суммирования частичных результатов
> - Сбор финального вектора на процессе 0

2024-11-25 20:05 UTC, allnes commented on tasks/mpi/shurigin_s_vertikal_shema_mpi/func_tests/main.cpp
> +TEST(shurigin_s_vertikal_shema, proc_more_than_cols) {
please resolve it in validation() function

2024-11-25 20:07 UTC, allnes commented on tasks/mpi/shurigin_s_vertikal_shema_mpi/func_tests/main.cpp
> +  int num_cols = 11;
additionaly, 16x32, 1x11, 7x7, 13x8

2024-11-26 12:07 UTC, PutinVVV commented on tasks/mpi/shurigin_s_vertikal_shema_mpi/func_tests/main.cpp
> +TEST(shurigin_s_vertikal_shema, proc_more_than_cols) {
fix

2024-11-26 12:08 UTC, PutinVVV commented on tasks/mpi/shurigin_s_vertikal_shema_mpi/src/ops_mpi.cpp
> +}
fixed

2024-11-26 12:08 UTC, PutinVVV commented on tasks/mpi/shurigin_s_vertikal_shema_mpi/func_tests/main.cpp
> +  int num_cols = 11;
fixed

2024-11-27 08:52 UTC, MikasaAkc approved these changes

2024-11-27 14:01 UTC, NeeMiyuki requested changes

2024-11-27 14:01 UTC, NeeMiyuki commented on tasks/mpi/shurigin_s_vertikal_shema_mpi/src/ops_mpi.cpp
> +#include <vector>
cstdlib, ctime, limits and iostream are included, but there is no sign it was used so it should be removed

2024-11-27 15:28 UTC, PutinVVV commented on tasks/mpi/shurigin_s_vertikal_shema_mpi/src/ops_mpi.cpp
> +#include <vector>
fixed

2024-11-27 16:31 UTC, NeeMiyuki approved these changes

2024-11-27 18:15 UTC, Alexey-Solovev approved these changes

2024-11-29 19:51 UTC, Alexmazhara approved these changes

2024-11-29 19:51 UTC, Alexmazhara approved these changes

2024-12-01 21:20 UTC, allnes approved these changes

2024-12-03 03:27 UTC, aobolensk approved these changes

2024-12-03 03:27 UTC, merged