Резанцева Анастасия. Задача 1. Вариант 9. Скалярное произведение векторов.
learning-process/ppc-2024-autumn pull request #32
Opened 2024-10-22 17:45 UTC by AnastasiaRezantseva

Описание последовательной задачи
Выполняется поэлементное умножение двух векторов,  результаты умножения суммируются для получения итогового значения скалярного произведения

Описание MPI задачи
Двумерный вектор целых чисел (std::vector<std::vector<int>>), который содержит два входных вектора, которые затем делятся на равные сегменты в зависимости от количества процессов. Затем эти сегменты отправляются в соответствующие процессы для дальнейшей обработки.  Каждый процесс получает свой сегмент данных и происходит поэлементное умножение двух векторов, результаты перемножения  суммируются. После этого результаты со всех процессов собираются на корневом процессе, где происходит их суммирование для получения итогового значения.

2024-10-25 13:43 UTC, hasanyanovk commented on tasks/mpi/rezantseva_a_vector_dot_product/include/ops_mpi.hpp
> +class TestMPITaskSequential : public ppc::core::Task {
Invalid name of class, check example

2024-10-25 13:48 UTC, hasanyanovk commented on tasks/mpi/rezantseva_a_vector_dot_product/src/ops_mpi.cpp
> +    broadcast(world, count_rank_add, 0);
not need to share `count_rank_add` if you dont use it

2024-10-25 14:12 UTC, AnastasiaRezantseva commented on tasks/mpi/rezantseva_a_vector_dot_product/include/ops_mpi.hpp
> +class TestMPITaskSequential : public ppc::core::Task {
The example shows how we are required to name the namespace, the name of the classes is not regulated

2024-10-27 11:10 UTC, AnastasiaRezantseva commented on tasks/mpi/rezantseva_a_vector_dot_product/src/ops_mpi.cpp
> +    broadcast(world, count_rank_add, 0);
fixed

2024-10-27 11:10 UTC, AnastasiaRezantseva commented on tasks/mpi/rezantseva_a_vector_dot_product/src/ops_mpi.cpp
> +  if (v1.size() != v2.size()) throw "Error! Vectors must have equal size!";
fixed

2024-10-27 11:10 UTC, AnastasiaRezantseva commented on tasks/mpi/rezantseva_a_vector_dot_product/src/ops_mpi.cpp
> +  if (num_processes == 0) {
fixed

2024-10-27 11:11 UTC, AnastasiaRezantseva commented on tasks/mpi/rezantseva_a_vector_dot_product/src/ops_mpi.cpp
> +  std::this_thread::sleep_for(20ms);
fixed

2024-10-28 15:46 UTC, Tanya-Yasakova commented on tasks/mpi/rezantseva_a_vector_dot_product/src/ops_mpi.cpp
> +std::vector<int> rezantseva_a_vector_dot_product_mpi::createRandomVector(int v_size) {
Этот метод можно перенести в тесты, потому что только там он используется

2024-10-28 16:29 UTC, AnastasiaRezantseva commented on tasks/mpi/rezantseva_a_vector_dot_product/src/ops_mpi.cpp
> +std::vector<int> rezantseva_a_vector_dot_product_mpi::createRandomVector(int v_size) {
moved

2024-10-28 16:32 UTC, Tanya-Yasakova approved these changes

2024-10-29 00:05 UTC, aobolensk requested changes

2024-10-29 00:05 UTC, aobolensk commented on tasks/mpi/rezantseva_a_vector_dot_product/perf_tests/main.cpp
> +std::vector<int> v2 = createRandomVector(count_size_vector);
Do not use global vectors for the tests. You can create them in the tests

2024-10-29 16:17 UTC, AnastasiaRezantseva commented on tasks/mpi/rezantseva_a_vector_dot_product/perf_tests/main.cpp
> +std::vector<int> v2 = createRandomVector(count_size_vector);
fixed, now vectors are created in the tests themselves

2024-10-29 19:23 UTC, allnes commented on tasks/seq/rezantseva_a_vector_dot_product/src/ops_seq.cpp
> +  if (v1.size() != v2.size()) throw "Error! Vectors must have equal size!";
it would be check in validation

2024-10-29 19:24 UTC, allnes commented on tasks/seq/rezantseva_a_vector_dot_product/src/ops_seq.cpp
> +using namespace std::chrono_literals;
for what do you use it?

2024-10-29 19:25 UTC, allnes commented on tasks/mpi/rezantseva_a_vector_dot_product/src/ops_mpi.cpp
> +bool rezantseva_a_vector_dot_product_mpi::TestMPITaskParallel::pre_processing() {
please send data in run() its part of mpi algorithm

2024-10-29 20:25 UTC, AnastasiaRezantseva commented on tasks/seq/rezantseva_a_vector_dot_product/src/ops_seq.cpp
> +  if (v1.size() != v2.size()) throw "Error! Vectors must have equal size!";
removed

2024-10-29 20:25 UTC, AnastasiaRezantseva commented on tasks/seq/rezantseva_a_vector_dot_product/src/ops_seq.cpp
> +using namespace std::chrono_literals;
removed using namespace std::chrono_literals; 
i use offset in **std::vector<int> createRandomVector**  to ensure the uniqueness of the initial value of the random number generator
moved this method to the seq tests, because it is used only there

2024-10-29 20:27 UTC, AnastasiaRezantseva commented on tasks/mpi/rezantseva_a_vector_dot_product/src/ops_mpi.cpp
> +bool rezantseva_a_vector_dot_product_mpi::TestMPITaskParallel::pre_processing() {
now i send and recv data in run()

2024-10-30 00:45 UTC, aobolensk approved these changes

2024-10-31 00:38 UTC, allnes approved these changes

2024-10-31 00:39 UTC, merged