Моисеев Артём. Задача 2. Вариант 17. Ленточная горизонтальная схема - разбиение только матрицы А
learning-process/ppc-2024-autumn pull request #321
Opened 2024-11-21 22:37 UTC by MoiseevArt

Описание последовательной задачи:
Используется наивный алгоритм умножения матриц.
Описание MPI задачи: 
Код решает умножение матриц с использованием ленточно-горизонтального разбиения только матрицы A на несколько процессов. Главный процесс (rank 0) загружает входные данные и делит матрицу A по строкам для каждого процесса, учитывая остаток от деления для равномерного распределения строк. Каждый процесс получает свою часть матрицы A и вычисляет локальную часть матрицы C, умножая свою часть A на матрицу B. После завершения вычислений локальные результаты собираются с помощью операции gatherv, чтобы сформировать глобальную матрицу C. Основной процесс записывает результат в taskData->outputs.

2024-11-22 05:57 UTC, 22380240 requested changes

2024-11-22 05:57 UTC, 22380240 commented on tasks/mpi/moiseev_a_ribbon_hor_scheme_splt_mat_a/include/ops_mpi.hpp
> +    std::fill(C.begin(), C.end(), 0);
```suggestion
    C = std::vector<DataType>(m * n, 0);
```

2024-11-22 10:01 UTC, 22380240 approved these changes

2024-11-22 20:31 UTC, kmichaelk requested changes

2024-11-22 20:31 UTC, kmichaelk commented on tasks/mpi/moiseev_a_ribbon_hor_scheme_splt_mat_a/include/ops_mpi.hpp
> +    std::vector<size_t> distributions = {0};
```suggestion
    std::vector<size_t> distributions;
```

2024-11-22 21:32 UTC, kmichaelk approved these changes

2024-11-24 03:14 UTC, aobolensk requested changes

2024-11-24 03:14 UTC, aobolensk commented on tasks/mpi/moiseev_a_ribbon_hor_scheme_splt_mat_a/func_tests/main.cpp
> +std::vector<DataType> generateRandomValues(int size) {
Either make it static or wrap with your namespace

2024-11-24 03:14 UTC, aobolensk commented on tasks/seq/moiseev_a_ribbon_hor_scheme_splt_mat_a/perf_tests/main.cpp
> +  taskData->outputs.emplace_back(reinterpret_cast<uint8_t*>(C.data()));
Run perf tests on random matrix

2024-11-24 11:13 UTC, MoiseevArt commented on tasks/mpi/moiseev_a_ribbon_hor_scheme_splt_mat_a/func_tests/main.cpp
> +std::vector<DataType> generateRandomValues(int size) {
done

2024-11-24 11:13 UTC, MoiseevArt commented on tasks/seq/moiseev_a_ribbon_hor_scheme_splt_mat_a/perf_tests/main.cpp
> +  taskData->outputs.emplace_back(reinterpret_cast<uint8_t*>(C.data()));
done

2024-11-25 20:13 UTC, allnes commented on tasks/mpi/moiseev_a_ribbon_hor_scheme_splt_mat_a/func_tests/main.cpp
> +  size_t n = 3;
please add
* 4x8x16
* 7x3x13
* 8x7x23
* 11x10x9

2024-11-25 20:13 UTC, allnes commented on tasks/mpi/moiseev_a_ribbon_hor_scheme_splt_mat_a/include/ops_mpi.hpp
> +    }
please check it in validation

2024-11-25 20:14 UTC, allnes commented on tasks/CMakeLists.txt
> +              target_link_libraries(${EXEC_FUNC} PUBLIC boost_mpi boost_serialization)
where are you using it?

2024-11-25 22:30 UTC, MoiseevArt commented on tasks/mpi/moiseev_a_ribbon_hor_scheme_splt_mat_a/func_tests/main.cpp
> +  size_t n = 3;
added

2024-11-25 22:30 UTC, MoiseevArt commented on tasks/mpi/moiseev_a_ribbon_hor_scheme_splt_mat_a/include/ops_mpi.hpp
> +    }
fixed

2024-12-01 21:24 UTC, allnes commented on tasks/CMakeLists.txt
> +              target_link_libraries(${EXEC_FUNC} PUBLIC boost_mpi boost_serialization)
if it was added in master, please correct it in your branch, this changes don't need to be here

2024-12-02 22:32 UTC, allnes approved these changes

2024-12-03 03:32 UTC, aobolensk approved these changes

2024-12-03 03:32 UTC, merged