Fix func tests. Чижов Максим. Задача 1. Вариант 16. Нахождение максимальных значений по столбца матрицы
learning-process/ppc-2024-autumn pull request #322
Opened 2024-11-22 12:06 UTC by MaximChizhov

Матрица представлена в виде вектора целых чисел

**Описание последовательной задачи**
В качестве максимального элемента выбирается первый элемент столбца. Дальше каждый элемент столбца сравнивается с максимальным, если значение элемента столбца больше максимального, то максимальный элемент обновляется. В конце выполнения функции возвращается вектор, который содержит максимальные значения каждого столбца.

**Описание MPI задачи**
В зависимости от количества столбцов и процессов матрица делится. Каждый процесс получает определенное количество столбцов, в которых находит максимальные значения в каждом столбце. Для этого рассчитывается стартовый столбец и последний столбец. Результат собирается при помощи функции gatherv в один вектор.

2024-11-22 12:45 UTC, MaxikGuy approved these changes

2024-11-22 12:46 UTC, WladislawFilatew approved these changes

2024-11-24 03:15 UTC, aobolensk requested changes
Please add what was fixed to the description

2024-11-25 20:16 UTC, allnes commented on tasks/mpi/chizhov_m_max_values_by_columns_matrix/src/ops_mpi.cpp
> +  int extra = cols % world.size();
please send delta and extra instead cols and rows

2024-12-03 03:33 UTC, aobolensk approved these changes

2024-12-13 23:37 UTC, MaximChizhov commented on tasks/mpi/chizhov_m_max_values_by_columns_matrix/src/ops_mpi.cpp
> +  int extra = cols % world.size();
fix, but I need to send out at least rows for my implementation

2024-12-15 19:01 UTC, allnes approved these changes

2024-12-15 19:01 UTC, merged