Дрождинов Дмитрий. Задача 2. Вариант 20. Метод Гаусса – ленточная вертикальная схема.
learning-process/ppc-2024-autumn pull request #323
Opened 2024-11-22 12:42 UTC by dima-dimka04

### Последовательная задача
Прямой ход метода Гаусса: на каждом шаге выбирается ведущий (`major`) элемент, другие элементы строки делятся на него, производятся элементарные преобразования со строками матрицы и со столбцом свободных членов. 
Обратный ход метода Гаусса: для каждой строки от последней к первой вычисляется значение переменной.
### Параллельная задача
Используется вертикальная схема разделения данных (по столбцам матрицы), каждый процесс получает блок столбцов, остаток делится между процессами с меньшим рангом(при необходимости). Каждый процесс локально ищет максимальный элемент в столбцах, которые он обрабатывает, и передаёт результат через `all_reduce` для определения глобального максимума. С помощью `broadcast` рассылаются коэффициенты для элементарных преобразований и порядок использования строк. В обратном ходе каждый процесс локально вычисляет свои данные, а вектор решения собирается в нулевом процессе.

2024-11-22 20:10 UTC, Alexey2013 commented on tasks/mpi/drozhdinov_d_gauss_vertical_scheme/include/ops_mpi.hpp
> +std::vector<double> genElementaryMatrix(int rows, int columns);
you generate only identity matrix for tests. can you try on other matrices to estimate the running time of the algorithm correctly?

2024-11-22 20:10 UTC, Alexey2013 commented on tasks/seq/drozhdinov_d_gauss_vertical_scheme/include/ops_seq.hpp
> +std::vector<double> genElementaryMatrix(int rows, int columns);
same

2024-11-23 12:47 UTC, dima-dimka04 commented on tasks/mpi/drozhdinov_d_gauss_vertical_scheme/include/ops_mpi.hpp
> +std::vector<double> genElementaryMatrix(int rows, int columns);
done. now there are tests on dense matrices as well

2024-11-23 13:11 UTC, Alexey2013 approved these changes

2024-11-23 17:14 UTC, MatveyKurakin commented on tasks/mpi/drozhdinov_d_gauss_vertical_scheme/src/ops_mpi.cpp
> +bool drozhdinov_d_gauss_vertical_scheme_mpi::TestMPITaskSequential::validation() {
Добавьте проверку на детерминант, ранг матрицы и проверку на число элементов в inputs, inputs_count, outputs, outputs_count
Аналогично для validation в TestMPITaskParallel

2024-11-25 12:14 UTC, dima-dimka04 commented on tasks/mpi/drozhdinov_d_gauss_vertical_scheme/src/ops_mpi.cpp
> +bool drozhdinov_d_gauss_vertical_scheme_mpi::TestMPITaskSequential::validation() {
Сделано

2024-11-25 12:18 UTC, MatveyKurakin approved these changes

2024-11-25 20:17 UTC, allnes commented on tasks/mpi/drozhdinov_d_gauss_vertical_scheme/src/ops_mpi.cpp
> +}
please move it to tests and use negative values too

2024-11-25 20:18 UTC, allnes commented on tasks/mpi/drozhdinov_d_gauss_vertical_scheme/src/ops_mpi.cpp
> +  }
where is check for determinant and single solution

2024-11-25 20:19 UTC, allnes commented on tasks/mpi/drozhdinov_d_gauss_vertical_scheme/src/ops_mpi.cpp
> +}
please use mpi functionality in run()

2024-11-26 00:02 UTC, aobolensk requested changes

2024-11-26 00:02 UTC, aobolensk commented on tasks/mpi/drozhdinov_d_gauss_vertical_scheme/include/ops_mpi.hpp
> +std::vector<T> getRandomVector(int sz);
please, move test functions to the test module

2024-11-26 00:02 UTC, aobolensk commented on tasks/seq/drozhdinov_d_gauss_vertical_scheme/func_tests/main.cpp
> +// not example
What does that mean?

2024-11-26 10:15 UTC, dima-dimka04 commented on tasks/mpi/drozhdinov_d_gauss_vertical_scheme/src/ops_mpi.cpp
> +}
Done

2024-11-26 10:15 UTC, dima-dimka04 commented on tasks/mpi/drozhdinov_d_gauss_vertical_scheme/src/ops_mpi.cpp
> +}
Done

2024-11-26 10:18 UTC, dima-dimka04 commented on tasks/mpi/drozhdinov_d_gauss_vertical_scheme/src/ops_mpi.cpp
> +  }
in the sequential task I check the determinant and ranks of the matrix in preprocessing, since the filling of vectors from taskData is implemented there. I find it more convenient, I don't think it's a serious mistake.

2024-11-26 14:17 UTC, dima-dimka04 commented on tasks/mpi/drozhdinov_d_gauss_vertical_scheme/include/ops_mpi.hpp
> +std::vector<T> getRandomVector(int sz);
Done

2024-11-26 14:17 UTC, dima-dimka04 commented on tasks/seq/drozhdinov_d_gauss_vertical_scheme/func_tests/main.cpp
> +// not example
Removed these notations

2024-12-01 21:25 UTC, allnes approved these changes

2024-12-03 03:39 UTC, aobolensk approved these changes

2024-12-03 03:39 UTC, merged