Наседкин Егор. Задача 2. Вариант 23. Итеративные методы (Зейделя).
learning-process/ppc-2024-autumn pull request #326
Opened 2024-11-22 17:17 UTC by myffii

2024-11-22 23:30 UTC, keshaproger commented on tasks/mpi/nasedkin_e_seidels_iterate_methods/func_tests/main.cpp
> +    auto taskData = std::make_shared<ppc::core::TaskData>();
Need to remove extra spaces

2024-11-22 23:30 UTC, keshaproger commented on tasks/mpi/nasedkin_e_seidels_iterate_methods/include/ops_mpi.hpp
> +    public:
Need to remove extra spaces

2024-11-22 23:32 UTC, keshaproger commented on tasks/mpi/nasedkin_e_seidels_iterate_methods/perf_tests/main.cpp
> +    taskData->inputs_count.push_back(3);  // Задаем корректное число уравнений
Need to remove extra spaces

2024-11-23 00:26 UTC, keshaproger approved these changes

2024-11-23 10:44 UTC, dangerulya requested changes

2024-11-23 10:44 UTC, dangerulya commented on tasks/mpi/nasedkin_e_seidels_iterate_methods/func_tests/main.cpp
> +TEST(nasedkin_e_seidels_iterate_methods_mpi, test_with_invalid_input) {
Add a test for a matrix with zero values ​​on the diagonal.

2024-11-23 20:06 UTC, dangerulya approved these changes

2024-11-24 03:20 UTC, aobolensk requested changes

2024-11-24 03:20 UTC, aobolensk commented on tasks/mpi/nasedkin_e_seidels_iterate_methods/src/ops_mpi.cpp
> +    std::cout << "Solution: ";
Please, remove debug output from the actual code

2024-11-24 03:20 UTC, aobolensk commented on tasks/mpi/nasedkin_e_seidels_iterate_methods/func_tests/main.cpp
> +#include <gtest/gtest.h>
What about seq version?

2024-11-25 20:23 UTC, allnes commented on tasks/mpi/nasedkin_e_seidels_iterate_methods/src/ops_mpi.cpp
> +  }
its validation

2024-11-25 20:26 UTC, allnes commented on tasks/mpi/nasedkin_e_seidels_iterate_methods/func_tests/main.cpp
> +TEST(nasedkin_e_seidels_iterate_methods_mpi, test_with_valid_input) {
I can't find check `||Ax-b|| < eps` for rando, values with right generated matrix

2024-12-07 16:38 UTC, aobolensk approved these changes

2024-12-08 11:04 UTC, allnes approved these changes

2024-12-08 11:05 UTC, merged