Соловьев Алексей. Задача 2. Вариант 12. Топология сети Звезда.
learning-process/ppc-2024-autumn pull request #327
Opened 2024-11-22 20:08 UTC by Alexey-Solovev

Нулевой процесс, который является root процессом, получает на вход вектор целых чисел, который записывается в переменную input_, затем передаёт эту переменную всем остальным процессам, в свою очередь остальные процессы принимают эту переменную и передают её обратно в нулевой процесс, при получении этих данных нулевой процесс записывает их в переменную res, которая изначально инициализируется как вектор нулей такого же размера как и входные данные. В тестах происходит поэлементное сравнение входных данных и итогового результата.

2024-11-23 18:41 UTC, NeeMiyuki requested changes

2024-11-23 18:41 UTC, NeeMiyuki commented on tasks/mpi/solovev_a_star_topology/perf_tests/main.cpp
> +std::vector<int> generate_random_vector(size_t size) {
this function should also be used in a func_tests to generate a random vector for tests

2024-11-23 22:11 UTC, Alexey-Solovev commented on tasks/mpi/solovev_a_star_topology/perf_tests/main.cpp
> +std::vector<int> generate_random_vector(size_t size) {
Fixed

2024-11-24 00:04 UTC, NeeMiyuki approved these changes

2024-11-24 03:26 UTC, aobolensk requested changes

2024-11-24 03:26 UTC, aobolensk commented on tasks/mpi/solovev_a_star_topology/func_tests/main.cpp
> +std::vector<int> generate_random_vector(size_t size) {
Make it either static or wrap with namespace

2024-11-24 03:26 UTC, aobolensk commented on tasks/mpi/solovev_a_star_topology/func_tests/main.cpp
> +        ASSERT_EQ(output[i], input[i]);
Add checks of received data on each data

2024-11-24 03:26 UTC, aobolensk commented on tasks/mpi/solovev_a_star_topology/func_tests/main.cpp
> +
Please, add tests that verify data transfer order

2024-11-25 20:27 UTC, allnes commented on tasks/mpi/solovev_a_star_topology/func_tests/main.cpp
> +  if (world.size() > 1) {
check in validation please

2024-11-27 18:10 UTC, PutinVVV requested changes
add a test to check the first condition in validation, that is, so that its input and output data are of different sizes but not empty
, and delete the library random in the implementation of func_test and perf_test

2024-11-27 19:10 UTC, PutinVVV approved these changes

2024-12-01 21:27 UTC, allnes approved these changes

2024-12-03 03:38 UTC, aobolensk requested changes

2024-12-03 03:38 UTC, aobolensk commented on tasks/mpi/solovev_a_star_topology/include/ops_mpi.hpp
> +std::vector<int> generate_random_vector(size_t size);
Please, move test function to the test module

2024-12-03 03:38 UTC, aobolensk commented on tasks/mpi/solovev_a_star_topology/func_tests/main.cpp
> +
Please, check the order in with data is transferred

2024-12-03 19:09 UTC, Alexey-Solovev commented on tasks/mpi/solovev_a_star_topology/include/ops_mpi.hpp
> +std::vector<int> generate_random_vector(size_t size);
fixed

2024-12-03 19:10 UTC, Alexey-Solovev commented on tasks/mpi/solovev_a_star_topology/func_tests/main.cpp
> +
fixed (if I understood correctly what you meant)

2024-12-04 03:18 UTC, aobolensk commented on tasks/mpi/solovev_a_star_topology/func_tests/main.cpp
> +
ok

2024-12-04 03:18 UTC, aobolensk approved these changes

2024-12-04 03:18 UTC, merged