Мухина Маргарита. Задача 2. Вариант 15. Ленточная горизонтальная схема
learning-process/ppc-2024-autumn pull request #328
Opened 2024-11-22 21:06 UTC by MargaritaMuhina

1. Последовательный алгоритм

Для каждой строки матрицы вычисляется результат, перемножая элементы этой строки на элементы вектора и суммируя их.

2. Параллельный алгоритм 

Процесс с рангом 0 отвечает за загрузку данных: матрицы и вектора, а также за вычисление распределения строк и их смещений между процессами.
Функция calculate_distribution вычисляет, сколько строк матрицы будет обрабатывать каждый процесс и какие смещения у этих строк. 
В случае, если количество процессов больше, чем строк матрицы, каждый процесс будет обрабатывать одну строку.
Если процессов меньше, чем строк, то строки делятся на равные блоки, и оставшиеся строки распределяются между процессами.

Размеры матрицы и вектора, а также распределение строк передаются всем процессам через broadcast.
Каждый процесс получает свою локальную часть матрицы и вектора, которые ему нужно обработать.
Для каждой строки, принадлежащей данному процессу, вычисляется скалярное произведение строки матрицы и вектора.
Локальные результаты сохраняются в массиве local_result.

После того, как все процессы завершили локальные вычисления, происходит обмен результатами с помощью операции boost::mpi::reduce.
Частичные результаты от всех процессов суммируются и отправляются на процесс с рангом 0.

2024-11-27 17:56 UTC, Semyon1104 commented on tasks/seq/muhina_m_horizontal_cheme/src/ops_seq.cpp
> +bool muhina_m_horizontal_cheme_seq::HorizontalSchemeSequential::validation() {
add a check for the possibility of multiplication - the number of columns should be equal to the number of rows in the vector. and the same in mpi version

2024-11-27 20:05 UTC, andrewmeow requested changes

2024-11-27 20:05 UTC, andrewmeow commented on tasks/mpi/muhina_m_horizontal_cheme/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
If you don't use it, delete it

2024-11-27 20:20 UTC, andrewmeow requested changes

2024-11-27 20:20 UTC, andrewmeow commented on tasks/mpi/muhina_m_horizontal_cheme/func_tests/main.cpp
> +  }
Add a validation test if the vector is going to be empty

2024-11-27 20:28 UTC, andrewmeow requested changes

2024-11-27 20:28 UTC, andrewmeow commented on tasks/mpi/muhina_m_horizontal_cheme/func_tests/main.cpp
> +  muhina_m_horizontal_cheme_mpi::HorizontalSchemeMPIParallel matrixVecMultParalle(taskDataPar);
You already use your namespace

2024-11-27 21:21 UTC, MargaritaMuhina commented on tasks/seq/muhina_m_horizontal_cheme/src/ops_seq.cpp
> +bool muhina_m_horizontal_cheme_seq::HorizontalSchemeSequential::validation() {
fixed

2024-11-27 21:21 UTC, MargaritaMuhina commented on tasks/mpi/muhina_m_horizontal_cheme/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
fixed

2024-11-27 21:22 UTC, MargaritaMuhina commented on tasks/mpi/muhina_m_horizontal_cheme/func_tests/main.cpp
> +  }
fixed_

2024-11-27 21:22 UTC, MargaritaMuhina commented on tasks/mpi/muhina_m_horizontal_cheme/func_tests/main.cpp
> +  muhina_m_horizontal_cheme_mpi::HorizontalSchemeMPIParallel matrixVecMultParalle(taskDataPar);
fixed

2024-11-27 22:27 UTC, Semyon1104 approved these changes

2024-11-27 23:24 UTC, andrewmeow approved these changes

2024-12-01 21:33 UTC, allnes commented on tasks/mpi/muhina_m_horizontal_cheme/src/ops_mpi.cpp
> +  for (int i = 0; i < (int)(localMatrix.size() / cols_); i++) {
please use `(int)(localMatrix.size() / cols_)` outside loop as constant in loop

2024-12-01 21:34 UTC, allnes commented on tasks/mpi/muhina_m_horizontal_cheme/func_tests/main.cpp
> +    matrix = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
please check not square matrix too

2024-12-02 22:35 UTC, allnes commented on tasks/mpi/muhina_m_horizontal_cheme/func_tests/main.cpp
> +    matrix = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
how can be 13 elements in matrix?

2024-12-04 11:52 UTC, MargaritaMuhina commented on tasks/mpi/muhina_m_horizontal_cheme/src/ops_mpi.cpp
> +  for (int i = 0; i < (int)(localMatrix.size() / cols_); i++) {
fixed

2024-12-04 11:52 UTC, MargaritaMuhina commented on tasks/mpi/muhina_m_horizontal_cheme/func_tests/main.cpp
> +    matrix = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
fixed

2024-12-05 23:31 UTC, allnes commented on tasks/mpi/muhina_m_horizontal_cheme/func_tests/main.cpp
> +    matrix = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
I can't find fix

2024-12-05 23:32 UTC, allnes commented on tasks/mpi/muhina_m_horizontal_cheme/src/ops_mpi.cpp
> +  for (int i = 0; i < (int)(localMatrix.size() / cols_); i++) {
I don't see changes in 150th line

2024-12-05 23:44 UTC, allnes approved these changes

2024-12-07 10:47 UTC, aobolensk approved these changes

2024-12-07 10:48 UTC, merged