Шурыгин Сергей. Задача №1. Вариант №16. Нахождение максимальных значений по столбцам матрицы
learning-process/ppc-2024-autumn pull request #33
Opened 2024-10-23 11:08 UTC by PutinVVV

Код выполняет вычисление максимальных значений в каждом столбце матрицы. Матрица представлена как двухмерный вектор целых чисел **(std::vector<std::vector<int>>)**.

**Описание последовательной задачи**
Каждый элемент матрицы сравнивается с текущим максимальным значением в соответствующем столбце, и при нахождении большего значения оно сохраняется как новое максимальное значение. В конце выполнения функции возвращается вектор, содержащий максимальные значения для каждого столбца.

**Описание MPI задачи**
Матрица целых чисел разбивается на равные части. Каждый процесс получает свою часть матрицы и находит максимальные значения в каждом столбце этой части. Затем все процессы отправляют свои результаты на главный процесс, который собирает их и определяет окончательные максимальные значения для каждого столбца всей матрицы.

2024-10-26 09:36 UTC, DSolo03 requested changes

2024-10-26 09:36 UTC, DSolo03 commented on tasks/mpi/Shurygin_S_max_po_stolbam_matrix/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
Adding `std::chrono_literals` to global namespace without using it later

2024-10-26 09:36 UTC, DSolo03 commented on tasks/seq/Shurygin_S_max_po_stolbam_matrix/src/ops_seq.cpp
> +using namespace std::chrono_literals;
Adding `std::chrono_literals` to global namespace without using it later

2024-10-27 09:21 UTC, allnes commented on tasks/seq/example/include/ops_seq.hpp
> -
please don't change not own files

2024-10-27 09:22 UTC, allnes commented on 2
> +[33mcommit 8a6f256857672c581fb479721112980339b9bab3[m[33m ([m[1;36mHEAD -> [m[1;32mShurygin_S_max_po_stolbam_matrix[m[33m, [m[1;31morigin/Shurygin_S_max_po_stolbam_matrix[m[33m)[m
please remove this files

2024-10-27 14:55 UTC, aobolensk requested changes

2024-10-27 14:55 UTC, aobolensk commented on tasks/seq/Shurygin_S_max_po_stolbam_matrix/perf_tests/main.cpp
> +  const int cols = 5000;
Use different sizes for tests

2024-10-28 11:08 UTC, PutinVVV commented on tasks/seq/example/include/ops_seq.hpp
> -
OK, I replaced it with the original file

2024-10-28 11:09 UTC, PutinVVV commented on tasks/seq/Shurygin_S_max_po_stolbam_matrix/perf_tests/main.cpp
> +  const int cols = 5000;
Okay, I corrected it.

2024-10-28 13:01 UTC, allnes approved these changes

2024-10-29 00:09 UTC, aobolensk approved these changes

2024-10-31 15:40 UTC, DSolo03 approved these changes

2024-10-31 15:41 UTC, merged