Малышев Антон. Задача 2. Вариант 24. Метод простой итерации.
learning-process/ppc-2024-autumn pull request #331
Opened 2024-11-23 15:01 UTC by lolipolovkovith

Валидация проверяет: 
1. Верность заполнения taskData
2. Совместность системы
2.1 Определитель  матрицы A не равен нулю
2.2 Ранг матрицы A равен рангу расширенной матрицы (A | B)
3. Скорость сходимости итерационного процесса (хотя бы одно)
3.1 Происходит доминирование по строкам
3.2 Происходит доминирование по столбцам

Входящие матрица A и вектор-столбец B пересчитываются в матрицу C и  вектор-столбец D. 
Итерационный процесс: Xk+1 = C * Xk + D
Итерационный процесс происходит, пока не будет достигнута заданная точность. 

Генерация случайных данных: 
- Чтобы гарантировать наличие решения, сначала генерируется решение
- Чтобы гарантировать скорость сходимости, сначала генерируются элементы на главной диагонали, а потом все остальные элементы в строке. 
- Свободные члены уравнения генерируются на основе сгенерированного решения и коэффициентов уравнения

В MPI, в отличие от seq каждый процесс просчитывает новые X на каждом шаге итерации лишь для своего набора уравнений. После каждой итерации все новые X собирает 0 процесс и проводится проверка погрешности. Если необходимая погрешность достигнута, итерационный процесс останавливается. Если точность недостигнута, то X0 = X, и новые X0 рассылаются процессам для продолжения итеративного процесса

2024-11-23 18:01 UTC, AndreySorokin7 requested changes

2024-11-23 18:01 UTC, AndreySorokin7 commented on tasks/mpi/malyshev_a_simple_iteration_method/func_tests/main.cpp
I looked at your codecov, you should use the Seq part in the MPI part tests. It would also be good if you wrote tests for your complex validation

2024-11-23 19:46 UTC, lolipolovkovith commented on tasks/mpi/malyshev_a_simple_iteration_method/func_tests/main.cpp
I agree with your comment. Fixed it.

2024-11-23 19:55 UTC, AndreySorokin7 approved these changes

2024-11-24 03:27 UTC, aobolensk requested changes
Please, increase code coverage

2024-11-24 08:58 UTC, lolipolovkovith commented
> Please, increase code coverage

@aobolensk I do not know why codecov does not see test coverage here. I am absolutely sure that I have a test that uses this block of code (validate_input_zero_on_the_main_diagonal)

![image](https://github.com/user-attachments/assets/8efdd845-0cc7-4fe3-8b5c-077c3d2023d7)

2024-11-24 09:21 UTC, Yarik3008 commented on tasks/mpi/malyshev_a_simple_iteration_method/src/matrix.cpp
> +}
It looks like you don't use it anywhere. Maybe you should delete it?

2024-11-24 09:21 UTC, Yarik3008 commented on tasks/seq/malyshev_a_simple_iteration_method/src/matrix.cpp
> +}
Same

2024-11-24 09:21 UTC, Yarik3008 commented on tasks/seq/malyshev_a_simple_iteration_method/perf_tests/main.cpp
It looks like you forgot to write seq at the end of the test suite name

2024-11-24 09:37 UTC, lolipolovkovith commented on tasks/mpi/malyshev_a_simple_iteration_method/src/matrix.cpp
> +}
It makes sense. Deleted

2024-11-24 09:37 UTC, lolipolovkovith commented on tasks/seq/malyshev_a_simple_iteration_method/src/matrix.cpp
> +}
It makes sense. Deleted

2024-11-24 09:38 UTC, lolipolovkovith commented on tasks/seq/malyshev_a_simple_iteration_method/perf_tests/main.cpp
Fixed

2024-11-24 09:46 UTC, Yarik3008 approved these changes

2024-11-26 00:05 UTC, aobolensk commented
> > Please, increase code coverage
> 
> @aobolensk I do not know why codecov does not see test coverage here. I am absolutely sure that I have a test that uses this block of code (validate_input_zero_on_the_main_diagonal)
> 
> ![image](https://private-user-images.githubusercontent.com/132440944/389259468-8efdd845-0cc7-4fe3-8b5c-077c3d2023d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1Nzk2ODMsIm5iZiI6MTczMjU3OTM4MywicGF0aCI6Ii8xMzI0NDA5NDQvMzg5MjU5NDY4LThlZmRkODQ1LTBjYzctNGZlMy04YjVjLTA3N2MzZDIwMjNkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwMDAzMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGNiNzZmMDMyNzkxOGRkMmMzOWZlNjNhMTY4ODk1ODdhMjc5OWIyM2FjN2ZlY2JiMWM5NjY1Njc4MjNiYTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fz0gbq2unCj7jy_8NwJfg81bNKcumJMkV2W3-zFAlS0)

`==` with double type may return non 0 and that is ok. I guess, to verify, you can remove this code and raise an exception instead of it and run the tests on CI. If it does not fail in this case, please ping me and attach the log link

2024-11-26 01:19 UTC, aobolensk requested changes

2024-11-26 01:19 UTC, aobolensk commented on tasks/mpi/malyshev_a_simple_iteration_method/include/matrix.hpp
> +void getRandomData(uint32_t n, std::vector<double>& A, std::vector<double>& B);
Please, move test function to the test module

2024-11-26 01:19 UTC, aobolensk commented on tasks/seq/malyshev_a_simple_iteration_method/perf_tests/main.cpp
> +  const int size = 300;
Please, increase matrix size for perf tests

2024-11-26 01:19 UTC, aobolensk commented on tasks/mpi/malyshev_a_simple_iteration_method/func_tests/main.cpp
> +
```suggestion
```

2024-11-26 01:19 UTC, aobolensk commented on tasks/mpi/malyshev_a_simple_iteration_method/func_tests/main.cpp
> +    malyshev_a_simple_iteration_method_mpi::getRandomData(size, A, B);
Please, add more random tests on different shapes

2024-11-26 19:45 UTC, lolipolovkovith commented on tasks/mpi/malyshev_a_simple_iteration_method/func_tests/main.cpp
> +
Deleted

2024-11-26 19:45 UTC, lolipolovkovith commented on tasks/mpi/malyshev_a_simple_iteration_method/include/matrix.hpp
> +void getRandomData(uint32_t n, std::vector<double>& A, std::vector<double>& B);
Moved

2024-11-26 19:45 UTC, lolipolovkovith commented on tasks/mpi/malyshev_a_simple_iteration_method/func_tests/main.cpp
> +    malyshev_a_simple_iteration_method_mpi::getRandomData(size, A, B);
I did not understand what shapes you are talking about if we can only have square matrices, since the system is uniquely defined by the condition. So I just added tests on different system sizes.

2024-11-26 19:46 UTC, lolipolovkovith commented on tasks/seq/malyshev_a_simple_iteration_method/perf_tests/main.cpp
> +  const int size = 300;
Increased. If the value is further increased, the pipeline testing time may exceed the maximum time limit. My validation is very complicated, calculating the determinant and the ranks of the matrices are not fast operations

2024-12-01 21:36 UTC, allnes commented on tasks/mpi/malyshev_a_simple_iteration_method/func_tests/main.cpp
> +    X[i] = random_double(50, 100);
please parametrize it

2024-12-01 21:36 UTC, allnes commented on tasks/mpi/malyshev_a_simple_iteration_method/func_tests/main.cpp
> +    A[i * n + i] = random_double(50, 100);
please paramterize it too

2024-12-01 21:38 UTC, allnes commented on tasks/mpi/malyshev_a_simple_iteration_method/func_tests/main.cpp
> +    sum_by_row_for_C = 0.01;
what is this magic constant?

2024-12-01 21:39 UTC, allnes commented on tasks/mpi/malyshev_a_simple_iteration_method/src/matrix.cpp
> +    det *= local_matrix[i][i];
please ues linear form everywhere

2024-12-01 21:39 UTC, allnes commented on tasks/mpi/malyshev_a_simple_iteration_method/src/ops_mpi.cpp
> +        C_[i][j] = -A_[i][j] / A_[i][i];
please use linear form everywhere

2024-12-02 11:16 UTC, lolipolovkovith commented on tasks/mpi/malyshev_a_simple_iteration_method/func_tests/main.cpp
> +    A[i * n + i] = random_double(50, 100);
parametrized

2024-12-02 11:16 UTC, lolipolovkovith commented on tasks/mpi/malyshev_a_simple_iteration_method/func_tests/main.cpp
> +    sum_by_row_for_C = 0.01;
I don't remember, but I fix it.

2024-12-02 11:16 UTC, lolipolovkovith commented on tasks/mpi/malyshev_a_simple_iteration_method/src/matrix.cpp
> +    det *= local_matrix[i][i];
changed

2024-12-02 11:16 UTC, lolipolovkovith commented on tasks/mpi/malyshev_a_simple_iteration_method/src/ops_mpi.cpp
> +        C_[i][j] = -A_[i][j] / A_[i][i];
changed

2024-12-02 19:35 UTC, lolipolovkovith commented
@aobolensk, now I think I increased codecov

![image](https://github.com/user-attachments/assets/6a783ae5-0985-4cbb-84d0-b93c949f24ce)

2024-12-03 16:22 UTC, aobolensk approved these changes

2024-12-03 16:22 UTC, merged