Сорокин Андрей. Задача 2. Вариант 1. Производители-потребители
learning-process/ppc-2024-autumn pull request #332
Opened 2024-11-23 15:07 UTC by AndreySorokin7

В тесте создаётся вектор значений от 1 до n, где n это число процессов производителей. В целом по условию задачи эти значения могут быть произвольные, но для удобства запишем так. После чего вектор разбивается на кусочки по одному элементу и раздаётся процессам производителям. Сам алгоритм основан на буфере состоящем из одного элемента. Туда записывается значение процессами производителями и подаётся сигнал какой именно процесс потребитель должен считать это значение. Каждый процесс делает запросы буферу с определённой периодичностью, а когда все потребители получат свои данные, то процесс прекращается. На выходе должен получиться точно такой же массив какой мы отправили на вход.

2024-11-23 17:42 UTC, ermolaevv commented on tasks/mpi/sorokin_a_producer_consumer/src/ops_mpi.cpp
> +      std::this_thread::sleep_for(std::chrono::milliseconds(2));
It seems to me that it would be more indicative if the threads fell asleep for a random time (for example, from 2 to 8 milliseconds)

2024-11-23 17:42 UTC, ermolaevv commented on tasks/mpi/sorokin_a_producer_consumer/src/ops_mpi.cpp
> +    for (unsigned int i = 0; i < count_p_; i++) reinterpret_cast<int*>(taskData->outputs[0])[i] = res_[i];
Most likely, this can be replaced with std::copy

2024-11-23 17:42 UTC, ermolaevv commented on tasks/mpi/sorokin_a_producer_consumer/src/ops_mpi.cpp
> +  return true;
Don't you need to validate something?

2024-11-23 18:55 UTC, Semyon1104 commented on tasks/mpi/sorokin_a_producer_consumer/func_tests/main.cpp
> +TEST(sorokin_a_producer_consumer_mpi, Test_Basic_x2) {
What means Test_Basic_x2?

2024-11-23 18:55 UTC, Semyon1104 commented on tasks/mpi/sorokin_a_producer_consumer/func_tests/main.cpp
> +    ASSERT_EQ(1, 1);
maybe GTEST_SKIP()?

2024-11-23 18:55 UTC, Semyon1104 commented on tasks/mpi/sorokin_a_producer_consumer/src/ops_mpi.cpp
> +    int rank_data = -1;
please delete unused variable

2024-11-23 19:30 UTC, Semyon1104 commented on tasks/mpi/sorokin_a_producer_consumer/src/ops_mpi.cpp
> +    int remaining_producers = static_cast<int>(count_p_);
please del unused var

2024-11-23 19:43 UTC, AndreySorokin7 commented on tasks/mpi/sorokin_a_producer_consumer/src/ops_mpi.cpp
> +  return true;
fixed

2024-11-23 19:44 UTC, AndreySorokin7 commented on tasks/mpi/sorokin_a_producer_consumer/src/ops_mpi.cpp
> +    for (unsigned int i = 0; i < count_p_; i++) reinterpret_cast<int*>(taskData->outputs[0])[i] = res_[i];
fixed

2024-11-23 19:44 UTC, AndreySorokin7 commented on tasks/mpi/sorokin_a_producer_consumer/src/ops_mpi.cpp
> +      std::this_thread::sleep_for(std::chrono::milliseconds(2));
fixed

2024-11-23 19:48 UTC, ermolaevv approved these changes

2024-11-23 22:01 UTC, AndreySorokin7 commented on tasks/mpi/sorokin_a_producer_consumer/func_tests/main.cpp
> +    ASSERT_EQ(1, 1);
Using GTEST_SKIP() allows you to explicitly indicate that the test was skipped due to unsatisfied conditions, and not completed successfully. Therefore, there will be problems with testing, since on the site the test will look like it has not been completed, although it cannot run on such a number of processes

2024-11-23 22:01 UTC, AndreySorokin7 commented on tasks/mpi/sorokin_a_producer_consumer/src/ops_mpi.cpp
> +    int remaining_producers = static_cast<int>(count_p_);
fixed

2024-11-23 22:01 UTC, AndreySorokin7 commented on tasks/mpi/sorokin_a_producer_consumer/func_tests/main.cpp
> +TEST(sorokin_a_producer_consumer_mpi, Test_Basic_x2) {
fixed

2024-11-24 07:37 UTC, Semyon1104 commented on tasks/mpi/sorokin_a_producer_consumer/func_tests/main.cpp
> +    ASSERT_EQ(1, 1);
Ok

2024-11-24 07:38 UTC, Semyon1104 approved these changes

2024-11-26 00:06 UTC, aobolensk requested changes

2024-11-26 00:06 UTC, aobolensk commented on tasks/mpi/sorokin_a_producer_consumer/func_tests/main.cpp
> +  if (world.size() < 3) {
Please, support the case with 2 processes

2024-11-26 00:31 UTC, AndreySorokin7 commented on tasks/mpi/sorokin_a_producer_consumer/func_tests/main.cpp
> +  if (world.size() < 3) {
My algorithm is written so that the null process is only a buffer and it does not apply to any producer or consumer. Accordingly, it makes no sense to run on two or less from the fact that validation will drop there at least, and at most nothing will start since no one will accept the information. Is it necessary for the null process to be more than just a buffer?

2024-12-01 21:41 UTC, allnes commented on tasks/mpi/sorokin_a_producer_consumer/src/ops_mpi.cpp
> +    std::this_thread::sleep_for(std::chrono::milliseconds(5));
please parametrize it in tests

2024-12-01 21:41 UTC, allnes commented on tasks/mpi/sorokin_a_producer_consumer/src/ops_mpi.cpp
> +      const double upper_bound = 6;
please parametrize it in tests

2024-12-01 21:42 UTC, allnes commented on tasks/mpi/sorokin_a_producer_consumer/src/ops_mpi.cpp
> +      const double upper_bound = 6;
please parametrize it in tests

2024-12-02 00:07 UTC, AndreySorokin7 commented on tasks/mpi/sorokin_a_producer_consumer/src/ops_mpi.cpp
> +    std::this_thread::sleep_for(std::chrono::milliseconds(5));
fixed)

2024-12-02 00:07 UTC, AndreySorokin7 commented on tasks/mpi/sorokin_a_producer_consumer/src/ops_mpi.cpp
> +      const double upper_bound = 6;
fixed

2024-12-02 00:07 UTC, AndreySorokin7 commented on tasks/mpi/sorokin_a_producer_consumer/src/ops_mpi.cpp
> +      const double upper_bound = 6;
fixed

2024-12-02 22:37 UTC, allnes approved these changes

2024-12-03 13:53 UTC, aobolensk approved these changes

2024-12-03 13:54 UTC, merged