Борисов Сергей. Задача 2. Вариант 5. Передача от одного всем (broadcast)
learning-process/ppc-2024-autumn pull request #333
Opened 2024-11-23 15:15 UTC by SergeyBoRss

Реализован алгоритм broadcast с использованием тернарного дерева

В задаче вычисления матрицы расстояний (между всеми точками), broadcast используется для:

1. Передачи количества точек (points_count) всем процессам
2. Передачи массива координат точек (points_) от корневого процесса остальным

Реализация тернарного дерева позволяет минимизировать глубину передачи и ускорить процесс распределения данных

2024-11-23 16:14 UTC, VladislavPoroshin commented on tasks/mpi/borisov_s_broadcast/src/ops_mpi.cpp
> +  size_t points_size = static_cast<size_t>(points_count) * 2;
for all such transformations it is worth adding checks

2024-11-23 16:14 UTC, VladislavPoroshin commented on tasks/mpi/borisov_s_broadcast/src/ops_mpi.cpp
> +  int broadcast_size = static_cast<int>(points_size);
for all such transformations it is worth adding checks

2024-11-23 16:14 UTC, VladislavPoroshin commented on tasks/mpi/borisov_s_my_broadcast/src/ops_mpi.cpp
> +  size_t points_size = static_cast<size_t>(points_count) * 2;
for all such transformations it is worth adding checks

2024-11-23 16:14 UTC, VladislavPoroshin commented on tasks/mpi/borisov_s_my_broadcast/src/ops_mpi.cpp
> +  int broadcast_size = static_cast<int>(points_size);
for all such transformations it is worth adding checks

2024-11-23 16:14 UTC, VladislavPoroshin commented on tasks/mpi/borisov_s_my_broadcast/src/ops_mpi.cpp
> +  // std::cout << world.rank() << " a " << base_size << " " << remainder << std::endl;
delete this please

2024-11-23 16:14 UTC, VladislavPoroshin commented on tasks/mpi/borisov_s_my_broadcast/src/ops_mpi.cpp
> +  // std::cout << world.rank() << " " << local_start << " " << local_end << std::endl;
delete this please

2024-11-23 16:16 UTC, KorotinEgor commented on tasks/mpi/borisov_s_broadcast/func_tests/main.cpp
> +#include <boost/mpi/environment.hpp>
Extra include

2024-11-23 16:16 UTC, KorotinEgor commented on tasks/mpi/borisov_s_my_broadcast/func_tests/main.cpp
> +#include <boost/mpi/environment.hpp>
Extra include

2024-11-23 16:16 UTC, KorotinEgor commented on tasks/mpi/borisov_s_broadcast/include/ops_mpi.hpp
> +// Copyright 2023 Nesterov Alexander
Delete comments

2024-11-23 16:16 UTC, KorotinEgor commented on tasks/mpi/borisov_s_my_broadcast/include/ops_mpi.hpp
> +// Copyright 2023 Nesterov Alexander
Delete comments

2024-11-23 16:16 UTC, KorotinEgor commented on tasks/mpi/borisov_s_broadcast/src/ops_mpi.cpp
> +#include <functional>
Extra include

2024-11-23 16:16 UTC, KorotinEgor commented on tasks/mpi/borisov_s_broadcast/src/ops_mpi.cpp
> +#include <thread>
Extra includes

2024-11-23 16:16 UTC, KorotinEgor commented on tasks/mpi/borisov_s_my_broadcast/src/ops_mpi.cpp
> +#include <thread>
Extra includes

2024-11-23 16:16 UTC, KorotinEgor commented on tasks/mpi/borisov_s_my_broadcast/src/ops_mpi.cpp
> +#include <functional>
Extra include

2024-11-23 17:27 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_broadcast/src/ops_mpi.cpp
> +  int broadcast_size = static_cast<int>(points_size);
Fixed

2024-11-23 17:27 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_my_broadcast/src/ops_mpi.cpp
> +  int broadcast_size = static_cast<int>(points_size);
Fixed

2024-11-23 17:27 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_my_broadcast/src/ops_mpi.cpp
> +  // std::cout << world.rank() << " a " << base_size << " " << remainder << std::endl;
Fixed

2024-11-23 17:27 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_my_broadcast/src/ops_mpi.cpp
> +  // std::cout << world.rank() << " " << local_start << " " << local_end << std::endl;
Fixed

2024-11-23 17:27 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_broadcast/func_tests/main.cpp
> +#include <boost/mpi/environment.hpp>
Fixed

2024-11-23 17:27 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_my_broadcast/func_tests/main.cpp
> +#include <boost/mpi/environment.hpp>
Fixed

2024-11-23 17:27 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_broadcast/include/ops_mpi.hpp
> +// Copyright 2023 Nesterov Alexander
Fixed

2024-11-23 17:27 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_my_broadcast/include/ops_mpi.hpp
> +// Copyright 2023 Nesterov Alexander
Fixed

2024-11-23 17:27 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_broadcast/src/ops_mpi.cpp
> +#include <functional>
Fixed

2024-11-23 17:28 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_broadcast/src/ops_mpi.cpp
> +#include <thread>
Fixed

2024-11-23 17:28 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_my_broadcast/src/ops_mpi.cpp
> +#include <thread>
Fixed

2024-11-23 17:28 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_my_broadcast/src/ops_mpi.cpp
> +#include <functional>
Fixed

2024-11-23 17:29 UTC, VladislavPoroshin approved these changes

2024-11-23 17:29 UTC, KorotinEgor approved these changes

2024-11-26 00:53 UTC, aobolensk requested changes

2024-11-26 00:53 UTC, aobolensk commented on tasks/mpi/borisov_s_broadcast/include/ops_mpi.hpp
> +std::vector<double> getRandomPoints(int count);
Please, move test functions to the test module

2024-11-26 00:53 UTC, aobolensk commented
What task is being solved using your broadcast implementation?

2024-11-26 03:42 UTC, SergeyBoRss commented
> What task is being solved using your broadcast implementation?

The calculation of the distance matrix, in particular for sending an array and a number of points

2024-11-26 04:19 UTC, closed without merging