Куракин Матвей. Задача 3. Вариант 24. Построение выпуклой оболочки – проход Грэхема
learning-process/ppc-2024-autumn pull request #334
Opened 2024-11-23 19:29 UTC by MatveyKurakin

Последовательная реализация
- Среди точек находим самую правую и нижнюю, она будет начальной
- Сортируем оставшиеся точки по углу относительно начальной
- Проходим по точкам, если поворот левый - добавляем в оболочку, если правый - удаляем последние добавленные точки, чтобы получился левый поворот
- В результате получаем последовательность - оболочку

Параллельная реализация
- Каждый процесс получает минимум по 3 точки, если так сделать нельзя, то последние процессы не получат точек
- Каждый процесс выполняет последовательный алгоритм для своих точек
- Все процессы передают свои оболочки нулевому процессу
- Нулевой процесс выполняет последовательный алгоритм для полученных точек
- В результате получаем последовательность - оболочку

2024-11-24 15:03 UTC, venn2713 requested changes

2024-11-24 15:03 UTC, venn2713 commented on tasks/mpi/kurakin_m_graham_scan_ops_mpi/src/kurakin_graham_scan_ops_mpi.cpp
> +  }
It seems to be preprocessing

2024-11-24 15:03 UTC, venn2713 commented on tasks/mpi/kurakin_m_graham_scan_ops_mpi/src/kurakin_graham_scan_ops_mpi.cpp
> +  }
I'm not sure, but it looks like a task for scatterv

2024-12-01 21:44 UTC, allnes commented on tasks/mpi/kurakin_m_graham_scan_ops_mpi/func_tests/kurakin_graham_scan.cpp
> +    count_point = 4;
please use different sizes and use more prime and 2^n, 10^n values

2024-12-01 21:47 UTC, allnes commented on tasks/mpi/kurakin_m_graham_scan_ops_mpi/src/kurakin_graham_scan_ops_mpi.cpp
> +    }
please use linear form where values has scheme {x0, y0, x1, y1 ...} or {x0, x1, x2,....,y0, y1, y2, .....}

2024-12-13 16:00 UTC, allnes approved these changes

2024-12-14 08:05 UTC, MatveyKurakin commented on tasks/mpi/kurakin_m_graham_scan_ops_mpi/src/kurakin_graham_scan_ops_mpi.cpp
> +  }
I agree, it's better to use scatter here, but with a small count of points, some of the processes will have to send an empty vector, I couldn't do it through scatterv and I couldn't come up with a beautiful solution, so I used send and recv

2024-12-14 08:07 UTC, MatveyKurakin commented on tasks/mpi/kurakin_m_graham_scan_ops_mpi/src/kurakin_graham_scan_ops_mpi.cpp
> +  }
fixed

2024-12-14 08:07 UTC, MatveyKurakin commented on tasks/mpi/kurakin_m_graham_scan_ops_mpi/src/kurakin_graham_scan_ops_mpi.cpp
> +  }
fixed

2024-12-14 09:32 UTC, MatveyKurakin commented on tasks/mpi/kurakin_m_graham_scan_ops_mpi/include/kurakin_graham_scan_ops_mpi.hpp
> +void getRandomVectorForGrahamScan(std::vector<double>& res_x, std::vector<double>& res_y, int count_point, int size);
fixed

2024-12-14 09:32 UTC, MatveyKurakin commented on tasks/mpi/kurakin_m_graham_scan_ops_mpi/src/kurakin_graham_scan_ops_mpi.cpp
> +using namespace std::chrono_literals;
fixed

2024-12-14 10:02 UTC, KolodkinGrigorii approved these changes

2024-12-15 12:45 UTC, aobolensk approved these changes

2024-12-15 12:46 UTC, merged