Титов Семён. Задача 2. Вариант 24. Метод простых итераций
learning-process/ppc-2024-autumn pull request #335
Opened 2024-11-23 20:51 UTC by Semyon1104

* ### Описание последовательной задачи: 
На вход подается матрица системы линейных уравнений, преобразуется к виду x = cx + d. Далее, начиная с точки 0 высчитываются последовательные приближения значений переменных системы уравнений. Для этого нужны 2 массива с текущими значениями и предыдущими. Процесс идет до тех пор пока максимальная разница между текущими значениями переменной и прошлыми значениями не будут меньше заданного epsilon.

* ### Описание параллельной задачи: 
На вход для удобства подается матрица A и вектор B, где СЛАУ имеет вид Ax=B, (здесь мы не преобразовываем матрицу заранее, а немного меняем вычисления новых значений). Каждой процессу выделена одна строка, если процессов меньше, то каждому процессу соответствует кратное количество строк, последний процесс забирает все оставшиеся. Если процессов выделено больше, часть из них бездействует. После подсчета очередным процессом очередного приближения переменной данные массив текущих значений x обновляется у всех процессов, по окончании итерации всеми процессами, массив с текущими значениями копируется в массив с прошлыми значениями, процесс продолжается пока в главном процессе не пройдет проверка на сходимость к epsilon.

2024-11-23 21:28 UTC, AndreySorokin7 requested changes

2024-11-23 21:28 UTC, AndreySorokin7 commented on tasks/mpi/titov_s_simple_iteration/src/ops_mpi.cpp
> +    current.assign(Rows, 0.0);
there must be a condition under which the solution of the equation converges to an exact solution from any point, in your case from point zero

2024-11-24 08:01 UTC, Semyon1104 commented on tasks/mpi/titov_s_simple_iteration/src/ops_mpi.cpp
> +    current.assign(Rows, 0.0);
fixed

2024-11-24 08:14 UTC, Kitos87 commented on tasks/mpi/titov_s_simple_iteration/func_tests/main.cpp
Please, add more functional tests for matrix of type 1x1, 2x2, and also don't forget to check the empty matrix

2024-11-27 15:27 UTC, Kitos87 approved these changes

2024-11-27 18:52 UTC, AndreySorokin7 approved these changes

2024-12-01 21:49 UTC, allnes commented on tasks/mpi/titov_s_simple_iteration/src/ops_mpi.cpp
> +bool titov_s_simple_iteration_mpi::MPISimpleIterationSequential::validation() {
Diagonal dominance is needed for convergence of the method, but where is the verification of a single solution of system linear algebraic equations?

2024-12-01 21:50 UTC, allnes commented on tasks/mpi/titov_s_simple_iteration/src/ops_mpi.cpp
> +  }
its validation

2024-12-01 21:50 UTC, allnes commented on tasks/mpi/titov_s_simple_iteration/src/ops_mpi.cpp
> +  transformMatrix();
its run()

2024-12-02 22:38 UTC, allnes commented on tasks/mpi/titov_s_simple_iteration/src/ops_mpi.cpp
>  using namespace std::chrono_literals;
please remove it

2024-12-02 22:38 UTC, allnes commented on tasks/seq/titov_s_simple_iteration/src/ops_seq.cpp
> +using namespace std::chrono_literals;
please remove it

2024-12-03 08:07 UTC, Semyon1104 commented on tasks/seq/titov_s_simple_iteration/src/ops_seq.cpp
> +using namespace std::chrono_literals;
ready

2024-12-03 08:07 UTC, Semyon1104 commented on tasks/mpi/titov_s_simple_iteration/src/ops_mpi.cpp
>  using namespace std::chrono_literals;
ready

2024-12-05 23:33 UTC, allnes approved these changes

2024-12-07 17:31 UTC, aobolensk approved these changes

2024-12-07 17:32 UTC, merged