Смирнов Илья. Задача 2. Вариант 17. Ленточная горизонатльная схема - разбиение только матрицы А.
learning-process/ppc-2024-autumn pull request #337
Opened 2024-11-23 21:27 UTC by IljarSmirnov

seq:
mpi:

2024-11-24 12:34 UTC, Vav1L0N commented on tasks/mpi/smirnov_i_tape_splitting_A/src/ops_mpi.cpp
> +    n_b = taskData->inputs_count[3];
You have this lines in validation

2024-11-24 12:34 UTC, Vav1L0N commented on tasks/seq/smirnov_i_tape_splitting_A/src/ops_seq.cpp
> +  n_b = taskData->inputs_count[3];
You have this lines in validation

2024-11-24 13:01 UTC, KorotinEgor reviewed
Everything else looks good

2024-11-24 14:40 UTC, IljarSmirnov commented on tasks/seq/smirnov_i_tape_splitting_A/src/ops_seq.cpp
> +  }
fixed

2024-11-24 14:40 UTC, IljarSmirnov commented on tasks/mpi/smirnov_i_tape_splitting_A/include/ops_mpi.hpp
> +  }
fixed

2024-11-24 14:40 UTC, IljarSmirnov commented on tasks/seq/smirnov_i_tape_splitting_A/include/ops_seq.hpp
> +  }
fixed

2024-11-24 14:40 UTC, IljarSmirnov commented on tasks/mpi/smirnov_i_tape_splitting_A/src/ops_mpi.cpp
> +  n_b = taskData->inputs_count[3];
fixed

2024-11-24 14:40 UTC, IljarSmirnov commented on tasks/seq/smirnov_i_tape_splitting_A/src/ops_seq.cpp
> +  n_b = taskData->inputs_count[3];
fixed

2024-11-24 14:44 UTC, KorotinEgor approved these changes

2024-11-24 14:44 UTC, Vav1L0N approved these changes

2024-11-26 01:23 UTC, aobolensk requested changes

2024-11-26 01:23 UTC, aobolensk commented on tasks/mpi/smirnov_i_tape_splitting_A/func_tests/main.cpp
> +  std::uniform_int_distribution<> distrib(1, 100);
Please add negative numbers tests

2024-11-26 01:23 UTC, aobolensk commented on tasks/mpi/smirnov_i_tape_splitting_A/include/ops_mpi.hpp
> +void get_random_matrix(double* matr, int size);
Please, move test functions to the test module

2024-11-26 01:23 UTC, aobolensk commented on tasks/seq/smirnov_i_tape_splitting_A/src/ops_seq.cpp
> +    tmp_ptr[i] = res[i];
std::copy

2024-11-26 01:23 UTC, aobolensk commented on tasks/mpi/smirnov_i_tape_splitting_A/src/ops_mpi.cpp
> +      A[i] = tmp_ptr_a[i];
also std::copy

2024-11-26 16:01 UTC, IljarSmirnov commented on tasks/mpi/smirnov_i_tape_splitting_A/func_tests/main.cpp
> +  std::uniform_int_distribution<> distrib(1, 100);
added

2024-11-26 16:01 UTC, IljarSmirnov commented on tasks/mpi/smirnov_i_tape_splitting_A/include/ops_mpi.hpp
> +void get_random_matrix(double* matr, int size);
fixed

2024-11-26 16:01 UTC, IljarSmirnov commented on tasks/seq/smirnov_i_tape_splitting_A/src/ops_seq.cpp
> +    tmp_ptr[i] = res[i];
fixed

2024-11-26 16:01 UTC, IljarSmirnov commented on tasks/mpi/smirnov_i_tape_splitting_A/src/ops_mpi.cpp
> +      A[i] = tmp_ptr_a[i];
fixed

2024-12-01 21:54 UTC, allnes commented on tasks/mpi/smirnov_i_tape_splitting_A/func_tests/main.cpp
> +  int n_b = 3;
please check, (1, 1, 1, 1) it needs to work

2024-12-02 07:44 UTC, IljarSmirnov commented on tasks/mpi/smirnov_i_tape_splitting_A/func_tests/main.cpp
> +  int n_b = 3;
Added

2024-12-02 22:40 UTC, allnes approved these changes

2024-12-03 16:20 UTC, aobolensk approved these changes

2024-12-03 16:21 UTC, merged