Милованкин Максим. Задача 2. Вариант 14. Топология Гиперкуб.
learning-process/ppc-2024-autumn pull request #338
Opened 2024-11-24 11:02 UTC by lizardwizardd

**_Параллельная задача_**
- Начальный процесс получает данные в виде структуры `DataIn`, вычисляет следующий процесс в пути, добавляет его в `route` и отправляет данные ему. 
- Все остальные процессы вызывают `recv`.
- Промежуточные процессы принимают данные, записывают ID следующего процесса в `route` и отправляют данные дальше.
- Следующий процесс вычисляется переворачивая 1 бит, чтобы он совпал с битом в ID цели.
- Последний процесс после получения данных отправляет их обратно в начальный процесс, чтобы корректно завершить работу неиспользованных процессов и записать результаты в `TaskData`.
- Начальный процесс проходит по `route` и отправляет сигнал завершения процессам, которых в нем нет.

2024-11-26 11:44 UTC, Sean0450 requested changes

2024-11-26 11:44 UTC, Sean0450 commented on tasks/mpi/milovankin_m_hypercube_topology/func_tests/main.cpp
> +
Add functional tests for failed validation and for same source and destination processes

2024-11-26 20:44 UTC, lizardwizardd commented on tasks/mpi/milovankin_m_hypercube_topology/func_tests/main.cpp
> +
done

2024-11-27 00:34 UTC, kmichaelk commented on tasks/mpi/milovankin_m_hypercube_topology/func_tests/main.cpp
> +  expect = {0, 2, 6, 14};  // 0000 -> 0010 -> 0110 -> 1110
```suggestion
  expect = {0b0000, 0b0010, 0b0110, 0b1110};
```

2024-11-27 15:22 UTC, Egor1dzeN-learn requested changes

2024-11-27 15:22 UTC, Egor1dzeN-learn commented on tasks/mpi/milovankin_m_hypercube_topology/src/ops_mpi.cpp
> +    if (data_.destination == 0) {
You can also check if destination is not lower than 0 and not higher than processor count

2024-11-27 15:46 UTC, lizardwizardd commented on tasks/mpi/milovankin_m_hypercube_topology/src/ops_mpi.cpp
> +    if (data_.destination == 0) {
done

2024-11-27 15:51 UTC, Egor1dzeN-learn approved these changes

2024-11-27 18:07 UTC, Sean0450 approved these changes

2024-12-01 21:57 UTC, allnes commented on tasks/mpi/milovankin_m_hypercube_topology/func_tests/main.cpp
> +  if (world.rank() != 0) return;
please handle it with help differnet methods

2024-12-02 00:02 UTC, lizardwizardd commented on tasks/mpi/milovankin_m_hypercube_topology/func_tests/main.cpp
> +  if (world.rank() != 0) return;
fixed

2024-12-02 22:41 UTC, allnes approved these changes

2024-12-03 16:21 UTC, aobolensk approved these changes

2024-12-03 16:23 UTC, merged