‎Рамс Сергей. Задача 2. Вариант 19. Метод Гаусса – ленточная горизонтальная схема
learning-process/ppc-2024-autumn pull request #339
Opened 2024-11-24 11:18 UTC by 22380240

Описание последовательной задачи:
Входные данные: матрица m*n, число переменных.
1) Прямой ход: перемещение первой строки с минимальным индексом первого ненулевого коэффициента на первое место; из каждого коэффициента каждой нижестоящей строки вычитается произведение соотвествующего коэффициента опорной строки и отношения ведущего коэффициента текущей строки и ведущего коэффициента опорной строки; в конце матрица оказывается приведенной к треугольной форме
2) Обратный ход: начиная с последней строки, можно узнать значение неизвестной переменной вычитанием из свободного члена суммы произведений всех известных (нижестоящих) переменных на соответствующие им коэффициенты из текущей строки
Выходные данные: список полученных значений переменных.

Описание параллельной задачи:
При прямом ходе строки матрицы равномерно распределяются между процессами для параллельного выполнения деления коэффициентов строки на коэффициенты опорной строки. При обратном ходе распарраллеливание по строкам невозможно, так как для произведения вычислений над строкой необходим результат вычислений предыдущей строки.

2024-11-24 12:51 UTC, MoiseevArt requested changes

2024-11-24 12:51 UTC, MoiseevArt commented on tasks/mpi/rams_s_gaussian_elimination_horizontally/src/ops_mpi.cpp
> +      double *current_row_start = matrix.data() + virtual_to_physical_row_idx[current_row] * cols_count;
```suggestion
      double *current_row_start = &matrix[virtual_to_physical_row_idx[current_row] * cols_count];
```

2024-11-24 13:17 UTC, kmichaelk commented on tasks/mpi/rams_s_gaussian_elimination_horizontally/src/ops_mpi.cpp
> +      std::copy(current_row_start, current_row_start + cols_count, local_current_row.data());
```suggestion
      auto current_row_start = matrix.begin() + virtual_to_physical_row_idx[current_row] * cols_count;
      std::copy(current_row_start, current_row_start + cols_count, local_current_row.data());
```

2024-11-24 13:47 UTC, kmichaelk commented on tasks/mpi/rams_s_gaussian_elimination_horizontally/src/ops_mpi.cpp
> +    auto get_local_item = [&](int row, int col) { return *get_local_item_ptr(row, col); };
```suggestion
    auto get_local_item = [&](int row, int col) -> int& {
      return local_matrix[row * cols_count + col - displs[world.rank()]];
    };
```

2024-11-24 13:47 UTC, kmichaelk commented on tasks/mpi/rams_s_gaussian_elimination_horizontally/src/ops_mpi.cpp
> +          *get_local_item_ptr(row, col) -= local_current_row[col] * ratio;
```suggestion
          get_local_item(row, col) -= local_current_row[col] * ratio;
```

2024-11-24 14:39 UTC, kmichaelk approved these changes

2024-11-24 15:17 UTC, MoiseevArt approved these changes

2024-11-26 01:25 UTC, aobolensk approved these changes

2024-12-01 21:59 UTC, allnes commented on tasks/mpi/rams_s_gaussian_elimination_horizontally/src/ops_mpi.cpp
> +}
where are checks of exist single soultion?

2024-12-05 23:39 UTC, allnes commented on tasks/mpi/rams_s_gaussian_elimination_horizontally/src/ops_mpi.cpp
> +}
1) для нахождени ранка используется, например, модифицированны метод Гаусса - http://e-maxx.ru/algo/matrix_rank
2) это требуется для того чтобы в производительности не было случаев nan, пересчитывание производительности увы не поддерживается

2024-12-06 08:05 UTC, 22380240 commented on tasks/mpi/rams_s_gaussian_elimination_horizontally/src/ops_mpi.cpp
> +}
Понятно, спасибо. Я добавил проверку: https://github.com/learning-process/ppc-2024-autumn/pull/339/commits/16ebfc8cdd6ed0dc5a419ac646282e8bf82b5761

2024-12-08 11:06 UTC, allnes approved these changes

2024-12-08 11:06 UTC, merged