Лупша Егор. Задача №1. Вариант №19. Интегрирование методом прямоугольников.
learning-process/ppc-2024-autumn pull request #34
Opened 2024-10-23 13:32 UTC by desiigner0

Интегрирование методом прямоугольников заключается в аппроксимации площади под кривой, используя прямоугольники.

**Описание последовательной задачи (SEQ):**
Отрезок **[lower_bound, upper_bound]** делим на **n**-интервалов, каждый шириной **(upper_bound - lower_bound) / n**
Для каждого интервала вычисляем значение функции **f(x)** на левой границе интервала и добавляем к общей сумме, которая умножается на ширину интервала.

**Описание параллельной задачи (MPI):**
Используется тот же алгоритм метода левых прямоугольников, как и в последовательной версии, только в этом случае:

- C помощью MPI_Bcast распределяем данные (границы интегрирования и количество интервалов) между всеми процессами.
- Распределяем интервалы между процессами. Если невозможно одинаково распределить все интервалы, то процессы получат дополнительные.
- Каждый процесс вычисляет свою долю интеграла, используя метод левых прямоугольников, и суммирует результаты.
- Процесс с рангом 0 записывает окончательный результат.

2024-10-27 09:23 UTC, allnes commented on tasks/mpi/example/func_tests/main.cpp
> -}
please don't change not own files

2024-10-27 14:50 UTC, aobolensk requested changes

2024-10-27 14:50 UTC, aobolensk commented on tasks/seq/lupsha_e_rect_integration/perf_tests/main.cpp
> +TEST(lupsha_e_rect_integration_seq, test_pipeline_run) {
Please, add random tests

2024-11-03 14:09 UTC, desiigner0 commented on tasks/mpi/example/func_tests/main.cpp
> -}
returned the original file

2024-11-03 23:46 UTC, aobolensk requested changes

2024-11-03 23:46 UTC, aobolensk commented on tasks/mpi/example/src/ops_mpi.cpp
> -  std::this_thread::sleep_for(20ms);
Please do not modify common code

2024-11-04 13:17 UTC, aobolensk approved these changes

2024-11-08 00:16 UTC, DSolo03 requested changes

2024-11-08 00:16 UTC, DSolo03 commented on tasks/mpi/lupsha_e_rect_integration/func_tests/main.cpp
> +}
please, put this function under your namespace like this:
`namespace <namespace name>{<this function>}`

2024-11-08 00:39 UTC, DSolo03 requested changes

2024-11-08 00:39 UTC, DSolo03 commented on tasks/mpi/lupsha_e_rect_integration/src/ops_mpi.cpp
> +  }
in MPI, all validation should be in 0th process

2024-12-29 19:35 UTC, merged