Кошкин Никита. Задача 2. Вариант 2. Читатели-Писатели.
learning-process/ppc-2024-autumn pull request #345
Opened 2024-11-25 21:11 UTC by NikitaKoshkin

Реализована первая проблема читателей–писателей из статьи wiki (readers-preference).

Процесс с ранком 0 - он же главный процесс, управляет доступом к общему ресурсу через два семафора:
resource: блокирует общий ресурс (чтение или запись).
rmutex: синхронизирует доступ к счётчику readcount.
Обрабатывает запросы от читателей и писателей, отправляя подтверждения (proceed или wait).
Остальные процессы являются либо писателями, либо читателями.

Читатели:
Отправляют запрос на вход (read_entry) и выход (read_exit) из критической секции.
Первый читатель блокирует ресурс для писателей, а последний освобождает его. 
Читатели могут одновременно читать ресурс.

Писатели:

Отправляют запрос на вход (read_entry) и выход (read_exit) из критической секции.
Блокируют ресурс, выполняют запись, затем освобождают его. 
Писатели получают доступ только при отсутствии читателей.
Для наглядности работы, структурой хранения выбран вектор, писатели по очередности записывают в него простое изменение, в конце главный процесс обновляет данные.

2024-11-26 12:09 UTC, Napkin-AI requested changes

2024-11-26 12:09 UTC, Napkin-AI commented on tasks/mpi/koshkin_n_readers_writers/src/ops_mpi.cpp
> +      output[i] = res[i];
std::copy

2024-11-26 12:09 UTC, Napkin-AI commented on tasks/mpi/koshkin_n_readers_writers/func_tests/main.cpp
> +#include <gtest/gtest.h>
Please, add the tests with size 16, 32

2024-11-26 16:03 UTC, EgorDormidontov commented on tasks/mpi/koshkin_n_readers_writers/src/ops_mpi.cpp
> +  for (int i = 0; i < sz; i++) {
Add negatives

2024-11-26 18:42 UTC, Napkin-AI commented on tasks/mpi/koshkin_n_readers_writers/src/ops_mpi.cpp
> +    } else if (role == "reader") {
>

2024-11-26 18:55 UTC, Napkin-AI approved these changes

2024-12-01 22:13 UTC, allnes commented on tasks/mpi/koshkin_n_readers_writers/func_tests/main.cpp
> +    ASSERT_TRUE(true);
please use GTEST_SKIP()

2024-12-01 22:14 UTC, allnes commented on tasks/mpi/koshkin_n_readers_writers/perf_tests/main.cpp
> +    ASSERT_TRUE(true);
please use GTEST_SKIP()

2024-12-02 17:51 UTC, NikitaKoshkin commented on tasks/mpi/koshkin_n_readers_writers/func_tests/main.cpp
> +    ASSERT_TRUE(true);
done

2024-12-02 17:51 UTC, NikitaKoshkin commented on tasks/mpi/koshkin_n_readers_writers/perf_tests/main.cpp
> +    ASSERT_TRUE(true);
done

2024-12-02 22:51 UTC, allnes approved these changes

2024-12-03 16:51 UTC, aobolensk approved these changes

2024-12-03 16:51 UTC, merged