Сорочкин Данила. Задача 2. Вариант 11. Топология сетей передачи данных - кольцо.
learning-process/ppc-2024-autumn pull request #349
Opened 2024-11-25 22:24 UTC by dssss12

Алгоритм реализует обработку данных в сети с топологией кольца через несколько этапов. На этапе `pre_processing` главный процесс извлекает данные из входного буфера и сохраняет их в локальный буфер. Функция `validation` проверяет корректность входных данных. На этапе `run` данные передаются между процессами по кольцу: каждый процесс получает данные от предшественника и отправляет следующему, с учетом границ кольца. На этапе `post_processing` главный процесс собирает обработанные данные в выходной буфер.

2024-11-27 16:34 UTC, flashkasi approved these changes

2024-11-28 19:38 UTC, dssss12 commented on tasks/mpi/sorochkin_d_ring_topology/func_tests/main.cpp
> +
added

2024-11-28 19:42 UTC, KoshkinMatvey approved these changes
all right guy

2024-11-30 00:41 UTC, aortemon requested changes

2024-11-30 00:41 UTC, aortemon commented on tasks/mpi/sorochkin_d_ring_topology/func_tests/main.cpp
> +    const int count_size_vector = 120;
In previous test count_size_vector is 120 too, it's a typo, please, correct this

2024-11-30 12:51 UTC, aortemon approved these changes

2024-12-01 22:16 UTC, allnes commented on tasks/mpi/sorochkin_d_ring_topology/func_tests/main.cpp
> +    vec[i] = gen() % 100;
please use negative values

2024-12-01 22:17 UTC, allnes commented on tasks/mpi/sorochkin_d_ring_topology/func_tests/main.cpp
> +    input = sorochkin_d_ring_topology_mpi_test::getRandomVector(count_size_vector);
please check prime values and 2^n values

2024-12-03 17:01 UTC, aobolensk approved these changes

2024-12-04 11:05 UTC, dssss12 commented on tasks/mpi/sorochkin_d_ring_topology/func_tests/main.cpp
> +    vec[i] = gen() % 100;
Fixed

2024-12-04 11:05 UTC, dssss12 commented on tasks/mpi/sorochkin_d_ring_topology/func_tests/main.cpp
> +    input = sorochkin_d_ring_topology_mpi_test::getRandomVector(count_size_vector);
Added

2024-12-05 23:45 UTC, allnes approved these changes

2024-12-05 23:46 UTC, merged