Пикарычев Илья. Задача 2. Вариант 4. Задача "Спящий брадобрей"
learning-process/ppc-2024-autumn pull request #350
Opened 2024-11-25 22:33 UTC by flashkasi

Проблема спящего брадобрея — классическая задача синхронизации и межпроцессного взаимодействия interprocess communication в многозадачной операционной системе. Проблема заключается в обеспечении того, чтобы парикмахер работал, когда есть клиенты, и отдыхал, когда клиентов нет. 

  В силу отсутствия в MPI разделяемой памяти для координации брадобрея и клиентов используется отдельный процесс. Он отрабатывает N итераций для получения данных, после чего сообщает остальным процессам специальный код, вызывающий их завершение.

2024-12-01 19:51 UTC, KoshkinMatvey approved these changes

2024-12-01 22:18 UTC, allnes commented on modules/core/perf/src/perf.cpp
> -  if (time_secs > PerfResults::MIN_TIME && time_secs < PerfResults::MAX_TIME) {
please don't change not own files

2024-12-01 22:19 UTC, allnes commented on tasks/mpi/pikarychev_i_sleeping_barber/src/ops_mpi.cpp
> +  return world.size() > 2 && (world.rank() != 0 || (taskData->inputs.size() == 1 && taskData->inputs_count[0] == 1));
why `world.rank() != 0 ` is false for validation?

2024-12-01 22:20 UTC, allnes commented on tasks/mpi/pikarychev_i_sleeping_barber/func_tests/main.cpp
> +TEST(pikarychev_i_sleeping_barber_mpi_test, test_10) { test(10); }
please use more values, prime values, 2^n, 10^n

2024-12-04 21:46 UTC, flashkasi commented on tasks/mpi/pikarychev_i_sleeping_barber/func_tests/main.cpp
> +TEST(pikarychev_i_sleeping_barber_mpi_test, test_10) { test(10); }
added

2024-12-04 21:47 UTC, flashkasi commented on tasks/mpi/pikarychev_i_sleeping_barber/src/ops_mpi.cpp
> +  return world.size() > 2 && (world.rank() != 0 || (taskData->inputs.size() == 1 && taskData->inputs_count[0] == 1));
You read it wrong, it returns true

2024-12-05 23:48 UTC, allnes commented on tasks/mpi/pikarychev_i_sleeping_barber/src/ops_mpi.cpp
> +  return world.size() > 2 && (world.rank() != 0 || (taskData->inputs.size() == 1 && taskData->inputs_count[0] == 1));
sorry for my wrong question, I don't understand idea, barber can work without client? why not `world.rank() > 1`

2024-12-06 00:02 UTC, aortemon approved these changes
Looks well, I have no idea what can be changed here

2024-12-06 09:35 UTC, flashkasi commented on tasks/mpi/pikarychev_i_sleeping_barber/src/ops_mpi.cpp
> +  return world.size() > 2 && (world.rank() != 0 || (taskData->inputs.size() == 1 && taskData->inputs_count[0] == 1));
For the simulation to work, a coordinating process is needed to organize the queue, because the barber itself is running another event loop and cannot respond to these requests in a timely manner (compared to the implementations on shared memory where coordinator is not needed).

So we validate it this way: there should be 2 processes at least - queue coordinator and the barber, if we have access to task data, we verify that there's capacity parameter, if we don't have access to the task data, we pass validation. 

As there's no other way to test that the simulation works correctly, I supplied the code with print statements, you can see in the logs that it works well.

2024-12-06 13:34 UTC, Ivan-Lysov commented on tasks/mpi/pikarychev_i_sleeping_barber/src/ops_mpi.cpp
> +              printf("Coordinator: drop %d\n", src);
Please remove the printf. I understand that you needed this for debugging, but there is no need for this in the wizard

2024-12-07 15:25 UTC, Ivan-Lysov approved these changes

2024-12-07 16:41 UTC, flashkasi commented on modules/core/perf/src/perf.cpp
> -  if (time_secs > PerfResults::MIN_TIME && time_secs < PerfResults::MAX_TIME) {
Okay

2024-12-07 17:29 UTC, aobolensk requested changes

2024-12-07 17:29 UTC, aobolensk commented on tasks/mpi/pikarychev_i_sleeping_barber/func_tests/main.cpp
> +  if (!testMpiTaskParallel.validation()) {
Please, add test where validation is checked to be "false" and not ignored

2024-12-07 17:29 UTC, aobolensk commented on tasks/mpi/pikarychev_i_sleeping_barber/src/ops_mpi.cpp
> +enum Tags : int {                                          // NOLINT(performance-enum-size)
What is the reason of ignoring "performance-enum-size"? It does not seem justified here

2024-12-07 18:04 UTC, flashkasi commented on tasks/mpi/pikarychev_i_sleeping_barber/src/ops_mpi.cpp
> +enum Tags : int {                                          // NOLINT(performance-enum-size)
As an underlying type, int is needed if necessary, and NOLINT drowns out warnings about the potential for using a smaller type to accommodate enum values.

2024-12-07 21:34 UTC, flashkasi commented on tasks/mpi/pikarychev_i_sleeping_barber/func_tests/main.cpp
> +  if (!testMpiTaskParallel.validation()) {
fixed

2024-12-08 06:49 UTC, aobolensk commented on tasks/mpi/pikarychev_i_sleeping_barber/src/ops_mpi.cpp
> +enum Tags : int {                                          // NOLINT(performance-enum-size)
smaller types are upcasted to int, so warning is valid

2024-12-08 11:07 UTC, allnes approved these changes

2024-12-08 20:13 UTC, flashkasi commented on tasks/mpi/pikarychev_i_sleeping_barber/src/ops_mpi.cpp
> +enum Tags : int {                                          // NOLINT(performance-enum-size)
fixed

2024-12-09 03:17 UTC, aobolensk approved these changes

2024-12-09 03:17 UTC, merged