Шульпин Илья. Задача 2. Вариант 18. Умножение матриц, ленточная горизонтальная схема А, вертикальное В
learning-process/ppc-2024-autumn pull request #351
Opened 2024-11-25 22:44 UTC by NeeMiyuki

2024-11-26 18:28 UTC, Alexey-Solovev requested changes

2024-11-26 18:28 UTC, Alexey-Solovev commented on tasks/seq/shulpin_i_strip_hA_vB/src/strip_hA_vB.cpp
> +std::vector<int> shulpin_strip_scheme_A_B::get_RND_matrix(int row, int col) {
This function is not used in the seq version and can be removed

2024-11-26 18:42 UTC, Alexey-Solovev requested changes

2024-11-26 18:42 UTC, Alexey-Solovev commented on tasks/mpi/shulpin_i_strip_hA_vB/include/strip_hA_vB.hpp
> +// void make_size_and_displace(int rows, int cols, int num_proc, std::vector<int>& size, std::vector<int>& displace);
Сommented code can be removed

2024-11-26 18:43 UTC, Alexey-Solovev requested changes

2024-11-26 18:43 UTC, Alexey-Solovev commented on tasks/mpi/shulpin_i_strip_hA_vB/src/strip_hA_vB.cpp
> +    // make_size_and_displace(mpi_rows_A * mpi_cols_B, 1, world.size(), size, displ);
Also can be removed

2024-11-26 20:10 UTC, NeeMiyuki commented on tasks/mpi/shulpin_i_strip_hA_vB/src/strip_hA_vB.cpp
> +    // make_size_and_displace(mpi_rows_A * mpi_cols_B, 1, world.size(), size, displ);
done

2024-11-26 20:10 UTC, NeeMiyuki commented on tasks/mpi/shulpin_i_strip_hA_vB/include/strip_hA_vB.hpp
> +// void make_size_and_displace(int rows, int cols, int num_proc, std::vector<int>& size, std::vector<int>& displace);
done

2024-11-26 20:10 UTC, NeeMiyuki commented on tasks/seq/shulpin_i_strip_hA_vB/src/strip_hA_vB.cpp
> +std::vector<int> shulpin_strip_scheme_A_B::get_RND_matrix(int row, int col) {
done

2024-11-26 20:25 UTC, Alexey-Solovev approved these changes

2024-11-27 16:36 UTC, PutinVVV requested changes
Add checks to make sure that you have correctly transmitted the necessary data (that is, you can transmit a 2x2 matrix, but at the same time transmit that the number of rows and columns in this matrix will be 1 and 1.)
For Seq Realisation #

2024-11-27 18:11 UTC, PutinVVV approved these changes

2024-12-01 22:21 UTC, allnes commented on tasks/mpi/shulpin_i_strip_hA_vB/perf_tests/main.cpp
> +  int rows_b = 500;
please use different cols and rows

2024-12-01 22:23 UTC, allnes commented on tasks/mpi/shulpin_i_strip_hA_vB/func_tests/main.cpp
> +  int rows_b = 500;
please use mixed values - prime values, 2^n, 10^n

2024-12-02 21:50 UTC, NeeMiyuki commented on tasks/mpi/shulpin_i_strip_hA_vB/func_tests/main.cpp
> +  int rows_b = 500;
done. now it's a 1000

2024-12-02 21:50 UTC, NeeMiyuki commented on tasks/mpi/shulpin_i_strip_hA_vB/perf_tests/main.cpp
> +  int rows_b = 500;
done. now it's a 1000

2024-12-02 22:57 UTC, allnes commented on tasks/mpi/shulpin_i_strip_hA_vB/func_tests/main.cpp
> +  int rows_b = 500;
mixed values - cols_a = prime value, rows_a = cols_b = 2^n, rows_b = 10^n

2024-12-02 22:57 UTC, allnes commented on tasks/mpi/shulpin_i_strip_hA_vB/perf_tests/main.cpp
> +  int rows_b = 500;
mixed values - cols_a = prime value, rows_a = cols_b = 2^n, rows_b = 10^n

2024-12-03 17:07 UTC, aobolensk requested changes

2024-12-03 17:07 UTC, aobolensk commented on tasks/mpi/shulpin_i_strip_hA_vB/include/strip_hA_vB.hpp
> +std::vector<int> get_RND_matrix(int row, int col);
Please, move test functions to the test module

2024-12-03 17:07 UTC, aobolensk commented on tasks/mpi/shulpin_i_strip_hA_vB/src/strip_hA_vB.cpp
> +  MPI_Gatherv(bufC.data(), LocalRows * cols_b, MPI_INT, C_mpi.data(), sendcounts.data(), displs.data(), MPI_INT, 0,
Why do you use mix of boost and C MPI?

2024-12-03 17:45 UTC, NeeMiyuki commented on tasks/mpi/shulpin_i_strip_hA_vB/src/strip_hA_vB.cpp
> +  MPI_Gatherv(bufC.data(), LocalRows * cols_b, MPI_INT, C_mpi.data(), sendcounts.data(), displs.data(), MPI_INT, 0,
i forgot to change boost to C MPI after i finished calculate_mpi function

2024-12-03 21:41 UTC, NeeMiyuki commented on tasks/mpi/shulpin_i_strip_hA_vB/src/strip_hA_vB.cpp
> +  MPI_Gatherv(bufC.data(), LocalRows * cols_b, MPI_INT, C_mpi.data(), sendcounts.data(), displs.data(), MPI_INT, 0,
done. changed all C MPI functions to boost

2024-12-03 21:41 UTC, NeeMiyuki commented on tasks/mpi/shulpin_i_strip_hA_vB/include/strip_hA_vB.hpp
> +std::vector<int> get_RND_matrix(int row, int col);
done

2024-12-04 02:14 UTC, NeeMiyuki commented on tasks/mpi/shulpin_i_strip_hA_vB/func_tests/main.cpp
> +  int rows_b = 500;
done, used values 401, 512, 512 and 1000

2024-12-04 02:15 UTC, NeeMiyuki commented on tasks/mpi/shulpin_i_strip_hA_vB/perf_tests/main.cpp
> +  int rows_b = 500;
done

2024-12-05 23:49 UTC, allnes approved these changes

2024-12-07 17:30 UTC, aobolensk approved these changes

2024-12-07 17:30 UTC, merged