Коньков Иван. Задача 2. Вариант 3. Задача «Обедающие философы».
learning-process/ppc-2024-autumn pull request #352
Opened 2024-11-25 23:32 UTC by keshaproger

# Описание задачи
В данной задаче реализуется решение классической проблемы обедающих философов с использованием технологии MPI (Message Passing Interface). Задача направлена на моделирование взаимодействия параллельных процессов, конкурирующих за ограниченные ресурсы (вилки), с целью предотвращения взаимных блокировок (дедлоков) и обеспечения корректного выполнения.

## Ключевые этапы реализации:
Инициализация процессов и ресурсов:

Каждый процесс моделирует философа, который выполняет чередующиеся действия: "думает" и "ест".
Общие ресурсы (вилки) и состояния философов инициализируются с помощью MPI для согласованной работы всех процессов.
Параллельное выполнение:

Каждый философ (процесс) пытается захватить две соседние вилки для приёма пищи.
Алгоритм гарантирует, что два процесса не могут одновременно использовать одну и ту же вилку.
Синхронизация:

Состояния процессов и ресурсов синхронизируются через MPI-коммуникации.
Используются барьеры и коллективные операции для предотвращения гонок данных и дедлоков.
Проверка на дедлок:

Выполняется локальная и глобальная проверка состояния философов, чтобы убедиться в отсутствии дедлоков.
Глобальная проверка реализована с помощью функции MPI_Allreduce, что позволяет объединить результаты всех процессов.
Функциональное и производительное тестирование:

Разработаны модульные тесты для проверки корректности работы алгоритма при различных сценариях: разные числа философов, недопустимые параметры и детектирование дедлоков.
Проведено тестирование производительности при увеличении числа философов.

2024-11-25 23:52 UTC, KADCHDR requested changes

2024-11-26 01:07 UTC, keshaproger commented on tasks/mpi/konkov_i_task_dining_philosophers/perf_tests/main.cpp
> +#include "core/perf/include/perf.hpp"
fixed

2024-11-26 01:08 UTC, keshaproger commented on tasks/seq/konkov_i_task_dining_philosophers/perf_tests/main.cpp
> +
added

2024-11-26 01:08 UTC, keshaproger commented on tasks/seq/konkov_i_task_dining_philosophers/perf_tests/main.cpp
> +#include "core/perf/include/perf.hpp"
fixed

2024-12-01 01:15 UTC, keshaproger commented
> а при чем тут философы

В описании задачи есть все ответы.

2024-12-01 14:04 UTC, venn2713 commented on tasks/mpi/konkov_i_task_dining_philosophers/src/ops_mpi.cpp
> +  reduce(world, local_res, res, std::plus(), 0);
Ой, выглядит как попытка обмануть. Я код посмотрел, и действительно нет там никаких философов, особенно seq версия выглядит смешно

2024-12-01 22:24 UTC, allnes commented on tasks/mpi/konkov_i_task_dining_philosophers/src/ops_mpi.cpp
> +    vec[i] = gen() % 100;
please use negative values

2024-12-01 22:26 UTC, allnes commented on tasks/seq/konkov_i_task_dining_philosophers/src/ops_seq.cpp
> +using namespace std::chrono_literals;
please remove it

2024-12-01 22:28 UTC, allnes commented
@keshaproger The task does not match the description

2024-12-08 00:33 UTC, antihype320 commented on tasks/seq/konkov_i_task_dining_philosophers/src/ops_seq.cpp
> +  for (int i = 0; i < philosopher_count_; ++i) {
change: for (int i = 0; i < philosopher_count_; ++i)
to: threads.reserve(philosopher_count_);\nfor (int i = 0; i < philosopher_count_; ++i)

2024-12-08 00:33 UTC, antihype320 commented on tasks/mpi/konkov_i_task_dining_philosophers/src/ops_mpi.cpp
> +      world_() {}
delete: world_()

2024-12-08 00:33 UTC, antihype320 commented on tasks/mpi/konkov_i_task_dining_philosophers/src/ops_mpi.cpp
> +  for (int i = 0; i < philosopher_count_; ++i) {
change: for (int i = 0; i < philosopher_count_; ++i)
to: threads.reserve(philosopher_count_);\nfor (int i = 0; i < philosopher_count_; ++i)

2024-12-08 01:06 UTC, keshaproger commented on tasks/seq/konkov_i_task_dining_philosophers/src/ops_seq.cpp
> +using namespace std::chrono_literals;
fixed

2024-12-08 01:06 UTC, keshaproger commented on tasks/mpi/konkov_i_task_dining_philosophers/src/ops_mpi.cpp
> +  for (int i = 0; i < philosopher_count_; ++i) {
fixed

2024-12-08 01:06 UTC, keshaproger commented on tasks/mpi/konkov_i_task_dining_philosophers/src/ops_mpi.cpp
> +      world_() {}
fixed

2024-12-08 01:15 UTC, antihype320 approved these changes

2024-12-08 11:09 UTC, allnes commented on tasks/seq/konkov_i_task_dining_philosophers/include/ops_seq.hpp
> +  std::vector<std::mutex> forks_;
this course about parallel processes and not about threads

2024-12-08 13:04 UTC, kmichaelk requested changes
the solution is thread-based, it does not use MPI

2024-12-08 23:40 UTC, KADCHDR approved these changes

2024-12-10 20:04 UTC, keshaproger commented
@aobolensk @allnes check please

2024-12-11 19:06 UTC, aobolensk requested changes
Please also collect an approval from @venn2713

2024-12-11 19:06 UTC, aobolensk commented on tasks/mpi/konkov_i_task_dining_philosophers/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
Please, move test functions to the test module

2024-12-11 19:06 UTC, aobolensk commented on tasks/mpi/konkov_i_task_dining_philosophers/src/ops_mpi.cpp
> +    vec[i] = gen() % 100;
This comment seems to be ignored for some reason

2024-12-11 19:06 UTC, aobolensk commented on tasks/mpi/konkov_i_task_dining_philosophers/src/ops_mpi.cpp
> +  broadcast(world, delta, 0);
Please, move data transfer to ::run() function

2024-12-13 00:22 UTC, keshaproger commented on tasks/mpi/konkov_i_task_dining_philosophers/src/ops_mpi.cpp
> +  broadcast(world, delta, 0);
fixed

2024-12-13 00:22 UTC, keshaproger commented on tasks/mpi/konkov_i_task_dining_philosophers/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
fixed

2024-12-13 00:23 UTC, keshaproger commented on tasks/mpi/konkov_i_task_dining_philosophers/src/ops_mpi.cpp
> +    vec[i] = gen() % 100;
fixed

2024-12-15 19:05 UTC, allnes commented
@keshaproger please, solve the problem you have been assigned, I don't see  "dining philosophers" right now

2024-12-16 11:57 UTC, keshaproger commented
@aobolensk @allnes changed and fixed all the problems

2024-12-22 21:23 UTC, kmichaelk requested changes
Still does not use MPI, but now there is no synchronization at all

2024-12-29 19:38 UTC, closed without merging