Сарафанов Максим. Задача 2 вариант 21 Метод Гаусса-Жордана
learning-process/ppc-2024-autumn pull request #356
Opened 2024-11-26 12:48 UTC by Pybigboy

Этот репозиторий реализует параллельный и последовательный метод Гаусса-Жордана для решения систем линейных уравнений.

MPI реализация: использует библиотеку MPI для распределения вычислений между процессами, оптимизируя обработку матрицы на этапах разложения и преобразования. Обеспечивает параллельное обновление матрицы и сбор результатов, сокращая время выполнения.

SEQ реализация: выполняет тот же алгоритм последовательно без параллелизма. Проста в реализации и используется для сравнения производительности с MPI-версией.

2024-11-26 16:00 UTC, venn2713 requested changes
Otherwise, the work is good, an interesting approach

2024-11-26 16:00 UTC, venn2713 commented on tasks/mpi/sarafanov_m_gauss_jordan_method/func_tests/main.cpp
> +}
This looks like a place where you could add a validation test if the matrix dimensions are incorrect

2024-11-26 16:00 UTC, venn2713 commented on tasks/mpi/sarafanov_m_gauss_jordan_method/src/ops_mpi.cpp
> +  return true;
I think in your case you can check that the matrix is ​​of the correct size, that is, an extended square

2024-11-26 19:09 UTC, korablev-vm requested changes
The implementation looks correct and logical, but you need to work on validation - think about and write it, as well as add functional tests. Otherwise, I agree with Sergey

2024-11-26 19:09 UTC, korablev-vm commented on tasks/seq/sarafanov_m_gauss_jordan_method/src/ops_seq.cpp
> +}
It is necessary to implement this block

2024-11-26 19:09 UTC, korablev-vm commented on tasks/mpi/sarafanov_m_gauss_jordan_method/src/ops_mpi.cpp
> +}
And this one too

2024-11-26 20:16 UTC, Pybigboy commented on tasks/mpi/sarafanov_m_gauss_jordan_method/src/ops_mpi.cpp
> +}
I fix that!

2024-11-26 20:16 UTC, Pybigboy commented on tasks/seq/sarafanov_m_gauss_jordan_method/src/ops_seq.cpp
> +}
I fix that!

2024-11-26 20:16 UTC, Pybigboy commented on tasks/mpi/sarafanov_m_gauss_jordan_method/src/ops_mpi.cpp
> +  return true;
I fix that!

2024-11-26 20:16 UTC, Pybigboy commented on tasks/mpi/sarafanov_m_gauss_jordan_method/func_tests/main.cpp
> +}
You are right!

2024-11-26 21:04 UTC, venn2713 approved these changes

2024-11-27 07:44 UTC, korablev-vm approved these changes

2024-12-01 22:37 UTC, allnes commented on tasks/mpi/sarafanov_m_gauss_jordan_method/func_tests/main.cpp
> +  std::uniform_real_distribution<double> dist(-20.0, 20.0);
please parametrize it and check in tests

2024-12-03 16:17 UTC, Pybigboy commented on tasks/mpi/sarafanov_m_gauss_jordan_method/func_tests/main.cpp
> +  std::uniform_real_distribution<double> dist(-20.0, 20.0);
Fix

2024-12-03 16:17 UTC, Pybigboy commented on tasks/mpi/sarafanov_m_gauss_jordan_method/src/ops_mpi.cpp
> +}
Fix

2024-12-03 18:34 UTC, aobolensk approved these changes

2024-12-05 23:54 UTC, allnes approved these changes

2024-12-05 23:54 UTC, merged