Соцков Андрей. Задача 2. Вариант 17. Ленточная горизонтальная схема - разбиение только матрицы А
learning-process/ppc-2024-autumn pull request #357
Opened 2024-11-26 18:58 UTC by flavvvour

# Описание задачи: Ленточная горизонтальная схема — разбиение только матрицы A

## Цель задачи
Реализовать умножение двух матриц \(A\) и \(B\) с использованием ленточной горизонтальной схемы, где разбиение производится только по строкам матрицы \(A\).

---

## Последовательная версия

В последовательной реализации используется базовый алгоритм умножения матриц.  
Алгоритм предполагает следующие этапы:

### 1. Инициализация данных
- Получение размеров матриц \(A\) и \(B\).
- Инициализация результата (матрица \(C\)) размером \( m * n \), где \(m\) — число строк \(A\), а \(n\) — число столбцов \(B\).

### 2. Валидация данных
- Проверка согласованности размеров матриц: число столбцов \(A\) должно совпадать с числом строк \(B\).

### 3. Умножение матриц
- Вложенные циклы проходят по строкам матрицы \(A\), столбцам матрицы \(B\), и выполняют скалярное произведение строк \(A\) на столбцы \(B\).

### 4. Сохранение результата
- Результат вычислений записывается в выходной буфер.

---

## Параллельная версия

В параллельной реализации задача решается с использованием MPI, где:

### 1. Разбиение данных
- Только строки матрицы \(A\) разбиваются на фрагменты и распределяются между процессами.
- Матрица \(B\) передается полностью всем процессам, так как она используется при расчете каждого фрагмента результата.

### 2. Передача данных
- Процесс с рангом 0 отправляет фрагменты строк матрицы \(A\) другим процессам через `MPI_Scatterv`.
- Матрица \(B\) передается через `MPI_Bcast`.

### 3. Локальное вычисление
- Каждый процесс выполняет умножение выделенного фрагмента строк \(A\) на матрицу \(B\) и формирует свой локальный фрагмент результата.

### 4. Сбор результата
- Локальные фрагменты матрицы \(C\) возвращаются процессу с рангом 0 с помощью `MPI_Gatherv`.

### 5. Обработка результата
- Процесс с рангом 0 объединяет все фрагменты в итоговую матрицу \(C\) и сохраняет её в выходной буфер.

---

2024-11-26 21:26 UTC, hasanyanovk commented on tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/src/ops_mpi.cpp
> +    }
Not need `()` if you initialize it later

2024-11-26 21:28 UTC, hasanyanovk commented on tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/src/ops_mpi.cpp
> +  MPI_Scatterv(input_A, sendcounts, displs, MPI_INT, local_A, sendcounts[rank], MPI_INT, 0, MPI_COMM_WORLD);
Why do you prefer `MPI_*` fuctions to the `boost::mpi` and `T*` to the `std::vector`?

2024-11-27 04:17 UTC, Svoloch2940194 commented on tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/src/ops_mpi.cpp
> +#include <string>
extra include

2024-11-27 04:17 UTC, Svoloch2940194 commented on tasks/seq/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/include/ops_seq.hpp
> +#include <string>
extra include

2024-11-27 13:47 UTC, flavvvour commented on tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/src/ops_mpi.cpp
> +  MPI_Scatterv(input_A, sendcounts, displs, MPI_INT, local_A, sendcounts[rank], MPI_INT, 0, MPI_COMM_WORLD);
**1)** I use C-style.
**2)** Direct use of `MPI_*` provides full control over communication, which is important for tasks with high performance requirements.
**3)** `MPI_*` function calls minimize the overhead that may arise from additional abstractions in `boost::mpi`.

2024-11-27 14:05 UTC, flavvvour commented on tasks/seq/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/include/ops_seq.hpp
> +#include <string>
Fixed in commit: "fix review"

2024-11-27 14:05 UTC, flavvvour commented on tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/src/ops_mpi.cpp
> +#include <string>
Fixed in commit: "fix review"

2024-11-27 14:05 UTC, flavvvour commented on tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/src/ops_mpi.cpp
> +    }
Fixed in commit: "fix review"

2024-11-27 14:07 UTC, hasanyanovk approved these changes

2024-11-27 14:14 UTC, Svoloch2940194 approved these changes

2024-12-01 22:41 UTC, allnes commented on tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/src/ops_mpi.cpp
> +  return taskData->inputs_count[0] > 1 && taskData->inputs_count[1] > 0 && taskData->inputs_count[2] > 0 &&
why `taskData->inputs_count[0] > 1 `?

2024-12-01 22:41 UTC, allnes commented on tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/func_tests/main.cpp
> +    mat[i] = gen() % 10 - 5;
please parametrize intervals and check it

2024-12-01 22:42 UTC, allnes commented on tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/func_tests/main.cpp
> +  }
where do you check assertions with empty inputs

2024-12-01 22:43 UTC, allnes commented on tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/func_tests/main.cpp
> +  }
please rewrite comparison and move to validation, or use GTEST_SKIP()

2024-12-01 22:44 UTC, allnes commented on tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/func_tests/main.cpp
> +    std::vector<int> expected_res(8, 0);
please check different sizes, prime values, 2^n, 10^n etc

2024-12-02 06:32 UTC, flavvvour commented on tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/src/ops_mpi.cpp
> +  return taskData->inputs_count[0] > 1 && taskData->inputs_count[1] > 0 && taskData->inputs_count[2] > 0 &&
The number of columns in matrix **A** must be greater than 1 in order to perform the correct multiplication.<br> If there is only one column in matrix A, it is actually a _vector_.

2024-12-02 17:02 UTC, flavvvour commented on tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/func_tests/main.cpp
> +    std::vector<int> expected_res(8, 0);
Fixed in commit: "fix review 2.0"

2024-12-02 17:02 UTC, flavvvour commented on tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/func_tests/main.cpp
> +  }
Fixed in commit: "fix review 2.0"

2024-12-02 17:02 UTC, flavvvour commented on tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/func_tests/main.cpp
> +    mat[i] = gen() % 10 - 5;
Fixed in commit: "fix review 2.0"

2024-12-02 23:00 UTC, allnes commented on tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/src/ops_mpi.cpp
> +  return taskData->inputs_count[0] > 1 && taskData->inputs_count[1] > 0 && taskData->inputs_count[2] > 0 &&
how can you handle case 1x1?

2024-12-03 00:07 UTC, flavvvour commented on tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/src/ops_mpi.cpp
> +  return taskData->inputs_count[0] > 1 && taskData->inputs_count[1] > 0 && taskData->inputs_count[2] > 0 &&
The `1x1` matrix is essentially a scalar. If the matrix `A` is `1x1`, it needs to be treated as a scalar in some operations, which changes the approach to multiplication.
And in this task, if I'm not mistaken, it requires working with **matrices**, not vectors.

2024-12-03 00:35 UTC, flavvvour commented on tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/src/ops_mpi.cpp
> +  return taskData->inputs_count[0] > 1 && taskData->inputs_count[1] > 0 && taskData->inputs_count[2] > 0 &&
Added a check for the `1*1` case!
**Fixed in commit:** "adding a 1*1 case"

2024-12-03 18:59 UTC, aobolensk requested changes

2024-12-03 18:59 UTC, aobolensk commented on tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/src/ops_mpi.cpp
> +      input_A[i] = tmp_ptr_a[i];
use std::copy

2024-12-03 18:59 UTC, aobolensk commented on tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/src/ops_mpi.cpp
> +    input_B = new int[column_B * row_B];
Do we need to free memory?

2024-12-03 20:30 UTC, flavvvour commented on tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/src/ops_mpi.cpp
> +    input_B = new int[column_B * row_B];
Fixed in commit: "fix review 3.0"

2024-12-05 23:56 UTC, allnes approved these changes

2024-12-08 06:53 UTC, aobolensk approved these changes

2024-12-08 06:53 UTC, merged