Шуравина Оксана. Задача 2. Вариант 27. Повышение контраста
learning-process/ppc-2024-autumn pull request #359
Opened 2024-11-26 20:07 UTC by shyravina19102004

2024-12-02 22:56 UTC, kobych requested changes
please add more tests

2024-12-04 17:38 UTC, dasha1112 commented on tasks/seq/shuravina_o_contrast/func_tests/main.h
Please, delete empty file

2024-12-04 17:38 UTC, dasha1112 commented on validation()
Please, delete empty file

2024-12-05 15:08 UTC, shyravina19102004 commented on validation()
fix

2024-12-05 15:08 UTC, shyravina19102004 commented on tasks/mpi/shuravina_o_contrast/func_tests/main.cpp
> +TEST(shuravina_o_contrast, Test_Contrast_Enhancement_Correct_Output_Size) {
fix

2024-12-06 09:02 UTC, kobych approved these changes

2024-12-06 13:00 UTC, dasha1112 approved these changes

2024-12-08 06:56 UTC, aobolensk requested changes
You still have too many files

2024-12-08 18:12 UTC, m1likus commented
75 changed files....

2024-12-09 03:18 UTC, aobolensk requested changes

2024-12-09 03:18 UTC, aobolensk commented on tasks/mpi/chistov_a_sum_of_matrix_elements/func_tests/main.cpp
> -#include "mpi/chistov_a_sum_of_matrix_elements/include/ops_mpi.hpp"
Please, do not modify others' files

2024-12-09 08:50 UTC, shyravina19102004 commented on tasks/mpi/chistov_a_sum_of_matrix_elements/func_tests/main.cpp
> -#include "mpi/chistov_a_sum_of_matrix_elements/include/ops_mpi.hpp"
there were problems with this file, I returned everything back

2024-12-10 16:52 UTC, shyravina19102004 commented on tasks/mpi/chistov_a_sum_of_matrix_elements/func_tests/main.cpp
> -#include "mpi/chistov_a_sum_of_matrix_elements/include/ops_mpi.hpp"
fix

2024-12-10 19:15 UTC, aobolensk requested changes

2024-12-10 19:15 UTC, aobolensk commented on tasks/mpi/shuravina_o_contrast/src/ops_mpi.cpp
> +  broadcast(world, delta, 0);
Please, move data transfer to ::run() function

2024-12-10 19:15 UTC, aobolensk commented on tasks/mpi/shuravina_o_contrast/src/ops_mpi.cpp
> +      tmp_ptr[i] = output_[i];
use std::copy

2024-12-10 19:15 UTC, aobolensk commented on tasks/mpi/shuravina_o_contrast/func_tests/main.cpp
> +TEST(shuravina_o_contrast, Test_Contrast_Enhancement_Single_Element_Input) {
Please, add tests on randomly generated images

2024-12-10 19:15 UTC, aobolensk commented on tasks/mpi/shuravina_o_contrast/perf_tests/main.cpp
> +    std::vector<uint8_t> input = {50};
Perf tests should follow naming convention (please, read rules) and they should be run on big images

2024-12-10 19:26 UTC, aobolensk requested changes
There are two tasks in one PR. This is not allowed

2024-12-11 13:24 UTC, shyravina19102004 commented on tasks/mpi/shuravina_o_contrast/perf_tests/main.cpp
> +    std::vector<uint8_t> input = {50};
fix

2024-12-11 13:24 UTC, shyravina19102004 commented on tasks/mpi/shuravina_o_contrast/func_tests/main.cpp
> +TEST(shuravina_o_contrast, Test_Contrast_Enhancement_Single_Element_Input) {
fix

2024-12-11 13:24 UTC, shyravina19102004 commented on tasks/mpi/shuravina_o_contrast/src/ops_mpi.cpp
> +      tmp_ptr[i] = output_[i];
fix

2024-12-11 19:04 UTC, aobolensk requested changes

2024-12-11 19:04 UTC, aobolensk commented on tasks/mpi/shuravina_o_contrast/func_tests/main.cpp
> +std::vector<uint8_t> generateRandomImage(size_t size) {
Please, either make it static or wrap with namespace

2024-12-11 19:04 UTC, aobolensk commented on tasks/mpi/shuravina_o_contrast/perf_tests/main.cpp
> +TEST(shuravina_o_contrast_perf, Test_Contrast_Enhancement_Large_Image) {
Please, align names of perf tests. There should be 2 perf tests with specific names (for each MPI and sequential version)

2024-12-11 19:04 UTC, aobolensk commented on tasks/mpi/shuravina_o_contrast/src/ops_mpi.cpp
> +  broadcast(world, delta, 0);
Please, move all data transfer and computation to ::run() function

2024-12-12 09:24 UTC, shyravina19102004 commented on tasks/mpi/shuravina_o_contrast/perf_tests/main.cpp
> +TEST(shuravina_o_contrast_perf, Test_Contrast_Enhancement_Large_Image) {
fix

2024-12-12 09:24 UTC, shyravina19102004 commented on tasks/mpi/shuravina_o_contrast/src/ops_mpi.cpp
> +  broadcast(world, delta, 0);
fix

2024-12-13 16:20 UTC, allnes commented on tasks/seq/shuravina_o_contrast/perf_tests/main.cpp
> +  const int count = 100;
small count for perf

2024-12-13 16:22 UTC, allnes commented on tasks/mpi/shuravina_o_contrast/func_tests/main.cpp
> +TEST(shuravina_o_contrast, Test_Contrast_Enhancement_Max_Values_Input) {
please check more cases, e.g. (100x32) (64x23) (27x128)

2024-12-13 17:57 UTC, shyravina19102004 commented on tasks/seq/shuravina_o_contrast/perf_tests/main.cpp
> +  const int count = 100;
Fix

2024-12-13 17:57 UTC, shyravina19102004 commented on tasks/mpi/shuravina_o_contrast/func_tests/main.cpp
> +TEST(shuravina_o_contrast, Test_Contrast_Enhancement_Max_Values_Input) {
Fix

2024-12-14 10:49 UTC, aobolensk approved these changes

2024-12-15 19:06 UTC, allnes approved these changes

2024-12-15 19:07 UTC, merged