Козлова Екатерина. Задача 2. Вариант 22. Итеративные методы (Якоби)
learning-process/ppc-2024-autumn pull request #360
Opened 2024-11-26 21:04 UTC by KatyaKozlova

### Описание последовательной версии
Система линейных уравнений представляется следующим образом: 
_Ax=B_, 
где _A_ — это матрица коэффициентов, _B_ — вектор правых частей, а _x_ — искомый вектор решений. В этой версии алгоритм выполняет итерации в одном процессе, последовательно вычисляя новые приближения для каждого элемента вектора решения по следующей формуле: 
![b65524feb90628943c526fd5417edc11e0a47e2a](https://github.com/user-attachments/assets/17633418-089b-40fa-985c-ac3c4ba63797)
На каждой итерации вычисляется разница между текущим и предыдущим вектором решения, и процесс продолжается до тех пор, пока эта разница не станет меньше заданной точности _eps_.  Также проверяется, что на главной диагонали матрицы _A_ нет нулевых элементов, так как это сделает метод Якоби неприменимым.

### Описание параллельной версии
Алгоритм выполняет аналогичные действия, что и в последовательной версии, но с распределением вычислений между процессами. Каждый процесс обрабатывает определённый блок строк матрицы, и в конце каждой итерации результаты собираются на процессе с рангом 0 с помощью операции gatherv. После этого новый вектор решения рассылается обратно всем процессам через операцию broadcast.

2024-11-28 16:12 UTC, Gn4ik requested changes

2024-11-28 16:12 UTC, Gn4ik commented on tasks/mpi/kozlova_e_jacobi_method/src/ops_mpi.cpp
> +bool kozlova_e_jacobi_method_mpi::MethodJacobiMPI::validation() {
add a check for negative epsilon

2024-11-29 09:39 UTC, KatyaKozlova commented on tasks/mpi/kozlova_e_jacobi_method/src/ops_mpi.cpp
> +bool kozlova_e_jacobi_method_mpi::MethodJacobiMPI::validation() {
fixed

2024-11-29 09:39 UTC, KatyaKozlova commented on tasks/mpi/kozlova_e_jacobi_method/src/ops_mpi.cpp
> +    eps = 1e-6;
fixed

2024-11-29 11:09 UTC, Gn4ik approved these changes

2024-11-29 12:28 UTC, KoshkinMatvey requested changes

2024-11-29 12:28 UTC, KoshkinMatvey commented on tasks/mpi/kozlova_e_jacobi_method/src/ops_mpi.cpp
> +  if (eps <= 0.0) {
move the check to validation

2024-11-29 19:03 UTC, KatyaKozlova commented on tasks/mpi/kozlova_e_jacobi_method/src/ops_mpi.cpp
> +  if (eps <= 0.0) {
fixed

2024-11-29 21:45 UTC, KoshkinMatvey approved these changes

2024-12-01 22:47 UTC, allnes commented on tasks/mpi/kozlova_e_jacobi_method/src/ops_mpi.cpp
> +bool kozlova_e_jacobi_method_mpi::MethodJacobiSeq::validation() {
where do you check exist of single solution of linear system

2024-12-01 22:48 UTC, allnes commented on tasks/mpi/kozlova_e_jacobi_method/perf_tests/main.cpp
> +    ASSERT_NEAR(X[i], expected_X[i], 0.5);
both values can be wrong, please for all algos and tests check `||Ax - b|| < eps` for seq and parallel

2024-12-03 18:55 UTC, aobolensk requested changes

2024-12-03 18:55 UTC, aobolensk commented on tasks/mpi/kozlova_e_jacobi_method/perf_tests/main.cpp
> +  }
Please, use random tests for perf tests

2024-12-03 18:55 UTC, aobolensk commented on tasks/mpi/kozlova_e_jacobi_method/perf_tests/main.cpp
> +  const int N = 490;
Use bigger siye for perf test

2024-12-06 11:21 UTC, KatyaKozlova commented on tasks/mpi/kozlova_e_jacobi_method/src/ops_mpi.cpp
> +bool kozlova_e_jacobi_method_mpi::MethodJacobiSeq::validation() {
fixed

2024-12-06 11:21 UTC, KatyaKozlova commented on tasks/mpi/kozlova_e_jacobi_method/perf_tests/main.cpp
> +    ASSERT_NEAR(X[i], expected_X[i], 0.5);
fixed

2024-12-06 11:21 UTC, KatyaKozlova commented on tasks/mpi/kozlova_e_jacobi_method/perf_tests/main.cpp
> +  }
fixed

2024-12-06 11:22 UTC, KatyaKozlova commented on tasks/mpi/kozlova_e_jacobi_method/perf_tests/main.cpp
> +  const int N = 490;
fixed

2024-12-08 07:33 UTC, aobolensk approved these changes

2024-12-08 11:12 UTC, allnes approved these changes

2024-12-08 11:12 UTC, merged