Борисов Сергей. Задача 2. Вариант 5. Передача от одного всем (broadcast)
learning-process/ppc-2024-autumn pull request #361
Opened 2024-11-26 22:42 UTC by SergeyBoRss

Выбрана задача:
Задана матрица размером MxN, где М - кол-во точек, а N - размерность пространства
0 поток нормализует точки и находит центр масс, затем передаёт нормализованную матрицу, центр масс, окрестность центра остальным потокам, которые бинарно кластеризуют эти точки (если точка лежит в окрестности, значит 1, иначе 0)

Broadcast реализован на тернарном дереве (3 наиболее близка к е), используется для передачи данных, указанных выше

2024-11-26 23:15 UTC, KorotinEgor commented on tasks/mpi/borisov_s_broadcast/src/ops_mpi.cpp
> +#include <thread>
Extra include

2024-11-26 23:15 UTC, KorotinEgor commented on tasks/mpi/borisov_s_broadcast/src/ops_mpi.cpp
> +  */
Delete the commented out code

2024-11-26 23:15 UTC, KorotinEgor commented on tasks/mpi/borisov_s_broadcast/src/ops_mpi.cpp
> +   */
Delete the commented out code

2024-11-26 23:15 UTC, KorotinEgor commented on tasks/mpi/borisov_s_broadcast/func_tests/main.cpp
> +#include <boost/mpi/environment.hpp>
Extra include

2024-11-26 23:15 UTC, KorotinEgor commented on tasks/mpi/borisov_s_my_broadcast/func_tests/main.cpp
> +#include <boost/mpi/environment.hpp>
Extra include

2024-11-26 23:15 UTC, KorotinEgor commented on tasks/mpi/borisov_s_my_broadcast/src/ops_mpi.cpp
> +#include <thread>
Extra include

2024-11-26 23:15 UTC, KorotinEgor commented on tasks/mpi/borisov_s_my_broadcast/src/ops_mpi.cpp
> +  */
Delete the commented out code

2024-11-26 23:15 UTC, KorotinEgor commented on tasks/mpi/borisov_s_my_broadcast/src/ops_mpi.cpp
> +   */
Delete the commented out code

2024-11-26 23:38 UTC, VladislavPoroshin commented on tasks/mpi/borisov_s_broadcast/src/ops_mpi.cpp
> +    for (size_t i = 0; i < rows; i++) {
use std::copy

2024-11-26 23:38 UTC, VladislavPoroshin commented on tasks/mpi/borisov_s_my_broadcast/src/ops_mpi.cpp
> +    auto *data_ptr = reinterpret_cast<double *>(taskData->inputs[0]);
use std::copy

2024-11-27 10:12 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_broadcast/src/ops_mpi.cpp
> +#include <thread>
Fixed

2024-11-27 10:12 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_broadcast/src/ops_mpi.cpp
> +  */
Fixed

2024-11-27 10:12 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_broadcast/src/ops_mpi.cpp
> +   */
Fixed

2024-11-27 10:12 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_my_broadcast/func_tests/main.cpp
> +#include <boost/mpi/environment.hpp>
Fixed

2024-11-27 10:12 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_my_broadcast/src/ops_mpi.cpp
> +#include <thread>
Fixed

2024-11-27 10:12 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_my_broadcast/src/ops_mpi.cpp
> +  */
Fixed

2024-11-27 10:14 UTC, KorotinEgor approved these changes

2024-11-27 10:35 UTC, VladislavPoroshin approved these changes

2024-12-01 22:50 UTC, allnes commented on tasks/mpi/borisov_s_broadcast/src/ops_mpi.cpp
> +  }
please move it to pre_processing

2024-12-01 22:51 UTC, allnes commented on tasks/mpi/borisov_s_my_broadcast/include/ops_mpi.hpp
> +    parent = (root + (source - 1) / 3) % size;
why are you dividing by 3

2024-12-02 18:00 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_my_broadcast/include/ops_mpi.hpp
> +    parent = (root + (source - 1) / 3) % size;
I implemented a broadcast through a ternary tree, where the indices of the ancestors of the i parent are 3i+1, 3i+2, 3i+3. So to find the index of the parent I need to subtract 1 and divide by 3

2024-12-02 20:24 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_broadcast/src/ops_mpi.cpp
> +  }
Fixed

2024-12-02 23:02 UTC, allnes commented on tasks/CMakeLists.txt
> -      get_filename_component(PROJECT_ID ${subd} NAME)
please don't change not own files

2024-12-03 05:15 UTC, SergeyBoRss commented on tasks/CMakeLists.txt
> -      get_filename_component(PROJECT_ID ${subd} NAME)
Fixed

2024-12-03 18:52 UTC, aobolensk requested changes

2024-12-03 18:52 UTC, aobolensk commented on tasks/mpi/borisov_s_broadcast/include/ops_mpi.hpp
> +std::vector<double> getRandomMatrix(size_t rows, size_t cols);
Please move test function to the test module

2024-12-03 18:52 UTC, aobolensk commented on tasks/mpi/borisov_s_broadcast/func_tests/main.cpp
> +TEST(Parallel_Operations_MPI, Test_Fixed_Example_1) {
Please, add more functional tests

2024-12-03 22:08 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_broadcast/include/ops_mpi.hpp
> +std::vector<double> getRandomMatrix(size_t rows, size_t cols);
done

2024-12-03 22:08 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_broadcast/func_tests/main.cpp
> +TEST(Parallel_Operations_MPI, Test_Fixed_Example_1) {
done

2024-12-05 23:58 UTC, allnes approved these changes

2024-12-08 07:31 UTC, aobolensk requested changes

2024-12-08 07:31 UTC, aobolensk commented on tasks/mpi/borisov_s_broadcast/perf_tests/main.cpp
> +std::vector<double> getRandomMatrix(size_t rows, size_t cols) {
Either make it static or wrap with namespace

2024-12-08 07:52 UTC, aobolensk approved these changes

2024-12-08 08:43 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_broadcast/perf_tests/main.cpp
> +std::vector<double> getRandomMatrix(size_t rows, size_t cols) {
fixed

2024-12-08 10:01 UTC, merged