Гордеева Таисия. Задача 2. Спящий брадобрей
learning-process/ppc-2024-autumn pull request #364
Opened 2024-11-27 12:03 UTC by TayaGordeeva

**Задача о спящем брадобрее** — это классическая задача параллельного программирования, которая используется для иллюстрации проблем синхронизации потоков и обработки конкурирующих запросов.

- Процесс с рангом 0 — барбер, который обслуживает клиентов. Он принимает клиентов, проверяет, есть ли место в очереди, и решает, принимать ли следующего клиента или отправить его обратно.

- Клиенты (процессы с рангами отличными от 0) пытаются попасть в очередь на обслуживание, проверяя, есть ли места. Если места есть, они добавляются в очередь, если нет — отправляются обратно.

Программа моделирует работу "спящего брадобрея", где клиенты могут ожидать своей очереди, а парикмахер обслуживает их по очереди, когда они приходят.

2024-12-01 22:53 UTC, allnes commented on tasks/mpi/gordeeva_t_sleeping_barber/src/ops_mpi.cpp
> +    std::this_thread::sleep_for(2ms);
please parametrize time and check it for different time limits

2024-12-01 22:53 UTC, allnes commented on tasks/mpi/gordeeva_t_sleeping_barber/src/ops_mpi.cpp
> +void gordeeva_t_sleeping_barber_mpi::TestMPITaskParallel::sleep() { std::this_thread::sleep_for(1ms); }
same point about parametrization

2024-12-01 22:54 UTC, allnes commented on tasks/mpi/gordeeva_t_sleeping_barber/func_tests/main.cpp
> +  const int max_waiting_chairs_ = 30;
please check 1024, 996, 999

2024-12-03 18:38 UTC, aobolensk commented
Code coverage is too low 
![image](https://github.com/user-attachments/assets/868356a1-d71b-4b60-b0f8-42e62c538543)

2024-12-03 18:40 UTC, aobolensk requested changes

2024-12-03 18:40 UTC, aobolensk commented on tasks/mpi/gordeeva_t_sleeping_barber/func_tests/main.cpp
> +  // bool barber_busy_ = false;
Clean up commented out code

2024-12-03 18:40 UTC, aobolensk commented on tasks/mpi/gordeeva_t_sleeping_barber/func_tests/main.cpp
> +TEST(gordeeva_t_sleeping_barber_mpi, Test_Barber_0_Seats_Client) {
Please, add test for 1 seat

2024-12-05 20:35 UTC, closed without merging