Харин Матвей. Задача 2. Вариант 23. Итеративные методы (Зейделя)
learning-process/ppc-2024-autumn pull request #365
Opened 2024-11-27 12:14 UTC by mateusxap

2024-11-27 23:37 UTC, hasanyanovk commented on tasks/mpi/kharin_m_seidel_method/src/ops_mpi.cpp
> +    mpi::broadcast(world, a[i], n, 0);
Really?

2024-11-28 07:28 UTC, mateusxap commented on tasks/mpi/kharin_m_seidel_method/src/ops_mpi.cpp
> +    mpi::broadcast(world, a[i], n, 0);
fixed

2024-11-28 21:41 UTC, ValeraDanger commented on tasks/mpi/kharin_m_seidel_method/include/ops_mpi.hpp
> +#include <string>
Unused include

2024-11-28 21:41 UTC, ValeraDanger commented on tasks/mpi/kharin_m_seidel_method/perf_tests/main.cpp
> +#include <vector>
Already included in `ops_mpi.hpp`

2024-11-28 21:41 UTC, ValeraDanger commented on tasks/mpi/kharin_m_seidel_method/src/ops_mpi.cpp
> +#include <iostream>
Unused

2024-11-28 21:41 UTC, ValeraDanger commented on tasks/seq/kharin_m_seidel_method/func_tests/main.cpp
> +#include <vector>
Already included in `ops_seq.hpp`

2024-11-28 21:41 UTC, ValeraDanger commented on tasks/seq/kharin_m_seidel_method/include/ops_seq.hpp
> +#include <string>
Unused

2024-11-28 21:41 UTC, ValeraDanger commented on tasks/seq/kharin_m_seidel_method/perf_tests/main.cpp
> +#include <vector>
Already included in `ops_seq.hpp`

2024-11-28 21:41 UTC, ValeraDanger commented on tasks/seq/kharin_m_seidel_method/src/ops_seq.cpp
> +#include <iostream>
Unused

2024-11-28 22:29 UTC, mateusxap commented on tasks/seq/kharin_m_seidel_method/src/ops_seq.cpp
> +#include <iostream>
fixed

2024-11-28 22:29 UTC, mateusxap commented on tasks/seq/kharin_m_seidel_method/perf_tests/main.cpp
> +#include <vector>
fixed

2024-11-28 22:29 UTC, mateusxap commented on tasks/seq/kharin_m_seidel_method/include/ops_seq.hpp
> +#include <string>
fixed

2024-11-28 22:29 UTC, mateusxap commented on tasks/seq/kharin_m_seidel_method/func_tests/main.cpp
> +#include <vector>
fixed

2024-11-28 22:29 UTC, ValeraDanger approved these changes

2024-11-28 22:29 UTC, mateusxap commented on tasks/mpi/kharin_m_seidel_method/src/ops_mpi.cpp
> +#include <iostream>
fixed

2024-11-28 22:29 UTC, mateusxap commented on tasks/mpi/kharin_m_seidel_method/perf_tests/main.cpp
> +#include <vector>
fixed

2024-11-28 22:29 UTC, mateusxap commented on tasks/mpi/kharin_m_seidel_method/include/ops_mpi.hpp
> +#include <string>
fixed

2024-11-29 19:55 UTC, hasanyanovk approved these changes

2024-12-01 22:55 UTC, allnes commented on tasks/mpi/kharin_m_seidel_method/src/ops_mpi.cpp
> +  p = new double[n];
please use linear form of matrix with help std::vector, and remove new

2024-12-01 22:56 UTC, allnes commented on tasks/mpi/kharin_m_seidel_method/src/ops_mpi.cpp
> +  int max_iterations = 10000;  // Максимальное количество итераций
pleasde parametrize it outside task

2024-12-01 22:56 UTC, allnes commented on tasks/mpi/kharin_m_seidel_method/src/ops_mpi.cpp
> +      x[i] = (b[i] - var) / a[i][i];
please use linear form of matrix everywhere

2024-12-01 22:57 UTC, allnes commented on tasks/mpi/kharin_m_seidel_method/src/ops_mpi.cpp
> +bool kharin_m_seidel_method::GaussSeidelSequential::validation() {
where do you check single solution of linear system

2024-12-02 21:11 UTC, mateusxap commented on tasks/mpi/kharin_m_seidel_method/src/ops_mpi.cpp
> +  p = new double[n];
fixed

2024-12-02 21:11 UTC, mateusxap commented on tasks/mpi/kharin_m_seidel_method/src/ops_mpi.cpp
> +      x[i] = (b[i] - var) / a[i][i];
fixed

2024-12-02 21:11 UTC, mateusxap commented on tasks/mpi/kharin_m_seidel_method/src/ops_mpi.cpp
> +bool kharin_m_seidel_method::GaussSeidelSequential::validation() {
fixed

2024-12-02 23:03 UTC, allnes commented on tasks/mpi/kharin_m_seidel_method/src/ops_mpi.cpp
> +bool kharin_m_seidel_method::GaussSeidelSequential::validation() {
I can't find check by ranks of matrix

2024-12-03 18:24 UTC, mateusxap commented on tasks/mpi/kharin_m_seidel_method/src/ops_mpi.cpp
> +bool kharin_m_seidel_method::GaussSeidelSequential::validation() {
added check of ranks

2024-12-03 19:09 UTC, aobolensk requested changes

2024-12-03 19:09 UTC, aobolensk commented on tasks/seq/kharin_m_seidel_method/func_tests/main.cpp
> +    xSeq[i] = 0.0;
use std::fill

2024-12-03 19:09 UTC, aobolensk commented on tasks/mpi/kharin_m_seidel_method/src/ops_mpi.cpp
> +  mpi::broadcast(world, b.data(), n, 0);
Please, move all data transfers to ::run()

2024-12-04 08:56 UTC, mateusxap commented on tasks/mpi/kharin_m_seidel_method/src/ops_mpi.cpp
> +  mpi::broadcast(world, b.data(), n, 0);
fixed

2024-12-06 00:00 UTC, allnes approved these changes

2024-12-08 07:29 UTC, aobolensk approved these changes

2024-12-08 07:30 UTC, merged