Отурин Александр. Задача 1. Вариант 26. Сглаживание изображений.
learning-process/ppc-2024-autumn pull request #366
Opened 2024-11-27 15:17 UTC by ovVrLFg8ks

В любом случае для последовательной и параллельной задачи сначала готовится матрица (kernel), на основе которой каждый пиксель будет вычислен, с учётом соседних. Размер этой матрицы 3x3. Вычисляется она с помощью Гауссовского распределения таким образом, чтобы сумма всех элементов матрицы была равна 1.

Основано на https://blog.geveo.com/Image-Smoothing-Algorithms.

**Описание последовательной задачи:**
Для каждого пикселя вычисляется значение, основанное на его текущем значении и значении соседних пикселей с помощью матрицы нормального распределения. 

**Описание MPI задачи:**
*Данный алгоритм основан на том, что использован мной в задаче 1.*
Каждый процесс получает ширину и высоту изображения, процесс 0-го ранга получает одномерный вектор изначального изображения и вектор для записи итогового изображения.

Далее в процессе 0-го ранга:
Каждому ненулевому процессу присылается ширина изображения (высоту изображения им знать не надо).
Основываясь на количестве процессов ненулевого ранга запускается цикл, в котором процессам, которым будет послано 3 строки шириной исходного изображения. После в этом же цикле 0-ой процесс получает от ненулевых процессов результат. Если количество процессов превышает кол-во строк в итерации цикла, то им пока что не посылается ничего. После цикла всем процессам посылается сигнал о завершении работы.
Вычисляется первая и последняя строка изображения (они зависят только от двух строк; это сделано для упрощения кода, и две строки на производительность не сильно повлияют).

В процессах ненулевого ранга:
Получается ширина изображения.
Запускается цикл, в котором сначала проверяется сигнал о выходе, и если сигнал невыходной, получается 3 строки, у которых вычисляется 1 строка с помощью матрицы нормального распределения, которая отправляется нулевому процессу.

2024-11-27 19:22 UTC, artich02 requested changes

2024-11-27 19:22 UTC, artich02 commented on tasks/seq/oturin_a_image_smoothing/include/ops_seq.hpp
> +struct pix {
this structure is not used anywhere at all

2024-11-27 19:50 UTC, DSolo03 requested changes

2024-11-27 19:50 UTC, DSolo03 commented on tasks/mpi/oturin_a_image_smoothing/src/ops_mpi.cpp
> +}
better move this function to `oturin_a_image_smoothing_mpi` to not doubling the same code

2024-11-27 22:25 UTC, DSolo03 approved these changes

2024-11-28 04:18 UTC, ovVrLFg8ks commented on tasks/seq/oturin_a_image_smoothing/include/ops_seq.hpp
> +struct pix {
Removed

2024-11-28 09:12 UTC, artich02 approved these changes

2024-12-01 22:58 UTC, allnes commented on tasks/mpi/oturin_a_image_smoothing/func_tests/main.cpp
> +    vec[i] = gen() % 100;
why do you use interval [0, 99] and not [0, 255]

2024-12-02 18:37 UTC, ovVrLFg8ks commented on tasks/mpi/oturin_a_image_smoothing/func_tests/main.cpp
> +    vec[i] = gen() % 100;
forgor to correct old randomizer
fixed

2024-12-02 23:04 UTC, allnes approved these changes

2024-12-04 03:20 UTC, aobolensk requested changes

2024-12-04 13:58 UTC, ovVrLFg8ks commented on tasks/seq/oturin_a_image_smoothing/func_tests/main.cpp
> +#else
now enabled
results may differ by 1 due to float kernel

2024-12-08 07:36 UTC, aobolensk approved these changes

2024-12-08 07:36 UTC, aobolensk commented on tasks/mpi/oturin_a_image_smoothing/include/ops_mpi.hpp
> +std::vector<uint8_t> getRandomVector(int sz);
Please, move test function to the test module

2024-12-08 07:36 UTC, aobolensk commented on tasks/seq/oturin_a_image_smoothing/src/ops_seq.cpp
> +// #include <algorithm>
Remove commented out code

2024-12-08 07:37 UTC, merged