Fix revert. Ковальчук Александр. Задача 1. Вариант 13. Максимальное значение элементов матрицы
learning-process/ppc-2024-autumn pull request #367
Opened 2024-11-27 15:42 UTC by KADCHDR

https://github.com/learning-process/ppc-2024-autumn/pull/181  performance has been improved by improving the algorithm and eliminating unnecessary checks.

2024-12-01 23:00 UTC, allnes commented on tasks/seq/kovalchuk_a_max_of_vector_elements/src/ops_seq.cpp
> +      }
please check it in validation and not process in run()

2024-12-04 03:21 UTC, aobolensk requested changes

2024-12-04 03:21 UTC, aobolensk commented on tasks/seq/kovalchuk_a_max_of_vector_elements/func_tests/main.cpp
> +
Please either wrap with namespace or make static to avoid collisions

2024-12-11 19:07 UTC, aobolensk commented
Please, note what was the fix in the description

2024-12-27 00:37 UTC, KADCHDR commented on tasks/seq/kovalchuk_a_max_of_vector_elements/func_tests/main.cpp
> +
fixed

2024-12-27 00:37 UTC, KADCHDR commented on tasks/seq/kovalchuk_a_max_of_vector_elements/src/ops_seq.cpp
> +      }
fixed

2024-12-27 16:01 UTC, merged