Кораблев Владлен. Задача 3. Вариант 14.  Быстрая сортировка с простым слиянием.
learning-process/ppc-2024-autumn pull request #368
Opened 2024-11-27 16:57 UTC by korablev-vm

# Быстрая сортировка с простым слиянием

## 1. Последовательная реализация

### Описание
Последовательная реализация алгоритма быстрой сортировки выполняется следующим образом:
1. **Базовый случай**: Если входной массив содержит один или менее элементов, он возвращается без изменений.
2. **Выбор опорного элемента**: В качестве опорного элемента выбирается средний элемент массива.
3. **Разделение массива**: Массив делится на две части:
   - Элементы, которые меньше опорного.
   - Элементы, которые больше опорного.
4. **Рекурсивная сортировка**: Обе части рекурсивно сортируются с использованием того же алгоритма.
5. **Слияние**: Отсортированные части объединяются с элементами, равными опорному, используя функцию `merge`. Эта функция проходит по двум отсортированным массивам и объединяет их в один, сохраняя порядок.

---

## 2. Параллельная реализация

###  Основные этапы:
1. **Рассылка данных**:
   - Корневой процесс (ранг 0) отправляет исходный массив всем процессам с использованием `boost::mpi::broadcast`. 

2. **Разбиение данных**:
   - Общий массив делится на части, размер которых определяется количеством процессов. Расчет производится каждым процессом.
   - Оставшиеся элементы равномерно распределяются между процессами с младшими рангами.
   - Используются векторы `sizes` и `displs`  для точного определения, какая часть массива отправляется каждому процессу.

3. **Локальная сортировка**:
   - Каждый процесс получает свою часть данных через `boost::mpi::scatterv` и выполняет сортировку локально с помощью функции `quick_sort_with_merge`.

4. **Сбор данных**:
   - Отсортированные части данных возвращаются на корневой процесс с использованием `boost::mpi::gatherv`.

5. **Слияние отсортированных частей**:
   - Корневой процесс последовательно сливает отсортированные части с помощью функции `merge`, сохраняя порядок элементов.

2024-11-27 17:34 UTC, korablev-vm commented
There is an interesting problem with gcc when it has optimization enabled.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107852
This is very strange, but you will have to get out of it using suboptimal methods

2024-12-01 09:53 UTC, venn2713 requested changes
Работа хорошая, думаю внесение этих изменений даст прирост в скорости

2024-12-01 09:53 UTC, venn2713 commented on tasks/mpi/korablev_v_quick_sort_simple_merge/func_tests/main.cpp
> +      ASSERT_NEAR(parallel_result[i], sequential_result[i], 1e-9);
Используйте пожалуйста EXPECT в конце теста

2024-12-01 09:53 UTC, venn2713 commented on tasks/mpi/korablev_v_quick_sort_simple_merge/func_tests/main.cpp
> +    ASSERT_TRUE(true) << "Process " << world.rank() << " completed successfully.";
Аналогично. Это проследняя проверка в тесте, она желательно должна быть EXPECT, А вообще ASSERT_TRUE(true) выглядит забавно 😁
Я думаю вы должны записать результат работы run в переменную и с ней сравнить?

2024-12-01 09:53 UTC, venn2713 commented on tasks/mpi/korablev_v_quick_sort_simple_merge/func_tests/main.cpp
> +      ASSERT_EQ(out[i], expected_output[i]);
Аналогично, хоть и дебаг, но тест в проде, пускай будет EXPECT

2024-12-01 09:53 UTC, venn2713 commented on tasks/mpi/korablev_v_quick_sort_simple_merge/perf_tests/main.cpp
> +    ASSERT_EQ(vector_size, out.size());
EXPECT 😉

2024-12-01 09:53 UTC, venn2713 commented on tasks/mpi/korablev_v_quick_sort_simple_merge/perf_tests/main.cpp
> +    ASSERT_EQ(vector_size, out.size());
Аналогично 😁

2024-12-01 09:53 UTC, venn2713 commented on tasks/mpi/korablev_v_quick_sort_simple_merge/src/ops_mpi.cpp
> +  std::vector<int> result;
Думаю можно добавить нечто вроде
`result.reserve(left.size() + right.size());`
Тогда не придется перевыделять память много раз
Ещё я бы подумал перенести эту функцию в header как `inline`

2024-12-01 09:53 UTC, venn2713 commented on tasks/mpi/korablev_v_quick_sort_simple_merge/src/ops_mpi.cpp
> +  }
Думаю оптимальнее будет
```cpp
result.insert(result.end(), left.begin() + i, left.end());
result.insert(result.end(), right.begin() + j, right.end());
  ```

2024-12-01 09:53 UTC, venn2713 commented on tasks/mpi/korablev_v_quick_sort_simple_merge/src/ops_mpi.cpp
> +    return res;
Думаю можно сразу вернуть
```
return std::vector<int>(arr.begin(), arr.end());
```

2024-12-01 09:53 UTC, venn2713 commented on tasks/mpi/korablev_v_quick_sort_simple_merge/src/ops_mpi.cpp
> +  return finalResult;
Возможно если разбить на три массива, один left, другой right а третий equal то мы уменьшим сложность и справимся за 2 слияния, в формате
```cpp
std::vector<int> merged = merge(sortedLeft, equal);
return merge(merged, sortedRight);
  ```

2024-12-01 09:53 UTC, venn2713 commented on tasks/mpi/korablev_v_quick_sort_simple_merge/src/ops_mpi.cpp
> +}
Думаю тут все хорошо, единственное что можно было бы добавить защиту "от дурака", но возможно это излишне

2024-12-01 09:53 UTC, venn2713 commented on tasks/mpi/korablev_v_quick_sort_simple_merge/src/ops_mpi.cpp
> +std::vector<int> korablev_v_qucik_sort_simple_merge_mpi::QuickSortSimpleMergeParallel::merge(
Функции похожи для seq и mpi, вынести их из классов могло бы сократить код я думаю

2024-12-01 09:53 UTC, venn2713 commented on tasks/mpi/korablev_v_quick_sort_simple_merge/src/ops_mpi.cpp
> +    }
Возможно это особенности реализации, а может быть можно более эффективно скопировать через стандартные библиотеки, не уверен

2024-12-01 09:53 UTC, venn2713 commented on tasks/seq/korablev_v_quick_sort_simple_merge/func_tests/main.cpp
> +    ASSERT_EQ(out[i], expected_output[i]);
Я думаю не обязательно проходиться поэлементно, просто `EXPECT_EQ(out[i], expected_output[i])` должен справиться

2024-12-01 23:02 UTC, allnes commented on tasks/mpi/korablev_v_quick_sort_simple_merge/func_tests/main.cpp
> +TEST(korablev_v_quick_sort_mpi, test_vector_10000) { run_quick_sort_test_for_vector_size(10000); }
please add prime values, 2^n

2024-12-01 23:03 UTC, allnes commented on tasks/mpi/korablev_v_quick_sort_simple_merge/func_tests/main.cpp
> +TEST(korablev_v_quick_sort_mpi, test_vector_10) { run_quick_sort_test_for_vector_size(10); }
please check scheme of reverse sort

2024-12-03 07:18 UTC, korablev-vm commented on tasks/mpi/korablev_v_quick_sort_simple_merge/src/ops_mpi.cpp
> +    return res;
К сожалению, из-за бага gcc, о котором я писал ранее, не получится, хотя я полностью с Вами согласен.

2024-12-03 07:20 UTC, korablev-vm commented on tasks/mpi/korablev_v_quick_sort_simple_merge/src/ops_mpi.cpp
> +}
А это уже проблема с покрытием тестами. Валидация в mpi версии тестов сначала проходит у параллельной части, поэтому найденные ошибки в данных (данные одинаковые, конечно же) сразу завершают тест. Конечно же, в отдельной seq реализации все есть

2024-12-03 07:21 UTC, korablev-vm commented on tasks/mpi/korablev_v_quick_sort_simple_merge/src/ops_mpi.cpp
> +    }
Тут да, раз уж делаем все с простым слиянием, и тут тоже можно его использовать. Но согласен, можно и через стандартные библиотеки

2024-12-03 07:25 UTC, shvedovav requested changes

2024-12-03 07:25 UTC, shvedovav commented on tasks/mpi/korablev_v_quick_sort_simple_merge/func_tests/main.cpp
> +}
Here you can create a reverse sorted vector, as discussed in the last practical lesson.

2024-12-03 07:25 UTC, shvedovav commented on tasks/mpi/korablev_v_quick_sort_simple_merge/func_tests/main.cpp
> +  std::vector<int> out(array_size, 0.0);
It is better to add random tests instead - with one, two, and so on elements.

2024-12-03 07:25 UTC, shvedovav commented on tasks/mpi/korablev_v_quick_sort_simple_merge/include/ops_mpi.hpp
> +  std::vector<int> quick_sort_with_merge(const std::span<int>& arr);
I propose to avoid code duplication by removing the sorting and merging functions

2024-12-03 09:52 UTC, shvedovav approved these changes

2024-12-03 09:55 UTC, venn2713 approved these changes

2024-12-04 03:23 UTC, aobolensk requested changes

2024-12-04 03:23 UTC, aobolensk commented on tasks/mpi/korablev_v_quick_sort_simple_merge/func_tests/main.cpp
> +namespace korablev_v_qucik_sort_simple_merge_mpi {
```suggestion
namespace korablev_v_quick_sort_simple_merge_mpi {
```

2024-12-04 03:23 UTC, aobolensk commented on tasks/mpi/korablev_v_quick_sort_simple_merge/func_tests/main.cpp
> +
Please, add test for 0

2024-12-08 07:39 UTC, aobolensk approved these changes

2024-12-08 11:14 UTC, allnes commented on tasks/mpi/korablev_v_quick_sort_simple_merge/func_tests/main.cpp
> +TEST(korablev_v_quick_sort_mpi, test_vector_10) { run_quick_sort_test_for_vector_size(10); }
did you fix it?

2024-12-08 11:19 UTC, korablev-vm commented on tasks/mpi/korablev_v_quick_sort_simple_merge/func_tests/main.cpp
> +TEST(korablev_v_quick_sort_mpi, test_vector_10) { run_quick_sort_test_for_vector_size(10); }
In the tests, a reverse-sorted array is now being used, and a comment has been added to the test file. Did I understand the point of the remark correctly?

2024-12-08 11:27 UTC, allnes approved these changes

2024-12-08 11:27 UTC, merged