Мухина Маргарита. Задача 1. Вариант 4.  Минимальное значение элементов вектора.
learning-process/ppc-2024-autumn pull request #37
Opened 2024-10-23 16:55 UTC by MargaritaMuhina

Описание последовательной задачи:
Каждый элемент вектора, сравниваем со значением переменной, в которой хранится минимальное значение вектора. Если значение данного элемента вектора меньше чем значение переменной, то записываем значение данного элемента вектора в переменную.

Описание MPI задачи:
- Делится вектор на фрагменты (по количеству процессов).
- Процесс с рангом 0 распределяет фрагменты между процессами.
- Каждый процесс получает свой фрагмент (local_input_).
- Каждый процесс находит минимальное значение в своем фрагменте.
- Используется функция reduce с оператором minimum для сбора минимального значения из всех процессов.
- Результат записывается в переменную res на процессе с рангом 0.
- Процесс с рангом 0 записывает найденное минимальное значение в выходной буфер.

2024-10-23 17:34 UTC, Semyon1104 commented on tasks/mpi/muhina_m_min_of_vector_elements/func_tests/main.cpp
> +  muhina_m_min_of_vector_elements_mpi::MinOfVectorMPIParallel testMpiTaskParallel(taskDataPar);
change the name of tasks

2024-10-23 17:34 UTC, Semyon1104 commented on tasks/seq/muhina_m_min_of_vector_elements/include/ops_seq.hpp
> +  std::string ops;
remove this line

2024-10-23 19:30 UTC, AndreySorokin7 commented on tasks/mpi/muhina_m_min_of_vector_elements/include/ops_mpi.hpp
> +        int res{};
The names of private class fields must end with an underscore ( _ ). Make this change in other classes as well.

2024-10-23 19:30 UTC, AndreySorokin7 commented on tasks/seq/muhina_m_min_of_vector_elements/src/ops_seq.cpp
> +  int mini = 100000000;
Is this the largest number that can come to the entrance?

2024-10-23 19:30 UTC, AndreySorokin7 commented on tasks/mpi/muhina_m_min_of_vector_elements/src/ops_mpi.cpp
> +        vec[i] = gen() % 100;
Please validate on negative values as well

2024-10-23 19:30 UTC, AndreySorokin7 commented on tasks/mpi/muhina_m_min_of_vector_elements/src/ops_mpi.cpp
> +    res = 0;
Why is res assigned the value 0? Is it used further somewhere?If this is necessary for certain tests, then they should be written

2024-10-23 19:30 UTC, AndreySorokin7 commented on tasks/seq/muhina_m_min_of_vector_elements/include/ops_seq.hpp
> +  int res{};
Similar defects need to be fixed in all files

2024-10-24 18:30 UTC, Semyon1104 approved these changes

2024-10-25 10:26 UTC, MargaritaMuhina commented on tasks/mpi/muhina_m_min_of_vector_elements/func_tests/main.cpp
> +  muhina_m_min_of_vector_elements_mpi::MinOfVectorMPIParallel testMpiTaskParallel(taskDataPar);
fixed

2024-10-25 10:26 UTC, MargaritaMuhina commented on tasks/seq/muhina_m_min_of_vector_elements/include/ops_seq.hpp
> +  std::string ops;
fixed

2024-10-25 10:26 UTC, MargaritaMuhina commented on tasks/seq/muhina_m_min_of_vector_elements/src/ops_seq.cpp
> +  int mini = 100000000;
fixed

2024-10-25 10:27 UTC, MargaritaMuhina commented on tasks/mpi/muhina_m_min_of_vector_elements/src/ops_mpi.cpp
> +        vec[i] = gen() % 100;
fixed

2024-10-25 10:27 UTC, MargaritaMuhina commented on tasks/mpi/muhina_m_min_of_vector_elements/src/ops_mpi.cpp
> +    res = 0;
fixed

2024-10-25 10:27 UTC, MargaritaMuhina commented on tasks/seq/muhina_m_min_of_vector_elements/include/ops_seq.hpp
> +  int res{};
fixed

2024-10-25 10:54 UTC, AndreySorokin7 approved these changes

2024-10-25 18:08 UTC, allnes commented on tasks/seq/muhina_m_min_of_vector_elements/src/ops_seq.cpp
> +  }
please check empty vector in validation

2024-10-26 00:07 UTC, aobolensk requested changes

2024-10-26 00:07 UTC, aobolensk commented on tasks/mpi/muhina_m_min_of_vector_elements/src/ops_mpi.cpp
> +}
Please, move this method to the tests. It is used only there

2024-10-27 17:02 UTC, MargaritaMuhina commented on tasks/mpi/muhina_m_min_of_vector_elements/src/ops_mpi.cpp
> +}
moved

2024-10-27 17:03 UTC, MargaritaMuhina commented on tasks/seq/muhina_m_min_of_vector_elements/src/ops_seq.cpp
> +  }
fixed

2024-10-28 01:26 UTC, aobolensk approved these changes

2024-10-28 14:13 UTC, merged