Зайцев Артем. Задача 2. Вариант 8. Обобщенная передача от одного всем (scatter).
learning-process/ppc-2024-autumn pull request #370
Opened 2024-11-27 17:54 UTC by aortemon

### The problem 
Finding the minimum element of a vector
### Algorithm
1. Divide the vector into sub-vectors and distribute them among the threads.
2. Find the local minimums of each subvector.
3. Find the global minimum among local ones.
### Implementation
1. Signatures of the self-written `scatter(...)` and `MPI_Scatter(...)` are identical. 
2. If it's impossible to distribute the elements of the vector equally between the processes, the unallocated values from the end of the vector will be taken into account and processed in the root process. 
3. `class TestMPITaskParallel<T, func>(...)` is a template: when creating an instance, you must specify the type `T` of values in the vector and the function `func` that distributes data to processes. The tests consider the options `T ∈ {int, double}` and `func ∈ {scatter, MPI_Scatter}`.

2024-11-27 18:55 UTC, Sean0450 approved these changes

2024-11-27 20:38 UTC, Ksu04 commented on tasks/mpi/zaitsev_a_scatter/include/ops_mpi.hpp
> +#include <gtest/gtest.h>
Delete this directive

2024-11-27 20:50 UTC, aortemon commented on tasks/mpi/zaitsev_a_scatter/include/ops_mpi.hpp
> +#include <gtest/gtest.h>
Removed

2024-11-28 04:30 UTC, Ksu04 approved these changes

2024-11-28 15:17 UTC, aortemon commented on tasks/mpi/zaitsev_a_scatter/perf_tests/main.cpp
> +  // Create Perf attributes
Done

2024-11-28 15:17 UTC, aortemon commented on tasks/mpi/zaitsev_a_scatter/func_tests/main.cpp
> +// Copyright 2023 Liolya Seledkina
Done

2024-11-28 15:21 UTC, PolinaSidorina approved these changes

2024-12-01 23:05 UTC, allnes commented on tasks/mpi/zaitsev_a_scatter/func_tests/main.cpp
> +#include <gtest/gtest.h>
where boost realization? please separate it into other directory

2024-12-04 03:49 UTC, aobolensk requested changes

2024-12-04 03:49 UTC, aobolensk commented on tasks/mpi/zaitsev_a_scatter/func_tests/main.cpp
> +  vec[0] = extrema;
Why do you need this line?

2024-12-04 03:49 UTC, aobolensk commented on tasks/mpi/zaitsev_a_scatter/func_tests/main.cpp
> +  vec[0] = extrema;
Same here

2024-12-04 03:49 UTC, aobolensk commented on tasks/mpi/zaitsev_a_scatter/func_tests/main.cpp
> +TEST(zaitsev_a_scatter, test__func_handwritten__dtype_int__size_1) { test_int<zaitsev_a_scatter::scatter>(1); }
Please, test empty arrays

2024-12-04 03:49 UTC, aobolensk commented on tasks/mpi/zaitsev_a_scatter/func_tests/main.cpp
> +
Please add test on random numbers

2024-12-05 02:25 UTC, aortemon commented on tasks/mpi/zaitsev_a_scatter/func_tests/main.cpp
> +  vec[0] = extrema;
The 15th line quarantees the existence of the predefined lower extrema in a vector. This allows us to know the value of the desired minimum in advance and to skip the part of tests where an unknown minimum would be searched.

2024-12-05 02:59 UTC, aortemon commented on tasks/mpi/zaitsev_a_scatter/func_tests/main.cpp
> +#include <gtest/gtest.h>
Separated

2024-12-05 13:43 UTC, aortemon commented on tasks/mpi/zaitsev_a_scatter/func_tests/main.cpp
> +  vec[0] = extrema;
You are right, it was a mistake to use this approach. I discovered data duplication in streams which contributed to the incomplete coverage of the vector in the search for the minimum. I've fixed this issue. Tests you requested were added.

2024-12-06 00:04 UTC, allnes approved these changes

2024-12-08 07:49 UTC, aobolensk approved these changes

2024-12-08 07:49 UTC, merged