Ковальчук Александр. Задача 2. Вариант 15. Ленточная горизонтальная схема
learning-process/ppc-2024-autumn pull request #371
Opened 2024-11-27 18:14 UTC by KADCHDR

Последовательная версия:
Последовательное вычисление скалярного произведения каждой строки матрицы на вектор и сохранение результата в выходной вектор
Параллельная версия:
Матрица делится построчно между процессами, каждому процессу выделяется часть матрицы и общий вектор, каждый процесс вычисляет скалярное произведение своей части матрицы на вектор, затем с помощью reduce собираются результаты для выходного вектора

2024-12-11 17:16 UTC, keshaproger requested changes

2024-12-11 17:16 UTC, keshaproger commented on tasks/mpi/kovalchuk_a_horizontal_tape_scheme/func_tests/main.cpp
> +
add more tests for different cases

2024-12-11 18:40 UTC, KADCHDR commented on tasks/mpi/kovalchuk_a_horizontal_tape_scheme/func_tests/main.cpp
> +
fixed

2024-12-11 18:41 UTC, keshaproger approved these changes

2024-12-11 20:34 UTC, kobych requested changes

2024-12-11 20:34 UTC, kobych commented on tasks/mpi/kovalchuk_a_horizontal_tape_scheme/include/ops_mpi.hpp
> +const int MAXIMUMGEN = 999;
do you use this?

2024-12-11 21:03 UTC, KADCHDR commented on tasks/mpi/kovalchuk_a_horizontal_tape_scheme/include/ops_mpi.hpp
> +const int MAXIMUMGEN = 999;
thx, fixed

2024-12-11 21:03 UTC, kobych approved these changes

2024-12-14 10:50 UTC, aobolensk approved these changes

2024-12-15 19:13 UTC, allnes approved these changes

2024-12-15 19:13 UTC, merged