Холин Кирилл. Задача 2. Вариант 23. Итеративные методы (Зейделя).
learning-process/ppc-2024-autumn pull request #372
Opened 2024-11-27 18:16 UTC by Kirius257

### Постановка задачи
_Исходные данные_
Дана СЛАУ AX = B, где A- квадратная матрица коэффициентов, X -вектор неизвестных, B - вектор свободных коэффициентов.

_Задача_
 Требуется решить систему итеративным методом Зейделя. 

_Описание решения_
Привести уравнение к виду X = CX` + F, где C - матрица коэффициентов с нулями по главной диагонали, полученная в результате следующих преобразований: C = E - A и коэффициенты имеют вид c ij = - (a ij) /(a ii) , a - коэффициенты матрицы A, F - новый вектор B с коэффициентами f i =  (b i )/ (a ii). Зададим некоторое начальное приближение X0 и положительное число эпсилон для указания точности решения СЛАУ.  Условно на нулевой итерации вектор-решение СЛАУ состоит из 0. Первое неизвестно x1 можно найти в результате подстановки X0 в X = CX` + F. Полученную компоненту x1 подставляем в x2, а  во все остальные ещё ненайденные неизвестные подставляем X0. Аналогичным образом находим остальные неизвестные.

В результате первой итерации получено первое приближение. Найдём максимальную разницу между компонентами векторов на нулевой и первой итерациях по модулю. Если максимальная разница оказалась больше заданной точности после проделанной итерации, то алгоритм нахождения решения СЛАУ завершается. В качестве решения можно взять вектор на предыдущей итерации.
**[SEQ]**
1. Заводим переменные под СЛАУ, как указано в описании решения. Приводим к итеративному виду X = CX` + F. 
2. Заведём два вектора X_next для вычисления новых неизвестных на следующей итерации и X_prev для сохранения компонент X_next перед началом следующей итерации.
3. В начале найдём X_next на первой итерации, а X_prev положим нулевым вектором. 
4. Найдём максимальную разницу компонент X_next и X_prev по модулю. Если разница меньше заданной точности, продолжаем алгоритм, сделав X_prev X_next, а X_next после обнулить.
5. После остановки алгоритма результатом будет X_prev, являющийся решением СЛАУ.

**[MPI]**
Аналогично SEQ.
_Схема распараллеливания_
Матрицу C разбить на верхне-треугольную и нижне-треугольную. Каждому процессу равномерно распределить элементы каждой строки матриц.

_Отличие_
Отличие лишь в том, что коэффициенты c ij будут перемножаться сначала с вычисленными компонентами X_next из нижне-треугольной матрицы, а после со старыми компонентами, которые содержит X_prev, из верхне-треугольной матрицы.

_Эффективность_
Все процессы знают, какие элементы матриц они вычисляют. Доступ к элементам  матриц стал удобен. В результате скорость вычисления неизвестных на каждой итерации должна увеличиться.
В результате разбиения все процессы без проблем знают

2024-11-28 19:42 UTC, NikitaKoshkin commented on tasks/mpi/kholin_k_iterative_methods_Seidel/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
remove unnecessary libraries

2024-11-28 19:42 UTC, NikitaKoshkin commented on tasks/mpi/kholin_k_iterative_methods_Seidel/include/ops_mpi.hpp
> +#include <vector>
remove unnecessary libraries

2024-11-28 19:42 UTC, NikitaKoshkin commented on tasks/seq/kholin_k_iterative_methods_Seidel/include/ops_seq.hpp
> +
remove unnecessary libraries

2024-11-28 19:42 UTC, NikitaKoshkin commented on tasks/mpi/kholin_k_iterative_methods_Seidel/src/ops_mpi.cpp
> +//
delete comment

2024-11-28 19:42 UTC, NikitaKoshkin commented on tasks/seq/kholin_k_iterative_methods_Seidel/src/ops_seq.cpp
> +//
delete comment

2024-11-28 19:42 UTC, NikitaKoshkin commented on tasks/mpi/kholin_k_iterative_methods_Seidel/func_tests/main.cpp
> +//
delete comment

2024-11-28 19:42 UTC, NikitaKoshkin commented on tasks/mpi/kholin_k_iterative_methods_Seidel/func_tests/main.cpp
> +//   boost::mpi::environment env(argc, argv);
If you don't use it, it's better to remove it comment

2024-11-28 19:42 UTC, NikitaKoshkin commented on tasks/mpi/kholin_k_iterative_methods_Seidel/include/ops_mpi.hpp
> +//
delete comment

2024-11-28 19:42 UTC, NikitaKoshkin commented on tasks/mpi/kholin_k_iterative_methods_Seidel/perf_tests/main.cpp
> +//
delete comment

2024-11-28 19:42 UTC, NikitaKoshkin commented on tasks/mpi/kholin_k_iterative_methods_Seidel/src/ops_mpi.cpp
> +//
delete comment

2024-11-28 19:42 UTC, NikitaKoshkin commented on tasks/seq/kholin_k_iterative_methods_Seidel/func_tests/main.cpp
> +//
delete comment

2024-11-28 19:42 UTC, NikitaKoshkin commented on tasks/seq/kholin_k_iterative_methods_Seidel/func_tests/main.cpp
> +  //
delete comment

2024-11-28 19:42 UTC, NikitaKoshkin commented on tasks/seq/kholin_k_iterative_methods_Seidel/func_tests/main.cpp
> +// int main(int argc, char **argv) {
If you don't use it, it's better to remove it comment

2024-11-28 19:42 UTC, NikitaKoshkin commented on tasks/seq/kholin_k_iterative_methods_Seidel/include/ops_seq.hpp
> +//
delete "//"

2024-11-28 19:42 UTC, NikitaKoshkin commented on tasks/seq/kholin_k_iterative_methods_Seidel/perf_tests/main.cpp
> +//
delete comment

2024-11-28 19:42 UTC, NikitaKoshkin commented on tasks/seq/kholin_k_iterative_methods_Seidel/perf_tests/main.cpp
> +// int main(int argc, char **argv) {
If you don't use it, it's better to remove it comment

2024-11-28 19:49 UTC, NikitaKoshkin commented on tasks/mpi/kholin_k_iterative_methods_Seidel/src/ops_mpi.cpp
> +        if (i == j) {
you can remove the "if" condition

2024-11-28 20:21 UTC, KolodkinGrigorii commented on tasks/mpi/kholin_k_iterative_methods_Seidel/perf_tests/main.cpp
> +  std::unique_ptr<float[]> out(new float[count_rows]);
Don't use std::unique_ptr

2024-11-28 20:21 UTC, KolodkinGrigorii commented on tasks/seq/kholin_k_iterative_methods_Seidel/src/ops_seq.cpp
> +  X0 = new float[n_rows];
Add std::fill for X0

2024-11-28 20:45 UTC, Kirius257 commented on tasks/mpi/kholin_k_iterative_methods_Seidel/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
Fixed!

2024-11-28 20:45 UTC, Kirius257 commented on tasks/mpi/kholin_k_iterative_methods_Seidel/include/ops_mpi.hpp
> +#include <vector>
Fixed!

2024-11-28 20:45 UTC, Kirius257 commented on tasks/seq/kholin_k_iterative_methods_Seidel/include/ops_seq.hpp
> +
Fixed!

2024-11-28 20:47 UTC, Kirius257 commented on tasks/mpi/kholin_k_iterative_methods_Seidel/src/ops_mpi.cpp
> +//
Fixed!My stupid mistake. While adding changes to git I lost them and had to put // to get them back again.

2024-11-28 20:48 UTC, Kirius257 commented on tasks/seq/kholin_k_iterative_methods_Seidel/src/ops_seq.cpp
> +//
Fixed! Yeah, that's where I missed it too //.

2024-11-28 20:48 UTC, Kirius257 commented on tasks/seq/kholin_k_iterative_methods_Seidel/func_tests/main.cpp
> +  //
Fixed!

2024-11-28 20:48 UTC, Kirius257 commented on tasks/seq/kholin_k_iterative_methods_Seidel/func_tests/main.cpp
> +// int main(int argc, char **argv) {
Fixed! Generally speaking, I use this when debugging my code, but now I don't need it anymore.

2024-11-28 20:49 UTC, Kirius257 commented on tasks/seq/kholin_k_iterative_methods_Seidel/include/ops_seq.hpp
> +//
Fixed!

2024-11-28 20:49 UTC, Kirius257 commented on tasks/seq/kholin_k_iterative_methods_Seidel/perf_tests/main.cpp
> +//
Fixed!

2024-11-28 20:49 UTC, Kirius257 commented on tasks/seq/kholin_k_iterative_methods_Seidel/perf_tests/main.cpp
> +// int main(int argc, char **argv) {
Fixed! I don`t use it anymore.

2024-11-28 20:50 UTC, Kirius257 commented on tasks/mpi/kholin_k_iterative_methods_Seidel/src/ops_mpi.cpp
> +        if (i == j) {
Fixed!Yes, you're right indeed. I call this method only for the null process in my programme.

2024-11-28 20:50 UTC, Kirius257 commented on tasks/mpi/kholin_k_iterative_methods_Seidel/perf_tests/main.cpp
> +  std::unique_ptr<float[]> out(new float[count_rows]);
Fixed! I wanted to try the smart pointers functionality, but yeah, probably unnecessary.

2024-11-28 20:51 UTC, Kirius257 commented on tasks/seq/kholin_k_iterative_methods_Seidel/src/ops_seq.cpp
> +  X0 = new float[n_rows];
Fixed! Forgot to initialise with the initial value, sorry.

2024-11-28 21:05 UTC, Kirius257 commented on tasks/mpi/kholin_k_iterative_methods_Seidel/perf_tests/main.cpp
> +  kholin_k_iterative_methods_Seidel_mpi::freeA_();
Fixed! Thank you for noticing.

2024-11-28 21:16 UTC, Kirius257 commented on tasks/mpi/kholin_k_iterative_methods_Seidel/perf_tests/main.cpp
> +  kholin_k_iterative_methods_Seidel_mpi::freeA_();
Fixed!

2024-11-28 21:52 UTC, Kirius257 commented on tasks/mpi/kholin_k_iterative_methods_Seidel/func_tests/main.cpp
> +//
fixed!

2024-11-28 21:52 UTC, Kirius257 commented on tasks/mpi/kholin_k_iterative_methods_Seidel/func_tests/main.cpp
> +//   boost::mpi::environment env(argc, argv);
Fixed!

2024-11-28 21:52 UTC, Kirius257 commented on tasks/mpi/kholin_k_iterative_methods_Seidel/include/ops_mpi.hpp
> +//
Fixed!

2024-11-28 21:52 UTC, Kirius257 commented on tasks/mpi/kholin_k_iterative_methods_Seidel/perf_tests/main.cpp
> +//
Fixed!

2024-11-28 21:53 UTC, Kirius257 commented on tasks/mpi/kholin_k_iterative_methods_Seidel/src/ops_mpi.cpp
> +//
Fixed!

2024-11-28 21:53 UTC, Kirius257 commented on tasks/seq/kholin_k_iterative_methods_Seidel/func_tests/main.cpp
> +//
Fixed!

2024-11-28 23:01 UTC, NikitaKoshkin approved these changes

2024-11-29 07:50 UTC, KolodkinGrigorii approved these changes

2024-12-01 23:06 UTC, allnes commented on .github/workflows/main.yml
> +  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
please don't remove not own files

2024-12-01 23:08 UTC, allnes commented on tasks/mpi/kholin_k_iterative_methods_Seidel/src/ops_mpi.cpp
> +         IsQuadro(taskData->inputs_count[0], taskData->inputs_count[1]);
where do you check a single solution of linear system?

2024-12-01 23:09 UTC, allnes commented on tasks/mpi/kholin_k_iterative_methods_Seidel/src/ops_mpi.cpp
> +  return true;
please fill it in tests, you can only process data here, not create

2024-12-01 23:09 UTC, allnes commented on tasks/mpi/kholin_k_iterative_methods_Seidel/src/ops_mpi.cpp
> +  C = nullptr;
I think better use std::vector

2024-12-03 21:05 UTC, Kirius257 commented on tasks/mpi/kholin_k_iterative_methods_Seidel/func_tests/main.cpp
> +    ASSERT_EQ(testMpiTaskSequential.validation(), true);
Hi. What answers am I not checking? How can I synchronise the test if all data is random, and all coefficients are float? It's quite complicated and time consuming. Explain what you mean, please.

2024-12-03 21:06 UTC, Kirius257 commented on tasks/seq/kholin_k_iterative_methods_Seidel/src/ops_seq.cpp
> +float* A_;
It is needed to check the matrix for validation.

2024-12-03 21:10 UTC, Kirius257 commented on tasks/mpi/kholin_k_iterative_methods_Seidel/src/ops_mpi.cpp
> +  C = nullptr;
fixed

2024-12-03 21:10 UTC, Kirius257 commented on tasks/mpi/kholin_k_iterative_methods_Seidel/src/ops_mpi.cpp
> +  return true;
fixed

2024-12-03 21:10 UTC, Kirius257 commented on .github/workflows/main.yml
> +  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
fixed

2024-12-03 21:29 UTC, Kirius257 commented on tasks/seq/kholin_k_iterative_methods_Seidel/src/ops_seq.cpp
> +float* A_;
Can I for example just remove this singleton and just from taskData->input[0], which stores the generated dominance matrix, pass it to the diagonal dominance check method?

2024-12-03 21:32 UTC, Kirius257 commented on tasks/mpi/kholin_k_iterative_methods_Seidel/func_tests/main.cpp
> +    ASSERT_EQ(testMpiTaskSequential.validation(), true);
All right. I can test with non-random data to show you that the responses of my tasks are identical. OK?

2024-12-03 21:40 UTC, Kirius257 commented on tasks/mpi/kholin_k_iterative_methods_Seidel/src/ops_mpi.cpp
> +         IsQuadro(taskData->inputs_count[0], taskData->inputs_count[1]);
In process fixing...

2024-12-04 03:58 UTC, aobolensk requested changes

2024-12-04 03:58 UTC, aobolensk commented on tasks/seq/kholin_k_iterative_methods_Seidel/src/ops_seq.cpp
> +std::vector<float> A_;
Please move all these internals to the task class

2024-12-04 03:58 UTC, aobolensk commented on tasks/mpi/kholin_k_iterative_methods_Seidel/func_tests/main.cpp
> +
Please, test on more different data shapes

2024-12-04 21:58 UTC, Kirius257 commented on tasks/mpi/kholin_k_iterative_methods_Seidel/func_tests/main.cpp
> +
Fixed! I created more different data

2024-12-04 21:59 UTC, Kirius257 commented on tasks/seq/kholin_k_iterative_methods_Seidel/src/ops_seq.cpp
> +float* A_;
Fixed! I have removed the singleton and use a vector within the task.

2024-12-04 22:00 UTC, Kirius257 commented on tasks/mpi/kholin_k_iterative_methods_Seidel/func_tests/main.cpp
> +    ASSERT_EQ(testMpiTaskSequential.validation(), true);
Fixed!I use lambda expressions as comparators to compare the solutions of sequential and parallel problems with some eps error. The error is not high, but it allows us to say for sure that the solutions are close.

2024-12-04 22:01 UTC, Kirius257 commented on tasks/mpi/kholin_k_iterative_methods_Seidel/src/ops_mpi.cpp
> +         IsQuadro(taskData->inputs_count[0], taskData->inputs_count[1]);
Fixed! I check the rank of my matrix of SLAU coefficients with the rank of the extended SLAU matrix. This is specified in the validation.

2024-12-04 23:22 UTC, Kirius257 commented on tasks/seq/kholin_k_iterative_methods_Seidel/src/ops_seq.cpp
> +std::vector<float> A_;
Fixed!

2024-12-06 00:06 UTC, allnes approved these changes

2024-12-08 07:50 UTC, aobolensk approved these changes

2024-12-08 07:51 UTC, merged