Ковалев Константин. Задача 2. Вариант 25. Сортировка пузырьком (алгоритм чет-нечетной перестановки)
learning-process/ppc-2024-autumn pull request #373
Opened 2024-11-27 20:43 UTC by ARBUZNIJ

Задача состоит в сортировке массива однородных данных алгоритмом пузырьковой сортировки. В последовательной версии используется классическая реализация алгортма.
В параллельной версии данные разделяются поровну, каждый процесс сортирует свои данные. Далее выполняется цикл с количеством итераций, равным количеству процессов. На чётных(нечётных) итерациях [итерации нумеруются с 1] процесс с номером 2i в группе с процессом 2i+1 (2i-1) сливают свои данные, сортируют их [сортировка подразумевает под собой слияние двух массивов], а затем разделяют данные. По завершении итерации каждый процесс владеет тем же количеством данных, что и до начала итерации. Таким образом, по завершении цикла данные упорядочены. Данные собираются на потоке с рангом 0. Сортировкой вставками обрабатывается случай ненулевого остатка

2024-11-28 17:37 UTC, sk1er52 commented on tasks/mpi/kovalev_k_bubble_sort_oddeven_transposition/func_tests/main.cpp
> +  for (size_t i = 0; i <= length; i++) in[i] = min + static_cast<double>(rand()) / RAND_MAX * (max - min);
this condition may lead to going outside the array, fix it

2024-11-28 17:37 UTC, sk1er52 approved these changes

2024-11-28 18:05 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_bubble_sort_oddeven_transposition/func_tests/main.cpp
> +  for (size_t i = 0; i <= length; i++) in[i] = min + static_cast<double>(rand()) / RAND_MAX * (max - min);
Fixed

2024-11-30 15:37 UTC, ValeraDanger commented on tasks/mpi/kovalev_k_bubble_sort_oddeven_transposition/func_tests/main.cpp
> +
добавь тесты на случай несоответствия количества входных данных размеру выходных

2024-11-30 15:37 UTC, ValeraDanger commented on tasks/seq/kovalev_k_bubble_sort_oddeven_transposition/func_tests/main.cpp
> +
добавь тесты на случай несоответствия количества входных данных размеру выходных

2024-11-30 19:00 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_bubble_sort_oddeven_transposition/func_tests/main.cpp
> +
fixed

2024-11-30 19:00 UTC, ARBUZNIJ commented on tasks/seq/kovalev_k_bubble_sort_oddeven_transposition/func_tests/main.cpp
> +
fixed

2024-12-01 23:10 UTC, allnes commented on tasks/mpi/kovalev_k_bubble_sort_oddeven_transposition/func_tests/main.cpp
> +TEST(kovalev_k_bubble_sort_oddeven_transposition_mpi, not_equal_lengths) {
please check revers sort

2024-12-01 23:11 UTC, allnes commented on tasks/mpi/kovalev_k_bubble_sort_oddeven_transposition/func_tests/main.cpp
> +  const size_t length = 300;
please use prime values, 2^n, 3^n, 10^n

2024-12-02 23:05 UTC, allnes approved these changes

2024-12-04 04:01 UTC, aobolensk requested changes

2024-12-04 04:01 UTC, aobolensk commented on tasks/mpi/kovalev_k_bubble_sort_oddeven_transposition/func_tests/main.cpp
> +
Add tests for empty arrays and more array shapes

2024-12-04 19:54 UTC, ARBUZNIJ commented on tasks/mpi/kovalev_k_bubble_sort_oddeven_transposition/func_tests/main.cpp
> +
Added

2024-12-07 20:15 UTC, ValeraDanger approved these changes

2024-12-07 20:17 UTC, sk1er52 approved these changes

2024-12-08 07:59 UTC, aobolensk approved these changes

2024-12-08 07:59 UTC, merged