Зиновьев Александр Задача 2 Вариант 2 Задача «Читатели-Писатели»
learning-process/ppc-2024-autumn pull request #374
Opened 2024-11-27 21:12 UTC by kobych

В данной работе представлена реализация классической задачи синхронизации "Читатели-Писатели" в контексте параллельного программирования. Решение предоставлено как в параллельной версии с использованием MPI, так и в последовательной версии. Реализация включает в себя функциональные тесты, тесты производительности, а также необходимые исходные и заголовочные файлы.

2024-11-27 21:37 UTC, dasha1112 requested changes

2024-11-27 21:37 UTC, dasha1112 commented on tasks/mpi/zinoviev_readers_and_writers/perf_tests/main.cpp
> +}
Please, add test test_task_run

2024-11-27 21:37 UTC, dasha1112 commented on tasks/stl/example/func_tests/main.cpp
> +}
Please, вon't change files other than your own

2024-11-28 11:51 UTC, KADCHDR requested changes

2024-11-28 11:51 UTC, KADCHDR commented on tasks/mpi/zinoviev_readers_and_writers/func_tests/main.cpp
> +TEST(zinoviev_a_readers_and_writers_mpi, Test_Readers_Writers) {
please add more tests

2024-11-28 13:43 UTC, kobych commented on tasks/mpi/zinoviev_readers_and_writers/perf_tests/main.cpp
> +}
fixed

2024-11-28 13:43 UTC, kobych commented on tasks/stl/example/func_tests/main.cpp
> +}
fixed

2024-11-28 13:43 UTC, kobych commented on tasks/mpi/zinoviev_readers_and_writers/func_tests/main.cpp
> +TEST(zinoviev_a_readers_and_writers_mpi, Test_Readers_Writers) {
fixed

2024-11-28 13:45 UTC, dasha1112 approved these changes

2024-11-29 11:12 UTC, KADCHDR approved these changes

2024-12-01 23:12 UTC, allnes commented
@kobych  please separate 1st and 2nd tasks!

2024-12-09 21:25 UTC, kobych commented
@allnes @aobolensk

2024-12-13 16:30 UTC, allnes commented
@kobych where is task?

2024-12-15 21:53 UTC, kobych commented
@allnes I accidentally committed the second task to the first PR, so the changes only say about the tests. The files of the second PR also contain the solution to the task

2024-12-15 22:55 UTC, allnes commented
@kobych I reverted https://github.com/learning-process/ppc-2024-autumn/pull/575 and maskred blue points, please separate 2 tasks, again get 4 approves for 2nd task, and not unite!

2024-12-16 23:06 UTC, closed without merging