Бессонов Егор. Задача 2. Вариант 12. Топология сетей передачи данных - Звезда
learning-process/ppc-2024-autumn pull request #376
Opened 2024-11-27 21:56 UTC by nCUXe

Главный процесс (ранг 0) играет роль центрального узла, который последовательно обменивается данными с остальными процессами:

Выполняет отправку данных всем остальным узлам в сети.
Получает ответ от каждого узла после отправки данных.
Остальные узлы:
Получают данные только от центрального узла.
Отправляют ответ обратно центральному узлу
Порядок обхода (traversal_order_) используется для отслеживания последовательности взаимодействий.
Например:
Если есть 3 узла (0, 1, 2), то порядок обхода: [0, 1, 0, 2, 0]

2024-11-29 11:17 UTC, emilien-gus requested changes
You have written several tests, please add tests with a vector of random values and with an empty vector

2024-11-30 11:00 UTC, emilien-gus approved these changes

2024-12-01 11:35 UTC, emilien-gus requested changes

2024-12-01 11:35 UTC, emilien-gus commented on tasks/mpi/bessonov_e_star_topology/func_tests/main.cpp
> +    }
Delete the redundant code - "if". The code is repeated unnecessarily. In other tests too

2024-12-01 13:13 UTC, pipidaster2004 commented on tasks/mpi/bessonov_e_star_topology/func_tests/main.cpp
> +  int* traversal_order = nullptr;
Using raw pointers and manual memory management can lead to memory leaks and undefined behavior. Instead, use standard containers like std::vector that manage memory automatically.

2024-12-01 18:00 UTC, nCUXe commented on tasks/mpi/bessonov_e_star_topology/func_tests/main.cpp
> +    }
fixed

2024-12-01 18:00 UTC, nCUXe commented on tasks/mpi/bessonov_e_star_topology/func_tests/main.cpp
> +  int* traversal_order = nullptr;
fixed

2024-12-01 18:59 UTC, emilien-gus approved these changes

2024-12-01 20:03 UTC, pipidaster2004 approved these changes

2024-12-01 23:19 UTC, allnes commented on tasks/mpi/bessonov_e_star_topology/func_tests/main.cpp
> +  const int data_size = 5;
please check prime values, 2^n, 3^n

2024-12-01 23:20 UTC, allnes commented on tasks/mpi/bessonov_e_star_topology/src/ops_mpi.cpp
> +  }
please separate it from validation to differnet function, because this check can be used as skip, but other checks need to be used as assert and false

2024-12-02 12:03 UTC, nCUXe commented on tasks/mpi/bessonov_e_star_topology/func_tests/main.cpp
> +  const int data_size = 5;
added

2024-12-02 12:04 UTC, nCUXe commented on tasks/mpi/bessonov_e_star_topology/src/ops_mpi.cpp
> +  }
fixed

2024-12-04 04:03 UTC, aobolensk requested changes

2024-12-04 04:03 UTC, aobolensk commented on tasks/mpi/bessonov_e_star_topology/func_tests/main.cpp
> +    ASSERT_TRUE(true);
What is that? Skip the test if this is not applicable for such scenario

2024-12-04 18:12 UTC, nCUXe commented on tasks/mpi/bessonov_e_star_topology/func_tests/main.cpp
> +    ASSERT_TRUE(true);
fixed

2024-12-06 00:08 UTC, allnes approved these changes

2024-12-08 09:55 UTC, aobolensk approved these changes

2024-12-08 09:55 UTC, merged