Алпутов Иван. Задача 2. Вариант 14. Топология сетей передачи данных "Гиперкуб"
learning-process/ppc-2024-autumn pull request #377
Opened 2024-11-27 22:11 UTC by Applejack2004

Параллельная задача: Маршрутизация по гиперкубу

Начальный процесс (rank 0): Получает входные данные (TaskData), содержащие полезную нагрузку (payload) и номер целевого процесса (targetRank). Добавляет свой rank в маршрут (route). Вычисляет следующий процесс в цепочке передачи с помощью CalculateNextHop и отправляет ему данные (RoutingData), содержащие payload, targetRank и route.

Промежуточные процессы: Ожидают данные через recv. После получения добавляют свой rank в route. Если текущий процесс не является целевым, вычисляют следующий процесс с помощью CalculateNextHop и пересылают ему данные. Если текущий процесс – целевой, отправляют данные обратно начальному процессу.

Начальный процесс (после получения данных от целевого процесса): Рассылает сигнал завершения (isFinished = true) всем процессам, которые не участвовали в маршруте. Это гарантирует, что никакие процессы не останутся в ожидании данных.

Выходные данные: После завершения всех передач, начальный процесс записывает полученную payload и route в выходные данные (TaskData).

Валидация (в начальном процессе): Перед началом передачи данных проверяет, что размер коммуникатора является степенью двойки, и targetRank неотрицателен и меньше размера коммуникатора.

2024-11-27 23:20 UTC, ValeraDanger commented on tasks/mpi/alputov_i_topology_hypercube/func_tests/main.cpp
> +    std::vector<int> inputData{1337, -5};  // negative rank
No need in comment, I think. This can be seen from code

2024-11-28 11:47 UTC, ValeraDanger commented on tasks/mpi/alputov_i_topology_hypercube/perf_tests/main.cpp
> +#include <gtest/gtest.h>
Already included in `ops_mpi.hpp`, no need to include again

2024-11-28 11:47 UTC, ValeraDanger commented on tasks/mpi/alputov_i_topology_hypercube/perf_tests/main.cpp
> +#include <random>
Unused include

2024-11-28 11:47 UTC, ValeraDanger commented on tasks/mpi/alputov_i_topology_hypercube/perf_tests/main.cpp
> +#include <vector>
Already included in `ops_mpi.hpp`, no need to include again

2024-11-28 11:47 UTC, ValeraDanger commented on tasks/mpi/alputov_i_topology_hypercube/include/ops_mpi.hpp
> +#include <string>
unused include

2024-11-28 18:10 UTC, Applejack2004 commented on tasks/mpi/alputov_i_topology_hypercube/func_tests/main.cpp
> +    std::vector<int> inputData{1337, -5};  // negative rank
fixed

2024-11-28 18:10 UTC, Applejack2004 commented on tasks/mpi/alputov_i_topology_hypercube/perf_tests/main.cpp
> +#include <gtest/gtest.h>
fixed

2024-11-28 19:15 UTC, Applejack2004 commented on tasks/mpi/alputov_i_topology_hypercube/perf_tests/main.cpp
> +#include <vector>
fixed

2024-11-28 19:15 UTC, Applejack2004 commented on tasks/mpi/alputov_i_topology_hypercube/include/ops_mpi.hpp
> +#include <string>
fixed

2024-11-28 19:18 UTC, ValeraDanger approved these changes

2024-11-28 19:31 UTC, VladislavPoroshin requested changes
some inclusions are back on

2024-11-28 19:42 UTC, VladislavPoroshin approved these changes

2024-12-01 23:22 UTC, allnes commented on tasks/mpi/alputov_i_topology_hypercube/func_tests/main.cpp
> +  if ((communicatorSize & (communicatorSize - 1)) == 0u && communicatorSize >= 2) {
please use in validation or GTEST_SIP()

2024-12-02 17:59 UTC, Applejack2004 commented on tasks/mpi/alputov_i_topology_hypercube/func_tests/main.cpp
> +  if ((communicatorSize & (communicatorSize - 1)) == 0u && communicatorSize >= 2) {
fixed

2024-12-02 23:06 UTC, allnes approved these changes

2024-12-04 04:04 UTC, aobolensk approved these changes

2024-12-04 04:04 UTC, merged