Соцков Андрей. Задача 1. Вариант 10. Сумма элементов матрицы.
learning-process/ppc-2024-autumn pull request #38
Opened 2024-10-24 10:09 UTC by flavvvour

## Основные классы — `TestMPITaskSequential` и `TestMPITaskParallel` — реализуют последовательную и параллельную версию задачи.

### В функции run():

- Каждый процесс вычисляет сумму только для своей части матрицы.

- Количество элементов матрицы, которые обрабатывает каждый процесс, определяется следующим образом:

`int elements_per_process = matrix.size() / size;`
`int start_idx = rank * elements_per_process;`
`int end_idx = (rank == size - 1) ? matrix.size() : start_idx + elements_per_process;`

- `elements_per_process` — количество элементов на процесс.
- `start_idx и end_idx` — это индексы элементов, которые должен обработать каждый процесс. Последний процесс берет все оставшиеся элементы, если их количество не делится нацело.

**Каждый процесс вычисляет сумму для своей части:**

`for (int i = start_idx; i < end_idx; ++i) {`
  `local_sum += matrix[i];`
`}`

2024-10-26 11:00 UTC, hasanyanovk commented on tasks/mpi/sotskov_a_sum_element_matrix/src/ops_mpi.cpp
> +  int end_idx = (rank == size - 1) ? matrix.size() : start_idx + elements_per_process;
bad idea to push extra elements to one process, imagine:
you have N processes and matrix.size() == k * N + (N - 1)
all processes except for the last one will recieve k elements, but the last will have k + N - 1 element
the work will not be distributed evenly at all

2024-10-26 15:44 UTC, korablev-vm requested changes
It would be a good solution to add very small matrices to the tests in order to check the correctness of the partitioning by process.

2024-10-26 17:14 UTC, flavvvour commented on tasks/mpi/sotskov_a_sum_element_matrix/src/ops_mpi.cpp
> +  int end_idx = (rank == size - 1) ? matrix.size() : start_idx + elements_per_process;
**Исправил, реализация распределения на процессы теперь выглядит следующим образом:**
`int base_elements_per_process = total_elements / size;`
`int remainder = total_elements % size;`

2024-10-26 17:16 UTC, flavvvour commented
> Хорошим решением было бы добавить в тесты очень маленькие матрицы, чтобы проверить правильность разделения по процессам.

Добавил проверку на распределение по процессам матрицы 4х3, 2х3 и 1х1

2024-10-26 17:18 UTC, korablev-vm approved these changes

2024-10-26 20:43 UTC, hasanyanovk approved these changes
Now it works as it should

2024-10-27 09:39 UTC, allnes approved these changes

2024-10-29 00:10 UTC, aobolensk approved these changes

2024-10-29 00:10 UTC, merged