Петров Олег. Задача 2. Вариант 19. Метод Гаусса – ленточная горизонтальная схема
learning-process/ppc-2024-autumn pull request #380
Opened 2024-11-27 23:40 UTC by ValeraDanger

2024-11-28 19:17 UTC, Applejack2004 requested changes

2024-11-28 19:25 UTC, ValeraDanger commented on tasks/mpi/petrov_o_horizontal_gauss_method/func_tests/main.cpp
> +#include <iostream>
fixed

2024-11-28 19:25 UTC, ValeraDanger commented on tasks/seq/petrov_o_horizontal_gauss_method/func_tests/main.cpp
> +#include <iostream>
fixed

2024-11-28 19:27 UTC, Applejack2004 approved these changes

2024-11-28 21:50 UTC, mateusxap requested changes

2024-11-28 21:50 UTC, mateusxap commented on tasks/mpi/petrov_o_horizontal_gauss_method/perf_tests/main.cpp
> +
several libraries are already in ops_mpi.hpp

2024-11-28 21:50 UTC, mateusxap commented on tasks/mpi/petrov_o_horizontal_gauss_method/src/ops_mpi.cpp
> +
several libraries are already in ops_mpi.hpp

2024-11-28 21:50 UTC, mateusxap commented on tasks/mpi/petrov_o_horizontal_gauss_method/func_tests/main.cpp
> +
several libraries are already in ops_mpi.hpp

2024-11-28 21:50 UTC, mateusxap commented on tasks/seq/petrov_o_horizontal_gauss_method/func_tests/main.cpp
> +
several libraries are already in ops_seq.hpp

2024-11-28 21:50 UTC, mateusxap commented on tasks/seq/petrov_o_horizontal_gauss_method/perf_tests/main.cpp
> +
several libraries are already in ops_seq.hpp

2024-11-28 21:50 UTC, mateusxap commented on tasks/seq/petrov_o_horizontal_gauss_method/src/ops_seq.cpp
> +
several libraries are already in ops_seq.hpp

2024-11-28 21:50 UTC, mateusxap commented on tasks/mpi/petrov_o_horizontal_gauss_method/func_tests/main.cpp
> +    taskData->inputs_count.push_back(n);
better to use emplace_back

2024-11-28 22:10 UTC, mateusxap requested changes

2024-11-28 22:23 UTC, mateusxap approved these changes

2024-12-01 23:27 UTC, allnes commented on tasks/mpi/petrov_o_horizontal_gauss_method/src/ops_mpi.cpp
> +}
where do you check single solution of linear system?

2024-12-01 23:27 UTC, allnes commented on tasks/mpi/petrov_o_horizontal_gauss_method/src/ops_mpi.cpp
> +        matrix[i][j] = matrix_input[i * n + j];
please use everywhere linear form of matrix

2024-12-01 23:28 UTC, allnes commented on tasks/mpi/petrov_o_horizontal_gauss_method/func_tests/main.cpp
> +TEST(petrov_o_horizontal_gauss_method_seq, TestGauss_ZeroDiagonal) {
please check random matrix (17x17) and check by ||Ax - b = 0||

2024-12-01 23:29 UTC, allnes commented on tasks/mpi/petrov_o_horizontal_gauss_method/perf_tests/main.cpp
> +}
please results of task

2024-12-02 19:26 UTC, ValeraDanger commented on tasks/mpi/petrov_o_horizontal_gauss_method/perf_tests/main.cpp
> +}
Fixed

2024-12-02 23:09 UTC, allnes commented on tasks/seq/petrov_o_horizontal_gauss_method/src/ops_seq.cpp
> +      double factor = matrix[i][k] / matrix[k][k];
please use linear form of matrix everywhere

2024-12-02 23:09 UTC, allnes commented on tasks/mpi/petrov_o_horizontal_gauss_method/src/ops_mpi.cpp
> +        matrix[i][j] = matrix_input[i * n + j];
didn't fix

2024-12-02 23:10 UTC, allnes commented on tasks/mpi/petrov_o_horizontal_gauss_method/src/ops_mpi.cpp
> +}
I couldn't find check

2024-12-02 23:10 UTC, allnes commented on tasks/mpi/petrov_o_horizontal_gauss_method/src/ops_mpi.cpp
> +}
I mean check ranks

2024-12-03 23:11 UTC, ValeraDanger commented on tasks/mpi/petrov_o_horizontal_gauss_method/src/ops_mpi.cpp
> +}
Added rank check

2024-12-03 23:13 UTC, ValeraDanger commented on tasks/seq/petrov_o_horizontal_gauss_method/src/ops_seq.cpp
> +      double factor = matrix[i][k] / matrix[k][k];
Added linear matrix in seq

2024-12-05 03:21 UTC, aobolensk requested changes

2024-12-05 03:21 UTC, aobolensk commented on tasks/seq/petrov_o_horizontal_gauss_method/perf_tests/main.cpp
> +  }
Why it is needed?

2024-12-05 03:21 UTC, aobolensk commented on tasks/seq/petrov_o_horizontal_gauss_method/src/ops_seq.cpp
> +    output[i] = x[i];
use std::copy

2024-12-05 03:21 UTC, aobolensk commented on tasks/mpi/petrov_o_horizontal_gauss_method/func_tests/main.cpp
> +
Please, add random tests

2024-12-05 17:22 UTC, ValeraDanger commented on tasks/mpi/petrov_o_horizontal_gauss_method/func_tests/main.cpp
> +
Already have, TestGauss_RandomMatrix, TestGauss_RandomMatrix_17x17

2024-12-05 21:57 UTC, ValeraDanger commented on tasks/seq/petrov_o_horizontal_gauss_method/perf_tests/main.cpp
> +  }
Removed

2024-12-05 21:57 UTC, ValeraDanger commented on tasks/seq/petrov_o_horizontal_gauss_method/src/ops_seq.cpp
> +    output[i] = x[i];
fixed

2024-12-06 00:10 UTC, allnes commented on tasks/seq/petrov_o_horizontal_gauss_method/src/ops_seq.cpp
> +      double factor = matrix[i][k] / matrix[k][k];
it needs for all relaizations, especially for mpi

2024-12-06 09:08 UTC, ValeraDanger commented on tasks/seq/petrov_o_horizontal_gauss_method/src/ops_seq.cpp
> +      double factor = matrix[i][k] / matrix[k][k];
I am using linear form in every implementation

2024-12-08 11:17 UTC, allnes approved these changes

2024-12-08 13:35 UTC, aobolensk approved these changes

2024-12-08 13:36 UTC, merged