Одинцов Михаил Вариант 16 Ленточная вертикальная схема.
learning-process/ppc-2024-autumn pull request #381
Opened 2024-11-28 06:44 UTC by odincovm

Последовательная версия: мы делим матрицу B по столбцам, затем каждую ленту перемножаем с матрицей А и складываем в соответствующую ячейку результирующей матрицы С

Параллельная версия: мы отправляем всем потокам матрицу А, затем делим поровну на ленты матрицу В. В каждом потоке считаем свою часть матрицы С. Потом складываем все части в 0 потоке и переставляем местами значения, чтобы они были на своих местах.

2024-11-28 08:26 UTC, Ilya2643 requested changes
Increase the range of values in the random matrix to 100
All the numbers in your tests are integers, so do a test in which matrices with float numbers

2024-11-28 09:37 UTC, Ilya2643 approved these changes

2024-12-01 10:02 UTC, venn2713 commented on tasks/mpi/Odintsov_M_VerticalRibbon_mpi/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
В примере это было для иммитации нагрузки, вам не нужно

2024-12-01 10:04 UTC, venn2713 commented on tasks/mpi/Odintsov_M_VerticalRibbon_mpi/src/ops_mpi.cpp
> +  }
Если добавить в resize вторым параметром 0 то все само инициализируется

2024-12-01 10:07 UTC, venn2713 commented on tasks/mpi/Odintsov_M_VerticalRibbon_mpi/src/ops_mpi.cpp
> +  }
Массивы в C++ хранятся в **row-major** порядке (строки хранятся последовательно). Поэтому доступ к элементам по столбцам `(matrixB[szB[2] * j + i])` неэффективен из-за кэш-промахов.
Можно перестроить алгоритм так, чтобы учитывать особенности памяти, например, транспонировать matrixB заранее. Либо сразу хранить матрицу в **"column-major"** порядке

2024-12-01 10:07 UTC, venn2713 commented on tasks/mpi/Odintsov_M_VerticalRibbon_mpi/src/ops_mpi.cpp
> +  }
Избегайте многократного вычисления индексов, таких как `szB[2] * j + i` или `Arow * szA[2] + k.`

2024-12-01 10:08 UTC, venn2713 commented on tasks/mpi/Odintsov_M_VerticalRibbon_mpi/src/ops_mpi.cpp
> +  }
Вместо копирования данных из `matrixB` в `ribbon`, можно напрямую использовать элементы из `matrixB`

2024-12-01 10:09 UTC, venn2713 commented on tasks/mpi/Odintsov_M_VerticalRibbon_mpi/src/ops_mpi.cpp
> +  }
Исопользуйте особенности векторов для эффективного копирования

2024-12-01 10:11 UTC, venn2713 commented on tasks/mpi/Odintsov_M_VerticalRibbon_mpi/src/ops_mpi.cpp
> +bool VerticalRibbonMPIParallel::run() {
Вот тут бы помогло хранение в **"col-major"** порядке, не приходилось бы формировать столбец, и можно было бы использовать `scetterv` для отправки данных (он оптимальнее)

2024-12-01 10:13 UTC, venn2713 commented on tasks/mpi/Odintsov_M_VerticalRibbon_mpi/src/ops_mpi.cpp
> +  broadcast(com, matrixA.data(), matrixA.size(), 0);
Вы раздаете всю матрицу, в чем тогда заключается **_"Ленточная вертикальная схема"_**

2024-12-02 23:13 UTC, allnes commented on tasks/mpi/Odintsov_M_VerticalRibbon_mpi/src/ops_mpi.cpp
> +    return false;
why do you use 4 values for counts in matrix-vector multiplication?

2024-12-06 00:12 UTC, allnes commented on tasks/mpi/Odintsov_M_VerticalRibbon_mpi/func_tests/main.cpp
> +std::vector<double> getMatrix(int sz) {
please use matrix with different rows and cols

2024-12-06 00:13 UTC, allnes commented on tasks/mpi/Odintsov_M_VerticalRibbon_mpi/func_tests/main.cpp
> +  int max = 100;
please parametrize it

2024-12-06 00:14 UTC, allnes commented on tasks/mpi/Odintsov_M_VerticalRibbon_mpi/func_tests/main.cpp
> +  std::vector<double> vectorB = getMatrix(60);
why `getMatrix(60)` return vecor?

2024-12-06 07:49 UTC, odincovm commented on tasks/mpi/Odintsov_M_VerticalRibbon_mpi/func_tests/main.cpp
> +  int max = 100;
Добавил

2024-12-06 07:49 UTC, odincovm commented on tasks/mpi/Odintsov_M_VerticalRibbon_mpi/func_tests/main.cpp
> +std::vector<double> getMatrix(int sz) {
Теперь это тест dif_sz_1800

2024-12-06 07:50 UTC, odincovm commented on tasks/mpi/Odintsov_M_VerticalRibbon_mpi/func_tests/main.cpp
> +  std::vector<double> vectorB = getMatrix(60);
Изменил название, так как функция для матрицы и вектора не отличается

2024-12-06 14:25 UTC, sanya2905 requested changes
add random generation for test sz_4 and take it out of the calculation loop vectorC.size()

2024-12-06 17:15 UTC, sanya2905 approved these changes

2024-12-07 15:26 UTC, venn2713 approved these changes

2024-12-08 10:52 UTC, aobolensk requested changes

2024-12-08 11:18 UTC, allnes approved these changes

2024-12-08 12:28 UTC, aobolensk approved these changes

2024-12-08 17:51 UTC, merged