Сидорина Полина. Задача 2. Вариант 5. Передача от одного всем (broadcast).
learning-process/ppc-2024-autumn pull request #382
Opened 2024-11-28 12:45 UTC by PolinaSidorina

Реализация метода broadcast. 
Реализованный метод используется в задаче, которая заключается в том, что на вход подаются 2 массива числовых данных. Первый массив отправляется на все процессы, а второй отправляется поэлементно. На каждом процессе происходит суммирование первого массива и элемента, посланного из второго массива. Таким образом к каждому элементу первого массива прибавляется элемент из второго, а потом данные собираются в один массив, который является ответом на задачу.

2024-11-28 14:52 UTC, aortemon commented on tasks/mpi/sidorina_p_broadcast_m/func_tests/main.cpp
> +  // neg
Unnecessary comments should be removed

2024-11-28 14:52 UTC, aortemon commented on tasks/mpi/sidorina_p_broadcast_m/func_tests/main.cpp
> +// random !!!
Unnecessary comments should be removed

2024-11-28 15:14 UTC, Ksu04 commented on tasks/mpi/sidorina_p_broadcast/include/ops_mpi.hpp
> +#include <vector>
Please delete unnecessary directives

2024-11-28 16:05 UTC, PolinaSidorina commented on tasks/mpi/sidorina_p_broadcast_m/func_tests/main.cpp
> +  // neg
fixed

2024-11-28 16:06 UTC, PolinaSidorina commented on tasks/mpi/sidorina_p_broadcast_m/func_tests/main.cpp
> +// random !!!
fixed

2024-11-28 16:08 UTC, Ksu04 approved these changes

2024-12-02 23:15 UTC, allnes commented on tasks/mpi/sidorina_p_broadcast/func_tests/main.cpp
> +TEST(sidorina_p_broadcast_mpi, Test_array3_term2_ref) {
please add more tests

2024-12-03 15:16 UTC, PolinaSidorina commented on tasks/mpi/sidorina_p_broadcast/func_tests/main.cpp
> +TEST(sidorina_p_broadcast_mpi, Test_array3_term2_ref) {
fixed

2024-12-05 04:14 UTC, aobolensk requested changes

2024-12-05 04:14 UTC, aobolensk commented on tasks/mpi/sidorina_p_broadcast/func_tests/main.cpp
> +
Please, add random tests as well

2024-12-05 04:14 UTC, aobolensk commented on tasks/mpi/sidorina_p_broadcast_m/func_tests/main.cpp
> +      array[i] = round(rand() % 100);
Why do we need to round this?

2024-12-05 09:50 UTC, PolinaSidorina commented on tasks/mpi/sidorina_p_broadcast_m/func_tests/main.cpp
> +      array[i] = round(rand() % 100);
After your comment I realized that round was really used inappropriately here. I decided to review the randomization in the test and rewrote it differently. Now the code fills the array with 15 randomly generated numbers in the range from 0 to 100 for each element.

2024-12-05 09:50 UTC, PolinaSidorina commented on tasks/mpi/sidorina_p_broadcast/func_tests/main.cpp
> +
Fixed

2024-12-06 00:15 UTC, allnes approved these changes

2024-12-08 14:05 UTC, aobolensk approved these changes

2024-12-08 14:05 UTC, merged