Садиков Иван. Задача 2. Вариант 9. Обобщенная передача от всех одному (gather)
learning-process/ppc-2024-autumn pull request #384
Opened 2024-11-28 14:04 UTC by Sean0450

Последовательное решение:
Реализован алгоритм подсчеты суммы по строкам матрицы.
Параллельное решение:
На входе делим строки матрицы по процессам(при помощи scatterv), если деление нацело невозможно, передаем оставшиеся строки нулевому процессу. После подсчета сумма по строкам, объединяем данные на root-процессе с помощью gatherv.
Реализация gather:
На входе рассчитываем левого и правого потомков для каждого процесса и ожидаем от них данные. Далее все процессы, кроме корневого, отправляют свои данные "родителям". По итогу все процессы передают свои данные на root-процесс, который перемещает их в вектор ответа.

2024-11-29 19:29 UTC, aortemon requested changes
I’ve tried to run your work but it crashes when number of procs are greater then five. Please, fix it

2024-11-29 21:36 UTC, Sean0450 commented on tasks/mpi/sadikov_I_gather/src/mpi_src.cpp
> +sadikov_I_gather_mpi::ReferenceTask::ReferenceTask(std::shared_ptr<ppc::core::TaskData> td) : Task(std::move(td)) {}
Done

2024-11-29 21:42 UTC, kalyakinaa approved these changes

2024-11-30 00:34 UTC, aortemon approved these changes
Seems like you had to make global changes. Your function performance is cool, great job!

2024-12-02 23:24 UTC, allnes commented on tasks/CMakeLists.txt
> +              target_link_libraries(${EXEC_FUNC} PUBLIC boost_mpi boost_serialization)
please don't modify not own files

2024-12-02 23:26 UTC, allnes commented on tasks/mpi/sadikov_I_gather/func_tests/main.cpp
> +  const int rows = 320;
please check (16x32), (17x64), (100x27)

2024-12-03 18:02 UTC, Sean0450 commented on tasks/mpi/sadikov_I_gather/func_tests/main.cpp
> +  const int rows = 320;
Done

2024-12-03 18:02 UTC, Sean0450 commented on tasks/CMakeLists.txt
> +              target_link_libraries(${EXEC_FUNC} PUBLIC boost_mpi boost_serialization)
Fixed

2024-12-05 04:17 UTC, aobolensk requested changes

2024-12-05 04:17 UTC, aobolensk commented on tasks/mpi/sadikov_I_gather/func_tests/main.cpp
> +
Please, add some fixed data tests

2024-12-05 15:56 UTC, Sean0450 commented on tasks/mpi/sadikov_I_gather/func_tests/main.cpp
> +
Added

2024-12-06 00:16 UTC, allnes approved these changes

2024-12-09 03:20 UTC, aobolensk commented on tasks/mpi/sadikov_I_gather/func_tests/main.cpp
> +
There are still no tests with fixed data

2024-12-09 09:31 UTC, Sean0450 commented on tasks/mpi/sadikov_I_gather/func_tests/main.cpp
> +
What do you mean by fixed data? I created data like this:
```cpp
in = std::vector<int>(columns * rows, 1);
```

> There are still no tests with fixed data

2024-12-09 16:46 UTC, aobolensk requested changes

2024-12-09 16:46 UTC, aobolensk commented on tasks/mpi/sadikov_I_gather/func_tests/main.cpp
> +
This is very simple variant. I mean fixed data like: {1, 2, 6,2, -6, -10, 8, ...}, just hardcoding the array

2024-12-09 16:57 UTC, Sean0450 commented on tasks/mpi/sadikov_I_gather/func_tests/main.cpp
> +
Added

2024-12-09 20:39 UTC, merged