Калякина Анастасия. Задача 2. Вариант 1. Задача "Производители-потребители"
learning-process/ppc-2024-autumn pull request #385
Opened 2024-11-28 15:09 UTC by kalyakinaa

### Описание алгоритма
В данной реализации есть три вида процессов:

1. **Менеджер по работе с буфером** – это всегда нулевой процесс, он принимает сообщения с данными от производителей, записывая значение в буфер, и отправляет сообщения потребителям, когда те готовы их обработать. Данный процесс не является ни производителем, ни потребителем.
2. **Производители** – процессы, выполняющие некоторую работу по созданию данных.
3. **Потребители** – процессы, обрабатывающие созданные данные.

Количество производителей и, как следствие, потребителей (зависит от количества производителей) определяется входными параметрами, как и количество ресурсов, которые нужно создать и обработать, и размер буфера.

2024-11-28 20:31 UTC, vitaliyvoroshilov requested changes

2024-11-28 20:31 UTC, vitaliyvoroshilov commented on tasks/mpi/kalyakina_a_producers_consumers/src/ops_mpi.cpp
> +    }
It is worth adapting the solution so that it also works on two processes. The zero process can be made a producer or a consumer in addition to its existing functions.

2024-11-28 22:16 UTC, kalyakinaa commented on tasks/mpi/kalyakina_a_producers_consumers/src/ops_mpi.cpp
> +    }
Fixed

2024-11-29 08:03 UTC, vitaliyvoroshilov commented on tasks/mpi/kalyakina_a_producers_consumers/src/ops_mpi.cpp
> +    }
So change text of your task description

2024-11-29 08:16 UTC, kalyakinaa commented on tasks/mpi/kalyakina_a_producers_consumers/src/ops_mpi.cpp
> +    }
Fixed

2024-11-29 08:25 UTC, vitaliyvoroshilov commented on tasks/mpi/kalyakina_a_producers_consumers/src/ops_mpi.cpp
> +}
I think you should try to make this function `bool` and do `return true` to fix codecov

2024-11-29 09:05 UTC, kalyakinaa commented on tasks/mpi/kalyakina_a_producers_consumers/src/ops_mpi.cpp
> +}
Fixed

2024-11-29 12:22 UTC, kalyakinaa commented on tasks/mpi/kalyakina_a_producers_consumers/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
Fixed

2024-11-29 12:59 UTC, Sean0450 approved these changes

2024-11-29 17:45 UTC, venn2713 approved these changes
Выглядит интересно, удивлен как вы не запутались во всех этих сигналах в своем решении. Однозначно апрув, не нашел к чему докопаться, даже лишних broadcast нет, все нужные 👍

2024-11-30 18:22 UTC, vitaliyvoroshilov commented on tasks/mpi/kalyakina_a_producers_consumers/src/ops_mpi.cpp
> +}
Yes, I saw your commits trying to fix it, nothing really helped. To be honest, I think its not that important, maybe its some kind of _codecov_ testing error. I think it's not worth changing the entire code structure because of this

2024-11-30 18:24 UTC, vitaliyvoroshilov approved these changes

2024-12-02 23:31 UTC, allnes commented on tasks/mpi/kalyakina_a_producers_consumers/func_tests/main.cpp
> +    in = std::vector<int>{std::max(world.size() / 5 / 2 / 2, 1), std::max(world.size() / 5, 1),
could you describe this expression `std::max(world.size() / 5 / 2 / 2, 1)`

2024-12-03 17:48 UTC, kalyakinaa commented on tasks/mpi/kalyakina_a_producers_consumers/func_tests/main.cpp
> +    in = std::vector<int>{std::max(world.size() / 5 / 2 / 2, 1), std::max(world.size() / 5, 1),
In this test, the specific input values are not as critical since the focus is on verifying the quantity of input data. Overall, these input parameters represent a small buffer size (four times smaller than the number of producers), a number of producers equal to twenty percent of the total, and a small amount of resources for production (half of the number of producers). I understand that the expression .../5/2/2 may seem a little strange; however, with a small buffer and a few resources, it was important for me that the size remains smaller than the amount of resources. Therefore, this representation was more intuitive for me when I was making tests. The function std::max is used to ensure the correctness of the input parameters when the overall number of processes is low

2024-12-05 04:29 UTC, aobolensk approved these changes

2024-12-06 00:18 UTC, allnes approved these changes

2024-12-06 00:18 UTC, merged