Седова Ольга. Задача 2. Вариант 16. Ленточная вертикальная схема умножения матрицы на вектор
learning-process/ppc-2024-autumn pull request #386
Opened 2024-11-28 16:23 UTC by Sedova-Olga

2024-11-28 21:10 UTC, 0P4RY5H commented
Nice job!
![image](https://github.com/user-attachments/assets/08769a0f-87ca-4a48-93da-3160acb6ae5f)

2024-11-28 21:48 UTC, venn2713 requested changes
Я склонен утверждать, что эта работа была украдена у меня. Я считаю это неприемлимым. Ваш код на ранних этапах разработки был 1 в 1 мой, да и в дальнейшем не потерял таковых черт. В подтверждение привожу сравнение кода. 
[Ссылка на сравнение кода вашего раннего этапа разработки и моей задачи залитой в мастер](https://www.diffchecker.com/W7broXUn/)

Хочу заметить что код не реализует вашу задачу. Вы не распределяете столбцы, как того требует задача, а делителитесь всеми данными матрицы. Это нужно переделать, а лучше не красть чужой код

2024-11-28 21:48 UTC, venn2713 commented on modules/core/perf/include/perf.hpp
> +﻿// Copyright 2023 Nesterov Alexander
Ну думаю что корректно менять файлы которые вас не просили менять

2024-11-28 21:48 UTC, venn2713 commented on modules/core/perf/src/perf.cpp
> +﻿// Copyright 2023 Nesterov Alexander
Аналогичная ситуация

2024-11-28 21:48 UTC, venn2713 commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/func_tests/main.cpp
> +  int a = 0;
Вы не используете нигде кроме `if (world.rank() == 0)` эту переменную, не вижу смысле объявлять ей на всех процессах

2024-11-28 21:48 UTC, venn2713 commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/func_tests/main.cpp
> +  }
Все ваши процессы должны возвращать одинаковый результат. Такое считается некорректным. Если валидация не прошла на 0 ранге, то все остальные потоки тоже вернут false

2024-11-28 21:48 UTC, venn2713 commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
Это не используется в вашем коде. В example это служило для иммтиации нагрузки

2024-11-28 21:48 UTC, venn2713 commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/src/ops_mpi.cpp
> +    return taskData->inputs_count[0] >= 1 && taskData->inputs_count[0] / taskData->inputs_count[1] > 0;
Нелогичная проверка. Вам необходимо проверять матрицы на условие умножения, тоесть что количество столбцов равно длине вектора (как минимум)

2024-11-28 21:48 UTC, venn2713 commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/src/ops_mpi.cpp
> +    }
Это не должно быть в препроцессинге, для такого придумали валидацию

2024-11-28 21:48 UTC, venn2713 commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/src/ops_mpi.cpp
> +    }
Склонен полагать, что это моя функция расчёта распределения и смещений, которую вы для "незаметности" включили в код в единственном месте где она вызывалась. Не уверен что это корректно. Следует стараться выносить сложный код в отдельные функции с понятным интерфейсом

2024-11-28 21:48 UTC, venn2713 commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/src/ops_mpi.cpp
> +  if (world.rank() != 0) {
Не ясно зачем прерывать предыдущий if (world.rank() == 0)

2024-11-28 21:48 UTC, venn2713 commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/src/ops_mpi.cpp
> +    result_vector_.resize(rows_, 0);
Весь этот блок нелогичен. Вы уже получили данные и записали их сюда через assign

2024-11-28 21:48 UTC, venn2713 commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, input_vector_1, 0);
Это противоречит с условием вашей задачи. Вам необходимо чтобы данные в процесс отправлялись по столбцам, а вы раздаете матрицу и вектор целиком. Это неправильно

2024-11-28 21:48 UTC, venn2713 commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/src/ops_mpi.cpp
> +  }
В связи с тем что вы некорректно передали данные, у вас неправильная логика и работы с ними

2024-11-28 21:48 UTC, venn2713 commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/src/ops_mpi.cpp
> +
Аналогично с предыдущим замечанием к валидации

2024-11-28 21:48 UTC, venn2713 commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/src/ops_mpi.cpp
> +  }
Вы используете обычный алгоритм умножения матрицы на вектор, хотя у вас задача вертикального разбиения. Было бы корректно поменять направления обхода по столбцам хотябы

2024-11-28 21:48 UTC, venn2713 commented on tasks/seq/sedova_o_vertical_ribbon_scheme/func_tests/main.cpp
> +  ASSERT_EQ(testTaskSequential.validation(), true);
Функция ASSERT_TRUE вам в помощь

2024-11-28 21:48 UTC, venn2713 commented on tasks/seq/sedova_o_vertical_ribbon_scheme/func_tests/main.cpp
> +  ASSERT_EQ(result, expected_result);
В конце теста принято вызывать EXPECT

2024-11-28 21:48 UTC, venn2713 commented on tasks/seq/sedova_o_vertical_ribbon_scheme/func_tests/main.cpp
> +}
У вас критически недостаточно тестов. Проверьте матрицы разных размеров, квадратные, 4x3, 3x4, 5x7, 7x5, 10x1, 1x10 и тому подобные. Не хватает тестов на валидацию. Проверьте некорректные размеры матрицы, не подходящий по размеру вектор, пустые значения обоих

2024-11-28 21:48 UTC, venn2713 commented on tasks/seq/sedova_o_vertical_ribbon_scheme/perf_tests/main.cpp
> +TEST(sedova_o_vertical_ribbon_scheme, test_small_matrix) {
Вы перепутали функцилнальные и производительные тесты. У нас есть требования к оформлению их. Обратитесь к примеру и перечитайте README.md проекта

2024-11-28 21:48 UTC, venn2713 commented on tasks/seq/sedova_o_vertical_ribbon_scheme/perf_tests/main.cpp
> +TEST(sedova_o_vertical_ribbon_scheme, test_medium_matrix) {
Аналогичная ситуация

2024-11-28 21:48 UTC, venn2713 commented on tasks/seq/sedova_o_vertical_ribbon_scheme/perf_tests/main.cpp
> +TEST(sedova_o_vertical_ribbon_scheme, test_large_matrix) {
То же самое. У вас должно быть два теста на производительность, насколько я подразумеваю такие, как описано в README

2024-11-28 21:48 UTC, venn2713 commented on tasks/seq/sedova_o_vertical_ribbon_scheme/perf_tests/main.cpp
> +  std::cout << "Average execution time (large): " << (double)duration.count() / iterations << " microseconds\n";
Ознакомьтесь с проектом и примерами (вы же умеете ознакамливаться с чужим кодом). В этой задаче следует действовать не так

2024-11-28 21:48 UTC, venn2713 commented on tasks/seq/sedova_o_vertical_ribbon_scheme/src/ops_seq.cpp
> +}
Проблемы аналогичные, как и то что я написал в mpi версии

2024-11-28 23:03 UTC, Sedova-Olga commented on modules/core/perf/include/perf.hpp
> +﻿// Copyright 2023 Nesterov Alexander
fixed

2024-11-28 23:03 UTC, Sedova-Olga commented on modules/core/perf/src/perf.cpp
> +﻿// Copyright 2023 Nesterov Alexander
fixed

2024-11-28 23:03 UTC, Sedova-Olga commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
fixed

2024-11-28 23:04 UTC, Sedova-Olga commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/src/ops_mpi.cpp
> +    return taskData->inputs_count[0] >= 1 && taskData->inputs_count[0] / taskData->inputs_count[1] > 0;
fixed

2024-11-28 23:04 UTC, Sedova-Olga commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/src/ops_mpi.cpp
> +    }
fixed

2024-11-28 23:05 UTC, Sedova-Olga commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/src/ops_mpi.cpp
> +  if (world.rank() != 0) {
fixed

2024-11-28 23:05 UTC, Sedova-Olga commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/src/ops_mpi.cpp
> +
fixed

2024-11-29 15:39 UTC, Sedova-Olga commented on tasks/seq/sedova_o_vertical_ribbon_scheme/src/ops_seq.cpp
> +}
fixed

2024-11-29 16:06 UTC, Sedova-Olga commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/src/ops_mpi.cpp
> +  }
fixed

2024-12-04 13:24 UTC, Sedova-Olga commented on tasks/seq/sedova_o_vertical_ribbon_scheme/func_tests/main.cpp
> +}
fixed

2024-12-04 13:24 UTC, Sedova-Olga commented on tasks/seq/sedova_o_vertical_ribbon_scheme/perf_tests/main.cpp
> +TEST(sedova_o_vertical_ribbon_scheme, test_small_matrix) {
fixed

2024-12-04 13:24 UTC, Sedova-Olga commented on tasks/seq/sedova_o_vertical_ribbon_scheme/perf_tests/main.cpp
> +TEST(sedova_o_vertical_ribbon_scheme, test_medium_matrix) {
fixed

2024-12-04 13:25 UTC, Sedova-Olga commented on tasks/seq/sedova_o_vertical_ribbon_scheme/perf_tests/main.cpp
> +  std::cout << "Average execution time (large): " << (double)duration.count() / iterations << " microseconds\n";
fixed

2024-12-06 10:07 UTC, KolodkinGrigorii commented on tasks/seq/sedova_o_vertical_ribbon_scheme/func_tests/main.cpp
> +TEST(sedova_o_vertical_ribbon_scheme_seq, Test1) {
Add test for empty vector

2024-12-06 10:07 UTC, KolodkinGrigorii commented on tasks/seq/sedova_o_vertical_ribbon_scheme/func_tests/main.cpp
> +TEST(sedova_o_vertical_ribbon_scheme_seq, Test1) {
Check matrix and vector with incorrect size

2024-12-06 13:33 UTC, Sedova-Olga commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/func_tests/main.cpp
> +  }
fixed

2024-12-06 13:34 UTC, Sedova-Olga commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, input_vector_1, 0);
fixed

2024-12-06 13:34 UTC, Sedova-Olga commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/src/ops_mpi.cpp
> +  }
fixed

2024-12-06 13:34 UTC, Sedova-Olga commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/func_tests/main.cpp
> +TEST(sedova_o_vertical_ribbon_scheme_mpi, Test_0) {
fixed

2024-12-06 13:35 UTC, Sedova-Olga commented on tasks/seq/sedova_o_vertical_ribbon_scheme/func_tests/main.cpp
> +TEST(sedova_o_vertical_ribbon_scheme_seq, Test1) {
fixed

2024-12-08 08:34 UTC, KolodkinGrigorii approved these changes

2024-12-08 10:01 UTC, KseniyaBeskhmelnova approved these changes

2024-12-08 10:17 UTC, venn2713 requested changes
Да, уже значительно лучше и куда больше индивидуальности, видно что вы разобрались в теме, посмотрели примеры, написали что-то более своё, ценю тех кто осознает ошибки. В seq просто проверьте тесты и перенесите валидацию, в остальном хорошо

2024-12-08 10:17 UTC, venn2713 commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/func_tests/main.cpp
> +TEST(sedova_o_vertical_ribbon_scheme_mpi, Test_3) {
Назовите тесты понятнее, что это на проверку функциональности вашего алгоритма распределения

2024-12-08 10:17 UTC, venn2713 commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/func_tests/main.cpp
> +TEST(sedova_o_vertical_ribbon_scheme_mpi, Test_7) {
А начиная отсюда что это тесты на валидация

2024-12-08 10:17 UTC, venn2713 commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/func_tests/main.cpp
> +  ASSERT_EQ(TestSequential.validation(), false);
Используйте EXPECT_FALSE
```suggestion
  EXPECT_FALSE(TestSequential.validation());
```

2024-12-08 10:17 UTC, venn2713 commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/func_tests/main.cpp
> +TEST(sedova_o_vertical_ribbon_scheme_mpi, Test_8) {
А это что тест на функциональность

2024-12-08 10:17 UTC, venn2713 commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/func_tests/main.cpp
> +}
Тут нужно все же чуть больше тестов добавить, с генерациями случайных входных данных, и сравнением результата работы mpi с seq версией (чтобы при запусках репозитория было ясно точно ли все корректно работает с случайными значениями)

2024-12-08 10:17 UTC, venn2713 commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/func_tests/main.cpp
> +  ASSERT_EQ(TestSequential.validation(), true);
```suggestion
  ASSERT_TRUE(TestSequential.validation());
```

2024-12-08 10:17 UTC, venn2713 commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/perf_tests/main.cpp
> +    }
```suggestion
    EXPECT_EQ(global_result, seq_result);
```

2024-12-08 10:17 UTC, venn2713 commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/perf_tests/main.cpp
> +    }
```suggestion
    EXPECT_EQ(global_result, seq_result);
```

2024-12-08 10:17 UTC, venn2713 commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/src/ops_mpi.cpp
> +}
Эта валидация првоеряет переданы ли были данные, а в вашей задаче следует проверить подходит ли вектор для умножения на матрицу (тоесть длина вектора передаваемого равно кол-во столбцов матрицы)

2024-12-08 10:17 UTC, venn2713 commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/src/ops_mpi.cpp
> +}
Аналогично что и с mpi

2024-12-08 10:53 UTC, aobolensk approved these changes
Please resolve comments by @venn2713

2024-12-08 11:20 UTC, allnes approved these changes

2024-12-08 11:21 UTC, allnes commented
Will merge it when you resolve resolve comments by @venn2713

2024-12-10 15:03 UTC, venn2713 approved these changes

2024-12-10 16:11 UTC, kmichaelk requested changes

2024-12-10 16:23 UTC, Sedova-Olga commented
@allnes комментарий Сергея исправлено, он их проверил

2024-12-10 16:25 UTC, kmichaelk commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/func_tests/main.cpp
> +}
What are you testing in those tests? If you want to test the distribution resolving functionality from the Task class, then test it, testing a copy-pasted code does not guarantee that the actual code is still working correctly as it may've been changed.

2024-12-10 16:28 UTC, kmichaelk requested changes
Where are the tests with random matrices?

2024-12-10 16:32 UTC, kmichaelk commented
I cloned your branch, ran perf tests as they do not run as part of actions for pull requests and encountered segfault on 3 processes.

2024-12-10 16:33 UTC, m1likus commented
![image](https://github.com/user-attachments/assets/dff19ac4-3d49-43d1-8354-ed296c173d92)

2024-12-10 16:43 UTC, kmichaelk commented
Indeed, and the [overall project test coverage will be 93.50%](https://github.com/learning-process/ppc-2024-autumn/pull/386#issuecomment-2506503649), which is lower than the required 95%.

2024-12-10 19:17 UTC, aobolensk requested changes

2024-12-10 19:17 UTC, aobolensk commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/perf_tests/main.cpp
> +TEST(sedova_o_vertical_ribbon_scheme_mpi, Performance_Pipeline_Run) {
Perf tests should be renamed

2024-12-10 19:26 UTC, Sedova-Olga commented on tasks/mpi/sedova_o_vertical_ribbon_scheme/perf_tests/main.cpp
> +TEST(sedova_o_vertical_ribbon_scheme_mpi, Performance_Pipeline_Run) {
fixed

2024-12-15 19:09 UTC, aobolensk approved these changes

2024-12-15 19:09 UTC, merged

2024-12-15 20:31 UTC, FiitWellwisher commented
Дорогие @aobolensk и @allnes, объясните, пожалуйста, что здесь происходит.

_Сразу скажем, что этот комментарий ждет очень много человек и это продукт коллективного творчества, поэтому игнорировать его будет некрасиво и негативно для репутации._

TL;DR: уважаемая Ольга сдала две кривых работы, несоответствующих требованиям (!) и отделалась минимальным штрафом, хотя эти работы не должны были быть засчитаны вообще!

Еще месяц назад, когда эта дамочка сдавала """свою""" первую работу, мы всем ФИИТом наблюдали за происходящим. А теперь ее слава распространилась на весь поток и последние недели в контексте обсуждения параллельного программирования мы только и занимались тем, что обсасывали этот пулл реквест: девушка целиком стащила себе чужую работу и имела наглость писать вопросы о ней в чат, где оригинальный автор и поймал ее за руку. И что дальше? 

Давайте целиком восстановим хронологию этой эпичной трагикомедии в двух актах, в том числе для тех, кто залетит сюда и будет погружаться в эту драму с нулевым уровнем подготовки.


## Акт 1

1. 2 ноября, за день до дедлайна по первой, простейшей задаче, который был перенесен на неделю, г-жа Седова открывает свой пулл реквест #112, в котором не понимая, что делает, взяла и оставила прямые, безаппеляционные улики воровства (https://github.com/learning-process/ppc-2024-autumn/pull/112#discussion_r1826656314), на чем и была поймана.
2. В надежде скрыть этот факт, она закрывает свой пулл реквест #112 и открывает новый #143, в котором какой-то чудик обвиняет ее в воровстве, ссылаясь на оставленный выше комментарий.
3. Она в панике закрывает свой пулл реквест #143 и открывает новый #146
4. Туда опять приходит этот тролль и повторяет свои обвинения
5. Мадам Седова закрывает свой пулл #146 и видя, что тот комментарий утонул в потоке ее бесконечных коммитов, переоткрывает #112
6. В #112 опарыш пишет ей гневную тираду, привлекая внимание всего потока к этому пуллу
7. Вы ему отвечаете, что обязательно проведете проверку на плагиат, и он ведет себя некорректно
8. У нашей подсудимой находят критические изъяны в работе, за которые вы заворачивали другие пулл реквесты, в частности эта работа не способна корректно обрабатывать входные данные с объемами, не делящимися нацело на число процессов
9. Она закрывает свой пулл реквест на время исправления, затем его снова открывает
10. Что мы видим? Она добавила запрошенный тест, но в нем не проверяется корректность ответа!
11. Возьмите попкорн и посмотрите это своими глазами - она делает кучу коммитов, в которых то удаляет, то добавляет проверку корректности полученных параллельным решением ответов. Ее попросили добавить тест на какую-то там матрицу - она добавила! Но только без проверки ответов)) `ASSERT_EQ(taskPar.validation(), true)` и все - что еще нужно для полного счастья?
12. Ей на это указывают, и мы возвращаемся в п. 9
13. Ничего не меняется
14. Она нагоняет каких-то людей, которые поставили ей недостающие аппрувы БЕЗ ПРЕТЕНЗИЙ, ХОТЯ НИЧЕГО НЕ РАБОТАЕТ КОРРЕКТНО, и вы его принимаете! Несмотря на то, что о некорректности решения было упомянуто много раз! А соседние пулл реквесты, мы сейчас посмотрели, не такие плохие, как Ольгин, а то и просто нормальные, без аппрувов с требованиями что-то переделать не засчитывали!
15. Наша героиня выходит из игры со штрафом -6 за просрочку.
16. БОНУС! Ее почти сразу ревертают, потому что у нее крашатся тесты, хотя об этом тоже говорили! Там идеальную картинку-реакцию по этому поводу оставили, словами эмоции не передать.
17. Любителям поковыряться в ее решении мадам Седова либо игнорирует, либо хамит им в ответ


## Акт 2

Ольга, как хорошая нейросеть, извлекает уроки из своих ошибок. Нужно было открывать пулл раньше, что Ольга и сделала. Начинается еще более эпическая комедия:

1. В ppc-2024-discussions начинают появляться сообщения от нашей героини с актуальными вопросами - почему решение не работает, даже не собирается?? Загадка...
2. Тут-то ее на глазах у всех ловит за руку автор оригинального решения, указывая на то, что она бездумно туда-сюда добавляет и удаляет строки с директивами include. Не понятно, зачем, может, чтобы не так заметно было, что списала (если бы это только помогло)
3. Он обрушивается на нее в этом пулл реквесте, она декоративно подчищает украденный код и параллельно (параллельное ж программирование, хоть что-то должно быть параллельно в этой истории) задалбывает, насколько можно судить, автора в ЛС, что он ради сохранения психического здоровья (а мы ведь знаем Ольгу) ставит аппрув и закрывает свое участие в этой истории
4. @aobolensk и @allnes ставят аппрувы неглядя, с единственным требованием решить вопросик с @venn2713, что и было сделано
5. Госпожа Седова взрывает пятые точки всего потока, тегая преподавателей в чате с просьбой вот так вот вне очереди пойти и принять ее работу
6. Еще больше людей начинает следить за ситуацией
7. **Ольге предъявляют серьезные претензии: ~~во-первых, я в другом городе~~ во-первых, У НЕЕ НЕТ РАНДОМНЫХ ТЕСТОВ, ЧТО ЯВЛЯЕТСЯ ОБЯЗАТЕЛЬНЫМ УСЛОВИЕМ - РАБОТЫ БЕЗ ИХ НАЛИЧИЯ ОТКАЗЫВАЛИСЬ ПРИНИМАТЬ, процент покрытия кода - 53%, много людей с таким покрытием отправили доделывать работы!**
8. **Если их добавить, то задача в самом деле начинает крашиться! Мы впятером сидели и проверяли!**
9. **Мы не поленились, скачали архив с этой работой, засунули ее к себе в проект, и запустили - ПЕРФ-ТЕСТЫ РЕАЛЬНО ПАДАЮТ! Удивительно! Не может быть!**
10. Эти сообщения Оля игнорирует. Ну, казалось бы, все, это финал. Конец! Ан-нет!
11. **БОЛЕЕ ТОГО, ЗАДАЧА НЕ СООТВЕТСТВУЕТ ОПИСАНИЮ! ЗДЕСЬ МАТРИЦА РАССЫЛАЕТСЯ ЦЕ-ЛИ-КО-М. Вы на #381 повесили плашку "not match description" за такое!** 
12. Ииии...
13. **РАБОТА ПРИНЯТА, ПРИЧЕМ ПРИНЯТА СО ШТРАФОМ 2 БАЛЛА! ЧТО? ДА!**

## Акт 3

To be continued...

## Эпилог

Скажите, почему так? Мы чего-то не понимаем? Мы всем потоком смотрим на это, и не понимаем, в чем дело! Вы еще в пятницу говорили, что пулл реквесты, в которых что-то не работает, принимать не будете, либо будете принимать со снятием баллов за функциональность. Почему у этой задачи максимальный балл по функциональности? Ее еще и ревертнут вот-вот уже, перф тесты ложатся!

Почему кто-то должен сидеть и беспокоиться о допуске на экзамен, бояться списывать, а кто-то может ВОТ ТАК вот заехать? Это же абсурд!

А что дальше? Ну ревертните вы ее. Строку в синий покрасите? А потом она вам до конца декабря как-нибудь все исправит, и вы ее не оштрафуете? Так давайте распространим эту схему на всех. Почему нет? Мы все дружно открываем пулл реквесты до дедлайна с пустыми работами, вы их всех мержите, ставите нам в таблицу максимальный балл, потом через 5 минут ревертаете и красите в синий цвет, и мы как-нибудь до конца семестра все сделаем. Как вам идея?

Ответьте, пожалуйста, мы все ждем вашего ответа, если его не будет, то нам останется лишь строить какие-то догадки и домыслы, но это же нехорошо!

2024-12-15 20:50 UTC, FiitWellwisher commented
Еще разок посмотрели на тесты. Смотрите:

- `distribution1` - проверяет корректность создания массивов для скаттера
- `distribution2` - аналогично
- `distribution3` - аналогично
- `distribution4` - аналогично
- `false_validation` - таск должен завалиться на валидации, ран не выполняется
- `true_validation` - таск должен пройти валидацию, ран не выполняется
- `correct_matrix_and_vector_seq` - на вход подаются заранее написанные векторы, не рандомные!
- ВСЁ!

@allnes, @aobolensk, почему вы не пишете "add more tests?"? Почему ей можно, а нам нет? Мы тоже хотим, чем мы хуже?

2024-12-15 20:57 UTC, FiitWellwisher commented
![image](https://github.com/user-attachments/assets/e0abdc7b-06fe-4fa1-86a2-ebc471a1009c)
![image](https://github.com/user-attachments/assets/16ae79fb-29c4-420b-8996-96c2068141b1)
![image](https://github.com/user-attachments/assets/9ddfe738-9d24-4c1d-aadf-a697d2f28b3c)
![image](https://github.com/user-attachments/assets/45add392-1dd9-4768-bb64-2c1b8e5caa1f)

2024-12-15 20:59 UTC, venn2713 commented
Боже, как я опять тут фигурирую... Ребят, прошу вас, свои смелые предположения формата "желтой прессы" можно и не оглашать на обильную аудиторию данного PR. Я вас несомненно понимаю, но не надо меня пожалуйста больше впутывать, с меня достаточно

2024-12-15 21:05 UTC, FiitWellwisher commented
Вот вам человек сам и расписался, что задолбался участвовать в этом несчастном #386, по итогу имеем реально пустой набор тестов, устаревший аппрув от @KseniyaBeskhmelnova с единственной просьбой "add tests on big sizes of matrix" (где, кстати?) и такого же качества аппрув от @KolodkinGrigorii, если убрать предложенные им тесты, то реально останутся только тесты на краденную функцию для создания массивов в количестве 4 штук и тест на заранее заготовленные данные, который реально ничего не проверяет.

Почему нет requires > 4 reviews?

2024-12-15 21:24 UTC, kmichaelk commented
I am not happy with yet another participation in such a discussion with such a final again, but now I read your message and the code again and noticed one more thing - the only "real" test you wrote about actually tests the sequential version of the task (parallel version is named `ParallelMPI`), so all this task implementation is fiction that never worked

![image](https://github.com/user-attachments/assets/8f22a8aa-3a10-46e1-85e0-4db5489faee6)

2024-12-16 07:41 UTC, Sedova-Olga commented
Перестаньте трогать людей и тегать их, у всех есть своя жизнь, и нет желания участвовать в разборках. Самое простое это создать фейк, потому что под своим ником крысы писать боятся. Желаю получения допуска к экзамену и успешной его сдаче всем с фиита. Если у вас есть много свободного времени, то лучше его потратить на написание третьей лабы и отчёта. Касаемо реверта первой задачи, там была ошибка на стороне гитхаба и под неё многие попали. Касаемо второй задачи все комментарии были исправлены, если вас так заинтересовало решение данного варианта, то напишите его сами, или тестируйте другие репозитории.

2024-12-16 10:26 UTC, kmichaelk commented
And post these tirades somewhere else next time (I hope this won't be needed though), it's very unpleasant for all of us to participate in your personal conflicts and we don't desire to involuntarily participate in