Малышев Владимир. Задача 2. Вариант 15. Ленточная горизонтальная схема
learning-process/ppc-2024-autumn pull request #388
Opened 2024-11-28 18:11 UTC by dangerulya

## Алгоритм "Умножение матрицы на вектор. Ленточная горизонтальная схема" — общее описание

### Последовательная версия

**Подготовка:**
1. Определяем размеры матрицы (строки `rows` и столбцы `cols`).
2. Определяем размер вектора `vector_size`.
3. Генерируем случайную матрицу `matrix` размером `rows x cols`.
4. Генерируем случайный вектор `vector` размером `vector_size`.
5. Создаём вектор `result` размером `rows` для хранения результата умножения.

**Итеративный процесс:**
1. Для каждой строки `i` матрицы:
   - Инициализируем элемент `result[i]` нулем.
   - Для каждого элемента `j` в строке `i`:
     - Увеличиваем `result[i]` на произведение `matrix[i][j] * vector[j]`.

**Результат:**
- Вектор `result` содержит результат умножения матрицы на вектор.

### Параллельная версия

**Подготовка:**
1. Определяем размеры матрицы (строки `rows` и столбцы `cols`).
2. Определяем размер вектора `vector_size`.
3. Генерируем случайную матрицу `matrix` размером `rows x cols`.
4. Генерируем случайный вектор `vector` размером `vector_size`.
5. Создаём вектор `result` размером `rows` для хранения результата умножения.
6. Распределяем строки матрицы между процессами. Каждый процесс получает часть строк матрицы.

**Итеративный процесс:**
1. Каждый процесс обрабатывает свои строки матрицы:
   - Для каждой строки `i` в локальной части матрицы:
     - Инициализируем элемент `local_result[i]` нулем.
     - Для каждого элемента `j` в строке `i`:
       - Увеличиваем `local_result[i]` на произведение `local_matrix[i][j] * vector[j]`.
2. Собираем результаты от всех процессов в корневой процесс.

**Результат:**
- Вектор `result` в корневом процессе содержит результат умножения матрицы на вектор.

2024-11-28 21:10 UTC, myffii requested changes

2024-11-28 21:10 UTC, myffii commented on tasks/mpi/malyshev_lent_horizontal/func_tests/main.cpp
> +TEST(malyshev_lent_horizontal, test_vertical_stretched_matrix_100x75) {
please add tests for zero matrix\vector

2024-11-29 05:57 UTC, dangerulya commented on tasks/mpi/malyshev_lent_horizontal/func_tests/main.cpp
> +TEST(malyshev_lent_horizontal, test_vertical_stretched_matrix_100x75) {
new test added

2024-11-29 06:05 UTC, keshaproger commented on tasks/seq/malyshev_lent_horizontal/func_tests/main.cpp
> +
please add tests for zero matrix\vector in seq

2024-11-29 07:00 UTC, dangerulya commented on tasks/seq/malyshev_lent_horizontal/func_tests/main.cpp
> +
new test added

2024-11-29 08:33 UTC, keshaproger approved these changes

2024-11-29 10:34 UTC, myffii approved these changes

2024-12-02 23:33 UTC, allnes commented on tasks/mpi/malyshev_v_lent_horizontal/func_tests/main.cpp
> +      el = -200 + gen() % (300 + 200 + 1);
please parametrize interval of random

2024-12-02 23:33 UTC, allnes commented on tasks/mpi/malyshev_v_lent_horizontal/func_tests/main.cpp
> +    el = -200 + gen() % (300 + 200 + 1);
please parametrize it

2024-12-02 23:35 UTC, allnes commented on tasks/mpi/malyshev_v_lent_horizontal/func_tests/main.cpp
> +    randomVector = malyshev_lent_horizontal::generateRandomVector(cols);
please check situation when vector and matrix sizes not equal (e.g. 7, 8, 9)

2024-12-03 11:07 UTC, dangerulya commented on tasks/mpi/malyshev_v_lent_horizontal/func_tests/main.cpp
> +    randomVector = malyshev_lent_horizontal::generateRandomVector(cols);
Done

2024-12-03 11:07 UTC, dangerulya commented on tasks/mpi/malyshev_v_lent_horizontal/func_tests/main.cpp
> +    el = -200 + gen() % (300 + 200 + 1);
Done

2024-12-03 11:07 UTC, dangerulya commented on tasks/mpi/malyshev_v_lent_horizontal/func_tests/main.cpp
> +      el = -200 + gen() % (300 + 200 + 1);
Done

2024-12-05 04:32 UTC, aobolensk approved these changes

2024-12-06 00:19 UTC, allnes approved these changes

2024-12-06 00:19 UTC, merged