Холин Кирилл. Задача 1. Вариант 8. Нахождение наиболее отличающихся по значению элементов вектора.
learning-process/ppc-2024-autumn pull request #39
Opened 2024-10-24 19:19 UTC by Kirius257

### Описание алгоритмов

_Последовательная программа:_

1.  Объявляются локальные переменные под хранение наибольшей разницы между соседними элементами вектора и текущий индекс элемента вектора, по которому можно вычислить наибольшую разницу.
2.  Получаем итератор текущий(итератор начала),итератор после текущего и итератор после конца. 
3. В цикле while обходим вектор, пока не дойдём до конца, и находим разницу по модулю между двумя соседними элементами, на которые указывают итератор после текущего и текущий итератор.
4. Результатом работы цикл будет индекс левого соседнего элемента и наибольшая разница по значению между двумя соседними элементами вектора

_Параллельная программа_

1. Отдаём вектор процессу с рангом 0 и вычисляем долю элементов для распределения остальным процессам,.
2. Применяем операцию MPI_Bcast, чтобы отослать вычисленную долю данных вектора остальным процессам.
3. Используем коллективную операцию распределения различающихся данных MPI_Scatter для распределения всем процессам равных по размеру, но различных по элементам частей вектора в соответствующие буферы данных.
4. Каждый процесс посчитает, следуя алгоритму вычисления, приведённого ранее, максимальную разницу(назовём её максимальной дельтой) в своём подвекторе. и упакует результаты в соответствующие буферы данных.
5. Используем операции MPI_Gather, которая позволит собрать максимальные дельты со всех подвекторов в отдельный буфер данных, зарезервированный ранее процессом рангом 0.
6. Находим максимум среди всех максимальных дельт.
7. Результатом будет наибольшая разница по значению между двумя соседними элементами исходного вектора.

2024-10-27 15:45 UTC, Arseny-Korobeinikov commented on tasks/mpi/kholin_k_vector_neighbor_diff_elems/include/ops_mpi.hpp
> +      MPI_Gather(sendbuf3, 1, MPI_INT, ranks.data(), 1, MPI_INT, 0, world);
Why don't you use reduction into one element by passing the boost::mpi::maximum<int>() function there. Then in the end you will immediately have a ready answer, and not a vector in which you need to look for the maximum element.

2024-10-27 21:55 UTC, Kirius257 commented on tasks/mpi/kholin_k_vector_neighbor_diff_elems/include/ops_mpi.hpp
> +      MPI_Gather(sendbuf3, 1, MPI_INT, ranks.data(), 1, MPI_INT, 0, world);
Fixed!I reworked the MPI program and now instead of using 3 MPI_Gather operations, I use one MPI_Reduce to quickly calculate the maximum difference.

2024-10-29 10:49 UTC, m1likus requested changes
Hpp should contain only function porotypes, check read.me

2024-10-29 11:50 UTC, Kirius257 commented
> Hpp should contain only function porotypes, check read.me

This is the inclusion of a pattern. All method implementations are written inside the hpp file. The ReadMe says that classes and function prototypes should be wrapped in a namespace. That's fine

2024-10-29 14:16 UTC, allnes commented on modules/core/perf/include/perf.hpp
> +  // Check performance of full task's pipeline:  pre_processing() -> validation() -> run() -> post_processing()
please don't change not own files

2024-10-29 15:51 UTC, m1likus commented on tasks/mpi/kholin_k_vector_neighbor_diff_elems/include/ops_mpi.hpp
> +        input_[i] = ptr[i];
You can use std::copy or std::assign instead

2024-10-29 15:51 UTC, m1likus commented on tasks/mpi/kholin_k_vector_neighbor_diff_elems/func_tests/main.cpp
> +    bool IsValid_ = testMPITaskSequential.validation();
You might do assert_eq without extra flags

2024-10-30 12:37 UTC, Kirius257 commented on modules/core/perf/include/perf.hpp
> +  // Check performance of full task's pipeline:  pre_processing() -> validation() -> run() -> post_processing()
Fixed! I brought perf.hpp back to its original state.

2024-10-30 12:38 UTC, Kirius257 commented
> Hpp should contain only function porotypes, check read.me

And fixed! I took the description of template functions out of the class.

2024-10-30 12:39 UTC, Kirius257 commented on tasks/mpi/kholin_k_vector_neighbor_diff_elems/func_tests/main.cpp
> +    bool IsValid_ = testMPITaskSequential.validation();
Fixed!

2024-10-30 16:58 UTC, hasanyanovk commented on tasks/mpi/kholin_k_vector_neighbor_diff_elems/include/ops_mpi.hpp
> +  if (ops == "MAX_DIFFERENCE") {
For what this check and why are you using `MPI_*` functions, but your class has a field `boost::mpi::communicator`

2024-10-30 18:37 UTC, Kirius257 commented on tasks/mpi/kholin_k_vector_neighbor_diff_elems/include/ops_mpi.hpp
> +  if (ops == "MAX_DIFFERENCE") {
Fixed! I removed the extra checking, and replaced boost::mpi::communicator with the default MPI_COMM_WORLD communicator, adding the appropriate MPI_Comm_size and MPI_Comm_rank operations.

2024-10-31 00:44 UTC, allnes approved these changes

2024-10-31 14:05 UTC, Arseny-Korobeinikov approved these changes

2024-10-31 16:28 UTC, aobolensk requested changes

2024-10-31 16:28 UTC, aobolensk commented on tasks/mpi/kholin_k_vector_neighbor_diff_elems/func_tests/main.cpp
> +TEST(kholin_k_vector_neighbor_diff_elems_mpi, check_validation) {
Please, add random tests

2024-10-31 16:28 UTC, aobolensk commented on tasks/mpi/kholin_k_vector_neighbor_diff_elems/include/ops_mpi.hpp
> +    // std::cout << "right el" << right_elem << "right_ind" << right_index << std::endl;
Please, get rid of commented out code here and in other places

2024-10-31 16:28 UTC, aobolensk commented on tasks/mpi/kholin_k_vector_neighbor_diff_elems/include/ops_mpi.hpp
> +  if (ops == "MAX_DIFFERENCE") {  // declaration operations with
Is string literal really required here? It is not very fast and error-prone (potentially we can make typos in the string). Consider using enum/enum class

2024-10-31 20:13 UTC, Kirius257 commented on tasks/mpi/kholin_k_vector_neighbor_diff_elems/include/ops_mpi.hpp
> +    // std::cout << "right el" << right_elem << "right_ind" << right_index << std::endl;
Fixed! I removed all comments.

2024-10-31 20:15 UTC, Kirius257 commented on tasks/mpi/kholin_k_vector_neighbor_diff_elems/include/ops_mpi.hpp
> +  if (ops == "MAX_DIFFERENCE") {  // declaration operations with
FIxed! I replaced this on enum and now the operation will be selected from the enumeration

2024-10-31 20:28 UTC, Kirius257 commented on tasks/mpi/kholin_k_vector_neighbor_diff_elems/func_tests/main.cpp
> +TEST(kholin_k_vector_neighbor_diff_elems_mpi, check_validation) {
Fixed! I added random tests for mpi and sequential programms

2024-11-01 00:37 UTC, aobolensk approved these changes

2024-11-01 00:37 UTC, merged