Филатьева Елизавета. Задача 2. Вариант 19. Метод Гаусса — ленточная горизонтальная схема
learning-process/ppc-2024-autumn pull request #390
Opened 2024-11-28 22:42 UTC by LizochkaSpring

Задача заключается в решении системы линейных уравнений вида Ax = b, где A — квадратная матрица коэффициентов (входные данные), x — вектор неизвестных переменных (решение), а b — вектор свободных членов (входные данные). Решение осуществляется методом LU-разложения, который включает прямой и обратный ход.

1. Входные данные:

Матрица A: квадратная матрица размером n x n, элементы которой являются коэффициентами при неизвестных в системе уравнений.
Вектор b: Вектор-столбец размером n x 1, элементы которого представляют собой свободные члены системы уравнений.

2. Прямой ход (LU-разложение):

Цель прямого хода – разложить матрицу A на произведение двух матриц: нижней треугольной матрицы L (Lower) и верхней треугольной матрицы U (Upper). В общем случае, алгоритм включает следующие шаги:

- Инициализация: L и U — квадратные матрицы размером n x n. Диагональные элементы L инициализируются единицами, а остальные — нулями. U инициализируется как нулевая матрица.
- Прямой ход Гаусса: итеративно выполняются элементарные преобразования строк матрицы A. На i-й итерации:
Выбирается ведущий элемент (обычно диагональный элемент).
- Строки ниже i-й строки преобразуются путём вычитания кратного i-й строки, чтобы элементы в i-м столбце ниже i-й строки стали нулями.
- Коэффициенты, используемые для преобразования строк, записываются в матрицу L. Элементы матрицы U заполняются элементами преобразованной матрицы A.
- Результат: после n итераций матрица A будет преобразована в верхнюю треугольную матрицу U, а матрица L будет содержать коэффициенты преобразований.

3. Обратный ход (решение системы Ly = b и Ux = y):

После LU-разложения мы получаем две системы уравнений: Ly = b и Ux = y. Решение осуществляется в два этапа:

- Решение системы Ly = b (подстановка вперед):

Система Ly = b является системой с нижней треугольной матрицей. Ее решение можно найти методом прямой подстановки, начиная с первой строки.

- Решение системы Ux = y (подстановка назад):

Система Ux = y является системой с верхней треугольной матрицей. Ее решение можно найти методом обратной подстановки, начиная с последней строки.

2024-11-29 06:51 UTC, MaximChizhov commented on tasks/mpi/filateva_e_metod_gausa/func_tests/main.cpp
> +  int size = 3;
Please give clearer names for the tests.

2024-11-29 06:51 UTC, MaximChizhov commented on tasks/seq/filateva_e_metod_gausa/src/ops_seq.cpp
> +  internal_order_test();
Please, delete the unnecessary include

2024-11-29 06:51 UTC, MaximChizhov commented on tasks/seq/filateva_e_metod_gausa/src/ops_seq.cpp
> +
Please, write a test when these values are not equal

2024-11-29 09:29 UTC, MaximChizhov approved these changes

2024-12-02 23:36 UTC, allnes commented on tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
> +}
please check single solution of linear systems

2024-12-02 23:38 UTC, allnes commented on tasks/mpi/filateva_e_metod_gausa/func_tests/main.cpp
> +  double alfa = 0.000000001;
gauss method is direct method, for double its high error

2024-12-04 01:09 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/func_tests/main.cpp
> +  double alfa = 0.000000001;
fixed

2024-12-04 01:10 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
> +}
fixed

2024-12-04 19:13 UTC, venn2713 requested changes

2024-12-06 00:27 UTC, allnes approved these changes

2024-12-06 00:27 UTC, allnes commented
@LizochkaSpring please finish all reviews

2024-12-06 16:49 UTC, aobolensk approved these changes

2024-12-07 11:46 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/func_tests/main.cpp
> +}
Добрый день, этот формат вывода позволяет избежать передачи решения в функцию, если оно не требуется, без перегрузки функции.

2024-12-07 12:05 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/func_tests/main.cpp
> +    auto *temp = reinterpret_cast<double *>(taskData->outputs[0]);
![capture_20241207150036871](https://github.com/user-attachments/assets/a58d0932-0d27-4290-ae45-af811b07eae8)
Работает вот так. outputs был заполнен в методе post_processing. Если нужно что бы данный вектор помещался в outputs в тестах, напиши ниже комментарий.

2024-12-07 12:24 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/func_tests/main.cpp
> +TEST(filateva_e_metod_gausa_mpi, test_size_200) {
Написать можно и один раз, добавив в конце "исправьте и в других тестах", а не плодить комментарии.

2024-12-07 12:25 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/include/ops_mpi.hpp
> +
Зачем, если мы можем проверить на точное решение.

2024-12-07 12:31 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
> +bool filateva_e_metod_gausa_mpi::MetodGausa::validation() {
В препроцессинге данные должны приводится к определенному формату, условия что данные должны быть получены в препроцессинге, если я не ошибаюсь не было. Могу данные получать и в конструкторе, если очень нужно убрать данный код из валидации. Напишите комментарий ниже, перенести данный код в конструктор или не нужно.

2024-12-07 12:31 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
> +bool filateva_e_metod_gausa_mpi::MetodGausa::pre_processing() {
Комментарий выше.

2024-12-07 14:07 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/func_tests/main.cpp
> +  }
Читай выше.

2024-12-07 14:08 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/func_tests/main.cpp
> +TEST(filateva_e_metod_gausa_mpi, test_size_100) {
Читай выше.

2024-12-07 14:08 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/perf_tests/main.cpp
Читай выше. По два раза одно и то же замечание можно не писать.

2024-12-07 14:58 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/func_tests/main.cpp
> +    ASSERT_EQ(check(answer, tResh, alfa), true);
Исправлено

2024-12-07 14:58 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/func_tests/main.cpp
> +  ASSERT_EQ(metodGausa.validation(), true);
Исправлено

2024-12-07 14:58 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/func_tests/main.cpp
> +    ASSERT_EQ(check(answer, tResh, alfa), true);
Исправлено

2024-12-07 14:58 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/func_tests/main.cpp
> +  double alfa = std::numeric_limits<double>::epsilon() * 10000;
Исправлено

2024-12-07 14:59 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/func_tests/main.cpp
> +    ASSERT_EQ(metodGausa.validation(), false);
Исправлено

2024-12-08 11:22 UTC, allnes commented
@LizochkaSpring will merge it after approve by @venn2713

2024-12-08 12:24 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
> +}
1 и 2. Код синхронизирован с помощью world.probe, по этому нельзя убрать. 

3) Если матрица небольших размеров и процессов больше чем размер матрицы, тогда мы потратим на передаче между процессами данных больше времени, чем при подсчете на одном. При больших размерах матрицы, (например при размере 500 на 500), сомневаюсь что данную задачу кто то решит запускать на 501 процессе. Но если у тебя есть более элегантное решение данной проблемы распределения между процессами, напиши, я его учту в следующей задаче. 

4) Согласна с тобой, что любое копирование это неэффективно. И возможно есть более правильный способ как решить данную задачу, но в данной реализации, я не вижу более правильного решения, которое бы кратно не усложняло код данной задачи. Если у тебя так же есть решение, то можешь написать, я его учту.

5) Давай посчитаем сложность данной задачи, метод Гаусса при обычной (не распараллеленном решение) имеет сложность n^3. При распараллеливание данной задачи на p процессов (без учета потерь на пересылку, дополнительное копирования и других накладных расходов) n^2 * (n/p). Обратный ход выполняется за n^2, тогда при условие вышеупомянутого сложность алгоритма будет  n^2 * (n/p) + n ^ 2, или же:  n^2 ((n + p) / n).  
При параллельной реализации обратного кода сложность: n^2 ((n + 1) / p) . То есть сложность алгоритма не уменьшится, мы не выиграем на распараллеливания обратного кода ничего, а вот если учитывать накладные расходы на распараллеливания, тогда можем еще и получить худший результат.

2024-12-08 12:43 UTC, venn2713 commented on tasks/mpi/filateva_e_metod_gausa/func_tests/main.cpp
> +    auto *temp = reinterpret_cast<double *>(taskData->outputs[0]);
А, ого... Ну странно, обычно мы передаем перед запуском переменные, их читаем в теле функции, изменяем и потом проверяем в тестах, но... Ладно, возможно так можно

2024-12-08 12:44 UTC, venn2713 commented on tasks/mpi/filateva_e_metod_gausa/include/ops_mpi.hpp
> +
Так было в примере, в постановке задачи было, что seq у нас проверяется на точном решении, а в последующем служит для проверки mpi вресии, понятное дело что можем, но нужно сделать как в примере было показано

2024-12-08 12:46 UTC, venn2713 commented on tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
> +bool filateva_e_metod_gausa_mpi::MetodGausa::validation() {
Валидация под собой подразумевает, что вы проверяете корректность входных данных перед тем как начать выполнять работу, а препроцессинг подразумевает что вы подготовливаете данные перед запуском алгоритма

2024-12-08 12:55 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/include/ops_mpi.hpp
> +
Так даже есть задачи типа где невозможно создать последовательную задачу. Есть где то условие что мы не можем проверять по точному решение, если да, то я не против переписать код, иначе я не вижу в данной затеи смысла.

2024-12-08 12:56 UTC, venn2713 commented on tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
> +}
1 и 2 почему нельзя, к чему здесь синхронизация. У вас матрица, вам необходимо на n процессов распределить опорную строку и следующие за ними. Для этого идеально подходит скатерв, в PR есть примеры как людям не повезло с вертикальным методом, и они и то придумали как таким образом хранить вектор, чтобы все работало в асинхронном формате. Просто в чем польза от MPI в данной реализации если у вас он синхронизирован на iprobe

2024-12-08 12:58 UTC, venn2713 commented on tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
> +}
Тут либо генерируется временный буфер, которые содержит необходимые строки для процесса и рассылается, либо всем процессам отдается опорная строка и остальным процессам лишь распределенные в них строки

2024-12-08 13:01 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
> +bool filateva_e_metod_gausa_mpi::MetodGausa::validation() {
Давай так, что бы проверить матрицу на ранг и определитель, мне ее нужно получить. Проверка данных происходит в валидации, которая стоит до предпроцессинга (где как ты пишешь нужно получать данные).Кая я могу проверить ранг по другому, не получив данные. Вообше в чем проблема, тут от этого не зависит не сложность алгоритма не какие-то логические ошибки. Получить данные вообще можно в конструкторе, если тебе так нужно то напиши.

2024-12-08 13:12 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
> +}
1 и 2) Разберись сначала с кодом, 0 процесс просто занимается раздачей работы и получает потом данные, для этого и синхронизация. И простои будут только на 0 процессе пока он ждет ответа от всех других потоков. Да возможна реализация, когда и на 0 процесс выделяется кусок матрицы и он его высчитывает, но здесь не такая реализация. 

Хороший вариант с выделением дополнительного буфера. Единственное, что на каждом процессе будет выделена памяти не n * delta, а n * n. Я решила воспользоваться первым вариантом, как по мне тоже имеет место быть.

2024-12-08 13:14 UTC, venn2713 commented on tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
> +bool filateva_e_metod_gausa_mpi::MetodGausa::validation() {
Ну так все хорошо, получила данные в валидации, локальные, потом в препроцессинге уже в класс занесла данные

2024-12-08 13:20 UTC, WladislawFilatew commented on tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
> +bool filateva_e_metod_gausa_mpi::MetodGausa::validation() {
Зачем?

2024-12-08 13:22 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
> +bool filateva_e_metod_gausa_mpi::MetodGausa::validation() {
Зачем? Лишнее выделение памяти, копирование и т.д.

2024-12-08 13:42 UTC, venn2713 requested changes
# **Реализован не тот метод. LU разложение вместо метода Гаусса**

2024-12-08 13:42 UTC, venn2713 commented on tasks/mpi/filateva_e_metod_gausa/func_tests/main.cpp
> +    taskData->outputs_count.emplace_back(size);
Здесь **и ниже** почему `outputs_count`?

2024-12-08 13:42 UTC, venn2713 commented on tasks/mpi/filateva_e_metod_gausa/func_tests/main.cpp
> +    ASSERT_FALSE(metodGausa.validation());
Ну вот как говорите не писать везде, тут не написал и тут ASSERT а не EXPECT
```suggestion
    EXPECT_FALSE(metodGausa.validation());
```

2024-12-08 13:42 UTC, venn2713 commented on tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
> +    if (taskData->inputs_count[0] != taskData->outputs_count[0] || taskData->inputs_count[0] == 0) {
Я понял. если что outputs_count у нас для выводимых из программы данных, тут должно быть inputs_count[1]

2024-12-08 13:42 UTC, venn2713 commented on tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
> +    if (taskData->inputs_count[0] != taskData->outputs_count[0] || taskData->inputs_count[0] == 0) {
Если я сюда передам -1 и -1 то все сработает и упадет

2024-12-08 13:42 UTC, venn2713 commented on tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
> +    this->matrix.insert(matrix.end(), temp, temp + size * size);
данные лучше заполнять через assign

2024-12-08 13:42 UTC, venn2713 commented on tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
> +    }
На данную проверку нет тестов, вы генерируете матрицы подходящие для метода гауса, добавьте тест с не подходящей матрицей на эти случаи

2024-12-08 13:42 UTC, venn2713 commented on tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
> +  }
Для чего тут else и весь resize

2024-12-08 13:42 UTC, venn2713 commented on tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
> +    boost::mpi::broadcast(world, t_strock.data(), size, 0);
можете просто подключить сериализатор и передавать даннык как 
```cpp
boost::mpi::broadcast(world, t_strock, 0);
```

2024-12-08 13:42 UTC, venn2713 commented on tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
Решил вчитаться в алгоритм, на удивление понял что у вас реализован не метод Гаусса, а LU разложение. Думаю это не совсем корректно в данном методе. Вы должны строить лишь верхнетреугольную матрицу!

2024-12-08 13:42 UTC, venn2713 commented on tasks/seq/filateva_e_metod_gausa/src/ops_seq.cpp
> +}
Аналогично LU разложение а не Гаусс

2024-12-08 17:08 UTC, kmichaelk requested changes

2024-12-08 17:08 UTC, kmichaelk commented on tasks/mpi/filateva_e_metod_gausa/perf_tests/main.cpp
> +    auto *temp = reinterpret_cast<double *>(taskData->outputs[0]);
You don't push anything to `outputs` previously, perf tests will fail

2024-12-08 17:10 UTC, kmichaelk commented on tasks/seq/filateva_e_metod_gausa/src/ops_seq.cpp
> +  taskData->outputs.emplace_back(reinterpret_cast<uint8_t*>(resh.data()));
Seems you do it here, but it's not conventional

2024-12-12 10:30 UTC, LizochkaSpring commented
fixed

2024-12-12 10:33 UTC, LizochkaSpring commented on tasks/seq/filateva_e_metod_gausa/src/ops_seq.cpp
> +  taskData->outputs.emplace_back(reinterpret_cast<uint8_t*>(resh.data()));
fixed

2024-12-12 10:33 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/perf_tests/main.cpp
> +    auto *temp = reinterpret_cast<double *>(taskData->outputs[0]);
fixed

2024-12-12 17:25 UTC, kmichaelk requested changes
Consider adding this test, it does not pass at the moment:

```cpp
  const int size = 3;
  // clang-format off
  std::vector<double> matrix{
    0, 1, 1,
    1, 0, 1,
    1, 1, 0
  };
  // clang-format on
  std::vector<double> vecB(size, 8);
  std::vector<double> answer(size);
  std::vector<double> tResh{4, 4, 4};
```

2024-12-12 21:54 UTC, LizochkaSpring commented
fixed

2024-12-13 10:43 UTC, ArtemPch approved these changes
you have a well written task

2024-12-13 10:45 UTC, WladislawFilatew approved these changes

2024-12-13 10:45 UTC, BogdanNaumov approved these changes
Everything is fine

2024-12-13 10:47 UTC, MargaritaMuhina approved these changes
The task is well written

2024-12-13 10:50 UTC, Matthewsoul124 commented
The test coverage is good and the program part of project is good too. I see no any drawbacks

2024-12-13 10:55 UTC, kavtorevd approved these changes
solution is fine!

2024-12-13 10:55 UTC, Dmit-bit-m approved these changes
the task is correct

2024-12-13 10:57 UTC, SingularityNN approved these changes
everything is fine

2024-12-13 11:02 UTC, Semyon1104 commented
Good job

2024-12-13 11:02 UTC, Semyon1104 approved these changes

2024-12-13 11:03 UTC, Irina2004-tech approved these changes
In my opinion, you did a great job! solution is good.

2024-12-13 11:12 UTC, safarov-nm approved these changes
Good job.

Sincerely,
ex-employee of Vkontakte

2024-12-13 11:17 UTC, ChernovaNatalya commented
Evetything is fine

2024-12-13 11:18 UTC, ChernovaNatalya approved these changes

2024-12-13 11:28 UTC, AndreySorokin7 approved these changes

2024-12-13 12:10 UTC, erty1909 approved these changes
Всё верно

2024-12-13 12:43 UTC, venn2713 commented
Но ведь **не fixed**. 
Вот в коммите [c1387da](https://github.com/learning-process/ppc-2024-autumn/pull/390/commits/c1387da7393ea8142151ba9bc61b45d57883d996) видно что вы просто добавили в валидации заглушку, в следствие чего код не может решить систему
0x₁ + 3x₂ = 1  
3x₁ + 0x₂ = 3

Код должен согласно алгоритму Гаусса если попадается на главной диагонали ноль, то идти вниз до первого не нулевого элемента, и менять строки местами, тоесть валидация не корректна, у такой задачи есть решение

2024-12-13 13:01 UTC, LizochkaSpring commented
Добрый день, данная задача решает данный пример, можете проверить

![2_](https://github.com/user-attachments/assets/22fc0a11-4727-4197-b70d-199754b41dc6)
![1](https://github.com/user-attachments/assets/0829a5e4-947f-4791-bf79-a94bd51be748)

2024-12-13 13:19 UTC, VlJulia approved these changes
Все хорошо

2024-12-13 13:21 UTC, KAPUSHA228 approved these changes

2024-12-13 13:33 UTC, venn2713 commented
А как алгоритм обрабатывает ситуации, когда в процессе преобразований на главной диагонали появляется 0?

2024-12-13 14:11 UTC, kmichaelk requested changes
This case is not being handled correctly:

```cpp
matrix = {0, 1, 1, 1, 1, 1, 0, 1, 0};
vecB = {2, 3, 1};
tResh = {1, 1, 1};
```

2024-12-13 16:14 UTC, safarov-nm commented
> > А как алгоритм обрабатывает ситуации, когда в процессе преобразований на главной диагонали появляется 0?
> 
> How dare you, of course it works correctly, this was confirmed with all sincerity by a whole ex-VKontakte employee who edited his message four times changing the company (what does that have to do with it) brand name to make it sound more convincing
> 
> ![image](https://private-user-images.githubusercontent.com/185696987/395610670-50995113-4894-441a-bfec-232826b4a4e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxMDY3MzAsIm5iZiI6MTczNDEwNjQzMCwicGF0aCI6Ii8xODU2OTY5ODcvMzk1NjEwNjcwLTUwOTk1MTEzLTQ4OTQtNDQxYS1iZmVjLTIzMjgyNmI0YTRlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxM1QxNjEzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDAwNWI3NWI4NDc4Yzc2M2YyMzQ1ZmYwODQwNGQ1MTcyOWQzMTA3OTEwOWU3NDg3ZDUzNGI4MDY4ZTczN2RlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.P-VCW9XTakYuRpJRR23sccmdaCobi07vpOJx3kLG9jI)

I didn't think you were following me everywhere. Nice. And by the way: the sentence "Good job." does not mean that the job was done completely correctly or incorrectly. And, as you noted, specifying the name of the company where I worked 2 years ago was really for credibility.

2024-12-13 16:28 UTC, aortemon commented
> 
> the sentence "Good job." does not mean that the job was done completely correctly or incorrectly

Then what is the point of your approvement if the comment does not carry any semantic load as your specified?

2024-12-13 16:56 UTC, safarov-nm commented
> > the sentence "Good job." does not mean that the job was done completely correctly or incorrectly
> 
> Then what is the point of your approvement if the comment does not carry any semantic load as your specified?

At the very least, to express support and a positive response for this work.

2024-12-13 16:57 UTC, safarov-nm commented
> > the sentence "Good job." does not mean that the job was done completely correctly or incorrectly
> 
> Then what is the point of your approvement if the comment does not carry any semantic load as your specified?

At a minimum, it is to express support and positive feedback for this work.

2024-12-13 17:08 UTC, safarov-nm commented
> > Approves pull request
> 
> > Declares his credibility by specifying his ex-employer (when he was a 2nd grader) widely known for web products not related to mathematical calculations
> 
> > A flaw has been found in this PR
> 
> > _the sentence "Good job." does not mean that the job was done completely correctly or incorrectly_
> 
> No more questions



> > Одобряет запрос на извлечение
> 
> > Заявляет о своей достоверности, указывая на своего бывшего работодателя (когда он был учеником 2-го класса), широко известного своими веб-продуктами, не связанными с математическими вычислениями
> 
> > В этом PR обнаружен недостаток
> 
> > _предложение «Хорошая работа» не означает, что работа была выполнена полностью правильно или неправильно_
> 
> Больше нет вопросов

1. I am glad that you are not blind and really see that I have approved the extraction request.
2. Are you sure? Any web product (as you say), especially one as large as VK, uses complex mathematical algorithms for analytics, recommendations, optimization of downloads and work with big data. 
3. It’s stupid, to tell the truth, to conclude based on my words that there are any errors in this PR. Perhaps they are present, but such conclusions cannot be drawn based on any of my words.

2024-12-13 18:50 UTC, safarov-nm commented
> Спасибо за высокую оценку моих способностей, я не спорю, что это талант, но этот талант прикладного уровня, поэтому работа клоуном мне не подходит. Тем не менее, сурово, но справедливо, как говорится в народе.
> 
> Раз вам нечего возразить по существу, значит я все правильно написал, ну что ж, думаю, пойду, ведь написание длинных текстов тоже требует жизненной силы, и ее нужно регулярно восполнять.
> 
> Еще раз спасибо за ваши сообщения, "с уважением бывший сотрудник ВК", я уверен, станет (и уже стал) местным мемом людей, посетивших~_сей мир в его минуты роковые_~этот пиар на многие годы вперед.
> 
> Кстати, некоторые из тех, кто одобрил этот PR, отправляют плохие задания, которые затем отменяются, или, что еще хуже, полностью крадут чужие — посмотрите, например, [#362 (комментарий)](https://github.com/learning-process/ppc-2024-autumn/pull/362#issuecomment-2503688238) .

I am glad that you immediately follow my orders - for example, continue to write messages that correspond, at a minimum, to the buzzkill. :)

2024-12-13 19:07 UTC, safarov-nm commented
:). Funny. Truth. Please continue.

2024-12-13 20:27 UTC, kmichaelk commented
Jokes aside, the solution [is still incomplete](https://github.com/learning-process/ppc-2024-autumn/pull/390#pullrequestreview-2502390864) despite requests to approve

2024-12-14 21:47 UTC, kmichaelk commented
You stole a piece of someone else's code with a weird redundant operation that's not needed given that `i` is always less than `world.size()`

#464 

![image](https://github.com/user-attachments/assets/446d99fe-ae8a-4b2d-8bda-7fac57c5dab9)

![image](https://github.com/user-attachments/assets/7fbff7a0-6c9a-46b1-be85-e323f83a7506)

2024-12-14 21:50 UTC, LizochkaSpring commented
Добрый вечер, эта строчка необходима, я ее не у кого не брала, вчитайтесь в код что бы разобраться в реализации данного метода.

2024-12-14 22:35 UTC, LizochkaSpring commented
Отвечаю на комментарий Михаила Крылова, о списывание работы. Данная работа полностью написано мной и не у кого решения данной работы не было списано, вот ссылка на презентацию по алгоритму который я использовала https://www.mkurnosov.net/teaching/docs/pct-lecture7.pdf.  Можете ознакомится с алгоритмом решения данной задачи и почему там нужно брать по модулю. Почему я поменяла алгоритм решения, (если посмотреть коммиты до  14.12.2024 там он немного отличается), по вашему же комментарию были выявлены недочеты в той реализации (а именно  matrix = {0, 1, 1, 1, 1, 1, 0, 1, 0};
vecB = {2, 3, 1};
tResh = {1, 1, 1};)
В той реализации довольно было сложно решить данную проблему и я решила переписать полностью метод, по презентации, которую приложило выше. Если что данный код тоже не решает данную проблему, по этому код был модифицирован и дополнен, можете ознакомится, если будут вопросы готова ответить на них. 
P.S. На будущее перед тем как обвинять человека в списывании, советую разобраться в ситуации, а не сразу строчить комментарии (если посмотрите мое решение, а не один участок кода, то сможете убедиться, что код очень сильно отличается от реализации Шишкарева Андрея).

2024-12-14 22:57 UTC, kmichaelk approved these changes
Doveray no proveray, it works and that's okay, nothing else seems to break

2024-12-14 22:59 UTC, kmichaelk commented on tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
> +        boost::mpi::broadcast(world, resh[i], i % world.size());
Although it's not very efficient and was done in that presentation for clarity, there's a slow down when synchronizing here, which is why it catches the eye

2024-12-14 23:09 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
> +        boost::mpi::broadcast(world, resh[i], i % world.size());
Про эффективность соглашусь с вами

2024-12-14 23:12 UTC, LizochkaSpring commented
Исправлены все замечания

2024-12-15 08:53 UTC, venn2713 approved these changes

2024-12-15 18:38 UTC, merged