Межуев Максим Задача 2 Вариант 13. Решетка-Тор
learning-process/ppc-2024-autumn pull request #394
Opened 2024-11-29 13:44 UTC by Domovenokkk

Алгоритм "решетка-тор" предназначен для выполнения вычислений в распределенной системе, где каждый узел взаимодействует с четырьмя соседними узлами (по горизонтали и вертикали), при этом используется периодическое соединение, замыкающее границы сетки. Работа алгоритма разделена на несколько этапов: валидация входных данных, обмен информацией между узлами и последующая обработка полученных данных. Все операции выполняются параллельно, а для координации узлов и оптимизации вычислений используется библиотека MPI, что обеспечивает эффективную работу в условиях многозадачности.

2024-12-02 22:08 UTC, decl1 approved these changes

2024-12-02 22:08 UTC, decl1 commented on tasks/mpi/mezhuev_m_lattice_torus/perf_tests/main.cpp
> +  std::vector<uint8_t> input_data(2020, 1);
Вместо магического числа 2020, использовать константу
```suggestion
  const int count = 2020;
  std::vector<uint8_t> input_data(count, 1);
```
Исправить везде в похожих местах

2024-12-02 22:16 UTC, decl1 requested changes

2024-12-02 22:16 UTC, decl1 commented on tasks/mpi/mezhuev_m_lattice_torus/func_tests/main.cpp
> +#include "mpi/mezhuev_m_lattice_torus/include/mpi.hpp"
Добавить пустую строку после
```suggestion
#include "mpi/mezhuev_m_lattice_torus/include/mpi.hpp"

```

2024-12-02 22:16 UTC, decl1 commented on tasks/mpi/mezhuev_m_lattice_torus/perf_tests/main.cpp
> +  std::vector<uint8_t> input_data(2020, 1);
Вместо магического числа в тестах использовать константу
```suggestion
  const int count = 2020;
  std::vector<uint8_t> input_data(count, 1);
```
Сделать во всех тестах

2024-12-02 23:41 UTC, allnes commented on tasks/mpi/mezhuev_m_lattice_torus/src/mpi.cpp
> +
its validation

2024-12-04 14:11 UTC, decl1 approved these changes

2024-12-06 00:31 UTC, allnes approved these changes

2024-12-06 16:52 UTC, aobolensk requested changes
Reported code coverage is too low

2024-12-08 17:54 UTC, Kvoks approved these changes

2024-12-09 16:34 UTC, ChastovSlava approved these changes

2024-12-12 06:37 UTC, aobolensk approved these changes

2024-12-12 06:39 UTC, merged