Хованский Дмитрий. Задача 2. Вариант 16. Ленточная вертикальная схема.
learning-process/ppc-2024-autumn pull request #395
Opened 2024-11-29 14:07 UTC by Kvoks

Задача умножения матрицы на вектор заключается в том, чтобы вычислить результирующий вектор, каждый элемент которого представляет собой скалярное произведение строки матрицы на входной вектор. При использовании ленточной вертикальной схемы элементы матрицы распределяются между процессами по колонкам. Алгоритм предполагает распределение данных и вычислений для повышения производительности.

Описание последовательной задачи:

1. Инициализация данных:
    Матрица и вектор загружаются в память из входных данных. Проверяется согласованность размеров.

2. Вычисление результата:
Выполняется обход строк матрицы. Для каждой строки происходит умножение её элементов на соответствующий элемент входного вектора и суммирование результата.

3. Сохранение результата:
Результирующий вектор сохраняется и передаётся в выходные данные.

Описание MPI задачи:

1. Разделение данных:
Процесс с рангом 0 делит матрицу вертикально по колонкам, распределяя блоки между всеми процессами. Вектор, который участвует в умножении, также передаётся всем процессам.

2. Передача данных:
Матрица и вектор пересылаются всем процессам с использованием механизма broadcast. Каждый процесс получает свои столбцы матрицы для дальнейших вычислений.

3. Вычисления на процессах:
Каждый процесс умножает полученные столбцы матрицы на входной вектор, формируя локальные частичные результаты.

4. Сбор результатов:
Локальные результаты суммируются в процессе с рангом 0 с использованием операции reduce. Итоговый вектор формируется как сумма всех частичных результатов.

5. Сохранение результата:
Процесс с рангом 0 сохраняет окончательный результат во выходные данные.

2024-11-29 15:13 UTC, venn2713 requested changes
Наработки неплохие, но вот момент с передачей матрицы и вектора через бродкаст смущает. Возможно на неэффективный алгоритм потянет. А там можно было бы хранить матрицу в столбцовом виде, тоесть не {1, 2, 3, 4, 5, 6, 7, 8, 9} матрицу 3x3 а {1, 4, 7, 2, 5, 8, 3, 6, 9 } и тогда можно было бы рассчитать так же sizes и displs и воспользоваться scatterv, каждый воркер обработал бы свой массив данных. Тоесть для обработки первого столбца тебе было бы достаточно передать от матрицы {1, 4, 7} и от вектора первый элемент. Так ты сэкономил бы сильно по памяти

2024-11-29 16:40 UTC, Kvoks commented on tasks/mpi/khovansky_d_ribbon_vertical_scheme/src/ops_mpi.cpp
> +  }
Thx, fixed

2024-11-29 16:40 UTC, Kvoks commented on tasks/mpi/khovansky_d_ribbon_vertical_scheme/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, rows_offsets, 0);
Thx, fixed

2024-11-29 16:40 UTC, Kvoks commented on tasks/seq/khovansky_d_ribbon_vertical_scheme/func_tests/main.cpp
> +  ASSERT_EQ(ribbonVerticalSchemeSeq.validation(), false);
Thx, fixed

2024-11-29 16:41 UTC, Kvoks commented on tasks/mpi/khovansky_d_ribbon_vertical_scheme/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, hello_vector, 0);
Thanks for the comment, but I don't fully agree. Despite the full transfer of matrix data, each process processes only the part allocated to it, thus the logic of partitioning and parallelization is observed.

2024-11-30 13:29 UTC, ChastovSlava requested changes

2024-11-30 13:29 UTC, ChastovSlava commented on tasks/mpi/khovansky_d_ribbon_vertical_scheme/func_tests/main.cpp
> +  }
Move duplicate code into a separate function.

2024-11-30 14:03 UTC, Kvoks commented on tasks/mpi/khovansky_d_ribbon_vertical_scheme/func_tests/main.cpp
> +  }
Thx, fixed

2024-11-30 14:03 UTC, ChastovSlava approved these changes

2024-12-02 23:46 UTC, allnes commented on tasks/mpi/khovansky_d_ribbon_vertical_scheme/func_tests/main.cpp
> +  int columns_count = 5;
please check case when matrix and vector sizes are different (e.g. 10, 11, 12)

2024-12-02 23:46 UTC, allnes commented on tasks/mpi/khovansky_d_ribbon_vertical_scheme/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
please remove it

2024-12-02 23:46 UTC, allnes commented on tasks/seq/khovansky_d_ribbon_vertical_scheme/src/ops_seq.cpp
> +using namespace std::chrono_literals;
please remove it

2024-12-03 00:28 UTC, Kvoks commented on tasks/mpi/khovansky_d_ribbon_vertical_scheme/func_tests/main.cpp
> +  int columns_count = 5;
Thx, fixed

2024-12-03 00:28 UTC, Kvoks commented on tasks/mpi/khovansky_d_ribbon_vertical_scheme/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
Thx, fixed

2024-12-03 00:28 UTC, Kvoks commented on tasks/seq/khovansky_d_ribbon_vertical_scheme/src/ops_seq.cpp
> +using namespace std::chrono_literals;
Thx, fixed

2024-12-06 00:31 UTC, allnes approved these changes

2024-12-07 07:20 UTC, aobolensk approved these changes

2024-12-07 07:22 UTC, merged