Golovkin Maksim. Task№2. Var №17. Rowwise_matrix_partitioning
learning-process/ppc-2024-autumn pull request #396
Opened 2024-11-29 20:17 UTC by Mxaqq

2024-11-30 23:24 UTC, Mxaqq commented on tasks/mpi/golovkin_rowwise_matrix_partitioning/func_tests/main.cpp
> +TEST(golovkin_rowwise_matrix_partitioning, test_small_matrices) {
I delete this test he is failed all time. I detect it.

2024-12-03 21:14 UTC, LizochkaSpring commented on tasks/mpi/golovkin_rowwise_matrix_partitioning/include/ops_mpi.hpp
> +
Please transfer it to private

2024-12-03 21:14 UTC, LizochkaSpring commented on tasks/mpi/golovkin_rowwise_matrix_partitioning/src/ops_mpi.cpp
> +#include <thread>
Delete unnecessary include

2024-12-03 21:14 UTC, LizochkaSpring commented on tasks/mpi/golovkin_rowwise_matrix_partitioning/src/ops_mpi.cpp
> +    }
Transfer not by elements

2024-12-04 14:32 UTC, LizochkaSpring approved these changes

2024-12-04 17:57 UTC, Semyon1104 approved these changes

2024-12-06 00:32 UTC, allnes commented on tasks/mpi/golovkin_integration_rectangular_method/func_tests/main.cpp
> +﻿// Golovkin Maksim
please separate tasks to different PRs

2024-12-08 11:29 UTC, allnes commented on tasks/mpi/golovkin_integration_rectangular_method/func_tests/main.cpp
> +  if (world.size() < 5 || world.rank() >= 4) {
why do you check it?

2024-12-08 11:31 UTC, allnes commented on tasks/mpi/golovkin_integration_rectangular_method/src/ops_mpi.cpp
> +  int timeout_ms = 3000;
why doyou think that validation will be slow?

2024-12-08 11:32 UTC, allnes commented on tasks/mpi/golovkin_integration_rectangular_method/src/ops_mpi.cpp
> +  int timeout_ms = 5000;
please remove timeout everywhere here its create problem for our checks

2024-12-08 11:32 UTC, allnes commented on tasks/mpi/golovkin_rowwise_matrix_partitioning/func_tests/main.cpp
> +void get_random_matrix(double *matr, int size) {
matrix can have different rows and cols

2024-12-10 19:20 UTC, aobolensk requested changes

2024-12-10 19:20 UTC, aobolensk commented on tasks/mpi/golovkin_integration_rectangular_method/func_tests/main.cpp
> +  int partition_count = 1000000;
I think partition count may be lowered for some func tests

2024-12-10 19:20 UTC, aobolensk commented on tasks/mpi/golovkin_integration_rectangular_method/func_tests/main.cpp
> +  if (world.size() < 5 || world.rank() >= 4) {
Why your tests are working on world.size() < 5 ?

2024-12-10 19:20 UTC, aobolensk commented on tasks/mpi/golovkin_integration_rectangular_method/src/ops_mpi.cpp
> +  broadcast(world, lower_bound, 0);
Please, move data transfer to ::run() function

2024-12-12 06:37 UTC, aobolensk approved these changes

2024-12-13 16:33 UTC, allnes approved these changes

2024-12-13 16:33 UTC, merged