Созонов Илья. Задача 2. Вариант 19. Метод Гаусса – ленточная горизонтальная схема.
learning-process/ppc-2024-autumn pull request #397
Opened 2024-11-29 23:56 UTC by sozozzya

2024-12-01 16:20 UTC, MatveyKurakin commented on tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/src/ops_mpi.cpp
> +    return taskData->inputs_count[0] == taskData->inputs_count[1] * (taskData->inputs_count[1] + 1) &&
also, it is necessary to check the matrix for the presence of a single solution

2024-12-01 16:20 UTC, MatveyKurakin commented on tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/src/ops_mpi.cpp
> +  return taskData->inputs_count[0] == taskData->inputs_count[1] * (taskData->inputs_count[1] + 1) &&
it is necessary to check the matrix for a single solution

2024-12-01 16:20 UTC, MatveyKurakin commented on tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/src/ops_seq.cpp
> +  return taskData->inputs_count[0] == taskData->inputs_count[1] * (taskData->inputs_count[1] + 1) &&
as in the MPI implementation, it is necessary to check the matrix for the presence of a single solution

2024-12-02 23:50 UTC, allnes requested changes

2024-12-02 23:50 UTC, allnes commented on tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/src/ops_mpi.cpp
> +bool sozonov_i_gaussian_method_horizontal_strip_scheme_mpi::TestMPITaskSequential::pre_processing() {
for that task we can check answer by ||Ax -b|| = 0, sequential version need to be check only perf version, and sequential version need to be checked same by ||Ax -b|| = 0

2024-12-02 23:51 UTC, allnes commented on tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/func_tests/main.cpp
> +  const int count = 10;
please add test values for diffrent rows and cols

2024-12-03 18:06 UTC, KolodkinGrigorii commented on tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/func_tests/main.cpp
> +TEST(sozonov_i_gaussian_method_horizontal_strip_scheme_mpi, test_10_unknowns) {
add test for random matrix

2024-12-06 16:58 UTC, aobolensk requested changes

2024-12-06 16:58 UTC, aobolensk commented on tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/func_tests/main.cpp
> +#include <vector>
Please, add fixed tests to func_tests as well

2024-12-07 04:33 UTC, sozozzya commented on tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/src/ops_mpi.cpp
> +    return taskData->inputs_count[0] == taskData->inputs_count[1] * (taskData->inputs_count[1] + 1) &&
fixed, please check

2024-12-07 04:34 UTC, sozozzya commented on tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/src/ops_mpi.cpp
> +  return taskData->inputs_count[0] == taskData->inputs_count[1] * (taskData->inputs_count[1] + 1) &&
fixed, please check

2024-12-07 04:34 UTC, sozozzya commented on tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/src/ops_seq.cpp
> +  return taskData->inputs_count[0] == taskData->inputs_count[1] * (taskData->inputs_count[1] + 1) &&
fixed, please check

2024-12-07 04:34 UTC, sozozzya commented on tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/src/ops_mpi.cpp
> +bool sozonov_i_gaussian_method_horizontal_strip_scheme_mpi::TestMPITaskSequential::pre_processing() {
fixed, please check

2024-12-07 04:34 UTC, sozozzya commented on tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/func_tests/main.cpp
> +  const int count = 10;
fixed, please check

2024-12-07 04:34 UTC, sozozzya commented on tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/func_tests/main.cpp
> +TEST(sozonov_i_gaussian_method_horizontal_strip_scheme_mpi, test_10_unknowns) {
fixed, please check

2024-12-07 04:34 UTC, sozozzya commented on tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/src/ops_mpi.cpp
> +    matrix[i] = tmp_ptr[i];
fixed, please check

2024-12-07 04:34 UTC, sozozzya commented on tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/func_tests/main.cpp
> +#include <vector>
fixed, please check

2024-12-07 06:41 UTC, MatveyKurakin approved these changes

2024-12-07 13:47 UTC, KolodkinGrigorii approved these changes

2024-12-08 11:33 UTC, allnes approved these changes

2024-12-08 14:15 UTC, aobolensk approved these changes

2024-12-08 14:15 UTC, merged