Комшина Дарья. Задача 2. Вариант 13. Топология сети передачи данных решетка-тор.
learning-process/ppc-2024-autumn pull request #398
Opened 2024-11-30 00:48 UTC by MikasaAkc

Алгоритм решетка-топор работает в распределенной системе, где каждый узел общается с четырьмя соседями (слева, справа, сверху и снизу) с учетом периодической (топорной) связи между ними. Он выполняет несколько этапов: проверяет корректность данных, обменивается информацией между узлами и обрабатывает данные после обмена. Всё это происходит параллельно с использованием MPI для эффективной работы в многозадачной среде.

2024-11-30 12:56 UTC, NeeMiyuki requested changes

2024-11-30 12:56 UTC, NeeMiyuki commented on tasks/mpi/komshina_d_grid_torus_topology/include/ops_mpi.hpp
> +#include <vector>
Array, cmath, functional, string are included, but there is no sign they are used so it should be removed

2024-11-30 13:20 UTC, MikasaAkc commented on tasks/mpi/komshina_d_grid_torus_topology/src/ops_mpi.cpp
> +        std::vector<uint8_t> send_data(taskData->inputs_count[0], 0);
fixed

2024-11-30 13:20 UTC, MikasaAkc commented on tasks/mpi/komshina_d_grid_torus_topology/include/ops_mpi.hpp
> +#include <vector>
fixed

2024-11-30 15:18 UTC, Dxppi commented on tasks/mpi/komshina_d_grid_torus_topology/src/ops_mpi.cpp
> +        }
Add a test for this code line to increase code coverage

2024-11-30 16:55 UTC, NeeMiyuki approved these changes

2024-12-01 09:00 UTC, MikasaAkc commented on tasks/mpi/komshina_d_grid_torus_topology/src/ops_mpi.cpp
> +        }
fixed

2024-12-01 11:54 UTC, Dxppi approved these changes

2024-12-01 14:08 UTC, PutinVVV approved these changes

2024-12-02 23:52 UTC, allnes commented on tasks/mpi/komshina_d_grid_torus_topology/src/ops_mpi.cpp
> +bool komshina_d_grid_torus_topology_mpi::GridTorusTopologyParallel::pre_processing() { return validation(); }
why do you use validation in pre_processing

2024-12-02 23:53 UTC, allnes commented on tasks/mpi/komshina_d_grid_torus_topology/src/ops_mpi.cpp
> +  int grid_size = std::sqrt(size);
please check that grid size is integer after std::sqrt(size), how calculate case size == 3

2024-12-04 12:26 UTC, MikasaAkc commented on tasks/mpi/komshina_d_grid_torus_topology/src/ops_mpi.cpp
> +bool komshina_d_grid_torus_topology_mpi::GridTorusTopologyParallel::pre_processing() { return validation(); }
fixed

2024-12-04 12:26 UTC, MikasaAkc commented on tasks/mpi/komshina_d_grid_torus_topology/src/ops_mpi.cpp
> +  int grid_size = std::sqrt(size);
fixed

2024-12-06 00:34 UTC, allnes approved these changes

2024-12-06 17:07 UTC, aobolensk approved these changes

2024-12-06 17:08 UTC, merged