Сомов Иван. Задача №2. Вариант 15. Ленточная горизонтальная схема
learning-process/ppc-2024-autumn pull request #399
Opened 2024-11-30 02:39 UTC by qfrff

### SEQ реализация:

1. Подготовка данных (pre_processing):
В методе pre_processing создается и инициализируется матрица, вектор и результат. Матрица и вектор считываются из входных данных, которые передаются через объект taskData. Эти данные передаются как массивы байт, которые затем интерпретируются как массивы целых чисел (int32_t). Вектор и матрица копируются из входных данных в соответствующие структуры.

2. Проверка данных (validation):
В методе validation происходит проверка, что количество строк в матрице (то есть размер первого измерения) 
соответствует количеству элементов в результате. Это важно для корректности задачи умножения матрицы на вектор, так как результат должен быть вектором, содержащим столько элементов, сколько строк в матрице.

3. Выполнение вычислений (run):
В методе run происходит само умножение матрицы на вектор. Для каждой строки матрицы происходит вычисление скалярного произведения этой строки на вектор. Для каждой строки матрицы, в цикле, накапливаются произведения соответствующих элементов строки матрицы и вектора, и результат сохраняется в отведённом векторе.

4. Запись результата (post_processing):
В методе post_processing результат вычислений записывается обратно в выходные данные. Результат копируется в выходной буфер, который затем передается обратно в вызывающий код через taskData->outputs.

### MPI реализация: 

в процессе...

2024-12-08 11:34 UTC, allnes commented on tasks/mpi/somov_i_horizontal_scheme/src/ops_mpi.cpp
> +  if (world.rank() != 0) return false;
please in test add gtest ignore insteads this comparison

2024-12-08 11:36 UTC, allnes commented on tasks/seq/somov_i_horizontal_scheme/func_tests/main.cpp
> +  uint32_t colCount = 5;
please check different rows and cols, e.g.  (17x32) (64x100) (81x17)

2024-12-08 11:36 UTC, allnes commented on tasks/seq/somov_i_horizontal_scheme/perf_tests/main.cpp
> +  uint32_t colCount = 3500;
```suggestion
  uint32_t rowCount = 3501;
  uint32_t colCount = 3499;
```

2024-12-08 13:59 UTC, qfrff commented on tasks/seq/somov_i_horizontal_scheme/func_tests/main.cpp
> +  uint32_t colCount = 5;
added

2024-12-08 13:59 UTC, qfrff commented on tasks/seq/somov_i_horizontal_scheme/perf_tests/main.cpp
> +  uint32_t colCount = 3500;
fixed

2024-12-09 19:53 UTC, qfrff commented on tasks/mpi/somov_i_horizontal_scheme/src/ops_mpi.cpp
> +  if (world.rank() != 0) return false;
fixed

2024-12-10 00:28 UTC, ev1ven commented on tasks/mpi/somov_i_horizontal_scheme/func_tests/main.cpp
> +}
Этот тест проверяет распределение только для большого количества строк, но этого недостаточно для полной проверки алгоритма. Уже есть тесты, такие как "test_distribution_more_processes_than_rows", которые проверяют корректность распределения (хоть и для более малых данных). Чтобы сделать проверку более полной, стоит добавить дополнительные проверки, такие как (например): отсутствие перекрытия строк между процессами, правильность распределения при разных количествах процессов, и гарантию того, что все строки будут распределены без пропусков.

2024-12-10 00:28 UTC, ev1ven commented on tasks/mpi/somov_i_horizontal_scheme/func_tests/main.cpp
> +TEST(somov_i_horizontal_scheme, test_distribution_more_processes_than_rows) {
Добавьте противоположный тест для случая, когда количество строк больше, чем количество процессов.

2024-12-10 01:02 UTC, qfrff commented on tasks/mpi/somov_i_horizontal_scheme/func_tests/main.cpp
> +TEST(somov_i_horizontal_scheme, test_distribution_more_processes_than_rows) {
adeed

2024-12-10 01:44 UTC, qfrff commented on tasks/mpi/somov_i_horizontal_scheme/func_tests/main.cpp
> +}
fixed

2024-12-10 10:06 UTC, ev1ven approved these changes

2024-12-10 19:28 UTC, Dxppi commented
increase code covarage %

2024-12-10 20:35 UTC, Sedova-Olga requested changes

2024-12-10 20:35 UTC, Sedova-Olga commented on tasks/mpi/somov_i_horizontal_scheme/src/ops_mpi.cpp
> +bool somov_i_horizontal_scheme::MatrixVectorTask::run() {
i * colCount_ пересчитывается на каждой итерации внутреннего цикла. Это избыточно, т. к. значение остаётся неизменным в пределах строки. Можно вынести вычисление этого индекса за пределы внутреннего цикла, предварительно вычислив его перед началом обработки строки.

2024-12-10 21:35 UTC, qfrff commented on tasks/mpi/somov_i_horizontal_scheme/src/ops_mpi.cpp
> +bool somov_i_horizontal_scheme::MatrixVectorTask::run() {
fixed

2024-12-11 06:06 UTC, Sedova-Olga approved these changes

2024-12-13 19:32 UTC, aobolensk commented
30% API coverage

2024-12-14 00:14 UTC, qfrff commented
> 30% API coverage

fixed

2024-12-14 10:52 UTC, aobolensk approved these changes

2024-12-15 19:11 UTC, allnes approved these changes

2024-12-15 19:11 UTC, merged