Кабалова Валерия. Задача 1. Вариант 22. Подсчет буквенных символов в строке.
learning-process/ppc-2024-autumn pull request #40
Opened 2024-10-25 06:56 UTC by m1likus

Последовательная реализация: проходим по строке input_, проверяем каждый символ с помощью isalpha(). Если символ - буква верхнего или нижнего регистра, увеличиваем счетчик на 1.
Параллельная реализация:
Делим строку на количество процессов, получаем подстроки, и в каждой подстроке считаем количество букв. Проблема такого подхода заключается в том, что не всегда str.size % num_threads == 0, поэтому для последнего процесса нужно посчитать, сколько для него составляет разница между str.size и суммарной длинной всех остальных подстрок. Эту разницу вычесть из delta для последнего процесса. Для обобщения сделано так, что каждый процесс получает delta - 0, а последний процесс delta - разница.
Также поддерживается возможность того, что длина строки меньше числа используемых процессов.
Функции getRandomNumber и getRandomString позволяют генерировать строки произвольной длины. Сравнение результата mpi-версии происходит с результатом seq-версии.

2024-10-25 08:24 UTC, hasanyanovk commented on tasks/mpi/kabalova_v_count_symbols/src/count_symbols_mpi.cpp
> +    flag2 = true;
useless compare

2024-10-25 08:26 UTC, hasanyanovk commented on tasks/mpi/kabalova_v_count_symbols/include/count_symbols_mpi.hpp
> +class Task1Seq : public ppc::core::Task {
Invalid name of class, check example

2024-10-25 08:30 UTC, m1likus commented on tasks/mpi/kabalova_v_count_symbols/src/count_symbols_mpi.cpp
> +    flag2 = true;
Any other idea how to check if we got a string on input, not, like, a number?

2024-10-25 08:32 UTC, m1likus commented on tasks/mpi/kabalova_v_count_symbols/include/count_symbols_mpi.hpp
> +class Task1Seq : public ppc::core::Task {
Fine

2024-10-25 08:35 UTC, m1likus commented on tasks/mpi/kabalova_v_count_symbols/include/count_symbols_mpi.hpp
> +class Task1Seq : public ppc::core::Task {
Actually not sure if it matters, because there's nothing about it in readme, but i'll fix it

2024-10-25 09:49 UTC, hasanyanovk commented on tasks/mpi/kabalova_v_count_symbols/src/count_symbols_mpi.cpp
> +    flag2 = true;
This check will not work and is not needed, but
if you want to check size of input tupe, you can use template requires.
However, this check is not neccessary, you can simply delete it

2024-10-25 10:21 UTC, kmichaelk commented on tasks/mpi/kabalova_v_count_symbols/src/count_symbols_mpi.cpp
> +    flag2 = true;
> if you want to check size of input tupe, you can use template requires.

This is not the case here. As for RTTI, it has already been defeated by the preceding reinterpret cast, not to mention that such relying on RTTI is a terrible practice in general.

2024-10-25 13:16 UTC, ascannel requested changes
add correctness check to the sequential implementation, or remove it from both

2024-10-25 14:50 UTC, m1likus commented on tasks/mpi/kabalova_v_count_symbols/perf_tests/main.cpp
> +    ASSERT_EQ(count_symbols, global_out[0]);
Got it

2024-10-25 15:15 UTC, aobolensk requested changes

2024-10-25 15:15 UTC, aobolensk commented on tasks/seq/example/func_tests/main.cpp
> +}
Please, revert these changes in examples

2024-10-26 18:03 UTC, m1likus commented on tasks/seq/example/func_tests/main.cpp
> +}
I have no idea what is wrong with this bracket

2024-10-26 21:34 UTC, ascannel approved these changes

2024-10-27 02:27 UTC, aobolensk commented on tasks/seq/example/func_tests/main.cpp
> +}
You have removed the new line after this bracket

2024-10-27 08:10 UTC, m1likus commented on tasks/seq/example/func_tests/main.cpp
> +}
Fixed

2024-10-27 09:45 UTC, allnes approved these changes

2024-10-27 14:31 UTC, aobolensk approved these changes

2024-10-27 14:32 UTC, merged