Резанцева Анастасия. Задача 2. Вариант 24. Метод простых итераций.
learning-process/ppc-2024-autumn pull request #401
Opened 2024-11-30 11:04 UTC by AnastasiaRezantseva

**Методы простых итераций** (последовательная версия)
Преобразуем систему Ax = b к виду x = Bx + c
Метод простых итераций заключается в том, что по известному приближению k, мы можем найти (k+1)-е приближение:
![image](https://github.com/user-attachments/assets/421237af-a05b-4fcf-92dd-13172ee57303)

где **B** - матрица перехода, элементы матрицы B вычисляются как:
Bij = 0, если i = j (диагональные элементы)
Bij = -Aij/Aii, если i ≠ j (недиагональные элементы)
**c** - вектор итераций, ci = bi/Aii
**τ** - неопределенный параметр, от которого зависит, будет ли сходиться метод, а если будет, то какова скорость сходимости, т.е. как много итераций нужно совершить для достижения требуемой точности. В простейшем случае τ можно положить равным некоторому постоянному числу, например, в данной реализации **τ = 1**

Метод простых итераций **_сходится тогда и только тогда,_** когда все собственные числа матрицы по модулю меньше единицы.

На вход получаем количество неизвестных n, матрицу A, содержащую коэффициенты линейных уравнений, вектор решений b, начальное приближение вектор x заполнен нулями.
В validation() проверяется правильность заполнения входных данных, количество неизвестных должно быть неотрицательным, а также условие диагональной доминантности матрицы А, так как это обеспечивает условие сходимости метода.
(Матрица имеет диагональное преобладание, если для каждой строки модуль диагонального элемента больше суммы модулей всех остальных элементов строки: |aii| > Σ|aij| (i≠j)
Если это условие выполняется, то норма матрицы B автоматически будет меньше 1)

Итерационный процесс: 
![image](https://github.com/user-attachments/assets/4f71859b-1808-45af-a26d-a311846f55df)

Итерационный процесс происходит, пока не будет достигнута заданная точность или превышено максимальное количество итераций (это ограничение, чтобы избежать бесконечного цикла, в случае невозможности достижения заданного приближения).

**MPI реализация**
В параллельной реализации процесс просчитывает новые приближения x на каждом шаге итерации для своего набора уравнений (своих строк матрицы B и соответствующих данных из вектора c). После каждой итерации корневой процесс собирает все новые x и проводит проверку погрешности: 
![image](https://github.com/user-attachments/assets/ae309082-deb5-4417-a737-565710bdb07f)
Если необходимая погрешность достигнута, итерационный процесс останавливается. Если точность не достигнута, то текущее приближение становится предыдущим, вычисленное - текущим и рассылается процессам для продолжения итеративного процесса
**Распределение данных процессам:**
Матрица B и вектор c распределяются по процессам блоками строк, для эффективности передачи больших матриц используется разбиение на чанки
Все процессы хранят полную копию текущего приближения x

P.S. из-за невнимательности я реализовывала метод Якоби, в момент создания PR увидела, что у меня немного другой метод.

2024-11-30 12:49 UTC, Tanya-Yasakova commented on tasks/mpi/rezantseva_a_simple_iteration_method/func_tests/main_rezantseva.cpp
> +#include <random>
Remove unnecessary includes that are already in the header files

2024-11-30 12:49 UTC, Tanya-Yasakova commented on tasks/mpi/rezantseva_a_simple_iteration_method/perf_tests/main_rezantseva.cpp
> +#include <random>
Remove unnecessary includes that are already in the header files

2024-12-01 16:37 UTC, m1likus requested changes

2024-12-01 16:37 UTC, m1likus commented on tasks/mpi/rezantseva_a_simple_iteration_method/src/ops_mpi_rezantseva.cpp
> +  return true;
Все процессы должны возвращать одно и то же значение в валидации. Попробуй использовать отдельную булевскую переменную

2024-12-01 16:37 UTC, m1likus commented on tasks/mpi/rezantseva_a_simple_iteration_method/src/ops_mpi_rezantseva.cpp
> +}
Уже есть такая функция checkMatrix, попробуй их объединить и для последовательного и параллельного случая, иначе получается повторяемость кода

2024-12-01 20:03 UTC, Tanya-Yasakova commented on tasks/mpi/rezantseva_a_simple_iteration_method/func_tests/main_rezantseva.cpp
> +  std::random_device rd;
You can make a range with negative numbers. Add maximum number to variable

2024-12-02 23:58 UTC, allnes commented on tasks/mpi/rezantseva_a_simple_iteration_method/src/ops_mpi_rezantseva.cpp
> +bool rezantseva_a_simple_iteration_method_mpi::SimpleIterationMPI::validation() {
please check single solution

2024-12-03 08:15 UTC, AnastasiaRezantseva commented on tasks/mpi/rezantseva_a_simple_iteration_method/src/ops_mpi_rezantseva.cpp
> +bool rezantseva_a_simple_iteration_method_mpi::SimpleIterationMPI::validation() {
@allnes  I'm sorry, but I didn't quite understand your request. can you explain in more detail

2024-12-03 14:37 UTC, AnastasiaRezantseva commented on tasks/mpi/rezantseva_a_simple_iteration_method/src/ops_mpi_rezantseva.cpp
> +  return true;
Поправила, теперь все процессы возвращают одно значение валидации, благодаря флагу, который может изменить значение  с true  на false на нулевом процессе, в случае, если данные не прошли проверку на корректность

2024-12-03 14:41 UTC, AnastasiaRezantseva commented on tasks/mpi/rezantseva_a_simple_iteration_method/src/ops_mpi_rezantseva.cpp
> +}
Внесла изменения, теперь в последовательном и параллельном случаях в валидации используется функция из моего пространства имен, которая выполняет проверку матрицы на диагональное доминирование

2024-12-03 14:42 UTC, AnastasiaRezantseva commented on tasks/mpi/rezantseva_a_simple_iteration_method/func_tests/main_rezantseva.cpp
> +  std::random_device rd;
Fix, now the matrix is ​​filled not only with positive numbers, and the boundaries of the range of values ​​are now constants

2024-12-03 14:50 UTC, Tanya-Yasakova approved these changes

2024-12-04 21:42 UTC, AnastasiaRezantseva commented on tasks/mpi/rezantseva_a_simple_iteration_method/src/ops_mpi_rezantseva.cpp
> +bool rezantseva_a_simple_iteration_method_mpi::SimpleIterationMPI::validation() {
Added function to check  if the system has a single solution

2024-12-05 11:02 UTC, m1likus approved these changes

2024-12-06 00:36 UTC, allnes approved these changes

2024-12-07 07:20 UTC, aobolensk approved these changes

2024-12-07 07:23 UTC, merged