Филатьев Владислав. Задача 2. Вариант 23. Итеративные методы (Зейделя)
learning-process/ppc-2024-autumn pull request #402
Opened 2024-11-30 11:58 UTC by WladislawFilatew

#### Решение системы линейных алгебраических уравнений (СЛАУ) методом Зейделя
Описание последовательной задачи:

В начале работы программа создаёт начальное приближенное решение. Затем в цикле уточняет это приближение, используя значения коэффициентов из матрицы и вектора свободных членов. На каждом шаге цикла (итерации) новые значения вычисляются на основе уже обновлённых значений предыдущих компонент вектора. Процесс повторяется до тех пор, пока не будет достигнута требуемая точность.

Описание параллельной задачи (MPI):

Матрица коэффициентов и вектор свободных членов распределяются между участвующими процессами. Каждый процесс отвечает за обновление части строк матрицы и соответствующих элементов вектора решения. Процессы обмениваются данными, чтобы обеспечить согласованность результатов. Для ускорения вычислений используется распараллеливание.  Вычисления прекращаются, когда достигается требуемая точность.

2024-11-30 17:00 UTC, LizochkaSpring commented on tasks/seq/filatev_v_metod_zedela/func_tests/main.cpp
> +  double alfa = 0.0001;
Дать тестам более понятные названия

2024-11-30 17:13 UTC, Cufeed commented on tasks/mpi/filatev_v_metod_zedela/func_tests/main.cpp
> +
In tests, you initially allocate memory, and then use insert to add elements to the beginning, as a result, you should have a matrix twice the required size, it's better to just fill the matrix with random numbers.

2024-11-30 17:13 UTC, Cufeed commented on tasks/seq/filatev_v_metod_zedela/src/ops_seq.cpp
> +#include <string>
Delete the unnecessary include and namespace

2024-11-30 18:52 UTC, LizochkaSpring approved these changes

2024-11-30 18:54 UTC, Cufeed approved these changes

2024-12-03 00:02 UTC, allnes commented on tasks/mpi/filatev_v_metod_zedela/func_tests/main.cpp
> +  int size = 3;
please check case as rows != cols and catch assert

2024-12-04 13:47 UTC, WladislawFilatew commented on tasks/mpi/filatev_v_metod_zedela/func_tests/main.cpp
> +  int size = 3;
fixed

2024-12-06 00:37 UTC, allnes approved these changes

2024-12-07 07:24 UTC, aobolensk requested changes

2024-12-07 07:24 UTC, aobolensk commented on tasks/mpi/filatev_v_metod_zedela/func_tests/main.cpp
> +int generatorVector(std::vector<int> &vec) {
Please make these functions static or wrap with namespace to avoid collisions

2024-12-07 10:07 UTC, WladislawFilatew commented on tasks/mpi/filatev_v_metod_zedela/func_tests/main.cpp
> +int generatorVector(std::vector<int> &vec) {
fixed

2024-12-08 10:03 UTC, aobolensk requested changes
It seems test code coverage is still low
![image](https://github.com/user-attachments/assets/fb69b9b2-f9be-4998-bf85-90baafd2dcc4)

2024-12-08 18:14 UTC, WladislawFilatew commented
> Похоже, охват тестового кода по-прежнему невелик ![изображение](https://private-user-images.githubusercontent.com/31939330/393585452-fb69b9b2-f9be-4998-bf85-90baafd2dcc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2ODE5NTcsIm5iZiI6MTczMzY4MTY1NywicGF0aCI6Ii8zMTkzOTMzMC8zOTM1ODU0NTItZmI2OWI5YjItZjliZS00OTk4LWJmODUtOTBiYWFmZDJkY2M0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDE4MTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkYmJjNGYwZWJhYWMyYWEwMzc1MTg4OGU1M2NiZmRhYjI3NzM1YjE0ZWI1NmI1NzY3ZWNjOWU2MzViNDQ2OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EjuDQb-NxwzWfwShYkzfY5FTdQnAoHlUM0bil38E7QA)

Исправлено

2024-12-09 03:22 UTC, aobolensk approved these changes

2024-12-09 03:22 UTC, merged