Revert "Бессонов Егор. Задача 21. Интегрирование – метод Монте-Карло."
learning-process/ppc-2024-autumn pull request #405
Opened 2024-11-30 16:41 UTC by nCUXe

SEQ:
Метод pre_processing() извлекает границы интегрирования a и b, а также количество случайных точек num_points из входных данных.
Интегрирование:
Метод run() выполняет следующие действия:

Инициализирует генератор случайных чисел.
Генерирует num_points случайных значений x в диапазоне [a, b].
Для каждого x вычисляет значение функции и суммирует результаты.
Вычисляет итоговый результат интегрирования как произведение диапазона интегрирования (b - a) на среднее значение вычисленных функций.
MPI
Метод run() выполняет следующие действия на каждом процессе:

Определяет количество точек num_points_for_process, которое необходимо обработать текущему процессу, учитывая общее количество процессов и возможный остаток.
Генерирует num_points_for_process случайных значений x в диапазоне [a, b].
Вычисляет_ значение функции для каждого x и суммирует результаты в переменную sum.
Сбор результатов:
reduce() суммирует все результаты.
В корневом процессе вычисляется итоговый результат интегрирования как (b - a) * (res / num_points)

2024-12-03 00:05 UTC, allnes commented on tasks/mpi/bessonov_e_integration_monte_carlo/include/ops_mpi.hpp
> +  static double exampl_func(double x) { return x * x * x; }
please use more difficult function additionaly

2024-12-07 07:26 UTC, aobolensk approved these changes

2024-12-08 17:38 UTC, allnes approved these changes

2024-12-09 10:14 UTC, pipidaster2004 commented on tasks/seq/bessonov_e_integration_monte_carlo/include/ops_seq.hpp
> +  static double exampl_func(double x) { return x * x * x; }
you forgot to change the seq version as in the mpi version

2024-12-13 09:28 UTC, nCUXe commented on tasks/seq/bessonov_e_integration_monte_carlo/include/ops_seq.hpp
> +  static double exampl_func(double x) { return x * x * x; }
done

2024-12-13 09:55 UTC, emilien-gus requested changes

2024-12-13 09:55 UTC, emilien-gus commented on tasks/mpi/bessonov_e_integration_monte_carlo/include/ops_mpi.hpp
> +
in the tests, you only check how your integration algorithm works, but there are no tests for validation, please add some tests

2024-12-13 12:04 UTC, nCUXe commented on tasks/mpi/bessonov_e_integration_monte_carlo/include/ops_mpi.hpp
> +
added

2024-12-13 18:02 UTC, pipidaster2004 approved these changes

2024-12-13 18:45 UTC, emilien-gus approved these changes

2024-12-15 19:11 UTC, merged