Ворошилов Виталий. Задача 2. Вариант 13. Топология сетей передачи данных "Решётка-тор"
learning-process/ppc-2024-autumn pull request #407
Opened 2024-11-30 20:58 UTC by vitaliyvoroshilov

### Задача:
Реализовать с помощью MPI программу, в которой несколько процессов взаимодействуют между собой исключительно в рамках виртуальной топологии "решётка-тор". В рамках этой топологии процессы выстраиваются в квадратную сетку (задача актуальна только для количества процессов равного `n^2`, где n - натуральное число).

В этой сетке каждый процесс может обмениваться данными не более чем с четырьмя своими соседями (с верхним и нижним, с левым и правым), при этом сетка зациклена (существует связь между первым и последним процессами в строке, между первым и последним процессами в столбце).

Цель - передать некоторый буфер данных от процесса-источника процессу-приёмнику, проверить на приёмнике корректность дошедших данных и при этом приёмник должен получить вектор пути, по которому эти данные прошли и также проверить его правильность.

### Решение:
**Входные данные:**

- `inputs_count[0]` - ранк процесса-источника (на всех процессах)
- `inputs_count[1]` - ранк процесса-приёмника (на всех процессах)
- `inputs[0]` - буфер данных (только на источнике и приёмнике)
- `inputs_count[2]` - размер буфера данных (только на источнике и приёмнике)

**Выходные данные:**

- `outputs[0]` - буфер для записи полученных процессом-приёмником данных (только на источнике и приёмнике)
- `outputs_counts[0]` - размер буфера данных (только на источнике и приёмнике)
- `outputs[1]` - буфер для записи полученного процессом-приёмником вектора пути (только на источнике и приёмнике)

**Важные уточнения:**

- Кроме буфера данных и вектора траектории, процессы обмениваются сигналами-командами, которые определены в структуре `Commands`, без этих команд взаимодействие процессов было бы сильно затруднено или даже невозможно
- Для решения используется стандартный коммуникатор `world`, никаких возможностей MPI по работе с виртуальными топологиями не используется (используются только `send()` и `recv()`)
- В тестах для проверки работы программы процесс-источник генерирует буфер данных и отправляет его процессу-получателю напрямую, скорее всего нарушая при этом топологию, но иначе получить в начале работы программы на обоих процессах один и тот же рандомный буфер невозможно (если запускать функцию генерации на разных процессах, каждый процесс сгенерирует свой уникальный буфер). Аналогично в тесте, в котором случайным образом генерируются ранк процесса-источника и ранк процесса-получателя, эти 2 значения рассылаются с помощью `broadcast()`, нарушая топологию
- Если количество процессов не равно `n^2`, тест завершается и считается пройденным

**Этапы работы программы в функции `run()`:**

1. Путь от процесса-источника к процессу получателю, в ходе которого последовательно от процесса к процессу согласно топологии с помощью команд `send_from_source` и `route_to_dest` передаётся буфер данных и при этом постепенно формируется вектор пути (составленный из ранков задействованных процессов). Алгоритм выбора следующего процесса основан на формировании декартовой системы координат, где `(0,0)` - процесс с ранком `0`, `(n,n)` - процесс с ранком `n^2` (координаты возрастают вправо, вниз). Т.к. строки и столбцы сетки закольцованы, можно было бы идти в обе стороны, но алгоритм для текущего процесса обеспечивает однозначный выбор соседа, от которого путь будет кратчайший. ![TorusGrid_Step1](https://github.com/user-attachments/assets/674abb16-11b7-4f14-a5a6-c1f0e8839aae)
2. Процесс-приёмник получил буфер данных и вектор пути, теперь задача - корректно завершить все процессы. Для этого последовательно передаются команды `move_to_zero` по тому же кратчайшему алгоритму до процесса `0`.
![TorusGrid_Step2](https://github.com/user-attachments/assets/37af85c5-e239-4a10-918f-7e7dcb4ae9d4)

3. Начиная с процесса `0` идёт последовательная отправка команд `direct_terminate` и `reverse_terminate,` с помощью которых осуществляется полный обход всех процессов и их завершение (каждый процесс отправляет команду на завершение следующему и после этого завершается сам, последний процесс ничего не отправляет и просто завершается). Алгоритм здесь уже другой: проход до конца строки вправо и спуск на следующую строку, затем проход до начала строки налево и спуск вниз и так далее. 
![TorusGrid_Step3](https://github.com/user-attachments/assets/d6899c97-b4d6-49c4-a109-a5d82cdda801)

На этом всё, все процессы завершили основную функцию `run()`, затем процесс-приёмник запишет данные в `outputs[0]`, запишет вектор пути в `outputs[1]` и проверит их в конце теста.

2024-12-03 00:12 UTC, allnes commented on tasks/mpi/voroshilov_v_torus_grid/func_tests/main.cpp
> +}
```
long long sr = sqrt(x);
return sr * sr == x
```

2024-12-03 00:12 UTC, allnes commented on tasks/mpi/voroshilov_v_torus_grid/func_tests/main.cpp
> +  int data_size = 100000;
please check different values, prime values, 2^n, 100001

2024-12-04 20:37 UTC, kalyakinaa requested changes
I read description of your task and found how to optimize solution in 3rd stage of program. Here the processes destroys sequentially in row, the complexity of your algorithm is `O(n^2)`. I suggest optimization: destroy processes by columns according to the following algorithm:
![ChangeAlgorithm](https://github.com/user-attachments/assets/7f2f3255-f962-446e-8a24-1e8b7d933b78)
The complexity of this will be about `O(n)`

2024-12-04 20:37 UTC, kalyakinaa commented on tasks/mpi/voroshilov_v_torus_grid/src/ops_mpi.cpp
> +    return false;
I think in `validation()` it'll be better, if you check if there is `n^2` processes for all processes, not only for `src` process, because all other processes will continue, but as I understand your task does not make sense when there are no `n*n` processes

2024-12-05 20:55 UTC, vitaliyvoroshilov commented on tasks/mpi/voroshilov_v_torus_grid/func_tests/main.cpp
> +}
Fixed

2024-12-05 20:55 UTC, vitaliyvoroshilov commented on tasks/mpi/voroshilov_v_torus_grid/func_tests/main.cpp
> +  int data_size = 100000;
Fixed

2024-12-05 21:01 UTC, vitaliyvoroshilov commented on tasks/mpi/voroshilov_v_torus_grid/src/ops_mpi.cpp
> +    return false;
Fixed.
And thank You for cool way to terminate processes!!! I added this to code, look!

2024-12-06 08:43 UTC, kalyakinaa approved these changes

2024-12-06 09:51 UTC, Egor1dzeN-learn requested changes

2024-12-06 09:51 UTC, Egor1dzeN-learn commented on tasks/mpi/voroshilov_v_torus_grid/perf_tests/main.cpp
> +      world.send(0, perf_tags.send_flag_path, flag_path);
I think here you dont need to initialize vectors on all process, just declare it and then you will initialize them only on processes src and dst

2024-12-06 11:31 UTC, Egor1dzeN-learn requested changes

2024-12-06 11:31 UTC, Egor1dzeN-learn commented on tasks/mpi/voroshilov_v_torus_grid/func_tests/main.cpp
> +  std::vector<int> output_path(expected_path.size());
I think here you dont need to initialize vectors on all process, just declare it and then you will initialize them only on processes src and dst

2024-12-06 11:31 UTC, Egor1dzeN-learn commented on tasks/mpi/voroshilov_v_torus_grid/func_tests/main.cpp
> +  }
I think you dont need outputs on src_proc, he doesnt use it

2024-12-06 11:31 UTC, Egor1dzeN-learn commented on tasks/mpi/voroshilov_v_torus_grid/src/ops_mpi.cpp
> +  return true;
So here you dont check outputs_count on src process

2024-12-06 20:31 UTC, Egor1dzeN-learn approved these changes

2024-12-06 20:33 UTC, vitaliyvoroshilov commented on tasks/mpi/voroshilov_v_torus_grid/func_tests/main.cpp
> +  std::vector<int> output_path(expected_path.size());
Fixed

2024-12-06 20:33 UTC, vitaliyvoroshilov commented on tasks/mpi/voroshilov_v_torus_grid/func_tests/main.cpp
> +  }
Fixed

2024-12-06 20:33 UTC, vitaliyvoroshilov commented on tasks/mpi/voroshilov_v_torus_grid/src/ops_mpi.cpp
> +  return true;
Fixed

2024-12-08 11:04 UTC, aobolensk approved these changes

2024-12-08 11:04 UTC, merged