Лысов Иван. Задача 1. Вариант 20. Интегрирование – метод трапеций.
learning-process/ppc-2024-autumn pull request #41
Opened 2024-10-25 13:48 UTC by Ivan-Lysov

Последовательный вариант(SEQ)

В последовательной версии используется метод run() класса TestTaskSequential, который выполняет интегрирование на заданном отрезке [a, b] с количеством разбиений cnt_of_splits. 
Основные этапы работы:
- **Валидация и подготовка данных:** Метод validation() проверяет корректность входных данных, включая размеры массивов и допустимость значения cnt_of_splits.
- **Подготовка разбиений:** Метод pre_processing() определяет шаг разбиения h, который равен (b - a) / cnt_of_splits, и инициализирует локальные переменные.
- **Интегрирование:** Метод run() вычисляет площадь трапеций на отрезке [a, b], проходя по разбиениям и суммируя результаты.
- **Постобработка данных:** В методе post_processing() результат интегрирования сохраняется в выходной массив.

Параллельный вариант (MPI)

В параллельной версии используется метод run() класса TestMPITaskParallel, который распределяет интервал между процессами. 
Основные этапы работы:

- **Распределение данных:** Метод pre_processing() делит отрезок [a, b] между процессами, определяя локальные переменные для каждого процесса (начало отрезка local_a и количество разбиений local_cnt_of_splits). Для синхронизации используется broadcast().
- **Локальное интегрирование:** Каждый процесс в методе run() выполняет интегрирование на своем участке и накапливает локальный результат local_res.
- **Сбор результатов:** Метод reduce() суммирует локальные результаты в переменную res в процессе с рангом 0.
- **Постобработка данных:** В методе post_processing() результат интегрирования сохраняется в выходной массив, если процесс с рангом 0.

2024-10-27 08:11 UTC, Alexey2013 commented on tasks/seq/lysov_i_integration_the_trapezoid_method/src/ops_seq.cpp
> +    result += function(x);
Change the name of the function so that it is clear what it does.

2024-10-27 08:11 UTC, Alexey2013 commented on tasks/mpi/lysov_i_integration_the_trapezoid_method/src/ops_mpi.cpp
> +  if (taskData->outputs.size() != 1) {
two conditions can be combined into one

2024-10-27 09:49 UTC, allnes commented on tasks/mpi/lysov_i_integration_the_trapezoid_method/src/ops_mpi.cpp
> +  cnt_of_splits = *reinterpret_cast<int*>(taskData->inputs[2]);
please use epsilon instead count of splits

2024-10-28 13:55 UTC, Ivan-Lysov commented on tasks/seq/lysov_i_integration_the_trapezoid_method/src/ops_seq.cpp
> +    result += function(x);
fix.check please

2024-10-28 13:55 UTC, Ivan-Lysov commented on tasks/mpi/lysov_i_integration_the_trapezoid_method/src/ops_mpi.cpp
> +  if (taskData->outputs.size() != 1) {
check please i`m fix

2024-10-28 14:08 UTC, Alexey2013 approved these changes

2024-10-30 01:07 UTC, aobolensk requested changes

2024-10-31 14:38 UTC, Ivan-Lysov commented on tasks/mpi/lysov_i_integration_the_trapezoid_method/src/ops_mpi.cpp
> +  cnt_of_splits = *reinterpret_cast<int*>(taskData->inputs[2]);
fix, check please

2024-10-31 14:38 UTC, Ivan-Lysov commented on tasks/mpi/lysov_i_integration_the_trapezoid_method/func_tests/main.cpp
> +  boost::mpi::communicator world;
fix, check please

2024-10-31 14:38 UTC, Ivan-Lysov commented on tasks/mpi/lysov_i_integration_the_trapezoid_method/src/ops_mpi.cpp
> +  // boost::mpi::reduce(world, res, global_result, std::plus<double>(), 0);// ?
fix, check please

2024-10-31 16:10 UTC, allnes approved these changes

2024-10-31 16:13 UTC, aobolensk approved these changes

2024-10-31 16:13 UTC, merged