Шкуринская Елена. Задача 2. Вариант 21. Метод Гаусса-Жордана
learning-process/ppc-2024-autumn pull request #411
Opened 2024-11-30 22:30 UTC by sudo-technoir

**Последовательная версия:**
Для каждого столбца (индекса k) ищется строка с максимальным элементом в этом столбце. Строки меняются местами, если найден ряд с большим элементом. Элементы в строках нормализуются так, чтобы на главной диагонали стояли единицы. Затем для каждой строки ниже текущей вычитаются нужные множители.
**Параллельное выполнение:**
Алгоритм распределяет работу между процессами с использованием MPI.
Процесс с рангом 0 находит строку с максимальным элементом в текущем столбце (аналогично последовательному выполнению). Происходит разделение строк матрицы между процессами. После этого каждый процесс получает свою часть матрицы и выполняет преобразования для строк в своей локальной части. После этого происходит сборка результатов чтобы обновить исходную матрицу.

Для тестов генерируется матрица с [диагональным преобладанием](https://en.wikipedia.org/wiki/Diagonally_dominant_matrix), которая является невырожденной.

2024-11-30 23:58 UTC, DSolo03 requested changes

2024-11-30 23:58 UTC, DSolo03 commented on tasks/mpi/shkurinskaya_e_gauss_jordan/include/ops_mpi.hpp
> +  };
not used struct, perhaps obsolete?

2024-11-30 23:58 UTC, DSolo03 commented on tasks/mpi/shkurinskaya_e_gauss_jordan/perf_tests/main.cpp
> +}
wrap this function in your `shkurinskaya_e_gauss_jordan_mpi` namespace, or else it may interfere with others function with same name and cause exception

2024-11-30 23:58 UTC, DSolo03 commented on tasks/mpi/shkurinskaya_e_gauss_jordan/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
not used namespace inclusion

2024-12-01 00:20 UTC, sudo-technoir commented on tasks/mpi/shkurinskaya_e_gauss_jordan/perf_tests/main.cpp
> +}
fixed

2024-12-01 00:28 UTC, sudo-technoir commented on tasks/mpi/shkurinskaya_e_gauss_jordan/include/ops_mpi.hpp
> +  };
it is, fixed

2024-12-01 00:39 UTC, sudo-technoir commented on tasks/mpi/shkurinskaya_e_gauss_jordan/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
removed

2024-12-01 01:55 UTC, DSolo03 approved these changes

2024-12-01 16:29 UTC, NeeMiyuki requested changes

2024-12-01 16:29 UTC, NeeMiyuki commented on tasks/mpi/shkurinskaya_e_gauss_jordan/func_tests/main.cpp
> +  std::shared_ptr<ppc::core::TaskData> taskDataPar = std::make_shared<ppc::core::TaskData>();
Add a test for degenerate matrix (for example, 2, 4, 6, 8, 1, 2, 3, 4, 3, 6, 9, 12).

2024-12-01 22:08 UTC, sudo-technoir commented on tasks/mpi/shkurinskaya_e_gauss_jordan/func_tests/main.cpp
> +  std::shared_ptr<ppc::core::TaskData> taskDataPar = std::make_shared<ppc::core::TaskData>();
The problem is that in the case of a matrix with linear dependence, we need to compute the rank or perform a check during the process of row reduction to echelon form, or afterward. Because of this, the validation will end up containing the same code as in run and will be larger than the algorithm itself.

2024-12-02 18:39 UTC, NeeMiyuki approved these changes

2024-12-06 00:57 UTC, allnes commented on tasks/mpi/shkurinskaya_e_gauss_jordan/func_tests/main.cpp
> +  std::uniform_real_distribution<> dist(-100.0, 100.0);
please parametrize interval in test

2024-12-06 01:00 UTC, allnes commented on tasks/mpi/shkurinskaya_e_gauss_jordan/src/ops_mpi.cpp
> +bool shkurinskaya_e_gauss_jordan_mpi::TestMPITaskSequential::validation() {
please check single solution

2024-12-06 04:23 UTC, sudo-technoir commented on tasks/mpi/shkurinskaya_e_gauss_jordan/src/ops_mpi.cpp
> +  std::vector<int> displacements;
Done

2024-12-06 04:28 UTC, sudo-technoir commented on tasks/mpi/shkurinskaya_e_gauss_jordan/func_tests/main.cpp
> +  std::uniform_real_distribution<> dist(-100.0, 100.0);
Fixed if I understood you correctly

2024-12-06 04:39 UTC, sudo-technoir commented on tasks/mpi/shkurinskaya_e_gauss_jordan/src/ops_mpi.cpp
> +  std::vector<int> displacements;
Done

2024-12-06 17:02 UTC, sudo-technoir commented on tasks/mpi/shkurinskaya_e_gauss_jordan/src/ops_mpi.cpp
> +bool shkurinskaya_e_gauss_jordan_mpi::TestMPITaskSequential::validation() {
For tests I generate a matrix with diagonal dominance (this matrix has one solution), in the lesson you said that for such logic the test for singularity of solution is unnecessary

2024-12-07 07:31 UTC, aobolensk requested changes

2024-12-07 07:31 UTC, aobolensk commented on tasks/mpi/shkurinskaya_e_gauss_jordan/func_tests/main.cpp
> +
Please, add random tests

2024-12-07 07:31 UTC, aobolensk commented on tasks/mpi/shkurinskaya_e_gauss_jordan/func_tests/main.cpp
> +namespace shkurinskaya_e_gauss_jordan_mpi {
Please, extend validation code coverage

2024-12-07 08:40 UTC, sudo-technoir commented on tasks/mpi/shkurinskaya_e_gauss_jordan/func_tests/main.cpp
> +
I already use generate_invertible_matrix for tests with randomly generated matrices, also same with perf tests

2024-12-07 16:59 UTC, sudo-technoir commented on tasks/mpi/shkurinskaya_e_gauss_jordan/func_tests/main.cpp
> +namespace shkurinskaya_e_gauss_jordan_mpi {
Done, now almost 95%

2024-12-08 11:20 UTC, aobolensk approved these changes

2024-12-08 11:45 UTC, allnes approved these changes

2024-12-08 11:45 UTC, merged