Плеханов Даниил. Задача 2. Вариант 7. Реализация all_reduce.
learning-process/ppc-2024-autumn pull request #412
Opened 2024-11-30 23:17 UTC by Dxppi

### **Последовательное решение**

В последовательном подходе мы начинаем с того, что проходим по каждому столбцу матрицы и находим минимальное значение в каждом из них. Для этого мы инициализируем переменную, которая будет хранить текущее минимальное значение, и сравниваем её с каждым элементом столбца. Как только мы определили минимум для столбца, мы переходим к следующему этапу — подсчету количества элементов, которые больше найденного минимума. Мы снова проходим по этому столбцу, увеличивая счетчик каждый раз, когда находим элемент, больший, чем минимум. В итоге мы получаем массив минимумов и массивы с количеством элементов, которые больше этих минимумов для каждого столбца.

**### MPI решение**

В параллельном решении с использованием MPI мы разбиваем матрицу на части, распределяя её между несколькими потоками (процессами). Каждый поток получает определенное количество столбцов для обработки. Затем каждый процесс ищет минимумы в своих локальных столбцах. После того, как все процессы завершили поиск минимумов, мы используем операцию all_reduce, чтобы собрать и сравнить результаты от всех потоков. Эта операция позволяет получить глобальные минимумы, которые затем передаются всем процессам.

Следующим шагом каждый поток снова проходит по своим столбцам, но теперь он сравнивает элементы с глобальными минимумами, чтобы подсчитать количество значений, которые больше этих минимумов.

2024-12-01 10:28 UTC, MikasaAkc commented
Please add a test with zero columns and matrices to 2 func tests.

2024-12-01 23:05 UTC, Dxppi commented
> Please add a test with zero columns and matrices to 2 func tests.

added tests with 0x0 matrices, works well

2024-12-02 13:00 UTC, MikasaAkc approved these changes

2024-12-06 01:01 UTC, allnes commented on tasks/mpi/plekhanov_d_allreduce_boost/func_tests/main.cpp
> +  int rows = 0;
please add 1x1

2024-12-06 01:02 UTC, allnes commented on tasks/mpi/plekhanov_d_allreduce_boost/src/ops_mpi.cpp
> +      value = gen() % 1000 + 1;
please use negative values and parametrize it in tests

2024-12-06 01:02 UTC, allnes commented on tasks/mpi/plekhanov_d_allreduce_boost/src/ops_mpi.cpp
> +  broadcast(world, rowCount, 0);
please broadcast deltas instead rows and cols

2024-12-06 01:03 UTC, allnes commented on tasks/mpi/plekhanov_d_allreduce_boost/src/ops_mpi.cpp
> +  broadcast(world, inputData_.data(), columnCount * rowCount, 0);
why do you broadcast all data?

2024-12-06 14:29 UTC, Dxppi commented on tasks/mpi/plekhanov_d_allreduce_boost/func_tests/main.cpp
> +  int rows = 0;
fixed

2024-12-06 14:29 UTC, Dxppi commented on tasks/mpi/plekhanov_d_allreduce_boost/src/ops_mpi.cpp
> +      value = gen() % 1000 + 1;
fixed

2024-12-07 13:31 UTC, aobolensk requested changes

2024-12-07 13:31 UTC, aobolensk commented on tasks/mpi/plekhanov_d_allreduce_boost/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int size);
Please, move to test module

2024-12-08 11:47 UTC, allnes commented on tasks/mpi/plekhanov_d_allreduce_boost/src/ops_mpi.cpp
> +      value = gen() % 1000 + 1;
I didn't see parametrization

2024-12-08 11:47 UTC, allnes commented on tasks/mpi/plekhanov_d_allreduce_boost/src/ops_mpi.cpp
> +    } while (value <= 0);
please remove while

2024-12-08 17:33 UTC, Dxppi commented on tasks/mpi/plekhanov_d_allreduce_boost/src/ops_mpi.cpp
> +      value = gen() % 1000 + 1;
Fixed, added negative sizes in Tests

2024-12-08 17:33 UTC, Dxppi commented on tasks/mpi/plekhanov_d_allreduce_boost/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int size);
fixed

2024-12-08 17:33 UTC, Dxppi commented on tasks/mpi/plekhanov_d_allreduce_boost/src/ops_mpi.cpp
> +    } while (value <= 0);
fixed

2024-12-08 17:38 UTC, Dxppi commented on tasks/mpi/plekhanov_d_allreduce_boost/src/ops_mpi.cpp
> +  broadcast(world, inputData_.data(), columnCount * rowCount, 0);
More memory is allocated, but each process works with its own columns, I realise that on large amounts of data, more memory may be consumed

2024-12-08 18:40 UTC, allnes commented on tasks/mpi/plekhanov_d_allreduce_boost/src/ops_mpi.cpp
> +  broadcast(world, inputData_.data(), columnCount * rowCount, 0);
please correct it

2024-12-09 01:50 UTC, Dxppi commented
I accidentally broke my branch,dunno how to fix it, so I'll create a new PR

2024-12-09 02:08 UTC, Dxppi commented on tasks/mpi/plekhanov_d_allreduce_boost/src/ops_mpi.cpp
> +  broadcast(world, inputData_.data(), columnCount * rowCount, 0);
fixed

2024-12-09 02:08 UTC, Dxppi commented on tasks/mpi/plekhanov_d_allreduce_boost/src/ops_mpi.cpp
> +  broadcast(world, rowCount, 0);
fixed

2024-12-09 17:54 UTC, Tanya-Yasakova commented on tasks/mpi/plekhanov_d_allreduce_boost/include/ops_mpi.hpp
> +#include <boost/mpi/collectives.hpp>
delete unnecessary includes

2024-12-09 17:54 UTC, Tanya-Yasakova commented on tasks/mpi/plekhanov_d_allreduce_mine/include/ops_mpi.hpp
> +#include <boost/mpi/collectives.hpp>
delete unnecessary includes

2024-12-09 18:34 UTC, Dxppi commented on tasks/mpi/plekhanov_d_allreduce_mine/include/ops_mpi.hpp
> +#include <boost/mpi/collectives.hpp>
fixed

2024-12-09 20:41 UTC, aobolensk requested changes

2024-12-09 20:41 UTC, aobolensk commented on tasks/mpi/plekhanov_d_allreduce_mine/func_tests/main.cpp
> +std::vector<int> getRandomMatrix1(int size) {
Please, either make it static or wrap with namespace

2024-12-09 21:13 UTC, Dxppi commented on tasks/mpi/plekhanov_d_allreduce_mine/func_tests/main.cpp
> +std::vector<int> getRandomMatrix1(int size) {
Fixed, made it static

2024-12-10 19:20 UTC, aobolensk approved these changes

2024-12-13 16:36 UTC, allnes approved these changes

2024-12-13 16:36 UTC, merged