Гусейнов Эмил. Задача 2. Вариант 8. Обобщенная передача от одного всем (scatter)
learning-process/ppc-2024-autumn pull request #414
Opened 2024-12-01 07:16 UTC by emilien-gus

Решаемая задача:
Нахождение суммы элементов вектора. Данные по процессам рассылаем с помощью функции scatter. Если какие-то данные не пересылаются с помощью scatter(то есть размер входных данных не делится нацело на число процессов), то обрабатываем их в нулевом процессе.

Реализация scatter:
Используя дерево процессов пересылаем данные от предков к потомкам, при этом каждый потомок получает столько данных сколько нужно ему, другим процессам на его уровне и последующим процессам. В корне копируем данные и отсылаем данные существующим потомкам. Потомки принимают данные, копируют n своих элементов в буфер, а потом также отсылают данные.

2024-12-01 07:53 UTC, nCUXe commented on tasks/mpi/guseynov_e_scatter/func_tests/main.cpp
> +
Add some tests with empty arrays

2024-12-01 12:12 UTC, emilien-gus commented on tasks/mpi/guseynov_e_scatter/func_tests/main.cpp
> +
done

2024-12-01 16:46 UTC, StroganovM commented on tasks/mpi/guseynov_e_scatter/src/ops_mpi.cpp
> +  }
You need to use std::copy

2024-12-02 10:31 UTC, StroganovM approved these changes

2024-12-06 01:06 UTC, allnes commented on tasks/mpi/guseynov_e_scatter/src/ops_mpi.cpp
> +  my_scatter(world, input_, local_input_.data(), delta, 0);
please add same task in different directory for boost scatter, we need to check both versions of performance

2024-12-06 01:07 UTC, allnes commented on tasks/mpi/guseynov_e_scatter/src/ops_mpi.cpp
> +    vec[i] = gen() % 100;
please add negative values, and paramteize interval in tests

2024-12-06 10:35 UTC, emilien-gus commented on tasks/mpi/guseynov_e_scatter/src/ops_mpi.cpp
> +    vec[i] = gen() % 100;
fixed

2024-12-06 10:35 UTC, emilien-gus commented on tasks/mpi/guseynov_e_scatter/src/ops_mpi.cpp
> +  my_scatter(world, input_, local_input_.data(), delta, 0);
fixed

2024-12-07 07:36 UTC, aobolensk requested changes

2024-12-07 07:36 UTC, aobolensk commented on tasks/mpi/guseynov_e_boost_scatter/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz, int minValue, int maxValue);
Please, move to the test module

2024-12-07 07:36 UTC, aobolensk commented on tasks/mpi/guseynov_e_boost_scatter/func_tests/main.cpp
> +
Please, add some fixed tests

2024-12-08 08:24 UTC, emilien-gus commented on tasks/mpi/guseynov_e_boost_scatter/func_tests/main.cpp
> +
fixed

2024-12-08 08:24 UTC, emilien-gus commented on tasks/mpi/guseynov_e_boost_scatter/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz, int minValue, int maxValue);
fixed

2024-12-08 11:37 UTC, aobolensk approved these changes

2024-12-08 11:48 UTC, allnes approved these changes

2024-12-08 11:48 UTC, merged