FIX Баранов Алексей. Задача 2. Вариант 11. Топология сети кольцо
learning-process/ppc-2024-autumn pull request #418
Opened 2024-12-01 14:50 UTC by Torcna

### ПРИЧИНА
Я уже нахожусь в мастере, но когда тестировал 3 задачу обнаружил ошибку в perf tests для этой задачи.

1. Изменен способ создания taskData (теперь он правильный).
2. Сделаны небольшие косметические изменения.
3. Основные правки в perf test.

2024-12-06 00:56 UTC, allnes commented
please resolve conflicts

2024-12-06 01:08 UTC, allnes commented on tasks/mpi/baranov_a_ring_topology/src/source_topology.cpp
> +template class baranov_a_ring_topology_mpi::ring_topology<int>;
please check char

2024-12-06 15:42 UTC, Torcna commented on tasks/mpi/baranov_a_ring_topology/src/source_topology.cpp
> +template class baranov_a_ring_topology_mpi::ring_topology<int>;
@allnes, I added explicit instantiation and resolved conflict, as you requested. Please review these changes!

2024-12-08 11:50 UTC, aobolensk approved these changes
This is done in correct way. Please collect students' review for this patch as well

2024-12-08 11:50 UTC, allnes commented on tasks/mpi/baranov_a_ring_topology/perf_tests/main_topology.cpp
> -  std::vector<int> global_vec(count_size_vector);
please not change old files, create a task according to the template

2024-12-08 11:51 UTC, allnes approved these changes

2024-12-09 12:07 UTC, ascannel requested changes

2024-12-09 12:07 UTC, ascannel commented on tasks/mpi/baranov_a_ring_topology/perf_tests/main_topology.cpp
> +    std::generate(arr.begin(), arr.end(), [&dist, &reng] { return dist(reng); });
i suggest you to create data for perf_tests outside of test code, creating one vector for both tests

2024-12-09 21:08 UTC, suvorovDm-1 approved these changes

2024-12-10 05:28 UTC, Torcna commented on tasks/mpi/baranov_a_ring_topology/perf_tests/main_topology.cpp
> +    std::generate(arr.begin(), arr.end(), [&dist, &reng] { return dist(reng); });
@ascannel, do these changes look good to you?

2024-12-10 08:29 UTC, ascannel commented on tasks/mpi/baranov_a_ring_topology/perf_tests/main_topology.cpp
> +    std::generate(arr.begin(), arr.end(), [&dist, &reng] { return dist(reng); });
acceptable

2024-12-10 08:29 UTC, ascannel approved these changes

2024-12-10 14:36 UTC, Torcna commented
@aobolensk, I suppose we`re good now.
Reviews are collected .

2024-12-10 19:21 UTC, merged