Баранов Алексей. Задача 3. Вариант 15. Быстрая сортировка с четно-нечетным слиянием Бэтчера.
learning-process/ppc-2024-autumn pull request #419
Opened 2024-12-01 15:21 UTC by Torcna

### 1 MPI
В этой задаче реализована Быстрая сортировка с четно-нечетным слиянием Бэтчера. Суть алгоритма заключается в том, что на каждый процесс рассылается часть исходного вектора, эти части сортируются с помощью быстрой сортировки, и после этого происходит слияние.

- Слияние выполняется по двум разным сценариям, если наш счетчик - четный, то все пары (0,1)... (n-1,n)обмениваются между собой данными и оставляют у себя нужную им часть. где n - это world.size()-1.
- На нечетном тике пары (1,2)...(n-2,n-1) меняются данными, где n - это world.size()-1.

Пример:
Исходный массив {9,8,7,6}. 4 Процесса используются.
n(размер вектора) =4, p= n/world.size().

1. На четной итерации процессы 0 и 1,а так же 2 и 3 обмениваются данными. процесс с меньшим rank оставляет у себя p наименьших элементов, а процесс со старшим рангом забирает p наибольших чисел.

- Таким образом после первой итерации массивы выглядят вот так
- {8}{9}{6}{7}

2. На нечетной итерации процессы 1 и 2 обмениваются данными. Схема точно такая же

- После второй итерации массивы выглядят вот так
- {8}{6}{9}{7}

3. Опять четная итерация. 0 и 1. 2 и 3

- После третьей итерации массивы выглядят вот так
- {6}{8}{7}{9}

4. И нечетная заключительная итерация

- После четвертой итерации массивы выглядят вот так
- {6}{7}{8}{9}

### 2 Итог
Благодаря такой организации работы получается так что сливают два отсортированных массива 2 процесса, а не 1 как в simple merge

### 3 Какие проверки выполняются
В тестах проверяются четные и нечетные размеры векторов. На различных типах данных тестируется различное количество процессов.

2024-12-12 08:23 UTC, ascannel requested changes

2024-12-12 08:23 UTC, ascannel commented on tasks/mpi/baranov_a_qsort_odd_even_mergesort/func_tests/main_func_tests_qsort_odd_even_merge.cpp
> +}
don't you think that you should compare corectness with sequential version?

2024-12-12 08:23 UTC, ascannel commented on tasks/mpi/baranov_a_qsort_odd_even_mergesort/src/source_b_a_qsort_odd_even.cpp
> +    vec_size_ = n;
maybe you could do just vec_size_ =  taskData->inputs_count[0];

2024-12-12 08:23 UTC, ascannel commented on tasks/mpi/baranov_a_qsort_odd_even_mergesort/src/source_b_a_qsort_odd_even.cpp
> +    if (taskData->outputs_count[0] == 1 && taskData->inputs_count.size() == 1 && taskData->inputs_count[0] >= 0) {
why do you need to sort an array of one number?

2024-12-12 08:23 UTC, ascannel commented on tasks/seq/baranov_a_odd_even_mergesort/perf_tests/main_perf_seq.cpp
> +  taskDataSeq->outputs_count.emplace_back(out.size());
i suggest you to move this code outside of tests, in its own function, and create the same data for both tests outside of test code

2024-12-12 08:23 UTC, ascannel commented on tasks/seq/baranov_a_odd_even_mergesort/src/source_seq_odd_even.cpp
> +  return (taskData->outputs_count[0] != 0);
i suggest you to expand validation

2024-12-12 09:20 UTC, Torcna commented on tasks/mpi/baranov_a_qsort_odd_even_mergesort/func_tests/main_func_tests_qsort_odd_even_merge.cpp
> +}
During the meeting on 5th of December Alexander and Arseniy mentioned, that it is legal to compare results of your algorithm to functions from std for both seq and mpi implementations in order to avoid situations, where both of them finish with wrong results.
Am I right @aobolensk

2024-12-12 09:21 UTC, Torcna commented on tasks/mpi/baranov_a_qsort_odd_even_mergesort/src/source_b_a_qsort_odd_even.cpp
> +    vec_size_ = n;
Sure. You re right

2024-12-12 09:22 UTC, Torcna commented on tasks/mpi/baranov_a_qsort_odd_even_mergesort/src/source_b_a_qsort_odd_even.cpp
> +    if (taskData->outputs_count[0] == 1 && taskData->inputs_count.size() == 1 && taskData->inputs_count[0] >= 0) {
This have reason for sure

2024-12-13 09:26 UTC, Torcna commented
@ascannel, please review these changes. I did all u wanted me to do, except suggestion where you asked for change of checking method. I guess we can handle this situation only with help of Alexander and Arseniy. so...

2024-12-13 10:35 UTC, ascannel approved these changes

2024-12-15 20:17 UTC, Alexey2013 commented on tasks/mpi/baranov_a_qsort_odd_even_mergesort/func_tests/main_func_tests_qsort_odd_even_merge.cpp
> +}
wrap the function in a namespace

2024-12-15 20:17 UTC, Alexey2013 commented on tasks/mpi/baranov_a_qsort_odd_even_mergesort/src/source_b_a_qsort_odd_even.cpp
> +    world.barrier();
This function is not needed

2024-12-18 18:03 UTC, Alexey2013 approved these changes

2024-12-18 20:07 UTC, Torcna commented on tasks/mpi/baranov_a_qsort_odd_even_mergesort/src/source_b_a_qsort_odd_even.cpp
> +    world.barrier();
You are absolutely right. Since I send each message on a specific iteration with a certain tag, there is no need for an additional 'level' of synchronization.

2024-12-18 20:08 UTC, Torcna commented on tasks/mpi/baranov_a_qsort_odd_even_mergesort/func_tests/main_func_tests_qsort_odd_even_merge.cpp
> +}
Check this out. I finally did it right!

2024-12-19 09:34 UTC, aobolensk approved these changes

2024-12-20 14:39 UTC, allnes commented on tasks/mpi/baranov_a_qsort_odd_even_mergesort/src/source_b_a_qsort_odd_even.cpp
> +    memcpy(ptr_d, ptr_r, sizeof(iotype) * vec_size_);
why do you use memcpy instead std::copy?

2024-12-20 15:13 UTC, Torcna commented on tasks/mpi/baranov_a_qsort_odd_even_mergesort/src/source_b_a_qsort_odd_even.cpp
> +    memcpy(ptr_d, ptr_r, sizeof(iotype) * vec_size_);
Thank you for your question! Actually, std::copy internally uses memcpy when copying data from one contiguous block to another, as it is optimized for this case. Since a std::vector guarantees contiguous memory storage, std::copy will effectively call memcpy under the hood to perform the operation. So, using memcpy directly here can be seen as a more explicit way to achieve the same result.
@allnes, I hope this explanation suits you!

2024-12-22 22:08 UTC, allnes approved these changes

2024-12-22 22:08 UTC, merged