Матюнина Александра. Задача 2. Вариант 3. Задача: Обедающие философы
learning-process/ppc-2024-autumn pull request #420
Opened 2024-12-01 15:24 UTC by erty1909

Существует несколько способов решения проблемы обедающих философов, которая заключается в распределении вилок между, каждым, кто хочет поесть. В какой то момент у каждого может остаться по одной вилке, и в этом случае появляется дедлок так как отобрать у другого человека философы не могут. Так все философы окажутся в ожидании второй вилки. Здесь приведено одно из самых простых решений этой задачи, Начальное распределение правой или левой вилок зависит от чётности и нечётности номера философа. В целом этот алгоритм может работать вечно без появления дедлока, но в программе мы ограничим на входе сколько каждый из философов захочет поесть. Таким образом мы ещё и убедимся в доступности поесть каждому из философов.

2024-12-06 01:09 UTC, allnes commented on tasks/mpi/matyunina_a_dining_philosophers/func_tests/main.cpp
> +    return;
please use GTEST_SKIP

2024-12-06 01:09 UTC, allnes commented on tasks/mpi/matyunina_a_dining_philosophers/func_tests/main.cpp
> +TEST(matyunina_a_dining_philosophers_mpi, they_eat_once) {
please add more tests

2024-12-06 01:10 UTC, allnes commented on tasks/mpi/matyunina_a_dining_philosophers/perf_tests/main.cpp
> +    return;
GTEST_SKIP

2024-12-06 01:10 UTC, allnes commented on tasks/mpi/matyunina_a_dining_philosophers/perf_tests/main.cpp
> +TEST(matyunina_a_dining_philosophers_mpi, test_1) {
please add 2 tests - run_pipeline and run_task

2024-12-07 09:25 UTC, LizochkaSpring commented on tasks/mpi/matyunina_a_dining_philosophers/src/ops_mpi.cpp
> +#include <vector>
Delete unnecessary include

2024-12-07 09:25 UTC, LizochkaSpring commented on tasks/mpi/matyunina_a_dining_philosophers/src/ops_mpi.cpp
> +      const double e = 3;
Please give me clearer names for the variables.

2024-12-08 13:33 UTC, allnes commented on tasks/mpi/matyunina_a_dining_philosophers/src/ops_mpi.cpp
> +                world.send(rank, 1, &answer, 1);
please non-blocked operations, isend, irecv ...

2024-12-14 16:20 UTC, DZaytsev4 commented on tasks/mpi/matyunina_a_dining_philosophers/src/ops_mpi.cpp
> +    while (c < nom) {
Edit more name variables

2024-12-14 20:26 UTC, erty1909 commented on tasks/mpi/matyunina_a_dining_philosophers/func_tests/main.cpp
> +    return;
fixed

2024-12-14 20:26 UTC, erty1909 commented on tasks/mpi/matyunina_a_dining_philosophers/func_tests/main.cpp
> +    return;
fixed

2024-12-14 20:26 UTC, erty1909 commented on tasks/mpi/matyunina_a_dining_philosophers/func_tests/main.cpp
> +TEST(matyunina_a_dining_philosophers_mpi, they_eat_once) {
fixed

2024-12-14 20:27 UTC, erty1909 commented on tasks/mpi/matyunina_a_dining_philosophers/perf_tests/main.cpp
> +    return;
fixed

2024-12-14 20:27 UTC, erty1909 commented on tasks/mpi/matyunina_a_dining_philosophers/perf_tests/main.cpp
> +TEST(matyunina_a_dining_philosophers_mpi, test_1) {
fixed

2024-12-14 20:27 UTC, erty1909 commented on tasks/mpi/matyunina_a_dining_philosophers/src/ops_mpi.cpp
> +#include <vector>
fixed

2024-12-14 20:27 UTC, erty1909 commented on tasks/mpi/matyunina_a_dining_philosophers/src/ops_mpi.cpp
> +      const double e = 3;
fixed

2024-12-14 20:27 UTC, erty1909 commented on tasks/mpi/matyunina_a_dining_philosophers/src/ops_mpi.cpp
> +                world.send(rank, 1, &answer, 1);
fixed

2024-12-14 20:27 UTC, erty1909 commented on tasks/mpi/matyunina_a_dining_philosophers/src/ops_mpi.cpp
> +    while (c < nom) {
fixed

2024-12-14 20:28 UTC, DZaytsev4 approved these changes

2024-12-14 20:31 UTC, LizochkaSpring approved these changes

2024-12-15 19:18 UTC, allnes approved these changes

2024-12-15 19:23 UTC, aobolensk requested changes

2024-12-15 19:23 UTC, aobolensk commented on tasks/mpi/matyunina_a_dining_philosophers/src/ops_mpi.cpp
> +    world.recv(0, 5, &a, 1);
Please, move data transfer to ::run() function

2024-12-15 19:23 UTC, aobolensk commented on tasks/mpi/matyunina_a_dining_philosophers/perf_tests/main.cpp
> +  }
1. use GTEST_SKIP 
2. Why it does not work on 2 processes?

2024-12-15 21:03 UTC, erty1909 commented on tasks/mpi/matyunina_a_dining_philosophers/perf_tests/main.cpp
> +  }
В данной реализации я предпочла чтобы в первом процессе осуществлялась раздача вилок. Таким образом он характеризует некоторый стол от которого я получаю информацию могу ли я взять вилку. А если запустить на двух процессах задача не будет иметь смысла так как вилка тоже будет одна как и человек, а он не может есть одной вилкой. Таким образом уже на трёх процессах код начинает полностью функционировать. Выделение одного процесса под стол считаю не большой проблемой ведь основная проблема дедлока решается и тут явно видно каким именно образом. Поэтому данной код отражает задачу.

2024-12-15 23:14 UTC, erty1909 commented on tasks/mpi/matyunina_a_dining_philosophers/src/ops_mpi.cpp
> +    world.recv(0, 5, &a, 1);
fixed

2024-12-15 23:14 UTC, erty1909 commented on tasks/mpi/matyunina_a_dining_philosophers/perf_tests/main.cpp
> +  }
fixed

2024-12-16 03:57 UTC, aobolensk commented on tasks/mpi/matyunina_a_dining_philosophers/perf_tests/main.cpp
> +  }
The answer is accepted

2024-12-16 03:57 UTC, aobolensk approved these changes

2024-12-16 03:58 UTC, merged