Сорокин Андрей. Задача 3. Вариант 24. Построение выпуклой оболочки – проход Грэхема
learning-process/ppc-2024-autumn pull request #421
Opened 2024-12-01 18:19 UTC by AndreySorokin7

На вход подаётся одномерный массив, который содержит координаты точек. Используя проход Грэхема (не знаю стоит ли прописывать суть алгоритма, так как он упоминался на лекции и в самом задании есть ссылка на видеоролик) мы получаем точки которые образуют выпуклую оболочку. Таким образом мы получили часть из имеющихся изначально точек, а все остальные находятся внутри фигуры которую можно изобразить из точек которые мы выделили, и они не попадают в ответ. Параллельная реализация заключается в разбиении общего числа точек на части. Так в каждом отдельном процессе получится ответом свой массив, а позже совместим их в нулевом процессе и запустим тот же алгоритм ещё раз, так и получится конечный ответ.

2024-12-09 17:28 UTC, Semyon1104 commented on tasks/mpi/sorokin_a_graham_algorithm/src/ops_mpi.cpp
> +bool sorokin_a_graham_algorithm_mpi::TestMPITaskSequential::validation() {
validation is empty

2024-12-09 17:28 UTC, Semyon1104 commented on tasks/mpi/sorokin_a_graham_algorithm/func_tests/main.cpp
> +TEST(sorokin_a_graham_algorithm_MPI, Test_1) {
please fix name of test

2024-12-09 17:28 UTC, Semyon1104 commented on tasks/mpi/sorokin_a_graham_algorithm/func_tests/main.cpp
> +      ASSERT_EQ(outres[i], out[i]);
too excessive

2024-12-09 18:06 UTC, AndreySorokin7 commented on tasks/mpi/sorokin_a_graham_algorithm/func_tests/main.cpp
> +      ASSERT_EQ(outres[i], out[i]);
First, it checks whether the values are the same with and without mpi, and then if they are the same, the answer is compared with the correct one of the vectors, so in this case both checks are quite important

2024-12-09 18:08 UTC, ermolaevv commented on tasks/seq/sorokin_a_graham_algorithm/src/ops_seq.cpp
> +  input_ = std::vector<int>(taskData->inputs_count[0]);
please use resize

2024-12-09 18:09 UTC, ermolaevv commented on tasks/seq/sorokin_a_graham_algorithm/src/ops_seq.cpp
> +
Do you need to validate anything?

2024-12-09 18:10 UTC, ermolaevv commented on tasks/seq/sorokin_a_graham_algorithm/src/ops_seq.cpp
> +  stack.push_back(indices[1]);
Please use emplace_back. Also consider changing in other places.

2024-12-09 18:12 UTC, ermolaevv commented on tasks/seq/sorokin_a_graham_algorithm/src/ops_seq.cpp
> +
Do you need it? Also correct in other places

2024-12-09 19:52 UTC, AndreySorokin7 commented on tasks/seq/sorokin_a_graham_algorithm/src/ops_seq.cpp
> +
fixed

2024-12-09 19:52 UTC, AndreySorokin7 commented on tasks/seq/sorokin_a_graham_algorithm/src/ops_seq.cpp
> +
fixed

2024-12-09 19:52 UTC, AndreySorokin7 commented on tasks/seq/sorokin_a_graham_algorithm/src/ops_seq.cpp
> +  input_ = std::vector<int>(taskData->inputs_count[0]);
fixed

2024-12-09 19:53 UTC, AndreySorokin7 commented on tasks/mpi/sorokin_a_graham_algorithm/func_tests/main.cpp
> +TEST(sorokin_a_graham_algorithm_MPI, Test_1) {
fixed

2024-12-09 19:55 UTC, Semyon1104 approved these changes

2024-12-09 20:13 UTC, ermolaevv approved these changes

2024-12-15 12:55 UTC, aobolensk requested changes

2024-12-15 12:55 UTC, aobolensk commented on tasks/mpi/sorokin_a_graham_algorithm/func_tests/main.cpp
> +std::vector<int> getrndvec(int n, int max, int min) {
Please, either make it static or wrap with namespace

2024-12-15 14:18 UTC, AndreySorokin7 commented on tasks/mpi/sorokin_a_graham_algorithm/func_tests/main.cpp
> +std::vector<int> getrndvec(int n, int max, int min) {
fixed

2024-12-16 03:56 UTC, aobolensk approved these changes

2024-12-20 14:41 UTC, allnes commented on tasks/seq/sorokin_a_graham_algorithm/perf_tests/main.cpp
> +  std::vector<int> in = sorokin_a_graham_algorithm_seq::getrndvec(2000000, -100, 100);
how do you handle situation which depends on small value of angle?

2024-12-20 17:33 UTC, AndreySorokin7 commented on tasks/seq/sorokin_a_graham_algorithm/perf_tests/main.cpp
> +  std::vector<int> in = sorokin_a_graham_algorithm_seq::getrndvec(2000000, -100, 100);
corrected for the herenation of points on and inside the circle

2024-12-22 22:09 UTC, allnes approved these changes

2024-12-22 22:09 UTC, merged