Тышкевич Артём. Задача 2. Вариант 14. Топология сети передачи данных "Гиперкуб"
learning-process/ppc-2024-autumn pull request #423
Opened 2024-12-01 19:39 UTC by artich02

Реализация параллельного обмена данных в гиперкубе с использованием MPI.

- **Проверка корректности:** Валидация размерности гиперкуба и входных данных.
- **Подготовка:** Инициализация структуры гиперкуба, распределение данных между узлами (отправитель/получатель).
- **Передача сообщений:** Данные пересылаются по кратчайшему пути в гиперкубе от отправителя к целевому узлу. Промежуточные узлы пересылают данные далее, пока они не достигнут цели.
- **Завершение:** Рассылка сигнала завершения всем узлам для завершения работы.
- **Постобработка:** Передача результатов и сохранение отправленного сообщения для анализа.

Ключевая логика: гарантированная доставка данных по оптимальному пути в гиперкубе с учетом асинхронного обмена и завершения процессов.

2024-12-01 21:11 UTC, korablev-vm requested changes

2024-12-01 21:11 UTC, korablev-vm commented on tasks/mpi/tyshkevich_a_hypercube/include/ops_mpi.hpp
> +};
I think creating a separate class is still unnecessary here. The functionality can be transferred all into one function. Otherwise, everything looks very good.

2024-12-01 21:15 UTC, artich02 commented on tasks/mpi/tyshkevich_a_hypercube/include/ops_mpi.hpp
> +};
Thank you, I was just doing the review, I'll fix everything now!!!

2024-12-01 21:15 UTC, artich02 commented on tasks/mpi/tyshkevich_a_hypercube/src/ops_mpi.cpp
> +  return val_sender_id < world_size && val_target_id >= 0;
Yes, you are right, I missed that.

2024-12-01 21:15 UTC, artich02 commented on tasks/mpi/tyshkevich_a_hypercube/func_tests/main.cpp
Good idea, thanks!

2024-12-01 23:20 UTC, artich02 commented
### Проблема в чужом коде
@allnes, @aobolensk, моя джоба упала не по моей вине.
Проблемный репозиторий: https://github.com/learning-process/ppc-2024-autumn/pull/296
![image](https://github.com/user-attachments/assets/b4cbc90c-e317-4702-8afa-ed395dcefa12)

2024-12-01 23:46 UTC, venn2713 approved these changes

2024-12-06 01:13 UTC, allnes commented on tasks/mpi/tyshkevich_a_hypercube/func_tests/main.cpp
> +    EXPECT_EQ(output_check, output_result);
please check path of transfer data

2024-12-06 14:00 UTC, kavtorevd commented on tasks/mpi/tyshkevich_a_hypercube/func_tests/main.cpp
> +      std::cout << "Low count of processes\n";
Please use in same situations GTEST_SKIP()

2024-12-06 14:09 UTC, artich02 commented on tasks/mpi/tyshkevich_a_hypercube/func_tests/main.cpp
> +    EXPECT_EQ(output_check, output_result);
I added the data_route_transfer vector, which I transfer with the data, and in each node I add the identifier of this node, then in post-processing I calculate what the shortest path should be and compare, returning a bool variable.

2024-12-06 14:20 UTC, kavtorevd approved these changes

2024-12-07 07:42 UTC, aobolensk requested changes

2024-12-07 07:42 UTC, aobolensk commented on tasks/mpi/tyshkevich_a_hypercube/perf_tests/main.cpp
Why there are no perf tests?

2024-12-07 18:16 UTC, artich02 commented on tasks/mpi/tyshkevich_a_hypercube/perf_tests/main.cpp
There were problems, so I temporarily deleted them locally, and then forgot to return them, now everything is in place, thanks for paying attention to this!

2024-12-07 19:04 UTC, artich02 commented
## Лог падает из-за другого  человека #328
Ссылка на лог: [ссылка](https://github.com/learning-process/ppc-2024-autumn/actions/runs/12215019047/job/34076480202?pr=423)

![image](https://github.com/user-attachments/assets/2ae07a2d-5a5c-4236-8ab8-6f40298f54a7)

@aobolensk @allnes

2024-12-08 10:01 UTC, aobolensk approved these changes

2024-12-08 11:52 UTC, allnes approved these changes

2024-12-08 11:53 UTC, merged