Дормидонтов Егор.Задача 2.Вариант 11.Топология кольцо
learning-process/ppc-2024-autumn pull request #424
Opened 2024-12-02 18:34 UTC by EgorDormidontov

Задача 11 Топология кольцо

Задача заключается в том, чтобы пройти по всем потокам и передать в массив номера посещённых рангов.
То есть мы начинаем в 0 ранге и кладём 0 ранг, идём в 1 , кладём 1 и так далее.В конце мы возвращаемся в 0 процесс и складываем 0.

2024-12-05 08:13 UTC, Konstantin-Grudzin requested changes

2024-12-05 08:13 UTC, Konstantin-Grudzin commented on tasks/mpi/dormidontov_e_circle_topology/func_tests/dect_main.cpp
> +  mas = dormidontov_e_circle_topology_mpi::GenVector(size);
You intinalize one array two times, it's not very efficient

2024-12-05 08:13 UTC, Konstantin-Grudzin commented on tasks/mpi/dormidontov_e_circle_topology/func_tests/dect_main.cpp
> +  std::vector<int> mans = dormidontov_e_circle_topology_mpi::GenMarksAns(world.size());
Use name that describe data structure (that it contains or for what you use it etc.)

2024-12-05 08:13 UTC, Konstantin-Grudzin commented on tasks/mpi/dormidontov_e_circle_topology/src/dect_ops_mpi.cpp
> +      marks_.push_back(world.rank());
it's hard to read, add some line to seperate two blocks

2024-12-06 01:14 UTC, allnes commented on tasks/mpi/dormidontov_e_circle_topology/func_tests/dect_main.cpp
> +    temp[i] = (rand() % 2001) - 1000;
please parametrize this interval in tests

2024-12-06 01:15 UTC, allnes commented on tasks/mpi/dormidontov_e_circle_topology/func_tests/dect_main.cpp
> +  int size = 1000;
please check 2^n, 3^n, prive values

2024-12-07 17:49 UTC, EgorDormidontov commented on tasks/mpi/dormidontov_e_circle_topology/func_tests/dect_main.cpp
> +  int size = 1000;
Can u elaborate on it? I don`t quite get what you mean when you say 2^n,3^n and prive.

2024-12-07 18:07 UTC, NikitaKoshkin requested changes

2024-12-07 18:07 UTC, NikitaKoshkin commented on tasks/mpi/dormidontov_e_circle_topology/src/dect_ops_mpi.cpp
> +      reinterpret_cast<int*>(taskData->outputs[0])[i] = output_[i];
Use reinterpret_cast only 1 time

2024-12-07 18:07 UTC, NikitaKoshkin commented on tasks/mpi/dormidontov_e_circle_topology/src/dect_ops_mpi.cpp
> +      reinterpret_cast<int*>(taskData->outputs[1])[i] = marks_[i];
Use reinterpret_cast only 1 time

2024-12-07 18:07 UTC, NikitaKoshkin commented on tasks/mpi/dormidontov_e_circle_topology/src/dect_ops_mpi.cpp
> +              input_.begin());
I think this can be transferred to the pre_processing()

2024-12-07 20:36 UTC, Konstantin-Grudzin approved these changes

2024-12-08 11:54 UTC, allnes approved these changes

2024-12-08 14:07 UTC, NikitaKoshkin approved these changes

2024-12-08 14:39 UTC, aobolensk approved these changes

2024-12-08 14:39 UTC, merged