Аникин Максим. Задача 2. Вариант 27. Повышение контраста.
learning-process/ppc-2024-autumn pull request #426
Opened 2024-12-02 21:51 UTC by decl1

Секвентальный алгоритм:
1. Считаем среднюю яркость изображения
2. Яркость одного пикселя вычисляется по формуле (valueR * 0.299 + valueG * 0.587 + valueB * 0.114);
3. Создаем массив данных содержащее 256 значений, эти значения значат то как определенное значение канала меняется при повышении контраста (newrgb[256])
 for (int i = 0; i < 256; i++)
{
	int delta = (int)i - lAB;
	int temp  = (int)(lAB + k *delta);

	if (temp < 0)
		temp = 0;

	if (temp >= 255)
		temp = 255;
	newrgb[i] = (unsigned char)temp;
}
5. Используя вычеслиненные значения конвертируем исходные значения в результат.

MPI алгоритм:
Разделяем исходный массив на кол-во процессов. Запускаем для каждого фрагмента секвентальный алгоритм

2024-12-06 01:17 UTC, allnes commented on tasks/mpi/anikin_m_contrastscale/src/ops_mpi.cpp
> +  }
its preprocessing

2024-12-06 01:18 UTC, allnes commented on tasks/mpi/anikin_m_contrastscale/func_tests/main.cpp
> +      ASSERT_EQ(seq_out[i].R, out[i].R);
why do you check R only?

2024-12-06 10:35 UTC, Kvoks requested changes
explicitly declare an array before using it
--> uint8_t newrgb[256] = { { 0 } };

2024-12-06 19:49 UTC, Domovenokkk requested changes
add a test when the contrast does not change

2024-12-06 20:12 UTC, decl1 commented on tasks/mpi/anikin_m_contrastscale/src/ops_mpi.cpp
> +  }
Fixed

2024-12-06 20:12 UTC, decl1 commented on tasks/mpi/anikin_m_contrastscale/func_tests/main.cpp
> +      ASSERT_EQ(seq_out[i].R, out[i].R);
Fixed

2024-12-06 20:15 UTC, Domovenokkk approved these changes

2024-12-06 20:24 UTC, Kvoks approved these changes

2024-12-07 13:34 UTC, aobolensk requested changes

2024-12-07 13:34 UTC, aobolensk commented on tasks/mpi/anikin_m_contrastscale/func_tests/main.cpp
> +  const int count = 10;
Please, test with different count

2024-12-07 13:34 UTC, aobolensk commented on tasks/mpi/anikin_m_contrastscale/src/ops_mpi.cpp
> +  // NOLINTNEXTLINE
What is the reason for that?

2024-12-07 15:15 UTC, decl1 commented on tasks/mpi/anikin_m_contrastscale/func_tests/main.cpp
> +  const int count = 10;
Added tests with 100 and 500 count

2024-12-07 15:24 UTC, decl1 commented on tasks/mpi/anikin_m_contrastscale/src/ops_mpi.cpp
> +  // NOLINTNEXTLINE
For some reason, the analyzer complained about scatterv, removed the suppress with next commit, and no longer complains.

2024-12-08 11:51 UTC, aobolensk approved these changes

2024-12-08 11:51 UTC, aobolensk approved these changes

2024-12-08 11:55 UTC, allnes approved these changes

2024-12-08 11:56 UTC, merged