‎Рамс Сергей. Задача 3. Вариант 20. Поразрядная сортировка для вещественных чисел (тип double) с простым слиянием.
learning-process/ppc-2024-autumn pull request #428
Opened 2024-12-03 14:33 UTC by 22380240

Описание последовательной задачи:
Входные данные: массив вещественных чисел double.
Выходные данные: отсортированный в порядке возрастания массив вещественных чисел double.

В качестве разряда выбран 1 байт. Таким образом для сортировки массива любой длины (<= std::vector::max_size) дополнительно потребуется 8 * (2 ^ 8) * 8 = 2 ^ 14 = 16KB памяти. Также, благодаря разряду в 1 байт, можно использовать битовый сдвиг вместо получения остатка от деления.

Содержимое типа double хранится в виде 64-битного числа в формате binary64, который описан стандартом IEEE 754.
```
[ sign (1 bit) ] [ exponent ] [ fraction ]
```
Экспонента хранится в более старших битах чем мантисса. Поэтому лексикографическое сравнение двоичного представления двух положительных чисел double даст тот же результат, что и сравнение этих чисел в вещественном представлении. У отрицательных вещественных чисел старший бит равен 1. Поэтому, для того чтобы лексикографическое сравнение двоичного представления положительных и отрицательных вещественных чисел давало такой же результат, что и сравнение в вещественном представлении, необходимо сравнивать модифицированные представления чисел: если старший бит равен 1 - то инвертировать все биты числа, если старший бит равен 0 - то инвертировать старший бит.

Для каждого разряда необходимо завести массив целых чисел с длиной равной количеству чисел, которые могут быть представлены этим разрядом. В этом решении:
Разряд - 1 байт. Значит всего разрядов - 8 / 1 = 8 (тип double занимает 8 байт).
Длина массива для каждого разряда - 2 ** 8 = 256.

Сортировка массива происходит в 3 этапа:

1. Для каждого разряда каждого числа исходного массива, элемент (с индексом равным значению текущего разряда исходного числа) массива (соответствующего номеру текущего разряда) увеличивается на 1.
2. Для каждого разряда элементы соответствующего номеру разряда массива конвертируются в префиксную сумму в порядке увеличения индекса массива.
3. Для каждого из разрядов в порядке от младшего к старшему каждый элемент исходного массива помещается в выходной массив на позицию равную значению префиксной суммы для элемента с индексом равным значению текущего разряда исходного числа массива соответстующего текущему разряду. Значение префиксной суммы увеличивается на 1. После смены текущего разряда, входной и выходной массив меняются местами.

В итоге получаем отсортированный массив.

Описание параллельной задачи:
Весь алгоритм тот же, за исключением того, что исходный массив делится на одинаковые части и каждая часть сортируется по отдельности каждым процессом. Потом слияние отсортированных частей выполняется в процессе с рангом 0. Нет необходимости делегировать слияние разным процессам, так как главному процессу все равно придется сделать N итераций для финального слияния.

2024-12-04 07:47 UTC, 22380240 commented on scripts/run.sh
> +for test_item in $(./build/bin/mpi_func_tests --gtest_list_tests | awk '/^[^ ].+\./{ SUITE=$1 }  /  / { print SUITE $1 }')
```shell
$ ./build/bin/mpi_func_tests --gtest_list_tests | tee testslist
Parallel_Operations_MPI.
  Test_Sum
  Test_Diff
some_test/some_test.
  parameterized/0  # GetParam() = {}
  parameterized/1  # GetParam() = { 10.4 }

$ cat testslist | awk '/\./{ SUITE=$1 }  /  / { print SUITE $1 }' | tee before
Parallel_Operations_MPI.Test_Sum
Parallel_Operations_MPI.Test_Diff
some_test/some_test.parameterized/0
parameterized/1parameterized/1

$ cat testslist | awk '/^[^ ].+\./{ SUITE=$1 }  /  / { print SUITE $1 }' | tee after
Parallel_Operations_MPI.Test_Sum
Parallel_Operations_MPI.Test_Diff
some_test/some_test.parameterized/0
some_test/some_test.parameterized/1

$ diff before after
4c4
< parameterized/1parameterized/1
---
> some_test/some_test.parameterized/1
```

`  parameterized/1  # GetParam() = { 10.4 }` удовлетворяет `/\./{ SUITE=$1 }`, так как `10.4` содержит точку.

---

Без этого изменения, параметризованные тесты, параметры которых содержат вещественные числа, не запускаются при исполнении `scripts/run.sh`:
<img src="https://github.com/user-attachments/assets/698af1f1-2adb-4def-b9a6-64aa9951aa6c" height="500px">

2024-12-08 11:52 UTC, aobolensk commented on scripts/run.sh
> +for test_item in $(./build/bin/mpi_func_tests --gtest_list_tests | awk '/^[^ ].+\./{ SUITE=$1 }  /  / { print SUITE $1 }')
Please, extract this to the separate patch

2024-12-15 03:07 UTC, kmichaelk commented on scripts/run.sh
> +for test_item in $(./build/bin/mpi_func_tests --gtest_list_tests | awk '/^[^ ].+\./{ SUITE=$1 }  /  / { print SUITE $1 }')
+1

2024-12-15 03:12 UTC, kmichaelk approved these changes

2024-12-15 03:12 UTC, kmichaelk commented on tasks/mpi/rams_s_radix_sort_with_simple_merge_for_doubles/src/ops_mpi.cpp
> +  }
IIRC there was a `scatterv` overload that omits `displs` given the data is contiguous

2024-12-16 08:17 UTC, MoiseevArt requested changes

2024-12-16 08:17 UTC, MoiseevArt commented on tasks/mpi/rams_s_radix_sort_with_simple_merge_for_doubles/src/ops_mpi.cpp
> +  const size_t bits_per_item = sizeof(double) * 8;
`const size_t bits_per_item = sizeof(double) * CHAR_BIT`

2024-12-16 08:17 UTC, MoiseevArt commented on tasks/seq/rams_s_radix_sort_with_simple_merge_for_doubles/src/ops_seq.cpp
> +    return histograms[histogram_index][((double_internal ^ (-(double_internal >> (bits_per_item - 1)) |
`return histograms[histogram_index][((double_internal ^ (-(double_internal >> (bits_per_item - 1)) |
                                                            (static_cast<size_t>(1) << (bits_per_item - 1)))) >>
                                        (radix * histogram_index)) &
                                       histogram_mask];`

2024-12-16 08:27 UTC, 22380240 commented on scripts/run.sh
> +for test_item in $(./build/bin/mpi_func_tests --gtest_list_tests | awk '/^[^ ].+\./{ SUITE=$1 }  /  / { print SUITE $1 }')
> Please, extract this to the separate patch

https://github.com/learning-process/ppc-2024-autumn/pull/554

2024-12-17 07:45 UTC, MoiseevArt approved these changes

2024-12-18 14:38 UTC, aobolensk approved these changes

2024-12-20 14:42 UTC, allnes approved these changes

2024-12-20 14:43 UTC, merged