Лаганина Елена. Задача 2. Вариант 2. Читатели-писатели.
learning-process/ppc-2024-autumn pull request #429
Opened 2024-12-03 19:13 UTC by laganina-cod

Реализована классическая задача “Читатели писатели” 

Некоторые потоки могут читать, а некоторые — писать, при этом ни один поток не может получить доступ к общему ресурсу для чтения или записи, пока другой поток записывает в него данные. 

База данных должна быть общей для нескольких процессов, при этом , некоторые из этих процессов могут только считывать данные из базы, в то время как другие -- обновлять данные в базе. Соответственно, процессы можно разделить на два типа: читатели и писатели. Запрещено одновременное изменение общего ресурса, а также изменение во время чтения, разрешено одновременное чтение. 

MPI реализация: 

Пусть процесс 0 является корневым и отвечает за коммуникацию между другими процессами. Так как у нас два типа процессов, разделим так : нечетные -- писатели, четные--читатели. К базе данных доступ осуществляется следующим образом: если обращается писатель-- ему выдается эксклюзивный доступ в базу, при котором другие процессы теряют возможность взаимодействовать с ней до тех пор, пока процесс писателя не завершится. Если обращается читатель -- база может выдать ему данные, а также может выдать данные любому последующему процессу-читателю. Важное замечание: пока все процессы-читатели не закончат свою работу доступ для писателя не может быть выдан.

2024-12-03 20:15 UTC, VladislavPoroshin commented on tasks/mpi/laganina_e_readers_writers/src/ops_mpi.cpp
> +    std::chrono::milliseconds timespan(1);  // simulate reading
I think it’s better to set the delay higher, for example, 3-10 ms

2024-12-03 20:15 UTC, VladislavPoroshin commented on tasks/mpi/laganina_e_readers_writers/src/ops_mpi.cpp
> +#include <ctime>
extra includes

2024-12-03 20:15 UTC, VladislavPoroshin commented on tasks/mpi/laganina_e_readers_writers/include/ops_mpi.hpp
> +#include <string>
extra includes

2024-12-03 20:27 UTC, laganina-cod commented on tasks/mpi/laganina_e_readers_writers/src/ops_mpi.cpp
> +  // int mutex = 1;             // semaphore for locking counter readers_count
fixed

2024-12-03 20:27 UTC, laganina-cod commented on tasks/mpi/laganina_e_readers_writers/src/ops_mpi.cpp
> +        // mutex = 1;  // unlock counter readerx_count
fixed

2024-12-03 20:27 UTC, laganina-cod commented on tasks/mpi/laganina_e_readers_writers/src/ops_mpi.cpp
> +        // mutex = 0;  // block counter readers_count
fixed

2024-12-03 20:28 UTC, laganina-cod commented on tasks/mpi/laganina_e_readers_writers/src/ops_mpi.cpp
> +        // mutex = 1;  // unlock counter readerx_count
fixed

2024-12-03 20:28 UTC, laganina-cod commented on tasks/mpi/laganina_e_readers_writers/src/ops_mpi.cpp
> +    std::chrono::milliseconds timespan(1);  // simulate reading
fixed

2024-12-03 20:28 UTC, laganina-cod commented on tasks/mpi/laganina_e_readers_writers/src/ops_mpi.cpp
> +#include <ctime>
fixed

2024-12-03 20:28 UTC, laganina-cod commented on tasks/mpi/laganina_e_readers_writers/include/ops_mpi.hpp
> +#include <string>
fixed

2024-12-03 20:31 UTC, VladislavPoroshin approved these changes

2024-12-03 20:31 UTC, KorotinEgor approved these changes

2024-12-06 01:19 UTC, allnes commented on tasks/mpi/laganina_e_readers_writers/func_tests/main.cpp
> +    vec[i] = (gen() % 100) - 49;
please parametrize this interval in tests

2024-12-06 01:20 UTC, allnes commented on tasks/mpi/laganina_e_readers_writers/src/ops_mpi.cpp
> +  // rank % 2 == 1 - writer
please randomize it

2024-12-06 01:21 UTC, allnes commented on tasks/mpi/laganina_e_readers_writers/src/ops_mpi.cpp
> +    world.send(0, 0, 1);
please use non-bloceked mpi operations everywhere - isend, irecv, ...

2024-12-06 17:34 UTC, laganina-cod commented on tasks/mpi/laganina_e_readers_writers/func_tests/main.cpp
> +    vec[i] = (gen() % 100) - 49;
fixed

2024-12-06 17:34 UTC, laganina-cod commented on tasks/mpi/laganina_e_readers_writers/src/ops_mpi.cpp
> +  // rank % 2 == 1 - writer
fixed

2024-12-06 17:35 UTC, laganina-cod commented on tasks/mpi/laganina_e_readers_writers/src/ops_mpi.cpp
> +    world.send(0, 0, 1);
fixed

2024-12-07 07:58 UTC, aobolensk commented on tasks/mpi/laganina_e_readers_writers/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz, int a, int b);
Please, move test function to the test module

2024-12-07 12:01 UTC, laganina-cod commented on tasks/mpi/laganina_e_readers_writers/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz, int a, int b);
fixed

2024-12-07 13:35 UTC, aobolensk requested changes

2024-12-07 17:02 UTC, laganina-cod commented on tasks/mpi/laganina_e_readers_writers/func_tests/main.cpp
> +std::vector<int> getRandomVector(int sz, int a, int b) {
fixed

2024-12-08 11:57 UTC, allnes approved these changes

2024-12-08 11:59 UTC, aobolensk approved these changes

2024-12-08 11:59 UTC, merged