Филатьев Владислав. Задача 1. Вариант 10. Сумма элементов матрицы.
learning-process/ppc-2024-autumn pull request #43
Opened 2024-10-25 23:33 UTC by WladislawFilatew

Матрица представлена в виде вектор целых чисел (развернутая матрица).

**Описание последовательной задачи**  
- Последовательное сложение всех элементов матрицы. 

**Описание MPI задачи**  
- Матрица целых чисел разбивается на равные части. Каждый процесс получает свою часть матрицы и находит сумму данной части. Затем все процессы отправляют свои результаты главному процессу, который собирает их и определяет окончательную сумму для всей матрицы.

2024-10-26 10:03 UTC, DSolo03 requested changes

2024-10-26 10:03 UTC, DSolo03 commented on tasks/mpi/filatev_v_sum_of_matrix_elements/src/ops_mpi.cpp
> +  }
Better `matrix.reserve` memory for all matrix element, and then `matrix.insert(matrix.end(),temp.begin(),temp.end())` every of matrix lines

2024-10-26 11:15 UTC, DSolo03 approved these changes

2024-10-26 11:16 UTC, WladislawFilatew commented on tasks/mpi/filatev_v_sum_of_matrix_elements/src/ops_mpi.cpp
> +  for (long unsigned int i = 0; i < matrix.size(); ++i) {
Fixed

2024-10-26 11:16 UTC, WladislawFilatew commented on tasks/mpi/filatev_v_sum_of_matrix_elements/src/ops_mpi.cpp
> +  }
Fixed

2024-10-27 08:00 UTC, hasanyanovk commented on tasks/mpi/filatev_v_sum_of_matrix_elements/src/ops_mpi.cpp
> +  }
you can unite these blocks

2024-10-27 08:02 UTC, hasanyanovk commented on tasks/mpi/filatev_v_sum_of_matrix_elements/src/ops_mpi.cpp
> +    local_vector = std::vector<int>(matrix.begin(), matrix.begin() + delta + ras);
Bad idea to push remainder of elements into one process, in your realisation root-process has the largest load, much more than the rest

2024-10-27 09:51 UTC, allnes commented on tasks/mpi/filatev_v_sum_of_matrix_elements/src/ops_mpi.cpp
> +bool filatev_v_sum_of_matrix_elements_mpi::SumMatrixParallel::pre_processing() {
please don't use functionality for run() in pre_processing(), work with mpi is not preprocessing

2024-10-27 15:00 UTC, aobolensk requested changes

2024-10-27 15:00 UTC, aobolensk commented on tasks/mpi/filatev_v_sum_of_matrix_elements/include/ops_mpi.hpp
> +std::vector<std::vector<int>> getRandomMatrix(int size_n, int size_m);
Move this function to tests

2024-10-27 15:00 UTC, aobolensk commented on tasks/seq/filatev_v_sum_of_matrix_elements/perf_tests/main.cpp
> +  const int count = 10000;
Test on different sizes in perf test

2024-10-27 19:44 UTC, WladislawFilatew commented on tasks/mpi/filatev_v_sum_of_matrix_elements/src/ops_mpi.cpp
> +  }
Fixed

2024-10-27 19:44 UTC, WladislawFilatew commented on tasks/mpi/filatev_v_sum_of_matrix_elements/src/ops_mpi.cpp
> +    local_vector = std::vector<int>(matrix.begin(), matrix.begin() + delta + ras);
Fixed

2024-10-27 19:45 UTC, WladislawFilatew commented on tasks/mpi/filatev_v_sum_of_matrix_elements/src/ops_mpi.cpp
> +bool filatev_v_sum_of_matrix_elements_mpi::SumMatrixParallel::pre_processing() {
Fixed

2024-10-27 21:29 UTC, WladislawFilatew commented on tasks/mpi/filatev_v_sum_of_matrix_elements/include/ops_mpi.hpp
> +std::vector<std::vector<int>> getRandomMatrix(int size_n, int size_m);
Fixed

2024-10-27 21:30 UTC, WladislawFilatew commented on tasks/seq/filatev_v_sum_of_matrix_elements/perf_tests/main.cpp
> +  const int count = 10000;
Added additional tests

2024-10-28 05:57 UTC, aobolensk approved these changes

2024-10-28 14:15 UTC, allnes approved these changes

2024-10-30 14:51 UTC, hasanyanovk approved these changes

2024-10-30 16:34 UTC, merged