Fix Лысов Иван. Задача 1. Вариант 20. Интегрирование – метод трапеций.
learning-process/ppc-2024-autumn pull request #431
Opened 2024-12-04 09:45 UTC by Ivan-Lysov

Последовательный вариант(SEQ)

- В последовательной версии используется метод run() класса TestTaskSequential, который выполняет интегрирование на заданном отрезке [a, b] используя epsilon для контроля точности.

Основные этапы работы:

Валидация и подготовка данных: Метод validation() проверяет корректность входных данных, включая размеры массивов и допустимость значения epsilon .
Подготовка разбиений: Метод pre_processing() определяет количество разбиений cnt_of_splits, в зависимости от заданной точности epsilon, шаг разбиения h, который равен (b - a) / cnt_of_splits, и инициализирует локальные переменные.
Интегрирование: Метод run() вычисляет площадь трапеций на отрезке [a, b], проходя по разбиениям и суммируя результаты.
Постобработка данных: В методе post_processing() результат интегрирования сохраняется в выходной массив.
Параллельный вариант (MPI)

- В параллельной версии используется метод run() класса TestMPITaskParallel, который распределяет интервал между процессами, основываясь на epsilon для контроля точности.

Основные этапы работы:

Распределение данных: Метод pre_processing() делит отрезок [a, b] между процессами, определяя локальные переменные для каждого процесса (начало отрезка local_a и количество разбиений local_cnt_of_splits). Для синхронизации используется broadcast().
Локальное интегрирование: Каждый процесс в методе run() выполняет интегрирование на своем участке и накапливает локальный результат local_res.
Сбор результатов: Метод reduce() суммирует локальные результаты в переменную res в процессе с рангом 0.
Постобработка данных: В методе post_processing() результат интегрирования сохраняется в выходной массив, если процесс с рангом 0.

Исправил func_test из-за которого падало

2024-12-04 10:54 UTC, novi40k1 commented on tasks/seq/lysov_i_integration_the_trapezoid_method/src/ops_seq.cpp
> +#include <thread>
remove unused libraries

2024-12-04 10:54 UTC, novi40k1 commented on tasks/mpi/lysov_i_integration_the_trapezoid_method/src/ops_mpi.cpp
> +#include <thread>
remove unused libraries

2024-12-05 18:33 UTC, Ivan-Lysov commented on tasks/seq/lysov_i_integration_the_trapezoid_method/src/ops_seq.cpp
> +#include <thread>
thanks, fix

2024-12-05 18:33 UTC, Ivan-Lysov commented on tasks/mpi/lysov_i_integration_the_trapezoid_method/src/ops_mpi.cpp
> +#include <thread>
thanks, fix

2024-12-05 20:48 UTC, novi40k1 approved these changes

2024-12-06 03:03 UTC, ascannel requested changes

2024-12-06 11:08 UTC, Ivan-Lysov commented on tasks/mpi/lysov_i_integration_the_trapezoid_method/perf_tests/main.cpp
> +    ASSERT_NEAR(reference_result[0], global_result[0], 1e-1);
thanks, I am fix

2024-12-06 11:13 UTC, ascannel approved these changes

2024-12-07 13:35 UTC, aobolensk approved these changes

2024-12-08 11:56 UTC, allnes approved these changes

2024-12-08 11:57 UTC, merged