Вершинина Александра. Задача 2. Вариант 26. Сглаживание изображения
learning-process/ppc-2024-autumn pull request #433
Opened 2024-12-04 17:46 UTC by sanya2905

Сглаживание изображения происходит путем нахождения среднего значения соседних пикселей и самого пикселя для каждого пикселя изображения. В параллельном решении матрица делится построчно в зависимости от числа процессов, строки отправляются каждому процессу с помощью scatterv, затем вычисляются значения и с помощью gatherv собирается ответ.

2024-12-05 21:39 UTC, belovtut requested changes

2024-12-05 21:39 UTC, belovtut commented on tasks/mpi/vershinina_a_image_smoothing/src/ops_mpi.cpp
> +  remainder = rows % world.size();
In preprocessing you only prepare data for further work with them, you have to move the rest of the code to run()

2024-12-06 00:17 UTC, belovtut approved these changes

2024-12-06 09:35 UTC, ermilovad requested changes

2024-12-06 10:11 UTC, ermilovad approved these changes

2024-12-06 14:26 UTC, sanya2905 commented on tasks/mpi/vershinina_a_image_smoothing/src/ops_mpi.cpp
> +  remainder = rows % world.size();
fixed

2024-12-06 14:26 UTC, sanya2905 commented on tasks/mpi/vershinina_a_image_smoothing/src/ops_mpi.cpp
> +        local_input_sizes[i] = rows * cols;
fixed

2024-12-08 12:54 UTC, allnes commented on tasks/mpi/vershinina_a_image_smoothing/src/ops_mpi.cpp
> +  broadcast(world, cols, 0);
please broadcast, rows per proc and reminder insteads rows and cols and calculate it one time in 0 process

2024-12-08 12:55 UTC, allnes commented on tasks/mpi/vershinina_a_image_smoothing/perf_tests/main.cpp
> +  std::uniform_int_distribution<> distr(2, 25);
its small values for rows and cols

2024-12-08 13:52 UTC, aobolensk requested changes

2024-12-08 13:52 UTC, aobolensk commented on tasks/mpi/vershinina_a_image_smoothing/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int rows, int cols);
Please, move test functions to the test module

2024-12-08 13:52 UTC, aobolensk commented on tasks/mpi/vershinina_a_image_smoothing/src/ops_mpi.cpp
> +          send[i] = 0;
Isn't that already 0 ?

2024-12-08 13:52 UTC, aobolensk commented on tasks/mpi/vershinina_a_image_smoothing/perf_tests/main.cpp
> +  in = vershinina_a_image_smoothing::getRandomVector(100, 99);
Too small size for perf tests

2024-12-08 13:52 UTC, aobolensk commented on tasks/seq/vershinina_a_image_smoothing/func_tests/main.cpp
> +std::vector<int> vershinina_a_image_smoothing::getRandomVector(int rows, int cols) {
Please, add func tests on random images

2024-12-08 13:58 UTC, sanya2905 commented on tasks/seq/vershinina_a_image_smoothing/func_tests/main.cpp
> +std::vector<int> vershinina_a_image_smoothing::getRandomVector(int rows, int cols) {
I already have it, Test_Random_1 and Test_Random_2

2024-12-08 15:01 UTC, sanya2905 commented on tasks/mpi/vershinina_a_image_smoothing/perf_tests/main.cpp
> +  in = vershinina_a_image_smoothing::getRandomVector(100, 99);
fixed

2024-12-08 15:02 UTC, sanya2905 commented on tasks/mpi/vershinina_a_image_smoothing/src/ops_mpi.cpp
> +          send[i] = 0;
yes, fixed

2024-12-08 15:02 UTC, sanya2905 commented on tasks/mpi/vershinina_a_image_smoothing/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int rows, int cols);
fixed

2024-12-08 15:02 UTC, sanya2905 commented on tasks/mpi/vershinina_a_image_smoothing/perf_tests/main.cpp
> +  std::uniform_int_distribution<> distr(2, 25);
fixed

2024-12-08 15:02 UTC, sanya2905 commented on tasks/mpi/vershinina_a_image_smoothing/perf_tests/main.cpp
> +  int random_cols = distr(gen);
fixed

2024-12-08 15:05 UTC, sanya2905 commented on tasks/mpi/vershinina_a_image_smoothing/src/ops_mpi.cpp
> +  broadcast(world, cols, 0);
fixed, I calculated rows per proc and reminder in 0 process and broadcasted, but didnt remove broadcast of rows and cols because these values are used by each process

2024-12-08 18:41 UTC, allnes approved these changes

2024-12-09 03:26 UTC, aobolensk approved these changes

2024-12-09 03:26 UTC, merged