Капустин Иван Задача 2 Вариант 25 "пузырьковая" сортировка
learning-process/ppc-2024-autumn pull request #435
Opened 2024-12-05 10:54 UTC by kapustinI

Задача заключается в реализации параллельной версии алгоритма сортировки пузырьком.  Входной массив делится на части, которые обрабатываются разными процессами. Каждый процесс выполняет сортировку своей части массива, затем данные обмениваются между процессами для корректной сортировки на всем объеме. После нескольких этапов обмена процесс с рангом 0 собирает отсортированные части и формирует итоговый отсортированный массив.

2024-12-05 18:38 UTC, hasanyanovk commented on tasks/mpi/kapustin_i_bubble/src/avg_mpi.cpp
> +    world.send(partner, 0, local_data.data(), send_size);
I think u can use different tags for different types of data

2024-12-05 21:06 UTC, kapustinI commented on tasks/mpi/kapustin_i_bubble/src/avg_mpi.cpp
> +    world.send(partner, 0, local_data.data(), send_size);
Fixed

2024-12-05 21:49 UTC, hasanyanovk approved these changes

2024-12-08 19:22 UTC, kmichaelk requested changes

2024-12-08 19:22 UTC, kmichaelk commented on tasks/mpi/kapustin_i_bubble/src/avg_mpi.cpp
> +    world.send(0, 0, &send_size, 1);
```suggestion
    world.send(0, 0, send_size);
```

2024-12-08 19:22 UTC, kmichaelk commented on tasks/mpi/kapustin_i_bubble/src/avg_mpi.cpp
> +      world.recv(rank, 0, &recv_size, 1);
```suggestion
      world.recv(rank, 0, recv_size);
```

2024-12-08 19:26 UTC, kmichaelk commented on tasks/mpi/kapustin_i_bubble/src/avg_mpi.cpp
> +    world.send(partner, 0, local_data.data(), send_size);
Should not be a problem until there's concurrency in nodes access though

2024-12-08 22:01 UTC, kmichaelk approved these changes

2024-12-09 03:34 UTC, aobolensk requested changes

2024-12-09 03:34 UTC, aobolensk commented on tasks/mpi/kapustin_i_bubble/func_tests/main.cpp
> +  std::generate(in.begin(), in.end(), []() { return rand() % 1000; });
Please, add check for negative numbers

2024-12-09 03:34 UTC, aobolensk commented on tasks/mpi/kapustin_i_bubble/perf_tests/main.cpp
> +  const int data_size = 30000;
Please, increase data size for perf tests

2024-12-09 03:34 UTC, aobolensk commented on tasks/seq/kapustin_i_bubble/func_tests/main.cpp
> +}
There are too few tests for seq version

2024-12-09 03:34 UTC, aobolensk commented on tasks/seq/kapustin_i_bubble/func_tests/main.cpp
> +std::vector<int> generate_random_data(int size, int min_val, int max_val) {
Either make it static or wrap with namespace

2024-12-09 19:25 UTC, kapustinI commented on tasks/seq/kapustin_i_bubble/func_tests/main.cpp
> +}
fixed

2024-12-09 20:42 UTC, aobolensk approved these changes

2024-12-15 19:23 UTC, allnes approved these changes

2024-12-15 19:23 UTC, merged