Чистов Алексей. Задача 3. Вариант 32. Построение выпуклой оболочки для компонент бинарного изображения.
learning-process/ppc-2024-autumn pull request #437
Opened 2024-12-05 15:37 UTC by Alexey2013

SEQ: На первом этапе выполняется маркировка связных компонент с использованием двух проходов. Затем для каждой компонент вычисляется выпуклая оболочка с помощью алгоритма Грэхема. На выходе формируется изображение с нанесенными контурами выпуклых оболочек.

MPI: Расширенная последовательная версия Исходное изображение разбивается на фрагменты, которые распределяются между процессами. Каждый процесс обрабатывает свой набор компонент и вычисляет выпуклые оболочки локально. Результаты собираются на основном процессе, который объединяет локальные оболочки и наносит их на итоговое изображение.

2024-12-06 14:47 UTC, MatveyKurakin commented on tasks/mpi/chistov_a_convex_hull_image/include/image.hpp
> +}  // namespace chistov_a_convex_hull_image_mpi_test
Move the test generation function to the test module

2024-12-06 14:47 UTC, MatveyKurakin commented on tasks/mpi/chistov_a_convex_hull_image/src/image.cpp
> +using namespace std::chrono_literals;
Remove this

2024-12-06 14:47 UTC, MatveyKurakin commented on tasks/seq/chistov_a_convex_hull_image_seq/include/image.hpp
> +}  // namespace chistov_a_convex_hull_image_seq_test
Move the test generation function to the test module

2024-12-06 16:03 UTC, dima-dimka04 commented on tasks/seq/chistov_a_convex_hull_image_seq/func_tests/image.cpp
> +  const int height = 10;
Add more tests with different image size or tests with more components (e.g. 7-10). In `mpi_func_tests` too.

2024-12-07 07:12 UTC, MatveyKurakin approved these changes

2024-12-07 10:23 UTC, dima-dimka04 approved these changes

2024-12-08 13:58 UTC, aobolensk requested changes

2024-12-08 13:58 UTC, aobolensk commented on tasks/mpi/chistov_a_convex_hull_image/func_tests/image.cpp
> +TEST(chistov_a_convex_hull_image_mpi, validation_test_empty_image) {
I'm not sure if 3x4 is an empty image

2024-12-08 13:58 UTC, aobolensk commented on tasks/mpi/chistov_a_convex_hull_image/perf_tests/image.cpp
> +  const int height = 1000;
Size seems to be small for perf test

2024-12-08 13:58 UTC, aobolensk commented on tasks/mpi/chistov_a_convex_hull_image/include/image.hpp
> +class ConvexHullSEQ : public ppc::core::Task {
I'm confused, why seq version is here?

2024-12-09 03:31 UTC, aobolensk approved these changes

2024-12-15 19:25 UTC, allnes approved these changes

2024-12-15 19:25 UTC, merged