Шведова Виталина. Задача 3. Вариант 9. Вычисление многомерных интегралов с использованием многошаговой схемы (метод Симпсона)
learning-process/ppc-2024-autumn pull request #438
Opened 2024-12-05 17:33 UTC by shvedovav

# Вычисление многомерных интегралов методом Симпсона с использованием многошаговой схемы

## Основные этапы

1. **Инициализация**  
   - Устанавливается начальное число подынтервалов (`subintervalCount = 2`).
   - Определяются пределы интегрирования.

2. **Рекурсия**  
   - Обрабатывается одна переменная, текущая точка добавляется в массив `currentArgs`.
   - Если переменных больше одной, вызывается рекурсивная функция для следующей переменной.
   - Если пределы закончились, вычисляется значение целевой функции.

3. **Метод Симпсона**  
   - Делится интервал на подынтервалы (`stepSize`).
   - Вычисляются значения функции с учетом весов:
     - Крайние точки: вес = 1.
     - Промежуточные точки: вес = 4 (нечетные индексы) или 2 (четные индексы).
   - Интегральная сумма масштабируется и проверяется на сходимость (точность).

4. **Возврат результатов**  
   - Результаты собираются с каждого уровня рекурсии.
   - Итерации повторяются до достижения заданной точности.

# Параллельная версия 

## Основной принцип
- Каждый процесс обрабатывает свою часть интервала интегрирования.

## Этапы параллельных вычислений
1. **Разделение интервала**  
   - Глобальный интервал делится на равные части между всеми процессами.
   - Каждый процесс получает свой локальный интервал для обработки.

2. **Локальные вычисления**  
   - Каждый процесс выполняет вычисление интеграла на своем интервале с использованием метода Симпсона.
   - Локальный результат масштабируется в соответствии с шагом интегрирования.

3. **Сбор результатов**  
   - Локальные результаты всех процессов объединяются (операция `reduce`) в глобальный результат.
   - Результат собирается в процессе с рангом `0`.

4. **Контроль точности**  
   - Процесс с рангом `0` проверяет, достигнута ли заданная точность.
   - Решение о продолжении итераций передается всем процессам (операция `broadcast`).

2024-12-12 06:57 UTC, korablev-vm approved these changes

2024-12-12 13:27 UTC, venn2713 requested changes

2024-12-12 13:27 UTC, venn2713 commented on tasks/mpi/shvedova_v_mult_int_simpson/perf_tests/main.cpp
> +TEST(shvedova_v_mult_int_simpson_mpi, test_pipeline_run) {
Посмотрите пример перф теста и перепишите, пожалуйста

2024-12-12 13:27 UTC, venn2713 commented on tasks/mpi/shvedova_v_mult_int_simpson/func_tests/main.cpp
> +  ASSERT_EQ(testTaskParallel.validation(), true);
Ипользуйте специальную структуру

2024-12-12 13:27 UTC, venn2713 commented on tasks/mpi/shvedova_v_mult_int_simpson/func_tests/main.cpp
> +double tripleProductFunction(std::vector<double>& args) { return args[0] * args[1] * args[2]; }
Не уверен что это здесь используется

2024-12-12 13:38 UTC, shvedovav commented on tasks/mpi/shvedova_v_mult_int_simpson/func_tests/main.cpp
> +double tripleProductFunction(std::vector<double>& args) { return args[0] * args[1] * args[2]; }
Функции используются ниже в тестах, сделала для удобства чтения кода.

2024-12-12 20:12 UTC, venn2713 commented on tasks/mpi/shvedova_v_mult_int_simpson/func_tests/main.cpp
> +double tripleProductFunction(std::vector<double>& args) { return args[0] * args[1] * args[2]; }
Понял, действительно

2024-12-13 14:43 UTC, venn2713 approved these changes

2024-12-15 09:12 UTC, aobolensk approved these changes

2024-12-20 14:44 UTC, allnes commented on tasks/seq/shvedova_v_multi_integral_simpson/perf_tests/main.cpp
> +    return args[0] * args[0] + args[1] * args[1] + args[2] * args[2];
please make more difficult function

2024-12-20 15:25 UTC, shvedovav commented on tasks/seq/shvedova_v_multi_integral_simpson/perf_tests/main.cpp
> +    return args[0] * args[0] + args[1] * args[1] + args[2] * args[2];
I have corrected your comment. At the same time, I changed the function in the mpi part, now they are the same. I chose triple integral because the class discussed the need to work correctly on double integrals and triple integrals. The function has now become much more difficult.

2024-12-24 20:38 UTC, shvedovav commented
@allnes, please review this PR

2024-12-25 18:50 UTC, merged