Хохлов Андрей. Задача 2. Вариант 23. Итеративные методы (Зейделя).
learning-process/ppc-2024-autumn pull request #439
Opened 2024-12-05 18:40 UTC by pipidaster2004

Задача: решить систему линейных алгебраических уравнений итеративным методом Зейделя.
Последовательная версия: на вход подается вещественная матрица коэффициентов А размером n на n и вектор b размером n, требуется найти вектор решений x размером n.  Метод Зейделя выполняет итерации, обновляя значения 
𝑥[𝑖] на основе текущего состояния других 𝑥[𝑗].
Условие сходимости: проверяется норма разности текущего и предыдущего решений 
∣∣𝑥(𝑘+1)−𝑥𝑘∣∣<𝜀.
формула обновления компоненты xi:
xi^(k+1) = 1/Aii(bi −(j=0,j!=i)(n-1)∑Aijxj^(k+1))

Параллельная версия: матрица коэффициентов А разбивается на локальные матрицы размера n*local_n, где local_n равняется делением нацело числа строк на число процессов, остаток записывается в последний процесс, вектор b также разбивается на локальные вектора размера n. После каждой итерации перезаписывается 𝑥(𝑘+1) и 𝑥𝑘, после чего считается локальная норма для каждого процесса и суммируется в нулевом, после чего происходит проверка на сходимость.

Чтобы решение сходилось, в тестах используется генерация матрицы с диагональным преобладанием.
​
  
​

2024-12-06 11:21 UTC, nCUXe commented on tasks/mpi/khokhlov_a_iterative_seidel_method/func_tests/main_khokhlov.cpp
> +
add more tests with different sizes and number of iterations (10, 20, 50, 100) and EPSILON must be specified by the user

2024-12-06 11:27 UTC, nCUXe commented on tasks/mpi/khokhlov_a_iterative_seidel_method/include/ops_mpi_khokhlov.hpp
> +  const double EPSILON = 1e-6;
EPSILON be set in pre_processing() and not be a constant value

2024-12-06 12:28 UTC, AnastasiaRezantseva requested changes

2024-12-06 12:28 UTC, AnastasiaRezantseva commented on tasks/mpi/khokhlov_a_iterative_seidel_method/src/ops_mpi_khokhlov.cpp
> +        x[i] = (b[i] - sum) / A[i * n + i];
Checking the correctness of the matrix should be in validation

2024-12-06 12:28 UTC, AnastasiaRezantseva commented on tasks/mpi/khokhlov_a_iterative_seidel_method/include/ops_mpi_khokhlov.hpp
> +#include <vector>
Remove unnecessary libraries

2024-12-06 14:18 UTC, pipidaster2004 commented on tasks/mpi/khokhlov_a_iterative_seidel_method/src/ops_mpi_khokhlov.cpp
> +        x[i] = (b[i] - sum) / A[i * n + i];
fixed

2024-12-06 14:18 UTC, pipidaster2004 commented on tasks/mpi/khokhlov_a_iterative_seidel_method/include/ops_mpi_khokhlov.hpp
> +#include <vector>
fixed

2024-12-06 14:19 UTC, pipidaster2004 commented on tasks/mpi/khokhlov_a_iterative_seidel_method/func_tests/main_khokhlov.cpp
> +
fixed

2024-12-06 14:21 UTC, nCUXe approved these changes

2024-12-06 15:18 UTC, AnastasiaRezantseva approved these changes

2024-12-06 18:58 UTC, emilien-gus requested changes

2024-12-06 18:58 UTC, emilien-gus commented on tasks/mpi/khokhlov_a_iterative_seidel_method/src/ops_mpi_khokhlov.cpp
> +  }
You should add a check for the uniqueness of the solution(check your outputs_count). Also do it for the sequantial version.

2024-12-06 19:14 UTC, emilien-gus commented on tasks/mpi/khokhlov_a_iterative_seidel_method/src/ops_mpi_khokhlov.cpp
> +bool khokhlov_a_iterative_seidel_method_mpi::seidel_method_mpi::validation() {
You should add a check for the uniqueness of the solution of a system of linear equation. Also do it for the seq version

2024-12-07 16:34 UTC, pipidaster2004 commented on tasks/mpi/khokhlov_a_iterative_seidel_method/src/ops_mpi_khokhlov.cpp
> +bool khokhlov_a_iterative_seidel_method_mpi::seidel_method_mpi::validation() {
fixed

2024-12-07 16:40 UTC, emilien-gus approved these changes

2024-12-09 03:40 UTC, aobolensk requested changes

2024-12-09 03:40 UTC, aobolensk commented on tasks/mpi/khokhlov_a_iterative_seidel_method/include/ops_mpi_khokhlov.hpp
> +void getRandomSLAU(std::vector<double>& A, std::vector<double>& b, int N);
Please, move test functions to the test module

2024-12-09 10:43 UTC, pipidaster2004 commented on tasks/mpi/khokhlov_a_iterative_seidel_method/include/ops_mpi_khokhlov.hpp
> +void getRandomSLAU(std::vector<double>& A, std::vector<double>& b, int N);
fixed

2024-12-09 20:53 UTC, aobolensk approved these changes

2024-12-15 19:26 UTC, allnes approved these changes

2024-12-15 19:26 UTC, merged