Чижов Максим. Задача 1. Вариант 16.  Нахождение максимальных значений по столбцам матрицы
learning-process/ppc-2024-autumn pull request #44
Opened 2024-10-26 11:53 UTC by MaximChizhov

Матрица представлена в виде вектора целых чисел

**Описание последовательной задачи**
В качестве максимального элемента выбирается первый элемент столбца. Дальше каждый элемент столбца сравнивается с максимальным, если значение элемента столбца больше максимального, то максимальный элемент обновляется. В конце выполнения функции возвращается вектор, который содержит максимальные значения каждого столбца.

**Описание MPI задачи**
В зависимости от количества столбцов и процессов матрица делится. Каждый процесс получает определенное количество столбцов, в которых находит максимальные значения в каждом столбце. Для этого рассчитывается стартовый столбец и последний столбец. Результат собирается при помощи функции gatherv в один вектор.

2024-10-29 04:14 UTC, LizochkaSpring commented on tasks/mpi/chizhov_m_max_values_by_columns_matrix/src/ops_mpi.cpp
> +}
Check the negative values

2024-10-29 04:26 UTC, LizochkaSpring commented on tasks/seq/chizhov_m_max_values_by_columns_matrix/src/ops_seq.cpp
> +using namespace std::chrono_literals;
These two lines are not needed

2024-10-29 04:28 UTC, LizochkaSpring commented on tasks/mpi/chizhov_m_max_values_by_columns_matrix/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
Lines 8 and 11 are not needed here

2024-10-29 19:28 UTC, MaxikGuy requested changes
Currently, the tests do not cover the case where the number of columns in the matrix is zero. This case could lead to unpredictable results or errors during program execution, as some MPI implementations do not handle such checks automatically. I recommend adding a check for this edge case to ensure that the program handles matrices with zero columns correctly.

2024-10-29 19:32 UTC, allnes commented on tasks/mpi/chizhov_m_max_values_by_columns_matrix/src/ops_mpi.cpp
> +bool chizhov_m_max_values_by_columns_matrix_mpi::TestMPITaskParallel::pre_processing() {
@MaximChizhov could I ask answer in comments, because I don't understand for what comments you answer, if it answer for me, please answer more detailed, thank you

2024-10-30 01:18 UTC, aobolensk requested changes

2024-10-30 01:18 UTC, aobolensk commented on tasks/mpi/chizhov_m_max_values_by_columns_matrix/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
Please move test function to the test module

2024-10-30 01:18 UTC, aobolensk commented on tasks/seq/chizhov_m_max_values_by_columns_matrix/func_tests/main.cpp
> +TEST(chizhov_m_max_values_by_columns_matrix_seq, Test_Max_3_Columns) {
Please, check empty matrix

2024-10-30 01:18 UTC, aobolensk commented on tasks/mpi/chizhov_m_max_values_by_columns_matrix/func_tests/main.cpp
> +TEST(chizhov_m_max_values_by_columns_matrix_mpi, Test_Max1) {
Please, check empty matrix

2024-11-01 11:53 UTC, LizochkaSpring approved these changes

2024-11-01 11:58 UTC, MaxikGuy approved these changes

2024-11-01 16:25 UTC, aobolensk approved these changes

2024-11-04 00:40 UTC, allnes approved these changes

2024-11-04 00:40 UTC, merged