Ермилова Дарья. Задача 2. Вариант 6. Передача от всех одному (reduce).
learning-process/ppc-2024-autumn pull request #440
Opened 2024-12-05 19:27 UTC by ermilovad

Реализована функция reduce. В качестве рассматриваемой задачи используется задача нахождения минимума в матрице.

Корневой процесс разбивает матрицу на равные части. Каждый процесс получает свою часть матрицы, затем находит минимум в выделенной ему части, используя функцию CustomReduce. Функция реализована по принципу двоичного дерева, где процессы, начиная с листьев (процессов, которые обрабатывают отдельные части данных), постепенно сливаются с соседними процессами. На каждом шаге два процесса сливают свои результаты (минимумы), пока не будет найдено одно итоговое минимальное значение, которое будет у корневого процесса.

2024-12-07 10:03 UTC, odincovm requested changes
apply_operation должна выдавать, ошибку если в нее передали неверную команду

2024-12-07 10:09 UTC, sanya2905 requested changes
delete "using namespace std::chrono_literals"
you don't use this

2024-12-07 11:06 UTC, ermilovad commented
> удалите «using namespace std::chrono_literals» вы не используете это

fixed

2024-12-07 11:06 UTC, ermilovad commented
> apply_operation должна выдавать, ошибку если в нее передали неверную команду

fixed

2024-12-07 11:08 UTC, sanya2905 approved these changes

2024-12-07 11:31 UTC, odincovm approved these changes

2024-12-09 03:48 UTC, aobolensk requested changes

2024-12-09 03:48 UTC, aobolensk commented on tasks/mpi/ermilova_d_custom_reduce/func_tests/main.cpp
> +  float global_result = std::numeric_limits<float>::min();
Why tests are dependent on the rank?

2024-12-09 03:48 UTC, aobolensk commented on tasks/mpi/ermilova_d_custom_reduce/include/ops_mpi.hpp
> +class TestMPITaskSequential : public ppc::core::Task {
Why do you need to keep seq version here?

2024-12-11 19:18 UTC, aobolensk requested changes

2024-12-11 19:18 UTC, aobolensk commented on tasks/mpi/ermilova_d_custom_reduce/func_tests/main.cpp
> +std::vector<T> getRandom(int size) {
Please, either make it static or wrap with namespace

2024-12-11 19:18 UTC, aobolensk commented on tasks/mpi/ermilova_d_custom_reduce/func_tests/main.cpp
> +  boost::mpi::scatter(world, input_.data(), recv_data.data(), size, 0);
Why tests are using MPI functions?

2024-12-11 19:54 UTC, ermilovad commented on tasks/mpi/ermilova_d_custom_reduce/func_tests/main.cpp
> +  boost::mpi::scatter(world, input_.data(), recv_data.data(), size, 0);
This is used to coordinate testing with random data.

2024-12-11 19:56 UTC, ermilovad commented on tasks/mpi/ermilova_d_custom_reduce/func_tests/main.cpp
> +std::vector<T> getRandom(int size) {
fixed

2024-12-11 19:58 UTC, aobolensk commented on tasks/mpi/ermilova_d_custom_reduce/func_tests/main.cpp
> +  boost::mpi::scatter(world, input_.data(), recv_data.data(), size, 0);
Actually, tests should not depend on direct MPI calls. They should use an interface that is agnostic to what is inside the implementation

2024-12-15 19:28 UTC, allnes approved these changes

2024-12-15 19:29 UTC, allnes approved these changes

2024-12-15 19:30 UTC, merged