Частов Вячеслав. Задача 2. Вариант 25. Сортировка пузырьком (алгоритм чет-нечетной перестановки).
learning-process/ppc-2024-autumn pull request #441
Opened 2024-12-05 19:38 UTC by ChastovSlava

Задача заключается в реализации алгоритма пузырьковой сортировки в двух вариантах: последовательном (SEQUENTIAL) и параллельном (MPI), с применением объектно-ориентированного подхода и тестированием функциональности.

Алгоритм пузырьковой сортировки:
1) Последовательно сравнивает соседние элементы массива.
2) Меняет их местами, если порядок нарушен.
3) Повторяет проходы по массиву до полной упорядоченности.

Последовательная версия (SEQUENTIAL):
Выполняет сортировку на одном процессе, используя стандартные структуры данных и алгоритмы.

Параллельная версия (MPI):
1) Использует технологии параллельного программирования (MPI) для распределения данных между процессами.
2) Обеспечивает ускорение за счет одновременной обработки фрагментов массива.

Тестирование:
1) Включает сценарии с различными входными данными: пустой массив, отсортированные данные, обратный порядок, случайные значения и массив с одинаковыми элементами.
2) Проверка корректности работы алгоритмов и соответствия выходных данных ожиданиям.

2024-12-06 09:31 UTC, StroganovM reviewed
Add a test for checking a zero-length array to the mpi version of your program.

2024-12-06 11:08 UTC, Kvoks requested changes
Good job, but the seq version of your program does not check for an array filled with real values. Add a test.

2024-12-06 12:56 UTC, Kvoks approved these changes

2024-12-06 13:00 UTC, StroganovM approved these changes

2024-12-09 04:09 UTC, aobolensk requested changes

2024-12-09 05:53 UTC, ChastovSlava commented on tasks/mpi/chastov_v_bubble_sort/perf_tests/main.cpp
> +  const size_t count_size_vector = 120;
fixed

2024-12-09 20:54 UTC, aobolensk approved these changes

2024-12-15 19:30 UTC, allnes approved these changes

2024-12-15 19:30 UTC, merged