Белов Артём. Задача 2. Вариант 23. Итеративные методы (Зейделя).
learning-process/ppc-2024-autumn pull request #442
Opened 2024-12-05 21:03 UTC by belovtut

**Описание последовательной реализации:**
Последовательная реализация итеративного метода Зейделя предназначена для решения систем линейных алгебраических уравнений (СЛАУ) вида **𝐴𝑥 = 𝑏**. 
Исходная матрица **𝐴** размером **n×n** и вектор свободных членов **𝑏** считываются из входных данных, а начальное приближение **𝑥<sup>(0)</sup>** задаётся как вектор, содержащий **n** нулей.
Для обеспечения сходимости метода Зейделя проверяется наличие диагональной доминантности матрицы **𝐴**. Для того чтобы матрица была диагонально доминирующей, абсолютное значение каждого элемента на главной диагонали 
**𝑎<sub>𝑖𝑖</sub>** в строке **𝑖** должно быть больше или равно сумме модулей всех остальных элементов в этой строке.
На каждой итерации вычисляется новое приближение **𝑥<sup>(𝑘+1)</sup>** на основе предыдущего **𝑥<sup>(𝑘)</sup>**. 
Нормы разности приближений вычисляются для оценки точности. Итерации продолжаются, пока разность между приближениями не станет меньше заданного значения **𝜖** (epsilon), после чего решение записывается в выходной массив.

**Описание MPI реализации:**
MPI версия метода Зейделя предназначена для распараллеливания вычислений внутри одной итерации. Root-процесс
считывает данные (матрицу **𝐴**, вектор **𝑏**, точность **𝜖**) и распределяет их между процессами.
Каждому процессу передаются только столбцы матрицы **𝐴**, которые он обрабатывает, каждый процесс вычисляет частичную сумму для своих элементов **𝑥[𝑖]** на текущей итерации, после чего частичные суммы собираются в главный процесс операцией `reduce`.
После обновления **𝑥[𝑖]** на главном процессе новые значения рассылаются остальным процессам с помощью `broadcast`.
Вычисления повторяются до достижения заданной точности, после чего корневой процесс собирает и сохраняет окончательное решение.

2024-12-05 22:04 UTC, sanya2905 requested changes

2024-12-05 22:04 UTC, sanya2905 commented on tasks/mpi/belov_a_gauss_seidel_iter_method/include/ops_mpi.hpp
> +std::vector<double> generateFreeMembers(int n);
If you use generative functions only in test modules, move them there

2024-12-06 00:12 UTC, belovtut commented on tasks/mpi/belov_a_gauss_seidel_iter_method/include/ops_mpi.hpp
> +std::vector<double> generateFreeMembers(int n);
moved, thank you!

2024-12-06 09:41 UTC, sanya2905 approved these changes

2024-12-06 18:04 UTC, hasanyanovk commented on tasks/seq/belov_a_gauss_seidel_iter_method/src/ops_seq.cpp
> +  if (!isDiagonallyDominant()) return false;
This call should be in `validation`

2024-12-08 00:46 UTC, belovtut commented on tasks/seq/belov_a_gauss_seidel_iter_method/src/ops_seq.cpp
> +  if (!isDiagonallyDominant()) return false;
agree, fixed :)

2024-12-08 13:29 UTC, hasanyanovk approved these changes

2024-12-09 04:15 UTC, aobolensk requested changes

2024-12-09 04:15 UTC, aobolensk commented on .gitignore
> +out
Please, do not modify common files

2024-12-09 04:15 UTC, aobolensk commented on tasks/seq/belov_a_gauss_seidel_iter_method/perf_tests/main.cpp
> +std::vector<double> generateDiagonallyDominantMatrix(int n) {
Either make it static or wrap with namespace

2024-12-09 07:04 UTC, belovtut commented on .gitignore
> +out
got it, they're reverted

2024-12-09 10:31 UTC, belovtut commented on tasks/seq/belov_a_gauss_seidel_iter_method/perf_tests/main.cpp
> +std::vector<double> generateDiagonallyDominantMatrix(int n) {
done

2024-12-09 20:54 UTC, aobolensk approved these changes

2024-12-15 19:31 UTC, allnes approved these changes

2024-12-15 19:31 UTC, merged