Гордеева Таисия. Задача 2. Вариант 4. Спящий брадобрей
learning-process/ppc-2024-autumn pull request #443
Opened 2024-12-05 21:52 UTC by TayaGordeeva

Задача о спящем брадобрее — это классическая задача параллельного программирования, которая используется для иллюстрации проблем синхронизации потоков и обработки конкурирующих запросов.

Процесс с рангом 0 — барбер, который обслуживает клиентов. Он принимает клиентов, если свободен, и выполняет "стрижку"

Процесс с рангом 1 - диспетчер, который проверяет, есть ли место в очереди, и решает, принимать ли следующего клиента или отправить его обратно.

Клиенты (процессы с рангами отличными от 0  и 1) пытаются попасть в очередь на обслуживание, "приходя" к диспетчеру. Если места есть, они добавляются в очередь, если нет — отправляются обратно.

Программа моделирует работу "спящего брадобрея", где клиенты могут ожидать своей очереди, а парикмахер обслуживает их по очереди, когда они приходят.

2024-12-06 08:17 UTC, SergeyBoRss commented on tasks/mpi/gordeeva_t_sleeping_barber/src/ops_mpi.cpp
> +      std::cout << "LAST: " << remaining_clients << std::endl;
Extra output

2024-12-06 08:17 UTC, SergeyBoRss commented on tasks/mpi/gordeeva_t_sleeping_barber/src/ops_mpi.cpp
> +#include <algorithm>
Extra include

2024-12-06 08:17 UTC, SergeyBoRss commented on tasks/mpi/gordeeva_t_sleeping_barber/src/ops_mpi.cpp
> +#include <random>
Extra include

2024-12-06 08:17 UTC, SergeyBoRss commented on tasks/mpi/gordeeva_t_sleeping_barber/src/ops_mpi.cpp
> +#include <vector>
Extra include

2024-12-06 08:17 UTC, SergeyBoRss commented on tasks/mpi/gordeeva_t_sleeping_barber/func_tests/main.cpp
> +#include <boost/mpi/environment.hpp>
Extra include

2024-12-06 09:33 UTC, TayaGordeeva commented on tasks/mpi/gordeeva_t_sleeping_barber/src/ops_mpi.cpp
> +      std::cout << "LAST: " << remaining_clients << std::endl;
deleted

2024-12-06 09:34 UTC, TayaGordeeva commented on tasks/mpi/gordeeva_t_sleeping_barber/src/ops_mpi.cpp
> +#include <algorithm>
deleted

2024-12-06 09:34 UTC, TayaGordeeva commented on tasks/mpi/gordeeva_t_sleeping_barber/src/ops_mpi.cpp
> +#include <random>
fixed

2024-12-06 09:34 UTC, TayaGordeeva commented on tasks/mpi/gordeeva_t_sleeping_barber/src/ops_mpi.cpp
> +#include <vector>
deleted

2024-12-06 09:34 UTC, TayaGordeeva commented on tasks/mpi/gordeeva_t_sleeping_barber/func_tests/main.cpp
> +#include <boost/mpi/environment.hpp>
fixed

2024-12-06 09:50 UTC, SergeyBoRss approved these changes

2024-12-06 13:14 UTC, maximchhek commented on tasks/mpi/gordeeva_t_sleeping_barber/include/ops_mpi.hpp
> +  int max_waiting_chairs;
Add {} after name

2024-12-06 13:14 UTC, maximchhek commented on tasks/mpi/gordeeva_t_sleeping_barber/include/ops_mpi.hpp
> +  int result;
Add {} after name

2024-12-06 13:14 UTC, maximchhek commented on tasks/mpi/gordeeva_t_sleeping_barber/perf_tests/main.cpp
> +  // Create TaskData
Delete all comments

2024-12-06 15:57 UTC, TayaGordeeva commented on tasks/mpi/gordeeva_t_sleeping_barber/include/ops_mpi.hpp
> +  int max_waiting_chairs;
done

2024-12-06 15:57 UTC, TayaGordeeva commented on tasks/mpi/gordeeva_t_sleeping_barber/include/ops_mpi.hpp
> +  int result;
done

2024-12-06 15:58 UTC, TayaGordeeva commented on tasks/mpi/gordeeva_t_sleeping_barber/perf_tests/main.cpp
> +  // Create TaskData
fixed

2024-12-06 16:00 UTC, maximchhek approved these changes

2024-12-09 04:16 UTC, aobolensk requested changes
Please, increase code coverage

2024-12-09 04:16 UTC, aobolensk commented on tasks/mpi/gordeeva_t_sleeping_barber/src/ops_mpi.cpp
> +      std::cout << "[BARBER] All clients served. Stopping." << std::endl;
Not all extra output was removed

2024-12-09 04:16 UTC, aobolensk commented on tasks/mpi/gordeeva_t_sleeping_barber/src/ops_mpi.cpp
> +      world.recv(0, 4, barber_signal);
use isend/irecv

2024-12-09 04:17 UTC, aobolensk commented
Two reviews above are invalid, please request 2 more

2024-12-09 05:12 UTC, TayaGordeeva commented on tasks/mpi/gordeeva_t_sleeping_barber/src/ops_mpi.cpp
> +      std::cout << "[BARBER] All clients served. Stopping." << std::endl;
![2024-12-09_08-02-19](https://github.com/user-attachments/assets/6291c99f-24c2-49db-934a-726e00764e22)

This is not extra output. When you run the program in the console, you will notice that all the outputs are needed. Moreover, the correct operation of my program is checked through the correct sequence of outputs

2024-12-09 05:14 UTC, TayaGordeeva commented on tasks/mpi/gordeeva_t_sleeping_barber/src/ops_mpi.cpp
> +      world.recv(0, 4, barber_signal);
But we only learned this last Friday... Moreover, the program does not work with isend and irecv

2024-12-09 16:55 UTC, aobolensk commented on tasks/mpi/gordeeva_t_sleeping_barber/src/ops_mpi.cpp
> +      world.recv(0, 4, barber_signal);
> we only learned this last Friday

Actually, it was mentioned before the last Friday and review is needed to find such mistakes 

> the program does not work with isend and irecv

If it does not work then the algorithm is not correct

2024-12-09 22:14 UTC, TayaGordeeva commented on tasks/mpi/gordeeva_t_sleeping_barber/src/ops_mpi.cpp
> +      std::cout << "[BARBER] All clients served. Stopping." << std::endl;
deleted outputs

2024-12-09 22:15 UTC, TayaGordeeva commented on tasks/mpi/gordeeva_t_sleeping_barber/src/ops_mpi.cpp
> +      world.recv(0, 4, barber_signal);
fixed, now instead of send and recv i use isend and irecv

2024-12-09 22:21 UTC, Applejack2004 requested changes

2024-12-09 22:21 UTC, Applejack2004 commented on tasks/mpi/gordeeva_t_sleeping_barber/src/ops_mpi.cpp
> +  if (accepted) {
Rewrite the if statement; the if/else block contains a repeated line which can be factored out of the conditional.

2024-12-09 22:22 UTC, Vav1L0N commented on tasks/mpi/gordeeva_t_sleeping_barber/src/ops_mpi.cpp
> +#include <string>
Extra include

2024-12-09 22:35 UTC, TayaGordeeva commented on tasks/mpi/gordeeva_t_sleeping_barber/src/ops_mpi.cpp
> +  if (accepted) {
fixed

2024-12-09 22:35 UTC, TayaGordeeva commented on tasks/mpi/gordeeva_t_sleeping_barber/src/ops_mpi.cpp
> +#include <string>
deleted

2024-12-09 22:36 UTC, Applejack2004 approved these changes

2024-12-09 22:41 UTC, Vav1L0N approved these changes

2024-12-11 19:18 UTC, aobolensk approved these changes

2024-12-15 19:34 UTC, allnes approved these changes

2024-12-15 19:34 UTC, merged