Мурадов Майк. Задача 2. Вариант 5. Методы передачи сообщений "Передача от одного всем (broadcast)"
learning-process/ppc-2024-autumn pull request #444
Opened 2024-12-06 00:11 UTC by MikeMuradov

Этот алгоритм реализует широковещательную передачу (**broadcast**) на основе биномиального дерева. Основная идея в том, что данные передаются по уровням, где каждый процесс либо отправляет, либо получает данные на определённом шаге. 

Для работы используется относительный ранг процессов относительно корня, чтобы упростить вычисления. Передача контролируется через двоичную маску, которая удваивается на каждом шаге, пока данные не дойдут до всех процессов. 

Всё построено на стандартных отправках и приёмах (`send` и `recv`) из Boost.MPI, что обеспечивает универсальность и поддержку любых типов данных благодаря шаблону. Этот подход даёт равномерное распределение нагрузки между процессами и минимизирует количество коммуникаций.

2024-12-06 12:12 UTC, venn2713 requested changes
Я бы попросил добавить в тесты функционал для проверки отправки не из 0 процесса всем остальным

2024-12-06 12:44 UTC, kavtorevd requested changes

2024-12-06 12:44 UTC, kavtorevd commented on tasks/mpi/muradov_m_broadcast/func_tests/main.cpp
Add an element of randomness, for example a test in which source is chosen randomly between 0 and world.size() - 1

2024-12-06 12:57 UTC, MikeMuradov commented on tasks/mpi/muradov_m_broadcast/func_tests/main.cpp
apply this

2024-12-06 14:15 UTC, kavtorevd approved these changes
Nice job!

2024-12-07 10:03 UTC, venn2713 approved these changes

2024-12-08 22:35 UTC, venn2713 commented
Вас пока что не проверили, но совет, вам нужно добавить ещё perf tests это обязательно, придумайте чтонибудь с передачей большого вектора)

2024-12-09 04:20 UTC, aobolensk requested changes
What task is being solved using your custom broadcast?

2024-12-09 04:20 UTC, aobolensk commented on tasks/mpi/muradov_m_broadcast/func_tests/main.cpp
> +TEST(muradov_m_broadcast_mpi, data_size_1) { muradov_m_broadcast_mpi::test_template_rundom(1); }
Please, check on 0

2024-12-09 04:20 UTC, aobolensk commented on tasks/mpi/muradov_m_broadcast/perf_tests/main.cpp
> +  }
Barely possible situation if you explicitly specify source == 0

2024-12-09 10:44 UTC, MikeMuradov commented
@aobolensk, I don't quite understand. My broadcast performs the task of distributing data across streams... Do I need to take another someone else’s problem and solve it? How to understand which one? Or can I take someone from the master or example?

2024-12-09 21:01 UTC, aobolensk commented
> What task is being solved using your custom broadcast?

To clarify, the idea of the tasks with data transfer: come up with a real task and solve it with your broadcast and original broadcast, comparing performance

2024-12-10 15:23 UTC, MikeMuradov commented
### Perf tests results
I made changes and drew graphs in Python, I attach them here:
---
![mediana](https://github.com/user-attachments/assets/97a08805-9a5a-43ed-8ea2-45d5a9fbddd9)
![4proc](https://github.com/user-attachments/assets/cad9cf8f-d580-43cb-8d13-23b934931724)
![8proc](https://github.com/user-attachments/assets/afdd3dc8-0afa-446a-92ef-4037b6295ba7)
![16proc](https://github.com/user-attachments/assets/7a60bb8e-8e10-4934-b27e-d713e5ccccce)
![32proc](https://github.com/user-attachments/assets/b9437f8b-cbd2-4ce6-85ec-a3d04d9d82e2)

2024-12-10 17:16 UTC, MikeMuradov commented
@aobolensk, I did as you said

2024-12-11 19:32 UTC, aobolensk approved these changes

2024-12-15 19:32 UTC, allnes approved these changes

2024-12-15 19:33 UTC, merged