Велиев Эльвин. Задача 2. Вариант 22. Итеративные методы (Якоби)
learning-process/ppc-2024-autumn pull request #445
Opened 2024-12-06 01:29 UTC by ev1ven

В процессе...

2024-12-09 17:15 UTC, Sedova-Olga commented on tasks/mpi/veliev_e_jacobi_method/src/ops_mpi.cpp
> +    for (int j = 0; j < n; ++j) temp[i][j] = matrix[i * n + j];
В методе используется вложенный цикл для копирования данных из matrix в temp. Можно уменьшить вложенность и повысить читаемость кода используя стандартный алгоритм std::copy или конструктор std::vector.

2024-12-09 20:05 UTC, qfrff approved these changes

2024-12-09 20:05 UTC, ev1ven commented on tasks/mpi/veliev_e_jacobi_method/src/ops_mpi.cpp
> +    for (int j = 0; j < n; ++j) temp[i][j] = matrix[i * n + j];
fixed

2024-12-09 20:06 UTC, ev1ven commented on tasks/mpi/veliev_e_jacobi_method/src/ops_mpi.cpp
> +  int size = world.size();
fixed

2024-12-09 20:22 UTC, Sedova-Olga requested changes

2024-12-09 20:22 UTC, Sedova-Olga commented on tasks/mpi/veliev_e_jacobi_method/func_tests/main.cpp
> +    ASSERT_EQ(seqTask.validation(), true);
используйте assert_true

2024-12-09 20:22 UTC, Sedova-Olga commented on tasks/mpi/veliev_e_jacobi_method/func_tests/main.cpp
> +  ASSERT_EQ(mpiTask.validation(), true);
используйте assert_true

2024-12-09 20:22 UTC, Sedova-Olga commented on tasks/mpi/veliev_e_jacobi_method/func_tests/main.cpp
> +    ASSERT_EQ(mpiTask.validation(), false);
используйте assert_false

2024-12-09 20:22 UTC, Sedova-Olga commented on tasks/mpi/veliev_e_jacobi_method/func_tests/main.cpp
используйте assert_true или assert_false

2024-12-09 20:28 UTC, Sedova-Olga requested changes

2024-12-09 20:28 UTC, Sedova-Olga commented on tasks/seq/veliev_e_jacobi_method/func_tests/main.cpp
аналогично как и с mpi

2024-12-09 22:58 UTC, Sedova-Olga approved these changes

2024-12-09 23:28 UTC, ev1ven commented on tasks/seq/veliev_e_jacobi_method/func_tests/main.cpp
fixed

2024-12-10 03:22 UTC, aobolensk approved these changes

2024-12-15 19:35 UTC, allnes approved these changes

2024-12-15 19:35 UTC, merged