Владимирова Юлия. Задача 2. Вариант 9. Обобщенная передача от всех одному (gather)
learning-process/ppc-2024-autumn pull request #446
Opened 2024-12-06 09:07 UTC by VlJulia

**Задача:**
Дана последовательность действий в виде вектора, где значение 1 -повернуть направо, -1 - повернуть налево, 2 -шаг вперед. Необходимо убрать тупики. 
_Алгоритм решения_ : Для решения задачи взят алгоритм избегания тупиков для пути, построенного путем прохождения лабиринта правилом правой руки.
**Gather:**
Каждый процесс получает по кусочку пути, убирает там все маленькие тупики, потом с помошью gather передает результат по дереву наверх (родительском узлу). Если узел является родительским, то после окончания работы с своим отрезком данных, он ждет результаты дочерних, сливает всю информацию вместе, и передает выше. Также использован уже существующий gather для сравнения.  
В конце главный процесс еще раз проходится по получившемуся пути, чтоб удалить тупики, которые могли образоваться из неудачного деления вектора.
_Тесты_
Есть тесты с заранее высчитанными значениемя, где проверяется правильность пути в ответе, а также есть тесты с рандомным путем, где проверяется меньше ли длина полученного пути ожидаемого значения. Ожидаемое значение формируется во время создания случайного пути, пучем исключения из счета длины добавляемых тупиков.

2024-12-06 10:51 UTC, ChernovaNatalya requested changes

2024-12-06 10:51 UTC, ChernovaNatalya commented on tasks/mpi/vladimirova_j_gather/src/ops_mpi.cpp
> +  return taskData->outputs_count[0] == 1;
Add a check that the vector is not empty.

2024-12-06 11:48 UTC, VasenkovAA commented on tasks/seq/vladimirova_j_gather/src/ops_seq.cpp
> +        if (((size_t)i < 0) || (!(j < way.size()))) {
каст к беззаконному типу чтобы сравнить с нулем?

2024-12-06 11:48 UTC, VasenkovAA commented on tasks/seq/vladimirova_j_gather/src/ops_seq.cpp
> +  while (j <= way.size()) {
почему <=? может просто <

2024-12-06 11:48 UTC, VasenkovAA commented on tasks/seq/vladimirova_j_gather/src/ops_seq.cpp
> +  return taskData->outputs_count[0] == 1;
надо бы проверить что данные подходят, например не нулевой вектор

2024-12-06 11:48 UTC, VasenkovAA commented on tasks/mpi/vladimirova_j_gather/src/ops_mpi.cpp
> +  int r = world.rank();
Может назвать переменную более читабельно, например `rank`?

2024-12-06 18:26 UTC, VlJulia commented on tasks/mpi/vladimirova_j_gather/src/ops_mpi.cpp
> +  return taskData->outputs_count[0] == 1;
fixed

2024-12-06 18:26 UTC, VlJulia commented on tasks/seq/vladimirova_j_gather/src/ops_seq.cpp
> +  while (j <= way.size()) {
fixed

2024-12-06 18:26 UTC, VlJulia commented on tasks/seq/vladimirova_j_gather/src/ops_seq.cpp
> +  return taskData->outputs_count[0] == 1;
fixed

2024-12-06 18:26 UTC, VlJulia commented on tasks/mpi/vladimirova_j_gather/src/ops_mpi.cpp
> +  int r = world.rank();
fixed

2024-12-06 18:27 UTC, ChernovaNatalya approved these changes

2024-12-07 20:30 UTC, VasenkovAA approved these changes

2024-12-09 16:52 UTC, aobolensk requested changes

2024-12-09 20:55 UTC, VlJulia commented on tasks/seq/vladimirova_j_gather/func_tests/main.cpp
> +std::vector<int> getRandomVal1(int sz) {
fixed, but they are in the test files (as indicated in the comments of work №1)

2024-12-09 21:04 UTC, aobolensk approved these changes

2024-12-15 19:37 UTC, allnes approved these changes

2024-12-15 19:37 UTC, merged