Агафеев Сергей. Задача 1. Вариант 13. Максимальное значение элементов матрицы
learning-process/ppc-2024-autumn pull request #448
Opened 2024-12-06 13:37 UTC by GrayPirat

Описание последовательной реализации:
Матрица представлена в виде вектора, алгоритм последовательно проходит вектор и находит максимум

Описание параллельной реализации:
Матрица (представленная в виде вектора) разбивается на равные части, каждая из которых отдается своему процессу. Процесс, находит максимум в своем куске, после чего с помощью reduce определяется глобальный максимум (максимум из всех максимумов)

2024-12-06 14:21 UTC, GrayPirat commented
Closed until fixing build troubles

2024-12-09 11:30 UTC, ascannel requested changes

2024-12-09 11:30 UTC, ascannel commented on tasks/mpi/agafeev_s_max_of_vector_elements/func_tests/main.cpp
> +#include <vector>
remove unnecessary includes

2024-12-09 11:30 UTC, ascannel commented on tasks/mpi/agafeev_s_max_of_vector_elements/func_tests/main.cpp
> +TEST(agafeev_s_max_of_vector_elements, test_find_in_3x3_matrix) {
add more tests with different martix sizes, also at least one test for validation

2024-12-09 11:30 UTC, ascannel commented on tasks/mpi/agafeev_s_max_of_vector_elements/src/ops_mpi.cpp
> +bool MaxMatrixSeq<T>::validation() {
i suggest to expand your validation section to check if matrix is even presented

2024-12-09 11:30 UTC, ascannel commented on tasks/mpi/agafeev_s_max_of_vector_elements/include/ops_mpi.hpp
> +}
move it to test files

2024-12-09 11:30 UTC, ascannel commented on tasks/mpi/agafeev_s_max_of_vector_elements/include/ops_mpi.hpp
> +}
move it to cpp files

2024-12-09 11:30 UTC, ascannel commented on tasks/mpi/agafeev_s_max_of_vector_elements/perf_tests/main.cpp
> +  std::vector<int> in_matrix = agafeev_s_max_of_vector_elements_mpi::create_RandomMatrix<int>(n, m);
create one matrix for both tests outside the test code

2024-12-09 14:40 UTC, Torcna requested changes

2024-12-09 14:40 UTC, Torcna commented on tasks/mpi/agafeev_s_max_of_vector_elements/func_tests/main.cpp
> +  // world.barrier();
remove barriers

2024-12-09 14:40 UTC, Torcna commented on tasks/mpi/agafeev_s_max_of_vector_elements/func_tests/main.cpp
> +  testTask->post_processing();
here too

2024-12-09 14:40 UTC, Torcna commented on tasks/mpi/agafeev_s_max_of_vector_elements/perf_tests/main.cpp
> +  // Create Perf attributes
Is there any use for testTask?
i doubt that, `cause in the next line u create a testTaskMpi.

2024-12-09 14:40 UTC, Torcna commented on tasks/mpi/agafeev_s_max_of_vector_elements/perf_tests/main.cpp
> +  auto testTaskMpi = std::make_shared<agafeev_s_max_of_vector_elements_mpi::MaxMatrixMpi<int>>(taskData);
and also here

2024-12-09 14:40 UTC, Torcna commented on tasks/mpi/agafeev_s_max_of_vector_elements/src/ops_mpi.cpp
> +    }*/
remove this debugging info

2024-12-09 14:40 UTC, Torcna commented on tasks/mpi/agafeev_s_max_of_vector_elements/src/ops_mpi.cpp
> +  // std::cout << std::endl;
and in general clean up your code from comments, please!

2024-12-09 20:55 UTC, GrayPirat commented on tasks/mpi/agafeev_s_max_of_vector_elements/include/ops_mpi.hpp
> +}
I tried to do this in previous versions, but there were problems with the build

2024-12-10 04:18 UTC, GrayPirat commented on tasks/mpi/agafeev_s_max_of_vector_elements/include/ops_mpi.hpp
> +}
After some thinking it finally worked

2024-12-10 20:10 UTC, ascannel approved these changes

2024-12-11 09:40 UTC, Torcna approved these changes

2024-12-11 19:33 UTC, aobolensk commented on tasks/mpi/agafeev_s_max_of_vector_elements/func_tests/main.cpp
> +std::vector<T> create_RandomMatrix(int row_size, int column_size) {
Please, either make it static or wrap with the namespace

2024-12-11 19:34 UTC, aobolensk commented on tasks/mpi/agafeev_s_max_of_vector_elements/perf_tests/main.cpp
> +  for (unsigned int i = 0; i < matrix.size(); ++i) matrix[i] = rand_gen() % 100;
Please, add negative numbers tests

2024-12-11 19:34 UTC, aobolensk commented on tasks/mpi/agafeev_s_max_of_vector_elements/perf_tests/main.cpp
> +  const int m = 1000;
Please, increase perf test size

2024-12-13 03:20 UTC, aobolensk approved these changes

2024-12-15 19:38 UTC, allnes approved these changes

2024-12-15 19:38 UTC, merged