Варфоломеев Григорий. Задача 2. Вариант 8. Обобщенная передача от одного всем (scatter)
learning-process/ppc-2024-autumn pull request #449
Opened 2024-12-06 15:24 UTC by petr1core

В процессе выполнения задачи был реализован класс с пользовательской функцией рассылки данных (`scatter`) а также его шаблонная версия, реализующая двоичное дерево процессов, поддерживающая типы `MPI_INT`, `MPI_FLOAT`, `MPI_DOUBLE`. Целью было распределить данные от корневого процесса к другим процессам, каждый из которых выполняет вычисления с использованием операций `+`, `-`, и `max` на своей части данных. Процессы организованы в виде двоичного дерева, что позволяет эффективно распределять и обрабатывать данные.
Для организации вычислений в виде двоичного дерева каждый процесс определяет свой уровень в дереве, своего родителя и детей (левый и правый), минимальный элемент, присутствующий на его уровне и общее количество элементов его уровня. 
В ходе работы данные разделяются между потомками, вычисляется локальный результат как на нулевом процессе,(который также оставляет за собой право взять часть данных для вычисления) так и на остальных процессах. Корневой процесс собирает промежуточные результаты в вектор результатов, после чего производит вычисление глобального результата (суммы/разности/максимума).

2024-12-07 09:55 UTC, KAPUSHA228 requested changes

2024-12-07 09:55 UTC, KAPUSHA228 commented on tasks/mpi/varfolomeev_g_transfer_from_one_to_all_scatter/src/ops_mpi.cpp
> +    if (ops == "+") {
как по мне бессмысленная конструкция if-else, переделать, а ещё излишнее количество include в файлах, рекомендую почистить

2024-12-07 09:55 UTC, KAPUSHA228 commented on tasks/mpi/varfolomeev_g_transfer_from_one_to_all_scatter/src/ops_mpi.cpp
> +  std::vector<int> vec(sz);
Повысь покрытие: добавь тесты на проверку генератора, на проверку неправильной операции ops

2024-12-07 11:58 UTC, petr1core commented on tasks/mpi/varfolomeev_g_transfer_from_one_to_all_scatter/src/ops_mpi.cpp
> +    if (ops == "+") {
Well done

2024-12-07 14:04 UTC, andrewmeow requested changes

2024-12-07 14:04 UTC, andrewmeow commented on tasks/mpi/varfolomeev_g_transfer_from_one_to_all_scatter/include/ops_mpi.hpp
> +class MyScatterTestMPITaskParallel : public ppc::core::Task {
Move your custom realisation in different directory because you need testing your version of scatter in perf tests

2024-12-07 16:35 UTC, petr1core commented on tasks/mpi/varfolomeev_g_transfer_from_one_to_all_scatter/include/ops_mpi.hpp
> +class MyScatterTestMPITaskParallel : public ppc::core::Task {
Moved

2024-12-07 16:38 UTC, KAPUSHA228 approved these changes

2024-12-07 16:38 UTC, andrewmeow approved these changes

2024-12-09 06:18 UTC, aobolensk requested changes
Code coverage is still too low

2024-12-10 03:43 UTC, aobolensk requested changes

2024-12-10 03:43 UTC, aobolensk commented on tasks/mpi/varfolomeev_g_transfer_from_one_to_all_scatter/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz, int a, int b);
Please, move test function to the test module

2024-12-10 12:25 UTC, petr1core commented on tasks/mpi/varfolomeev_g_transfer_from_one_to_all_scatter/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz, int a, int b);
Coverage fixed, and generator moved to tests, also added more tests

2024-12-11 19:39 UTC, aobolensk requested changes

2024-12-11 19:39 UTC, aobolensk commented on tasks/mpi/varfolomeev_g_transfer_from_one_to_all_scatter/func_tests/main.cpp
> +std::vector<int> getRandomVector_(int sz, int a, int b) {  // [a, b]
Please, either make it static or wrap with namespace

2024-12-11 20:20 UTC, petr1core commented on tasks/mpi/varfolomeev_g_transfer_from_one_to_all_scatter/func_tests/main.cpp
> +std::vector<int> getRandomVector_(int sz, int a, int b) {  // [a, b]
Thank you, I made this static

2024-12-13 03:21 UTC, aobolensk approved these changes

2024-12-15 19:39 UTC, allnes approved these changes

2024-12-15 19:39 UTC, merged