Золотарева Арина. Задача 2. Вариант 26. Сглаживание изображения
learning-process/ppc-2024-autumn pull request #450
Opened 2024-12-06 19:57 UTC by andrewmeow

Обрабатывается изображение в виде массива пикселей в оттенках серого.
Алгоритм сглаживания - матричный фильтр по Гауссу. Фильтр Гаусса применяется к каждому пикселю изображения для вычисления его нового значения на основе весовых коэффициентов, которые определяются распределением Гаусса (матричное ядро). Этот фильтр вычисляет средневзвешенное значение яркостей в окрестности каждого пикселя (обычно это 3x3 матрица, включая сам пиксель), придавая больший вес пикселям, находящимся ближе к целевой позиции.

Seq (последовательная версия)
Алгоритм работает с изображением, представленным в виде одномерного массива, интерпретируемого как двумерный. 
Проход по массиву с применением фильтра к каждому пикселю.

MPI (параллельная версия)
Исходное изображение разбивается строки, которые распределяются между процессами.
Каждый процесс получает свою часть изображения, включая дополнительные строки границ, чтобы корректно обрабатывать края фрагментов. Каждый процесс применяет фильтр Гаусса к своей части, а затем передает данные корневому процессу. Главный процесс также обрабатывает свою часть, затем собирает все данные и складывает их в исходном порядке.

base height - количество строк разделенное на количество процессов.
remaining - остаток от деления. 

Количество строк, получаемые процессами определенных рангов:
0 процесс получает base height + remaining + 1 (граничащая строка снизу)
С 1 по n-1 процессы получают base height + 2 (граничащая строка сверху и снизу)
Последний n-й процесс получает base height +1 (граничащая строка сверху)

2024-12-08 00:29 UTC, KAPUSHA228 requested changes

2024-12-08 00:29 UTC, KAPUSHA228 commented on tasks/mpi/zolotareva_a_smoothing_image/src/ops_mpi.cpp
> +  std::vector<float> horizontal_kernel =
эффективнее будет вычисление ядра проводить на нулевом процессе и потом раздать через broadcast

2024-12-08 01:44 UTC, venn2713 requested changes

2024-12-08 01:44 UTC, venn2713 commented on tasks/mpi/zolotareva_a_smoothing_image/src/ops_mpi.cpp
> +  }
Используй copy

2024-12-08 01:44 UTC, venn2713 commented on tasks/mpi/zolotareva_a_smoothing_image/src/ops_mpi.cpp
> +    }
Аналогично

2024-12-08 03:55 UTC, andrewmeow commented on tasks/mpi/zolotareva_a_smoothing_image/src/ops_mpi.cpp
> +  std::vector<float> horizontal_kernel =
done

2024-12-08 03:56 UTC, andrewmeow commented on tasks/mpi/zolotareva_a_smoothing_image/src/ops_mpi.cpp
> +  }
fixed

2024-12-08 03:56 UTC, andrewmeow commented on tasks/mpi/zolotareva_a_smoothing_image/src/ops_mpi.cpp
> +    }
Аналогично fixed

2024-12-08 13:32 UTC, KAPUSHA228 approved these changes

2024-12-08 13:45 UTC, venn2713 approved these changes

2024-12-10 03:45 UTC, aobolensk requested changes

2024-12-10 03:45 UTC, aobolensk commented on tasks/mpi/zolotareva_a_smoothing_image/func_tests/main.cpp
> +std::vector<uint8_t> generateRandomImage(int height, int width) {
Either make it static or move to the namespace

2024-12-10 03:45 UTC, aobolensk commented on tasks/mpi/zolotareva_a_smoothing_image/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, height_, 0);
Please, move data transfer to ::run() function

2024-12-10 19:05 UTC, andrewmeow commented on tasks/mpi/zolotareva_a_smoothing_image/func_tests/main.cpp
> +std::vector<uint8_t> generateRandomImage(int height, int width) {
its done

2024-12-10 19:05 UTC, andrewmeow commented on tasks/mpi/zolotareva_a_smoothing_image/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, height_, 0);
I did all, Can you check, please?

2024-12-11 19:47 UTC, aobolensk approved these changes

2024-12-15 19:46 UTC, allnes approved these changes

2024-12-15 19:46 UTC, merged