Allow sanitizers to be used with GCC
learning-process/ppc-2024-autumn pull request #452
Opened 2024-12-06 22:06 UTC by kmichaelk

2024-12-08 18:15 UTC, allnes approved these changes

2024-12-09 06:35 UTC, aobolensk requested changes
CI build with gcc compiler + sanitizer should be added in that case. Otherwise, change does not impact anything

2024-12-09 09:05 UTC, kmichaelk commented
I often run it with sanitisers locally, so I either switch compiler to clang either modify this file manually each time, otherwise there is no difference

2024-12-10 03:46 UTC, aobolensk commented
> I often run it with sanitisers locally, so I either switch compiler to clang from gcc either modify this file manually each time, otherwise there is no difference

Ok then, we will consider adding CI for that later. Please, also port it to the upstream repo

2024-12-10 03:46 UTC, aobolensk approved these changes

2024-12-10 03:46 UTC, merged