Петров Артём Андреевич/Задача2/Ленточная вертикальная схема
learning-process/ppc-2024-autumn pull request #453
Opened 2024-12-07 00:09 UTC by ArtemPch

Вертикальная схема ленты для умножения матрицы на вектор делит матрицу по столбцам (или, точнее, по блокам столбцов) и распределяет части вектора по каждому процессу. Этот подход особенно полезен, когда матрица разреженная или полосатая, что позволяет эффективно распараллеливать.

2024-12-07 09:16 UTC, LizochkaSpring commented on tasks/seq/petrov_a_ribbon_vertical_scheme/perf_tests/main.cpp
> +
Please add random filling of the matrix

2024-12-07 09:16 UTC, LizochkaSpring commented on tasks/seq/petrov_a_ribbon_vertical_scheme/perf_tests/main.cpp
> +
Please add random filling of the vector

2024-12-07 09:16 UTC, LizochkaSpring commented on tasks/mpi/petrov_a_ribbon_vertical_scheme/src/ops_mpi.cpp
> +#include <limits>
Delete unnecessary include

2024-12-07 09:55 UTC, ArtemPch commented on tasks/mpi/petrov_a_ribbon_vertical_scheme/src/ops_mpi.cpp
> +#include <limits>
i done

2024-12-07 09:55 UTC, ArtemPch commented on tasks/seq/petrov_a_ribbon_vertical_scheme/perf_tests/main.cpp
> +
i done

2024-12-07 09:55 UTC, ArtemPch commented on tasks/seq/petrov_a_ribbon_vertical_scheme/perf_tests/main.cpp
> +
i done

2024-12-07 16:36 UTC, LizochkaSpring approved these changes

2024-12-07 19:02 UTC, DZaytsev4 commented on tasks/mpi/petrov_a_ribbon_vertical_scheme/perf_tests/main.cpp
> +  int* displs = new int[size];
add std::vector here and for the next test

2024-12-07 20:27 UTC, ArtemPch commented on tasks/mpi/petrov_a_ribbon_vertical_scheme/perf_tests/main.cpp
> +  int* displs = new int[size];
i done

2024-12-07 20:29 UTC, DZaytsev4 approved these changes

2024-12-09 03:39 UTC, aobolensk requested changes

2024-12-09 03:39 UTC, aobolensk commented on tasks/mpi/petrov_a_ribbon_vertical_scheme/func_tests/main.cpp
> +  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
Why do you have MPI calls in the tests?

2024-12-09 03:39 UTC, aobolensk commented on tasks/mpi/petrov_a_ribbon_vertical_scheme/perf_tests/main.cpp
> +  const int rows = 1000;
Please, increase data size for perf tests

2024-12-09 03:39 UTC, aobolensk commented on tasks/mpi/petrov_a_ribbon_vertical_scheme/src/ops_mpi.cpp
> +  MPI_Bcast(&cols, 1, MPI_INT, 0, MPI_COMM_WORLD);
Please, move data transfers to ::run() function

2024-12-09 15:15 UTC, ArtemPch commented on tasks/mpi/petrov_a_ribbon_vertical_scheme/func_tests/main.cpp
> +  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
Cтрока 12 определяет ранг текущего процесса рамках коммуникатора.
Так же:

MPI_COMM_WORLD - Это предопределённый коммуникатор, который включает все процессы, запущенные текущей MPI-программой.

&rank - Указатель на переменную

Цель - распределение работы т.к. каждая задача запускается на нескольких процессах

2024-12-09 19:25 UTC, ArtemPch commented on tasks/mpi/petrov_a_ribbon_vertical_scheme/src/ops_mpi.cpp
> +  MPI_Bcast(&cols, 1, MPI_INT, 0, MPI_COMM_WORLD);
done

2024-12-09 19:25 UTC, ArtemPch commented on tasks/mpi/petrov_a_ribbon_vertical_scheme/perf_tests/main.cpp
> +  const int rows = 1000;
done

2024-12-10 03:47 UTC, aobolensk commented on tasks/mpi/petrov_a_ribbon_vertical_scheme/func_tests/main.cpp
> +  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
I understand, but why do you have them in tests, not in the implementation?

2024-12-11 19:48 UTC, aobolensk commented on tasks/mpi/petrov_a_ribbon_vertical_scheme/func_tests/main.cpp
> +  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
Please, reply

2024-12-11 19:48 UTC, aobolensk requested changes

2024-12-11 19:48 UTC, aobolensk commented on tasks/mpi/petrov_a_ribbon_vertical_scheme/perf_tests/main.cpp
> +TEST(petrov_a_ribbon_vertical_scheme_mpi, test_task) {
Please, fix perf test names according to the convention

2024-12-12 07:29 UTC, ArtemPch commented on tasks/mpi/petrov_a_ribbon_vertical_scheme/func_tests/main.cpp
> +  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
I understood your question, and sorry for the late reply, I tried to remove the implementation from the tests, but it takes longer than I initially thought.
Now about the question - I added mpi calls to the tests, so I worked on the task separately from the implementation "roughly speaking". In terms of test execution time, everything was fine and I thought this idea was good.

2024-12-12 08:09 UTC, ArtemPch commented on tasks/mpi/petrov_a_ribbon_vertical_scheme/perf_tests/main.cpp
> +TEST(petrov_a_ribbon_vertical_scheme_mpi, test_task) {
done

2024-12-14 19:29 UTC, ArtemPch commented on tasks/mpi/petrov_a_ribbon_vertical_scheme/func_tests/main.cpp
> +  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
Please, reply

2024-12-15 14:19 UTC, aobolensk commented on tasks/mpi/petrov_a_ribbon_vertical_scheme/func_tests/main.cpp
> +  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
If you perfer to leve this is as is, solution score will not be full + efficiency will be 0, because in this case it is impossible to measure algorithm performance using this framework.

2024-12-15 15:33 UTC, ArtemPch commented on tasks/mpi/petrov_a_ribbon_vertical_scheme/func_tests/main.cpp
> +  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
I want to complete this task and move on to a new one.

2024-12-18 14:40 UTC, aobolensk approved these changes

2024-12-20 14:45 UTC, allnes approved these changes

2024-12-20 14:45 UTC, merged