Харин Матвей. Задача 3. Вариант 20. Поразрядная сортировка для вещественных чисел (тип double) с простым слиянием.
learning-process/ppc-2024-autumn pull request #455
Opened 2024-12-07 01:32 UTC by mateusxap

2024-12-15 00:15 UTC, Chiks37 commented on tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, SimpleData) {
1) Change "MPI" to "seq"
2) Align perf test names with naming convention

2024-12-15 00:15 UTC, Chiks37 commented on tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, ValidationFailureTestSize) {
1) Change "MPI" to "seq"
2) Align perf test names with naming convention

2024-12-15 00:15 UTC, Chiks37 commented on tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, RandomDataSmall) {
1) Change "MPI" to "seq"
2) Align perf test names with naming convention

2024-12-15 00:16 UTC, Chiks37 commented on tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, RandomDataLarge) {
1) Change "MPI" to "seq"
2) Align perf test names with naming convention

2024-12-15 00:16 UTC, Chiks37 commented on tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, AlreadySortedData) {
1) Change "MPI" to "seq"
2) Align perf test names with naming convention

2024-12-15 00:16 UTC, Chiks37 commented on tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, ReverseSortedData) {
1) Change "MPI" to "seq"
2) Align perf test names with naming convention

2024-12-15 00:17 UTC, Chiks37 commented on tasks/seq/kharin_m_radix_double_sort/perf_tests/main.cpp
> +TEST(RadixSort_Sequential_PerfTest, test_pipeline_run) {
Align perf test names with naming convention

2024-12-15 00:18 UTC, Chiks37 commented on tasks/seq/kharin_m_radix_double_sort/perf_tests/main.cpp
> +#include <cmath>
Delete unused lib

2024-12-15 00:18 UTC, Chiks37 commented on tasks/seq/kharin_m_radix_double_sort/perf_tests/main.cpp
> +TEST(RadixSort_Sequential_PerfTest, test_task_run) {
Align perf test names with naming convention

2024-12-15 00:19 UTC, Chiks37 commented on tasks/mpi/kharin_m_radix_double_sort/perf_tests/main.cpp
> +TEST(RadixSort_MPI_PerfTest, test_pipeline_run) {
Align perf test names with naming convention

2024-12-15 00:19 UTC, Chiks37 commented on tasks/mpi/kharin_m_radix_double_sort/perf_tests/main.cpp
> +TEST(RadixSort_MPI_PerfTest, test_task_run) {
Align perf test names with naming convention

2024-12-15 00:19 UTC, Chiks37 commented on tasks/mpi/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, SimpleData) {
Align perf test names with naming convention

2024-12-15 00:19 UTC, Chiks37 commented on tasks/mpi/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, ValidationFailureTestSize) {
Align perf test names with naming convention

2024-12-15 00:19 UTC, Chiks37 commented on tasks/mpi/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, RandomDataSmall) {
Align perf test names with naming convention

2024-12-15 00:19 UTC, Chiks37 commented on tasks/mpi/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, RandomDataLarge) {
Align perf test names with naming convention

2024-12-15 00:19 UTC, Chiks37 commented on tasks/mpi/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, AlreadySortedData) {
Align perf test names with naming convention

2024-12-15 00:20 UTC, Chiks37 commented on tasks/mpi/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, ReverseSortedData) {
Align perf test names with naming convention

2024-12-15 00:21 UTC, Chiks37 requested changes
Please, fix all notices, leaved by me

2024-12-15 20:05 UTC, mateusxap commented on tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, SimpleData) {
fixed

2024-12-15 20:06 UTC, mateusxap commented on tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, ValidationFailureTestSize) {
fixed

2024-12-15 20:06 UTC, mateusxap commented on tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, RandomDataSmall) {
fixed

2024-12-15 20:06 UTC, mateusxap commented on tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, RandomDataLarge) {
fixed

2024-12-15 20:06 UTC, mateusxap commented on tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, AlreadySortedData) {
fixed

2024-12-15 20:06 UTC, mateusxap commented on tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, ReverseSortedData) {
fixed

2024-12-15 20:06 UTC, mateusxap commented on tasks/seq/kharin_m_radix_double_sort/perf_tests/main.cpp
> +TEST(RadixSort_Sequential_PerfTest, test_pipeline_run) {
fixed

2024-12-15 20:06 UTC, mateusxap commented on tasks/seq/kharin_m_radix_double_sort/perf_tests/main.cpp
> +#include <cmath>
fixed

2024-12-15 20:06 UTC, mateusxap commented on tasks/seq/kharin_m_radix_double_sort/perf_tests/main.cpp
> +TEST(RadixSort_Sequential_PerfTest, test_task_run) {
fixed

2024-12-15 20:06 UTC, Chiks37 approved these changes

2024-12-15 20:06 UTC, mateusxap commented on tasks/mpi/kharin_m_radix_double_sort/perf_tests/main.cpp
> +TEST(RadixSort_MPI_PerfTest, test_pipeline_run) {
fixed

2024-12-15 20:07 UTC, mateusxap commented on tasks/mpi/kharin_m_radix_double_sort/perf_tests/main.cpp
> +TEST(RadixSort_MPI_PerfTest, test_task_run) {
fixed

2024-12-15 20:07 UTC, mateusxap commented on tasks/mpi/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, SimpleData) {
fixed

2024-12-15 20:07 UTC, mateusxap commented on tasks/mpi/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, ValidationFailureTestSize) {
fixed

2024-12-15 20:07 UTC, mateusxap commented on tasks/mpi/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, RandomDataSmall) {
fixed

2024-12-15 20:07 UTC, mateusxap commented on tasks/mpi/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, RandomDataLarge) {
fixed

2024-12-15 20:07 UTC, mateusxap commented on tasks/mpi/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, AlreadySortedData) {
fixed

2024-12-15 20:07 UTC, mateusxap commented on tasks/mpi/kharin_m_radix_double_sort/func_tests/main.cpp
> +TEST(RadixSort_MPI, ReverseSortedData) {
fixed

2024-12-15 20:32 UTC, sk1er52 commented on tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
> +    ASSERT_EQ(inputData[i], resultSeq[i]);
I think there should be an ASSERT_NEAR here, because there is a chance that using ASSERT_EQ may be incorrect due to loss of precision in double

2024-12-15 20:32 UTC, sk1er52 commented on tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
> +    ASSERT_EQ(inputData[i], resultSeq[i]);
I think there should be an ASSERT_NEAR here, because there is a chance that using ASSERT_EQ may be incorrect due to loss of precision in double

2024-12-15 20:32 UTC, sk1er52 commented on tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
> +    ASSERT_EQ(inputData[i], resultSeq[i]);
I think there should be an ASSERT_NEAR here, because there is a chance that using ASSERT_EQ may be incorrect due to loss of precision in double

2024-12-15 20:32 UTC, sk1er52 commented on tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
> +    ASSERT_EQ(inputData[i], resultSeq[i]);
I think there should be an ASSERT_NEAR here, because there is a chance that using ASSERT_EQ may be incorrect due to loss of precision in double

2024-12-15 20:32 UTC, sk1er52 commented on tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
> +    ASSERT_EQ(inputData[i], resultSeq[i]);
I think there should be an ASSERT_NEAR here, because there is a chance that using ASSERT_EQ may be incorrect due to loss of precision in double

2024-12-15 21:50 UTC, mateusxap commented on tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
> +    ASSERT_EQ(inputData[i], resultSeq[i]);
fixed

2024-12-15 21:50 UTC, mateusxap commented on tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
> +    ASSERT_EQ(inputData[i], resultSeq[i]);
fixed

2024-12-15 21:50 UTC, mateusxap commented on tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
> +    ASSERT_EQ(inputData[i], resultSeq[i]);
fixed

2024-12-15 21:50 UTC, mateusxap commented on tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
> +    ASSERT_EQ(inputData[i], resultSeq[i]);
fixed

2024-12-15 21:50 UTC, mateusxap commented on tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
> +    ASSERT_EQ(inputData[i], resultSeq[i]);
fixed

2024-12-15 21:53 UTC, sk1er52 approved these changes

2024-12-20 14:47 UTC, allnes approved these changes

2024-12-20 14:47 UTC, merged