Чернова Наталья. Задача 2. Вариант 11. Топология сетей передачи данных кольцо
learning-process/ppc-2024-autumn pull request #457
Opened 2024-12-07 05:44 UTC by ChernovaNatalya

В топологии сетей передачи данных кольцо мы передаём данные потокам по порядку и возвращаемся в исходный поток (0 - 1 - 2 - 3 - ... - n - 0).  Вектор output_ хранит в себе передаваемые данные, а вектор process_ - номера процессов, которым мы передавали данные (нужен для проверки корректности работы алгоритма).

2024-12-07 22:32 UTC, VasenkovAA commented on tasks/mpi/chernova_n_topology_ring/src/ops_mpi.cpp
> +    memcpy(input_.data(), taskData->inputs[0], sizeof(char) * n);
я где то читал что std::copy лучше чем memcpy в плане безопасности кода

2024-12-07 22:32 UTC, VasenkovAA commented on tasks/mpi/chernova_n_topology_ring/src/ops_mpi.cpp
> +  internal_order_test();
странно в тестах делать валидацию во всех процессах, а фактически делать ее на 0

2024-12-07 22:32 UTC, VasenkovAA commented on tasks/mpi/chernova_n_topology_ring/src/ops_mpi.cpp
> +      return true;
????

2024-12-07 22:34 UTC, VasenkovAA commented on tasks/mpi/chernova_n_topology_ring/src/ops_mpi.cpp
> +      return true;
Почему ВСЕГДА возвращает true?

2024-12-07 22:36 UTC, VlJulia requested changes

2024-12-07 22:36 UTC, VlJulia commented on tasks/mpi/chernova_n_topology_ring/func_tests/main.cpp
> +  }
Я не думаю что тест логичный, там же проверка на то, что валидация false?

2024-12-07 22:36 UTC, VlJulia commented on tasks/mpi/chernova_n_topology_ring/src/ops_mpi.cpp
> +    if (taskData->outputs_count[0] == 1 && taskData->inputs_count.size() == 1 && taskData->inputs_count[0] >= 0) {
Ты сверяешь с единицей, но ты же в тестах туда 2 кладешь?

2024-12-08 18:48 UTC, ChernovaNatalya commented on tasks/mpi/chernova_n_topology_ring/src/ops_mpi.cpp
> +    memcpy(input_.data(), taskData->inputs[0], sizeof(char) * n);
Изменено

2024-12-08 18:48 UTC, ChernovaNatalya commented on tasks/mpi/chernova_n_topology_ring/src/ops_mpi.cpp
> +      return true;
Исправила

2024-12-08 18:49 UTC, ChernovaNatalya commented on tasks/mpi/chernova_n_topology_ring/func_tests/main.cpp
> +  }
Поправила, теперь тест с пустыми данными не проходит валидацию

2024-12-08 18:49 UTC, ChernovaNatalya commented on tasks/mpi/chernova_n_topology_ring/src/ops_mpi.cpp
> +    if (taskData->outputs_count[0] == 1 && taskData->inputs_count.size() == 1 && taskData->inputs_count[0] >= 0) {
Изменила

2024-12-09 08:29 UTC, VasenkovAA approved these changes

2024-12-09 11:39 UTC, VlJulia approved these changes

2024-12-10 03:49 UTC, aobolensk requested changes

2024-12-10 03:49 UTC, aobolensk commented on tasks/mpi/chernova_n_topology_ring/func_tests/main.cpp
> +std::vector<char> generateData(int k) {
Please, either make test data generation functions static or wrap them with the namespace

2024-12-10 11:47 UTC, ChernovaNatalya commented on tasks/mpi/chernova_n_topology_ring/func_tests/main.cpp
> +std::vector<char> generateData(int k) {
Fixed

2024-12-11 19:49 UTC, aobolensk approved these changes

2024-12-15 19:40 UTC, allnes approved these changes

2024-12-15 19:41 UTC, merged