Будажапова Екатерина. Задача 2. Вариант 15. Ленточная горизонтальная схема
learning-process/ppc-2024-autumn pull request #458
Opened 2024-12-07 06:19 UTC by Save-Yourself

2024-12-08 17:19 UTC, ascannel requested changes

2024-12-08 17:19 UTC, ascannel commented on tasks/seq/budazhapova_e_matrix_multiplication/func_tests/matrix_mult_func_tests.cpp
> +TEST(budazhapova_e_matrix_mult_seq, ordinary_test) {
i suggest you to add more tests for functionality, not just matrix and vector with 1's in them

2024-12-08 17:19 UTC, ascannel commented on tasks/mpi/budazhapova_e_matrix_multiplication/func_tests/matrix_mult_func_tests_mpi.cpp
> +TEST(budazhapova_e_matrix_mult_mpi, ordinary_test_1) {
i suggest you to add more tests for functionality, for matrices and vectors with random values, so you could compare seq and parallel solutions on them

2024-12-08 17:43 UTC, VasenkovAA approved these changes

2024-12-08 17:43 UTC, VasenkovAA commented on tasks/mpi/budazhapova_e_matrix_multiplication/src/matrix_mult_mpi.cpp
> +  boost::mpi::broadcast(world, recv_counts, 0);
Ты уверена что надо рассылать recv_counts и desplacements?

2024-12-10 03:57 UTC, aobolensk requested changes

2024-12-10 03:57 UTC, aobolensk commented on tasks/mpi/budazhapova_e_matrix_multiplication/src/matrix_mult_mpi.cpp
> +  boost::mpi::broadcast(world, columns, 0);
Please, move data transfer to ::run() function and reduce amount of data that is being transferred if possible

2024-12-10 04:44 UTC, ascannel approved these changes

2024-12-11 19:56 UTC, aobolensk requested changes

2024-12-11 19:56 UTC, aobolensk commented on tasks/mpi/budazhapova_e_matrix_multiplication/func_tests/matrix_mult_func_tests_mpi.cpp
> +std::vector<int> generate_random_vector_or_matrix(int size, int minValue, int maxValue) {
Please, either make it static or wrap with namespace

2024-12-11 19:56 UTC, aobolensk commented on tasks/mpi/budazhapova_e_matrix_multiplication/pref_tests/matrix_mult_pref_tests_mpi.cpp
> +
Please, rename the whole directory to "perf_tests", otherwise tests will not work correctly

2024-12-12 20:55 UTC, Save-Yourself commented on tasks/mpi/budazhapova_e_matrix_multiplication/src/matrix_mult_mpi.cpp
> +  boost::mpi::broadcast(world, columns, 0);
thanks, fixed

2024-12-12 20:56 UTC, Save-Yourself commented on tasks/mpi/budazhapova_e_matrix_multiplication/func_tests/matrix_mult_func_tests_mpi.cpp
> +std::vector<int> generate_random_vector_or_matrix(int size, int minValue, int maxValue) {
thanks, fixed

2024-12-12 20:56 UTC, Save-Yourself commented on tasks/mpi/budazhapova_e_matrix_multiplication/pref_tests/matrix_mult_pref_tests_mpi.cpp
> +
thanks, fixed

2024-12-13 03:22 UTC, aobolensk approved these changes

2024-12-15 19:43 UTC, allnes approved these changes

2024-12-15 19:43 UTC, merged