Филатьева Елизавета. Задача 1. Вариант 25. Подсчет числа предложений в строке.
learning-process/ppc-2024-autumn pull request #46
Opened 2024-10-27 10:27 UTC by LizochkaSpring

**Описание последовательной задачи**
- Последовательно считает количество знаков заканчивающих предложение.
**Описание MPI задачи**
- Строка разбивается на подстроки одинаковой длины. Каждый процесс получает свою подстроку, затем все процессы отправляют свой результат главному процессу, который собирает их и определяет окончательное количество предложений в строке.

2024-10-28 22:43 UTC, WladislawFilatew commented on tasks/mpi/filateva_e_number_sentences_line/src/ops_mpi.cpp
> +  }
This code must belong to the run method.

2024-10-28 22:48 UTC, WladislawFilatew commented on tasks/mpi/filateva_e_number_sentences_line/src/ops_mpi.cpp
> +    local_line = std::string(line.begin(), line.begin() + delta + remains);
It is better to allocate only the remaining part to the null process.

2024-10-29 07:00 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_number_sentences_line/src/ops_mpi.cpp
> +    local_line = std::string(line.begin(), line.begin() + delta + remains);
fixed

2024-10-29 07:14 UTC, WladislawFilatew approved these changes

2024-10-29 19:29 UTC, allnes approved these changes

2024-10-30 00:41 UTC, aobolensk requested changes

2024-10-30 07:39 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_number_sentences_line/perf_tests/main.cpp
> +  int count = 22;
Добрый день, в данных тестах происходит проверка не 22 предложений в строке, а 2^22 предложений в строке. 
![capture_20241030103502326](https://github.com/user-attachments/assets/a47edc88-7291-4872-8fd8-c1ca3c6eb369)

2024-10-30 09:49 UTC, LizochkaSpring commented on tasks/mpi/filateva_e_number_sentences_line/include/ops_mpi.hpp
> +
fixed

2024-10-30 09:49 UTC, LizochkaSpring commented on tasks/seq/filateva_e_number_sentences_line/func_tests/main.cpp
> +TEST(filateva_e_number_sentences_line_seq, empty_string) {
fixed

2024-10-30 16:31 UTC, aobolensk commented on tasks/mpi/filateva_e_number_sentences_line/perf_tests/main.cpp
> +  int count = 22;
OK, got it

2024-10-30 16:32 UTC, aobolensk approved these changes

2024-10-30 16:32 UTC, merged