Грудзин Константин. Задача 3. Вариант 10. Интегрирование методом Монте-Карло многомерных интегралов
learning-process/ppc-2024-autumn pull request #463
Opened 2024-12-07 19:34 UTC by Konstantin-Grudzin

Основная идея многопоточного решения:
Статистически, маловероятно попадание нескольких потоков в один и тот же вектор (Особенно при разных сидах)
Поэтому достаточно каждому потоку просуммировать отведённое количество случайных точек и слить их в нулевом потоке
Чтобы удостоверится, что теория верна, дополнительно написана последовательная версия, с которой сравнивается программа (на ошибку не более одного процента от обычного метода Монте-Карло)

2024-12-17 08:14 UTC, Napkin-AI requested changes

2024-12-17 08:14 UTC, Napkin-AI commented on tasks/mpi/grudzin_k_monte_carlo/func_tests/gmc_ftests.cpp
> +#include <gtest/gtest.h>
Add sequential vesion to folder seq to measure performance

2024-12-17 08:14 UTC, Napkin-AI commented on tasks/mpi/grudzin_k_monte_carlo/func_tests/gmc_ftests.cpp
> +  std::uniform_real_distribution<> dist(-5.0, 5.0);
fix the seed

2024-12-17 08:14 UTC, Napkin-AI commented on tasks/mpi/grudzin_k_monte_carlo/func_tests/gmc_ftests.cpp
> +TEST(grudzin_k_monte_carlo_mpi, Test_1Dim) {
try N = 2^k,  (for expl k = 15)

2024-12-17 08:14 UTC, Napkin-AI commented on tasks/mpi/grudzin_k_monte_carlo/func_tests/gmc_ftests.cpp
> +    // MC1_Data->inputs.emplace_back(reinterpret_cast<uint8_t *>(&N));
remove the comments please, your code is hard to read

2024-12-17 08:14 UTC, Napkin-AI commented on tasks/mpi/grudzin_k_monte_carlo/include/gmc_include.hpp
> +  // answer
remove the comment. I see the variable with name "result" is an answer

2024-12-17 08:14 UTC, Napkin-AI commented on tasks/mpi/grudzin_k_monte_carlo/include/gmc_include.hpp
> +  // answer
remove the comment. I see the variable with name "result" is an answer

2024-12-17 08:14 UTC, Napkin-AI commented on tasks/mpi/grudzin_k_monte_carlo/include/gmc_include.hpp
> +  // target function
either remove this comment or add it to seq version

2024-12-17 08:14 UTC, Napkin-AI commented on tasks/mpi/grudzin_k_monte_carlo/src/gmc_src.cpp
> +template class MonteCarloMpi<1>;
what is that?

2024-12-18 11:27 UTC, Konstantin-Grudzin commented on tasks/mpi/grudzin_k_monte_carlo/func_tests/gmc_ftests.cpp
> +  std::uniform_real_distribution<> dist(-5.0, 5.0);
What do you want to fix? If you construct it by default (without specified seed) it use default seed (like zero or smth like that). I can't use some random seed cause' it bring unpredictable situations. (if you interested, i test it on different seeds and it worked)

2024-12-18 11:30 UTC, Konstantin-Grudzin commented on tasks/mpi/grudzin_k_monte_carlo/func_tests/gmc_ftests.cpp
> +TEST(grudzin_k_monte_carlo_mpi, Test_1Dim) {
add power of two and prime number for count of dots

2024-12-18 11:32 UTC, Konstantin-Grudzin commented on tasks/mpi/grudzin_k_monte_carlo/src/gmc_src.cpp
> +template class MonteCarloMpi<1>;
Without it my code dont see this versions of function, i cnnot remove that

2024-12-19 08:28 UTC, m1likus requested changes

2024-12-19 08:28 UTC, m1likus commented on tasks/mpi/grudzin_k_monte_carlo/include/gmc_include.hpp
> +#include <vector>
Some of this includes already are in task.hpp

2024-12-19 08:28 UTC, m1likus commented on tasks/seq/grudzin_k_monte_carlo/func_tests/main.cpp
> +  EXPECT_LE(abs(etalon - result_seq) / etalon, 1e-1);
Why do you use Less Equal everywhere and not Near?

2024-12-19 08:45 UTC, Napkin-AI approved these changes

2024-12-19 08:52 UTC, Konstantin-Grudzin commented on tasks/seq/grudzin_k_monte_carlo/func_tests/main.cpp
> +  EXPECT_LE(abs(etalon - result_seq) / etalon, 1e-1);
Near just checked,that your value located between some diapasone of dot ([a-x;a+x]), but absolute error can be less that one precent on some value, i can make smth like that: (my statement,0.1,0.1), but it's much more text

2024-12-19 10:31 UTC, m1likus commented on tasks/seq/grudzin_k_monte_carlo/func_tests/main.cpp
> +  EXPECT_LE(abs(etalon - result_seq) / etalon, 1e-1);
I think at least at sec impl near is more logic than LE but that's fine then now I get it

2024-12-19 10:32 UTC, m1likus approved these changes

2024-12-20 20:14 UTC, aobolensk approved these changes

2024-12-22 22:12 UTC, allnes commented on tasks/mpi/grudzin_k_monte_carlo/func_tests/gmc_ftests.cpp
> +std::vector<double> GenDimDistr(int dim) {
please parametrize range

2024-12-22 22:13 UTC, allnes commented on tasks/mpi/grudzin_k_monte_carlo/func_tests/gmc_ftests.cpp
> +    { return 0.0 * (x[0] + x[1]) + 1.0; }
please don't use functions with zero multiplication

2024-12-23 16:00 UTC, Konstantin-Grudzin commented on tasks/mpi/grudzin_k_monte_carlo/func_tests/gmc_ftests.cpp
> +    { return 0.0 * (x[0] + x[1]) + 1.0; }
Sorry, but i cannot delete this: one of compilators complaning about unusing variables, this multiplication needs for accepting this issue

2024-12-23 16:00 UTC, Konstantin-Grudzin commented on tasks/mpi/grudzin_k_monte_carlo/func_tests/gmc_ftests.cpp
> +    { return 0.0 * (x[0] + x[1]) + 1.0; }
(It was clang build)

2024-12-25 18:51 UTC, merged