Шишкарев Андрей. Задача 2. Вариант 19. Метод Гаусса – ленточная горизонтальная схема.
learning-process/ppc-2024-autumn pull request #464
Opened 2024-12-07 21:03 UTC by shishkarev

На вход подаётся двумерная матрица коэффициентов и вектор свободных членов системы линейных уравнений, которые необходимо решить с помощью метода Гаусса. Последовательное решение задачи включает в себя приведение матрицы к верхнетреугольному виду с последующим обратным ходом для нахождения решения. Для этого поочередно нормализуются строки матрицы, а затем из каждой строки вычитаются пропорциональные элементы, чтобы устранить нижнюю треугольную часть.

Для параллельной реализации используется подход с распределением строк матрицы между MPI-процессами. Каждый процесс получает часть строк матрицы и вектора свободных членов, выполняет их обработку, включая нормализацию и вычитание, а затем обмен данными между процессами для обеспечения корректности вычислений на каждом шаге. После этого решения для каждой части системы объединяются с использованием операции редукции (reduce) в главном процессе, где результат сохраняется. Этот подход позволяет эффективно использовать параллельные вычисления для решения больших систем уравнений на многопроцессорных системах, сокращая время вычислений.

2024-12-12 10:08 UTC, decl1 requested changes

2024-12-12 13:04 UTC, Domovenokkk requested changes
Write tests to check for zero and negative values ​​in a matrix в seq.

2024-12-12 16:35 UTC, korablev-vm requested changes
+ замените ASSERT_ на EXPECT_ в тестах, когда производится финальное сравнение результатов

2024-12-12 16:35 UTC, korablev-vm commented on tasks/mpi/shishkarev_a_gaussian_method_horizontal_strip_pattern/include/ops_mpi.hpp
> +};
local_matrix и local_res у Вас используются только внтури run, их объявление можно перенести туда

2024-12-12 16:35 UTC, korablev-vm commented on tasks/mpi/shishkarev_a_gaussian_method_horizontal_strip_pattern/src/ops_mpi.cpp
> +#include <vector>
не нашел, для чего может использоваться <string>, если действительно лишнее - стоит удалить

2024-12-12 16:35 UTC, korablev-vm commented on tasks/seq/shishkarev_a_gaussian_method_horizontal_strip_pattern/include/ops_seq.hpp
> +#include <vector>
аналогично про string

2024-12-12 16:35 UTC, korablev-vm commented on tasks/mpi/shishkarev_a_gaussian_method_horizontal_strip_pattern/include/ops_mpi.hpp
> +#include <vector>
string, аналогично.

2024-12-22 22:14 UTC, allnes commented on tasks/mpi/shishkarev_a_gaussian_method_horizontal_strip_pattern/func_tests/main.cpp
> +std::vector<double> getRandomMatrix(int sz) {
please parametrize range

2024-12-22 22:15 UTC, allnes commented on tasks/mpi/shishkarev_a_gaussian_method_horizontal_strip_pattern/perf_tests/main.cpp
> +}
please move it in src part

2024-12-29 19:38 UTC, closed without merging