Бурыкин Михаил. Задача 2. Вариант 5. Методы передачи сообщений "Передача от одного всем (broadcast)"
learning-process/ppc-2024-autumn pull request #466
Opened 2024-12-07 23:10 UTC by WholeHorse

### Описание MPI алгоритма для функции `broadcast`

Функция `broadcast` реализует рассылку данных от одного процесса-источника (**root**) ко всем остальным процессам с использованием бинарного дерева для оптимизации передачи данных.

#### Принцип работы

1. **Организация процессов**:  
   Процессы упорядочиваются в виде бинарного дерева, где корнем является процесс `root`.

2. **Передача данных**:  
   - **Корневой процесс** отправляет данные своим дочерним процессам (левому и правому).  
   - Каждый дочерний процесс после получения данных пересылает их своим дочерним узлам, если они существуют.

#### Пример

Для 7 процессов (0-6) с `root = 0` структура бинарного дерева будет:

```
    (root = 0)
       /  \
      1    2
     / \  / \
    3  4 5   6
```

**Шаги передачи данных**:  
1. Процесс `0` отправляет данные процессам `1` и `2`.  
2. Процесс `1` пересылает данные процессам `3` и `4`.  
3. Процесс `2` пересылает данные процессам `5` и `6`.

2024-12-08 00:39 UTC, venn2713 requested changes
Кажется тут все, очень лаконичное решение, интересный подход к распределению по воркерам, красивое дерево получается, я видел в другом репозитории немного более быстрый вариант, но этот прям красивый как по мне)

2024-12-08 00:39 UTC, venn2713 commented on tasks/mpi/burykin_m_broadcast/func_tests/main.cpp
Добавьте элемент случайности, пусть будет тест в котором выбирается случайным образом root от `0` до `world.size() - 1`

2024-12-08 01:12 UTC, venn2713 requested changes

2024-12-08 01:12 UTC, venn2713 commented on tasks/mpi/burykin_m_broadcast/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, input_vector, source_worker);
Вы использовали стандартную библиотеку, видимо случайно (надеюсь)

2024-12-09 11:46 UTC, MikeMuradov requested changes

2024-12-09 11:46 UTC, MikeMuradov commented on tasks/mpi/burykin_m_broadcast/src/ops_mpi.cpp
> +
In such a problem, you need to come up with a problem that can be solved via broadcast and solve

2024-12-09 13:06 UTC, venn2713 requested changes
Когда добавите функцию которую реализовываете в ране, то поставлю апрув, а то я правда вспомнил что говорили надо

2024-12-10 20:51 UTC, MikeMuradov approved these changes

2024-12-10 21:37 UTC, venn2713 approved these changes

2024-12-11 12:31 UTC, korablev-vm approved these changes

2024-12-11 12:33 UTC, korablev-vm commented on tasks/mpi/burykin_m_broadcast/perf_tests/main.cpp
> +  }
Все же нет, в коде выполнено корректно, моя ошибка

2024-12-11 20:00 UTC, aobolensk approved these changes

2024-12-15 19:50 UTC, allnes approved these changes

2024-12-15 19:50 UTC, merged