Громов Алексей. Задача 2. Вариант 20. Метод Гаусса – ленточная вертикальная схема.
learning-process/ppc-2024-autumn pull request #468
Opened 2024-12-08 06:55 UTC by DSFKnight

**Описание последовательной задачи**
На вход подаётся две матрицы: одна содержит коэффициенты неизвестных (`input_coefficient`), другая — значения правой части уравнений (`input_rhs`). На основе этих данных строится расширенная матрица, которая используется для вычислений методом Гаусса с ленточной схемой.

1. Прямой ход метода Гаусса:
- Проводится поиск максимального элемента в пределах текущей полосы матрицы (ширина полосы задаётся параметром `band_width`).
- Перестановка строк осуществляется для размещения максимального элемента в главной диагонали.
- Путём исключения переменных с использованием факторизации производится приведение матрицы к верхнетреугольному виду.
2. Обратный ход:
- Вычисляются значения переменных, начиная с нижнего уравнения и поднимаясь вверх, используя сохранённые значения для вычисления.

Результаты сохраняются в векторе решения.

**Описание параллельной задачи**
1. Распределение данных:
- Матрицы разделяются между процессами, чтобы каждый процесс работал только с частью данных.
- Процесс с рангом 0 управляет распределением строк и пересылает данные другим процессам.

2. Прямой ход:
-  Каждый процесс выполняет поиск максимального элемента в своей части данных.
-  Результаты синхронизируются между процессами для выбора глобального максимального элемента.
- Обновлённые строки отправляются между процессами для обеспечения корректности вычислений.

3. Обратный ход:
- Процессы выполняют вычисления для своих строк, передавая необходимые данные процессу с рангом 0, где формируется итоговый результат.

2024-12-08 08:30 UTC, WholeHorse requested changes

2024-12-08 08:30 UTC, WholeHorse commented on tasks/mpi/gromov_a_gaussian_method_vertical/perf_tests/main.cpp
> +#include <algorithm>
is it used?

2024-12-08 08:30 UTC, WholeHorse commented on tasks/mpi/gromov_a_gaussian_method_vertical/func_tests/main.cpp
> +#include <algorithm>
is it used?

2024-12-08 08:30 UTC, WholeHorse commented on tasks/mpi/gromov_a_gaussian_method_vertical/src/ops_mpi.cpp
> +#include <thread>
is it used?

2024-12-08 09:29 UTC, artich02 requested changes

2024-12-08 09:29 UTC, artich02 commented on tasks/seq/gromov_a_gaussian_method_vertical/src/ops_seq.cpp
> +  }
Better to use std::copy, please fix it

2024-12-08 09:29 UTC, artich02 commented on tasks/seq/gromov_a_gaussian_method_vertical/src/ops_seq.cpp
> +  }
Use std::copy

2024-12-08 09:29 UTC, artich02 commented on tasks/seq/gromov_a_gaussian_method_vertical/func_tests/main.cpp
> +
Add some more tests, please

2024-12-08 12:37 UTC, WholeHorse approved these changes

2024-12-08 19:03 UTC, artich02 approved these changes

2024-12-10 04:23 UTC, aobolensk requested changes

2024-12-10 04:23 UTC, aobolensk commented on tasks/mpi/gromov_a_gaussian_method_vertical/perf_tests/main.cpp
> +  int equations = 240;
Please, increase the shape or oerf tests

2024-12-11 03:23 UTC, aobolensk approved these changes

2024-12-15 19:51 UTC, allnes approved these changes

2024-12-15 19:51 UTC, merged