Кабалова Валерия. Задача 2. Вариант 6. Передача от всех одному (reduce).
learning-process/ppc-2024-autumn pull request #470
Opened 2024-12-08 09:36 UTC by m1likus

Реализация mpi_reduce.

На вход подается вектор чисел. Его элементы делятся между всеми процессами программы.
На вход также подается операция, которая будет применена к вектору. На выходе получаем результат
от операции reduce, либо myReduce.

Параметры, принимаемые функцией MPI_reduce
- sendbuf[in] - дескриптор буфера, который содержит данные, отправляемые корневому процессу
- recvbuf [out, optional] - Дескриптор буфера для получения результата операции сокращения. 
Этот параметр имеет значение только в корневом процессе.
- count - кол-во элементов, отправляемых из этого процесса
- datatype - Тип данных каждого элемента в буфере. Этот параметр должен быть совместим с операцией, 
как указано в параметре op
- op -Выполняемая операция глобального сокращения. 
- root - Ранг принимающего процесса в указанном коммуникаторе
- comm - дескриптор коммуникатора.

MPI_MAX - max
MPI_MIN - min
MPI_SUM - +
MPI_PROD - *
MPI_LAND - ||
MPI_BAND - &
MPI_LOR - |
MPI_BOR - &
MPI_LXOR - lxor
MPI_BXOR - ^

В моей задаче используется reduce из библиотеки boost/mpi, также идентично реализуется myReduce. 
myReduce реализуется с использованием бинарного дерева процессов, также используется boost/packed_iarchive, который 
позволяет пользоваться пользовательсики классами: packed_iarchive и packed_oarchive. Это бустовская работа с MPI_buffer.

Как уже было сказано: на вход подается вектор чисел. Его элементы делятся между всеми процессами программы с помощью scatterv.
На вход также подается операция, которая будет применена к вектору.
В валидацию входит проверка на верную операцию. Аналоги названиям MPI представлены выше.
Затем вектор чисел разделяется между всеми процессами с помощью scatterv. 
Для scatterv вычисляется delta и remains. Remains распределяются между всеми процессами до 
тех пор, пока это возможно.
Затем локально в подвекторах выполняется нужная операция и вызывается reduce для всех процессов.

2024-12-08 11:40 UTC, ascannel commented on tasks/mpi/kabalova_v_my_reduce/src/kabalova_my_reduce.cpp
> +    }
you could use different way to preprocess data for better performance

2024-12-08 11:40 UTC, ascannel commented on tasks/mpi/kabalova_v_my_reduce/src/kabalova_my_reduce.cpp
> +#include <vector>
unnecessary includes, declared in task.hpp already

2024-12-08 11:40 UTC, ascannel commented on tasks/mpi/kabalova_v_mpi_reduce/perf_tests/kabalova_mpi_reduce_perf_tests.cpp
> +  }
i propose to move the creation of a vector with random data outside the test, and the vector will be created one for two tests, so that the speed can be correctly compared

2024-12-08 13:28 UTC, AnastasiaRezantseva requested changes

2024-12-08 13:28 UTC, AnastasiaRezantseva commented on tasks/mpi/kabalova_v_mpi_reduce/src/kabalova_mpi_reduce.cpp
> +    throw("Wrong operation");
You have already checked the correctness of the operation in validation

2024-12-08 13:28 UTC, AnastasiaRezantseva commented on tasks/mpi/kabalova_v_mpi_reduce/src/kabalova_mpi_reduce.cpp
> +  } else if (ops == "*") {  // MPI_PROD
Maybe you should use switch/case instead of if/else for better code readability

2024-12-08 14:46 UTC, m1likus commented on tasks/mpi/kabalova_v_mpi_reduce/src/kabalova_mpi_reduce.cpp
> +  } else if (ops == "*") {  // MPI_PROD
Actually I do not agree, because it's only about readability, and readability is relative concept, so it seems to me that if/else is fine here

2024-12-08 14:48 UTC, m1likus commented on tasks/mpi/kabalova_v_mpi_reduce/perf_tests/kabalova_mpi_reduce_perf_tests.cpp
> +  }
I do not agree about random data, because I need to compare speed between my reduce and mpi reduce and also between pipeline and rung, but I agree about moving out the creation of a vector

2024-12-08 16:38 UTC, Konstantin-Grudzin requested changes

2024-12-08 16:38 UTC, Konstantin-Grudzin commented on tasks/mpi/kabalova_v_mpi_reduce/func_tests/kabalova_mpi_reduce_func_tests.cpp
> +    result = result && (bool)vec[i];
Dont use c-style cast, better way is using the static cast

2024-12-08 16:38 UTC, Konstantin-Grudzin commented on tasks/mpi/kabalova_v_mpi_reduce/func_tests/kabalova_mpi_reduce_func_tests.cpp
> +    result = result || (bool)vec[i];
Dont use c-style cast

2024-12-08 16:38 UTC, Konstantin-Grudzin commented on tasks/mpi/kabalova_v_mpi_reduce/func_tests/kabalova_mpi_reduce_func_tests.cpp
> +    bool res1 = !(bool)vec[i];
Dont use c-style cast

2024-12-08 16:38 UTC, Konstantin-Grudzin commented on tasks/mpi/kabalova_v_mpi_reduce/src/kabalova_mpi_reduce.cpp
> +  return (ops == "+" || ops == "*" || ops == "min" || ops == "max" || ops == "&&" || ops == "||" || ops == "&" ||
It will be better of you reduce this string for better reading (maybe add for or smth like that)

2024-12-08 16:38 UTC, Konstantin-Grudzin commented on tasks/mpi/kabalova_v_mpi_reduce/src/kabalova_mpi_reduce.cpp
> +      local_res = static_cast<int>((bool)local_res && (bool)local_input_[i]);
Dont use c-style cast

2024-12-08 16:38 UTC, Konstantin-Grudzin commented on tasks/mpi/kabalova_v_mpi_reduce/src/kabalova_mpi_reduce.cpp
> +      bool res1 = !(bool)local_res;
Dont use c-style cast

2024-12-08 16:38 UTC, Konstantin-Grudzin commented on tasks/mpi/kabalova_v_my_reduce/func_tests/kabalova_my_reduce_func_tests.cpp
> +  std::mt19937 gen(rd());
I think it's better if you use seed instead of random engine, 'cause it can throw some unexpected result

2024-12-08 16:38 UTC, Konstantin-Grudzin commented on tasks/mpi/kabalova_v_my_reduce/func_tests/kabalova_my_reduce_func_tests.cpp
> +    result = result && (bool)vec[i];
Dont use c-style cast

2024-12-08 16:38 UTC, Konstantin-Grudzin commented on tasks/mpi/kabalova_v_my_reduce/func_tests/kabalova_my_reduce_func_tests.cpp
> +    result = result || (bool)vec[i];
Dont use c-style cast

2024-12-08 16:38 UTC, Konstantin-Grudzin commented on tasks/mpi/kabalova_v_my_reduce/src/kabalova_my_reduce.cpp
> +  return (ops == "+" || ops == "*" || ops == "min" || ops == "max" || ops == "&&" || ops == "||" || ops == "&" ||
I think, it will be better if you reduce this string

2024-12-08 16:38 UTC, Konstantin-Grudzin commented on tasks/mpi/kabalova_v_my_reduce/src/kabalova_my_reduce.cpp
> +    if (tmp > std::numeric_limits<int>::max()) throw "overflow";
So, can you imagine like it will happen?

2024-12-08 16:38 UTC, Konstantin-Grudzin commented on tasks/mpi/kabalova_v_my_reduce/src/kabalova_my_reduce.cpp
> +    if ((unsigned int)world.rank() < remains) {
Dont use c-style cast

2024-12-08 16:40 UTC, m1likus commented on tasks/mpi/kabalova_v_my_reduce/src/kabalova_my_reduce.cpp
> +    if (tmp > std::numeric_limits<int>::max()) throw "overflow";
I can, I tested it)

2024-12-08 16:50 UTC, ascannel commented on tasks/mpi/kabalova_v_my_reduce/src/kabalova_my_reduce.cpp
> +    }
yes, assigns in particular

2024-12-08 16:53 UTC, ascannel commented on tasks/mpi/kabalova_v_mpi_reduce/perf_tests/kabalova_mpi_reduce_perf_tests.cpp
> +  }
ok, maybe not fully random, but somewhat random data, identical for both reduces, not just 1, 2, 3 ...

2024-12-08 18:00 UTC, Konstantin-Grudzin commented on tasks/mpi/kabalova_v_my_reduce/src/kabalova_my_reduce.cpp
> +    if (tmp > std::numeric_limits<int>::max()) throw "overflow";
It very interesting, how you possibly can get this statement true

2024-12-09 07:29 UTC, m1likus commented on tasks/mpi/kabalova_v_mpi_reduce/perf_tests/kabalova_mpi_reduce_perf_tests.cpp
> +  }
Fair

2024-12-09 08:45 UTC, m1likus commented on tasks/mpi/kabalova_v_my_reduce/src/kabalova_my_reduce.cpp
> +    if (tmp > std::numeric_limits<int>::max()) throw "overflow";
Fine fine, I thought about it a little bit and fixed

2024-12-09 10:00 UTC, Konstantin-Grudzin approved these changes

2024-12-09 10:10 UTC, AnastasiaRezantseva approved these changes

2024-12-09 10:25 UTC, ascannel approved these changes

2024-12-10 04:24 UTC, aobolensk requested changes

2024-12-10 04:24 UTC, aobolensk commented on tasks/mpi/kabalova_v_mpi_reduce/perf_tests/kabalova_mpi_reduce_perf_tests.cpp
> +  size_t vecSize = 1000;
Please, use bigger size for perf tests

2024-12-10 15:29 UTC, m1likus commented on tasks/mpi/kabalova_v_mpi_reduce/perf_tests/kabalova_mpi_reduce_perf_tests.cpp
> +  size_t vecSize = 1000;
fixed

2024-12-11 20:04 UTC, aobolensk approved these changes

2024-12-15 19:54 UTC, allnes approved these changes

2024-12-15 19:54 UTC, merged