Тараканов Денис. Задача 2. Вариант 11. Топология сети Кольцо
learning-process/ppc-2024-autumn pull request #472
Opened 2024-12-08 10:45 UTC by Chiks37

Моя программа реализует обмен данными между процессами в сети с топологией "Кольцо" с использованием библиотеки MPI. Главный процесс (ранг 0) инициализирует входные данные, которые затем передаются следующему процессу в кольце. Каждый процесс принимает данные от предыдущего, при необходимости обрабатывает их и отправляет следующему. Последний процесс завершает цикл, возвращая данные обратно главному процессу.

Для передачи данных используются функции send и recv, которые обеспечивают передачу размера буфера и самих данных. Если программа запускается с одним процессом, обмен не выполняется, чтобы избежать излишней обработки. После завершения обмена главный процесс копирует полученные данные в выходной буфер для дальнейшей обработки.

2024-12-08 12:07 UTC, sk1er52 reviewed
good work , I don't see what could be wrong here.

2024-12-08 12:07 UTC, sk1er52 commented on tasks/mpi/tarakanov_d_ring_topology/perf_tests/main.cpp
> +}  // namespace
remove this comment

2024-12-08 12:07 UTC, sk1er52 commented on tasks/mpi/tarakanov_d_ring_topology/func_tests/main.cpp
> +}  // namespace
remove this comment

2024-12-08 12:08 UTC, sk1er52 approved these changes

2024-12-08 13:30 UTC, Chiks37 commented on tasks/mpi/tarakanov_d_ring_topology/perf_tests/main.cpp
> +}  // namespace
There is opening of the anonymous namespace above

2024-12-08 13:30 UTC, Chiks37 commented on tasks/mpi/tarakanov_d_ring_topology/func_tests/main.cpp
> +}  // namespace
It must be here, because there is opening of the anonymous namespace above.

2024-12-08 13:41 UTC, sk1er52 commented on tasks/mpi/tarakanov_d_ring_topology/perf_tests/main.cpp
> +}  // namespace
sorry, my bad, i don't see that <3

2024-12-08 13:41 UTC, sk1er52 commented on tasks/mpi/tarakanov_d_ring_topology/func_tests/main.cpp
> +}  // namespace
sorry, my bad, i don't see that <3

2024-12-09 22:24 UTC, Chiks37 commented on tasks/mpi/tarakanov_d_ring_topology/include/ops_mpi.hpp
> +  int buffer_size_{0};
fixed

2024-12-09 22:24 UTC, Chiks37 commented on tasks/mpi/tarakanov_d_ring_topology/include/ops_mpi.hpp
> +  int received_size_{0};
fixed

2024-12-11 20:18 UTC, aobolensk requested changes

2024-12-11 20:18 UTC, aobolensk commented on tasks/mpi/tarakanov_d_ring_topology/perf_tests/main.cpp
> +TEST(tarakanov_d_ring_topology_mpi_perf_test, test_large_pipeline_run) {
Please, align perf test names with naming convention

2024-12-11 20:18 UTC, aobolensk commented on tasks/mpi/tarakanov_d_ring_topology/func_tests/main.cpp
> +TEST(tarakanov_d_ring_topology_mpi_test, test_size_50) { run_test_case(50); }
Please, add cases with size 0, 1

2024-12-11 22:03 UTC, Chiks37 commented on tasks/mpi/tarakanov_d_ring_topology/func_tests/main.cpp
> +TEST(tarakanov_d_ring_topology_mpi_test, test_size_50) { run_test_case(50); }
Fixed

2024-12-11 22:03 UTC, Chiks37 commented on tasks/mpi/tarakanov_d_ring_topology/perf_tests/main.cpp
> +TEST(tarakanov_d_ring_topology_mpi_perf_test, test_large_pipeline_run) {
Fixed

2024-12-13 14:06 UTC, aobolensk approved these changes

2024-12-15 19:54 UTC, allnes approved these changes

2024-12-15 19:54 UTC, merged