Корнеева Екатерина. Задача 2. Вариант 7. Передача от всех одному и рассылка (allreduce)
learning-process/ppc-2024-autumn pull request #474
Opened 2024-12-08 12:52 UTC by KorneevaEkaterina

### Задача: вычисления среднего значения элементов вектора.

**Последовательная версия:** В этом алгоритме все элементы вектора суммируются на одном процессе, и полученная сумма делится на количество элементов, чтобы вычислить среднее значение.

**MPI-версия:** В этой версии данные распределяются между несколькими процессами. Каждый процесс вычисляет сумму своей части вектора. После этого все результаты объединяются с помощью операции `MPI_Allreduce`, и только корневой процесс вычисляет итоговое среднее значение.

**Реализация allreduce:** Для реализации операции `allreduce` использована структура бинарного дерева. Каждый процесс отправляет свою часть суммы родительскому процессу в дереве. Вершины дерева постепенно объединяют результаты, и в конце итоговое значение среднего передается всем процессам.

2024-12-08 13:02 UTC, hasanyanovk commented on tasks/mpi/korneeva_e_average_of_vector_elements/include/ops_mpi.hpp
> +  std::copy(source_ptr, source_ptr + input_size, input_data.begin());
I think, `assign` better in this case

2024-12-08 13:02 UTC, hasanyanovk commented on tasks/mpi/korneeva_e_average_of_vector_elements/include/ops_mpi.hpp
> +    if (child < size) {  // Если потомок существует
Please, use one language in comments

2024-12-08 15:52 UTC, belovtut requested changes

2024-12-08 15:52 UTC, belovtut commented on tasks/mpi/korneeva_e_average_of_vector_elements/include/ops_mpi.hpp
> +  }
run() must return boolean

2024-12-08 17:35 UTC, hasanyanovk approved these changes

2024-12-08 19:01 UTC, belovtut approved these changes

2024-12-11 20:37 UTC, aobolensk approved these changes

2024-12-15 19:56 UTC, allnes approved these changes

2024-12-15 19:56 UTC, merged