Федоров Матвей. Задача 2. Вариант 6. Передача от всех одному (reduce)
learning-process/ppc-2024-autumn pull request #480
Opened 2024-12-08 14:03 UTC by Matthewsoul124

В проекте реализована функция my_reduce, которая эффективно вычисляет сумму элементов вектора, распределенного между несколькими процессами в среде MPI. Помимо использования стандартной функции boost::mpi::reduce, которая выполняет редукцию в коллективной операции, в проекте реализован собственный алгоритм, основанный на построении бинарного дерева коммуникаций между процессами.
В основе алгоритма лежит принцип построения бинарного дерева, где каждый процесс общается только со своим “партнером” на каждом уровне дерева. Каждый процесс выполняет локальное суммирование своих данных, а затем обменивается промежуточными результатами со своим партнером на каждом уровне дерева, пока не будет получен окончательный результат.

2024-12-09 09:56 UTC, petr1core requested changes

2024-12-09 09:56 UTC, petr1core commented on tasks/mpi/matthew_fyodorov_reduce/src/ops_mpi.cpp
> +  // for (int i = 0; i < local_input_.size(); i++) {
Clean-up

2024-12-09 09:56 UTC, petr1core commented on tasks/mpi/matthew_fyodorov_reduce_custom/func_tests/main.cpp
> +TEST(matthew_fyodorov_reduce_custom_mpi, TestMPITaskParallel_Sum_Random_Numbers) {
So, there need more tests (negative+positive=0), (single), etc.

2024-12-09 09:56 UTC, petr1core commented on tasks/mpi/matthew_fyodorov_reduce_custom/func_tests/main.cpp
> +TEST(matthew_fyodorov_reduce_custom_mpi , TestMPITaskParallel_Sum_PositiveNumbers_2) {
Clean-up

2024-12-09 09:56 UTC, petr1core commented on tasks/mpi/matthew_fyodorov_reduce_custom/src/ops_mpi.cpp
> +std::vector<int> matthew_fyodorov_reduce_custom_mpi ::getRandomVector(int sz) {
Same idea with your custom version

2024-12-09 09:56 UTC, petr1core commented on tasks/mpi/matthew_fyodorov_reduce/func_tests/main.cpp
> +TEST(matthew_fyodorov_reduce_mpi, TestMPITaskParallel_Sum_PositiveNumbers_2) {
Clean-up

2024-12-09 10:11 UTC, Matthewsoul124 commented on tasks/mpi/matthew_fyodorov_reduce/src/ops_mpi.cpp
> +std::vector<int> matthew_fyodorov_reduce_mpi::getRandomVector(int sz) {
done

2024-12-09 10:12 UTC, Matthewsoul124 commented on tasks/mpi/matthew_fyodorov_reduce/src/ops_mpi.cpp
> +  // for (int i = 0; i < local_input_.size(); i++) {
done

2024-12-09 10:15 UTC, Matthewsoul124 commented on tasks/mpi/matthew_fyodorov_reduce_custom/func_tests/main.cpp
> +TEST(matthew_fyodorov_reduce_custom_mpi, TestMPITaskParallel_Sum_Random_Numbers) {
done

2024-12-09 10:16 UTC, Matthewsoul124 commented on tasks/mpi/matthew_fyodorov_reduce_custom/func_tests/main.cpp
> +TEST(matthew_fyodorov_reduce_custom_mpi , TestMPITaskParallel_Sum_PositiveNumbers_2) {
done

2024-12-09 10:17 UTC, Matthewsoul124 commented on tasks/mpi/matthew_fyodorov_reduce/func_tests/main.cpp
> +TEST(matthew_fyodorov_reduce_mpi, TestMPITaskParallel_Sum_PositiveNumbers_2) {
done

2024-12-09 10:21 UTC, Matthewsoul124 commented on tasks/mpi/matthew_fyodorov_reduce_custom/src/ops_mpi.cpp
> +std::vector<int> matthew_fyodorov_reduce_custom_mpi ::getRandomVector(int sz) {
done. you mean to make func more flexible too? I an't got this topic.

2024-12-09 10:26 UTC, Matthewsoul124 commented on tasks/mpi/matthew_fyodorov_reduce_custom/src/ops_mpi.cpp
> +std::vector<int> matthew_fyodorov_reduce_custom_mpi ::getRandomVector(int sz) {
Oh, I got it.

2024-12-09 18:02 UTC, KAPUSHA228 commented on tasks/mpi/matthew_fyodorov_reduce/src/ops_mpi.cpp
> +std::vector<int> matthew_fyodorov_reduce_mpi::getRandomVector(int sz) {
перенеси реализацию рандома конкретно в файлы тестов и вытащи из пространства имён

2024-12-10 08:33 UTC, KAPUSHA228 approved these changes

2024-12-10 08:42 UTC, Matthewsoul124 commented on tasks/mpi/matthew_fyodorov_reduce/src/ops_mpi.cpp
> +std::vector<int> matthew_fyodorov_reduce_mpi::getRandomVector(int sz) {
Сделал)

2024-12-11 20:35 UTC, aobolensk requested changes

2024-12-11 20:35 UTC, aobolensk commented on tasks/mpi/matthew_fyodorov_reduce/func_tests/main.cpp
> +std::vector<int> getRandomVectora(int sz) {
Please, either make static or wrap with namespace

2024-12-11 20:35 UTC, aobolensk commented on tasks/mpi/matthew_fyodorov_reduce/include/ops_mpi.hpp
> +// std::vector<int> getRandomVector(int sz);
Please, remove comments

2024-12-11 20:35 UTC, aobolensk commented on tasks/mpi/matthew_fyodorov_reduce/perf_tests/main.cpp
> +  // int rank = world.rank();
Please, remove commented out code here and everywhere else

2024-12-12 11:40 UTC, Matthewsoul124 commented on tasks/mpi/matthew_fyodorov_reduce/func_tests/main.cpp
> +std::vector<int> getRandomVectora(int sz) {
All changes have been made

2024-12-13 14:08 UTC, aobolensk commented
It seems there are missing tests for "-" and "max".

2024-12-14 10:58 UTC, aobolensk approved these changes

2024-12-15 19:58 UTC, allnes approved these changes

2024-12-15 19:58 UTC, merged