Ануфриев Даниил. Задача 3. Вариант 27. Линейная фильтрация изображений (вертикальное разбиение). Ядро Гаусса 3x3.
learning-process/ppc-2024-autumn pull request #481
Opened 2024-12-08 15:04 UTC by sk1er52

SEQ Версия (Последовательная Реализация)
Алгоритм:
Валидация Данных (validation):

Проверка наличия необходимых входных и выходных данных.
Проверка соответствия размеров изображения и минимальных требований (минимум 3x3).
Предварительная Обработка (pre_processing):

Копирование входных данных изображения в локальный буфер.
Инициализация буфера для выходных данных.
Применение Гауссова Фильтра (run):

Применение 3x3 Гауссова фильтра к изображению.
Обработка каждого пикселя (за исключением границ) путем взвешенного среднего соседних пикселей.
Постобработка (post_processing):

Копирование обработанных данных обратно в выходной буфер.

MPI Версия (Распараллеленная Реализация)
Алгоритм:
Валидация Данных (validation):

Аналогично SEQ-версии, с дополнительным распространением параметров (width и height) на все процессы через broadcast.
Предварительная Обработка (pre_processing):

Распределение Данных (distributeData):
Транспонирование исходного изображения для удобства вертикального разбиения по столбцам.
Расчет количества столбцов для каждого процесса с учетом остатка.
Распределение столбцов между процессами с помощью MPI_Scatterv.
Обмен Гало-Областями (exchangeHalo):

Каждый процесс обменивается гало-столбцами (по одному столбцу слева и справа) с соседними процессами.
Использование неблокирующих отправок и получений (MPI_Isend, MPI_Irecv) для повышения эффективности.
Применение Гауссова Фильтра (applyGaussianFilter):

Применение 3x3 Гауссова фильтра к локально распределенным столбцам изображения с учетом гало-столбцов.
Обработка каждого столбца путем взвешенного среднего соседних столбцов и строк.
Сбор Данных (gatherData):

Сбор обработанных столбцов обратно на корневой процесс с помощью MPI_Gatherv.
Транспонирование собранных данных для восстановления исходного порядка строк и столбцов.
Постобработка (post_processing):

Копирование собранных данных обратно в выходной буфер на корневом процессе.

2024-12-15 22:07 UTC, mateusxap requested changes

2024-12-15 22:07 UTC, mateusxap commented on tasks/mpi/anufriev_d_linear_image/func_tests/main_anufriev.cpp
> +#include <vector>
already included in hpp

2024-12-15 22:07 UTC, mateusxap commented on tasks/mpi/anufriev_d_linear_image/func_tests/main_anufriev.cpp
> +#include <numeric>
remove unused lib

2024-12-15 22:07 UTC, mateusxap commented on tasks/mpi/anufriev_d_linear_image/perf_tests/main_anufriev.cpp
> +#include <vector>
already included in hpp

2024-12-15 22:07 UTC, mateusxap commented on tasks/mpi/anufriev_d_linear_image/src/ops_mpi_anufriev.cpp
> +#include <numeric>
remove unused lib 
already included in hpp

2024-12-15 22:07 UTC, mateusxap commented on tasks/seq/anufriev_d_linear_image/func_tests/main_anufriev.cpp
> +#include <numeric>
remove unused lib

2024-12-15 22:07 UTC, mateusxap commented on tasks/seq/anufriev_d_linear_image/perf_tests/main_anufriev.cpp
> +#include <vector>
already included in hpp

2024-12-15 22:07 UTC, mateusxap commented on tasks/seq/anufriev_d_linear_image/perf_tests/main_anufriev.cpp
> +#include <numeric>
remove unused lib

2024-12-15 22:07 UTC, mateusxap commented on tasks/seq/anufriev_d_linear_image/src/ops_seq_anufriev.cpp
> +#include <numeric>
remove unused lib

2024-12-16 19:58 UTC, sk1er52 commented on tasks/mpi/anufriev_d_linear_image/func_tests/main_anufriev.cpp
> +#include <vector>
fixed

2024-12-16 19:58 UTC, sk1er52 commented on tasks/mpi/anufriev_d_linear_image/func_tests/main_anufriev.cpp
> +#include <numeric>
fixed

2024-12-16 19:58 UTC, sk1er52 commented on tasks/mpi/anufriev_d_linear_image/perf_tests/main_anufriev.cpp
> +#include <vector>
fixed

2024-12-16 19:59 UTC, sk1er52 commented on tasks/mpi/anufriev_d_linear_image/src/ops_mpi_anufriev.cpp
> +#include <numeric>
fixed

2024-12-16 19:59 UTC, sk1er52 commented on tasks/seq/anufriev_d_linear_image/func_tests/main_anufriev.cpp
> +#include <numeric>
fixed

2024-12-16 19:59 UTC, sk1er52 commented on tasks/seq/anufriev_d_linear_image/perf_tests/main_anufriev.cpp
> +#include <vector>
fixed

2024-12-16 19:59 UTC, sk1er52 commented on tasks/seq/anufriev_d_linear_image/src/ops_seq_anufriev.cpp
> +#include <numeric>
fixed

2024-12-17 00:31 UTC, mateusxap approved these changes

2024-12-17 14:32 UTC, ValeraDanger approved these changes

2024-12-19 09:37 UTC, aobolensk approved these changes

2024-12-20 14:50 UTC, allnes commented on tasks/mpi/anufriev_d_linear_image/func_tests/main_anufriev.cpp
> +          int cc = std::min(std::max(c + kc, 0), width - 1);
could you describe why do you use min and max?

2024-12-20 14:51 UTC, allnes commented on tasks/mpi/anufriev_d_linear_image/src/ops_mpi_anufriev.cpp
> +    MPI_Irecv(recv_left.data(), height_, MPI_INT, left, 1, comm, &reqs_left[req_count_left++]);
What do you use non-blocked operations for?

2024-12-20 16:52 UTC, sk1er52 commented on tasks/mpi/anufriev_d_linear_image/func_tests/main_anufriev.cpp
> +          int cc = std::min(std::max(c + kc, 0), width - 1);
The use of std::min and std::max here is used to process the edge pixels of the image. When a filter is applied to pixels on the edge of an image, neighboring pixels may fall outside the acceptable range of indexes. To avoid exceeding the boundaries of the array and ensure the correct application of the filter, we limit the indexes rr and cc to values from 0 to height - 1 and from 0 to width - 1, respectively. This allows you to use mirroring of the borders or repetition of the extreme pixel values when calculating the weighted average.

2024-12-20 18:48 UTC, sk1er52 commented on tasks/mpi/anufriev_d_linear_image/src/ops_mpi_anufriev.cpp
> +    MPI_Irecv(recv_left.data(), height_, MPI_INT, left, 1, comm, &reqs_left[req_count_left++]);
If I use blocking operations, my functional tests fall due to deadlock, but I think I can change my code using blocking operations if this is really required

2024-12-21 22:03 UTC, sk1er52 commented on tasks/mpi/anufriev_d_linear_image/src/ops_mpi_anufriev.cpp
> +    MPI_Irecv(recv_left.data(), height_, MPI_INT, left, 1, comm, &reqs_left[req_count_left++]);
fixed, I replaced the non-blocking MPI_Isend and MPI_Irecv operations with the blocking MPI_Sendrecv ones. In the else blocks, I now copy the first and last local columns in the halo area, which corresponds to the boundary conditions.

2024-12-22 22:16 UTC, allnes approved these changes

2024-12-22 22:17 UTC, merged