Суворов Дмитрий. Задача 2. Вариант 10. Топология сети "Линейка".
learning-process/ppc-2024-autumn pull request #482
Opened 2024-12-08 16:10 UTC by suvorovDm-1

MPI:
Реализован следующий функционал:
Сгенерированный случайный вектор передаётся процессу с рангом 0. Он передает этот вектор процессу с рангом 1. Аналогично все последующие процессы принимают вектор данных от процесса с рангом на 1 меньше своего и передают процессу с рангом на 1 больше своего. Передача вектора происходит исключительно с помощью методов world.send() и world.recv(). Таким образом вектор данных оказывается у процесса с рангом N -1 (где N - общее кол-во процессов).
Для проверки корректности работы программы процессы передают от себя к каждому следующему вектор, в который каждый запускающийся процесс пишет свой ранг. Если этот вектор будет хранить числа от 0 до N - 1 по порядку, то процессы запускались в линейном, правильном порядке.
Также для проверки корректности передачи данных, вектор данных проверяется на целостность в N - 1 процессе. Для этого из процесса с рангом 0 дополнительно изначальный вектор отправляется в процесс с рангом N - 1. В процессе с рангом N - 1 сравниваются два вектора: прошедший всю линию, полученный от процесса с рангом N - 2 и проверочный, пришедший от процесса с рангом 0.
Процесс N - 1 не имеет возможности запускать в тестах вывод информации (в том числе встроенные функции проверки EXCEPT_* и ASSERT_*, так как в main() подобное право имеет только процесс с рангом 0), следовательно, для проверки результатов, процесс с рангом N - 1 отправляет 1 в процесс с рангом 0 при равных исходном и полученным им векторах данных и при корректном векторе порядка пересылки. Иначе отправляет нулевому процессу число 0.
(Можно было просто отправлять полученный N - 1 процессом вектор к 0 процессу и там делать проверки, но тогда топология "Линейка" превращается в топологию "Кольцо". Именно из этих соображений я проверяю корректность работы в N - 1 процессе, а результат проверки уже отправляется в 0 процесс и им проверяется и выводится в тестах).

Функциональные тесты проверяют корректность работы с различным числом элементов в исходном векторе данных.

2024-12-08 17:45 UTC, korablev-vm requested changes

2024-12-08 17:45 UTC, korablev-vm commented on tasks/mpi/suvorov_d_linear_topology/func_tests/line_topo_f_tests.cpp
> +}
I suggest making result_data a boolean variable to increase the readability of the code.

2024-12-08 17:45 UTC, korablev-vm commented on tasks/mpi/suvorov_d_linear_topology/func_tests/line_topo_f_tests.cpp
> +  }
Here you can simply refer to result_data. In fact, you're just accessing the same piece of memory using different variable names.

2024-12-08 19:12 UTC, GrayPirat requested changes

2024-12-08 19:12 UTC, GrayPirat commented on tasks/mpi/suvorov_d_linear_topology/func_tests/line_topo_f_tests.cpp
> +  }
You need to add some tests. Like for 0 and 1 size vector

2024-12-08 19:22 UTC, Torcna commented on tasks/mpi/suvorov_d_linear_topology/src/linear_topology.cpp
> +  boost::mpi::broadcast(world, data_size, 0);
There s no place for mpi-functions in pre_processing. All of them should be in run.
Please change that.

2024-12-08 19:22 UTC, Torcna commented on tasks/mpi/suvorov_d_linear_topology/src/linear_topology.cpp
> +      world.send(0, 3, SUCCESS);
The same here.

2024-12-08 19:22 UTC, Torcna commented on tasks/mpi/suvorov_d_linear_topology/func_tests/line_topo_f_tests.cpp
> +  std::vector<int> result_data(1, 0);
To be honest, i find it "over-kill" to have a vector for one bool, ur checking in ASSERT_TRUE. You may not agree with me, but i suggest u to do that.

2024-12-08 23:44 UTC, GrayPirat approved these changes

2024-12-09 12:42 UTC, suvorovDm-1 commented
All wishes were taken into account. Please check.
@korablev-vm , @Torcna

2024-12-09 12:46 UTC, korablev-vm approved these changes

2024-12-09 13:48 UTC, Torcna approved these changes

2024-12-11 20:37 UTC, aobolensk approved these changes

2024-12-15 20:00 UTC, allnes approved these changes

2024-12-15 20:00 UTC, merged