Дудченко Олеся. Задача 2. Вариант 4. Спящий брадобрей.
learning-process/ppc-2024-autumn pull request #484
Opened 2024-12-08 17:33 UTC by Uzzika

Задача "Спящий брадобрей" заключается в моделировании процесса обслуживания клиентов в парикмахерской с ограниченным количеством мест. Моделирование включает в себя решение задачи многозадачности с учётом синхронизации потоков, что требует использования многозадачных алгоритмов и подходов. В задаче присутствуют два типа потоков: клиенты, которые приходят поочередно, и парикмахер, который обслуживает клиентов, выполняя операции в зависимости от состояния салона.

Основная цель — эффективно управлять процессами клиентов и парикмахера с использованием алгоритма, который обеспечивает корректное выполнение задачи в условиях ограниченного числа мест для ожидания и обслуживания. Для этого необходимо правильно синхронизировать поток клиентов, которые могут приходить в любой момент времени, и парикмахера, который обслуживает их по очереди.

Реализация задачи состоит из двух частей. В первой части происходит моделирование параллельного обслуживания клиентов: потоки клиентов и парикмахера синхронизируются через механизмы блокировок или условных переменных. Во второй части анализируется производительность решения с использованием различных стратегий распределения времени и ресурсов между потоками. Это позволяет оценить эффективность работы алгоритма в условиях разных входных данных.

Для параллельной реализации используется подход с распределением работы между несколькими процессами или потоками, что позволяет эффективно обрабатывать большое количество клиентов и ускорить выполнение задачи.

2024-12-12 16:39 UTC, korablev-vm requested changes
Также рекомендую удалить все комментарии из кода

2024-12-12 16:39 UTC, korablev-vm commented on tasks/seq/dudchenko_o_sleeping_barber/src/ops_seq.cpp
> +  }
Выглядит как часть валидации (validation)

2024-12-12 16:39 UTC, korablev-vm commented on tasks/seq/dudchenko_o_sleeping_barber/src/ops_seq.cpp
> +
для чего Вы это используете?

2024-12-12 16:39 UTC, korablev-vm commented on tasks/mpi/dudchenko_o_sleeping_barber/include/ops_mpi.hpp
> +}  // namespace dudchenko_o_sleeping_barber_mpi
в этом же файле должна быть еще и seq реализациЯ, чтобы сравнивать результаты тестов в func_tests

2024-12-12 16:39 UTC, korablev-vm commented on tasks/mpi/dudchenko_o_sleeping_barber/func_tests/main.cpp
> +}
Суть функциональных тестов в сравнии последовательной и параллельной версии. Последовательную версию мы тщательно тестируем внутри директории seq

2024-12-13 15:57 UTC, decl1 requested changes

2024-12-13 15:57 UTC, decl1 commented on tasks/mpi/dudchenko_o_sleeping_barber/func_tests/main.cpp
> +    if (world.rank() == 0) {
[if (world.size() > 1)] and [if (world.rank() == 0)] are mutually exclusive, the conditions of calling [if (world.rank() == 0)] inside [if (world.size() > 1)] means that it will never be executed, hence ASSERT_EQ(global_res, 0); never appeared

2024-12-13 15:57 UTC, decl1 commented on tasks/mpi/dudchenko_o_sleeping_barber/func_tests/main.cpp
> +    if (world.rank() == 0) {
same

2024-12-13 15:57 UTC, decl1 commented on tasks/mpi/dudchenko_o_sleeping_barber/func_tests/main.cpp
> +    if (world.rank() == 0) {
same

2024-12-13 15:57 UTC, decl1 commented on tasks/mpi/dudchenko_o_sleeping_barber/func_tests/main.cpp
> +    if (world.rank() == 0) {
same

2024-12-13 15:57 UTC, decl1 commented on tasks/mpi/dudchenko_o_sleeping_barber/func_tests/main.cpp
> +    if (world.rank() == 0) {
same

2024-12-13 16:00 UTC, decl1 requested changes

2024-12-13 16:00 UTC, decl1 commented on tasks/mpi/dudchenko_o_sleeping_barber/func_tests/main.cpp
> +  }
[if (world.size() > 1)] and [if (world.rank() == 0)] are mutually exclusive, the conditions of calling [if (world.rank() == 0)] inside [if (world.size() > 1)] means that it will never be executed, hence ASSERT_EQ(global_res, 0); never appeared

Same on lines:
115 - 126
143 - 153
170 - 181

2024-12-22 22:18 UTC, allnes commented on tasks/mpi/dudchenko_o_sleeping_barber/src/ops_mpi.cpp
> +        }
please use non-blocked mpi fucntions

2024-12-29 19:38 UTC, closed without merging