Иванов Михаил. Задача 2. Вариант 19. Метод Гаусса – ленточная горизонтальная схема.
learning-process/ppc-2024-autumn pull request #487
Opened 2024-12-08 18:12 UTC by misha-ivanov

**Входные данные:**
- расширенная матрица (матрица коэффициентов и вектор решения)
- количество уравнений в системе (количество строк)

**Последовательная версия:**

Прямой ход:
- На каждой итерации:
- - поиск максимального элемента (опорного элемента) в опорном стобце
- - если максимальный элемент находится не на опорной строке, меняем местами опорную строку и строку с максимальным элементом
- - делим все элементы опорной строки на опорный элемент
- - вычитаем из каждой строки ниже опорной опорную строку, умноженную на элемент с координатами (номер строки, номер опорного столбца)

Обратный ход:
- Во время хода с последней строки к первой последовательно получаем значение решения с индексом строки

**Параллельная версия:**

Прямой ход:
- На каждой итерации:
- - поиск максимального элемента (опорного элемента) в опорном стобце расширенной матрицы (`extended_matrix`)
- - если максимальный элемент находится не на опорной строке, меняем местами опорную строку и строку с максимальным элементом
- - делим все элементы опорной строки на опорный элемент
- - рассылаем каждому процессу через `scatterv` последовательность строк для обработки
- - рассылка всем процессам через broadcast опорную строку
- - в каждом процессе вычитаем из каждой строки опорную строку, умноженную на элемент с координатами (номер строки, номер опорного столбца)
- - собираем в расширенную матрицу (`extended_matrix`) все обработанные строки через `gatherv`

Обратный ход:
- Во время хода с последней строки к первой последовательно получаем значение решения с индексом строки

**Генерация матриц для тестов:**
Генерация расширенной матрицы из слияния нижнетреугольной единичной матрицы и вектора с решением, и насыщение её случайными значениями, посредством элементарных преобразований и проходом сначала снизу вверх, а потом сверху вниз.

2024-12-08 20:40 UTC, MaxikGuy requested changes

2024-12-08 20:40 UTC, MaxikGuy commented on tasks/mpi/ivanov_m_gauss_horizontal/src/ops_mpi.cpp
> +  number_of_equations = *reinterpret_cast<int*>(taskData->inputs[1]);
In pre_processing you don't check if number_of_equations negative or equals zero. Fix it and add tests for it.

2024-12-08 20:40 UTC, MaxikGuy commented on tasks/mpi/ivanov_m_gauss_horizontal/src/ops_mpi.cpp
> +
You should check if number_of_equations is relevant or not before using determinant. Add tests.

2024-12-08 20:59 UTC, MishaRysev commented on tasks/mpi/ivanov_m_gauss_horizontal/func_tests/main.cpp
> +
add tests with small sizes of matrix to check algorithms correctness

2024-12-08 20:59 UTC, MishaRysev commented on tasks/mpi/ivanov_m_gauss_horizontal/src/ops_mpi.cpp
> +bool ivanov_m_gauss_horizontal_mpi::TestMPITaskSequential::validation() {
validation should assess if inputs and outputs are adequate. You shouldn't check their value, compare their sizes, for example, or something like that, and write new tests for it

2024-12-08 20:59 UTC, MishaRysev commented on tasks/seq/ivanov_m_gauss_horizontal/src/ops_seq.cpp
> +bool ivanov_m_gauss_horizontal_seq::TestTaskSequential::validation() {
validation should assess if inputs and outputs are adequate. You shouldn't check their value, compare their sizes, for example, or something like that, and write new tests for it

2024-12-08 21:55 UTC, misha-ivanov commented on tasks/mpi/ivanov_m_gauss_horizontal/src/ops_mpi.cpp
> +  number_of_equations = *reinterpret_cast<int*>(taskData->inputs[1]);
Fixed here and in sequential version

2024-12-08 21:55 UTC, misha-ivanov commented on tasks/mpi/ivanov_m_gauss_horizontal/src/ops_mpi.cpp
> +
Fixed here and in sequential version too)

2024-12-08 21:56 UTC, misha-ivanov commented on tasks/mpi/ivanov_m_gauss_horizontal/func_tests/main.cpp
> +
Have done!

2024-12-08 21:57 UTC, misha-ivanov commented on tasks/mpi/ivanov_m_gauss_horizontal/src/ops_mpi.cpp
> +bool ivanov_m_gauss_horizontal_mpi::TestMPITaskSequential::validation() {
Oh, I got it. I hope I rewrote it correctly.

2024-12-08 21:58 UTC, misha-ivanov commented on tasks/seq/ivanov_m_gauss_horizontal/src/ops_seq.cpp
> +bool ivanov_m_gauss_horizontal_seq::TestTaskSequential::validation() {
Fixed too

2024-12-09 07:07 UTC, MaxikGuy approved these changes

2024-12-09 08:48 UTC, MishaRysev approved these changes

2024-12-12 06:32 UTC, aobolensk approved these changes

2024-12-15 20:02 UTC, allnes approved these changes

2024-12-15 20:02 UTC, merged