Бесхмельнова Ксения. Задача 1. Вариант 8. Нахождение наиболее отличающихся по значению соседних элементов вектора.
learning-process/ppc-2024-autumn pull request #49
Opened 2024-10-27 12:08 UTC by KseniyaBeskhmelnova

Описание последовательной задачи:
Задача заключается в нахождении пары соседних элементов вектора с наибольшей разницей значений. Сначала находится разница первого и второго элементов вектора, она берется за максимальную, а индекс первого элемента искомой пары за 0. Затем начинается проход по вектору, начиная со второго элемента. Считаем разницу между соседними элементами и сравниваем ее с текущим максимумом, если больше - меняем текущий максимум и индекс первого элемента пары. По окончании прохода по вектору получаем индекс первого элемента пары наиболее отличающихся соседних элементов вектора. Соответственно в результат записываем этот элемент и следующий за ним.

Описание MPI задачи:
В реализации с помощью MPI данные распределяются между процессами с использованием scatterv между процессами. Основной процесс загружает исходные данные и делит их с учётом равномерного распределения и остатка, чтобы каждый процесс получил данные корректного размера. Процессы выполняют локальные вычисления на своих частях данных, а также проверяют разницу на границах соседних процессов, затем результаты собираются с помощью reduce, для нахождения глобального результата. Для обеспечения верной работы алгоритма используется не индекс первого элемента искомой пары, как в последовательной реализации, а структура, которая хранит оба элемента пары и разницу.

2024-10-29 19:35 UTC, allnes commented on tasks/mpi/beskhmelnova_k_most_different_neighbor_elements/func_tests/main.cpp
> -#include <boost/mpi/communicator.hpp>
please don't change not own files

2024-10-29 19:36 UTC, allnes commented on tasks/seq/example/src/ops_seq.cpp
> -
please don't remove not own files

2024-10-30 14:36 UTC, KseniyaBeskhmelnova commented on tasks/seq/example/src/ops_seq.cpp
> -
Done

2024-10-30 17:28 UTC, Torcna reviewed
I suggest you to add a test for vector with size 0, 1, 2 and check if evrth is ok!

2024-10-31 00:45 UTC, allnes approved these changes

2024-10-31 01:07 UTC, aobolensk requested changes

2024-10-31 01:07 UTC, aobolensk commented on tasks/mpi/example/src/ops_mpi.cpp
> +  std::this_thread::sleep_for(20ms);
Please, remove this

2024-10-31 02:24 UTC, aobolensk approved these changes

2024-10-31 03:24 UTC, merged