Сдобнов Владимир. Задача 2. Вариант 22. Итеративный метод Якоби.
learning-process/ppc-2024-autumn pull request #492
Opened 2024-12-08 22:46 UTC by VladimirSdobnov

Суть метода: вычисление решения СЛАУ путем вычисления членов сходящейся последовательности.

Входные данные: Программа на вход принимает size - размер матрицы и вектора свободных челнов, диагонально превосходящую (элементы на главной диагонали максимальные в строке) квадратную матрицу развернутую в вектор и столбец свободных членов.
Выходные данные: вектор с приближенными значениями х

Последовательное решение: на первой итерации задаем приближенные значения равные 0. На каждой итерации вычисляем новые приближенные значения х. После вычисления сравниваем новые и старые значения х, если максимальная разность между ними меньше заданной величины, то выходим из итеративного цикла и возращаем ответ. Если цикл проделал 100 итераций, но так и не достиг заданного порога точности, то возвращаем то, что получилось.

Параллельное решение: Делим строки матрицы между процессами. Каждый процесс получает необходимые старые значения х и строки исходной матрицы и на их основании вычисляет новые значения x, после чего родительский процесс собирает новые значения. После получения новых значений родительский процесс проверяет точность значений. Если она достаточна, то рассылает по прочим процессам флаг остановки.

2024-12-09 11:15 UTC, decl1 requested changes

2024-12-09 11:15 UTC, decl1 commented on tasks/mpi/Sdobnov_V_iteration_method_yakoby/src/ops_mpi.cpp
> +void calculate_mat_part_param(int rows, int num_proc, std::vector<int>& sizes, std::vector<int>& offsets) {
Wrap it in namespace, or make it static

2024-12-09 11:15 UTC, decl1 commented on tasks/mpi/Sdobnov_V_iteration_method_yakoby/src/ops_mpi.cpp
> +void calculate_free_members_part_param(int len, int num_proc, std::vector<int>& sizes, std::vector<int>& offsets) {
Wrap it in namespace, or make it static

2024-12-09 11:15 UTC, decl1 commented on tasks/mpi/Sdobnov_V_iteration_method_yakoby/src/ops_mpi.cpp
> +bool isDiagonallyDominant(int n, const std::vector<double>& A) {
Wrap it in namespace, or make it static

2024-12-09 11:15 UTC, decl1 commented on tasks/seq/Sdobnov_V_iteration_method_yakoby/src/ops_seq.cpp
> +bool isDiagonallyDominant(int n, const std::vector<double>& A) {
Wrap it in namespace, or make it static

2024-12-09 19:11 UTC, decl1 approved these changes

2024-12-09 19:45 UTC, emilien-gus requested changes

2024-12-09 19:45 UTC, emilien-gus commented on tasks/mpi/Sdobnov_V_iteration_method_yakoby/include/ops_mpi.hpp
> +namespace Sdobnov_iteration_method_yakoby {
Please, add mpi in you namespace name. Also do it everywhere where it mentioned.

2024-12-09 19:45 UTC, emilien-gus commented on tasks/seq/Sdobnov_V_iteration_method_yakoby/include/ops_seq.hpp
> +namespace Sdobnov_iteration_method_yakoby {
Please, add seq in you namespace name. Also do it everywhere where it mentioned.

2024-12-10 09:23 UTC, emilien-gus commented on tasks/mpi/Sdobnov_V_iteration_method_yakoby/src/ops_mpi.cpp
> +  if (world.rank() == 0) {
You can do same scatterv call in all processes. Also you can do it for gatherv

2024-12-10 11:47 UTC, emilien-gus approved these changes

2024-12-12 06:34 UTC, aobolensk requested changes

2024-12-12 06:34 UTC, aobolensk commented on tasks/mpi/Sdobnov_V_iteration_method_yakoby/func_tests/main.cpp
> +TEST(Sdobnov_V_iteration_method_yakoby_par, InvalidMatrixWithoutDiagonalDominance) {
Please add some random tests to func_tests

2024-12-13 03:23 UTC, aobolensk approved these changes

2024-12-15 20:05 UTC, allnes approved these changes

2024-12-15 20:05 UTC, merged