Прохоров Никита. Задача 2. Вариант 1. Задача «Производители-потребители».
learning-process/ppc-2024-autumn pull request #495
Opened 2024-12-09 12:14 UTC by antihype320

##Параллельная реализация

##Основные этапы:
1. Предобработка данных:
-	 Процесс-менеджер (ранг 0) генерирует массив данных (producer_data) или использует предварительно заданный.
-	Размер данных отправляется всем процессам с использованием MPI_Broadcast.
2.  Разделение данных:
-	Процесс-менеджер делит массив на части и отправляет их процессам-производителям.
-	Размер частей рассчитывается пропорционально количеству процессов, а оставшиеся элементы распределяются между последними процессами.
3. Буферизация данных:
-	Производители помещают свои части данных в общий буфер, синхронизируясь с потребителями через MPI_Barrier для предотвращения переполнения.
4. Обработка данных потребителями:
-	Потребители извлекают данные из буфера, выполняют обработку (например, удвоение значений) и сохраняют результаты.
-	После завершения обработки результаты отправляются процессу-менеджеру.
5. Сбор и накопление результатов:
-	Процесс-менеджер получает обработанные данные от потребителей, аккумулирует их и сохраняет в выходные данные.
6. Синхронизация завершения:
-	Используется флаг processing_complete для завершения работы всех процессов и предотвращения зацикливания.

2024-12-09 12:49 UTC, kobych commented on tasks/mpi/prokhorov_n_producer_customer/include/ops_mpi.hpp
> +      : Task(std::move(taskData_)), ops("default_operation"), world() {}
please remove world():

2024-12-09 13:10 UTC, KADCHDR requested changes

2024-12-09 13:10 UTC, KADCHDR commented on tasks/mpi/prokhorov_n_producer_customer/src/ops_mpi.cpp
> +    if (world.rank() == 0) {
remove this check

2024-12-09 14:06 UTC, antihype320 commented on tasks/mpi/prokhorov_n_producer_customer/include/ops_mpi.hpp
> +      : Task(std::move(taskData_)), ops("default_operation"), world() {}
fix

2024-12-09 14:08 UTC, antihype320 commented on tasks/mpi/prokhorov_n_producer_customer/src/ops_mpi.cpp
> +    if (world.rank() == 0) {
fix

2024-12-09 14:28 UTC, kobych approved these changes

2024-12-11 22:17 UTC, antihype320 commented
@aobolensk @allnes check please

2024-12-12 06:35 UTC, aobolensk requested changes
Please, do not modify submodules

2024-12-13 17:55 UTC, closed without merging