Рысев Михаил. Задача 2. Вариант 14. Топология Гиперкуб
learning-process/ppc-2024-autumn pull request #497
Opened 2024-12-09 12:33 UTC by MishaRysev

Представленная реализация топологии "Гиперкуб" содержит в себе следующие этапы:

1. **Валидация**. На данном этапе происходит проверка на равенство количества запущенных процессов какой-либо степени двойки. Для иного количества процессов данная топология не предназначена.

2. **Предобработка**. На данном этапе каждый процесс получает информацию о том, кто является отправителем, а кто получателем текущего набора данных. По мимо этого, процесс-отправитель получает сам набор данных.

3. **Передача**. Данные последовательно пересылаются от отправителя к получателю. Каждое новое звено цепи передач вычисляется при помощи побитовых операций. Во время исполнения данного шага, каждый узел, ждёт сообщения от одного из своих соседей. Каждый узел, входящий в цепь передач, получает сообщение и передаёт его далее. Как только данные дошли до получателя, тот отправляет сообщение о завершении процесса передачи отправителю. Отправитель, при получении сообщения о завершении, оповещает все ожидающие(не вошедшие в цепь передач) узлы о том, что передача завершена и ожидать больше ничего не нужно.

4. **Постобработка**. На данном этапе в процессе получателе сохраняются полученные данные, а также пройденный ими путь.

При комбинации побитовых операций "побитовое И" и "исключающее ИЛИ" удаётся достичь кратчайшего из возможных путей для передачи данных от одного узла другому. Для любой пары узлов это расстояние будет равняться расстоянию Хэмминга между двоичными представлениями номеров этих узлов.

2024-12-09 15:49 UTC, misha-ivanov requested changes

2024-12-09 15:49 UTC, misha-ivanov commented on tasks/mpi/rysev_m_hypercube/src/ops_mpi.cpp
> +
Most of these libraries are not used in this file and some of them are not used in the project at all (for example, string)

2024-12-09 15:49 UTC, misha-ivanov commented on tasks/mpi/rysev_m_hypercube/src/ops_mpi.cpp
> +    if (*reinterpret_cast<int *>(taskData->inputs[0]) >= size || *reinterpret_cast<int *>(taskData->inputs[0]) < 0)
This if can be replaced by return with the same meaning

2024-12-09 15:49 UTC, misha-ivanov commented on tasks/mpi/rysev_m_hypercube/func_tests/main.cpp
> +
Please, add tests, when validation returns false

2024-12-28 20:04 UTC, allnes commented on tasks/mpi/rysev_m_hypercube/func_tests/main.cpp
> +  if (world.size() < 2 || (world.size() & (world.size() - 1)) != 0) {
please describe this comparison

2024-12-29 19:39 UTC, closed without merging