Коробейников Арсений. Задача 1. Вариант 15. Нахождение максимальных значений по строкам матрицы.
learning-process/ppc-2024-autumn pull request #50
Opened 2024-10-27 13:45 UTC by Arseny-Korobeinikov

Цель: Найти максимальные элементы в каждой строке матрицы. 

Последовательное решение задачи:
Запустить цикл по строкам матрицы, для каждой строки найти максимальный элемент и положить его в результирующий вектор. В результирующем векторе на i-ой позиции стоит максимальный элемент i-ой строки.

Параллельное решение задачи:
Представляем матрицу, как один большой массив, делим его на количество процессов и каждому процессу отдаём свою часть. Поскольку элементов может быть не кратно количеству процессов, то последнему процессу отдаём остаток от деления количества элементов матрицы на количество процессов. Каждый процесс считает на своём участке максимальные элементы для тех строк, которые он затрагивает (даже частично), и редуцирует их в результирующий вектор. Поскольку редуцирование это коллективная операция, и в i-ый элемент результирующего вектора будет ожидаться ответ от каждого процесса, то нам необходимо каждому процессу также средуцировать INT_MIN в те элементы результирующего вектора, на которые наш процесс не должен оказывать влияние. В конечно итоге мы получим правильный результирующий вектор.

2024-10-27 14:17 UTC, hasanyanovk commented on tasks/mpi/korobeinikov_a_max_elements_in_rows_of_matrix/src/ops_mpi_korobeinikov.cpp
> +      world.send(proc, 0, input_.data() + proc * delta, delta + taskData->inputs_count[0] % world.size());
bad idea to push extra elements to one process, imagine:
you have N processes and matrix.size() == k * N + (N - 1)
all processes except for the last one will recieve k elements, but the last will have k + N - 1 element
the work will not be distributed evenly at all

2024-10-27 14:18 UTC, hasanyanovk commented on tasks/mpi/korobeinikov_a_max_elements_in_rows_of_matrix/src/ops_mpi_korobeinikov.cpp
> +    }
can use std::copy or std::vector::assign

2024-10-27 14:21 UTC, hasanyanovk commented on tasks/mpi/korobeinikov_a_max_elements_in_rows_of_matrix/src/ops_mpi_korobeinikov.cpp
> +    }
you can unite checks and use `return (expr2 && expr2 && ... && exprN` to reduce the number of comparisons

2024-10-27 15:05 UTC, Arseny-Korobeinikov commented on tasks/mpi/korobeinikov_a_max_elements_in_rows_of_matrix/src/ops_mpi_korobeinikov.cpp
> +    }
fixed

2024-10-27 15:05 UTC, Arseny-Korobeinikov commented on tasks/mpi/korobeinikov_a_max_elements_in_rows_of_matrix/src/ops_mpi_korobeinikov.cpp
> +    }
fixed

2024-10-27 15:08 UTC, Arseny-Korobeinikov commented on tasks/mpi/korobeinikov_a_max_elements_in_rows_of_matrix/src/ops_mpi_korobeinikov.cpp
> +      world.send(proc, 0, input_.data() + proc * delta, delta + taskData->inputs_count[0] % world.size());
I don't think this is a bad idea, because in the worst case, N-1 elements will fall on the last process, their processing will take a minimum amount of time, since the number of processes is a small number.

2024-10-27 15:29 UTC, hasanyanovk approved these changes

2024-10-27 16:00 UTC, MatveyKurakin commented on tasks/mpi/korobeinikov_a_max_elements_in_rows_of_matrix/func_tests/main_korobeinikov.cpp
> +  std::vector<int> global_matrix{3, 17, 5, -1, 2, -3, 11, 12, 13, -7, 4, 9};
You fill global_matrix with random numbers in line 78

2024-10-27 16:01 UTC, MatveyKurakin commented on tasks/mpi/korobeinikov_a_max_elements_in_rows_of_matrix/func_tests/main_korobeinikov.cpp
> +
Add a test so that validation returns false

2024-10-27 16:07 UTC, Arseny-Korobeinikov commented on tasks/mpi/korobeinikov_a_max_elements_in_rows_of_matrix/func_tests/main_korobeinikov.cpp
> +
fixed

2024-10-27 16:07 UTC, Arseny-Korobeinikov commented on tasks/mpi/korobeinikov_a_max_elements_in_rows_of_matrix/func_tests/main_korobeinikov.cpp
> +  std::vector<int> global_matrix{3, 17, 5, -1, 2, -3, 11, 12, 13, -7, 4, 9};
fixed

2024-10-27 18:15 UTC, MatveyKurakin approved these changes

2024-10-29 00:18 UTC, aobolensk requested changes

2024-10-29 00:18 UTC, aobolensk commented on tasks/mpi/korobeinikov_a_max_elements_in_rows_of_matrix/func_tests/main_korobeinikov.cpp
> +TEST(max_elements_in_rows_of_matrix_mpi, Test_3_false_validation) {
Please add
1. empty matrix test
2. 1 row matrix test

2024-10-29 00:18 UTC, aobolensk commented on tasks/seq/korobeinikov_a_max_elements_in_rows_of_matrix/perf_tests/main_korobeinikov.cpp
> +  // ASSERT_EQ(right_answer,seq_res);
Please get rid of commented out code

2024-10-29 20:38 UTC, Arseny-Korobeinikov commented on tasks/mpi/korobeinikov_a_max_elements_in_rows_of_matrix/func_tests/main_korobeinikov.cpp
> +TEST(max_elements_in_rows_of_matrix_mpi, Test_3_false_validation) {
Did it

2024-10-29 20:39 UTC, Arseny-Korobeinikov commented on tasks/seq/korobeinikov_a_max_elements_in_rows_of_matrix/perf_tests/main_korobeinikov.cpp
> +  // ASSERT_EQ(right_answer,seq_res);
Did it

2024-10-29 20:39 UTC, Arseny-Korobeinikov commented on tasks/mpi/korobeinikov_a_max_elements_in_rows_of_matrix/src/ops_mpi_korobeinikov.cpp
> +bool korobeinikov_a_test_task_mpi::TestMPITaskParallel::pre_processing() {
Did it

2024-10-30 00:46 UTC, aobolensk approved these changes

2024-10-31 00:40 UTC, allnes approved these changes

2024-10-31 00:40 UTC, merged