Наумов Богдан. Задача 2. Вариант 25. Сортировка пузырьком (алгоритм чет-нечетной перестановки).
learning-process/ppc-2024-autumn pull request #500
Opened 2024-12-09 16:50 UTC by BogdanNaumov

Задача состоит в разработке и реализации алгоритма пузырьковой сортировки двумя методами: последовательным  и параллельным. Оба подхода реализованы с использованием объектно-ориентированного программирования и протестированы на корректность.

Алгоритм пузырьковой сортировки:

Повторяющиеся проходы по массиву для сравнения соседних элементов.
 Перестановка элементов при нарушении порядка.
 Завершение работы при достижении полной упорядоченности.
 Последовательная версия :

Выполняет сортировку на одном процессе с использованием стандартных структур данных.
Параллельная версия :

 Распределяет данные между процессами с помощью MPI.
 Использует параллельные операции для повышения производительности.
 Тестирование:

Охватывает массивы разных типов: пустые, случайные, с повторяющимися элементами.

2024-12-09 18:25 UTC, ArtemMakadrai requested changes

2024-12-09 18:25 UTC, ArtemMakadrai commented on tasks/mpi/naumov_b_bubble_sort/src/ops_mpi.cpp
> +
delete try catch, it is not needed here

2024-12-09 19:45 UTC, BogdanNaumov commented on tasks/mpi/naumov_b_bubble_sort/src/ops_mpi.cpp
> +
fixed

2024-12-10 17:47 UTC, ArtemMakadrai approved these changes

2024-12-12 10:34 UTC, ArtemPch commented on tasks/mpi/naumov_b_bubble_sort/func_tests/main.cpp
> +  }
make it random

2024-12-12 10:42 UTC, BogdanNaumov commented on tasks/mpi/naumov_b_bubble_sort/func_tests/main.cpp
> +  }
fixed

2024-12-13 21:16 UTC, ArtemPch approved these changes

2024-12-14 11:06 UTC, aobolensk requested changes

2024-12-14 11:06 UTC, aobolensk commented on tasks/mpi/naumov_b_bubble_sort/func_tests/main.cpp
> +std::vector<int> getRandomVec(int size) {
Either make it static or wrap with namepsace

2024-12-14 11:06 UTC, aobolensk commented on tasks/mpi/naumov_b_bubble_sort/perf_tests/main.cpp
> +  const size_t count_size_vector = 120;
Please, increase array size for perf tests

2024-12-14 11:06 UTC, aobolensk commented on tasks/mpi/naumov_b_bubble_sort/src/ops_mpi.cpp
> +  MPI_Bcast(&total_size_, 1, MPI_INT, 0, MPI_COMM_WORLD);
Please, move data transfer to ::run() function

2024-12-15 07:17 UTC, BogdanNaumov commented on tasks/mpi/naumov_b_bubble_sort/src/ops_mpi.cpp
> +  MPI_Bcast(&total_size_, 1, MPI_INT, 0, MPI_COMM_WORLD);
fixed

2024-12-15 07:17 UTC, BogdanNaumov commented on tasks/mpi/naumov_b_bubble_sort/perf_tests/main.cpp
> +  const size_t count_size_vector = 120;
fixed

2024-12-15 07:17 UTC, BogdanNaumov commented on tasks/mpi/naumov_b_bubble_sort/func_tests/main.cpp
> +std::vector<int> getRandomVec(int size) {
fixed

2024-12-15 20:06 UTC, allnes approved these changes

2024-12-15 20:07 UTC, merged