Fix Revert. Бесхмельнова Ксения. Задача 2. Вариант 3. Обедающие философы.
learning-process/ppc-2024-autumn pull request #503
Opened 2024-12-09 18:02 UTC by KseniyaBeskhmelnova

Программа реализует задачу об обедающих философах с использованием MPI для параллельного взаимодействия между процессами. Каждый философ представляет отдельный процесс, который поочередно переходит через состояния THINKING, HUNGRY и EATING. Для перехода в состояние EATING философы запрашивают вилки(ресурсы), отправляя сообщения своим соседям, и освобождают их по завершении. Программа реализует механизм проверки взаимоблокировки (deadlock) и разрешает её, возвращая философа в состояние THINKING. Завершение программы происходит, когда все философы находятся в состоянии THINKING. Такая реализация обеспечивает синхронизацию процессов и управление доступом к разделяемым ресурсам.

Что исправлено: изменены названия функциональных тестов, теперь они соответствуют правилам. Также изменено время, которое философы проводят в состоянии THINKING и EATING.

2024-12-10 18:48 UTC, Torcna requested changes

2024-12-10 20:13 UTC, dima-dimka04 reviewed
![image](https://github.com/user-attachments/assets/e752e86a-80a5-41ff-b779-31fac930737a)
look it in readme.md

2024-12-10 20:13 UTC, dima-dimka04 commented on tasks/mpi/beskhmelnova_k_dinning_philosophers/perf_tests/main.cpp
> +  boost::mpi::communicator world;
name the perf_tests as written in the instruction

2024-12-10 20:13 UTC, dima-dimka04 commented on tasks/mpi/beskhmelnova_k_dinning_philosophers/perf_tests/main.cpp
> +  boost::mpi::communicator world;
same

2024-12-10 21:07 UTC, KseniyaBeskhmelnova commented on tasks/mpi/beskhmelnova_k_dinning_philosophers/src/dinning_philosophers.cpp
> +  return world.size() >= 2 && num_philosophers >= 2 && num_philosophers > 0;
you're right, I left only num_philosophers >= 2

2024-12-10 21:07 UTC, KseniyaBeskhmelnova commented on tasks/mpi/beskhmelnova_k_dinning_philosophers/src/dinning_philosophers.cpp
> +      }
done

2024-12-10 21:08 UTC, KseniyaBeskhmelnova commented on tasks/mpi/beskhmelnova_k_dinning_philosophers/func_tests/main.cpp
> +#include "mpi/beskhmelnova_k_dinning_philosophers/src/dinning_philosophers.cpp"
left only hpp files in include

2024-12-10 21:09 UTC, KseniyaBeskhmelnova commented on tasks/mpi/beskhmelnova_k_dinning_philosophers/perf_tests/main.cpp
> +  boost::mpi::communicator world;
renamed perf tests

2024-12-10 21:10 UTC, KseniyaBeskhmelnova commented
@Torcna, @dima-dimka04, i hope everything is right now :)

2024-12-11 08:03 UTC, dima-dimka04 approved these changes

2024-12-11 09:41 UTC, Torcna approved these changes

2024-12-12 06:36 UTC, aobolensk approved these changes

2024-12-15 20:07 UTC, allnes approved these changes

2024-12-15 20:07 UTC, merged