Цацын Александр. Задача 3. Вариант 30. "Повышение контраста полутонового изображения посредством линейной растяжки гистограммы"
learning-process/ppc-2024-autumn pull request #505
Opened 2024-12-09 21:21 UTC by KAPUSHA228

в последовательной версии один в один как на видосе
в параллельной версии выдаю локальные версии данных процессам, они считают количество разных пикселей, возвращают нулевому процессу, чтобы он просчитал их вес, иначе можно с ним ошибиться

2024-12-10 23:21 UTC, andrewmeow requested changes
алгоритм неправильный. точнее выполняет не ту задачу. в описании написано повышение контраста, а реализация выполняет как будто бы повышение общей интенсивности изображения

2024-12-10 23:32 UTC, andrewmeow requested changes

2024-12-10 23:32 UTC, andrewmeow commented on tasks/seq/tsatsyn_a_increasing_contrast_by_histogram/src/ops_seq.cpp
> +    std::cout << localka[i] << " ";
алгоритм неправильный. точнее выполняет не ту задачу... в описании написано повышение контраста, а 
ваша реализация выполняет как будто бы просто повышение общей интенсивности изображения, нет никакой работы отдельно с низкими/высокими тонами

2024-12-10 23:35 UTC, andrewmeow commented on tasks/seq/tsatsyn_a_increasing_contrast_by_histogram/src/ops_seq.cpp
> +    std::cout << localka[i] << " ";
видимо что-то перепутали
нужно именно разницу тонов повышать

2024-12-11 19:22 UTC, petr1core requested changes

2024-12-11 19:22 UTC, petr1core commented on tasks/mpi/tsatsyn_a_increasing_contrast_by_histogram/src/ops_mpi.cpp
> +      world.send(proc, 0, local_data);
```suggestion
      world.send(proc, 0, local_data);
      local_data.clear();
```
Я полагаю, вам следует поместить очистку вектора сюда.
И необходимо ли очищать вектор от локальных данных, который уже является чистым (строка: 41) и был только что создан на (строка: 32)?

2024-12-11 19:22 UTC, petr1core commented on tasks/mpi/tsatsyn_a_increasing_contrast_by_histogram/src/ops_mpi.cpp
> +        local_data.emplace_back(input_data[i]);
I suggest to use this instead of .emplace_back(input_data[i])
```suggestion
        local_data.insert(local_data.end(), input_data.begin() + i, input_data.end());
```

2024-12-11 20:46 UTC, KAPUSHA228 commented on tasks/seq/tsatsyn_a_increasing_contrast_by_histogram/src/ops_seq.cpp
> +    std::cout << localka[i] << " ";
алгоритм перделал

2024-12-11 20:46 UTC, KAPUSHA228 commented on tasks/mpi/tsatsyn_a_increasing_contrast_by_histogram/func_tests/main.cpp
> +//   std::vector<int32_t> global_sum;
fixed

2024-12-11 20:46 UTC, KAPUSHA228 commented on tasks/seq/tsatsyn_a_increasing_contrast_by_histogram/func_tests/main.cpp
> +//   const int count = 20;
fixed

2024-12-11 20:46 UTC, KAPUSHA228 commented on tasks/mpi/tsatsyn_a_increasing_contrast_by_histogram/src/ops_mpi.cpp
> +      world.send(proc, 0, local_data);
пофикшено

2024-12-11 20:52 UTC, KAPUSHA228 commented on tasks/mpi/tsatsyn_a_increasing_contrast_by_histogram/src/ops_mpi.cpp
> +        local_data.emplace_back(input_data[i]);
даже не совсем так, если бы шаг в цикле был i++ то да, но там шаг i+=world.size()

2024-12-12 06:48 UTC, petr1core approved these changes

2024-12-12 06:57 UTC, andrewmeow approved these changes

2024-12-13 15:35 UTC, aobolensk requested changes

2024-12-13 15:35 UTC, aobolensk commented on tasks/seq/tsatsyn_a_increasing_contrast_by_histogram/func_tests/main.cpp
> +  // in = getRandomVector(count_size_vector, 0, 255);
Please, remove redundant code parts

2024-12-13 15:35 UTC, aobolensk commented on tasks/mpi/tsatsyn_a_increasing_contrast_by_histogram/func_tests/main.cpp
> +  vec[1] = gen() % (1000) + 10;
```suggestion
  vec[0] = gen() % (1000);
  vec[1] = gen() % (1000);
```

2024-12-13 15:57 UTC, KAPUSHA228 commented on tasks/seq/tsatsyn_a_increasing_contrast_by_histogram/func_tests/main.cpp
> +  // in = getRandomVector(count_size_vector, 0, 255);
removed

2024-12-14 11:06 UTC, aobolensk approved these changes

2024-12-20 14:53 UTC, allnes commented on tasks/mpi/tsatsyn_a_increasing_contrast_by_histogram/func_tests/main.cpp
> +}
please check that interval = [0,255]

2024-12-20 14:53 UTC, allnes commented on tasks/mpi/tsatsyn_a_increasing_contrast_by_histogram/func_tests/main.cpp
> +}
and why do you have negative values in generator?

2024-12-20 14:59 UTC, KAPUSHA228 commented on tasks/mpi/tsatsyn_a_increasing_contrast_by_histogram/func_tests/main.cpp
> +}
не понял, что Вы имеете ввиду, у меня и так используется интервал [0,255] и нет негативных значений

2024-12-22 22:21 UTC, allnes commented on tasks/mpi/tsatsyn_a_increasing_contrast_by_histogram/func_tests/main.cpp
> +}
давайте я перефразирую, поставьте пожалуйста защиту также здесь, чтобы далее не было где-то ошибок в генерации изображений с плохими интервалами и вообще для эйто задачи интервал не может меняться, также у меня вопрос, почему у вас генерируется вектор с sz, у изображения две характиристики - высоты и ширина

2024-12-22 23:00 UTC, KAPUSHA228 commented on tasks/mpi/tsatsyn_a_increasing_contrast_by_histogram/func_tests/main.cpp
> +}
на вопрос "почему у вас генерируется вектор с sz, у изображения две характеристики - высота и ширина" - мне в тестах приходят 2 значения: высота и ширина из которых я создаю одномерный вектор размером = ширина*высота, т.к Вы на занятиях упоминали, что нельзя использовать вектор векторов. Но возможно это было применительно только ко 2 задаче, в таком случае сейчас переделаю

2024-12-23 01:24 UTC, KAPUSHA228 commented on tasks/mpi/tsatsyn_a_increasing_contrast_by_histogram/func_tests/main.cpp
> +}
@allnes пофикшено

2024-12-24 16:04 UTC, allnes approved these changes

2024-12-24 16:04 UTC, merged