Fix Revert. Созонов Илья. Задача 1. Вариант 7. Нахождение наиболее близких соседних элементов вектора.
learning-process/ppc-2024-autumn pull request #506
Opened 2024-12-09 21:34 UTC by sozozzya

**Описание последовательной задачи:**

1. Создаём переменную min и инициализируем её максимальным возможным значением INT_MAX.
2. Проходим по вектору, начиная с первого элемента до предпоследнего, и находим модуль разности между текущим элементом и следующим за ним.
3. Если модуль разности между ними меньше текущего значения min, обновляем min и запоминаем индекс текущего элемента вектора.

**Описание MPI задачи:**

1. Создаем новый вектор diff, состоящий из пар: модуль разности соседних элементов исходного вектора и соответствующего индекса.
2. Полученный вектор пар делится равномерно на сегменты по числу процессов.
3. Каждый сегмент данных отправляется от нулевого процесса остальным.
4. Каждый процесс находит наименьший элемент и соответствующий ему индекс в полученном сегменте данных.
5. После завершения локальных вычислений процессы возвращают результаты корневому процессу, где с помощью коллективной операции reduce находится наименьший модуль разности соседних элементов вектора и соответствующий индекс.

**Исправление:**
Изначально вектор делился между процессами на равное число блоков. Поэтому, если число элементов вектора не делилось нацело на число процессов, возникала ошибка. Во избежание этого, добавил функции, распределяющие элементы вектора между процессами так, чтобы все элементы вектора распределились между процессами правильно.

2024-12-10 09:19 UTC, ascannel requested changes

2024-12-10 09:19 UTC, ascannel commented on tasks/mpi/sozonov_i_nearest_neighbor_elements/src/ops_mpi.cpp
> +#include <algorithm>
i suugest you to remove unnecessary includes declared in task.hpp already, and aslo namespace

2024-12-10 09:19 UTC, ascannel commented on tasks/mpi/sozonov_i_nearest_neighbor_elements/src/ops_mpi.cpp
> +    auto* tmp_ptr = reinterpret_cast<int*>(taskData->inputs[0]);
i suggest you to use std::copy instead

2024-12-10 09:19 UTC, ascannel commented on tasks/mpi/sozonov_i_nearest_neighbor_elements/include/ops_mpi.hpp
> +#include <utility>
unnecessay includes, that also doubles in .cpp file

2024-12-11 18:18 UTC, Ivan-Lysov commented on tasks/mpi/sozonov_i_nearest_neighbor_elements/func_tests/main.cpp
> +}
You also need to generate negative numbers

2024-12-11 21:24 UTC, sozozzya commented on tasks/mpi/sozonov_i_nearest_neighbor_elements/func_tests/main.cpp
> +}
fixed, please check

2024-12-11 21:24 UTC, sozozzya commented on tasks/mpi/sozonov_i_nearest_neighbor_elements/include/ops_mpi.hpp
> +#include <utility>
fixed, please check

2024-12-11 21:24 UTC, sozozzya commented on tasks/mpi/sozonov_i_nearest_neighbor_elements/src/ops_mpi.cpp
> +    auto* tmp_ptr = reinterpret_cast<int*>(taskData->inputs[0]);
fixed, please check

2024-12-11 21:24 UTC, sozozzya commented on tasks/mpi/sozonov_i_nearest_neighbor_elements/src/ops_mpi.cpp
> +#include <algorithm>
fixed, please check

2024-12-11 21:26 UTC, ascannel approved these changes

2024-12-12 13:45 UTC, Ivan-Lysov approved these changes

2024-12-13 03:24 UTC, aobolensk approved these changes

2024-12-15 20:08 UTC, allnes approved these changes

2024-12-15 20:08 UTC, merged