Васенков Андрей. Задача 1. Вариант 23. Подсчет частоты символа в строке
learning-process/ppc-2024-autumn pull request #51
Opened 2024-10-27 14:49 UTC by VasenkovAA

Описание последовательной задачи.
Входные данные - строка и символ, число вхождений которого нужно найти.
Выходные данные - целочисленное значение - количество символа в строке.
Для простоты и читаемости кода подсчет ведется с помощью метода count библиотеки std.

Описание параллельной задачи.
Разделяем строку на несколько подстрок и поручаем эту задачу нескольким потокам. Разделение происходит равномерно. Затем каждый поток считает число входов символа в своей части строки. В итоге всё суммируется с помощью reduce.

2024-10-27 15:44 UTC, ChastovSlava approved these changes

2024-10-29 00:21 UTC, aobolensk requested changes

2024-10-29 00:21 UTC, aobolensk commented on tasks/mpi/vasenkov_a_char_freq/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
Please move test function to the test module

2024-10-29 00:21 UTC, aobolensk commented on tasks/mpi/vasenkov_a_char_freq/src/ops_mpi.cpp
> +  }
use std::copy for this

2024-10-29 19:47 UTC, allnes requested changes

2024-10-29 19:47 UTC, allnes commented on tasks/mpi/vasenkov_a_char_freq/src/ops_mpi.cpp
> +bool vasenkov_a_char_freq_mpi::CharFrequencyParallel::pre_processing() {
please use mpi functionality in run(), it's part of mpi algorithm

2024-10-30 00:52 UTC, aobolensk approved these changes

2024-11-01 21:14 UTC, VasenkovAA commented on tasks/mpi/vasenkov_a_char_freq/src/ops_mpi.cpp
> +bool vasenkov_a_char_freq_mpi::CharFrequencyParallel::pre_processing() {
fixed

2024-11-01 21:14 UTC, VasenkovAA commented on tasks/mpi/vasenkov_a_char_freq/src/ops_mpi.cpp
> +  }
fixed

2024-11-01 21:14 UTC, VasenkovAA commented on tasks/mpi/vasenkov_a_char_freq/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
fixed

2024-11-02 01:21 UTC, allnes approved these changes

2024-11-02 10:33 UTC, ChernovaNatalya approved these changes
The length of the strings for your perf tests is too small, it will work too fast.

2024-11-02 10:33 UTC, ChernovaNatalya commented on tasks/mpi/vasenkov_a_char_freq/src/ops_mpi.cpp
> +  }
You wrote that you fixed it, but you didn't add the changes.

2024-11-02 10:41 UTC, VasenkovAA commented on tasks/mpi/vasenkov_a_char_freq/src/ops_mpi.cpp
> +  }
Sorry, I forgot to upload the changes.

2024-11-02 12:21 UTC, merged