Дерябин Максим. Задача 2. Вариант 22. Итерационный метод Якоби
learning-process/ppc-2024-autumn pull request #512
Opened 2024-12-10 10:28 UTC by BrunoBucCcellati

Sequential
Реализация классического метода Якоби, нахождение решения СЛАУ путем последовательных приближений.
Начальное приближение - нулевое.
Каждая компонента вектора неизвестных на каждом следующем шаге вычисляется как число обратное к соответствующему диагональному элементу матрицы СЛАУ помноженное на разность между соответствующей компонентой вектора правой части и суммой произведений всех остальных элементов матрицы из той же строки на компоненты вектора неизвестных, полученных на предыдущем шаге.
Итерационный процесс продолжается до тех пор пока не достигнута требуемая точность (здесь 10^-6) или пока не достигнуто предельное число итераций Nmax. 
MPI 
Одномерная декомпозиция матрицы СЛАУ на горизонтальные полосы: равномерное распределение строк матрицы между некорневыми процессами, корневой процесс обрабатывает на остаточное число строк больше.
Параллелизм в рамках одной итерации метода: каждый процесс обновляет свою часть вектора неизвестных, после чего происходит сбор всех значений в родительском процессе с помощью boost::mpi::gatherv и рассылка обновленного вектора неизвестных с помощью boost::mpi::broadcast.
P.S.
Так как метод Якоби применим только к СЛАУ с квадратными матрицами, то на стадии валидации достаточно проверить только условие строго диагонального преобладания (условие сходимости метода Якоби), так как квадратная матрица, обладающая строгим диагональным преобладанием является невырожденной, а значит СЛАУ имеет единственное решение (условия, что определитель матрицы не должен равняться нулю, и, что ранг основной матрицы системы должен равняться рангу расширенной и числу переменных - в случае квадратных матриц эквивалентные условия, означающие, что система имеет единственное решение, эти условия выполняются автоматически при наличии у матрицы строгого диагонального преобладания). Условие применимости метода (неравенство нулю диагональных элементов) также будет выполнено для матриц со строгим диагональным преобладанием. 
P.S.2
Метод Якоби не применим к матрицам с отрицательными элементами, так как он предполагает, что все собственные числа матрицы должны быть положительными.

2024-12-10 20:54 UTC, laganina-cod requested changes

2024-12-10 20:54 UTC, laganina-cod commented on tasks/seq/deryabin_m_jacobi_iterative_method/func_tests/main.cpp
> +
please make test for matrix more 10 dim

2024-12-10 20:54 UTC, laganina-cod commented on tasks/seq/deryabin_m_jacobi_iterative_method/func_tests/main.cpp
> +  ASSERT_EQ(jacobi_iterative_method_TaskSequential.validation(), false);
please add tests for sparse and null matrices

2024-12-11 12:29 UTC, BrunoBucCcellati commented on tasks/seq/deryabin_m_jacobi_iterative_method/func_tests/main.cpp
> +  ASSERT_EQ(jacobi_iterative_method_TaskSequential.validation(), false);
fixed

2024-12-11 14:31 UTC, laganina-cod approved these changes

2024-12-12 17:39 UTC, Applejack2004 requested changes

2024-12-12 17:39 UTC, Applejack2004 commented on tasks/mpi/deryabin_m_jacobi_iterative_method/func_tests/main.cpp
> +}
Please add a test for a matrix with negative elements and a test with a stepped matrix.

2024-12-12 19:12 UTC, Applejack2004 approved these changes

2024-12-12 19:16 UTC, BrunoBucCcellati commented on tasks/mpi/deryabin_m_jacobi_iterative_method/func_tests/main.cpp
> +}
fixed

2024-12-13 15:43 UTC, aobolensk requested changes

2024-12-13 15:43 UTC, aobolensk commented on tasks/mpi/deryabin_m_jacobi_iterative_method/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, number_of_local_matrix_rows, 0);
Why do you have many MPI calls in ::validation()?

2024-12-13 15:43 UTC, aobolensk commented on tasks/mpi/deryabin_m_jacobi_iterative_method/src/ops_mpi.cpp
> +    input_matrix_[i] = tmp_ptr_matr[i];
use std::copy

2024-12-13 20:54 UTC, BrunoBucCcellati commented on tasks/mpi/deryabin_m_jacobi_iterative_method/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, number_of_local_matrix_rows, 0);
sorry, I forgot that we can't use MPI at the validation stage, it's been fixed, but to be fair, checking not the entire matrix for strict diagonal predominance, but individual parts of the matrix at each process accelerated the program's operation

2024-12-13 20:55 UTC, BrunoBucCcellati commented on tasks/mpi/deryabin_m_jacobi_iterative_method/src/ops_mpi.cpp
> +    input_matrix_[i] = tmp_ptr_matr[i];
changes have been made

2024-12-19 04:06 UTC, aobolensk approved these changes

2024-12-19 04:06 UTC, aobolensk commented on tasks/mpi/deryabin_m_symbol_frequency/func_tests/main.cpp
> -#include <boost/mpi/environment.hpp>
Please, do not modify other files

2024-12-20 14:54 UTC, allnes commented on tasks/mpi/deryabin_m_jacobi_iterative_method/perf_tests/main.cpp
> +    if (razmernost % 101 == 0) {
what is magic value 101?

2024-12-21 10:25 UTC, BrunoBucCcellati commented on tasks/mpi/deryabin_m_jacobi_iterative_method/perf_tests/main.cpp
> +    if (razmernost % 101 == 0) {
diagonal element of matrix

2024-12-22 22:21 UTC, allnes approved these changes

2024-12-22 22:22 UTC, merged