Золотарева Арина. Задача 3. Вариант 6. Решение систем линейных уравнений методом сопряженных градиентов.
learning-process/ppc-2024-autumn pull request #518
Opened 2024-12-11 05:15 UTC by andrewmeow

Описание алгоритма решения СЛАУ методом сопряженных градиентов:
- вычисляется начальная невязка r = b - A*x0, где x0 = 0.
- задается начальное направление поиска p = r.
- метод рассчитан на позитивно определенную симметричную матрицу A.
- метод рассчитан на поиск решения за n иттераций.

Итерация:

- Для каждой итерации k:

- Вычисляем a(alpha/шаг) = (r_k^T r_k) / (p_k^T A p_k).

- Обновляем  x_{k+1} = x_k + ak * p_k.

- Обновляем  остаток: r_{k+1} = r_k - ak * A * p_k.

- Проверяем критерий остановки - меньше ли невязка заданного порога(threshold), то есть норма остатка стала ниже
- 
- Обновляем  направление поиска: p_{k+1} = r_{k+1} + βk * p_k.

Seq:
Validation, проверяется:

- корректность входных данных: размеры матрицы A и вектора b
- симметричность матрицы А
- определена ли матрица А положительно

Входные данные:

- Инициализируются массивы для хранения матрицы A(n*n), вектора b(n) и начального приближения решения x(n, нулевой вектор).

Тесты:

- разные тесты на корректность вычислений.
- тесты с использованием рандомизирующей функции. Проверка простая: проходимся по уравнениям, складываем результат левой части и сравниваем с правой (bi).

2024-12-18 00:52 UTC, venn2713 requested changes
Уберите комментарии и исправьте узкое горлышко с разворачиванием вектора

2024-12-18 00:52 UTC, venn2713 commented on tasks/mpi/zolotareva_a_SLE_gradient_method/func_tests/main.cpp
> +    ASSERT_TRUE(testMpiTaskParallel.validation());
Уберите, оно вам не надо)

2024-12-18 00:52 UTC, venn2713 commented on tasks/mpi/zolotareva_a_SLE_gradient_method/func_tests/main.cpp
> +    ASSERT_TRUE(testMpiTaskParallel.validation());
Уберите, оно вам не надо)

2024-12-18 00:52 UTC, venn2713 commented on tasks/mpi/zolotareva_a_SLE_gradient_method/include/ops_mpi.hpp
> +// Copyright 2023 Nesterov Alexander
Удалите пожалуйста

2024-12-18 00:52 UTC, venn2713 commented on tasks/mpi/zolotareva_a_SLE_gradient_method/src/ops_mpi.cpp
> +// здесь писать саму задачу
Невероятно верный комментарий

2024-12-18 00:52 UTC, venn2713 commented on tasks/mpi/zolotareva_a_SLE_gradient_method/src/ops_mpi.cpp
> +    boost::mpi::all_gather(world, p, gathered_p);
Тут можно allgatherv использовать

2024-12-18 09:39 UTC, KAPUSHA228 requested changes

2024-12-18 09:39 UTC, KAPUSHA228 commented on tasks/seq/zolotareva_a_SLE_gradient_method/src/ops_seq.cpp
> +  if (int(taskData->inputs_count[0]) != n_ * n_ || int(taskData->inputs_count[1]) != n_) {
лучше использовать static_cast<int>(), и безопаснее и эффективнее

2024-12-18 09:39 UTC, KAPUSHA228 commented on tasks/seq/zolotareva_a_SLE_gradient_method/func_tests/main.cpp
> +TEST(zolotareva_a_SLE_gradient_method_seq, invalid_input_sizes) {
Не вижу тестов на n=0,n=1 или валидации на это

2024-12-18 22:23 UTC, andrewmeow commented on tasks/seq/zolotareva_a_SLE_gradient_method/src/ops_seq.cpp
> +  if (int(taskData->inputs_count[0]) != n_ * n_ || int(taskData->inputs_count[1]) != n_) {
fixed

2024-12-18 22:24 UTC, andrewmeow commented on tasks/seq/zolotareva_a_SLE_gradient_method/func_tests/main.cpp
> +TEST(zolotareva_a_SLE_gradient_method_seq, invalid_input_sizes) {
added

2024-12-18 22:25 UTC, andrewmeow commented on tasks/mpi/zolotareva_a_SLE_gradient_method/src/ops_mpi.cpp
> +    boost::mpi::all_gather(world, p, gathered_p);
переписала эту часть

2024-12-19 08:51 UTC, venn2713 approved these changes

2024-12-19 12:41 UTC, KAPUSHA228 approved these changes

2024-12-20 20:21 UTC, aobolensk approved these changes

2024-12-22 22:24 UTC, allnes commented on tasks/mpi/zolotareva_a_SLE_gradient_method/func_tests/main.cpp
> +  std::uniform_real_distribution<double> dist(-100.0f, 100.0f);
please parametrize it outside, e.g. in tests

2024-12-22 22:24 UTC, allnes commented on tasks/mpi/zolotareva_a_SLE_gradient_method/func_tests/main.cpp
> +    A[i * n + i] += n * 100.0f;  // Обеспечение доминирования диагонали
please change it, and don't use constants for that

2024-12-22 22:25 UTC, allnes commented on tasks/mpi/zolotareva_a_SLE_gradient_method/func_tests/main.cpp
> +  std::uniform_real_distribution<double> dist(-100.0f, 100.0f);
maybe depends on elements of matrix

2024-12-23 20:03 UTC, andrewmeow commented on tasks/mpi/zolotareva_a_SLE_gradient_method/func_tests/main.cpp
> +    A[i * n + i] += n * 100.0f;  // Обеспечение доминирования диагонали
По ревью поправила. На разговоре по задачам, был момент с тем, что seq-версия не одинакова с seq в mpi, а также разная допустимая погрешность в seq и mpi тестах.
Теперь реализация класса seq везде одинаковая, но погрешность в seq, я оставила 1e-5, так как:
-как минимум мне кажется, что для этих вычислений double будет маловато, возможно, c long double ситуация была бы получше.
-конечно, можно было и над реализацией подумать, но целом уже хороший результат.
При сравнении параллельной и последовательной версий в тестах стоит погрешность 1e-10, опять же - я думаю, из-за того, что размера double не хватает + фактор погрешности от распараллеливания.
Вы сказали, что не очень хорошо с допустимой погрешностью сравнивать, но, мне кажется, лучше так, чем риск упасть

2024-12-24 16:05 UTC, allnes approved these changes

2024-12-24 16:05 UTC, merged