Фролова Елизавета. Задача 2. Вариант 18. Ленточная горизонтальная схема A, вертикальное B
learning-process/ppc-2024-autumn pull request #519
Opened 2024-12-11 12:49 UTC by ElizavetaFrolova

Описание последовательной задачи:
Реализует стандартный алгоритм умножения матриц, вычисляя каждый элемент результирующей матрицы как скалярное произведение соответствующей строки первой матрицы и столбца второй матрицы.

Описание MPI задачи:
1. Главный процесс (ранг 0) вычисляет, как разделить строки матрицы A и столбцы матрицы B между процессами, чтобы распределить работу равномерно.
2. Главный процесс делит строки матрицы A и столбцы матрицы B между процессами.
Каждый процесс получает свой подмассив строк матрицы A и подмассив столбцов матрицы B.
3. Если участвует больше одного процесса, реализуется циклический обмен подмассивами столбцов матрицы B между процессами. Каждый процесс выполняет умножение своих строк на текущие столбцы и передает столбцы следующему процессу. Этот шаг повторяется, пока все необходимые данные не будут обработаны.
4. Каждый процесс выполняет умножение своих строк матрицы A на полученные столбцы матрицы B и сохраняет результат в своем локальном массиве.
5. Все процессы, кроме главного, отправляют свои результаты обратно главному процессу.
Главный процесс объединяет полученные части и формирует итоговую матрицу.

2024-12-11 17:19 UTC, Alexey2013 commented on tasks/mpi/frolova_e_matrix_multiplication/func_tests/main_frolova_matrix.cpp
> +TEST(frolova_e_matrix_multiplication_mpi, multiplying_matrix_by_a_vector) {
Add more tests on 1x1 matrices, prime numbers and powers of two

2024-12-11 17:19 UTC, Alexey2013 commented on tasks/mpi/frolova_e_matrix_multiplication/src/ops_mpi_frolova_matrix.cpp
> +using namespace std::chrono_literals;
this line is not needed

2024-12-11 20:21 UTC, KatyaKozlova commented on tasks/mpi/frolova_e_matrix_multiplication/src/ops_mpi_frolova_matrix.cpp
> +void frolova_e_matrix_multiplication_mpi::randomNumVec(int N, std::vector<int>& vec) {
please move the function to tests

2024-12-11 20:21 UTC, KatyaKozlova commented on tasks/seq/frolova_e_matrix_multiplication/src/ops_seq_frolova_matrix.cpp
> +void frolova_e_matrix_multiplication_seq::randomNumVec(int N, std::vector<int>& vec) {
please move the function to tests

2024-12-11 20:21 UTC, KatyaKozlova commented on tasks/mpi/frolova_e_matrix_multiplication/include/ops_mpi_frolova_matrix.hpp
> +namespace frolova_e_matrix_multiplication_mpi {
please add matrix multiplication as vectors

2024-12-11 22:12 UTC, Alexey2013 approved these changes

2024-12-11 22:52 UTC, KatyaKozlova approved these changes

2024-12-13 15:57 UTC, aobolensk requested changes

2024-12-13 15:57 UTC, aobolensk commented on tasks/mpi/frolova_e_matrix_multiplication/perf_tests/main_frolova_matrix.cpp
> +void randomNumVec(int N, std::vector<int>& vec) {
Please, either make it static or wrap with namespace

2024-12-13 15:57 UTC, aobolensk commented on tasks/mpi/frolova_e_matrix_multiplication/perf_tests/main_frolova_matrix.cpp
> +  std::vector<int> values_2 = {100, 100};
Please, increase shape for perf tests

2024-12-13 15:57 UTC, aobolensk commented on tasks/mpi/frolova_e_matrix_multiplication/perf_tests/main_frolova_matrix.cpp
> +    int num = rand() % 100 + 1;
Please, add negative numbers

2024-12-14 08:38 UTC, aobolensk approved these changes

2024-12-15 20:10 UTC, allnes approved these changes

2024-12-15 20:10 UTC, merged