Казунин Никита. Задача 1. Вариант 23. Подсчёт частоты символа в строке.
learning-process/ppc-2024-autumn pull request #52
Opened 2024-10-27 15:58 UTC by NikKazzzzzz

Описание задачи
Задача заключается в подсчете частоты появления заданного символа в строке, используя как последовательный, так и параллельный подходы. Основная цель — продемонстрировать, как различные методы обработки данных влияют на производительность и эффективность выполнения.

Последовательный вариант
В последовательном варианте реализация использует стандартную библиотеку C++ для подсчета символа в строке. Код проходит по каждому символу строки и считает количество вхождений целевого символа. Этот метод прост в реализации, но может быть неэффективным для больших строк, так как выполняет всю работу на одном потоке.

Параллельный вариант (MPI)
Параллельный вариант использует библиотеку MPI (Message Passing Interface) для распределения нагрузки между несколькими процессами. В этом варианте строка разбивается на сегменты, которые обрабатываются параллельно, что позволяет значительно ускорить подсчет вхождений символа в больших строках. Каждый процесс считает количество символов в своем сегменте, после чего результаты объединяются на главном процессе. Это позволяет эффективно использовать вычислительные ресурсы и уменьшить время выполнения задачи при работе с большими объемами данных.

2024-10-27 16:13 UTC, hasanyanovk commented on tasks/mpi/kazunin_n_count_freq_a_char_in_string/src/ops_mpi.cpp
> +  boost::mpi::scatterv(global, input_string_.data(), send_counts, displs, local_segment_.data(), loc_vec_size, 0);
you should use different overloads of `boost::mpi::scatterv` in root-process and other processes to send/recieve

2024-10-29 06:51 UTC, NikKazzzzzz commented on tasks/mpi/kazunin_n_count_freq_a_char_in_string/src/ops_mpi.cpp
> +  boost::mpi::scatterv(global, input_string_.data(), send_counts, displs, local_segment_.data(), loc_vec_size, 0);
Fixed

2024-10-29 06:51 UTC, NikKazzzzzz commented on tasks/mpi/kazunin_n_count_freq_a_char_in_string/src/ops_mpi.cpp
> +  size_t world_size = static_cast<size_t>(global.size());
Fixed

2024-10-29 08:18 UTC, hasanyanovk approved these changes

2024-10-29 10:13 UTC, Kitos87 approved these changes

2024-10-29 19:53 UTC, allnes requested changes

2024-10-29 19:53 UTC, allnes commented on tasks/mpi/kazunin_n_count_freq_a_char_in_string/src/ops_mpi.cpp
> +bool kazunin_n_count_freq_a_char_in_string_mpi::CharFreqCounterMPIParallel::pre_processing() {
Please don't use mpi functionality in pre-processing, is part of parallel algorithm

2024-10-29 19:53 UTC, allnes commented on tasks/seq/kazunin_n_count_freq_a_char_in_string/src/ops_seq.cpp
> +using namespace std::chrono_literals;
For what do you use it?

2024-10-30 15:40 UTC, NikKazzzzzz commented on tasks/seq/kazunin_n_count_freq_a_char_in_string/src/ops_seq.cpp
> +using namespace std::chrono_literals;
Yes, it is not necessary, i deleted it. See the changes

2024-10-30 15:41 UTC, NikKazzzzzz commented on tasks/mpi/kazunin_n_count_freq_a_char_in_string/src/ops_mpi.cpp
> +bool kazunin_n_count_freq_a_char_in_string_mpi::CharFreqCounterMPIParallel::pre_processing() {
Rewrote the forwarding logic in "run". See the changes please.

2024-10-31 00:46 UTC, allnes approved these changes

2024-10-31 16:22 UTC, aobolensk requested changes

2024-10-31 16:53 UTC, NikKazzzzzz commented on tasks/mpi/kazunin_n_count_freq_a_char_in_string/func_tests/main.cpp
> +TEST(kazunin_n_count_freq_a_char_in_string_mpi, test_all_char_is_same) {
added

2024-11-01 00:40 UTC, aobolensk approved these changes

2024-11-01 00:40 UTC, merged

2024-11-01 21:59 UTC, kmichaelk commented
Both func & perf tests corrupt heap, revert is required

You write 4 bytes more as you cast int32_t -> size_t aka uint64_t on x64

@aobolensk 

```
=================================================================
==21291==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000038f30 at pc 0x55d157e26dae bp 0x7ffe4e42d850 sp 0x7ffe4e42d848
WRITE of size 8 at 0x602000038f30 thread T0
    #0 0x55d157e26dad in kazunin_n_count_freq_a_char_in_string_mpi::CharFreqCounterMPIParallel::post_processing() /workspaces/ppc-2024-autumn/tasks/mpi/kazunin_n_count_freq_a_char_in_string/src/ops_mpi.cpp:97:54
    #1 0x55d157d56f3c in kazunin_n_count_freq_a_char_in_string_mpi_test_pipeline_run_Test::TestBody() /workspaces/ppc-2024-autumn/tasks/mpi/kazunin_n_count_freq_a_char_in_string/perf_tests/main.cpp:37:24
    #2 0x55d157eb740a in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /workspaces/ppc-2024-autumn/3rdparty/googletest/googletest/src/gtest.cc:2612:10
    #3 0x55d157e9cb39 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /workspaces/ppc-2024-autumn/3rdparty/googletest/googletest/src/gtest.cc:2648:14
    #4 0x55d157e7bf72 in testing::Test::Run() /workspaces/ppc-2024-autumn/3rdparty/googletest/googletest/src/gtest.cc:2687:5
    #5 0x55d157e7cb6f in testing::TestInfo::Run() /workspaces/ppc-2024-autumn/3rdparty/googletest/googletest/src/gtest.cc:2836:11
    #6 0x55d157e7d40b in testing::TestSuite::Run() /workspaces/ppc-2024-autumn/3rdparty/googletest/googletest/src/gtest.cc:3015:30
    #7 0x55d157e8e12e in testing::internal::UnitTestImpl::RunAllTests() /workspaces/ppc-2024-autumn/3rdparty/googletest/googletest/src/gtest.cc:5921:44
    #8 0x55d157ebb59a in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /workspaces/ppc-2024-autumn/3rdparty/googletest/googletest/src/gtest.cc:2612:10
    #9 0x55d157e9f049 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /workspaces/ppc-2024-autumn/3rdparty/googletest/googletest/src/gtest.cc:2648:14
    #10 0x55d157e8dc92 in testing::UnitTest::Run() /workspaces/ppc-2024-autumn/3rdparty/googletest/googletest/src/gtest.cc:5485:10
    #11 0x55d157d38890 in RUN_ALL_TESTS() /workspaces/ppc-2024-autumn/3rdparty/googletest/googletest/include/gtest/gtest.h:2316:73
    #12 0x55d157d35279 in main /workspaces/ppc-2024-autumn/tasks/mpi/example/perf_tests/main.cpp:98:10
    #13 0x7fde600f5d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #14 0x7fde600f5e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #15 0x55d157c033f4 in _start (/workspaces/ppc-2024-autumn/build/bin/mpi_perf_tests+0x7c3f4) (BuildId: 2d62bd7df6bb0635b0a1cc2fbc81795e0826145e)

0x602000038f34 is located 0 bytes to the right of 4-byte region [0x602000038f30,0x602000038f34)
allocated by thread T0 here:
    #0 0x55d157cc100d in operator new(unsigned long) (/workspaces/ppc-2024-autumn/build/bin/mpi_perf_tests+0x13a00d) (BuildId: 2d62bd7df6bb0635b0a1cc2fbc81795e0826145e)
    #1 0x55d157cd04e9 in __gnu_cxx::new_allocator<int>::allocate(unsigned long, void const*) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/ext/new_allocator.h:127:27
    #2 0x55d157cd0470 in std::allocator<int>::allocate(unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/allocator.h:185:32
    #3 0x55d157cd0470 in std::allocator_traits<std::allocator<int> >::allocate(std::allocator<int>&, unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/alloc_traits.h:464:20
    #4 0x55d157cce39f in std::_Vector_base<int, std::allocator<int> >::_M_allocate(unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_vector.h:346:20
    #5 0x55d157ce1fa0 in std::_Vector_base<int, std::allocator<int> >::_M_create_storage(unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_vector.h:361:33
    #6 0x55d157ce1e41 in std::_Vector_base<int, std::allocator<int> >::_Vector_base(unsigned long, std::allocator<int> const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_vector.h:305:9
    #7 0x55d157ce18ac in std::vector<int, std::allocator<int> >::vector(unsigned long, int const&, std::allocator<int> const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_vector.h:524:9
    #8 0x55d157d56343 in kazunin_n_count_freq_a_char_in_string_mpi_test_pipeline_run_Test::TestBody() /workspaces/ppc-2024-autumn/tasks/mpi/kazunin_n_count_freq_a_char_in_string/perf_tests/main.cpp:14:24
    #9 0x55d157eb740a in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /workspaces/ppc-2024-autumn/3rdparty/googletest/googletest/src/gtest.cc:2612:10
    #10 0x55d157e9cb39 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /workspaces/ppc-2024-autumn/3rdparty/googletest/googletest/src/gtest.cc:2648:14
    #11 0x55d157e7bf72 in testing::Test::Run() /workspaces/ppc-2024-autumn/3rdparty/googletest/googletest/src/gtest.cc:2687:5
    #12 0x55d157e7cb6f in testing::TestInfo::Run() /workspaces/ppc-2024-autumn/3rdparty/googletest/googletest/src/gtest.cc:2836:11
    #13 0x55d157e7d40b in testing::TestSuite::Run() /workspaces/ppc-2024-autumn/3rdparty/googletest/googletest/src/gtest.cc:3015:30
    #14 0x55d157e8e12e in testing::internal::UnitTestImpl::RunAllTests() /workspaces/ppc-2024-autumn/3rdparty/googletest/googletest/src/gtest.cc:5921:44
    #15 0x55d157ebb59a in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /workspaces/ppc-2024-autumn/3rdparty/googletest/googletest/src/gtest.cc:2612:10
    #16 0x55d157e9f049 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /workspaces/ppc-2024-autumn/3rdparty/googletest/googletest/src/gtest.cc:2648:14
    #17 0x55d157e8dc92 in testing::UnitTest::Run() /workspaces/ppc-2024-autumn/3rdparty/googletest/googletest/src/gtest.cc:5485:10
    #18 0x55d157d38890 in RUN_ALL_TESTS() /workspaces/ppc-2024-autumn/3rdparty/googletest/googletest/include/gtest/gtest.h:2316:73
    #19 0x55d157d35279 in main /workspaces/ppc-2024-autumn/tasks/mpi/example/perf_tests/main.cpp:98:10
    #20 0x7fde600f5d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

SUMMARY: AddressSanitizer: heap-buffer-overflow /workspaces/ppc-2024-autumn/tasks/mpi/kazunin_n_count_freq_a_char_in_string/src/ops_mpi.cpp:97:54 in kazunin_n_count_freq_a_char_in_string_mpi::CharFreqCounterMPIParallel::post_processing()
Shadow bytes around the buggy address:
  0x0c047ffff190: fa fa 00 fa fa fa fd fd fa fa fd fa fa fa 04 fa
  0x0c047ffff1a0: fa fa 04 fa fa fa 04 fa fa fa 00 fa fa fa 05 fa
  0x0c047ffff1b0: fa fa 03 fa fa fa fd fa fa fa 00 fa fa fa 07 fa
  0x0c047ffff1c0: fa fa 04 fa fa fa 00 fa fa fa 00 00 fa fa 00 07
  0x0c047ffff1d0: fa fa 00 fa fa fa fd fa fa fa 00 fa fa fa 00 00
=>0x0c047ffff1e0: fa fa 00 fa fa fa[04]fa fa fa fd fa fa fa fd fa
  0x0c047ffff1f0: fa fa 00 00 fa fa 00 fa fa fa 00 fa fa fa 04 fa
  0x0c047ffff200: fa fa 00 fa fa fa 00 00 fa fa fd fd fa fa fd fd
  0x0c047ffff210: fa fa fd fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047ffff220: fa fa fa fa fa fa fa fa  [...]