Дурыничев Дмитрий. Задача 2. Вариант 7. Передача от всех одному и рассылка (allreduce)
learning-process/ppc-2024-autumn pull request #521
Opened 2024-12-11 14:47 UTC by ofuuse

1. **Двоичное дерево для обмена данными**:
   - Используется обмен данными по схеме двоичного дерева, что обеспечивает логарифмическое количество шагов – `O(log(size))`.

2. **XOR-операция для определения партнера**:
   - На каждом шаге `partner` определяется как `rank ^ step`. Это эффективно для реализации схожей с алгоритмом бинарного дерева для уменьшения данных.

3. **Симметричный обмен**:
   - Процессы отправляют и принимают данные с партнером в зависимости от их ранга:
     - Если `rank < partner`, сначала отправляют, затем принимают.
     - Если `rank > partner`, сначала принимают, затем отправляют.

4. **Реконструкция дерева для распространения результата**:
   - После редукции результат передается обратно по дереву для распространения на все процессы:
     - **Получение данных от родителя** (`p`).
     - **Передача данных левому и правому потомкам** (`lc`, `rc`).

5. **Шаблонная функция**:
   - Реализация поддерживает произвольные типы данных и пользовательские операции через шаблон `BinaryOperation`.

6. **Перегруженная версия функции**:
   - Есть две версии функции:
     - **Возвращающая результат** напрямую.
     - **Модифицирующая результат** через ссылку на `global_result`.

2024-12-11 16:46 UTC, venn2713 requested changes
Вам следует делать больше ошибок перед отправкой PR, а то на ревью сложно искать что не так 😢

2024-12-11 16:46 UTC, venn2713 commented on tasks/mpi/durynichev_d_allreduce/perf_tests/main.cpp
> +  boost::mpi::environment env;
Зачем он вам?

2024-12-11 16:46 UTC, venn2713 commented on tasks/mpi/durynichev_d_custom_allreduce/perf_tests/main.cpp
> +  boost::mpi::environment env;
То же самое

2024-12-11 18:05 UTC, korablev-vm commented on tasks/mpi/durynichev_d_custom_allreduce/func_tests/main.cpp
> +}
В нашу задачу обычно входит правильное создание данных (в том числе рандомных), поэтому не уверен, что этот момент с пропуском тестов в случае проверки валидации будет легальным.

2024-12-12 13:39 UTC, korablev-vm approved these changes

2024-12-12 19:03 UTC, venn2713 approved these changes

2024-12-13 16:00 UTC, aobolensk approved these changes

2024-12-15 20:11 UTC, allnes approved these changes

2024-12-15 20:11 UTC, merged