Мухина Маргарита. Задача 3. Вариант 16. Сортировка Шелла с простым слиянием
learning-process/ppc-2024-autumn pull request #522
Opened 2024-12-11 18:31 UTC by MargaritaMuhina

Последовательная версия 

Сортировка Шелла
Цикл for (gap = 1; gap < n / 3; gap = gap * 3 + 1); вычисляет начальный интервал (gap) для сортировки. 
Внешний цикл for (; gap > 0; gap = (gap - 1) / 3) перебирает интервалы, постепенно уменьшая их. На каждой итерации выполняется сортировка вставками, но не для всех элементов, а только для элементов, расстояние между которыми равно текущему интервалу (gap).
Внутренний цикл for (int i = gap; i < n; i++) проходит по массиву, начиная с индекса gap. Для каждого элемента sortedVec[i] выполняется следующее:
Значение элемента сохраняется во временной переменной temp.
Внутренний цикл сдвигает элементы, которые больше чем temp, на gap позиций вправо, пока не найдёт подходящее место для temp. Этот цикл является модификацией сортировки вставками: вместо сравнения с соседним элементом, сравнение идёт с элементом, находящимся на расстоянии gap.
После нахождения подходящего места, значение temp вставляется в массив.

Параллельная версия

Размер массива рассылается всем процессам с помощью broadcast.
Массив делится на части delta приблизительно равного размера, остаток распределяется между первыми процессами.
Выполняется распределение входного массива input_ между процессами.  Каждый процесс получает свою часть в local_input_.
Каждый процесс сортирует свою локальную часть с помощью shellSort.
Сбор отсортированных частей, используя merge для слияния отсортированных подмассивов, получаемых от других процессов с помощью world_.recv.

2024-12-14 10:04 UTC, kavtorevd requested changes

2024-12-14 10:04 UTC, kavtorevd commented on tasks/mpi/muhina_m_shell_sort/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
remove unused namespace

2024-12-14 10:04 UTC, kavtorevd commented on tasks/mpi/muhina_m_shell_sort/include/ops_mpi.hpp
> +#include <string>
remove unused include

2024-12-14 10:04 UTC, kavtorevd commented on tasks/mpi/muhina_m_shell_sort/func_tests/main.cpp
> +}
add test where checks empty vector

2024-12-14 10:04 UTC, kavtorevd commented on tasks/mpi/muhina_m_shell_sort/func_tests/main.cpp
> +}
add test where checks single-element vector

2024-12-14 20:53 UTC, LizochkaSpring commented on tasks/seq/muhina_m_shell_sort/func_tests/main.cpp
> +}
Помести данную функцию в namespace, так же и в других тестах.

2024-12-14 20:53 UTC, LizochkaSpring commented on tasks/seq/muhina_m_shell_sort/src/ops_seq.cpp
> +  return taskData->outputs_count[0] != 0;
Пожалуйста, измени на более понятный, и добавь проверку на меньше нуля

2024-12-14 20:53 UTC, LizochkaSpring commented on tasks/seq/muhina_m_shell_sort/func_tests/main.cpp
> +
Пожалуйста, добавь тесты на неверно веденные данные

2024-12-16 06:00 UTC, MargaritaMuhina commented on tasks/mpi/muhina_m_shell_sort/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
fixed

2024-12-16 06:00 UTC, MargaritaMuhina commented on tasks/mpi/muhina_m_shell_sort/include/ops_mpi.hpp
> +#include <string>
fixed

2024-12-16 06:00 UTC, MargaritaMuhina commented on tasks/mpi/muhina_m_shell_sort/func_tests/main.cpp
> +}
fixed

2024-12-16 06:00 UTC, MargaritaMuhina commented on tasks/mpi/muhina_m_shell_sort/func_tests/main.cpp
> +}
fixed

2024-12-16 06:01 UTC, MargaritaMuhina commented on tasks/seq/muhina_m_shell_sort/func_tests/main.cpp
> +}
fixed

2024-12-16 06:01 UTC, MargaritaMuhina commented on tasks/seq/muhina_m_shell_sort/src/ops_seq.cpp
> +  return taskData->outputs_count[0] != 0;
fixed

2024-12-16 06:01 UTC, MargaritaMuhina commented on tasks/seq/muhina_m_shell_sort/func_tests/main.cpp
> +
fixed

2024-12-16 10:09 UTC, LizochkaSpring approved these changes

2024-12-16 10:25 UTC, kavtorevd approved these changes

2024-12-19 04:08 UTC, aobolensk approved these changes

2024-12-20 14:58 UTC, allnes commented on tasks/mpi/muhina_m_shell_sort/func_tests/main.cpp
> +    global_vec = {-5, -2, -9, -1, -5, -6};
please generate values wirg differnet sizes

2024-12-20 20:01 UTC, MargaritaMuhina commented on tasks/mpi/muhina_m_shell_sort/func_tests/main.cpp
> +    global_vec = {-5, -2, -9, -1, -5, -6};
fixed

2024-12-22 22:26 UTC, allnes approved these changes

2024-12-22 22:27 UTC, merged