Гнитиенко Кирилл. Задача 3. Вариант 23. Поиск кратчайших путей из одной вершины (алгоритм Беллмана-Форда)
learning-process/ppc-2024-autumn pull request #523
Opened 2024-12-11 18:51 UTC by Gn4ik

### Последовательная версия
`pre_processing:` В этом методе происходит подготовка данных перед запуском основного алгоритма.
Входной граф, заданный в виде матрицы смежности, преобразуется в формат CRS (Compressed Row Storage) для оптимизации работы алгоритма.
`validation:` Проверка размеров входных и выходных данных.
`run:`  Выполняется V-1 (где V — количество вершин в графе) итераций с помощью функции `Iteration()`. Для каждой вершины проверяется, можно ли сократить расстояние до её соседей. Если существует более короткий путь через соседнюю вершину, то минимальное расстояние обновляется. Итерация повторяется для всех рёбер в графе, обновляя массив кратчайших путей. Если на какой-либо итерации не произошло изменений в кратчайших путях, выполнение алгоритма останавливается. После всех итераций проводится проверка на отрицательные циклы через метод `check_negative_cycle()`: После выполнения основного цикла алгоритма (V-1 итераций) выполняется ещё одна итерация, чтобы проверить, можно ли уменьшить расстояние для какой-либо вершины. Если удаётся уменьшить расстояние, значит, в графе существует отрицательный цикл.
### Параллельная версия
В методе `Iteration()` следующие изменения: 

- Каждый процесс обрабатывает только часть вершин графа. 
- Внутри каждого процесса обновляются кратчайшие пути для всех вершин, принадлежащих его части графа.
- После этого все процессы выполняют синхронизацию данных с помощью функции `reduce`. Это позволяет собрать минимальные значения кратчайших путей из всех процессов.
- Затем с помощью функции `broadcast `происходит передача обновлённых данных между всеми процессами для дальнейшей обработки.

2024-12-17 23:31 UTC, dssss12 commented on tasks/mpi/gnitienko_k_bellman-ford-algorithm/include/ops_mpi.hpp
> +  size_t E{};
you don't use the number of edges E in the main algorithm, this field can be deleted

2024-12-18 12:28 UTC, Gn4ik commented on tasks/mpi/gnitienko_k_bellman-ford-algorithm/include/ops_mpi.hpp
> +  size_t E{};
ready

2024-12-18 20:54 UTC, dssss12 approved these changes

2024-12-20 11:40 UTC, KoshkinMatvey commented on tasks/mpi/gnitienko_k_bellman-ford-algorithm/src/ops_mpi.cpp
> +  internal_order_test();
add a check for missing loops

2024-12-20 16:40 UTC, KoshkinMatvey approved these changes

2024-12-21 12:53 UTC, aobolensk requested changes

2024-12-21 12:53 UTC, aobolensk commented on tasks/mpi/gnitienko_k_bellman-ford-algorithm/func_tests/main.cpp
> +std::vector<int> generateGraph(const int V) {
Please, add more func tests

2024-12-21 12:53 UTC, aobolensk commented on tasks/mpi/gnitienko_k_bellman-ford-algorithm/src/ops_mpi.cpp
> +        if (b == 1000000000) return a;
Should you reuse INF in your solution?

2024-12-21 16:35 UTC, Gn4ik commented on tasks/mpi/gnitienko_k_bellman-ford-algorithm/src/ops_mpi.cpp
> +        if (b == 1000000000) return a;
Fixed

2024-12-21 16:36 UTC, Gn4ik commented on tasks/mpi/gnitienko_k_bellman-ford-algorithm/func_tests/main.cpp
> +std::vector<int> generateGraph(const int V) {
Added

2024-12-22 22:35 UTC, allnes commented on tasks/mpi/gnitienko_k_bellman-ford-algorithm/func_tests/main.cpp
> +  std::vector<int> graph = {0, 10, 0,  0, 0, 8, 0, 0,  0, 2,  0, 0, 0, 1, 0, 0, 0, 0,
please create graphs generator with different types of graphs for func and perf tests

2024-12-22 22:37 UTC, allnes commented on tasks/seq/gnitienko_k_bellman-ford_algorithm/func_tests/main.cpp
> +          if (graph[i * V + j] != 0 && expected_res[i] != INT_MAX - 1000 &&
what is magic number 1000

2024-12-22 22:37 UTC, allnes commented on tasks/seq/gnitienko_k_bellman-ford_algorithm/perf_tests/main.cpp
> +const int INF = 1000000000;
please use max numeric int from std

2024-12-22 22:37 UTC, allnes commented on tasks/seq/gnitienko_k_bellman-ford_algorithm/perf_tests/main.cpp
> +}
use type of graphs for generation not only values

2024-12-23 06:33 UTC, aobolensk approved these changes

2024-12-24 16:06 UTC, allnes approved these changes

2024-12-24 16:06 UTC, merged