Соцков Андрей. Задача 3. Вариант 20. Поразрядная сортировка для вещественных чисел (тип double) с простым слиянием.
learning-process/ppc-2024-autumn pull request #526
Opened 2024-12-11 22:28 UTC by flavvvour

# Описание задачи: Поразрядная сортировка для вещественных чисел (тип double) с простым слиянием.

## Цель задачи:

Сортировка массива чисел с использованием алгоритма поразрядной сортировки (Radix Sort) для чисел с плавающей точкой типа double

---
## Последовательная версия

### 1. Разбиение данных
Данные, подлежащие сортировке, представляют собой массив чисел, который разбивается на две части:
  - Положительные числа.
  - Отрицательные числа.

Эти данные затем сортируются по отдельности, но оба набора чисел сортируются с помощью одного и того же алгоритма поразрядной сортировки (Radix Sort).

### 2. Передача данных
В данной версии все данные находятся в одном процессе и не требуют передачи между различными частями системы. Данные, передаваемые в задачу, загружаются в память в начале работы через указатель `taskData->inputs` и сохраняются в переменной `input_data_`.

### 3. Вычисление
- Алгоритм поразрядной сортировки (Radix Sort) используется для сортировки как положительных, так и отрицательных чисел.
- Отрицательные числа инвертируются перед сортировкой, и после завершения сортировки они снова инвертируются.
- Затем оба набора данных объединяются в одну отсортированную последовательность.

### 4. Результат
Результат сортировки сохраняется в локальном массиве `sorted_data_`, который затем копируется в выходной буфер, подготовленный для хранения результатов (через `taskData->outputs`).

### 5. Обработка результата
После завершения сортировки, процесс записывает итоговый отсортированный массив в выходной буфер, чтобы дальнейшие этапы работы с результатом могли быть выполнены.

## Параллельная версия

### 1. Разбиение данных
Данные, подлежащие сортировке, разбиваются между процессами. Каждый процесс получает свою часть данных, которая будет сортироваться с использованием алгоритма поразрядной сортировки (Radix Sort). Для удобства, данные разбиваются на положительные и отрицательные числа, которые обрабатываются отдельно, но в рамках одного алгоритма сортировки.

### 2. Передача данных
Процесс с рангом 0 (главный процесс) выполняет разбиение данных и отправляет их другим процессам через `MPI_Scatterv`. Каждый процесс получает свою часть данных, на которой будет выполняться сортировка.

### 3. Вычисление
Каждый процесс выполняет сортировку локальной части данных с помощью поразрядной сортировки (Radix Sort). В этом процессе:

- Числа разделяются на положительные и отрицательные.
- Отрицательные числа инвертируются для выполнения сортировки, а затем снова инвертируются после сортировки.
- Каждая часть данных сортируется независимо на каждом процессе, что ускоряет общий процесс за счет параллелизма.

### 4. Результат
После выполнения сортировки каждый процесс отправляет отсортированные данные обратно в процесс с рангом 0 с помощью `MPI_Gatherv`. Процесс 0 получает все отсортированные части данных и готовится к слиянию.

### 5. Обработка результата
Процесс с рангом 0 выполняет слияние отсортированных данных, полученных от других процессов, в финальную отсортированную последовательность.

2024-12-13 08:40 UTC, korablev-vm requested changes

2024-12-13 08:40 UTC, korablev-vm commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/func_tests/main.cpp
> +}
оберните в namespace

2024-12-13 08:40 UTC, korablev-vm commented on tasks/seq/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/func_tests/main.cpp
> +}
namespace

2024-12-13 08:40 UTC, korablev-vm commented on tasks/seq/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/perf_tests/main.cpp
> +}
namespace + используйте обратно отсортированный вектор

2024-12-13 08:40 UTC, korablev-vm commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/perf_tests/main.cpp
> +  }
можно вынести аналогично функциональным тестам в отдельную функцию (не забыв про namespace) + вектор должен быть обратно отсортированным

2024-12-13 08:40 UTC, korablev-vm commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/src/ops_mpi.cpp
> +    : Task(std::move(taskData_)) {}
зачем вам это здесь?

2024-12-13 08:40 UTC, korablev-vm commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/src/ops_mpi.cpp
> +}
не уверен, что нам в принципе разрешно использовать std::sort, поправьте, если ошибаюсь и это часть алгоритма

2024-12-13 08:40 UTC, korablev-vm commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/src/ops_mpi.cpp
> +    : Task(std::move(taskData_)) {}
аналогично, оставляется спокойно в .hpp

2024-12-13 08:40 UTC, korablev-vm commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/src/ops_mpi.cpp
> +  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
можно перенести в .hpp, если используется в нескольких местах (а у Вас именно так и используется)

2024-12-13 08:40 UTC, korablev-vm commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/src/ops_mpi.cpp
> +      }
Рекомендую убрать выводы, чтобы не засорять логи

2024-12-13 09:58 UTC, flavvvour commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/func_tests/main.cpp
> +}
Fixed

2024-12-13 09:58 UTC, flavvvour commented on tasks/seq/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/func_tests/main.cpp
> +}
Fixed

2024-12-13 09:58 UTC, flavvvour commented on tasks/seq/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/perf_tests/main.cpp
> +}
Fixed

2024-12-13 09:58 UTC, flavvvour commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/src/ops_mpi.cpp
> +    : Task(std::move(taskData_)) {}
Fixed

2024-12-13 09:58 UTC, flavvvour commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/src/ops_mpi.cpp
> +}
Fixed

2024-12-13 09:58 UTC, flavvvour commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/src/ops_mpi.cpp
> +    : Task(std::move(taskData_)) {}
Fixed

2024-12-13 09:58 UTC, flavvvour commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/src/ops_mpi.cpp
> +  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
Fixed

2024-12-13 09:58 UTC, flavvvour commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/src/ops_mpi.cpp
> +      }
Fixed

2024-12-13 13:34 UTC, ermolaevv commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/include/ops_mpi.hpp
> +  boost::mpi::communicator world;
It looks like you don't use it anywhere. If so, delete it

2024-12-13 13:34 UTC, ermolaevv commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/include/ops_mpi.hpp
> +#include <boost/serialization/vector.hpp>
Why would you do that if you use pure mpi

2024-12-13 13:34 UTC, ermolaevv commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/include/ops_mpi.hpp
> +#include <boost/mpi.hpp>
It seems to me that using two include mpi is excessive. Remove boost/mpi.hpp

2024-12-13 13:34 UTC, ermolaevv commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
Why do you use that?

2024-12-13 13:34 UTC, ermolaevv commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/src/ops_mpi.cpp
> +#include <vector>
Please move all includes to hpp, except mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/include/ops_mpi.hpp

2024-12-13 13:34 UTC, ermolaevv commented on tasks/seq/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/src/ops_seq.cpp
> +#include <thread>
Same

2024-12-13 13:34 UTC, ermolaevv commented on tasks/seq/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/src/ops_seq.cpp
> +#include <thread>
Are you using thread for something?

2024-12-13 13:34 UTC, ermolaevv commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/src/ops_mpi.cpp
> +  sequentialSort();
Why do you double call sort? Inside sequentialSort alse calls radixSortWithSignHandling

2024-12-13 13:34 UTC, ermolaevv commented on tasks/seq/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/func_tests/main.cpp
> +TEST(sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging_seq, RandomSortedSameIntegerPart) {
In mpi's func_tests you make a function for run test. Please do same here

2024-12-13 18:00 UTC, flavvvour commented on tasks/seq/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/func_tests/main.cpp
> +TEST(sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging_seq, RandomSortedSameIntegerPart) {
Fixed

2024-12-13 18:00 UTC, flavvvour commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/src/ops_mpi.cpp
> +  sequentialSort();
Fixed

2024-12-13 18:00 UTC, flavvvour commented on tasks/seq/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/src/ops_seq.cpp
> +#include <thread>
Fixed

2024-12-13 18:00 UTC, flavvvour commented on tasks/seq/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/src/ops_seq.cpp
> +#include <thread>
Fixed

2024-12-13 18:00 UTC, flavvvour commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/src/ops_mpi.cpp
> +#include <vector>
Fixed

2024-12-13 18:01 UTC, flavvvour commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
Fixed

2024-12-13 18:01 UTC, flavvvour commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/include/ops_mpi.hpp
> +#include <boost/mpi.hpp>
Fixed

2024-12-13 18:01 UTC, flavvvour commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/include/ops_mpi.hpp
> +#include <boost/serialization/vector.hpp>
Fixed

2024-12-13 18:01 UTC, flavvvour commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/include/ops_mpi.hpp
> +  boost::mpi::communicator world;
Fixed

2024-12-13 19:25 UTC, ermolaevv approved these changes

2024-12-13 19:35 UTC, korablev-vm approved these changes

2024-12-15 18:45 UTC, aobolensk approved these changes

2024-12-22 22:40 UTC, allnes commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/func_tests/main.cpp
> +  std::sort(data.rbegin(), data.rend());
please use this function only for generate data, this line about pre processing

2024-12-22 22:40 UTC, allnes commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/func_tests/main.cpp
> +  std::sort(data.rbegin(), data.rend());
and why do you use it?

2024-12-22 22:41 UTC, allnes commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/perf_tests/main.cpp
> +  std::sort(data.rbegin(), data.rend());
same point about generating and pre processing

2024-12-22 22:43 UTC, allnes commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/include/ops_mpi.hpp
> +    MPI_Comm_size(MPI_COMM_WORLD, &size);
please don't combine classic mpi api and boost mpi api, it could be create potential problem

2024-12-22 23:33 UTC, flavvvour commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/include/ops_mpi.hpp
> +    MPI_Comm_size(MPI_COMM_WORLD, &size);
Fixed in commit "review 3.0"

2024-12-22 23:33 UTC, flavvvour commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/perf_tests/main.cpp
> +  std::sort(data.rbegin(), data.rend());
Fixed in commit "review 3.0"

2024-12-22 23:33 UTC, flavvvour commented on tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/func_tests/main.cpp
> +  std::sort(data.rbegin(), data.rend());
Fixed in commit "review 3.0"

2024-12-24 16:14 UTC, allnes approved these changes

2024-12-24 16:14 UTC, merged