Колодкин Григорий. Задача 3. Вариант 14. Быстрая сортировка с простым слиянием
learning-process/ppc-2024-autumn pull request #527
Opened 2024-12-12 06:25 UTC by KolodkinGrigorii

Описание последовательной задачи: на вход подается числовой массив, после чего к нему применяется быстрая сортировка: выбирается опорный элемент, после чего массив упорядочивается и делится на два подмассива таким образом, что слева от опорного элемента находятся элементы меньше него, а справа больше. Процедура повторяется рекурсивно к подмассивам и так до тех пор, пока не останется один элемент. На выходе получается отсортированный по возрастанию массив.
Описание параллельной задачи: на вход подается числовой массив. Root-процесс делит его между другими процессами, а те в свою очередь выполняют над полученными участками быструю сортировку. Отсортированные участки отправляются на Root-процесс, который объединяет их при помощи слияния, а именно выбирает от каждого полученного сегмента данных минимальный элемент, сравнивает их и добавляет в итоговый массив. На выходе получается отсортированный по возрастанию массив.

2024-12-12 18:58 UTC, ascannel requested changes

2024-12-22 06:59 UTC, KolodkinGrigorii commented on tasks/mpi/kolodkin_g_hoar_merge_sort/perf_tests/main.cpp
> +    }
moved

2024-12-22 07:00 UTC, KolodkinGrigorii commented on tasks/mpi/kolodkin_g_hoar_merge_sort/func_tests/main.cpp
> +    }
moved

2024-12-22 07:00 UTC, KolodkinGrigorii commented on tasks/mpi/kolodkin_g_hoar_merge_sort/func_tests/main.cpp
> +TEST(kolodkin_g_hoar_merge_sort_MPI, Test_vector_with_one_elems) {
fixed

2024-12-22 07:10 UTC, MatveyKurakin reviewed
Add a test to check the vector with repeated elements

2024-12-22 08:59 UTC, MatveyKurakin approved these changes

2024-12-22 09:15 UTC, ascannel approved these changes

2024-12-22 22:44 UTC, allnes commented on tasks/mpi/kolodkin_g_hoar_merge_sort/func_tests/main.cpp
> +    vector.push_back(-100 + rand() % 100000);
please parametrize all constants in gtest (-100 and 100000)

2024-12-22 22:47 UTC, allnes commented on tasks/mpi/kolodkin_g_hoar_merge_sort/func_tests/main.cpp
> +  }
please remove this branche, all data need to be contained in root process only, or please descibe why do you use it

2024-12-22 22:48 UTC, allnes commented on tasks/mpi/kolodkin_g_hoar_merge_sort/func_tests/main.cpp
> +    vector = kolodkin_g_random_function::create_random_vector(1000);
please use 2^n, prime values also

2024-12-23 06:33 UTC, aobolensk approved these changes

2024-12-24 08:51 UTC, KolodkinGrigorii commented on tasks/mpi/kolodkin_g_hoar_merge_sort/func_tests/main.cpp
> +  }
removed

2024-12-24 08:51 UTC, KolodkinGrigorii commented on tasks/mpi/kolodkin_g_hoar_merge_sort/func_tests/main.cpp
> +    vector = kolodkin_g_random_function::create_random_vector(1000);
added

2024-12-24 08:51 UTC, KolodkinGrigorii commented on tasks/mpi/kolodkin_g_hoar_merge_sort/func_tests/main.cpp
> +    vector.push_back(-100 + rand() % 100000);
fixed

2024-12-24 16:15 UTC, allnes approved these changes

2024-12-24 16:15 UTC, merged