Колоколова Дарья. Задача 1. Вариант 15. Нахождение максимальных значений по строкам матрицы.
learning-process/ppc-2024-autumn pull request #53
Opened 2024-10-27 16:14 UTC by dasha1112

Описание последовательной задачи
На вход принимается вектор (матрица) и количество рядов и их размер. После этого вектор разбивается на ряды из которых образуется двумерный вектор вида std::vector<std::vector<int>>, то есть создается вектор элементами которого являются ряды матрицы, после чего в каждом ряду производится поиск максимального значения и результат сохранятся в векторе.

Описание MPI задачи
На вход принимается матрица, после чего на нулевом процессе она разбивается на ряды и каждому процессу передаем ряд матрицы. После этого в каждом процессе происходит локальный поиск максимума в ряду, после чего результат полученный каждым процессом оправляется нулевому с помощью метода gather и сохраняется в векторе с результатом.

2024-10-28 16:13 UTC, KaterinaKaraseva commented
В последовательной реализации в блоке validation лучше будет добавить проверку на корректность передаваемых данных, как это было сделано в MPI

2024-10-28 17:24 UTC, KaterinaKaraseva approved these changes

2024-10-28 18:31 UTC, dasha1112 commented on tasks/mpi/kolokolova_d_max_of_row_matrix/src/ops_mpi.cpp
> +  size_t row_count = static_cast<size_t>(*taskData->inputs[1]);
Thanks, fixed

2024-10-28 18:38 UTC, Kitos87 approved these changes

2024-10-29 00:24 UTC, aobolensk requested changes

2024-10-29 00:24 UTC, aobolensk commented on tasks/mpi/example/include/ops_mpi.hpp
>  #pragma once
Please revert all changes in examples. Common files should not be touched

2024-10-29 00:24 UTC, aobolensk commented on tasks/mpi/example/src/ops_mpi.cpp
>  #include "mpi/example/include/ops_mpi.hpp"
Please revert all changes in examples. Common files should not be touched

2024-10-29 00:24 UTC, aobolensk commented on tasks/mpi/kolokolova_d_max_of_row_matrix/func_tests/main.cpp
> +  int count_rows = world.size();
Please add tests when count_rows is not equal to world size

2024-10-29 00:24 UTC, aobolensk commented on tasks/mpi/kolokolova_d_max_of_row_matrix/func_tests/main.cpp
> +
Please add test when:
1. the matrix is empty
2. there is only one row
3. there is only one column

2024-10-29 19:01 UTC, dasha1112 commented on tasks/mpi/example/include/ops_mpi.hpp
>  #pragma once
Fixed

2024-10-29 19:01 UTC, dasha1112 commented on tasks/mpi/example/src/ops_mpi.cpp
>  #include "mpi/example/include/ops_mpi.hpp"
Fixed

2024-10-29 19:55 UTC, allnes commented on tasks/mpi/kolokolova_d_max_of_row_matrix/src/ops_mpi.cpp
> +    vec[i] = gen() % 100;
please use negative values too

2024-10-29 19:56 UTC, allnes commented on tasks/mpi/kolokolova_d_max_of_row_matrix/src/ops_mpi.cpp
> +bool kolokolova_d_max_of_row_matrix_mpi::TestMPITaskParallel::pre_processing() {
Please use all mpi functionality in run (), it's part of parallel algorithm

2024-10-30 12:48 UTC, dasha1112 commented on tasks/mpi/kolokolova_d_max_of_row_matrix/func_tests/main.cpp
> +  int count_rows = world.size();
Fixed

2024-10-30 12:49 UTC, dasha1112 commented on tasks/mpi/kolokolova_d_max_of_row_matrix/func_tests/main.cpp
> +
Added

2024-10-30 13:36 UTC, dasha1112 commented on tasks/mpi/kolokolova_d_max_of_row_matrix/src/ops_mpi.cpp
> +    vec[i] = gen() % 100;
Fixed, now values are generated ​​from -100 to 99

2024-10-31 00:22 UTC, aobolensk approved these changes

2024-10-31 09:24 UTC, dasha1112 commented on tasks/mpi/kolokolova_d_max_of_row_matrix/src/ops_mpi.cpp
> +bool kolokolova_d_max_of_row_matrix_mpi::TestMPITaskParallel::pre_processing() {
Fixed

2024-10-31 16:11 UTC, allnes approved these changes

2024-10-31 16:11 UTC, merged