Казунин Никита. Задача 3. Вариант 14. Быстрая сортировка с простым слиянием.
learning-process/ppc-2024-autumn pull request #532
Opened 2024-12-12 18:52 UTC by NikKazzzzzz

Описание функционала алгоритма
---

#### Декомпозиция данных и локальная сортировка:
Данные равномерно распределяются между процессами `(scatterv)`.
Каждый процесс сортирует свою часть данных с помощью итеративного быстрой сортировки `(iterative_quicksort)`.

#### Функция `worker_function`:
Рабочие процессы отправляют свои отсортированные элементы по одному мастеру.
После отправки каждого элемента рабочий процесс ждет подтверждения от мастера перед отправкой следующего.

#### Функция master_function:
Мастер-процесс использует минимальную кучу для эффективного слияния данных, поступающих от рабочих процессов.
На каждом шаге:
 - Из кучи извлекается наименьший элемент.
 - Этот элемент добавляется в результирующий массив.
 - Мастер запрашивает следующий элемент у соответствующего рабочего процесса (если в его данных еще есть элементы).
 - Процесс продолжается, пока куча не станет пустой.

#### Синхронизация и сбор результатов:
Функция `merge_func` вызывает `master_function` для мастера и `worker_function` для рабочих процессов.
Все процессы синхронизируются через барьер `(world.barrier())`, чтобы гарантировать завершение обмена данными.

---

### Общая структура:
- Распределением данных (scatterv).
- Локальной сортировкой.
- Слиянием результатов.

2024-12-12 20:10 UTC, korablev-vm requested changes

2024-12-12 20:10 UTC, korablev-vm commented on tasks/mpi/kazunin_n_quicksort_simple_merge/perf_tests/main.cpp
> +}  // namespace kazunin_n_quicksort_simple_merge_mpi
Perf тесты мы проводим на обратно отсортированных векторах.

2024-12-12 20:10 UTC, korablev-vm commented on tasks/seq/kazunin_n_quicksort_simple_merge/perf_tests/main.cpp
> +}
Аналогично, должен быть обратно отсортированный вектор

2024-12-14 20:57 UTC, venn2713 requested changes

2024-12-14 20:57 UTC, venn2713 commented on tasks/mpi/kazunin_n_quicksort_simple_merge/func_tests/main.cpp
добавьте тесты со случаными векторами

2024-12-14 20:57 UTC, venn2713 commented on tasks/mpi/kazunin_n_quicksort_simple_merge/perf_tests/main.cpp
> +  }
Генерируйте в тесты подходящую матрицу, и не делайте никаких скипов

2024-12-14 22:00 UTC, tyurinm requested changes

2024-12-14 22:06 UTC, tyurinm approved these changes

2024-12-14 22:17 UTC, venn2713 approved these changes

2024-12-15 05:34 UTC, korablev-vm approved these changes

2024-12-15 10:28 UTC, NikKazzzzzz commented on tasks/mpi/kazunin_n_quicksort_simple_merge/perf_tests/main.cpp
> +}  // namespace kazunin_n_quicksort_simple_merge_mpi
Fixed

2024-12-15 10:28 UTC, NikKazzzzzz commented on tasks/seq/kazunin_n_quicksort_simple_merge/perf_tests/main.cpp
> +}
Also fixed

2024-12-15 10:28 UTC, NikKazzzzzz commented on tasks/mpi/kazunin_n_quicksort_simple_merge/func_tests/main.cpp
fix

2024-12-15 10:28 UTC, NikKazzzzzz commented on tasks/mpi/kazunin_n_quicksort_simple_merge/perf_tests/main.cpp
> +  }
fix

2024-12-15 10:28 UTC, NikKazzzzzz commented on tasks/mpi/kazunin_n_quicksort_simple_merge/func_tests/main.cpp
> +TEST(kazunin_n_quicksort_simple_merge_mpi, test_quick_sort_1) {
fix

2024-12-15 18:50 UTC, aobolensk approved these changes

2024-12-22 22:56 UTC, allnes approved these changes

2024-12-22 22:56 UTC, merged