Коробейников Арсений. Задача 2. Вариант 18. Ленточная горизонтальная схема А, вертикальное В.
learning-process/ppc-2024-autumn pull request #534
Opened 2024-12-12 20:48 UTC by Arseny-Korobeinikov

2024-12-12 21:16 UTC, hasanyanovk commented on tasks/mpi/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/func_tests/main_korobeinikov.cpp
> +TEST(matrix_multiplication_horizontal_scheme_A_vertical_scheme_B,
Names of tests should contain your last name

2024-12-12 21:18 UTC, hasanyanovk commented on tasks/mpi/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/src/ops_mpi_korobeinikov.cpp
> +           ((int)*taskData->inputs[4] * (int)*taskData->inputs[5] == (int)taskData->inputs_count[3]);
Not need cast from inputs_count, it's already contains 4 bytes integer

2024-12-12 21:23 UTC, hasanyanovk commented on tasks/mpi/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/src/ops_mpi_korobeinikov.cpp
> +  displs.push_back(count_rows_on_proc * A_cols * (num_use_proc - 1));
You can wrap it to function and calculate the `counts` only in root process, because in other processes it's easier to calculate it's own size

2024-12-13 00:18 UTC, Arseny-Korobeinikov commented on tasks/mpi/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/func_tests/main_korobeinikov.cpp
> +TEST(matrix_multiplication_horizontal_scheme_A_vertical_scheme_B,
I don't understand how I forgot about it. Fixed

2024-12-13 00:19 UTC, Arseny-Korobeinikov commented on tasks/mpi/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/src/ops_mpi_korobeinikov.cpp
> +           ((int)*taskData->inputs[4] * (int)*taskData->inputs[5] == (int)taskData->inputs_count[3]);
Fixed

2024-12-13 00:19 UTC, Arseny-Korobeinikov commented on tasks/mpi/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/src/ops_mpi_korobeinikov.cpp
> +  displs.push_back(count_rows_on_proc * A_cols * (num_use_proc - 1));
I did the calculations only on root. Fixed

2024-12-13 05:19 UTC, hasanyanovk approved these changes

2024-12-13 10:12 UTC, MatveyKurakin commented on tasks/mpi/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/src/ops_mpi_korobeinikov.cpp
> +           ((*taskData->inputs[4]) * (*taskData->inputs[5]) == (int)taskData->inputs_count[3]);
add a check on TaskData->input.size() and for the rest of the input and output data, as well as tests

2024-12-13 10:12 UTC, MatveyKurakin commented on tasks/mpi/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/src/ops_mpi_korobeinikov.cpp
> +using namespace std::chrono_literals;
remove this

2024-12-13 13:28 UTC, Arseny-Korobeinikov commented on tasks/mpi/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/src/ops_mpi_korobeinikov.cpp
> +using namespace std::chrono_literals;
Removed

2024-12-13 13:28 UTC, Arseny-Korobeinikov commented on tasks/mpi/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/src/ops_mpi_korobeinikov.cpp
> +           ((*taskData->inputs[4]) * (*taskData->inputs[5]) == (int)taskData->inputs_count[3]);
Done

2024-12-13 13:28 UTC, Arseny-Korobeinikov commented on tasks/mpi/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/include/ops_mpi_korobeinikov.hpp
> +std::vector<int> getRandomVector(int sz);
Done

2024-12-13 14:47 UTC, MatveyKurakin approved these changes

2024-12-13 16:12 UTC, aobolensk requested changes

2024-12-13 16:12 UTC, aobolensk commented on tasks/seq/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/src/ops_seq_korobeinikov.cpp
> +      // res.data[i * res.count_cols + j] = 0;
Please, remove commented out code

2024-12-13 16:12 UTC, aobolensk commented on tasks/mpi/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/perf_tests/main_korobeinikov.cpp
> +    B = std::vector<int>(22500, 1);
Why perf tests are done on such shapes?

2024-12-13 16:19 UTC, Arseny-Korobeinikov commented on tasks/mpi/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/perf_tests/main_korobeinikov.cpp
> +    B = std::vector<int>(22500, 1);
Because the elements of the matrix are of type uint8_t and in the resulting matrix the element must satisfy the restriction of this data type

2024-12-14 11:31 UTC, Arseny-Korobeinikov commented on tasks/mpi/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/perf_tests/main_korobeinikov.cpp
> +    B = std::vector<int>(22500, 1);
I have 2-3 seconds of calculations on this data

2024-12-15 15:22 UTC, aobolensk approved these changes

2024-12-15 20:12 UTC, allnes approved these changes

2024-12-15 20:13 UTC, merged