Ясакова Татьяна. Задача 2. Вариант 6. Передача от всеx одному (reduce)
learning-process/ppc-2024-autumn pull request #535
Opened 2024-12-12 21:13 UTC by Tanya-Yasakova

Реализована функция reduce, которая используется для решения задачи нахождения минимального элемента в матрице.

Процесс работы следующий:
1. Корневой процесс разбивает исходную матрицу на равные части.
2. Каждый процесс получает свою часть матрицы и находит минимум в ней, используя функцию CustomReduce.
3. Функция CustomReduce реализована по принципу двоичного дерева. Начиная с листовых процессов (которые обрабатывают отдельные части данных), процессы постепенно объединяются со своими соседями.
4. На каждом шаге два объединяющихся процесса сливают свои промежуточные результаты (найденные минимумы), пока не останется одно итоговое минимальное значение, которое будет у корневого процесса.

Таким образом, распараллеливая обработку матрицы и используя иерархическое объединение промежуточных результатов, корневой процесс получает минимальный элемент всей матрицы.

2024-12-12 21:27 UTC, AnastasiaRezantseva requested changes

2024-12-12 21:27 UTC, AnastasiaRezantseva commented on tasks/mpi/yasakova_t_reduce/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
remove, you don't use this

2024-12-12 21:27 UTC, AnastasiaRezantseva commented on tasks/mpi/yasakova_t_reduce_custom/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
remove

2024-12-12 21:27 UTC, AnastasiaRezantseva commented on tasks/mpi/yasakova_t_reduce/func_tests/main.cpp
> +std::vector<int> getRandomVector(int size, int upper_border, int lower_border) {
please make this method static and move it to your namespace

2024-12-12 21:27 UTC, AnastasiaRezantseva commented on tasks/mpi/yasakova_t_reduce/func_tests/main.cpp
> +std::vector<std::vector<int>> getRandomMatrix(int rows, int columns, int upper_border, int lower_border) {
please make this method static and move it to your namespace

2024-12-12 21:55 UTC, Tanya-Yasakova commented on tasks/mpi/yasakova_t_reduce/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
I remove

2024-12-12 21:55 UTC, Tanya-Yasakova commented on tasks/mpi/yasakova_t_reduce/func_tests/main.cpp
> +std::vector<int> getRandomVector(int size, int upper_border, int lower_border) {
done

2024-12-12 22:06 UTC, AnastasiaRezantseva approved these changes

2024-12-12 22:09 UTC, emilien-gus requested changes

2024-12-12 22:09 UTC, emilien-gus commented on tasks/mpi/yasakova_t_reduce_custom/src/ops_mpi.cpp
> +#include <thread>
You don't use these headers

2024-12-12 22:09 UTC, emilien-gus commented on tasks/mpi/yasakova_t_reduce_custom/src/ops_mpi.cpp
> +void apply_operation(void *inbuf, void *inoutbuf, int count, MPI_Datatype datatype, MPI_Op op) {
You should throw error if used wrong MPI_Op

2024-12-12 22:27 UTC, Tanya-Yasakova commented on tasks/mpi/yasakova_t_reduce_custom/src/ops_mpi.cpp
> +#include <thread>
I remove

2024-12-12 22:28 UTC, Tanya-Yasakova commented on tasks/mpi/yasakova_t_reduce_custom/src/ops_mpi.cpp
> +void apply_operation(void *inbuf, void *inoutbuf, int count, MPI_Datatype datatype, MPI_Op op) {
add

2024-12-12 22:58 UTC, emilien-gus approved these changes

2024-12-13 06:52 UTC, AnastasiaRezantseva approved these changes

2024-12-15 16:10 UTC, aobolensk requested changes

2024-12-15 16:10 UTC, aobolensk commented on tasks/mpi/yasakova_t_reduce_custom/src/ops_mpi.cpp
> +  MPI_Bcast(&res, 1, MPI_INT, 0, MPI_COMM_WORLD);
Move data transfer to ::run() function

2024-12-15 17:25 UTC, Tanya-Yasakova commented on tasks/mpi/yasakova_t_reduce/include/ops_mpi.hpp
> +std::vector<std::vector<int>> getRandomMatrix(int rows, int columns, int upper_border, int lower_border);
done

2024-12-15 17:26 UTC, Tanya-Yasakova commented on tasks/mpi/yasakova_t_reduce_custom/src/ops_mpi.cpp
> +  MPI_Bcast(&res, 1, MPI_INT, 0, MPI_COMM_WORLD);
done

2024-12-16 03:53 UTC, aobolensk approved these changes

2024-12-22 22:57 UTC, allnes approved these changes

2024-12-22 22:57 UTC, merged