Golovkin Maksim. Task №3. Var №28. Linear Image Filtering with Block. Gaussian core 3x3.
learning-process/ppc-2024-autumn pull request #537
Opened 2024-12-13 08:26 UTC by Mxaqq

# Описание Работы

В рамках данной работы была реализована система линейной фильтрации изображений с блочным разбиением, включающая как последовательную (SimpleIntSEQ), так и параллельную (SimpleBlockMPI) версии алгоритма. Основной целью проекта являлось повышение эффективности обработки изображений путём распределения вычислительных задач на блоки, что позволяет оптимизировать использование ресурсов и ускорить процесс фильтрации.

## Основные компоненты реализации:

### Последовательная реализация (SimpleIntSEQ):

1. Валидация данных: Проверка корректности входных и выходных данных, включая размеры изображения.
2. Предварительная обработка: Инициализация входных данных и подготовка буфера для результатов.
3. Применение Гауссового фильтра: Разбиение изображения на блоки и последовательное применение 3x3 ядра Гаусса к каждому блоку.
4. Постобработка: Копирование обработанных данных в выходной буфер.

### Параллельная реализация (SimpleBlockMPI):

* Использование MPI для распределения данных между процессами.
* Обмен граничными строками (халлоу) между соседними процессами для корректного применения фильтра.
* Сбор обработанных данных от всех процессов для формирования окончательного изображения.

1. Валидация: Проверка корректности и полноты входных данных.
2. Предварительная обработка: Подготовка данных для фильтрации.
3. Выполнение: Применение фильтра Гаусса с блочным разбиением.
4. Постобработка: Сбор и сохранение результатов фильтрации.

2024-12-18 20:09 UTC, WladislawFilatew commented on tasks/mpi/golovkin_linear_image_filtering_with_block_partitioning/perf_tests/main.cpp
> +}
Пожалуйста, перенеси в namespace, так же и в других тестах

2024-12-18 20:09 UTC, WladislawFilatew commented on tasks/mpi/golovkin_linear_image_filtering_with_block_partitioning/perf_tests/main.cpp
> +#include <vector>
Пожалуйста, удали ненужные include, так же в других файлах

2024-12-19 08:24 UTC, Semyon1104 commented
You can add tests that check the behavior of the algorithm for very large image sizes or in the presence of abnormal data (for example, zero or negative pixel values).

2024-12-19 09:32 UTC, Mxaqq commented on tasks/mpi/golovkin_linear_image_filtering_with_block_partitioning/perf_tests/main.cpp
> +}
Выполнил

2024-12-19 11:23 UTC, WladislawFilatew approved these changes

2024-12-22 23:00 UTC, allnes commented on tasks/mpi/golovkin_linear_image_filtering_with_block_partitioning/func_tests/main.cpp
> +TEST(golovkin_linear_image_filtering_with_block_partitioning, VeryLargeImageTest) {
please add test (499, 501)

2024-12-22 23:01 UTC, allnes commented on tasks/mpi/golovkin_linear_image_filtering_with_block_partitioning/src/ops_mpi.cpp
> +    }
why do you check sizes < 3

2024-12-22 23:01 UTC, allnes commented on tasks/mpi/golovkin_linear_image_filtering_with_block_partitioning/src/ops_mpi.cpp
> +    MPI_Irecv(recv_down.data(), width_, MPI_INT, down, 0, world, &recv_down_req);
why do you use non-blocked mpi functions in this task

2024-12-24 06:07 UTC, Mxaqq commented on tasks/mpi/golovkin_linear_image_filtering_with_block_partitioning/src/ops_mpi.cpp
> +    }
The check of the width_ < 3 || height_ < 3 conditions was introduced to ensure the correct application of the 3x3 Gaussian kernel. To perform filtering, it is required that each dimension of the data block be at least 3 pixels, otherwise it is impossible to apply the filter correctly without going beyond the data boundaries.

2024-12-24 06:08 UTC, Mxaqq commented on tasks/mpi/golovkin_linear_image_filtering_with_block_partitioning/src/ops_mpi.cpp
> +    MPI_Irecv(recv_down.data(), width_, MPI_INT, down, 0, world, &recv_down_req);
I chose to use non-blocking MPI functions (MPI_Isend and MPI_Irecv) to increase the efficiency of data exchange between processes. Non-blocking calls allow you to initiate sending and receiving data without waiting for the operation to complete, which contributes to better resource utilization and reduced processor downtime. In the context of linear image filtering, this is especially useful when exchanging boundary lines (hallows) between neighboring processes, as it allows other calculations or communications to be performed in parallel.

2024-12-24 10:47 UTC, Mxaqq commented on tasks/mpi/golovkin_linear_image_filtering_with_block_partitioning/func_tests/main.cpp
> +TEST(golovkin_linear_image_filtering_with_block_partitioning, VeryLargeImageTest) {
add it.

2024-12-24 16:17 UTC, allnes approved these changes

2024-12-24 20:12 UTC, aobolensk approved these changes

2024-12-25 09:28 UTC, KAPUSHA228 requested changes

2024-12-25 09:28 UTC, KAPUSHA228 commented on tasks/seq/golovkin_linear_image_filtering_with_block_partitioning/func_tests/main.cpp
> +TEST(golovkin_linear_image_filtering_with_block_partitioning, TestGaussianFilterSmall) {
не хватает тестов на шум изображения, однородное изображение и на градиент

2024-12-25 09:38 UTC, Mxaqq commented on tasks/seq/golovkin_linear_image_filtering_with_block_partitioning/func_tests/main.cpp
> +TEST(golovkin_linear_image_filtering_with_block_partitioning, TestGaussianFilterSmall) {
add it.

2024-12-25 15:55 UTC, KAPUSHA228 approved these changes

2024-12-25 18:52 UTC, merged