Лопатин Илья. Задача 3. Вариант 15. Быстрая сортировка с чётно-нечётным слиянием Бэтчера.
learning-process/ppc-2024-autumn pull request #538
Opened 2024-12-13 10:06 UTC by ascannel

- **seq**
classic recursive quick sort

- **mpi**
1. chunk distribution:
calculates the size of each process's chunk of the array, accounting for any remainder.
determines the starting position and actual chunk size for each process based on its rank.

2. data distribution:
the root process (rank 0) sends its portion of the input array to other processes.
each process receives its assigned chunk of the data.

3. local sorting:
each process sorts its local chunk using the classic recursive quicksort algorithm.

4. odd-even merging:
in odd steps, processes send and receive data from their neighbors, merging their local arrays.
In even steps, the same process communication and merging occurs, but with adjusted conditions based on rank.

5. final gathering:
the root process gathers the sorted chunks from all processes into a final result array.

2024-12-15 20:11 UTC, Alexey2013 commented on tasks/mpi/lopatin_i_quick_batcher_mergesort/func_tests/quickBatcherMergesortFuncTestsMPI.cpp
> +}
wrap the function in a namespace

2024-12-15 20:11 UTC, Alexey2013 commented on tasks/seq/lopatin_i_quick_batcher_mergesort/func_tests/quickBatcherMergesortFuncTestsSeq.cpp
> +}
same

2024-12-15 20:26 UTC, ascannel commented on tasks/mpi/lopatin_i_quick_batcher_mergesort/func_tests/quickBatcherMergesortFuncTestsMPI.cpp
> +}
fixed

2024-12-15 21:36 UTC, Alexey2013 approved these changes

2024-12-19 21:08 UTC, Torcna requested changes

2024-12-19 21:08 UTC, Torcna commented on tasks/mpi/lopatin_i_quick_batcher_mergesort/src/quickBatcherMergesortMPI.cpp
> +}
Your implementation relies on recursive qsort. I believe we can significantly improve efficiency by switching to std::sort when the size of the vector to sort is less than 20 (or another suitable threshold).
This change would undoubtedly make any MPI program perform better.

2024-12-20 16:48 UTC, Torcna approved these changes

2024-12-20 16:48 UTC, ascannel commented on tasks/mpi/lopatin_i_quick_batcher_mergesort/src/quickBatcherMergesortMPI.cpp
> +}
added

2024-12-20 17:42 UTC, aobolensk approved these changes

2024-12-22 23:03 UTC, allnes commented on tasks/mpi/lopatin_i_quick_batcher_mergesort/func_tests/quickBatcherMergesortFuncTestsMPI.cpp
> +    outputArray[i] = (gen() % 200) - 99;
please parametrize constants in tests

2024-12-22 23:06 UTC, allnes commented on tasks/mpi/lopatin_i_quick_batcher_mergesort/src/quickBatcherMergesortMPI.cpp
> +    heapsort(localArray);
please use only quick sort, as yours task was called quick sort only

2024-12-22 23:07 UTC, allnes commented on tasks/seq/lopatin_i_quick_batcher_mergesort/func_tests/quickBatcherMergesortFuncTestsSeq.cpp
> +    outputArray[i] = (gen() % 200) - 99;
same point, please parametrize

2024-12-22 23:24 UTC, ascannel commented on tasks/mpi/lopatin_i_quick_batcher_mergesort/func_tests/quickBatcherMergesortFuncTestsMPI.cpp
> +    outputArray[i] = (gen() % 200) - 99;
now the function is made so that you can set the minimum and maximum limits for random values.
fixed.

2024-12-22 23:25 UTC, ascannel commented on tasks/mpi/lopatin_i_quick_batcher_mergesort/src/quickBatcherMergesortMPI.cpp
> +    heapsort(localArray);
yeah, that's fair, thought about performance on small chunks. removed.

2024-12-24 16:18 UTC, allnes approved these changes

2024-12-24 16:18 UTC, merged