Грудзин Константин. Задача 1. Вариант 7. Нахождение наиболее близких по значению соседних элементов вектора.
learning-process/ppc-2024-autumn pull request #54
Opened 2024-10-27 18:59 UTC by Konstantin-Grudzin

**Основная идея**:
Так как мы проверяем два соседних элемента, может случится проблема "наслаивания" двух массивов друг на друга. Чтобы это избежать, можно воспользоваться std::pair<int,int>. Где первый элемент пары - абсолютная разница между эдементом с индексом i и i+1, а второй - это сам индекс. Тогда пользуясь определением сравнения пар, задача свелась к поиску минимального элемента в массиве.

**Последовательная реализация**:
Мы проходимся по массиву и находим минимальный элемент среди пар.

**Реализация MPI**:
Мы разделяем наши массивы на несколько равных частей и отдаем каждому потоку свою часть массива.
Он вычисляет минимум и с помощью операции reduce передает эту информацию главному потоку

2024-10-28 14:04 UTC, Napkin-AI commented on tasks/seq/grudzin_k_nearest_neighbor_elements/include/ops_seq.hpp
> +  std::pair<int, int> res{};
Use two different variables for result.

2024-10-28 14:05 UTC, Napkin-AI commented on tasks/seq/grudzin_k_nearest_neighbor_elements/perf_tests/main.cpp
> +  for (int i = 0; i < size; ++i) {
Declare all the variables first.

2024-10-28 14:06 UTC, Napkin-AI commented on tasks/seq/grudzin_k_nearest_neighbor_elements/func_tests/main.cpp
> +TEST(grudzin_k_nearest_neighbor_elements_seq, Test_Close_Lazy) {
add some tests with different sizes

2024-10-28 14:13 UTC, Napkin-AI commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/include/ops_mpi.hpp
> +  std::pair<int, int> res;
Use two different variables for result.

2024-10-28 14:14 UTC, Napkin-AI commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/src/ops_mpi.cpp
> +  for (unsigned i = 0; i < taskData->inputs_count[0] - 1; i++) {
I don't think it's right to preprocess data in this way. It seems like it's enough to copy the array in pre-processing. Use ```std::copy```

2024-10-28 14:17 UTC, Napkin-AI commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/src/ops_mpi.cpp
> +  return taskData->outputs_count[0] == 1;
Your input data can be empty? I guess ```input_count``` should be more than 1

2024-10-29 10:44 UTC, Konstantin-Grudzin commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/src/ops_mpi.cpp
> +  return taskData->outputs_count[0] == 1;
fixed

2024-10-29 10:44 UTC, Konstantin-Grudzin commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/src/ops_mpi.cpp
> +    // Check count elements of output
fixed

2024-10-29 10:44 UTC, Konstantin-Grudzin commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/src/ops_mpi.cpp
> +  for (unsigned i = 0; i < taskData->inputs_count[0] - 1; i++) {
fixed

2024-10-29 10:47 UTC, Konstantin-Grudzin commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/include/ops_mpi.hpp
> +  std::pair<int, int> res{};
same as below

2024-10-29 10:47 UTC, Konstantin-Grudzin commented on tasks/seq/grudzin_k_nearest_neighbor_elements/src/ops_seq.cpp
> +    input_[i] = {abs(tmp_ptr[i] - tmp_ptr[i + 1]), i};
fixed

2024-10-29 10:47 UTC, Konstantin-Grudzin commented on tasks/seq/grudzin_k_nearest_neighbor_elements/include/ops_seq.hpp
> +  std::pair<int, int> res{};
same as below

2024-10-29 10:50 UTC, Konstantin-Grudzin commented on tasks/seq/grudzin_k_nearest_neighbor_elements/perf_tests/main.cpp
> +  for (int i = 0; i < size; ++i) {
fixed

2024-10-29 10:50 UTC, Konstantin-Grudzin commented on tasks/seq/grudzin_k_nearest_neighbor_elements/perf_tests/main.cpp
> +  for (int i = 0; i < size; ++i) {
fixed

2024-10-29 11:04 UTC, Konstantin-Grudzin commented on tasks/seq/grudzin_k_nearest_neighbor_elements/func_tests/main.cpp
> +TEST(grudzin_k_nearest_neighbor_elements_seq, Test_Close_Lazy) {
fixed

2024-10-29 11:05 UTC, Konstantin-Grudzin commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/func_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
fixed

2024-10-30 08:42 UTC, Napkin-AI approved these changes

2024-10-30 08:47 UTC, EgorDormidontov requested changes

2024-10-30 08:47 UTC, EgorDormidontov commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/src/ops_mpi.cpp
> +    vec[i] = gen() % 100;
Add negative numbers generation

2024-10-30 08:47 UTC, EgorDormidontov commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/src/ops_mpi.cpp
> +    res = std::min(res, {abs(input_[i] - input_[i + 1]), i});
Don`t create temp object in std::min

2024-10-30 08:47 UTC, EgorDormidontov commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/src/ops_mpi.cpp
> +    local_ans_ = std::min(local_ans_, {abs(local_input_[i] - local_input_[i + 1]), i + start});
Don`t create temp object in std::min

2024-10-30 10:22 UTC, EgorDormidontov approved these changes

2024-10-31 00:48 UTC, aobolensk requested changes

2024-10-31 00:48 UTC, aobolensk commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
Please, move this function to the test module

2024-10-31 07:53 UTC, Konstantin-Grudzin commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
Move function but i keep it in namespace to prevent pontetial conflicts.

2024-10-31 16:23 UTC, allnes requested changes

2024-10-31 16:23 UTC, allnes commented on tasks/seq/grudzin_k_nearest_neighbor_elements/src/ops_seq.cpp
> +using namespace std::chrono_literals;
For waht do you use it?

2024-10-31 16:23 UTC, allnes commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/src/ops_mpi.cpp
> +bool grudzin_k_nearest_neighbor_elements_mpi::TestMPITaskParallel::pre_processing() {
please use mpi functions only in run() function

2024-11-01 05:35 UTC, Konstantin-Grudzin commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/src/ops_mpi.cpp
> +bool grudzin_k_nearest_neighbor_elements_mpi::TestMPITaskParallel::pre_processing() {
fixed

2024-11-01 05:35 UTC, Konstantin-Grudzin commented on tasks/seq/grudzin_k_nearest_neighbor_elements/src/ops_seq.cpp
> +using namespace std::chrono_literals;
remove namespace and thread library

2024-11-01 16:29 UTC, aobolensk commented on tasks/mpi/grudzin_k_nearest_neighbor_elements/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
OK, also if you want to avoid potential conflicts static function is applicable for such cases

2024-11-01 16:29 UTC, aobolensk approved these changes

2024-11-02 01:21 UTC, allnes approved these changes

2024-11-02 01:22 UTC, merged