Коровин Никита. Задача 3. Вариант 1. Умножение плотных матриц. Элементы типа double. Блочная схема, алгоритм Кэннона.
learning-process/ppc-2024-autumn pull request #540
Opened 2024-12-13 19:13 UTC by Kitos87

#  **Блочная схема, алгоритм Кэннона**

В MPI-версии алгоритма Кэннона основная идея состоит в том, чтобы использовать наименьший квадрат числа процессов. Если общее количество процессов не является квадратом, выбирается `q = floor(sqrt(size))`, и только `q×q` процессов активно участвуют в вычислениях, в то время как остальные остаются неактивными. Такой подход упрощает реализацию алгоритма Кэннона, который наиболее эффективно работает именно на квадратной решётке процессов.

Для упрощения обмена данными между процессами используется декартовая топология MPI. Команды `MPI_Cart_create`, `MPI_Cart_coords` и `MPI_Cart_shift` позволяют просто и наглядно осуществлять циклические сдвиги блоков матриц вдоль строк и столбцов. Хотя декартовая топология особенно актуальна для систем с распределённой памятью и сложной топологией соединений, она всё же предоставляет удобный функционал, упрощающий логику обмена данными и структуру кода, даже в среде с общей памятью.

## Этапы MPI-версии:

**pre_processing**  
- На корневом процессе загружаются размеры и данные входных матриц `A` и `B`

**validation**
- На корневом процессе проверяется корректность входных данных: размеры матриц и наличие входных/выходных буферов

**run** 
- Распространяются размеры матриц среди всех процессов
- Определяется размерность решётки `q×q` и формируется декартовая топология из активных процессов. Неактивные процессы отделяются и не участвуют в вычислениях
- Матрицы при необходимости дополнительно заполняются нулями до размеров, кратных `q`, для удобного разбиения на блоки
- Корневой процесс разрезает матрицы на блоки и распределяет их среди активных процессов.
- Выполняется алгоритм Кэннона: на каждой итерации процессы умножают свои локальные блоки, затем циклически сдвигают блоки `A` налево по строкам и `B` вверх по столбцам с помощью функций декартовой топологии (`MPI_Cart_shift`)
- По окончании итераций корневой процесс собирает все полученные блоки результата в финальную матрицу `C`

**post_processing** 
- На корневом процессе итоговый результат умножения копируется в выходной буфер

## Этапы Seq:

В последовательной версии (seq) `pre_processing` и `validation` ничем принципиально не отличаются от параллельной: они просто загружают и проверяют входные данные. Основная работа происходит в методе `run`, где задача умножения матриц решается обычным тройным вложенным циклом. Исходные матрицы `A` и `B` считываются в вектор, затем для каждого элемента результирующей матрицы `C` последовательно вычисляется сумма произведений соответствующих элементов из `A` и `B`. После завершения умножения готовая матрица `C` копируется в выходной буфер в методе `post_processing`.

Таким образом, использование ближайшего квадрата процессов для параллельного умножения матриц, а также декартовой топологии MPI, делает реализацию алгоритма Кэннона более понятной, удобной и структурированной в MPI-версии

2024-12-13 23:20 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/include/ops_mpi.hpp
> +  int k;
fixed

2024-12-13 23:20 UTC, Kitos87 commented on tasks/seq/korovin_n_matrix_multiple_cannon/src/ops_seq.cpp
> +  k = taskData->inputs_count[2];
Done

2024-12-13 23:20 UTC, Kitos87 commented on tasks/seq/korovin_n_matrix_multiple_cannon/include/ops_seq.hpp
> +  int k;
Fixed

2024-12-13 23:21 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/include/ops_mpi.hpp
> +};
Fixed

2024-12-13 23:21 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/src/ops_mpi.cpp
> +  k = taskData->inputs_count[2];
Done

2024-12-13 23:21 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/src/ops_mpi.cpp
> +    k = taskData->inputs_count[2];
Done

2024-12-13 23:22 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
Yes, thanks, I added this test

2024-12-14 06:04 UTC, ermolaevv approved these changes

2024-12-15 10:53 UTC, NikKazzzzzz requested changes
There were more tests than I expected. Please use the same structure in all tests.

2024-12-15 10:53 UTC, NikKazzzzzz commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +  ASSERT_EQ(testTask.validation(), true);
Please use ASSERT_TRUE
```suggestion
  ASSERT_TRUE(testTask.validation());
```

2024-12-15 10:53 UTC, NikKazzzzzz commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +    ASSERT_EQ(testTaskSeq.validation(), true);
```suggestion
    ASSERT_TRUE(testTaskSeq.validation());
```

2024-12-15 10:53 UTC, NikKazzzzzz commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +      ASSERT_DOUBLE_EQ(C_mpi[i], C_seq[i]);
```suggestion
      EXPECT_DOUBLE_EQ(C_mpi[i], C_seq[i]);
```

2024-12-15 10:53 UTC, NikKazzzzzz commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +  ASSERT_EQ(testTask.validation(), true);
```suggestion
  ASSERT_TRUE(testTask.validation());
```

2024-12-15 10:53 UTC, NikKazzzzzz commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +    ASSERT_EQ(testTaskSeq.validation(), true);
```suggestion
    ASSERT_TRUE(testTaskSeq.validation());
```

2024-12-15 10:53 UTC, NikKazzzzzz commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +      ASSERT_DOUBLE_EQ(C_mpi[i], C_seq[i]);
```suggestion
      EXPECT_DOUBLE_EQ(C_mpi[i], C_seq[i]);
```

2024-12-15 10:53 UTC, NikKazzzzzz commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +  ASSERT_EQ(testTask.validation(), true);
```suggestion
  ASSERT_TRUE(testTask.validation());
```

2024-12-15 10:53 UTC, NikKazzzzzz commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +    ASSERT_EQ(testTaskSeq.validation(), true);
```suggestion
    ASSERT_TRUE(testTaskSeq.validation());
```

2024-12-15 10:53 UTC, NikKazzzzzz commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +      ASSERT_DOUBLE_EQ(C_mpi[i], C_seq[i]);
```suggestion
      EXPECT_DOUBLE_EQ(C_mpi[i], C_seq[i]);
```

2024-12-15 10:53 UTC, NikKazzzzzz commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +  ASSERT_EQ(testTask.validation(), true);
```suggestion
  ASSERT_TRUE(testTask.validation());
```

2024-12-15 10:53 UTC, NikKazzzzzz commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +    ASSERT_EQ(testTaskSeq.validation(), true);
```suggestion
    ASSERT_TRUE(testTaskSeq.validation());
```

2024-12-15 10:53 UTC, NikKazzzzzz commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +      ASSERT_DOUBLE_EQ(C_mpi[i], C_seq[i]);
```suggestion
      EXPECT_DOUBLE_EQ(C_mpi[i], C_seq[i]);
```

2024-12-15 10:53 UTC, NikKazzzzzz commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +  ASSERT_EQ(testTask.validation(), true);
```suggestion
  ASSERT_TRUE(testTask.validation());
```

2024-12-15 11:04 UTC, venn2713 requested changes

2024-12-15 11:04 UTC, venn2713 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/src/ops_mpi.cpp
> +  C_.resize(numRowsA_ * numColsB_, 0.0);
Я думаю во всех resize у вас нет необходимости заполнять все 0.0

2024-12-15 11:04 UTC, venn2713 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/src/ops_mpi.cpp
> +  numColsB_ = taskData->inputs_count[2];
Вы принимаете данные на этапе валидации, а лучше здесь создать переменные для врменной проверки, типа int temp_numRowsA_ и принять и проверить, а данный код перенести в pre_processing

2024-12-15 11:04 UTC, venn2713 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/src/ops_mpi.cpp
> +  MPI_Comm_free(&active_comm);
Я бы протестировал без этого блока, думаю ничего не изменится (но это теория)

2024-12-15 13:19 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/perf_tests/main.cpp
> +
![image](https://github.com/user-attachments/assets/a71fedee-0168-4dd7-b517-103de7c2534b)

I don't think that's necessary.

2024-12-15 13:19 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/perf_tests/main.cpp
> +    taskData->outputs_count.emplace_back(C.size());
Fixed

2024-12-15 13:20 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/perf_tests/main.cpp
> +  // Create Perf attributes
Fixed

2024-12-15 13:20 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/src/ops_mpi.cpp
> +  C_.resize(numRowsA_ * numColsB_, 0.0);
Done

2024-12-15 13:20 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/src/ops_mpi.cpp
> +  numColsB_ = taskData->inputs_count[2];
Done

2024-12-15 13:21 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/include/ops_mpi.hpp
> +// Copyright 2023 Nesterov Alexander
Fixed

2024-12-15 13:24 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +  ASSERT_EQ(testTask.validation(), true);
Thanks, done

2024-12-15 13:24 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +    ASSERT_EQ(testTaskSeq.validation(), true);
Fix

2024-12-15 13:24 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +      ASSERT_DOUBLE_EQ(C_mpi[i], C_seq[i]);
Fix

2024-12-15 13:24 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +  ASSERT_EQ(testTask.validation(), true);
Fix

2024-12-15 13:24 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +    ASSERT_EQ(testTaskSeq.validation(), true);
Fix

2024-12-15 13:24 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +      ASSERT_DOUBLE_EQ(C_mpi[i], C_seq[i]);
Fix

2024-12-15 13:25 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +  ASSERT_EQ(testTask.validation(), true);
Fix

2024-12-15 13:25 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +    ASSERT_EQ(testTaskSeq.validation(), true);
Fix

2024-12-15 13:25 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +  ASSERT_EQ(testTask.validation(), true);
Done

2024-12-15 13:25 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +    ASSERT_EQ(testTaskSeq.validation(), true);
Done

2024-12-15 13:25 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +      ASSERT_DOUBLE_EQ(C_mpi[i], C_seq[i]);
Thanks, fixed

2024-12-15 13:25 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
> +  ASSERT_EQ(testTask.validation(), true);
Fix

2024-12-15 13:26 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/src/ops_mpi.cpp
> +  MPI_Comm_free(&active_comm);
Done

2024-12-15 16:48 UTC, venn2713 approved these changes

2024-12-15 19:11 UTC, NikKazzzzzz approved these changes

2024-12-22 15:20 UTC, kmichaelk commented on tasks/mpi/korovin_n_matrix_multiple_cannon/src/ops_mpi.cpp
> +    B_ = std::move(B_padded);
Did you check if perf tests work after this? Unless I've missed anything, with each iteration they will work slower due to the fact that there will be more and more data each time, the run function it is not idempotent, keep the original data untouched.

2024-12-22 17:45 UTC, kmichaelk approved these changes

2024-12-22 18:32 UTC, Kitos87 commented on tasks/mpi/korovin_n_matrix_multiple_cannon/src/ops_mpi.cpp
> +    B_ = std::move(B_padded);
Fixed

2024-12-22 23:12 UTC, allnes approved these changes

2024-12-22 23:12 UTC, merged