Варфоломеев Григорий. Задача 3. Вариант 14. Быстрая сортировка с простым слиянием.
learning-process/ppc-2024-autumn pull request #544
Opened 2024-12-14 10:05 UTC by petr1core

Алгоритм быстрой сортировки — это эффективный алгоритм сортировки, основанный на принципе "разделяй и властвуй". Он разбивает массив на подмассивы, сортирует их рекурсивно и объединяет результаты. В последовательной реализации выбирается опорный элемент, каждый массив делится на две части, и каждая часть сортируется отдельно. Этот процесс повторяется до полного упорядочивания массива.

Параллельная реализация распределяет данные между несколькими процессами и каждый процесс выполняет быструю сортировку на своём объёме данных. В последствии, каждый процесс выполняет локальную сортировку, а затем отправляет результаты корневому процессу. Корневой процесс объединяет отсортированные части в окончательный результат. Такой подход позволяет ускорить выполнение алгоритма за счёт привлечения бóльших мощностей.

2024-12-16 07:11 UTC, andrewmeow requested changes

2024-12-16 07:11 UTC, andrewmeow commented on tasks/mpi/varfolomeev_g_quick_sort_simple_merge/func_tests/main.cpp
> +std::vector<int> getRandomVector_mpi(int sz, int a, int b) {  // [a, b]
Покрытие хорошее, но, возможно, стоит написать тесты и для функций getRandomVector_mpi и getAntisorted_mpi тоже для надежности?
Также не вижу проверку на следующие входные:
- пустой вектор
- вектор размером 1
- вектор, состоящий из дублей

2024-12-16 07:11 UTC, andrewmeow commented on tasks/mpi/varfolomeev_g_quick_sort_simple_merge/include/ops_mpi.hpp
> +  static std::vector<int> quickSort(const std::vector<int>& vec) {
Для чего этот буферный вектор sortedvec? Я думаю, это не имеет смысла, и стоит вообще убрать публичную функцию quickSort, а приватную quickSortRecursive перенести в public.

2024-12-18 13:34 UTC, KAPUSHA228 requested changes

2024-12-18 13:34 UTC, KAPUSHA228 commented on tasks/seq/varfolomeev_g_quick_sort_simple_merge/func_tests/main.cpp
> +TEST(varfolomeev_g_quick_sort_simple_merge_seq, Test_getRandomVector_func) {
нет теста или валидации на уже отсортированный массив

2024-12-18 19:33 UTC, petr1core commented on tasks/mpi/varfolomeev_g_quick_sort_simple_merge/func_tests/main.cpp
> +std::vector<int> getRandomVector_mpi(int sz, int a, int b) {  // [a, b]
Спасибо, дополнил. Вспомогательные функции в тестах для mpi и seq идентичны, поэтому протестировал их в seq-func_tests

2024-12-18 19:37 UTC, petr1core commented on tasks/seq/varfolomeev_g_quick_sort_simple_merge/func_tests/main.cpp
> +TEST(varfolomeev_g_quick_sort_simple_merge_seq, Test_getRandomVector_func) {
Благодарю. Всё учтено и исправлено

2024-12-18 20:33 UTC, andrewmeow approved these changes

2024-12-18 21:10 UTC, KAPUSHA228 approved these changes

2024-12-22 09:43 UTC, aobolensk approved these changes

2024-12-22 23:21 UTC, allnes approved these changes

2024-12-22 23:21 UTC, merged