Шурыгин Сергей. Задача №3. Вариант №28. Ленточная вертикальная схема. Ядро Гаусса 3x3 (блочное разбиение).
learning-process/ppc-2024-autumn pull request #545
Opened 2024-12-14 10:16 UTC by PutinVVV

### **Общая информация**

Данный проект реализует распределённый алгоритм линейной фильтрации изображений с использованием Гауссовского ядра размером 3x3. Для достижения высокой производительности используется блочное разбиение изображения и параллельная обработка с применением библиотеки MPI.

### **Реализация методов класса TaskMpi**

- Метод validation():

> - Проверяет корректность входных данных, включая размеры матрицы и наличие выходных значений. Убедитесь, что входные данные имеют достаточный размер для обработки.

- Метод pre_processing():

> -Подготавливает данные, извлекая параметры изображения и генерируя индексы для обработки. Вычисляет размеры блоков и смещения для соответствующих данных.

- Метод run():
 

> -Осуществляет основную обработку:

> -Распространяет данные между процессами и выполняет локальную обработку изображения с применением Гауссовского фильтра. Результаты собираются на главном процессе.

- Метод post_processing():
 

> -Завершает процесс обработки, возвращая обработанные данные в выходной массив, при этом добавляя нули вокруг результата для корректного отображения.

2024-12-18 00:03 UTC, NeeMiyuki requested changes

2024-12-18 00:03 UTC, NeeMiyuki commented on tasks/mpi/shurigin_lin_filtr_razbien_bloch_gaus_3x3/src/ops_mpi.cpp
> +#include <vector>
limits, iostream and functional are not used, so should be removed

2024-12-18 11:23 UTC, PutinVVV commented on tasks/mpi/shurigin_lin_filtr_razbien_bloch_gaus_3x3/src/ops_mpi.cpp
> +#include <vector>
ok, im deleted it

2024-12-18 12:16 UTC, NeeMiyuki approved these changes

2024-12-18 20:02 UTC, Alexey-Solovev approved these changes

2024-12-20 17:20 UTC, MikasaAkc approved these changes

2024-12-22 09:48 UTC, aobolensk requested changes

2024-12-22 09:48 UTC, aobolensk commented on tasks/mpi/shurigin_lin_filtr_razbien_bloch_gaus_3x3/func_tests/main.cpp
> +TEST(shurigin_lin_filtr_razbien_bloch_gaus_3x3_mpi, validation_zero_zero) {
Please, add fixed tests and more random tests on different image sizes

2024-12-22 09:48 UTC, aobolensk commented on tasks/mpi/shurigin_lin_filtr_razbien_bloch_gaus_3x3/perf_tests/main.cpp
> +TEST(shurigin_lin_filtr_razbien_bloch_gaus_3x3_mpi, Performance_Pipeline_Run) {
Please, fix perf tests names and remove extra perf tests

2024-12-22 09:48 UTC, aobolensk commented on tasks/mpi/shurigin_lin_filtr_razbien_bloch_gaus_3x3/perf_tests/main.cpp
> +  int num_cols = 100;
Size is too small for perf tests

2024-12-22 12:45 UTC, PutinVVV commented on tasks/mpi/shurigin_lin_filtr_razbien_bloch_gaus_3x3/func_tests/main.cpp
> +TEST(shurigin_lin_filtr_razbien_bloch_gaus_3x3_mpi, validation_zero_zero) {
ok, done

2024-12-22 12:45 UTC, PutinVVV commented on tasks/mpi/shurigin_lin_filtr_razbien_bloch_gaus_3x3/perf_tests/main.cpp
> +TEST(shurigin_lin_filtr_razbien_bloch_gaus_3x3_mpi, Performance_Pipeline_Run) {
Fix

2024-12-22 17:57 UTC, aobolensk approved these changes

2024-12-22 23:25 UTC, allnes commented on tasks/mpi/shurigin_lin_filtr_razbien_bloch_gaus_3x3/src/ops_mpi.cpp
> +    weights[i] = std::exp(-0.5 * i / num_proc);
its not 3x3 gauss kernel, its gauss function

2024-12-22 23:26 UTC, allnes commented on tasks/mpi/shurigin_lin_filtr_razbien_bloch_gaus_3x3/src/ops_mpi.cpp
> +const double KERNEL[3][3] = {{0.0625, 0.125, 0.0625}, {0.125, 0.25, 0.125}, {0.0625, 0.125, 0.0625}};
its not gauss approximation

2024-12-22 23:26 UTC, allnes commented on tasks/mpi/shurigin_lin_filtr_razbien_bloch_gaus_3x3/src/ops_mpi.cpp
> +const double KERNEL[3][3] = {{0.0625, 0.125, 0.0625}, {0.125, 0.25, 0.125}, {0.0625, 0.125, 0.0625}};
please describe yours solution

2024-12-23 10:02 UTC, PutinVVV commented on tasks/mpi/shurigin_lin_filtr_razbien_bloch_gaus_3x3/src/ops_mpi.cpp
> +    weights[i] = std::exp(-0.5 * i / num_proc);
This was my experiment with the data distribution method, it got into the commit by accident, I deleted it.

2024-12-23 10:20 UTC, PutinVVV commented on tasks/mpi/shurigin_lin_filtr_razbien_bloch_gaus_3x3/src/ops_mpi.cpp
> +const double KERNEL[3][3] = {{0.0625, 0.125, 0.0625}, {0.125, 0.25, 0.125}, {0.0625, 0.125, 0.0625}};
This is the Gaussian kernel for sigma =0.8 (you can verify this on the website http://www.demofox.org/gauss.html )

2024-12-23 10:20 UTC, PutinVVV commented on tasks/mpi/shurigin_lin_filtr_razbien_bloch_gaus_3x3/src/ops_mpi.cpp
> +const double KERNEL[3][3] = {{0.0625, 0.125, 0.0625}, {0.125, 0.25, 0.125}, {0.0625, 0.125, 0.0625}};
For each pixel of the image, a weighted sum of the pixel values in its surroundings is calculated using a Gaussian kernel.

2024-12-24 16:54 UTC, allnes approved these changes

2024-12-24 16:55 UTC, merged