Хасаньянов Кирилл. Задача 3. Вариант 2. Умножение плотных матриц. Блочная схема, алгоритм Фокса.
learning-process/ppc-2024-autumn pull request #548
Opened 2024-12-14 12:51 UTC by hasanyanovk

## Описание последовательного алгоритма:  
Последовательное умножение матриц за _O(n<sup>3</sup>)_  
## Описание параллельного алгоритма:   
Реализовано умножение матриц с помощью [алгоритма Фокса](https://www.opennet.ru/docs/RUS/linux_parallel/node158.html/).  
1. Вычисляем количество процессов, которые будут участвовать в умножении(их количество должно быть степенью целого числа).
2. Лишние процессы делаем недействительными, получаем новый коммуникатор с помощью `mpi::communicator::split()`.
3. Рассчитываем размеры квадратных блоков в зависимости от количества процессов.
4. Каждому процессу рассылаем блоки матриц в соответствии с их номерами, при этом недостающие до квадратной матрицы элементы считаем равными 0.
5. Далее за $\sqrt{p}$ итераций, где _p_ - количество процессов вычисляем произведение матриц согласно алгоритму в каждом процессе.
6. Собираем блоки в сетку в `root-процессе`.
7. Итоговую сетку из блоков преобразуем в результирующую матрицу.

2024-12-15 09:29 UTC, Kitos87 commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/func_tests/matrix_tests.cpp
> +
Please, add tests for the following cases: multiplication of matrices of size 1x1, also `A * A^{-1} = E`. I think, optionally, multiplication by the zero matrix and the unit matrix can also be checked.

2024-12-15 09:29 UTC, Kitos87 commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/perf_tests/main.cpp
> +    ASSERT_EQ(expected, C);
I think this check is unnecessary here specifically in perf tests, since you check the main work of your algorithm in functional tests

2024-12-15 09:29 UTC, Kitos87 commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/perf_tests/main.cpp
> +    ASSERT_EQ(expected, C);
Same

2024-12-15 10:30 UTC, hasanyanovk commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/func_tests/matrix_tests.cpp
> +
these cases already checked in func_tests, check tuples for my test class

2024-12-15 10:30 UTC, hasanyanovk commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/perf_tests/main.cpp
> +    ASSERT_EQ(expected, C);
fixed

2024-12-15 10:30 UTC, hasanyanovk commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/perf_tests/main.cpp
> +    ASSERT_EQ(expected, C);
same

2024-12-15 12:51 UTC, Kitos87 approved these changes

2024-12-15 21:04 UTC, venn2713 requested changes

2024-12-15 21:04 UTC, venn2713 commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/func_tests/fox_algorithm_tests.cpp
> +  // can't mult these matrix
удалите комментарии из релизной версии пожулуйста

2024-12-15 21:04 UTC, venn2713 commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/func_tests/fox_algorithm_tests.cpp
> +    ASSERT_EQ(expected, C);
В таких ситуациях используйте EXPECT (это последняя проверка теста)

2024-12-15 21:04 UTC, venn2713 commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/include/fox_algorithm.hpp
> +    // std::cout << "С:\n" << C << std::endl;
И по всему документу (про комментарии)

2024-12-15 21:19 UTC, hasanyanovk commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/func_tests/fox_algorithm_tests.cpp
> +  // can't mult these matrix
fixed

2024-12-15 21:19 UTC, hasanyanovk commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/func_tests/fox_algorithm_tests.cpp
> +    ASSERT_EQ(expected, C);
done

2024-12-15 21:20 UTC, hasanyanovk commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/include/fox_algorithm.hpp
> +    // std::cout << "С:\n" << C << std::endl;
done

2024-12-15 21:25 UTC, venn2713 approved these changes

2024-12-15 22:05 UTC, kmichaelk approved these changes

2024-12-15 22:05 UTC, kmichaelk commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/include/fox_algorithm.hpp
> +  }
Seems like you can just floor `sqrt(size)`, or I got it wrong?

2024-12-15 22:06 UTC, kmichaelk commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/include/fox_algorithm.hpp
> +  }
nvm,

2024-12-16 08:08 UTC, hasanyanovk commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/include/fox_algorithm.hpp
> +  }
I use `static_cast` to avoid casting after call `floor`, because that function returns `double`

2024-12-16 08:11 UTC, belovtut approved these changes

2024-12-22 09:58 UTC, aobolensk requested changes
seq version is missing

2024-12-22 09:58 UTC, aobolensk commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/include/matrix_operations.hpp
> +matrix<T> MatrixOperations::generate_random_matrix(size_t rows, size_t columns, const T& left, const T& right) {
Please, move test functions to the test module

2024-12-22 09:58 UTC, aobolensk commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/perf_tests/main.cpp
> +  const int n = 256;
It seems these sizes are too small for perf tests

2024-12-22 09:58 UTC, aobolensk commented
Test coverage is too low as well

2024-12-22 10:09 UTC, hasanyanovk commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/include/matrix_operations.hpp
> +matrix<T> MatrixOperations::generate_random_matrix(size_t rows, size_t columns, const T& left, const T& right) {
This function is a member of `MatrixOperations`, it's not only for tests and includes into all tests files

2024-12-22 23:34 UTC, allnes commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/perf_tests/main.cpp
> +#include <boost/mpi/timer.hpp>
where seq version as simple gemm? opposit we can't check speed up

2024-12-23 11:50 UTC, hasanyanovk commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/perf_tests/main.cpp
> +#include <boost/mpi/timer.hpp>
It is implemented as a simple matrix multiplication, can I make perf tests on it without creating new files in the `seq` folder because the Fox algorithm itself does not imply a sequential solution?

2024-12-23 11:51 UTC, hasanyanovk commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/include/fox_algorithm.hpp
> +  }
I got you idea, fixed, ty

2024-12-23 15:14 UTC, hasanyanovk commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/perf_tests/main.cpp
> +  const int n = 256;
fixed

2024-12-23 15:18 UTC, hasanyanovk commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/perf_tests/main.cpp
> +#include <boost/mpi/timer.hpp>
Regarding the project coverage, I want to draw attention to the fact that _codecov_ incorrectly determines this coverage, if you look at the report, it will become clear that the main problem is that the `create_task_data` function is not covered, although it is obvious that this function is called in absolutely every test. Help and explain how to fix this please

2024-12-24 17:00 UTC, allnes commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/perf_tests/main.cpp
> +#include <boost/mpi/timer.hpp>
@hasanyanovk without seq we can't undetstand perf values, sorry, please create it
@aobolensk please help with coverage

2024-12-24 20:33 UTC, hasanyanovk commented on tasks/mpi/khasanyanov_k_multiply_matrix_fox_algorithm_mpi/perf_tests/main.cpp
> +#include <boost/mpi/timer.hpp>
Got it, done

2024-12-27 13:39 UTC, aobolensk approved these changes

2024-12-27 13:39 UTC, merged