Миронов Арсений. Задача 1. Вариант 3. Максимальное значение элементов вектора.
learning-process/ppc-2024-autumn pull request #55
Opened 2024-10-27 19:16 UTC by Napkin-AI

### Описание последовательной задачи:
1. Инициализация переменной ```result```, в которой будет храниться максимальное значение вектора. Эта переменная изначально может быть установлена равной первому элементу вектора ```input_```.
2. Для каждого элемента выполняется сравнение его значения с текущим  максимумом ```result```.
3. Если значение текущего элемента больше, чем значение переменной, то текущий максимум обновляется.
4. После проверки всех элементов вектора, в переменной ```result``` будет храниться максимальное значение.

### Описание MPI задачи:
1. **Разделение данных**
Исходный вектор делится на фрагменты. Размеры каждого блока ```delta``` одинаковые и равны частному количества элементов и количеству процессов с округлением вверх. Если количество элементов не делится нацело на количество процессов, то искуственно добавляем несколько элементов в вектор, равные минимальному целочисленному числу, причём их количество опеределяется остатком от деления. Перессылка элементов вектора по процессам осуществляется методами класса ```boost::mpi::communicator```: ```send``` и ```recv```. Отправка ```delta``` осуществляется при помощи функции ```broadcast```.
2. **Обработка фрагментов**
Каждый процесс выполняет поиск максимального значения в своем фрагменте вектора, используя алгоритм, аналогичный описанному в последовательной задаче.
3. **Сбор результатов**:
Cбор результатов осуществляется при помощи функции ```reduce``` с оператором __maximum__. В результате выполнения операции `reduce` в переменной `result` будет храниться максимальное значение из всех фрагментов.

2024-10-28 13:46 UTC, Konstantin-Grudzin requested changes

2024-10-28 13:46 UTC, Konstantin-Grudzin commented on tasks/mpi/mironov_a_max_of_vector_elements/func_tests/main.cpp
> +    for (int i = 0; i < 100; ++i) global_vec[i] = i % 2 == 1 ? INT_MAX : 0;
It's hard to read for opeator in one line (this problem continues in other tests too)

2024-10-28 13:46 UTC, Konstantin-Grudzin commented on tasks/mpi/mironov_a_max_of_vector_elements/func_tests/main.cpp
> +    for (int i = 0; i < 100; ++i) global_vec[i] = i % 2 == 1 ? INT_MAX : 0;
It's not very safe to use ternary opeartor

2024-10-28 13:46 UTC, Konstantin-Grudzin commented on tasks/mpi/mironov_a_max_of_vector_elements/src/ops_mpi.cpp
> +  }
For my opinion, if operator in one line is hard to read

2024-10-29 10:24 UTC, Konstantin-Grudzin approved these changes

2024-10-30 05:31 UTC, Napkin-AI commented on tasks/mpi/mironov_a_max_of_vector_elements/func_tests/main.cpp
> +    for (int i = 0; i < 100; ++i) global_vec[i] = i % 2 == 1 ? INT_MAX : 0;
fixed

2024-10-30 05:31 UTC, Napkin-AI commented on tasks/mpi/mironov_a_max_of_vector_elements/func_tests/main.cpp
> +    for (int i = 0; i < 100; ++i) global_vec[i] = i % 2 == 1 ? INT_MAX : 0;
fixed

2024-10-30 05:31 UTC, Napkin-AI commented on tasks/mpi/mironov_a_max_of_vector_elements/src/ops_mpi.cpp
> +  }
fixed

2024-10-31 01:06 UTC, aobolensk requested changes

2024-10-31 06:24 UTC, Napkin-AI commented on tasks/mpi/mironov_a_max_of_vector_elements/func_tests/main.cpp
> +    for (int i = 0; i < count; ++i) {
Added 2 tests with randomized vectors: *Test_Max_6, Test_Max_7*

2024-10-31 13:29 UTC, Svoloch2940194 approved these changes

2024-10-31 16:22 UTC, aobolensk approved these changes

2024-10-31 16:25 UTC, allnes requested changes

2024-10-31 16:25 UTC, allnes commented on tasks/mpi/mironov_a_max_of_vector_elements/src/ops_mpi.cpp
> +bool mironov_a_max_of_vector_elements_mpi::MaxVectorMPI::pre_processing() {
please use all mpi functions in run()

2024-10-31 18:18 UTC, Napkin-AI commented on tasks/mpi/mironov_a_max_of_vector_elements/src/ops_mpi.cpp
> +bool mironov_a_max_of_vector_elements_mpi::MaxVectorMPI::pre_processing() {
fixed

2024-11-04 00:41 UTC, allnes approved these changes

2024-11-04 00:41 UTC, merged