Сомов Иван. Задача №3. Вариант 21. Поразрядная сортировка для вещественных чисел (тип double) с чётно-нечётным слиянием Бэтчера
learning-process/ppc-2024-autumn pull request #552
Opened 2024-12-14 23:36 UTC by qfrff

...

2024-12-16 13:00 UTC, ev1ven commented on tasks/mpi/somov_i_bitwise_sorting_batcher_merge/func_tests/main.cpp
> +  std::vector<double> out(in.size(), 0);
make test names more descriptive

2024-12-16 13:00 UTC, ev1ven commented on tasks/mpi/somov_i_bitwise_sorting_batcher_merge/perf_tests/main.cpp
> +  std::vector<double> out(in.size(), 0);
and also here

2024-12-16 13:00 UTC, ev1ven commented on tasks/seq/somov_i_bitwise_sorting_batcher_merge/func_tests/main.cpp
similar changes in seq

2024-12-16 13:48 UTC, ev1ven commented on tasks/mpi/somov_i_bitwise_sorting_batcher_merge/src/ops_mpi.cpp
> +  }
use reserve() for "positive" and "negative" vectors, as this will help optimise memory allocation and avoid unnecessary reallocations. replace push_back() with emplace_back()

2024-12-16 13:48 UTC, ev1ven commented on tasks/seq/somov_i_bitwise_sorting_batcher_merge/src/ops_seq.cpp
same

2024-12-16 22:55 UTC, MikasaAkc commented on tasks/mpi/somov_i_bitwise_sorting_batcher_merge/src/ops_mpi.cpp
> +  }
в данном случае можно заменить std::memcpy на reinterpret_cast, т.к. в функции не происходит копирование содержимого между независимыми областями памяти, а лишь преобразование данных из одного типа в другой

можно заменить все случаи в данной функции

2024-12-17 00:31 UTC, qfrff commented on tasks/mpi/somov_i_bitwise_sorting_batcher_merge/func_tests/main.cpp
> +  std::vector<double> out(in.size(), 0);
fixed

2024-12-17 00:31 UTC, qfrff commented on tasks/mpi/somov_i_bitwise_sorting_batcher_merge/perf_tests/main.cpp
> +  std::vector<double> out(in.size(), 0);
fixed

2024-12-17 00:32 UTC, qfrff commented on tasks/seq/somov_i_bitwise_sorting_batcher_merge/func_tests/main.cpp
fixed in seq

2024-12-17 00:32 UTC, qfrff commented on tasks/mpi/somov_i_bitwise_sorting_batcher_merge/src/ops_mpi.cpp
> +  }
fixed

2024-12-17 00:32 UTC, qfrff commented on tasks/seq/somov_i_bitwise_sorting_batcher_merge/src/ops_seq.cpp
fixed in seq

2024-12-17 00:34 UTC, qfrff commented on tasks/mpi/somov_i_bitwise_sorting_batcher_merge/src/ops_mpi.cpp
> +  }
fixed in mpi and the seq implementation is also fixed

2024-12-17 17:26 UTC, ev1ven approved these changes

2024-12-22 17:57 UTC, aobolensk requested changes

2024-12-22 17:57 UTC, aobolensk commented on tasks/mpi/somov_i_bitwise_sorting_batcher_merge/func_tests/main.cpp
> +std::vector<double> create_random_vector(int size, double mean = 3.0, double stddev = 300.0) {
Please, move to namespace pr make it static

2024-12-22 17:57 UTC, aobolensk commented on tasks/mpi/somov_i_bitwise_sorting_batcher_merge/func_tests/main.cpp
> +  std::normal_distribution<double> norm_dist(mean, stddev);
Please, add fixed (not random) tests as well

2024-12-22 23:48 UTC, allnes commented on tasks/mpi/somov_i_bitwise_sorting_batcher_merge/func_tests/main.cpp
> +TEST(somov_i_bitwise_sorting_batcher_merge_MPI, test_sorting_parallel_and_sequential_1000_elements) {
please check 2^n, prime, and 3^n values

2024-12-22 23:48 UTC, allnes commented on tasks/mpi/somov_i_bitwise_sorting_batcher_merge/func_tests/main.cpp
> +TEST(somov_i_bitwise_sorting_batcher_merge_MPI, test_sorting_parallel_and_sequential_20_elements) {
please add reverse check

2024-12-22 23:49 UTC, allnes commented on tasks/seq/somov_i_bitwise_sorting_batcher_merge/perf_tests/main.cpp
> +  std::vector<double> in = create_random_vector(3000000);
```suggestion
  std::vector<double> in = create_random_vector(3000001);
```

2024-12-22 23:49 UTC, allnes commented on tasks/seq/somov_i_bitwise_sorting_batcher_merge/perf_tests/main.cpp
> +  std::vector<double> in = create_random_vector(3000000);
```suggestion
  std::vector<double> in = create_random_vector(3000001);
```

2024-12-24 00:44 UTC, qfrff commented on tasks/mpi/somov_i_bitwise_sorting_batcher_merge/func_tests/main.cpp
> +TEST(somov_i_bitwise_sorting_batcher_merge_MPI, test_sorting_parallel_and_sequential_20_elements) {
added

2024-12-24 00:44 UTC, qfrff commented on tasks/seq/somov_i_bitwise_sorting_batcher_merge/perf_tests/main.cpp
> +  std::vector<double> in = create_random_vector(3000000);
fixed

2024-12-24 00:44 UTC, qfrff commented on tasks/seq/somov_i_bitwise_sorting_batcher_merge/perf_tests/main.cpp
> +  std::vector<double> in = create_random_vector(3000000);
fixed

2024-12-24 00:44 UTC, qfrff commented on tasks/mpi/somov_i_bitwise_sorting_batcher_merge/func_tests/main.cpp
> +TEST(somov_i_bitwise_sorting_batcher_merge_MPI, test_sorting_parallel_and_sequential_1000_elements) {
added

2024-12-24 00:44 UTC, qfrff commented on tasks/mpi/somov_i_bitwise_sorting_batcher_merge/func_tests/main.cpp
> +  std::normal_distribution<double> norm_dist(mean, stddev);
added

2024-12-24 00:44 UTC, qfrff commented on tasks/mpi/somov_i_bitwise_sorting_batcher_merge/func_tests/main.cpp
> +std::vector<double> create_random_vector(int size, double mean = 3.0, double stddev = 300.0) {
fixed

2024-12-24 17:25 UTC, allnes approved these changes

2024-12-24 20:03 UTC, aobolensk approved these changes

2024-12-24 20:03 UTC, merged