Task 3.4: CRS sparse matrix multiplication
learning-process/ppc-2024-autumn pull request #553
Opened 2024-12-15 02:07 UTC by kmichaelk

**Описание последовательной задачи.** На вход задачи подаются две матрицы, представленные в формате CSR. Правая матрица транспонируется для организации доступа по столбцам, затем на нее умножается левая матрица.

**Описание MPI задачи.** Реализуется схема, напоминающая обобщенную ленточную схему с разбиением только левой матрицы, правая матрица рассылается всем процессам в коммуникаторе. Для оптимизации рассылки правой матрицы используются расширенные возможности `boost::serialization` - введен дополнительный класс, представляющий фрагмент CSR-матрицы, организующий доступ к членам по невладеющим ссылкам (точнее говоря, с помощью `std::span`, являющегося невладеющей оберткой над указателем на непрерывный блок памяти и размером этого блока). В классе спрятана структура, содержащая владеющие вектора для хранения этих же данных - при создании чанка из существующих данных, невладеющие ссылки указывают на переданные при создании данные, а при десериализации инстанцируются вышеупомянутые входящие в класс векторы, невладеющие ссылки начинают указывать на них. После перемножения всех фрагментов с помощью `gather` происходит сбор в корневой процесс всех частичных результатов (здесь использование сериализации для представления частей матрицы избавляет от необходимости координации сбора размеров перед сборкой непосредственно данных), а затем их реассемблирование с коррекцией указателей на строки, выражающейся в их смещении с учетом порядка фрагментов матрицы.

Верификация ответов в обеих версиях задачи производится с помощью конверсии матрицы из CSR-представления в плотное и наивного алгоритма матричного умножения. \
Тестируются всевозможные комбинации плотностей и размеров матриц, включая ряд граничных случаев.

2024-12-15 23:59 UTC, belovtut requested changes

2024-12-15 23:59 UTC, belovtut commented on tasks/mpi/krylov_m_crs_mmul/include/smmul_mpi.hpp
> +  }
maybe you meant world.rank()?

2024-12-16 00:05 UTC, kmichaelk commented on tasks/mpi/krylov_m_crs_mmul/include/smmul_mpi.hpp
> +  }
Indeed, nice catch

2024-12-18 20:55 UTC, venn2713 approved these changes

2024-12-20 01:21 UTC, belovtut approved these changes

2024-12-22 17:32 UTC, aobolensk approved these changes

2024-12-22 23:36 UTC, allnes approved these changes

2024-12-22 23:36 UTC, merged