Одинцов Михаил. Задача 3 Вариант 13 Многошаговая система решения двухмерных задач глобальной оптимизации. Распараллеливание по характеристикам
learning-process/ppc-2024-autumn pull request #556
Opened 2024-12-15 10:17 UTC by odincovm

Последовательная версия: Мы берем заданную область с заданным шагом, затем проходим по каждой точке в этой области, проверяя на ограничения. Если точка проходит сравниваем ее с нашим минимумом/максимумом и потом корректируем область и шаг в зависимости от найденного минимума. Выходим из цикла при достижении заданной точности

Параллельная версия: В каждом потоке у нас свой набор ограничений. Также проходим по области.  В каждом процессе проверяем свой набор ограничений, затем их соединяем и проверяем точку в 0 потоке, если проходит сравниваем с минимумом в конце переопределяем область и уменьшаем шаг затем передаем эту информацию остальным потокам.Выходим из цикла при достижении заданной точности

2024-12-17 10:06 UTC, ermilovad requested changes
Add a test to verify that the program is working correctly if there are more threads than the number of restrictions

2024-12-18 12:03 UTC, sanya2905 requested changes
You have a refinement of the area only for the minimum. Add for maximum

2024-12-18 14:33 UTC, sanya2905 approved these changes

2024-12-18 14:50 UTC, ermilovad approved these changes

2024-12-22 17:31 UTC, aobolensk commented
Please, increase code coverage

2024-12-22 23:56 UTC, allnes commented on tasks/mpi/Odintsov_M_GlobalOptimizationSpecifications/func_tests/main.cpp
> +  srand(time(nullptr));
could you use random device

2024-12-22 23:57 UTC, allnes commented on tasks/mpi/Odintsov_M_GlobalOptimizationSpecifications/func_tests/main.cpp
> +  std::vector<double> area = {-10, 10, -10, 10};
additionaly please check small range - (0.0000001, 0.0000002)

2024-12-22 23:57 UTC, allnes commented on tasks/mpi/Odintsov_M_GlobalOptimizationSpecifications/perf_tests/main.cpp
> +  std::vector<double> area = {-10, 10, -10, 10};
please check different ranges

2024-12-22 23:58 UTC, allnes commented on tasks/mpi/Odintsov_M_GlobalOptimizationSpecifications/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
please remove it

2024-12-24 03:20 UTC, aobolensk approved these changes

2024-12-24 17:28 UTC, allnes approved these changes

2024-12-24 20:10 UTC, merged