Ворошилов Виталий. Задача 1. Вариант 22. Подсчёт числа буквенных символов в строке.
learning-process/ppc-2024-autumn pull request #56
Opened 2024-10-27 23:35 UTC by vitaliyvoroshilov

Алгоритм решения задачи подсчёта числа буквенных символов в строке заключается в полном переборе имеющейся строки и формировании результата в виде целого числа.

- В случае последовательного решения программа просто проходит по всей строке (точнее по vector<char>), сравнивает ASCII-код текущего символа с ASCII-кодами английских букв (строчных и прописных) и, если совпадение найдено, увеличивает переменную-счётчик. После прохождения всего вектора переменная-счётчик содержит искомый результат.

- В случае параллельного решения root-процесс распределяет имеющийся вектор символов равными частями себе и остальным процессам коммуникатора, после чего каждый процесс формирует свой локальный результат всё тем же методом полного перебора имеющегося фрагмента изначального вектора с сравнением ASCII-кодов. В конце root-процесс собирает глобальный результат как сумму локальных результатов всех процессов, полученный глобальный результат и есть искомое число.

2024-10-28 08:49 UTC, hasanyanovk commented on tasks/mpi/voroshilov_v_num_of_alphabetic_chars/src/ops_mpi.cpp
> +    if (((code >= 65) && (code <= 90)) || ((code >= 97) && (code <= 122))) {  // ASCII codes of english alphabet
Why don`y use `isalpha`?

2024-10-28 08:52 UTC, hasanyanovk commented on tasks/mpi/voroshilov_v_num_of_alphabetic_chars/src/ops_mpi.cpp
> +    world.recv(0, 0, local_input_.data(), part);
What if the number of elements is not divisible by the number of processes?

2024-10-28 23:08 UTC, vitaliyvoroshilov commented on tasks/mpi/voroshilov_v_num_of_alphabetic_chars/src/ops_mpi.cpp
> +    if (((code >= 65) && (code <= 90)) || ((code >= 97) && (code <= 122))) {  // ASCII codes of english alphabet
Added. Thanks for the helpful hint!

2024-10-28 23:11 UTC, vitaliyvoroshilov commented on tasks/mpi/voroshilov_v_num_of_alphabetic_chars/src/ops_mpi.cpp
> +    world.recv(0, 0, local_input_.data(), part);
Fixed. Now root-process also calculates the remainder if there is one

2024-10-29 08:17 UTC, hasanyanovk approved these changes

2024-10-30 09:53 UTC, kmichaelk approved these changes

2024-10-31 16:18 UTC, aobolensk requested changes

2024-10-31 16:18 UTC, aobolensk commented on modules/core/perf/include/perf.hpp
> -  constexpr const static double MIN_TIME = 0.05;
Please, do not modify common files

2024-10-31 16:18 UTC, aobolensk commented on modules/core/perf/src/perf.cpp
> +    std::cerr << " time < " << PerfResults::MAX_TIME << " secs." << std::endl;
Same, please do not modify this

2024-10-31 16:18 UTC, aobolensk commented on tasks/mpi/voroshilov_v_num_of_alphabetic_chars/func_tests/main.cpp
> +TEST(voroshilov_v_num_of_alphabetic_chars_mpi_func, test_without_alphabetic_chars_mpi) {
Please, add some random tests

2024-10-31 16:18 UTC, aobolensk commented on tasks/seq/voroshilov_v_num_of_alphabetic_chars/func_tests/main.cpp
> +    in[i] = str[i];
Use std::copy

2024-10-31 16:18 UTC, aobolensk commented on tasks/seq/voroshilov_v_num_of_alphabetic_chars/perf_tests/main.cpp
> +  std::string str_Z(10000, 'Z');
Use some more sophisticated combinations of characters for perf tests as well

2024-11-01 11:49 UTC, vitaliyvoroshilov commented on tasks/mpi/voroshilov_v_num_of_alphabetic_chars/func_tests/main.cpp
> +TEST(voroshilov_v_num_of_alphabetic_chars_mpi_func, test_without_alphabetic_chars_mpi) {
Fixed. Added a function that can generate random vector with required number of alphabetic chars and added tests using it

2024-11-01 11:49 UTC, vitaliyvoroshilov commented on tasks/seq/voroshilov_v_num_of_alphabetic_chars/func_tests/main.cpp
> +    in[i] = str[i];
Fixed.

2024-11-01 11:50 UTC, vitaliyvoroshilov commented on tasks/seq/voroshilov_v_num_of_alphabetic_chars/perf_tests/main.cpp
> +  std::string str_Z(10000, 'Z');
Fixed. Added tests with random generated vector

2024-11-01 11:50 UTC, vitaliyvoroshilov commented on tasks/mpi/voroshilov_v_num_of_alphabetic_chars/src/ops_mpi.cpp
> +bool voroshilov_v_num_of_alphabetic_chars_mpi::AlphabetCharsTaskParallel::pre_processing() {
Fixed

2024-11-02 16:50 UTC, vitaliyvoroshilov commented on modules/core/perf/include/perf.hpp
> -  constexpr const static double MIN_TIME = 0.05;
Fixed

2024-11-02 16:50 UTC, vitaliyvoroshilov commented on modules/core/perf/src/perf.cpp
> +    std::cerr << " time < " << PerfResults::MAX_TIME << " secs." << std::endl;
Fixed

2024-11-03 10:18 UTC, aobolensk approved these changes

2024-11-04 00:42 UTC, allnes approved these changes

2024-11-04 00:42 UTC, merged