Васенков Андрей. Задача 2. Вариант 21. Метод Гаусса-Жордана
learning-process/ppc-2024-autumn pull request #560
Opened 2024-12-15 16:57 UTC by VasenkovAA

*Последовательная версия:*
Для каждого столбца определяется строка с максимальным элементом в этом столбце. Если находится строка с большим элементом, строки меняются местами. Затем элементы в строках нормализуются так, чтобы на главной диагонали находились единицы. После этого из каждой строки ниже текущей вычитаются необходимые множители.
*Параллельное выполнение:*
Алгоритм распределяет задачи между процессами с использованием MPI. Процесс с рангом 0 находит строку с максимальным элементом в текущем столбце, что аналогично последовательному выполнению. Затем происходит разделение строк матрицы между процессами. Каждый процесс получает свою часть матрицы и выполняет преобразования для строк в своей локальной области. После этого результаты собираются для обновления исходной матрицы.

2024-12-15 17:12 UTC, ChastovSlava requested changes
Мне кажется у тебя маловато тестов. Также хотелось бы видеть тесны на 2x2 и 4x4 для mpi и seq версии твоей задачи.

2024-12-15 17:29 UTC, VasenkovAA commented
> Мне кажется у тебя маловато тестов. Также хотелось бы видеть тесны на 2x2 и 4x4 для mpi и seq версии твоей задачи.
Да, согласен. Я еще тест на пустую матрицу забыл. Поправлю

2024-12-15 17:38 UTC, VlJulia requested changes

2024-12-15 17:38 UTC, VlJulia commented on tasks/mpi/vasenkov_a_gauss_jordan_method_mpi/src/GausJordanMpi.cpp
> +bool vasenkov_a_gauss_jordan_method_mpi::GaussJordanParallel::run() {
Я думаю, что следует ее немножко поделить, просто она чуть великовата

2024-12-15 17:38 UTC, ChernovaNatalya requested changes
You don't have tests with random data

2024-12-15 17:57 UTC, VasenkovAA commented on tasks/mpi/vasenkov_a_gauss_jordan_method_mpi/src/GausJordanMpi.cpp
> +bool vasenkov_a_gauss_jordan_method_mpi::GaussJordanParallel::run() {
> Я думаю, что следует ее немножко поделить, просто она чуть великовата

Согласен, функция выглядит очень большой и совершенно нечитабельной. Поправлю

2024-12-15 18:17 UTC, VasenkovAA commented
> You don't have tests with random data

Я добавил еще тестов с рандомными данными в функциональные тесты

2024-12-15 18:18 UTC, VasenkovAA commented
> > Мне кажется у тебя маловато тестов. Также хотелось бы видеть тесны на 2x2 и 4x4 для mpi и seq версии твоей задачи.
> 
> Да, согласен. Я еще тест на пустую матрицу забыл. Поправлю

Поправил, теперь есть тесты от 2x2 вплоть до 4x4 . Есть рандомные тесты и проверка валидации

2024-12-15 18:28 UTC, ChernovaNatalya commented
> > You don't have tests with random data
> 
> Я добавил еще тестов с рандомными данными в функциональные тесты

Все твои новые тесты были добавлены только в mpi версию. Поправь seq тоже

2024-12-15 21:35 UTC, VasenkovAA commented
> > > You don't have tests with random data
> > 
> > 
> > Я добавил еще тестов с рандомными данными в функциональные тесты
> 
> Все твои новые тесты были добавлены только в mpi версию. Поправь seq тоже

Я добавил тесты в seq версию

2024-12-15 21:35 UTC, VasenkovAA commented on tasks/mpi/vasenkov_a_gauss_jordan_method_mpi/src/GausJordanMpi.cpp
> +bool vasenkov_a_gauss_jordan_method_mpi::GaussJordanParallel::run() {
Поправил

2024-12-16 21:57 UTC, ChernovaNatalya approved these changes

2024-12-17 11:05 UTC, ChastovSlava approved these changes

2024-12-22 09:49 UTC, aobolensk commented
Perf tests coverage is too low

2024-12-23 00:09 UTC, allnes commented on tasks/mpi/vasenkov_a_gauss_jordan_method_mpi/func_tests/main.cpp
> +  double upperLimit = 100.0;
please parametrize this constants in test

2024-12-23 00:10 UTC, allnes commented on tasks/mpi/vasenkov_a_gauss_jordan_method_mpi/src/GausJordanMpi.cpp
> +#define EPSILON 1e-9
for direct methos its big error

2024-12-23 00:11 UTC, allnes commented on tasks/mpi/vasenkov_a_gauss_jordan_method_mpi/src/GausJordanMpi.cpp
> +    throw std::runtime_error("Деление на ноль во время нормализации.");
where try / catch preocessing? or remove it please

2024-12-24 17:53 UTC, aobolensk commented
Please, increase code coverage

2024-12-29 19:40 UTC, closed without merging