Ермилова Дарья. Задача 3. Вариант 16. Сортировка Шелла с простым слиянием
learning-process/ppc-2024-autumn pull request #567
Opened 2024-12-15 19:17 UTC by ermilovad

Сортировка Шелла.
Внешний цикл for (size_t gap = n / 2; gap > 0; gap /= 2):
Внешний цикл управляет значением интервала. Он начинается с половины длины массива и уменьшается в два раза на каждом шаге, пока не достигнет 1. Для каждого интервала, элементы массива, расположенные через этот интервал, будут сравниваться и переставляться.
Внутренний цикл for (size_t i = gap; i < n; i++):
Внутренний цикл выполняет сортировку вставками для элементов, расположенных через интервал. То есть, для каждого элемента с индексом i, начиная с позиции gap, выполняется сортировка с соседними элементами, находящимися на расстоянии gap друг от друга.
Когда интервал достигает 1, выполняется обычная сортировка вставками для всех элементов.

Последовательная версия:
Выполняется сортировка Шелла на массиве данных.

Параллельная версия:
Данные разделяются на примерно одинаковое количество элементов и отправляются процессам. Каждый процесс сортирует свою часть данных с помощью алгоритма Шелла. После сбора данных со всех процессов, на корневом процессе происходит слияние отсортированных частей с использованием структуры данных priority_queue для объединения отсортированных элементов.

2024-12-21 14:32 UTC, MikeMuradov requested changes
Add a test for a vector of 1 element

2024-12-21 14:42 UTC, sanya2905 requested changes
Remove unused includes and namespace

2024-12-21 16:31 UTC, sanya2905 approved these changes

2024-12-21 16:32 UTC, MikeMuradov approved these changes

2024-12-22 18:04 UTC, aobolensk approved these changes

2024-12-23 00:13 UTC, allnes commented on tasks/mpi/ermilova_d_Shell_sort_simple_merge/func_tests/main.cpp
> +TEST(ermilova_d_Shell_sort_simple_merge_mpi, Test_vec_5000) {
please add revers sort test and please add tests with prime values, 2^n, 3^n

2024-12-25 18:53 UTC, merged