Козлова Екатерина. Задача 3. Вариант 21. Поразрядная сортировка для вещественных чисел (тип double) с четно-нечетным слиянием Бэтчера.
learning-process/ppc-2024-autumn pull request #577
Opened 2024-12-15 22:58 UTC by KatyaKozlova

### Реализация последовательной версии.
В классе реализована поразрядная сортировка для чисел с плавающей точкой типа double. Каждый элемент массива преобразуется в его 64-битное целочисленное представление, что позволяет работать с числами на уровне их битов. Для корректной сортировки отрицательных чисел старший бит (бит знака) инвертируется, чтобы все отрицательные числа были обработаны как положительные, не нарушая общей логики сортировки. Алгоритм выполняет сортировку, начиная с младшего бита и постепенно переходя к более старшим. На каждом шаге происходит разделение данных на две группы в зависимости от значения текущего бита (0 или 1). После завершения сортировки по всем битам, 64-битные целые числа преобразуются обратно в значения типа double, и отрицательные числа восстанавливают своё исходное состояние.
### Реализация параллельной версии.
С помощью функции scatterv исходный массив разбивается на части, после этого они отправляются на различные процессы. Каждый процесс сортирует свою часть данных, используя алгоритм поразрядной сортировки из последовательной версии. Затем происходит обмен данными между процессами по принципу четно нечетного слияния Бэтчера. Суть метода заключается в чередующемся слиянии данных между процессами на разных этапах.
На каждом шаге один процесс будет обмениваться данными с другим, причем очередность этого обмена зависит от фазы слияния (чётная или нечётная). После каждого обмена данные сортируются локально на каждом процессе. Этот процесс повторяется несколько раз (в зависимости от количества процессов), постепенно улучшая сортировку всего набора данных. Когда все этапы сортировки завершены, главный процесс собирает все части массива в один полностью отсортированный массив с помощью функции gatherv.

2024-12-16 15:37 UTC, ElizavetaFrolova commented on tasks/mpi/kozlova_e_radix_batcher_sort/src/ops_mpi.cpp
> +#include <random>
Please delete what you are not using

2024-12-17 15:53 UTC, KatyaKozlova commented on tasks/mpi/kozlova_e_radix_batcher_sort/src/ops_mpi.cpp
> +#include <random>
deleted

2024-12-17 18:07 UTC, ElizavetaFrolova approved these changes

2024-12-17 20:26 UTC, Gn4ik requested changes

2024-12-17 22:18 UTC, KatyaKozlova commented on tasks/mpi/kozlova_e_radix_batcher_sort/func_tests/main.cpp
> +TEST(kozlova_e_radix_batcher_sort_mpi, test_same_elements) {
added

2024-12-17 23:54 UTC, Gn4ik approved these changes

2024-12-19 15:19 UTC, aobolensk approved these changes

2024-12-23 00:21 UTC, allnes commented on tasks/mpi/kozlova_e_radix_batcher_sort/func_tests/main.cpp
> +  std::uniform_real_distribution<double> dist(-100.0, 100.0);
please parametrize this constants in tests

2024-12-23 00:22 UTC, allnes commented on tasks/mpi/kozlova_e_radix_batcher_sort/func_tests/main.cpp
> +TEST(kozlova_e_radix_batcher_sort_mpi, test_identical_elements_with_diff_signs) {
please add revers sort test

2024-12-23 00:22 UTC, allnes commented on tasks/mpi/kozlova_e_radix_batcher_sort/func_tests/main.cpp
> +TEST(kozlova_e_radix_batcher_sort_mpi, test_large_mas) {
please add test with sizes - 2^n, 3^n, prime values

2024-12-24 17:45 UTC, allnes approved these changes

2024-12-24 17:46 UTC, merged