Гнитиенко Кирилл. Задача 1. Вариант 11. Сумма значений по строкам матрицы
learning-process/ppc-2024-autumn pull request #58
Opened 2024-10-28 15:16 UTC by Gn4ik

### Описание последовательной задачи

- **pre_processing**: Подготавливаются данные, извлекая размеры матрицы и копируя входные данные в вектор input_.
- **validation**: Проверяется корректность входных и выходных данных, включая размеры и количество элементов.
- **run**: Основная логика суммирования по строкам: Матрица задана в виде одномерного вектора. Внешний цикл проходит по каждой строке матрицы (от 0 до rows). Внутренний цикл суммирует все элементы в текущей строке (от 0 до cols). Сумма элементов строки сохраняется в результирующем векторе res.
- **post_processing**: Запись результатов в выходные данные.

### Описание MPI задачи

- **pre_processing**: Инициализируются размеры матрицы и распределяет данные между процессами. Главный процесс загружает данные и передаёт их другим процессам через broadcast.
- **validation**: Проверяется корректность входных и выходных данных аналогично последовательной задаче, но только на главном процессе.
- **run**: Выполняется суммирование по строкам в каждом процессе. Каждый процесс вычисляет количество строк, которые ему необходимо обработать, вызывает метод mainFunc, передавая ему диапазон строк на обработку. Внутри mainFunc аналогично последовательному варианту происходит суммирование по строкам, но теперь каждый процесс обрабатывает только свою часть матрицы. Результаты собираются на главном процессе с помощью gatherv.
- **post_processing**: Главный процесс записывает собранные результаты в выходные данные.

2024-10-31 16:21 UTC, aobolensk requested changes

2024-10-31 16:21 UTC, aobolensk commented on tasks/mpi/gnitienko_k_sum_values_by_rows_matrix/func_tests/main.cpp
> +TEST(gnitienko_k_sum_values_by_rows_MPI, test_empty_matrix) {
Please, add some random tests to verify functionality better

2024-10-31 16:21 UTC, aobolensk commented on tasks/mpi/gnitienko_k_sum_values_by_rows_matrix/func_tests/main.cpp
> +  }
Add test for empty matrix and small matrices

2024-10-31 16:30 UTC, allnes commented on tasks/mpi/gnitienko_k_sum_values_by_rows_matrix/src/ops_mpi.cpp
> +bool gnitienko_k_sum_row_mpi::SumByRowMPIParallel::pre_processing() {
please use all mpi functions in run()

2024-10-31 16:31 UTC, allnes commented on tasks/seq/gnitienko_k_sum_values_by_rows_matrix/src/ops_seq.cpp
> +  std::this_thread::sleep_for(20ms);
please remove it

2024-10-31 16:32 UTC, allnes commented on tasks/seq/gnitienko_k_sum_values_by_rows_matrix/src/ops_seq.cpp
> +using namespace std::chrono_literals;
why do you use it?

2024-10-31 23:20 UTC, Gn4ik commented on tasks/mpi/gnitienko_k_sum_values_by_rows_matrix/func_tests/main.cpp
> +TEST(gnitienko_k_sum_values_by_rows_MPI, test_empty_matrix) {
added

2024-10-31 23:20 UTC, Gn4ik commented on tasks/mpi/gnitienko_k_sum_values_by_rows_matrix/func_tests/main.cpp
> +  }
added

2024-10-31 23:21 UTC, Gn4ik commented on tasks/seq/gnitienko_k_sum_values_by_rows_matrix/src/ops_seq.cpp
> +  std::this_thread::sleep_for(20ms);
remove

2024-10-31 23:23 UTC, Gn4ik commented on tasks/seq/gnitienko_k_sum_values_by_rows_matrix/src/ops_seq.cpp
> +using namespace std::chrono_literals;
cstring for Ubuntu build, other removed

2024-11-01 14:42 UTC, Gn4ik commented on tasks/mpi/gnitienko_k_sum_values_by_rows_matrix/src/ops_mpi.cpp
> +bool gnitienko_k_sum_row_mpi::SumByRowMPIParallel::pre_processing() {
fixed

2024-11-02 01:23 UTC, allnes approved these changes

2024-11-02 14:14 UTC, KoshkinMatvey approved these changes
good work

2024-11-02 16:39 UTC, polikanovv approved these changes

2024-11-03 01:48 UTC, merged