Сарафанов Максим. Задача 3. Вариант 15. Быстрая сортировка с четно-нечетным слиянием Бэтчера.
learning-process/ppc-2024-autumn pull request #580
Opened 2024-12-15 23:44 UTC by Pybigboy

Алгоритм реализует следующую логику:

1. **Создание битонической последовательности**:  
   На нулевом процессе создается битоническая последовательность, где первая половина сортируется по возрастанию, а вторая — по убыванию.

2. **Деление на подгруппы**:  
   Процессы делятся на подгруппу с размером, равным ближайшей степени двойки (максимально возможной).

3. **Распределение данных (scatter)**:  
   Данные распределяются между процессами в подгруппе для локальной сортировки.

4. **Слияние по Батчеру (Batcher Merge)**:  
   В подгруппе выполняются итеративные обмены данных между процессами для постепенного слияния подмассивов:
   - Процессы обмениваются частями данных и сортируют элементы после обмена, чтобы поддерживать корректное слияние.
   - Используется определение цвета (iter_color) для контроля участия процессов в обмене.

5. **Локальная сортировка и сбор данных (gather)**:  
   Каждый процесс выполняет быструю сортировку на своей части данных, после чего отсортированные блоки собираются на нулевом процессе.

2024-12-17 12:26 UTC, korablev-vm commented on tasks/mpi/sarafanov_m_quick_sort_batcher_merge/src/ops_mpi.cpp
> +}
Сюда можно еще про output добавить проверку (как в примере)

2024-12-17 18:22 UTC, venn2713 requested changes
Да как будто бы и все... Если будет мало для моего ревью я конечно могу докопаться до мелочей попробовать, а так все хорошо, код чистый, объявления хороший. Вот как в том ревью согласен, можно проверять достаточного ли размера буфер в который будете писать, это можно, да. Жду фиксы и с меня апрув

2024-12-17 18:22 UTC, venn2713 commented on tasks/mpi/sarafanov_m_quick_sort_batcher_merge/func_tests/main.cpp
> +#include "boost/mpi/collectives/broadcast.hpp"
Не нужен тут инклюд

2024-12-17 19:35 UTC, Pybigboy commented on tasks/mpi/sarafanov_m_quick_sort_batcher_merge/src/ops_mpi.cpp
> +}
I'm sorry, but everything is already in the namespace, look at the beginning of the file 😁

2024-12-17 19:36 UTC, Pybigboy commented on tasks/mpi/sarafanov_m_quick_sort_batcher_merge/src/ops_mpi.cpp
> +}
I append it

2024-12-17 19:46 UTC, Pybigboy commented on tasks/mpi/sarafanov_m_quick_sort_batcher_merge/func_tests/main.cpp
> +#include "boost/mpi/collectives/broadcast.hpp"
I deleted it 😁

2024-12-17 22:50 UTC, venn2713 approved these changes

2024-12-19 08:53 UTC, korablev-vm approved these changes

2024-12-21 12:54 UTC, aobolensk approved these changes

2024-12-23 00:29 UTC, allnes commented on tasks/mpi/sarafanov_m_quick_sort_batcher_merge/include/ops_mpi.hpp
> +  const int threshold = 10;
why this threshold = 10? and what is it for?

2024-12-23 08:58 UTC, Pybigboy commented on tasks/mpi/sarafanov_m_quick_sort_batcher_merge/include/ops_mpi.hpp
> +  const int threshold = 10;
Здравствуйте! Я хотел сделать алгоритм быстрой сортировки более оптимальным, поэтому изучил современные подходы, которые используются в реализации quick sort. На основе этого написал, по моему мнению, максимально оптимизированную версию. Она всё ещё остаётся алгоритмом быстрой сортировки по своему типу действия, но её принцип работы теперь следующий:

1. Если размер массива небольшой (меньше порога `threshold`, равного 10), используется **сортировка вставками**. Это более эффективно на небольших данных, поскольку алгоритм вставок имеет низкие накладные расходы и хорошо работает с кэш-памятью.
2. Если массив крупнее, применяется **quick sort** с выбором опорного элемента (pivot), который делит массив на две части. После этого обе части сортируются рекурсивно.

Таким образом, алгоритм сочетает преимущества обеих стратегий, чтобы минимизировать время выполнения и повысить общую эффективность.

2024-12-24 17:47 UTC, allnes approved these changes

2024-12-24 17:47 UTC, merged