Махов Михаил. Задача 2. Вариант 11. Топология сетей - кольцо.
learning-process/ppc-2024-autumn pull request #581
Opened 2024-12-15 23:48 UTC by SingularityNN

Каждый процесс, начиная с корневого, отправляет следующему процессу входные данные (вектор целых чисел) и данные о последовательности передачи данных между процессами (так же вектор целых чисел).
Каждый процесс взаимодействует только с двумя соседними, образуя кольцо.
Передача данных заканчивается, когда корневой процесс принял входные данные от последнего процесса

2024-12-21 15:40 UTC, andrewmeow requested changes

2024-12-21 15:40 UTC, andrewmeow commented on tasks/mpi/makhov_m_ring_topology/func_tests/main.cpp
> +    input_vector[i] = (int32_t)(min + gen() % (max - min + 1));
Лучше использовать stasic_cast<>()

2024-12-21 15:40 UTC, andrewmeow commented on tasks/mpi/makhov_m_ring_topology/func_tests/main.cpp
> +    input_vector[i] = (int32_t)(min + gen() % (max - min + 1));
и далее во всех преобразованиях типов тоже поправить

2024-12-21 15:49 UTC, MaxikGuy requested changes

2024-12-21 15:49 UTC, MaxikGuy commented on tasks/mpi/makhov_m_ring_topology/func_tests/main.cpp
> +  }
Hi! 
You should put the random matrix generation into a separate function and use it in similar places.

2024-12-22 19:23 UTC, andrewmeow approved these changes

2024-12-22 21:49 UTC, MaxikGuy approved these changes

2024-12-23 00:36 UTC, allnes commented on tasks/mpi/makhov_m_ring_topology/func_tests/main.cpp
> +  size_t size = 1000;
please add 2^n, 3^n and prime values

2024-12-23 00:36 UTC, allnes commented on tasks/mpi/makhov_m_ring_topology/src/ops_mpi.cpp
> +      world.send(receiver, 1, sequence);
please use non-blocked mpi functions everywhere in this task

2024-12-24 20:04 UTC, aobolensk commented
Please, increase code coverage as well

2024-12-29 19:40 UTC, closed without merging