Fix Revert. Бесхмельнова Ксения. Задача 2. Вариант 3. Обедающие философы.
learning-process/ppc-2024-autumn pull request #594
Opened 2024-12-16 12:30 UTC by KseniyaBeskhmelnova

Программа реализует задачу об обедающих философах с использованием MPI для параллельного взаимодействия между процессами. Каждый философ представляет отдельный процесс, который поочередно переходит через состояния THINKING, HUNGRY и EATING. Для перехода в состояние EATING философы запрашивают вилки(ресурсы), отправляя сообщения своим соседям, и освобождают их по завершении. Программа реализует механизм проверки взаимоблокировки (deadlock) и разрешает её, возвращая философа в состояние THINKING. Завершение программы происходит, когда все философы находятся в состоянии THINKING. Такая реализация обеспечивает синхронизацию процессов и управление доступом к разделяемым ресурсам.

Что исправлено:
добавлено internal_order_tests() в pre_processing, validation, run и post_processing

2024-12-17 15:15 UTC, Alexey2013 approved these changes

2024-12-19 19:29 UTC, aobolensk commented
Please, increase code coverage

2024-12-19 21:58 UTC, KseniyaBeskhmelnova commented
@aobolensk, done

2024-12-22 21:06 UTC, kmichaelk requested changes
You have a problem in logic somewhere, the execution is being terminated immediately, also the `num_philosophers` you're relying to does not have effect

![image](https://github.com/user-attachments/assets/f636881b-dd54-4627-aa08-2b856d6a583a)

2024-12-22 21:06 UTC, kmichaelk commented on tasks/mpi/beskhmelnova_k_dinning_philosophers/src/dinning_philosophers.cpp
> +  std::this_thread::sleep_for(std::chrono::milliseconds(10));
It seems like these values ​​should be random

2024-12-22 21:06 UTC, kmichaelk commented on tasks/mpi/beskhmelnova_k_dinning_philosophers/src/dinning_philosophers.cpp
> +  std::this_thread::sleep_for(std::chrono::milliseconds(60));
These and the rest too

2024-12-22 21:06 UTC, kmichaelk commented on tasks/mpi/beskhmelnova_k_dinning_philosophers/src/dinning_philosophers.cpp
> +  int num_philosophers = taskData->inputs_count[0];
Do you use `num_philosophers` anywhere actually?

2024-12-22 21:14 UTC, kmichaelk commented
Same for perf tests, they don't work and terminate immediately

2024-12-22 21:19 UTC, kmichaelk commented on tasks/mpi/beskhmelnova_k_dinning_philosophers/src/dinning_philosophers.cpp
> +  std::this_thread::sleep_for(std::chrono::milliseconds(60));
?

2024-12-23 00:16 UTC, allnes approved these changes

2024-12-23 00:17 UTC, allnes commented
we will merge after @kmichaelk approve

2024-12-23 18:31 UTC, KseniyaBeskhmelnova commented
@kmichaelk, you were right, the processes were terminated before run. i rearranged the completion check and added random in functions. look, please, i hope it is good now.

2024-12-23 19:01 UTC, kmichaelk commented
Yes, does not terminate immediately now, but now it behaves incorrectly as all philosophers eat at the same time (which is not possible because everyone needs two forks), this can be confirmed by adding prints and sleep:

```cpp
template <typename DataType>
bool beskhmelnova_k_dining_philosophers::DiningPhilosophersMPI<DataType>::run() {
  internal_order_test();
  while (true) {
    think();
    request_forks();
    printf("[%d] Eat\n", world.rank());
    eat();
    printf(" [%d] Done\n", world.rank());
    std::this_thread::sleep_for(std::chrono::seconds(10));
    release_forks();
    if (check_deadlock()) return false;
    if (check_for_termination()) break;
  }
  printf("[%d] Terminated\n", world.rank());
  return true;
}
```

2024-12-23 19:11 UTC, KseniyaBeskhmelnova commented
@kmichaelk, that is what you mean?
![Снимок экрана 2024-12-23 221017](https://github.com/user-attachments/assets/d1255350-117f-4114-a851-c7a4ec11aa13)

2024-12-23 19:21 UTC, kmichaelk commented
The current problem with this function is that all processes enter it and exit it all at once (and so proceed with eating, which is not possible by the definition of the dining philosophers task). And this function should block those processes-philosophers who do not have a fork available yet.

In fact, the messages that go in this function should match the messages coming from `release_forks`. It doesn't seem to work as is, maybe try different tags for requesting and releasing forks, you can check if it works by adding the prints and a sleep like in the comment above.

2024-12-23 19:27 UTC, kmichaelk commented
The problem seems to be with the tags indeed

2024-12-23 19:27 UTC, kmichaelk commented on tasks/mpi/beskhmelnova_k_dinning_philosophers/src/dinning_philosophers.cpp
> +  num_philosophers = taskData->inputs_count[0];
You still don't use it anywhere

2024-12-23 19:33 UTC, KseniyaBeskhmelnova commented
please, look again. i added prints like toy and everything is good: 
[7] Eat
 [7] Done
[5] Eat
 [5] Done
[2] Eat
 [2] Done
[4] Eat
 [4] Done
[1] Eat
 [1] Done
[6] Eat
 [6] Done
[3] Eat
 [3] Done
[0] Eat
 [0] Done

2024-12-23 20:28 UTC, kmichaelk commented
It seems nothing has changed, at least with the current revision in PR

2024-12-23 21:43 UTC, KseniyaBeskhmelnova commented
@kmichaelk, i mean there is something wrong with your prints. everything works correctly on my computer, see the prints above.
You were right about the number of philosophers: in all tests number of philosophers was the same as number of processes. now number of them = number of philosophers in tests.

2024-12-23 21:50 UTC, kmichaelk commented
Perhaps you forgot to push the latest commit, currently the problem still persists because you are using the same tag for all messages, everything should be fixed as soon as the request for forks and their return are identified differently, there is very little left to fix.

2024-12-23 22:09 UTC, KseniyaBeskhmelnova commented
@kmichaelk, look, please. did i understand you correct?
i hope, it is all right now. it is very hard

2024-12-23 22:39 UTC, kmichaelk commented
Interesting task. In fact, you have one synchronization point - it is a pair of `request_forks` and `release_forks` - `request_forks` should block the process until a message from `release_forks` arrives there. Because the memory is not shared, there is a chicken and egg problem - at the very beginning all processes should call `release_forks`, but then each process will receive a message and they will not block in `request_forks`, **which will lead to all philosophers eating at the same time**, which is wrong. 

That is, the problem comes down to the fact that in the current implementation, a fork is not a shared resource, so it can be "in the hands" of two philosopher processes at once, which is impossible by definition.

I just thought, IMO, this can only be properly resolved by introducing a separate coordinator ("table") process, or by dedicating a separate process per each fork.

ALTHOUGH there is another possible partial solution, it seems to me (de facto inlined the `release_forks` function into `run`, right forks are dropped on the beginning only to the part of processes):
![image](https://github.com/user-attachments/assets/caefc8ff-f5e5-450e-bd2f-122b41655905)
![image](https://github.com/user-attachments/assets/f0c35b8e-a3dc-4ff1-8de8-9fca5304b025)

And it gives correct output now:

```
[1] Eat()
[7] Eat()
[5] Eat()
[3] Eat()
 [1] Done
[2] Eat()
 [7] Done
[0] Eat()
 [5] Done
[6] Eat()
 [3] Done
[4] Eat()
 [0] Done
 [2] Done
 [4] Done
 [6] Done
[1] Eat()
[3] Eat()
[5] Eat()
[7] Eat()
 [1] Done
[2] Eat()
 [7] Done
 [3] Done
 [5] Done
[6] Eat()
[0] Eat()
[4] Eat()
 [2] Done
 [0] Done
 [6] Done
 [4] Done
[5] Eat()
[3] Eat()
[1] Eat()
[7] Eat()
 [5] Done
[6] Eat()
 [3] Done
[4] Eat()
 [1] Done
[2] Eat()
[0] Eat()
 [7] Done
 [6] Done
 [4] Done
 [2] Done
 [0] Done
[1] Eat()
[7] Eat()
[5] Eat()
[3] Eat()
 [1] Done
[2] Eat()
 [7] Done
 [5] Done
[6] Eat()
[0] Eat()
 [3] Done
[4] Eat()
 [0] Done
 [2] Done
 [6] Done
 [4] Done
[3] Eat()
[1] Eat()
[5] Eat()
[7] Eat()
```

And for infinity as there's no exit condition as for now, but works properly judging by the ranks (two neighboring philosophers do not eat at the same time).

If the current revision is considered acceptable, I would approve, but otherwise I would abstain from voting in either direction.

2024-12-23 23:17 UTC, kmichaelk approved these changes
The workaround I suggested above is also flawed, because it will never lead to combinations like this (green philosophers are eating). In fact, the same sets of philosophers will switch each time, so a coordinator process is needed for correct solution.

![image](https://github.com/user-attachments/assets/728fefc9-7479-4d20-90b8-b990d835eba1)

Not a fan of unwittingly force someone to redo a hard task at the end but JFYI it doesn't work correctly if you're interested

2024-12-24 04:40 UTC, KseniyaBeskhmelnova commented
@aobolensk, @allnes, you can merge now.

it was very hard and took a lot of time, but i did :)

2024-12-24 04:42 UTC, KseniyaBeskhmelnova commented
if I fail the exam today, it will be partly on Mikhail's conscience )))

2024-12-24 18:16 UTC, merged