FIX. Дрождинов Дмитрий. Задача 2. Вариант 20. Метод Гаусса – ленточная вертикальная схема.
learning-process/ppc-2024-autumn pull request #595
Opened 2024-12-16 13:42 UTC by dima-dimka04

**Исправлено:** изменены данные в mpi_perf_tests, чтобы время выполнения тестов было корректным и помещалось в заданные значения. На будущее учтены расхождения во времени исполнения тестов на домашнем компьютере и машинах репозитория.

2024-12-16 15:28 UTC, KseniyaBeskhmelnova commented
![Снимок экрана 2024-12-16 182812](https://github.com/user-attachments/assets/5dd8081c-c1fc-42f4-9261-9251601d2079)
Read the instruction and rename tests, please

2024-12-16 21:50 UTC, Alexey2013 commented on tasks/mpi/drozhdinov_d_gauss_vertical_scheme/perf_tests/main.cpp
> +  int rows = 500;
Make the same values ​​as in seq

2024-12-16 22:35 UTC, dima-dimka04 commented
@KseniyaBeskhmelnova tests names was fixed

2024-12-17 05:42 UTC, KseniyaBeskhmelnova approved these changes

2024-12-17 07:58 UTC, dima-dimka04 commented on tasks/mpi/drozhdinov_d_gauss_vertical_scheme/perf_tests/main.cpp
> +  int rows = 500;
now in seq perf tests the values are the same as in mpi, so time must be correct

2024-12-17 09:49 UTC, Alexey2013 approved these changes

2024-12-19 19:29 UTC, aobolensk requested changes

2024-12-19 19:29 UTC, aobolensk commented on tasks/mpi/drozhdinov_d_gauss_vertical_scheme/include/ops_mpi.hpp
> +double myrnd(double value);
Please, move under namespace

2024-12-19 19:54 UTC, aobolensk approved these changes

2024-12-23 00:17 UTC, allnes approved these changes

2024-12-23 00:17 UTC, merged