Fix Revert. Мухина Маргарита. Задача 2. Вариант 15. Ленточная горизонтальная схема
learning-process/ppc-2024-autumn pull request #606
Opened 2024-12-16 18:53 UTC by MargaritaMuhina

Последовательный алгоритм
Для каждой строки матрицы вычисляется результат, перемножая элементы этой строки на элементы вектора и суммируя их.

Параллельный алгоритм
pre_processing():
Процесс с рангом 0 отвечает за загрузку данных: матрицы и вектора, а также определяет размеры матрицы (rows_, cols_).
run():
Главный процесс делит строки матрицы между рабочими процессами, каждый рабочий процесс получает свою часть матрицы. Распределение происходит построчно, с попыткой равномерного распределения строк между процессами. Лишние строки назначаются первым процессам.
Каждый процесс выполняет локальное умножение матрицы на вектор на своей части матрицы, используя распространенный вектор. Результат сохраняется в local_result. После локальных вычислений рабочие процессы отправляют свои результаты главному процессу с помощью world_.send. Главный процесс принимает эти результаты с помощью world_.recv, собирает полный результирующий вектор (result_) и сохраняет его.
post_processing()
Процесс с рангом 0 записывает окончательный результат в выходные данные.

Revert: исправлен тест Test_MatrixVectorMultiplication_RepeatingValues

2024-12-17 20:18 UTC, ermolaevv commented on tasks/mpi/muhina_m_horizontal_cheme/perf_tests/main.cpp
Seems like this sizes is too small. Maybe you should increase them. And please use same sizes in seq and MPI perf tests

2024-12-18 07:17 UTC, WladislawFilatew commented on tasks/mpi/muhina_m_horizontal_cheme/func_tests/main.cpp
> +    vec = {1, 1, 1};
matrix = {} можно удалить, она изначально пустая

2024-12-18 07:20 UTC, WladislawFilatew commented on tasks/mpi/muhina_m_horizontal_cheme/func_tests/main.cpp
> +  ASSERT_TRUE(matrixVecMultParalle->post_processing());
Оставить можно только у validation, т.к. в других методах в твоей реализации всегда возвращается true

2024-12-18 07:21 UTC, WladislawFilatew commented on tasks/mpi/muhina_m_horizontal_cheme/include/ops_mpi.hpp
> +#include <vector>
Unnecessary include, also in other files

2024-12-18 13:05 UTC, MargaritaMuhina commented on tasks/mpi/muhina_m_horizontal_cheme/include/ops_mpi.hpp
> +#include <vector>
fixed

2024-12-18 13:05 UTC, MargaritaMuhina commented on tasks/mpi/muhina_m_horizontal_cheme/func_tests/main.cpp
> +  ASSERT_TRUE(matrixVecMultParalle->post_processing());
fixed

2024-12-18 13:05 UTC, MargaritaMuhina commented on tasks/mpi/muhina_m_horizontal_cheme/func_tests/main.cpp
> +    vec = {1, 1, 1};
fixed

2024-12-18 13:05 UTC, MargaritaMuhina commented on tasks/mpi/muhina_m_horizontal_cheme/perf_tests/main.cpp
fixed

2024-12-18 19:51 UTC, WladislawFilatew approved these changes

2024-12-21 12:56 UTC, aobolensk requested changes

2024-12-21 12:56 UTC, aobolensk commented on tasks/mpi/muhina_m_horizontal_cheme/func_tests/main.cpp
> +
Please, add random tests

2024-12-21 18:56 UTC, MargaritaMuhina commented on tasks/mpi/muhina_m_horizontal_cheme/func_tests/main.cpp
> +
added

2024-12-23 00:18 UTC, allnes approved these changes

2024-12-24 20:04 UTC, aobolensk approved these changes

2024-12-24 20:04 UTC, merged