Межуев Максим Задача 3 Вариант 29 "Выделение ребер на изображении с использованием оператора Собеля"
learning-process/ppc-2024-autumn pull request #607
Opened 2024-12-16 19:15 UTC by Domovenokkk

В рамках данной задачи требуется разработать и протестировать алгоритм выделения границ методом Собеля с использованием MPI  для параллельных вычислений. Реализация включает работу с входными данными (изображениями), их обработку, распределение задач между процессами MPI и сбор результатов.

2024-12-16 20:46 UTC, Kvoks requested changes
code coverage is too low

2024-12-18 11:25 UTC, Kvoks approved these changes

2024-12-19 15:40 UTC, decl1 requested changes

2024-12-19 15:40 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/src/ops_mpi.cpp
> +  if (!validation()) {
this is not needed here

2024-12-19 15:40 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/src/ops_mpi.cpp
> +  if (taskData == nullptr) {
its validation

2024-12-19 15:40 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/src/ops_mpi.cpp
> +  if (task_data == nullptr) {
its validation

2024-12-19 15:40 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/src/ops_mpi.cpp
> +  if (input_image == nullptr || output_image == nullptr) {
its validation

2024-12-19 15:40 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/src/ops_mpi.cpp
> +  if (width == 0 || height == 0) {
its validation

2024-12-19 15:40 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/src/ops_mpi.cpp
> +  uint8_t* output_image = taskData->outputs[0];
its preproccesing

2024-12-19 15:40 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/src/ops_mpi.cpp
> +  if (taskData == nullptr || taskData->outputs[0] == nullptr) {
its validation

2024-12-19 15:52 UTC, decl1 requested changes

2024-12-19 15:52 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/src/ops_mpi.cpp
> +}
I think you shouldn't do this. The class must be inherited

2024-12-19 15:52 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/src/ops_mpi.cpp
> +  }
this is validation

2024-12-19 15:52 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/src/ops_mpi.cpp
> +  }
u dont need do this check

2024-12-19 15:52 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/src/ops_mpi.cpp
> +  }
this is validation

2024-12-19 15:52 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/src/ops_mpi.cpp
> +  }
this is validation

2024-12-19 15:52 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/src/ops_mpi.cpp
> +  }
this is validation

2024-12-19 15:52 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/src/ops_mpi.cpp
> +  uint8_t* output_image = taskData->outputs[0];
its preproccesing

2024-12-19 15:52 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/src/ops_mpi.cpp
> +  world.barrier();
I could be wrong. it is not necessary to put a barrier before return

2024-12-19 15:52 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/src/ops_mpi.cpp
> +  if (taskData == nullptr || taskData->outputs[0] == nullptr) {
its validation

2024-12-19 15:52 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/include/ops_mpi.hpp
> +};
this class must be inherited : public ppc::core::Task

2024-12-19 15:52 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/include/ops_mpi.hpp
> +};
it's in public ppc::core::Task

2024-12-19 15:52 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/include/ops_mpi.hpp
> +};
and you must add seq task in ops_mpi.hpp. You need compare them in func tests.

2024-12-19 15:59 UTC, decl1 requested changes

2024-12-19 15:59 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/include/ops_mpi.hpp
> +};
you tasks classes must be from public ppc::core::Task

2024-12-19 15:59 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/src/ops_mpi.cpp
> +}
must be from public ppc::core::Task

2024-12-19 15:59 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/src/ops_mpi.cpp
> +  if (taskData == nullptr || taskData->inputs.empty() || taskData->outputs.empty()) {
in begin of every task function must be internal_order_test();

2024-12-19 16:00 UTC, decl1 commented on tasks/mpi/mezhuev_m_sobel_edge_detection/src/ops_mpi.cpp
> +  if (taskData == nullptr || taskData->inputs.empty() || taskData->outputs.empty()) {
```suggestion
bool SobelEdgeDetectionMPI::validation() {
  internal_order_test();
  
  // your function code here
  
  return ...;
}
```

2024-12-21 06:39 UTC, decl1 approved these changes

2024-12-23 00:43 UTC, allnes commented on tasks/mpi/mezhuev_m_sobel_edge_detection/src/ops_mpi.cpp
> +  if (taskData->inputs_count[0] != taskData->outputs_count[0]) {
where check sizes of inputs_count, outputs_count?

2024-12-23 00:44 UTC, allnes commented on tasks/mpi/mezhuev_m_sobel_edge_detection/src/ops_mpi.cpp
> +  uint8_t* output_image = taskData->outputs[0];
@Domovenokkk you haven't corrected this comment

2024-12-23 00:46 UTC, allnes commented
@decl1 you approved this PR, but some comments wasn't corrected, @Domovenokkk please add 1 addtional reviewer

2024-12-24 03:21 UTC, aobolensk commented
Please increase test coverage

2024-12-29 19:41 UTC, closed without merging