Милованкин Максим. Задача 1. Вариант 1. Сумма элементов вектора.
learning-process/ppc-2024-autumn pull request #62
Opened 2024-10-28 20:43 UTC by lizardwizardd

_**Последовательная задача**_
Итерация по элементам вектора и суммирование значений.

**_Параллельная задача_**
Вектор разделяется между процессами на равные части. Если количество элементов N не делится нацело на количество процессов P, то первые `N % P` процессов обрабатывают еще по одному элементу. 
Данные распределяются по процессам функцией `scatterv`, каждый процесс подсчитывает свою часть с помощью `accumulate`, затем получившиеся в процессах суммы складываются функцией `reduce`.

2024-10-31 16:38 UTC, allnes requested changes

2024-10-31 16:38 UTC, allnes commented on tasks/mpi/milovankin_m_sum_of_vector_elements/src/ops_mpi.cpp
> +bool VectorSumPar::pre_processing() {
please use all mpi functions in run()

2024-10-31 21:30 UTC, lizardwizardd commented on tasks/mpi/milovankin_m_sum_of_vector_elements/src/ops_mpi.cpp
> +bool VectorSumPar::pre_processing() {
fixed

2024-11-01 18:48 UTC, Sean0450 approved these changes

2024-11-01 20:05 UTC, Egor1dzeN-learn approved these changes

2024-11-02 01:24 UTC, allnes approved these changes

2024-11-03 02:35 UTC, aobolensk requested changes

2024-11-03 13:40 UTC, aobolensk approved these changes

2024-11-03 14:03 UTC, merged