Агафеев Сергей. Задача 2. Вариант 10. Линейная топология сети.
learning-process/ppc-2024-autumn pull request #622
Opened 2024-12-16 21:41 UTC by GrayPirat

Параллельная реализация:
Начиная с процесса ранга 0 и до процесса ранга N-1 передается вектор случайных чисел и вектор "журнал регистрации". 
Чтобы точно знать, что все данные были переданы от начала и до конца, каждый процесс отмечается в "журнале регистрации" который в последнем процессе проверяется на правильность порядка и наличие всех записей в нём. Только после этого последний процесс отправляет результат: "true", если всё в порядке и все процессы по очереди передали данные, и "false", если что-то пошло не так.

2024-12-17 09:53 UTC, korablev-vm requested changes
У вас не совсем корректная логика работы программы. Должно задаваться два узла - отправитель и получатель. Данные должны передаваться по кратчайшему пути, а маршрут сохраняться. Кроме того, так как реализация основана на шаблонах, перенесите ее в .hpp файл

2024-12-17 12:30 UTC, Torcna requested changes

2024-12-18 15:52 UTC, GrayPirat commented on tasks/mpi/agafeev_s_linear_topology/func_tests/main.cpp
> +}
It's static already, so it won't be seen in other files

2024-12-19 10:37 UTC, korablev-vm approved these changes

2024-12-19 12:53 UTC, Torcna approved these changes

2024-12-19 13:17 UTC, Torcna requested changes
im sorry, i realized that there are some problems with logic of implementation/ I mentioned them in comment below, please,  change, if you agree with me or explain what are you doing, and why you think this is right

2024-12-19 13:17 UTC, Torcna commented on tasks/mpi/agafeev_s_linear_topology/func_tests/main.cpp
> +
Whoops, what’s this?
I don’t quite understand why this is in the test body and not in the validation section.
Also, I’m not sure if it’s okay to have a test so tightly coupled to world.size(). I think a linear topology is supposed to send data from 0 to n-1, where n-1 checks if the data is correct and then responds to the root with the result. What you’re doing here is quite questionable.

2024-12-19 13:39 UTC, GrayPirat commented on tasks/mpi/agafeev_s_linear_topology/func_tests/main.cpp
> +
Oh, sure, I will change this to check validation instead of GTEST_SKIP();
As I understand it, the essence of the task is that any process can correctly send data to any other process using the linear network topology.  That is, the network has only two end nodes and any number of intermediate nodes. And there is only one path between any two nodes

2024-12-19 20:44 UTC, Torcna commented on tasks/mpi/agafeev_s_linear_topology/func_tests/main.cpp
> +
alright, with that i can accept it. Thank you for special commit for me

2024-12-19 20:45 UTC, Torcna approved these changes

2024-12-19 20:47 UTC, GrayPirat commented
I appeal to the Gods @allnes @aobolensk

2024-12-21 12:58 UTC, aobolensk approved these changes

2024-12-23 00:52 UTC, allnes approved these changes

2024-12-23 00:52 UTC, merged