Колоколова Дарья. Задача 3. Вариант 19. Поразрядная сортировка для целых чисел с четно-нечетным слиянием Бэтчера.
learning-process/ppc-2024-autumn pull request #624
Opened 2024-12-16 21:58 UTC by dasha1112

Описание последовательной задачи
В последовательной версии реализована поразрядная сортировка для целых чисел с помощью функции radix_sort. Сначала она находит максимальное и минимальное значения в векторе, чтобы определить диапазон разрядов для сортировки. Затем, с помощью цикла, она вызывает функцию counting_sort_radix для сортировки чисел по разрядам, начиная с наименьшего. После обработки всех разрядов массив делится на два вектора: один для отрицательных чисел и другой для положительных. Отрицательные числа сортируются по возрастанию, а положительные остаются в отсортированном порядке. В конце оба вектора объединяются, и возвращается итоговый отсортированный массив.

Описание MPI задачи
В MPI версии реализован алгоритм поразрядной сортировки с четно-нечетным слиянием Бэтчера согласно его логике работы. Сначала на вход подается вектор целых чисел, после чего он делится между процессами. Далее в цикле, который повторяется ровно столько раз, сколько всего было запущено процессов, каждый процесс обменивается данными с соседним процессом, согласно логике алгоритма сортировки четно-нечетным слиянием Бэтчера. То есть, если итерация кратна двум, то процессы с четными рангами отправляют соседнему процессу свою часть вектора, а те в свою очередь при помощи функции radix_sort сортируют вектор, полученный при помощи слияния этих двух процессов. Далее процессу с меньшим рангом отправляется соответственно часть вектора с минимальными значениями, а процессу с большим рангом достается часть вектора с максимальными значениями. Аналогичная ситуация происходит на итерации не кратной, но уже с процессами с нечетными рангами. После цикла со всех процессов собираются результаты с помощью gather.

2024-12-17 07:52 UTC, Kitos87 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +    ASSERT_EQ(testMpiTaskParallel.validation(), false);
Please, use ASSERT_FALSE

2024-12-17 07:52 UTC, Kitos87 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +      ASSERT_EQ(sorted_vector[i], reference_res[i]);
Please, use EXPECT_EQ

2024-12-17 07:52 UTC, Kitos87 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +    ASSERT_EQ(testTaskSequential.validation(), true);
Please, use ASSERT_TRUE

2024-12-17 07:52 UTC, Kitos87 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +  ASSERT_EQ(testMpiTaskParallel.validation(), true);
Please, use ASSERT_TRUE

2024-12-17 07:52 UTC, Kitos87 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +      ASSERT_EQ(sorted_vector[i], reference_res[i]);
Please, use EXPECT_EQ

2024-12-17 07:52 UTC, Kitos87 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +    ASSERT_EQ(testTaskSequential.validation(), true);
Please, use ASSERT_TRUE

2024-12-17 07:52 UTC, Kitos87 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +  ASSERT_EQ(testMpiTaskParallel.validation(), true);
Please, use ASSERT_TRUE

2024-12-17 07:52 UTC, Kitos87 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +  ASSERT_EQ(testMpiTaskParallel.validation(), true);
Please, use ASSERT_TRUE

2024-12-17 07:52 UTC, Kitos87 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +    ASSERT_EQ(testTaskSequential.validation(), true);
Same

2024-12-17 07:52 UTC, Kitos87 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +      ASSERT_EQ(sorted_vector[i], reference_res[i]);
Please, use EXPECT_EQ

2024-12-18 11:02 UTC, dasha1112 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +    ASSERT_EQ(testMpiTaskParallel.validation(), false);
Fixed

2024-12-18 11:02 UTC, dasha1112 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +      ASSERT_EQ(sorted_vector[i], reference_res[i]);
Fixed

2024-12-18 11:02 UTC, dasha1112 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +  ASSERT_EQ(testMpiTaskParallel.validation(), true);
Fixed

2024-12-18 11:02 UTC, dasha1112 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +      ASSERT_EQ(sorted_vector[i], reference_res[i]);
Fixed

2024-12-18 11:02 UTC, dasha1112 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +    ASSERT_EQ(testTaskSequential.validation(), true);
Fixed

2024-12-18 11:02 UTC, dasha1112 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +  ASSERT_EQ(testMpiTaskParallel.validation(), true);
Fixed

2024-12-18 11:02 UTC, dasha1112 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +  ASSERT_EQ(testMpiTaskParallel.validation(), true);
Fixed

2024-12-18 11:02 UTC, dasha1112 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +    ASSERT_EQ(testTaskSequential.validation(), true);
Fixed

2024-12-18 11:02 UTC, dasha1112 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +      ASSERT_EQ(sorted_vector[i], reference_res[i]);
Fixed

2024-12-18 14:30 UTC, Kitos87 approved these changes

2024-12-18 21:51 UTC, antihype320 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +}
Please, add test when output is empty to check validation

2024-12-22 13:15 UTC, dasha1112 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +}
Fixing

2024-12-22 16:27 UTC, antihype320 approved these changes

2024-12-22 18:10 UTC, aobolensk requested changes

2024-12-22 18:10 UTC, aobolensk commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
Please, move test function to the test module

2024-12-22 18:10 UTC, aobolensk commented on tasks/seq/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +
Please, add random tests

2024-12-22 18:10 UTC, aobolensk commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/perf_tests/main.cpp
> +    vec[i] = gen() % 100;
Please, use negative numbers

2024-12-23 00:53 UTC, allnes commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +  std::uniform_int_distribution<int> dist(-10000, 10000);
please parametrize this constants in tests

2024-12-23 00:54 UTC, allnes commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +  int size_vector = world.size() * 4;
why do you do multiplication?

2024-12-23 00:54 UTC, allnes commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
please remove it

2024-12-23 00:55 UTC, allnes commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/src/ops_mpi.cpp
> +    int index = (array[i] / exp) % 10;
exp is reservated name

2024-12-23 00:55 UTC, allnes commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/src/ops_mpi.cpp
> +  for (int exp = 1; max_num / exp > 0 || min_num / exp < 0; exp *= 10) {
please describe this loop

2024-12-23 22:44 UTC, dasha1112 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
Fixed

2024-12-23 22:44 UTC, dasha1112 commented on tasks/seq/kolokolova_d_radix_integer_merge_sort/func_tests/main.cpp
> +
Fixed

2024-12-23 22:44 UTC, dasha1112 commented on tasks/mpi/kolokolova_d_radix_integer_merge_sort/perf_tests/main.cpp
> +    vec[i] = gen() % 100;
Fixed

2024-12-24 03:21 UTC, aobolensk approved these changes

2024-12-24 18:19 UTC, merged