Зиновьев Александр Задача 2 Вариант 2 Задача «Читатели-Писатели»
learning-process/ppc-2024-autumn pull request #627
Opened 2024-12-17 01:17 UTC by kobych

В данной работе представлена реализация классической задачи синхронизации "Читатели-Писатели" в контексте параллельного программирования. Решение предоставлено как в параллельной версии с использованием MPI, так и в последовательной версии. Реализация включает в себя функциональные тесты, тесты производительности, а также необходимые исходные и заголовочные файлы.

Проект содержит два основных класса задач:

**ReadersWritersMPITaskSequential:** Класс, реализующий последовательное выполнение задачи "Читатели-Писатели". Используется для сравнения с параллельным выполнением.

**ReadersWritersMPITaskParallel:** Класс, реализующий параллельное выполнение задачи "Читатели-Писатели" с использованием MPI. Распределяет вычисления на несколько процессов и использует механизмы синхронизации для обеспечения корректного доступа к общим данным.

2024-12-17 20:07 UTC, dasha1112 requested changes

2024-12-17 20:07 UTC, dasha1112 commented on tasks/mpi/zinoviev_a_readers_and_writers/src/ops_mpi.cpp
> +}
Please, add check for input

2024-12-17 20:07 UTC, dasha1112 commented on tasks/mpi/zinoviev_a_readers_and_writers/src/ops_mpi.cpp
> +  }
Please, add check for input

2024-12-17 20:47 UTC, shyravina19102004 commented on tasks/mpi/zinoviev_a_readers_and_writers/src/ops_mpi.cpp
> +
Please add this to the tests

std::vector<int> zinoviev_a_readers_and_writers_mpi::getRandomVector(int sz) {
  std::random_device dev;
  std::mt19937 gen(dev());
  std::vector<int> vec(sz);
  for (int i = 0; i < sz; i++) {
    vec[i] = gen() % 100;
  }
  return vec;
}

2024-12-18 09:41 UTC, kobych commented on tasks/mpi/zinoviev_a_readers_and_writers/src/ops_mpi.cpp
> +
fixed

2024-12-18 09:41 UTC, kobych commented on tasks/mpi/zinoviev_a_readers_and_writers/src/ops_mpi.cpp
> +}
fixed

2024-12-18 09:45 UTC, shyravina19102004 approved these changes

2024-12-18 10:04 UTC, dasha1112 approved these changes

2024-12-19 12:16 UTC, kobych commented
@allnes @aobolensk please, check

This is new PR with separated task and new approves as you asked. The previous PR of this task is here: https://github.com/learning-process/ppc-2024-autumn/pull/374

2024-12-19 19:55 UTC, aobolensk approved these changes

2024-12-20 11:17 UTC, kobych commented
@allnes please, check

2024-12-23 00:56 UTC, allnes approved these changes

2024-12-23 00:56 UTC, merged