Отурин Александр. Задача 3. Вариант 30. Повышение контраста полутонового изображения посредством линейной растяжки гистограммы.
learning-process/ppc-2024-autumn pull request #632
Opened 2024-12-17 08:11 UTC by ovVrLFg8ks

**Описание последовательной задачи:**
Для всего изображения находится минимальная и максимальная яркость у пикселей. На основе этой информации повышается контрастность изображения, сначала вычислив множитель:
float pixMultiplier = 255.0f / (maximum - minimum)
и с помощью него вычисляется конечная яркость пикселей:
output[i] = round(input[i] - minimum) * pixMultiplier)

**Описание MPI задачи:**
0-ой процесс вычисляет, как поделить изображение на равные части и отправляет полученный размер блока остальным процессам. Затем и сам кусок изображения. 
Значение последнего куска изображения может отличаться от остальных. Если, например, процессов 4, а пикселей 3, то остальные процессы получают размер 0 и завершают работу, осознавая свою бессмысленность. И 0-ой выполняет всю работу из 3-ёх пикселей. Изображение из 6px разделится на 4 процесса как 1,1,1 и 3.
А так все процессы сканируют полученный кусок и выдают минимум и максимум нулевому. Нулевой вычисляет самый минимальный минимум, отсылает всем. И все вместе начинают преобразовывать изображение. Полученные результаты собираются в нулевом. Да и всё...

2024-12-17 13:12 UTC, artich02 requested changes

2024-12-17 13:12 UTC, artich02 commented on tasks/seq/oturin_a_histogram_stretch/func_tests/main.cpp
add a test where the maximum and minimum brightness are equal

2024-12-17 14:31 UTC, ovVrLFg8ks commented on tasks/seq/oturin_a_histogram_stretch/func_tests/main.cpp
new Test_IMAGE_ONECOLOR improved code coverage from 79.62% to 83.33%, thanks

2024-12-23 14:31 UTC, WholeHorse requested changes

2024-12-23 14:31 UTC, WholeHorse commented on tasks/mpi/oturin_a_histogram_stretch/src/ops_mpi.cpp
> +    auto* data = new uint8_t[picMemSize];
Potential memory leak: Using `new` without a corresponding `delete` risks memory leaks if exceptions occur. Consider replacing the raw pointer with `std::vector<uint8_t>` or `std::unique_ptr<uint8_t[]>` for safer memory management.

2024-12-23 15:45 UTC, ovVrLFg8ks commented on tasks/mpi/oturin_a_histogram_stretch/src/ops_mpi.cpp
> +    auto* data = new uint8_t[picMemSize];
ok, now it's a vector

2024-12-23 16:20 UTC, WholeHorse approved these changes

2024-12-24 03:48 UTC, aobolensk approved these changes

2024-12-25 18:56 UTC, merged