Лаврентьев Алексей. Задача 3. Вариант 20. Поразрядная сортировка для вещественных чисел (тип double) с простым слиянием.
learning-process/ppc-2024-autumn pull request #633
Opened 2024-12-17 10:10 UTC by mahor13

Мой алгоритм выполняет параллельную сортировку с использованием распределения и слияния данных:

1. **Распределение данных**: Исходный массив распределяется между всеми процессами с помощью `Scatterv`, чтобы каждый процесс получил свой подмассив.
2. **Локальная поразрядная сортировка**: Каждый процесс выполняет поразрядную сортировку на своей части данных.
3. **Сбор данных**: Отсортированные локальные подмассивы собираются на нулевом процессе с помощью `Gatherv`.
4. **Слияние отсортированных данных**: На нулевом процессе выполняется слияние подмассивов в итоговый отсортированный массив.

В результате алгоритм эффективно использует параллельные вычисления для ускорения сортировки большого массива данных.

2024-12-17 23:05 UTC, venn2713 requested changes

2024-12-17 23:05 UTC, venn2713 commented on tasks/mpi/lavrentyev_a_radix_sort_simple_merge/src/ops_mpi.cpp
> +  }
Думаю вы можете не разделять тут это, есть возможность вызвать scatterv на всех процессах и не придется ничего лишний раз проверять

2024-12-17 23:05 UTC, venn2713 commented on tasks/mpi/lavrentyev_a_radix_sort_simple_merge/src/ops_mpi.cpp
> +  }
Аналогично для gatherv

2024-12-18 03:25 UTC, korablev-vm requested changes

2024-12-18 17:02 UTC, korablev-vm approved these changes

2024-12-19 20:24 UTC, aobolensk approved these changes

2024-12-23 01:06 UTC, allnes commented on tasks/mpi/lavrentyev_a_radix_sort_simple_merge/func_tests/main.cpp
> +TEST(lavrentyev_a_radix_sort_simple_merge_mpi, Random_Vector_With_Duplicate_Values) {
please check reverse sort case

2024-12-25 18:56 UTC, merged