Зиновьев Александр Задача 3 Вариант 23 Задача «Поиск кратчайших путей из одной вершины (алгоритм Беллмана-Форда). С CRS графов».
learning-process/ppc-2024-autumn pull request #634
Opened 2024-12-17 12:30 UTC by kobych

В данной работе представлена реализация **алгоритма Беллмана-Форда для поиска кратчайших путей из одной вершины в графе, представленном в формате CRS (Compressed Row Storage)**. Задача включает как последовательную, так и параллельную реализации алгоритма.

**Алгоритм Беллмана-Форда:**

Алгоритм Беллмана-Форда используется для нахождения кратчайших путей от одной вершины (источника) до всех остальных вершин в графе. Он работает с графами, которые могут содержать рёбра с отрицательными весами, но не допускает наличия отрицательных циклов.

В данной задаче граф представлен в формате CRS, что позволяет эффективно хранить разреженные графы.

**Формат CRS (Compressed Row Storage):**

CRS — это формат хранения графа, который использует три массива:

row_ptr: указатели на начало строк в матрице смежности.

col_ind: индексы столбцов для каждого ребра.

values: веса рёбер.

Этот формат позволяет эффективно работать с разреженными графами, где количество рёбер значительно меньше, чем количество возможных рёбер в полном графе.

2024-12-22 16:29 UTC, antihype320 commented on tasks/seq/zinoviev_a_bellman_ford/func_tests/main.cpp
> +}
add more tests, please

2024-12-22 18:47 UTC, shyravina19102004 requested changes

2024-12-22 18:47 UTC, shyravina19102004 commented on tasks/mpi/zinoviev_a_bellman_ford/func_tests/main.cpp
> +TEST(zinoviev_a_bellman_ford, Test_Small_Graph_mpi) {
Please add more tests

2024-12-23 00:29 UTC, antihype320 approved these changes

2024-12-23 09:57 UTC, kobych commented on tasks/seq/zinoviev_a_bellman_ford/func_tests/main.cpp
> +}
fixed

2024-12-24 11:13 UTC, shyravina19102004 approved these changes

2024-12-24 20:05 UTC, aobolensk requested changes

2024-12-24 20:05 UTC, aobolensk commented on tasks/mpi/zinoviev_a_bellman_ford/func_tests/main.cpp
> +
Please, add random tests

2024-12-24 20:05 UTC, aobolensk commented on tasks/mpi/zinoviev_a_bellman_ford/perf_tests/main.cpp
> +TEST(zinoviev_a_bellman_ford, test_pipeline_run) {
Please, test performance on big random graphs

2024-12-25 03:59 UTC, aobolensk approved these changes

2024-12-25 09:03 UTC, kobych commented
@allnes please, check

2024-12-25 18:57 UTC, merged