Fix revert Одинцов Михаил. Задача 1.Вариант 27 Подсчет числа несовпадающих символов двух строк
learning-process/ppc-2024-autumn pull request #636
Opened 2024-12-17 12:41 UTC by odincovm

https://github.com/learning-process/ppc-2024-autumn/pull/513 Добавил рандомные тесты

2024-12-18 14:48 UTC, sanya2905 approved these changes

2024-12-19 14:40 UTC, Ilya2643 approved these changes

2024-12-21 13:20 UTC, aobolensk requested changes
Please, increase code coverage

2024-12-23 01:08 UTC, allnes commented on tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/src/ops_mpi.cpp
> +bool CountingCharacterMPIParallel::run() {
what happend with algorithm? and how did you fix it?

2024-12-23 17:23 UTC, odincovm commented on tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/src/ops_mpi.cpp
> +bool CountingCharacterMPIParallel::run() {
Откатился до того момента, когда я случайно замержился. При локальном запуске отдельно тесты проходили а в общем некоторые чужие тесты ломались ( видно их выкинули после моих и моя ветка просто не обновилась). Также исправил генерацию строк и теперь не засоряет буфер
![image](https://github.com/user-attachments/assets/8cd16790-5d6a-4a15-aed6-968305f380e2)

2024-12-25 18:34 UTC, aobolensk approved these changes

2024-12-25 18:57 UTC, merged