Ясакова Татьяна. Задача 3. Вариант 14. Быстрая сортировка с простым слиянием.
learning-process/ppc-2024-autumn pull request #640
Opened 2024-12-17 13:50 UTC by Tanya-Yasakova

Алгоритм включает в себя следующие основные этапы:

1. Декомпозиция данных:
Данные равномерно распределяются между процессами с помощью scatterv.
Каждый процесс сортирует свою часть данных с помощью итеративной быстрой сортировки.

2. Взаимодействие между рабочими процессами и мастером:
Рабочие процессы отправляют свои отсортированные элементы по одному мастеру.
Перед отправкой каждого элемента рабочий процесс ждет подтверждения от мастера.
Мастер-процесс использует минимальную кучу для эффективного слияния данных, поступающих от рабочих процессов.
На каждом шаге мастер извлекает наименьший элемент из кучи, добавляет его в результирующий массив и запрашивает следующий элемент у соответствующего рабочего процесса.

3. Синхронизация и сбор результатов:
Функция merge_func вызывает master_function для мастера и worker_function для рабочих процессов.
Все процессы синхронизируются через барьер, чтобы гарантировать завершение обмена данными.

Таким образом, алгоритм сочетает в себе декомпозицию данных, локальную сортировку и эффективное слияние результатов с помощью минимальной кучи, обеспечивая параллельную обработку и синхронизацию между процессами.

2024-12-17 14:17 UTC, AnastasiaRezantseva commented on tasks/seq/yasakova_t_quick_sort_with_simple_merge/func_tests/main.cpp
> +void executeQuickSortTest(const std::vector<int>& inputData) {
move this method to your namespace

2024-12-17 14:18 UTC, AnastasiaRezantseva commented on tasks/mpi/yasakova_t_quick_sort_with_simple_merge/func_tests/main.cpp
> +std::vector<int> create_random_integer_vector(int size, int minimum_value = -100, int maximum_value = 100,
move all methods in your tests file to your namespace

2024-12-17 14:20 UTC, AnastasiaRezantseva commented on tasks/seq/yasakova_t_quick_sort_with_simple_merge/func_tests/main.cpp
> +
please, add tests with negative numbers

2024-12-17 14:47 UTC, Tanya-Yasakova commented on tasks/seq/yasakova_t_quick_sort_with_simple_merge/func_tests/main.cpp
> +void executeQuickSortTest(const std::vector<int>& inputData) {
fixed

2024-12-17 14:48 UTC, Tanya-Yasakova commented on tasks/seq/yasakova_t_quick_sort_with_simple_merge/func_tests/main.cpp
> +
add

2024-12-17 14:50 UTC, AnastasiaRezantseva approved these changes

2024-12-17 14:57 UTC, emilien-gus requested changes

2024-12-17 14:57 UTC, emilien-gus commented on tasks/seq/yasakova_t_quick_sort_with_simple_merge/perf_tests/main.cpp
> +#include <random>
Please remove all unnecessary headers

2024-12-17 14:57 UTC, emilien-gus commented on tasks/mpi/yasakova_t_quick_sort_with_simple_merge/func_tests/main.cpp
> +#include <gtest/gtest.h>
Please add some tests with sorted data and with big numbers

2024-12-17 15:19 UTC, Tanya-Yasakova commented on tasks/seq/yasakova_t_quick_sort_with_simple_merge/perf_tests/main.cpp
> +#include <random>
done

2024-12-17 18:10 UTC, emilien-gus approved these changes

2024-12-19 20:25 UTC, aobolensk approved these changes

2024-12-23 01:14 UTC, allnes commented on tasks/mpi/yasakova_t_quick_sort_with_simple_merge/src/ops_mpi.cpp
> +struct PriorityQueueNode {
please use std::priority_queue

2024-12-23 01:15 UTC, allnes commented on tasks/mpi/yasakova_t_quick_sort_with_simple_merge/func_tests/main.cpp
> +TEST(yasakova_t_quick_sort_with_simple_merge_mpi, test_random_generated_array_with_10_elements) {
please add reverse sort case

2024-12-23 13:26 UTC, Tanya-Yasakova commented on tasks/mpi/yasakova_t_quick_sort_with_simple_merge/src/ops_mpi.cpp
> +struct PriorityQueueNode {
I'm already using this

2024-12-23 13:27 UTC, Tanya-Yasakova commented on tasks/mpi/yasakova_t_quick_sort_with_simple_merge/func_tests/main.cpp
> +TEST(yasakova_t_quick_sort_with_simple_merge_mpi, test_random_generated_array_with_10_elements) {
add

2024-12-23 15:54 UTC, Tanya-Yasakova commented on tasks/mpi/yasakova_t_quick_sort_with_simple_merge/func_tests/main.cpp
> +TEST(yasakova_t_quick_sort_with_simple_merge_mpi, test_random_generated_array_with_10_elements) {
add

2024-12-26 17:26 UTC, closed without merging