Шуравина Оксана. Задача 1 Вариант 21. Интегрирование – метод Монте-Карло.
learning-process/ppc-2024-autumn pull request #641
Opened 2024-12-17 13:56 UTC by shyravina19102004

2024-12-19 20:32 UTC, antihype320 commented on tasks/mpi/shuravina_o_monte_carlo/perf_tests/main.cpp
> +
std::cout calls can slow down execution by reducing their number

2024-12-19 20:56 UTC, dasha1112 requested changes
Please, add a task description

2024-12-19 21:06 UTC, dasha1112 approved these changes

2024-12-19 21:30 UTC, antihype320 approved these changes

2024-12-19 22:36 UTC, shyravina19102004 commented on tasks/mpi/shuravina_o_monte_carlo/perf_tests/main.cpp
> +
fix

2024-12-21 13:21 UTC, aobolensk requested changes
Please, increase code coverage

2024-12-23 01:16 UTC, allnes approved these changes

2024-12-24 20:06 UTC, aobolensk approved these changes

2024-12-24 20:06 UTC, merged