Шуравина Оксана. Задача 2 Вариант 27. Повышение контраста.
learning-process/ppc-2024-autumn pull request #642
Opened 2024-12-17 14:49 UTC by shyravina19102004

2024-12-19 21:07 UTC, dasha1112 requested changes
Please, add a task description

2024-12-19 21:43 UTC, dasha1112 approved these changes

2024-12-19 21:54 UTC, kobych requested changes

2024-12-19 21:54 UTC, kobych commented on tasks/mpi/shuravina_o_contrast/src/ops_mpi.cpp
> +      output_[i] = static_cast<uint8_t>((local_input_[i] - min_val_) * 255.0 / (max_val_ - min_val_));
There is an error in the intensity normalization formula. fix it. please

2024-12-19 22:04 UTC, kobych requested changes

2024-12-19 22:04 UTC, kobych commented on tasks/seq/shuravina_o_contrast/src/ops_seq.cpp
> +
Skipping the check for an empty image

2024-12-19 22:35 UTC, shyravina19102004 commented on tasks/seq/shuravina_o_contrast/src/ops_seq.cpp
> +
fix

2024-12-19 22:35 UTC, kobych approved these changes

2024-12-20 16:33 UTC, aobolensk commented
<img width="872" alt="image" src="https://github.com/user-attachments/assets/bd1fdcf4-3edf-4830-ac20-69944e0e2ce2" />
Too low code coverage

2024-12-23 01:17 UTC, allnes approved these changes

2024-12-29 19:42 UTC, closed without merging