Шуравина Оксана. Задание 3 Вариант 25. Построение выпуклой оболочки – проход Джарвиса.
learning-process/ppc-2024-autumn pull request #643
Opened 2024-12-17 15:52 UTC by shyravina19102004

Построение выпуклой оболочки – проход Джарвиса
Алгоритм Джарвиса — это метод построения выпуклой оболочки. Он работает следующим образом:
Находится самая левая (или самая нижняя) точка из множества точек — это первая точка выпуклой оболочки.
Начиная с этой точки, алгоритм находит следующую точку оболочки, используя критерий поворота (правило ориентированного угла).
Процесс повторяется, пока алгоритм не вернётся к начальной точке.

Последовательная реализация
Выбирается самая левая (или самая нижняя) точка из множества точек. Эта точка будет первой точкой выпуклой оболочки.
Начиная с стартовой точки, алгоритм находит следующую точку оболочки, используя критерий поворота (правило ориентированного угла).
Процесс повторяется, пока алгоритм не вернётся к начальной точке.
После завершения обхода всех точек возвращается список точек, образующих выпуклую оболочку.

Параллельная реализация с использованием MPI
Вектор точек делится между процессами. Каждый процесс получает часть точек для обработки.
Каждый процесс выполняет последовательный алгоритм Джарвиса на своей части точек, получая локальную выпуклую оболочку.
Все локальные оболочки собираются в корневой процесс.
Корневой процесс объединяет все локальные оболочки в одну глобальную выпуклую оболочку, используя последовательный алгоритм Джарвиса.

2024-12-17 21:41 UTC, dasha1112 requested changes
Please, add a task description

2024-12-17 21:47 UTC, dasha1112 approved these changes

2024-12-17 21:55 UTC, kobych requested changes

2024-12-17 21:55 UTC, kobych commented on tasks/mpi/shuravina_o_jarvis_pass/src/ops_mpi.cpp
> +
each variable must be declared on a separate line

2024-12-17 22:55 UTC, shyravina19102004 commented on tasks/mpi/shuravina_o_jarvis_pass/src/ops_mpi.cpp
> +
fix

2024-12-17 22:56 UTC, kobych approved these changes

2024-12-21 13:25 UTC, aobolensk requested changes

2024-12-21 13:25 UTC, aobolensk commented on tasks/mpi/shuravina_o_jarvis_pass/func_tests/main.cpp
> +TEST(shuravina_o_jarvis_pass, Test_Fixed_Points) {
Please, add more functional tests for the algorithm

2024-12-21 13:25 UTC, aobolensk commented on tasks/mpi/shuravina_o_jarvis_pass/perf_tests/main.cpp
> +TEST(shuravina_o_jarvis_pass_mpi_perf, Test_1000_Points) {
Please, follow perf test rules:
1. 2 tests
2. specific test names

2024-12-21 13:25 UTC, aobolensk commented on tasks/mpi/shuravina_o_jarvis_pass/perf_tests/main.cpp
> +    std::cout << "Time taken for 1000 points (MPI): " << elapsed.count() << " seconds" << std::endl;
Please, clean up extra output

2024-12-21 20:34 UTC, shyravina19102004 commented on tasks/mpi/shuravina_o_jarvis_pass/func_tests/main.cpp
> +TEST(shuravina_o_jarvis_pass, Test_Fixed_Points) {
fix

2024-12-21 20:34 UTC, shyravina19102004 commented on tasks/mpi/shuravina_o_jarvis_pass/perf_tests/main.cpp
> +TEST(shuravina_o_jarvis_pass_mpi_perf, Test_1000_Points) {
fix

2024-12-21 20:34 UTC, shyravina19102004 commented on tasks/mpi/shuravina_o_jarvis_pass/perf_tests/main.cpp
> +    std::cout << "Time taken for 1000 points (MPI): " << elapsed.count() << " seconds" << std::endl;
fix

2024-12-23 01:19 UTC, allnes commented on tasks/mpi/shuravina_o_jarvis_pass/func_tests/main.cpp
> +TEST(shuravina_o_jarvis_pass, Test_Empty_Points) {
please add few figures (e.g. cycle)

2024-12-25 04:00 UTC, aobolensk commented
Please increase code coverage

2024-12-25 15:16 UTC, shyravina19102004 commented on tasks/mpi/shuravina_o_jarvis_pass/func_tests/main.cpp
> +TEST(shuravina_o_jarvis_pass, Test_Empty_Points) {
fix

2024-12-25 18:35 UTC, aobolensk approved these changes

2024-12-25 18:58 UTC, merged