Кошкин Никита. Задача 3. Вариант 30. Повышение контраста полутонового изображения посредством  линейной растяжки гистограммы
learning-process/ppc-2024-autumn pull request #645
Opened 2024-12-17 20:11 UTC by NikitaKoshkin

Предописание, считаю, что на вход я принимаю матрицу (вектор) цветного изображения (которое заведомо обработано) вида "[R1, G1, B1, R2, G2, B2, ..., RN, GN, BN]".

Описание последовательной задачи:
1) Обрабатывается вектор image_input RGB, получение данных для каждого цвета R, G, B каждого пикселя.
2) Одновременно вычисляется массив яркостей "I" на основе RGB пикселя, затем сразу ищется минимум и максимум значения массива яркостей Imin и Imax.
3) Далее применение линейной растяжки (расчёт новых значений яркостей Inew).
4) Получение коэффициента coeff масштабирования для обратного преобразования массива яркостей в цвета пикселя RGB.
5) Расчет новых значений RGB и возврат нового вектора изображения image_output.

Описание MPI задачи: 
(Поскольку 1 задача была на матрицу и там я разделял входную матрицу на локальные части и обрабатывал их разными процессами, затем собирал все в едино, аналогично тому решению применил подобную реализацию и в данной задачи, т.к. другие не получалось заставить работать(()
1) Сначала главный процесс определяет общий размер входного изображения (image_input.size()). 
1.1) Передача размера изображения через broadcast.
1.2) Далее вычисляется количество пикселей и их распределение между процессами:
- num_pixels: общее количество пикселей (размер изображения делится на 3, т.к. каждая группа из трёх значений представляет RGB компоненты одного пикселя, аналогично для обработки в последовательной версии).
- pixels_per_process: базовое количество пикселей, обрабатываемое каждым процессом.
- extra_pixels: оставшиеся пиксели, которые не удалось равномерно распределить, они распределяются по первым процессам.
1.3) Расчёт локального количества пикселей на каждом процессе: local_pixels.
2) Вычисление send_counts и displacements главным процессом:
- send_counts: кол-во элементов, которые каждый процесс получит из общего массива данных. (local_pixels * 3, т.к. у каждого пикселя есть 3 компоненты RGB)
- displacements: смещение данных для каждого процесса относительно начала исходного массива.
2.1) Сообщение этих массивов всем процессам через broadcast.
3) Распределение данных с scatterv. Каждому процессу отправляется его локальная часть массива данных (local_input)
4) Каждый процесс обрабатывает свою часть данных локально. Вычисляются локальные яркости local_I и также находятся локальные минимумы и максимумы яркости local_Imin и local_Imax.
5) Сбор локальных мин. и макс. в глобальные данные через all_reduce, global_Imin и global_Imax.
6) Используя глобальные Imin и Imax, каждый процесс выполняет растяжение гистограммы Inew и коэффициента coeff масштабирования в local_output.
7) Сбор обработанных данных с gatherv, каждый процесс отправляет свои результаты главному процессу. Затем главный процесс собирает полный обработанный массив image_output.

2024-12-18 12:54 UTC, Napkin-AI requested changes

2024-12-18 17:59 UTC, EgorDormidontov requested changes

2024-12-18 17:59 UTC, EgorDormidontov commented on tasks/seq/koshkin_n_linear_histogram_stretch/src/ops_seq.cpp
> +    float coeff = static_cast<float>(Inew) / static_cast<float>(I[k]);
Use static_cast PLS

2024-12-18 17:59 UTC, EgorDormidontov commented on tasks/seq/koshkin_n_linear_histogram_stretch/src/ops_seq.cpp
> +  if (Imin == Imax) {
Add tests to test it

2024-12-18 17:59 UTC, EgorDormidontov commented on tasks/mpi/koshkin_n_linear_histogram_stretch/src/ops_mpi.cpp
> +  int Imin = 255, Imax = 0;
Clang-tidy is not proud of this

2024-12-18 17:59 UTC, EgorDormidontov commented on tasks/mpi/koshkin_n_linear_histogram_stretch/src/ops_mpi.cpp
> +  int global_Imin, global_Imax;
Clang-tidy is no joke

2024-12-18 20:13 UTC, EgorDormidontov approved these changes

2024-12-18 21:26 UTC, NikitaKoshkin commented on tasks/mpi/koshkin_n_linear_histogram_stretch/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
fix

2024-12-18 21:26 UTC, NikitaKoshkin commented on tasks/mpi/koshkin_n_linear_histogram_stretch/src/ops_mpi.cpp
> +    int R = image_input[i];
fix

2024-12-18 21:27 UTC, NikitaKoshkin commented on tasks/mpi/koshkin_n_linear_histogram_stretch/src/ops_mpi.cpp
> +    float coeff = static_cast<float>(Inew) / static_cast<float>(I[k]);
yes, i need to take this float coefficient into account, otherwise the conversion back to rgb does not work correctly with int

2024-12-18 21:28 UTC, NikitaKoshkin commented on tasks/mpi/koshkin_n_linear_histogram_stretch/func_tests/main.cpp
> +  // std::vector<int> in_vec = {105, 150, 200, 50, 80, 90, 255, 255, 255};
fix

2024-12-18 21:28 UTC, NikitaKoshkin commented on tasks/mpi/koshkin_n_linear_histogram_stretch/func_tests/main.cpp
> +#include <gtest/gtest.h>
added

2024-12-18 21:28 UTC, NikitaKoshkin commented on tasks/seq/koshkin_n_linear_histogram_stretch/src/ops_seq.cpp
> +using namespace std::chrono_literals;
fix

2024-12-18 21:28 UTC, NikitaKoshkin commented on tasks/seq/koshkin_n_linear_histogram_stretch/src/ops_seq.cpp
> +  // Перевод RGB в яркость (luminance) по стандартной формуле I=0.299⋅R+0.587⋅G+0.114⋅B
fix

2024-12-19 03:46 UTC, Napkin-AI approved these changes

2024-12-21 13:28 UTC, aobolensk requested changes

2024-12-22 20:14 UTC, NikitaKoshkin commented on tasks/mpi/koshkin_n_linear_histogram_stretch/src/ops_mpi.cpp
> +std::vector<int> koshkin_n_linear_histogram_stretch_mpi::getRandomImage(int sz) {
fixed all

2024-12-23 01:22 UTC, allnes commented on tasks/mpi/koshkin_n_linear_histogram_stretch/func_tests/main.cpp
> +  const int height = 3;
please add tests with different width and height

2024-12-23 01:24 UTC, allnes commented on tasks/mpi/koshkin_n_linear_histogram_stretch/src/ops_mpi.cpp
> +                            0.114 * static_cast<double>(b));
its preprocessing

2024-12-23 16:12 UTC, NikitaKoshkin commented on tasks/mpi/koshkin_n_linear_histogram_stretch/src/ops_mpi.cpp
> +                            0.114 * static_cast<double>(b));
moved

2024-12-23 16:12 UTC, NikitaKoshkin commented on tasks/mpi/koshkin_n_linear_histogram_stretch/func_tests/main.cpp
> +  const int height = 3;
done

2024-12-24 16:42 UTC, aobolensk approved these changes

2024-12-25 18:58 UTC, merged