‎Рамс Сергей. Задача 1. Вариант 23. Подсчет частоты символа в строке
learning-process/ppc-2024-autumn pull request #65
Opened 2024-10-29 16:08 UTC by 22380240

Описание последовательной задачи:
Входные данные: строка и символ.
Подсчет числа вхождений символа в строку с помощью std::count.
Выходные данные: число вхождений символа в строку.

Описание параллельной задачи:
Входная строка равномерно делится между процессами. В случае если целочисленное деление длины строки на количество процессов невозможно, оставшиеся символы добавляются к подстроке последнего процесса. Каждый процесс считает число символов в своей подстроке. Полученные в каждом из процессов значения суммируются при помощи reduce.

2024-10-29 16:14 UTC, kmichaelk commented on tasks/mpi/rams_s_char_frequency/src/ops_mpi.cpp
> +  broadcast(world, overflow, 0);
Perhaps a cheaper way would be to send only the total number and calculate the side ones independently in each process

2024-10-29 16:14 UTC, kmichaelk approved these changes

2024-10-30 14:59 UTC, MoiseevArt commented on tasks/mpi/rams_s_char_frequency/func_tests/main.cpp
> +
You can add some random tests

2024-10-30 15:51 UTC, MoiseevArt approved these changes

2024-10-30 15:53 UTC, kmichaelk approved these changes

2024-10-31 16:32 UTC, aobolensk requested changes

2024-10-31 16:32 UTC, aobolensk commented on tasks/mpi/rams_s_char_frequency/func_tests/main.cpp
> +}
Please, add test for empty string

2024-10-31 16:38 UTC, 22380240 commented on tasks/mpi/rams_s_char_frequency/func_tests/main.cpp
> +}
Он уже есть - https://github.com/learning-process/ppc-2024-autumn/pull/65/files/53336be30925715fd310f1fd55bf8e58fb85bd1d#diff-3b660f176379fb8ec04535f8ffeee2d2ab7d72dd47d18ba33c1250badc24f6e9R109-R112

2024-10-31 16:40 UTC, allnes requested changes

2024-10-31 16:40 UTC, allnes commented on tasks/mpi/rams_s_char_frequency/src/ops_mpi.cpp
> +bool rams_s_char_frequency_mpi::TestMPITaskParallel::pre_processing() {
please use all mpi functions in run()

2024-11-02 12:19 UTC, aobolensk approved these changes

2024-11-04 00:44 UTC, allnes approved these changes

2024-11-04 00:44 UTC, merged