Петров Олег. Задача 3. Вариант 18. Поразрядная сортировка для целых чисел с простым слиянием.
learning-process/ppc-2024-autumn pull request #651
Opened 2024-12-17 22:13 UTC by ValeraDanger

2024-12-17 22:32 UTC, mateusxap requested changes

2024-12-17 22:32 UTC, mateusxap commented on tasks/mpi/petrov_o_radix_sort_with_simple_merge/func_tests/main.cpp
> +#include <vector>
this libs is already in hpp

2024-12-17 22:32 UTC, mateusxap commented on tasks/mpi/petrov_o_radix_sort_with_simple_merge/src/ops_mpi.cpp
> +#include <iostream>
there is no need in iostream

2024-12-17 22:32 UTC, mateusxap commented on tasks/seq/petrov_o_radix_sort_with_simple_merge/perf_tests/main.cpp
> +#include <vector>
this libs is already in hpp

2024-12-17 22:32 UTC, mateusxap commented on tasks/seq/petrov_o_radix_sort_with_simple_merge/src/ops_seq.cpp
> +#include <iostream>
there is no need in iostream

2024-12-18 19:44 UTC, ValeraDanger commented on tasks/mpi/petrov_o_radix_sort_with_simple_merge/func_tests/main.cpp
> +#include <vector>
Fixed

2024-12-18 19:44 UTC, ValeraDanger commented on tasks/mpi/petrov_o_radix_sort_with_simple_merge/src/ops_mpi.cpp
> +#include <iostream>
Fixed

2024-12-18 19:44 UTC, ValeraDanger commented on tasks/seq/petrov_o_radix_sort_with_simple_merge/func_tests/main.cpp
> +#include <vector>
Fixed

2024-12-18 19:44 UTC, ValeraDanger commented on tasks/seq/petrov_o_radix_sort_with_simple_merge/func_tests/main.cpp
> +// Базовый тест на сортировку небольшого массива
Added

2024-12-18 19:45 UTC, ValeraDanger commented on tasks/seq/petrov_o_radix_sort_with_simple_merge/perf_tests/main.cpp
> +#include <vector>
Fixed

2024-12-18 19:45 UTC, ValeraDanger commented on tasks/seq/petrov_o_radix_sort_with_simple_merge/src/ops_seq.cpp
> +#include <iostream>
Fixed

2024-12-18 19:53 UTC, mateusxap approved these changes

2024-12-19 10:53 UTC, Applejack2004 requested changes

2024-12-19 10:53 UTC, Applejack2004 commented on tasks/mpi/petrov_o_radix_sort_with_simple_merge/func_tests/main.cpp
> +  } else {
This else is meaningless.

2024-12-19 10:53 UTC, Applejack2004 commented on tasks/mpi/petrov_o_radix_sort_with_simple_merge/func_tests/main.cpp
> +    taskData->inputs_count.emplace_back(0);
This else is meaningless.

2024-12-19 10:53 UTC, Applejack2004 commented on tasks/mpi/petrov_o_radix_sort_with_simple_merge/func_tests/main.cpp
> +    taskData->inputs_count.emplace_back(0);
This else is meaningless in all tests.

2024-12-19 10:53 UTC, Applejack2004 commented on tasks/mpi/petrov_o_radix_sort_with_simple_merge/func_tests/main.cpp
> +  } else {
This else is meaningless.

2024-12-19 16:45 UTC, ValeraDanger commented on tasks/mpi/petrov_o_radix_sort_with_simple_merge/func_tests/main.cpp
> +    taskData->inputs_count.emplace_back(0);
removed

2024-12-19 16:45 UTC, ValeraDanger commented on tasks/mpi/petrov_o_radix_sort_with_simple_merge/func_tests/main.cpp
> +    taskData->inputs_count.emplace_back(0);
removed

2024-12-19 16:46 UTC, ValeraDanger commented on tasks/mpi/petrov_o_radix_sort_with_simple_merge/func_tests/main.cpp
> +  } else {
removed

2024-12-19 16:51 UTC, Applejack2004 approved these changes

2024-12-23 01:28 UTC, allnes commented on tasks/mpi/petrov_o_radix_sort_with_simple_merge/func_tests/main.cpp
> +    in = {-100, -5, -3, 2, 7, 12};
please generate random vector with size - 2^n, 3^n, 10^n, prime values

2024-12-23 16:12 UTC, aobolensk requested changes

2024-12-23 16:12 UTC, aobolensk commented on tasks/seq/petrov_o_radix_sort_with_simple_merge/func_tests/main.cpp
> +
Please, add random tests

2024-12-23 16:12 UTC, aobolensk commented on tasks/seq/petrov_o_radix_sort_with_simple_merge/perf_tests/main.cpp
> +  std::vector<int> in = {1, 3, 7, 5, 6, 10, 12, 14, 15, 2};
Perf tests should be performed on big shapes

2024-12-23 22:27 UTC, ValeraDanger commented on tasks/seq/petrov_o_radix_sort_with_simple_merge/perf_tests/main.cpp
> +  std::vector<int> in = {1, 3, 7, 5, 6, 10, 12, 14, 15, 2};
Fixed

2024-12-23 22:27 UTC, ValeraDanger commented on tasks/seq/petrov_o_radix_sort_with_simple_merge/func_tests/main.cpp
> +
Added more random tests

2024-12-23 22:28 UTC, ValeraDanger commented on tasks/mpi/petrov_o_radix_sort_with_simple_merge/func_tests/main.cpp
> +    in = {-100, -5, -3, 2, 7, 12};
Done

2024-12-24 03:52 UTC, aobolensk approved these changes

2024-12-25 18:59 UTC, merged