Холин Кирилл. Задача 3. Вариант 7. Вычисление многомерных интегралов с использованием многошаговой схемы  (метод прямоугольников).
learning-process/ppc-2024-autumn pull request #657
Opened 2024-12-18 13:32 UTC by Kirius257

**ПОСТАНОВКА ЗАДАЧИ ДЛЯ ОДНОМЕРНОГО ИНТЕГРАЛА**
Необходимо вычислить определённый интеграл на отрезке ([a, b]). Этот отрезок разбивается на (n) равных частей, где длина каждой части определяется как

$$ h = \frac{b - a}{n}. $$

Обозначим через $$f\left(x_{i-1} + \frac{h}{2}\right)$$ значение функции в середине каждого частичного отрезка. Затем составим сумму произведений всех таких значений $$f\left(x_{i-1} + \frac{h}{2}\right)$$ на h — шаг отрезка. Полученная сумма будет представлять собой приближённое значение определённого интеграла на отрезке ([a, b]) по формуле средних прямоугольников:

$$ \int_{a}^{b} f(x) , dx \approx h \sum_{i=1}^{n} f\left(x_{i-1} + \frac{h}{2}\right) = h \sum_{i=1}^{n} f\left(x_{i} - \frac{h}{2}\right). $$

_ПРАВИЛО РУНГЕ_
Для оценки точности вычисления определённого интеграла применяется правило Рунге.
Интеграл вычисляется по выбранной формуле численного интегрирования(в данном случае по формуле средних прямоугольников) при числе шагов n, а затем при числе шагов 2*n. Погрешность вычисления интеграла при числе шагов 2*n определяется по формуле:
Δ<sub>2n</sub> ≈ Θ|I<sub>2n</sub> - I<sub>n</sub>| , где $\theta = 1/3$ для средних прямоугольников

Интеграл вычисляется для последовательных значений числа шагов N = n<sub>0</sub>, 2n<sub>0</sub>, 4n<sub>0</sub>,..., где n<sub>0</sub> — начальное число шагов. Процесс вычислений заканчивается, когда для очередного значения N будет выполнено условие Δ<sub>2n</sub> < ε,  где ε — заданная точность.

**ПОСТАНОВКА ЗАДАЧИ ДЛЯ МНОГОМЕРНОГО ИНТЕГРАЛА**
Задача аналогичная задаче одномерного случая. n-мерная область разбивается на равные части. по каждому измерению.  Выбираем центр каждой части по каждому измерению. Шаг по каждому измерению вычисляется как

$$ h = \frac{b - a}{n}. $$

b и a - конец и начала отрезка, n - число шагов.

Общая формула для d-мерного интеграла:
Δx = (b - a) / n = h

$$I \approx \sum_{i_1=1}^n \sum_{i_2=1}^n \dots \sum_{i_d=1}^n f(x_{i_1}, x_{i_2}, \dots, x_{i_d}) \cdot (\Delta x)^d,$$

где

$$x_{i_k} = a + (i_k - \frac{1}{2}) \cdot \Delta x, \ k = 1, \dots, d.$$

**ОПИСАНИЕ РЕШЕНИЯ**
_[SEQ]_

1. Задаём начальное число шагов n<sub>0 </sub>= 1.
2. Вычисляем интеграл I<sub>n</sub> по формуле средних прямоугольников заданной размерности с начальным число шагов.
3. Удваиваем начальное число шагов и вычисляем уже интеграл для данного числа шагов I<sub>2n</sub>.
4. Находим абсолютную погрешность найденных интегралов.
5. Проверяем правило Рунге
6. Если правило Рунге выполнено, то результатом будет интеграл при удвоенном числе шагов.
7. Иначе I<sub>n</sub> = I<sub>2n</sub> и повторяем процедуру с шага 3.

_[MPI}_
Распределяем равные части отрезка size процессам. Каждый процесс вычислит свою часть интеграла. Полученные результаты собираются. Процесс вычисления приближённого интеграла становится эффективнее.

2024-12-18 16:08 UTC, m1likus reviewed
So do you use boost::mpi or mpi?

2024-12-18 16:08 UTC, m1likus commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
You don't use it in cpp

2024-12-18 16:10 UTC, Kirius257 commented
Hello, Valeria! In my project, I use both libraries: boost and mpi.h

2024-12-18 16:14 UTC, m1likus commented
Why both?

2024-12-18 16:22 UTC, m1likus requested changes

2024-12-18 16:22 UTC, m1likus commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/perf_tests/main.cpp
> +//////
You don't need main in tests.cpp, better to delete it

2024-12-18 16:22 UTC, m1likus commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/src/ops_mpi.cpp
> +kholin_k_multidimensional_integrals_rectangle_mpi::TestMPITaskParallel::~TestMPITaskParallel() { MPI_Type_free(&sz_t); }
Why do you use destructor? In MPI MPI_finalize does this job and in boost everything is controlled in boost::mpi::communicator

2024-12-18 16:22 UTC, m1likus commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/include/ops_mpi.hpp
> +#include <boost/mpi/communicator.hpp>
As long as you use boost only in perf_tests (as I can see), you can move this includes

2024-12-20 11:04 UTC, Kirius257 commented
m1likus, I use both libraries: boost-mpi to support running tests and mpi.h to communicate processes and create custom data types.

2024-12-20 11:13 UTC, Kirius257 commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/src/ops_mpi.cpp
> +kholin_k_multidimensional_integrals_rectangle_mpi::TestMPITaskParallel::~TestMPITaskParallel() { MPI_Type_free(&sz_t); }
I agree with you in part. The point is that we must necessarily specify MPI_Type_free() for custom data types. Let me explain why. First, we allocate resources for storing user data types using special functions (MPI_Type_conntiguous(), MPI_Type_commit()). According to the rules of creating custom data types, we must call MPI_Type_free() to free these resources. boost-mpi and mpi.h cannot release these resources automatically. It is so in the rules of creating custom data types.

https://translated.turbopages.org/proxy_u/en-ru.ru.f0ef8d5a-67655146-acbbe9af-74722d776562/https/stackoverflow.com/questions/64484207/how-to-create-mpi-custom-type-properly

2024-12-20 11:14 UTC, Kirius257 commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/src/ops_mpi.cpp
> +kholin_k_multidimensional_integrals_rectangle_mpi::TestMPITaskParallel::~TestMPITaskParallel() { MPI_Type_free(&sz_t); }
You can read the doc here.

2024-12-20 11:24 UTC, Kirius257 commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/include/ops_mpi.hpp
> +#include <boost/mpi/communicator.hpp>
#include <boost/mpi/communicator.hpp>
the header providing process communication can indeed be moved.

#include <boost/mpi/collectives.hpp>
Unfortunately, it cannot be ported, because it provides collective operations for communicating with processes. The teachers told me on the first assignment that boost-mpi and mpi.h are functionally very similar libraries, i.e. I could theoretically plug in mpi.h instead of boos-mpi, but there is practically no difference, except for the usage interface.

2024-12-20 11:28 UTC, Kirius257 commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/perf_tests/main.cpp
> +//////
Im in process fixing...

2024-12-20 11:28 UTC, Kirius257 commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
Im in process fixing...

2024-12-20 12:11 UTC, NikitaKoshkin requested changes

2024-12-20 12:11 UTC, NikitaKoshkin commented on tasks/seq/kholin_k_multidimensional_integrals_rectangle/src/ops_seq.cpp
> +    // std::cout << "n: " << n << ", I: " << I_2n << ", delta : " << delta << std::endl;
delete comment

2024-12-20 12:11 UTC, NikitaKoshkin commented on tasks/seq/kholin_k_multidimensional_integrals_rectangle/perf_tests/main.cpp
> +// int main(int argc, char **argv) {
you don't need it

2024-12-20 12:11 UTC, NikitaKoshkin commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/src/ops_mpi.cpp
> +  // }
if you don't use it, you can delete it

2024-12-20 12:11 UTC, NikitaKoshkin commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/src/ops_mpi.cpp
> +  run_multistep_scheme_method_rectangle(f, f_values, lower_limits, upper_limits, dim, epsilon);
do you ultimately need this function?

2024-12-20 12:11 UTC, NikitaKoshkin commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/src/ops_mpi.cpp
> +
if you don't use it, you can delete it

2024-12-20 12:11 UTC, NikitaKoshkin commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/src/ops_mpi.cpp
> +       }*/
delete the comment

2024-12-20 12:11 UTC, NikitaKoshkin commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/func_tests/main.cpp
> +  //  ASSERT_NEAR(out_I[0], I, epsilon);
delete comment?

2024-12-20 12:11 UTC, NikitaKoshkin commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/func_tests/main.cpp
> +  /*ASSERT_NEAR(out_I[0], I, epsilon);*/
delete comment

2024-12-20 12:11 UTC, NikitaKoshkin commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/func_tests/main.cpp
> +  /*ASSERT_NEAR(out_I[0], I, epsilon);*/
delete comment

2024-12-20 12:11 UTC, NikitaKoshkin commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/func_tests/main.cpp
> +  /*ASSERT_NEAR(out_I[0], I, epsilon);*/
delete comment

2024-12-20 12:11 UTC, NikitaKoshkin commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/func_tests/main.cpp
> +  /*ASSERT_NEAR(out_I[0], I, epsilon);*/
delete comment

2024-12-20 12:11 UTC, NikitaKoshkin commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/func_tests/main.cpp
> +//  boost::mpi::environment env(argc, argv);
delete main in ur func_tests

2024-12-20 12:43 UTC, Kirius257 commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/func_tests/main.cpp
> +//  boost::mpi::environment env(argc, argv);
fixed

2024-12-20 12:43 UTC, Kirius257 commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/func_tests/main.cpp
> +  /*ASSERT_NEAR(out_I[0], I, epsilon);*/
fixed

2024-12-20 12:44 UTC, Kirius257 commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/func_tests/main.cpp
> +  /*ASSERT_NEAR(out_I[0], I, epsilon);*/
fixed

2024-12-20 12:44 UTC, Kirius257 commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/func_tests/main.cpp
> +  /*ASSERT_NEAR(out_I[0], I, epsilon);*/
fixed

2024-12-20 12:44 UTC, Kirius257 commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/func_tests/main.cpp
> +  /*ASSERT_NEAR(out_I[0], I, epsilon);*/
fixed

2024-12-20 12:44 UTC, Kirius257 commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/src/ops_mpi.cpp
> +       }*/
fixed

2024-12-20 12:44 UTC, Kirius257 commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/src/ops_mpi.cpp
> +
fixed

2024-12-20 12:46 UTC, Kirius257 commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/src/ops_mpi.cpp
> +  run_multistep_scheme_method_rectangle(f, f_values, lower_limits, upper_limits, dim, epsilon);
Of course, it is needed to start the computation of the multivariate integral using a multistep scheme using the rectangle method.

2024-12-20 12:47 UTC, Kirius257 commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/src/ops_mpi.cpp
> +  // }
fixed

2024-12-20 12:47 UTC, Kirius257 commented on tasks/seq/kholin_k_multidimensional_integrals_rectangle/perf_tests/main.cpp
> +// int main(int argc, char **argv) {
fixed

2024-12-20 12:47 UTC, Kirius257 commented on tasks/seq/kholin_k_multidimensional_integrals_rectangle/src/ops_seq.cpp
> +    // std::cout << "n: " << n << ", I: " << I_2n << ", delta : " << delta << std::endl;
fixed

2024-12-20 12:47 UTC, Kirius257 commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/src/ops_mpi.cpp
> +    /*   std::cout << "n: " << n << ", I: " << I_2n << ", delta : " << delta << std::endl;*/
fixed

2024-12-20 12:48 UTC, Kirius257 commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/perf_tests/main.cpp
> +//////
OK!Fixed

2024-12-20 12:48 UTC, Kirius257 commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
fixed!

2024-12-20 14:27 UTC, NikitaKoshkin approved these changes

2024-12-20 16:29 UTC, m1likus approved these changes

2024-12-21 14:30 UTC, aobolensk approved these changes

2024-12-23 01:35 UTC, allnes commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/func_tests/main.cpp
> +TEST(kholin_k_multidimensional_integrals_rectangle_mpi, double_integral_one_var) {
please small range - e.g (0.0000001, 0.0000002)

2024-12-23 01:36 UTC, allnes commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/src/ops_mpi.cpp
> +  double delta = 0;
this parameter need to be changed in tests

2024-12-23 16:00 UTC, Kirius257 commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/func_tests/main.cpp
> +TEST(kholin_k_multidimensional_integrals_rectangle_mpi, double_integral_one_var) {
Fixed! I've added tests with high precision calculations!

2024-12-23 16:01 UTC, Kirius257 commented on tasks/mpi/kholin_k_multidimensional_integrals_rectangle/src/ops_mpi.cpp
> +  double delta = 0;
Fixed! I've parameterised the step

2024-12-25 19:01 UTC, merged