Коньков Иван. Задача 3. Вариант 30. Задача "Повышение контраста полутонового изображения посредством  линейной растяжки гистограммы".
learning-process/ppc-2024-autumn pull request #659
Opened 2024-12-18 15:46 UTC by keshaproger

-

2024-12-18 17:32 UTC, KADCHDR requested changes

2024-12-18 17:32 UTC, KADCHDR commented on tasks/mpi/konkov_i_linear_hist_stretch/include/ops_mpi.hpp
> +  void stretch_pixels();
not used

2024-12-18 17:32 UTC, KADCHDR commented on tasks/mpi/konkov_i_linear_hist_stretch/src/ops_mpi.cpp
> +
not used

2024-12-18 17:32 UTC, KADCHDR commented on tasks/mpi/konkov_i_linear_hist_stretch/perf_tests/main.cpp
> +  }
add initialization

2024-12-18 17:32 UTC, KADCHDR commented on tasks/mpi/konkov_i_linear_hist_stretch/func_tests/main.cpp
> +
add initialization

2024-12-19 05:29 UTC, keshaproger commented on tasks/mpi/konkov_i_linear_hist_stretch/func_tests/main.cpp
> +}
added

2024-12-19 05:30 UTC, keshaproger commented on tasks/mpi/konkov_i_linear_hist_stretch/func_tests/main.cpp
> +
fixed

2024-12-19 05:30 UTC, keshaproger commented on tasks/mpi/konkov_i_linear_hist_stretch/perf_tests/main.cpp
> +  }
fixed

2024-12-19 05:30 UTC, keshaproger commented on tasks/mpi/konkov_i_linear_hist_stretch/src/ops_mpi.cpp
> +
deleted

2024-12-19 05:30 UTC, keshaproger commented on tasks/mpi/konkov_i_linear_hist_stretch/include/ops_mpi.hpp
> +  void stretch_pixels();
deleted

2024-12-19 09:37 UTC, antihype320 approved these changes

2024-12-20 14:48 UTC, KADCHDR approved these changes

2024-12-28 16:45 UTC, aobolensk commented
Please, fix code coverage

2024-12-29 19:42 UTC, closed without merging