Миронов Арсений. Задача 3. Вариант 14. Быстрая сортировка с простым слиянием.
learning-process/ppc-2024-autumn pull request #661
Opened 2024-12-18 16:50 UTC by Napkin-AI

Рекурсивная реализация быстрой сортировки. 
В последовательной версии на входе массив чисел, на выходе - отсортированный массив чисел. 

В параллельной версии исходный массив делиться равномерно на части для каждого процесса и рассылаются самим процессам. Далее каждый процесс сортирует свою часть, отсылает её обратно корневому процессу. Корневой процесс производит простое слияние всех этих чисел.

2024-12-18 19:04 UTC, NikitaKoshkin requested changes

2024-12-18 19:04 UTC, NikitaKoshkin commented on tasks/mpi/mironov_a_quick_sort/perf_tests/main.cpp
> +    const int count = 6291456;
similar remark about size

2024-12-18 19:04 UTC, NikitaKoshkin commented on tasks/mpi/mironov_a_quick_sort/func_tests/main.cpp
> +  // cout << "Epoch 4 " << world.rank() << endl;
u can delete this comments

2024-12-18 19:04 UTC, NikitaKoshkin commented on tasks/mpi/mironov_a_quick_sort/func_tests/main.cpp
> +  // cout << "Epoch 4 " << world.rank() << endl;
u can delete this comments

2024-12-18 19:04 UTC, NikitaKoshkin commented on tasks/mpi/mironov_a_quick_sort/func_tests/main.cpp
> +  // cout << "Epoch 4 " << world.rank() << endl;
u can delete this comments

2024-12-18 19:04 UTC, NikitaKoshkin commented on tasks/mpi/mironov_a_quick_sort/func_tests/main.cpp
> +    vec[i] = gen() % mod;
use negative values?

2024-12-18 19:28 UTC, Napkin-AI commented on tasks/seq/mironov_a_quick_sort/perf_tests/main.cpp
> +  const int count = 10000000;
It is about 5 MB so i dont think it is a problem.
I need to have a large size of array to test the perfomance.

2024-12-19 04:22 UTC, Konstantin-Grudzin requested changes

2024-12-19 04:22 UTC, Konstantin-Grudzin commented on tasks/mpi/mironov_a_quick_sort/include/ops_mpi.hpp
> +  unsigned int delta = 0u;
don't declare zero in class you constructor or declare it in code where you use it

2024-12-19 04:22 UTC, Konstantin-Grudzin commented on tasks/seq/mironov_a_quick_sort/func_tests/main.cpp
> +namespace mironov_a_quick_sort_seq {
It belong to all versions, but i wrote it here: add more size of tests,maybe power of 2. prime number etc.

2024-12-19 04:22 UTC, Konstantin-Grudzin commented on tasks/mpi/mironov_a_quick_sort/src/ops_mpi.cpp
> +#ifdef DEBUG
remove it please

2024-12-19 04:22 UTC, Konstantin-Grudzin commented on tasks/mpi/mironov_a_quick_sort/src/ops_mpi.cpp
> +int* res = nullptr;
why u declare res outside of function, it's very dangerous way of programming nowadays, so maybe can you translate it in function, or mabe like a field of the class?

2024-12-19 06:42 UTC, NikitaKoshkin approved these changes

2024-12-19 11:29 UTC, Konstantin-Grudzin approved these changes

2024-12-22 07:59 UTC, aobolensk requested changes

2024-12-22 07:59 UTC, aobolensk commented on tasks/mpi/mironov_a_quick_sort/include/ops_mpi.hpp
> +std::vector<int> get_random_vector(int sz);
Please, move test functions to the test module

2024-12-22 10:23 UTC, Napkin-AI commented on tasks/mpi/mironov_a_quick_sort/include/ops_mpi.hpp
> +std::vector<int> get_random_vector(int sz);
This has been fixed, could you please check?

2024-12-23 01:37 UTC, allnes commented on tasks/mpi/mironov_a_quick_sort/func_tests/main.cpp
> +  }
please parametrize all constants in tests

2024-12-23 17:58 UTC, Napkin-AI commented on tasks/mpi/mironov_a_quick_sort/func_tests/main.cpp
> +TEST(mironov_a_quick_sort_mpi, Test_wrong_input) {
This has been fixed, could you please check?

2024-12-24 06:33 UTC, aobolensk approved these changes

2024-12-25 19:01 UTC, merged