Черных Андрей. Задача 3. Вариант 9. Вычисление многомерных интегралов с использованием многошаговой схемы (метод Симпсона).
learning-process/ppc-2024-autumn pull request #662
Opened 2024-12-18 18:57 UTC by andreychh

## Общее описание задачи

Задача **вычисления многомерных интегралов методом Симпсона** направлена на численное определение значения интеграла функции нескольких переменных на заданных границах.

## Описание последовательной задачи

1. **Инициализация**: Устанавливаются параметры интегрирования — границы по каждому измерению, точность.
2. **Рекурсивное интегрирование**: Метод Симпсона применяется последовательно по каждому измерению, начиная с последнего.
3. **Проверка сходимости**: Удваивается количество шагов до достижения заданной точности.
4. **Результат**: Возвращается значение многомерного интеграла.

## Описание MPI задачи

1. **Разделение данных**: Процесс 0 делит границы последнего измерения между доступными процессами.
2. **Вычисления**: Каждый процесс вычисляет интеграл по своему сегменту методом Симпсона, рекурсивно обрабатывая оставшиеся измерения.
3. **Сбор результатов**: Частичные результаты собираются и суммируются с помощью операции `reduce`.
4. **Обработка результата**: Процесс 0 сохраняет окончательный результат, остальные процессы завершают работу.

2024-12-19 16:34 UTC, ofuuse approved these changes

2024-12-19 20:55 UTC, artich02 requested changes

2024-12-19 20:55 UTC, artich02 commented on tasks/mpi/chernykh_a_multidimensional_integral_simpson/perf_tests/main.cpp
> +#include <chrono>
The #include <chrono> is not utilized in this file and should be removed

2024-12-19 21:13 UTC, andreychh commented on tasks/mpi/chernykh_a_multidimensional_integral_simpson/perf_tests/main.cpp
> +#include <chrono>
fixed, thanks

2024-12-20 08:24 UTC, artich02 approved these changes

2024-12-22 08:00 UTC, aobolensk approved these changes

2024-12-23 01:40 UTC, allnes commented on tasks/mpi/chernykh_a_multidimensional_integral_simpson/func_tests/main.cpp
> +TEST(chernykh_a_multidimensional_integral_simpson_mpi, linear_2d_integration) {
please add tests with small range - e.g. (0.00000001, 0.00000002)

2024-12-24 04:24 UTC, andreychh commented on tasks/mpi/chernykh_a_multidimensional_integral_simpson/func_tests/main.cpp
> +TEST(chernykh_a_multidimensional_integral_simpson_mpi, linear_2d_integration) {
tests added. thanks

2024-12-25 19:02 UTC, merged