Вавилов Виталий. Задача 3. Вариант 23. Алгоритм Беллмана-Форда
learning-process/ppc-2024-autumn pull request #665
Opened 2024-12-18 20:12 UTC by Vav1L0N

Алгоритм Беллмана-Форда широко используется для поиска кратчайших путей от одной вершины до всех остальных в графе с заданными весами рёбер. Основное преимущество алгоритма заключается в его способности корректно обрабатывать графы с отрицательными весами рёбер. 

Дан направленный граф $G = (V, E)$, где $V$ - множество вершин, $E$ - множество рёбер с весами $w(u, v)$. Требуется найти кратчайшие пути от заданной вершины $s \in V$ до всех остальных вершин графа.
Было реализовано 2 последовательной версии. Первая хранит в массиве исходящую вершину, входящую вершину и вес. Вторая версия заключается в реализации CRS графа. Поскольку использование CRS графа эффективнее, то параллельная версия была реализована с CRS хранением.

Схема последовательного алгоритма:
1) Инициализировать расстояния: $dist[s] = 0$, $dist[v] = \infty$ для всех $v \neq s$.
2) Выполнить $|V| - 1$ итерацию:
    Для каждого ребра $(u, v)$: $dist[v] = \min(dist[v], dist[u] + w(u, v))$.
3) Проверить наличие отрицательных циклов.

Схема параллельного алгоритма:
1) Инициализировать расстояния на каждом процессоре.
2) Выполнить $|V| - 1$ итерацию:
    Локально обновить расстояния для вершин, закреплённых за процессором.
    Обменяться обновлёнными данными с другими процессорами.
3) Проверить наличие отрицательных циклов.

2024-12-18 20:18 UTC, IljarSmirnov commented on tasks/mpi/vavilov_v_bellman_ford/func_tests/main.cpp
> +TEST(vavilov_v_bellman_ford_mpi, ValidInputWithMultiplePaths_seq) {
Add test with random matrix

2024-12-19 20:10 UTC, VladislavPoroshin commented on tasks/mpi/vavilov_v_bellman_ford/include/ops_mpi.hpp
> +#include <string>
extra includes

2024-12-19 20:10 UTC, VladislavPoroshin commented on tasks/seq/vavilov_v_bellman_ford/include/ops_seq.hpp
> +#include <string>
extra includes

2024-12-19 21:39 UTC, Vav1L0N commented on tasks/mpi/vavilov_v_bellman_ford/func_tests/main.cpp
> +TEST(vavilov_v_bellman_ford_mpi, ValidInputWithMultiplePaths_seq) {
added

2024-12-19 21:40 UTC, Vav1L0N commented on tasks/mpi/vavilov_v_bellman_ford/include/ops_mpi.hpp
> +#include <string>
fixed

2024-12-19 21:40 UTC, Vav1L0N commented on tasks/seq/vavilov_v_bellman_ford/include/ops_seq.hpp
> +#include <string>
fixed

2024-12-19 22:27 UTC, VladislavPoroshin approved these changes

2024-12-20 06:35 UTC, IljarSmirnov approved these changes

2024-12-22 08:15 UTC, aobolensk requested changes

2024-12-22 08:15 UTC, aobolensk commented on tasks/mpi/vavilov_v_bellman_ford/func_tests/main.cpp
> +std::vector<int> generate_random_crs_graph(int vertices, int edges_count) {
Please, either wrap with namespace or make it static

2024-12-22 22:37 UTC, Vav1L0N commented on tasks/mpi/vavilov_v_bellman_ford/func_tests/main.cpp
> +std::vector<int> generate_random_crs_graph(int vertices, int edges_count) {
fixed

2024-12-24 06:34 UTC, aobolensk approved these changes

2024-12-25 01:28 UTC, Vav1L0N commented on tasks/mpi/vavilov_v_bellman_ford/func_tests/main.cpp
> +}
fixed

2024-12-25 19:02 UTC, merged