Велиев Эльвин Задача 3 Вариант 29. Выделение ребер на изображении с использованием оператора Собеля
learning-process/ppc-2024-autumn pull request #666
Opened 2024-12-18 21:27 UTC by ev1ven

...

2024-12-23 12:42 UTC, qfrff commented on tasks/mpi/veliev_e_sobel_operator/func_tests/main.cpp
> +  }
optimize random vector generation

2024-12-23 12:42 UTC, qfrff commented on tasks/mpi/veliev_e_sobel_operator/perf_tests/main.cpp
also here

2024-12-23 12:42 UTC, qfrff commented on tasks/seq/veliev_e_sobel_operator/perf_tests/main.cpp
and here

2024-12-23 12:42 UTC, qfrff commented on tasks/seq/veliev_e_sobel_operator/src/ops_seq.cpp
> +  }
replace the result normalization loop with std::transform:

2024-12-23 12:42 UTC, qfrff commented on tasks/mpi/veliev_e_sobel_operator/src/ops_mpi.cpp
and here

2024-12-23 12:50 UTC, Sedova-Olga requested changes

2024-12-23 12:50 UTC, Sedova-Olga commented on tasks/seq/veliev_e_sobel_operator/src/ops_seq.cpp
> +std::vector<double> sobel_filter(const std::vector<double> &image_vector, int h, int w) {
Cyclic normalization is built into the core filter logic, which reduces readability. Create a separate function to normalize the vector.

2024-12-23 19:19 UTC, ev1ven commented on tasks/seq/veliev_e_sobel_operator/src/ops_seq.cpp
> +std::vector<double> sobel_filter(const std::vector<double> &image_vector, int h, int w) {
fixed

2024-12-23 19:20 UTC, ev1ven commented on tasks/mpi/veliev_e_sobel_operator/src/ops_mpi.cpp
fixed

2024-12-23 19:21 UTC, ev1ven commented on tasks/seq/veliev_e_sobel_operator/perf_tests/main.cpp
fixed

2024-12-24 00:43 UTC, qfrff approved these changes

2024-12-24 10:39 UTC, Sedova-Olga approved these changes

2024-12-24 20:07 UTC, aobolensk approved these changes

2024-12-25 19:03 UTC, merged