Морозов Егор. Задача 1. Вариант17.  Нахождение минимальных значений по строкам матрицы
learning-process/ppc-2024-autumn pull request #67
Opened 2024-10-29 18:00 UTC by Egor1dzeN

**_Описание последовательной задачи_**
Создаем вектор размера равным количеству строк матрицы. Проходимся по строкам матрицы и вычисляем максимальное значение и кладем в вектор ответов.
**_Описание параллельной задачи_**
Делим матрицу на несколько частей (в каждой равное количество строк (почти, максимальная разница по количество<=1)). Вычисляем в каждой части минимальное значение по строкам. Собираем все ответы в один общий вектор ответов.

2024-10-31 19:02 UTC, kmichaelk approved these changes

2024-11-03 02:29 UTC, aobolensk requested changes

2024-11-03 02:29 UTC, aobolensk commented on tasks/mpi/morozov_e_min_val_in_rows_matrix/include/ops_mpi.hpp
> +
Please move to the test module

2024-11-03 02:29 UTC, aobolensk commented on tasks/mpi/morozov_e_min_val_in_rows_matrix/func_tests/main.cpp
> +TEST(morozov_e_min_val_in_rows_matrix_MPI, Test_Validation_isFalse) {
Too few tests

2024-11-03 02:29 UTC, aobolensk commented on tasks/mpi/morozov_e_min_val_in_rows_matrix/src/ops_mpi.cpp
> +  broadcast(world, m, 0);
Please move MPI data transfer to ::run()

2024-11-03 17:22 UTC, polikanovv commented on tasks/mpi/morozov_e_min_val_in_rows_matrix/include/ops_mpi.hpp
> +
fixed

2024-11-03 17:23 UTC, Egor1dzeN commented on tasks/mpi/morozov_e_min_val_in_rows_matrix/include/ops_mpi.hpp
> +
fixed

2024-11-03 17:23 UTC, Egor1dzeN commented on tasks/mpi/morozov_e_min_val_in_rows_matrix/func_tests/main.cpp
> +TEST(morozov_e_min_val_in_rows_matrix_MPI, Test_Validation_isFalse) {
fixed, was added

2024-11-03 17:23 UTC, Egor1dzeN commented on tasks/mpi/morozov_e_min_val_in_rows_matrix/src/ops_mpi.cpp
> +  broadcast(world, m, 0);
fixed

2024-11-03 23:45 UTC, aobolensk approved these changes

2024-11-04 00:45 UTC, allnes approved these changes

2024-11-04 05:28 UTC, 22380240 approved these changes

2024-11-04 18:39 UTC, allnes commented
@kmichaelk @22380240 approves is not accepted

2024-11-04 19:50 UTC, sk1er52 commented on tasks/mpi/morozov_e_min_val_in_rows_matrix/func_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
please rewrite this comment or remove

2024-11-04 19:50 UTC, sk1er52 commented on tasks/mpi/morozov_e_min_val_in_rows_matrix/include/ops_mpi.hpp
> +// Copyright 2023 Nesterov Alexander
please rewrite this comment or remove

2024-11-04 19:50 UTC, sk1er52 commented on tasks/mpi/morozov_e_min_val_in_rows_matrix/include/ops_mpi.hpp
> +#include <string>
please remove unused lib

2024-11-04 19:50 UTC, sk1er52 commented on tasks/mpi/morozov_e_min_val_in_rows_matrix/perf_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
please rewrite this comment or remove

2024-11-04 19:50 UTC, sk1er52 commented on tasks/mpi/morozov_e_min_val_in_rows_matrix/src/ops_mpi.cpp
> +#include <string>
please remove unused lib

2024-11-04 19:50 UTC, sk1er52 commented on tasks/mpi/morozov_e_min_val_in_rows_matrix/src/ops_mpi.cpp
> +  //local_matrix_.resize(cur_n, std::vector<int>(m));
remove this comment

2024-11-04 19:50 UTC, sk1er52 commented on tasks/seq/morozov_e_min_val_in_rows_matrix/func_tests/main.cpp
> +  // ASSERT_EQ(v, res2);
remove this comment

2024-11-04 19:50 UTC, sk1er52 commented on tasks/seq/morozov_e_min_val_in_rows_matrix/func_tests/main.cpp
> +  // ASSERT_EQ(v, res2);
remove this comment

2024-11-04 19:50 UTC, sk1er52 commented on tasks/seq/morozov_e_min_val_in_rows_matrix/func_tests/main.cpp
> +  // ASSERT_EQ(v, res2);
remove this comment

2024-11-04 19:50 UTC, sk1er52 commented on tasks/seq/morozov_e_min_val_in_rows_matrix/func_tests/main.cpp
> +  // ASSERT_EQ(v, res2);
remove this comment

2024-11-04 19:50 UTC, sk1er52 commented on tasks/seq/morozov_e_min_val_in_rows_matrix/perf_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
please rewrite this comment or remove

2024-11-04 19:50 UTC, sk1er52 commented on tasks/seq/morozov_e_min_val_in_rows_matrix/src/ops_seq.cpp
> +#include <string>
please remove unused lib

2024-11-04 19:50 UTC, sk1er52 commented on tasks/seq/morozov_e_min_val_in_rows_matrix/src/ops_seq.cpp
> +  // std::cout << "HELLO";
please remove this comment

2024-11-04 20:43 UTC, Egor1dzeN-learn commented on tasks/mpi/morozov_e_min_val_in_rows_matrix/include/ops_mpi.hpp
> +  std::vector<std::vector<int>> matrix_, local_matrix_;
fixed

2024-11-04 20:43 UTC, Egor1dzeN-learn commented on tasks/mpi/morozov_e_min_val_in_rows_matrix/func_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
fixed

2024-11-04 20:43 UTC, Egor1dzeN-learn commented on tasks/mpi/morozov_e_min_val_in_rows_matrix/include/ops_mpi.hpp
> +// Copyright 2023 Nesterov Alexander
fixed

2024-11-04 20:43 UTC, Egor1dzeN-learn commented on tasks/mpi/morozov_e_min_val_in_rows_matrix/include/ops_mpi.hpp
> +#include <string>
fixed

2024-11-04 20:44 UTC, Egor1dzeN-learn commented on tasks/seq/morozov_e_min_val_in_rows_matrix/src/ops_seq.cpp
> +#include <string>
fixed

2024-11-04 20:44 UTC, Egor1dzeN-learn commented on tasks/seq/morozov_e_min_val_in_rows_matrix/perf_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
fixed

2024-11-04 20:44 UTC, Egor1dzeN-learn commented on tasks/seq/morozov_e_min_val_in_rows_matrix/func_tests/main.cpp
> +  // ASSERT_EQ(v, res2);
fixed

2024-11-04 20:44 UTC, Egor1dzeN-learn commented on tasks/seq/morozov_e_min_val_in_rows_matrix/func_tests/main.cpp
> +  // ASSERT_EQ(v, res2);
fixed

2024-11-04 20:44 UTC, Egor1dzeN-learn commented on tasks/mpi/morozov_e_min_val_in_rows_matrix/src/ops_mpi.cpp
> +#include <string>
fixed

2024-11-04 20:44 UTC, Egor1dzeN-learn commented on tasks/mpi/morozov_e_min_val_in_rows_matrix/perf_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
fixed

2024-11-04 20:44 UTC, Egor1dzeN-learn commented on tasks/mpi/morozov_e_min_val_in_rows_matrix/src/ops_mpi.cpp
> +  //local_matrix_.resize(cur_n, std::vector<int>(m));
fixed

2024-11-04 20:45 UTC, Egor1dzeN-learn commented on tasks/seq/morozov_e_min_val_in_rows_matrix/func_tests/main.cpp
> +  // ASSERT_EQ(v, res2);
fixed

2024-11-04 20:45 UTC, Egor1dzeN-learn commented on tasks/seq/morozov_e_min_val_in_rows_matrix/func_tests/main.cpp
> +  // ASSERT_EQ(v, res2);
fixed

2024-11-04 21:21 UTC, vitaliyvoroshilov approved these changes

2024-11-04 21:41 UTC, merged