Дурыничев Дмитрий. Задача 3. Вариант 21. "Поразрядная сортировка для вещественных чисел (тип double)  с четно-нечетным слиянием Бэтчера."
learning-process/ppc-2024-autumn pull request #674
Opened 2024-12-19 09:04 UTC by ofuuse

Алгоритм поразрядной сортировки для вещественных чисел типа double с использованием четно-нечетного слияния Бэтчера работает следующим образом: данные равномерно распределяются между процессами с помощью boost::mpi::scatter, затем происходит обмен элементами и их локальная сортировка согласно алгоритму Бэтчера. После этого отсортированные части объединяются в итоговый отсортированный массив с помощью boost::mpi::gather.

2024-12-19 23:26 UTC, venn2713 approved these changes

2024-12-23 17:24 UTC, tyurinm requested changes

2024-12-23 17:24 UTC, tyurinm commented on tasks/mpi/durynichev_d_radix_batcher/include/ops_mpi.hpp
> +  }
please add a test that will check this situation

2024-12-23 17:24 UTC, tyurinm commented on tasks/seq/durynichev_d_radix_batcher/include/ops_seq.hpp
> +  }
the same

2024-12-23 18:33 UTC, tyurinm approved these changes

2024-12-24 06:34 UTC, aobolensk approved these changes

2024-12-25 19:04 UTC, merged