Тышкевич Артём. Задача 3. Вариант 10. Вычисление многомерных интегралов методом Монте-Карло.
learning-process/ppc-2024-autumn pull request #675
Opened 2024-12-19 09:09 UTC by artich02

Задача вычисления многомерных интегралов методом Монте-Карло решается следующим образом: диапазон интегрирования и заданное количество точек равномерно распределяются между процессами (остаток передается последнему процессу, если необходимо). Каждый процесс генерирует свои точки для оценки интеграла, после чего результаты объединяются с помощью boost::mpi::reduce в нулевой процесс. В нулевом процессе происходит вычисление итогового объема.

2024-12-19 17:05 UTC, korablev-vm requested changes

2024-12-20 17:48 UTC, venn2713 requested changes
Я не сторонник плодить код, поэтому думаю история с отдельным файлом как у второго ревьюера было предложение будет разумным, а так по коду все отлично, перенесите и тегните в ответ когда сделаете и тесты пройдут

2024-12-21 19:39 UTC, venn2713 approved these changes

2024-12-22 08:55 UTC, aobolensk approved these changes

2024-12-23 01:48 UTC, allnes commented on tasks/mpi/tyshkevich_a_monte_carlo/func_tests/main.cpp
> +TEST(tyshkevich_a_monte_carlo_mpi, function_sin_sum_dims_1) {
please add test with small range - e.g. (0.000000001, 0.000000002)

2024-12-24 09:09 UTC, artich02 commented on tasks/mpi/tyshkevich_a_monte_carlo/func_tests/main.cpp
> +TEST(tyshkevich_a_monte_carlo_mpi, function_sin_sum_dims_1) {
@allnes ready

2024-12-25 19:04 UTC, merged