Fix Revert. Созонов Илья. Задача 2. Вариант 19. Метод Гаусса – ленточная горизонтальная схема.
learning-process/ppc-2024-autumn pull request #676
Opened 2024-12-19 11:54 UTC by sozozzya

**Описание последовательной задачи**
Алгоритм состоит из двух этапов: прямой ход и обратный ход.
**Этап 1: Прямой ход**
Для всех строк от i=0 до n-1 (перебираем ведущие строки):
Для всех строк от i=k+1 до n:
Вычисляем множитель: m_ik=A[k,i]/(A[i,i]) ;
Обновляем элементы строки i от j=i до n+1: A[k,j]=A[k,j]− A[i,j]⋅m_ik
После выполнения прямого хода матрица становится верхнетреугольной.
**Этап 2: Обратный ход**
Для всех строк от i=n−1 до 0 (в обратном порядке):
Находим свободный член b= A[i,n];
Находим значение очередной неизвестной, используя предыдущие:
Вычитаем из свободного члена сумму: ∑_(j=i+1)^n▒〖A[i,j]∙x[j]〗 ;
Получившееся выражение делим на диагональный элемент: x[i]=b/(A[i,i]);
После выполнения обратного хода получаем значения всех неизвестных.

**Описание MPI задачи**
Циклически передаем всем процессам строки исходной матрицы.
**Этап 1: Прямой ход**
Перебираем все строки матрицы от 0 до n-1. Если текущая строка принадлежит данному процессу, то рассылаем ее всем процессам. Для оставшихся строк данного процесса обновляем элементы согласно прямому хода последовательного алгоритма.
**Этап 2: Обратный ход**
Для каждого процесса инициализируем вектор неизвестных значением из столбца свободных членном. Перебираем все строки матрицы от n-1 до 0. Если не достигли конца строк в данном процессе, то если текущая строка принадлежит данному процессу, делим неизвестную строки на диагональный элемент. Для оставшихся строк данного процесса находим значения неизвестных согласно обратному ходу последовательного алгоритма.

**Исправление:**
Изначально задал слишком маленькую погрешность, из-за чего в некоторых функциональных тестах значения не совпадали. Во избежание этого, увеличил погрешность вычислений.

2024-12-19 17:42 UTC, ascannel requested changes

2024-12-19 17:42 UTC, ascannel commented on tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/include/ops_mpi.hpp
> +#include <vector>
delete unnecessary includes

2024-12-19 17:42 UTC, ascannel commented on tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/src/ops_mpi.cpp
> +#include <vector>
unnecessary includes

2024-12-19 17:42 UTC, ascannel commented on tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/include/ops_seq.hpp
> +#include <vector>
unnecessary includes

2024-12-19 17:42 UTC, ascannel commented on tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/perf_tests/main.cpp
> +#include <vector>
also here

2024-12-19 17:42 UTC, ascannel commented on tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/src/ops_seq.cpp
> +using namespace std::chrono_literals;
remove this, it is unnecessary

2024-12-19 18:44 UTC, MatveyKurakin commented on tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/src/ops_mpi.cpp
> +    cols = taskData->inputs_count[1];
You must pass the matrix A and vector b to the input.
As I understand it, you are passing a single A|b matrix.
You need to check that it is more than or equal to 2 columns.

2024-12-20 16:39 UTC, ascannel approved these changes

2024-12-20 16:42 UTC, MatveyKurakin approved these changes

2024-12-20 20:24 UTC, aobolensk approved these changes

2024-12-25 19:04 UTC, merged