Гордеева Таисия. Задача 3. Сортировка Шелла с четно-нечетным слиянием Бэтчера
learning-process/ppc-2024-autumn pull request #678
Opened 2024-12-19 13:56 UTC by TayaGordeeva

_Последовательная версия:_

- Работает сортировка Шелла

_Параллельная версия:_

- Вектор данных распределяется п процессам
- Работает для каждого процесса локальная сортировка Шелла
- Происходит четно-нечетное слияние данных 
- В конце данные собираются в один вектор

Результатом последовательной и параллельной версий программы является отсортированный вектор данных

2024-12-20 09:48 UTC, maximchhek commented on tasks/mpi/gordeeva_t_shell_sort_batcher_merge/func_tests/main.cpp
> +TEST(gordeeva_t_shell_sort_batcher_merge_mpi, Shell_sort_Zero_Value) {
Add more tests. Low cod coverage

2024-12-20 09:48 UTC, maximchhek commented on tasks/mpi/gordeeva_t_shell_sort_batcher_merge/func_tests/main.cpp
> +TEST(gordeeva_t_shell_sort_batcher_merge_mpi, Shell_sort_100_with_random) {
Add test with size = 17

2024-12-20 09:48 UTC, maximchhek commented on tasks/mpi/gordeeva_t_shell_sort_batcher_merge/src/ops_mpi.cpp
> +#include <string>
Extra include

2024-12-20 09:48 UTC, maximchhek commented on tasks/seq/gordeeva_t_shell_sort_batcher_merge/src/ops_seq.cpp
> +using namespace std::chrono_literals;
No needs here

2024-12-20 09:55 UTC, Applejack2004 requested changes

2024-12-20 09:55 UTC, Applejack2004 commented on tasks/mpi/gordeeva_t_shell_sort_batcher_merge/perf_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
delete comment pls

2024-12-20 09:55 UTC, Applejack2004 commented on tasks/seq/gordeeva_t_shell_sort_batcher_merge/func_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
delete comment pls

2024-12-20 09:55 UTC, Applejack2004 commented on tasks/mpi/gordeeva_t_shell_sort_batcher_merge/include/ops_mpi.hpp
> +
Extra include

2024-12-20 11:35 UTC, TayaGordeeva commented on tasks/mpi/gordeeva_t_shell_sort_batcher_merge/func_tests/main.cpp
> +TEST(gordeeva_t_shell_sort_batcher_merge_mpi, Shell_sort_Zero_Value) {
add tests

2024-12-20 11:35 UTC, TayaGordeeva commented on tasks/mpi/gordeeva_t_shell_sort_batcher_merge/func_tests/main.cpp
> +TEST(gordeeva_t_shell_sort_batcher_merge_mpi, Shell_sort_100_with_random) {
done

2024-12-20 11:35 UTC, TayaGordeeva commented on tasks/mpi/gordeeva_t_shell_sort_batcher_merge/src/ops_mpi.cpp
> +#include <string>
deleted

2024-12-20 11:36 UTC, TayaGordeeva commented on tasks/seq/gordeeva_t_shell_sort_batcher_merge/src/ops_seq.cpp
> +using namespace std::chrono_literals;
deleted

2024-12-20 11:36 UTC, TayaGordeeva commented on tasks/mpi/gordeeva_t_shell_sort_batcher_merge/perf_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
deleted

2024-12-20 11:36 UTC, TayaGordeeva commented on tasks/seq/gordeeva_t_shell_sort_batcher_merge/func_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
deleted

2024-12-20 11:37 UTC, TayaGordeeva commented on tasks/mpi/gordeeva_t_shell_sort_batcher_merge/include/ops_mpi.hpp
> +
done, deleted

2024-12-20 11:39 UTC, maximchhek approved these changes

2024-12-20 12:21 UTC, Applejack2004 approved these changes

2024-12-22 08:58 UTC, aobolensk approved these changes

2024-12-22 09:02 UTC, aobolensk requested changes

2024-12-22 09:02 UTC, aobolensk commented on tasks/mpi/gordeeva_t_shell_sort_batcher_merge/func_tests/main.cpp
> +
Please, add fixed tests

2024-12-22 09:02 UTC, aobolensk commented on tasks/mpi/gordeeva_t_shell_sort_batcher_merge/src/ops_mpi.cpp
> +std::vector<int> gordeeva_t_shell_sort_batcher_merge_mpi::TestMPITaskSequential::rand_vec(int size, int down, int upp) {
Please, move test functions to the test module

2024-12-23 21:43 UTC, TayaGordeeva commented on tasks/mpi/gordeeva_t_shell_sort_batcher_merge/src/ops_mpi.cpp
> +std::vector<int> gordeeva_t_shell_sort_batcher_merge_mpi::TestMPITaskSequential::rand_vec(int size, int down, int upp) {
fixed

2024-12-23 21:44 UTC, TayaGordeeva commented on tasks/mpi/gordeeva_t_shell_sort_batcher_merge/func_tests/main.cpp
> +
added

2024-12-24 06:36 UTC, aobolensk approved these changes

2024-12-25 19:05 UTC, merged