Харин Матвей. Задача 1. Вариант 25. Подсчет числа предложений в строке.
learning-process/ppc-2024-autumn pull request #68
Opened 2024-10-29 18:50 UTC by mateusxap

**Описание последовательной задачи**

Задача подсчета предложений в тексте выполняется последовательно, символ за символом. Программа анализирует каждый символ текста и увеличивает счетчик предложений, если встречает знак окончания предложения ('.', '?', '!').

**Описание MPI задачи**

Задача подсчета предложений в тексте решается параллельно, разбивая текст на фрагменты и распределяя их между несколькими процессами с помощью MPI. Каждый процесс независимо подсчитывает количество предложений в своем фрагменте, а затем результаты суммируются для получения общего количества предложений во всем тексте.

2024-10-31 16:41 UTC, allnes commented on tasks/mpi/kharin_m_number_of_sentences_mpi/src/ops_mpi.cpp
> +bool CountSentencesParallel::pre_processing() {
please use all mpi functions in run()

2024-10-31 20:06 UTC, mateusxap commented on tasks/mpi/kharin_m_number_of_sentences_mpi/src/ops_mpi.cpp
> +bool CountSentencesParallel::pre_processing() {
fixed

2024-11-01 00:48 UTC, aobolensk requested changes

2024-11-01 00:48 UTC, aobolensk commented on tasks/mpi/kharin_m_number_of_sentences_mpi/func_tests/main.cpp
> +TEST(Parallel_Sentences_Count_MPI, Test_Sentences_with_other_symbols) {
Please, add case on randomized string

2024-11-01 09:30 UTC, mateusxap commented on tasks/mpi/kharin_m_number_of_sentences_mpi/func_tests/main.cpp
> +TEST(Parallel_Sentences_Count_MPI, Test_Sentences_with_other_symbols) {
fixed

2024-11-01 12:23 UTC, DSolo03 approved these changes

2024-11-01 18:57 UTC, ValeraDanger commented on tasks/mpi/kharin_m_number_of_sentences_mpi/src/ops_mpi.cpp
> +#include <algorithm>
Delete unused lib

2024-11-01 18:57 UTC, ValeraDanger commented on tasks/seq/kharin_m_number_of_sentences_seq/src/ops_seq.cpp
> +#include <algorithm>
delete unused lib

2024-11-01 18:59 UTC, mateusxap commented on tasks/mpi/kharin_m_number_of_sentences_mpi/src/ops_mpi.cpp
> +#include <algorithm>
fixed

2024-11-01 18:59 UTC, mateusxap commented on tasks/seq/kharin_m_number_of_sentences_seq/src/ops_seq.cpp
> +#include <algorithm>
fixed

2024-11-02 01:25 UTC, allnes approved these changes

2024-11-02 12:20 UTC, aobolensk approved these changes

2024-11-02 12:20 UTC, merged