Хованский Дмитрий. Задача 2. Вариант 16. Ленточная вертикальная схема.
learning-process/ppc-2024-autumn pull request #680
Opened 2024-12-19 18:22 UTC by Kvoks

исправил реверт #578
ошибка была в моей невнимательности и неверных расстановках i и j в фориках, из-за чего пришлось перелопатить пол кода

2024-12-19 18:45 UTC, StroganovM commented on tasks/mpi/khovansky_d_ribbon_vertical_scheme/func_tests/main.cpp
> +}
delete this

2024-12-19 19:02 UTC, ChastovSlava requested changes
Remove the third test in perf_tests in mpi

2024-12-19 21:09 UTC, ChastovSlava approved these changes

2024-12-19 21:12 UTC, StroganovM approved these changes

2024-12-20 20:25 UTC, aobolensk approved these changes

2024-12-25 19:06 UTC, merged