Морозов Егор. Задача 3. Вариант 5. Умножение разреженных матриц. Элементы типа double.  Формат хранения матрицы – столбцовый (CCS).
learning-process/ppc-2024-autumn pull request #681
Opened 2024-12-19 20:17 UTC by Egor1dzeN-learn

Формат хранения - **столбцовый**:
![image](https://github.com/user-attachments/assets/38a565df-a922-455d-b0bd-e1f29587e189)
Для матрицы выше необходимо хранить 3 массива данных:
**val**: [2,3,1,4] (ненулевые элементы)
**row_indices**: [1,0,2,1] (индексы строк, в которой находится каждый элемент из val)
**col_ptr**: [0,1,3,4] (индексы элементов, с которых начинается столбец)
P.S. также необходимо хранить размеры матрицы в обычном виде, т.к. может быть столбец нулей, соответственно из col_ptr будет неизвестно узнать начальные размеры матрицы, чтобы позже проверить можно ли 2 матрицы умножать (кол-во столбцов первой == кол-ву строк второй)

! В тестах изначально используются матрицы в привычном виде (вектор векторов), а позже он преобразуется в формат CCS - это сделано исключительно для читабельности и проверки правильности работы тестов

Последовательная версия:
1. Преобразуем матрицы из CCS в привычный вид, при этом для удобства 2 матрицу разворачиваем на 90 градусов (для удобства получим, что нужно будет просто умножить строку на строку)
2. Перемножаем каждую строку на столбец, получаем матрицу - ответ

Параллельная версия:
1. Преобразуем матрицы из CCS в привычный вид, при этом для удобства 2 матрицу разворачиваем на 90 градусов (для удобства получим, что нужно будет просто умножить строку на строку)
2. Каждому процессу выдаем 2 вектора, которые ему нужно умножить и вернуть в 0 процесс для формирования матрицы - ответа. Также каждому процессу отправлять место в матрице - ответе, куда нужно будет вставить результат умножения.

2024-12-20 09:27 UTC, KAPUSHA228 requested changes

2024-12-20 09:27 UTC, KAPUSHA228 commented on tasks/mpi/morozov_e_mult_sparse_matrix/func_tests/main.cpp
> +TEST(morozov_e_mult_sparse_matrix, Test_Main2) {
в mpi тестах нужно сравнивать ответы с seq версией

2024-12-20 09:27 UTC, KAPUSHA228 commented on tasks/mpi/morozov_e_mult_sparse_matrix/func_tests/main.cpp
> +TEST(morozov_e_mult_sparse_matrix, Test_Main3) {
не хватает тестов для чисел типа double

2024-12-20 11:22 UTC, KAPUSHA228 requested changes

2024-12-20 11:22 UTC, KAPUSHA228 commented on tasks/mpi/morozov_e_mult_sparse_matrix/func_tests/main.cpp
> +TEST(morozov_e_mult_sparse_matrix, Test_Main1) {
отсутствуют тесты с рандомными значениями

2024-12-20 13:11 UTC, Egor1dzeN-learn commented on tasks/mpi/morozov_e_mult_sparse_matrix/func_tests/main.cpp
> +TEST(morozov_e_mult_sparse_matrix, Test_Main2) {
added

2024-12-20 13:12 UTC, Egor1dzeN-learn commented on tasks/mpi/morozov_e_mult_sparse_matrix/func_tests/main.cpp
> +TEST(morozov_e_mult_sparse_matrix, Test_Main1) {
added

2024-12-20 13:14 UTC, KAPUSHA228 approved these changes

2024-12-20 15:48 UTC, kmichaelk commented on tasks/seq/morozov_e_mult_sparse_matrix/func_tests/main.cpp
> +  taskData->inputs.emplace_back(reinterpret_cast<uint8_t *>(col_indB.data()));
Maybe extract to a separate function?

2024-12-20 18:14 UTC, kmichaelk commented on tasks/mpi/morozov_e_mult_sparse_matrix/perf_tests/main.cpp
> +  std::vector<std::vector<double>> matrixB = {{0, 2, 0}, {1, 0, 3}, {0, 4, 0}};
Use bigger randomly generated matrices, perf results won't be meaningful otherwise

2024-12-21 20:26 UTC, Egor1dzeN-learn commented on tasks/mpi/morozov_e_mult_sparse_matrix/perf_tests/main.cpp
> +  std::vector<std::vector<double>> matrixB = {{0, 2, 0}, {1, 0, 3}, {0, 4, 0}};
fixed

2024-12-21 21:42 UTC, kmichaelk approved these changes

2024-12-22 09:17 UTC, aobolensk requested changes

2024-12-22 09:17 UTC, aobolensk commented on tasks/mpi/morozov_e_mult_sparse_matrix/func_tests/main.cpp
> +      double value = static_cast<double>(rand()) / RAND_MAX;
Please, test negative numbers as well

2024-12-22 09:17 UTC, aobolensk commented on tasks/mpi/morozov_e_mult_sparse_matrix/perf_tests/main.cpp
> +  std::vector<std::vector<double>> matrixB = morozov_e_mult_sparse_matrix::generateRandomMatrix(300, 100);
Are you sure that size is enough for perf tests?

2024-12-22 15:58 UTC, Egor1dzeN-learn commented on tasks/mpi/morozov_e_mult_sparse_matrix/func_tests/main.cpp
> +      double value = static_cast<double>(rand()) / RAND_MAX;
fixed

2024-12-22 15:58 UTC, Egor1dzeN-learn commented on tasks/mpi/morozov_e_mult_sparse_matrix/perf_tests/main.cpp
> +  std::vector<std::vector<double>> matrixB = morozov_e_mult_sparse_matrix::generateRandomMatrix(300, 100);
fixed

2024-12-24 20:07 UTC, aobolensk approved these changes

2024-12-25 19:06 UTC, aobolensk commented
Please, increase code coverage

2024-12-25 19:07 UTC, aobolensk requested changes
Please, increase code coverage

2024-12-28 16:47 UTC, merged