Владимирова Юлия. Задача 3. Вариант 25. Построение выпуклой оболочки – проход Джарвиса.
learning-process/ppc-2024-autumn pull request #686
Opened 2024-12-19 21:18 UTC by VlJulia

2024-12-19 23:33 UTC, VasenkovAA approved these changes

2024-12-19 23:33 UTC, VasenkovAA commented on tasks/mpi/vladimirova_j_jarvis_method/src/ops_mpi.cpp
> +    std::vector<int> send_data = {reg_x, reg_y, B.x, B.y, active};
Может быть лучше вынести это в отдельную функцию?

2024-12-19 23:43 UTC, ChernovaNatalya requested changes

2024-12-19 23:43 UTC, ChernovaNatalya commented on tasks/mpi/vladimirova_j_jarvis_method/src/ops_mpi.cpp
> +#include <vector>
Мне кажется, что ты не используешь все эти библиотеки

2024-12-20 13:52 UTC, VlJulia commented on tasks/mpi/vladimirova_j_jarvis_method/src/ops_mpi.cpp
> +#include <vector>
fixed

2024-12-20 13:52 UTC, VlJulia commented on tasks/mpi/vladimirova_j_jarvis_method/src/ops_mpi.cpp
> +    std::vector<int> send_data = {reg_x, reg_y, B.x, B.y, active};
fixed

2024-12-20 13:53 UTC, ChernovaNatalya approved these changes

2024-12-22 09:26 UTC, aobolensk requested changes

2024-12-22 09:26 UTC, aobolensk commented on tasks/seq/vladimirova_j_jarvis_method/func_tests/test_val.cpp
> +const std::vector<int> data_10_0 = {
Do no use global variables for that. At least wrap them with namespace

2024-12-22 09:26 UTC, aobolensk commented on tasks/mpi/vladimirova_j_jarvis_method/func_tests/main.cpp
> +TEST(Parallel_Operations_MPI, Test_data_10_0) {
Please, add more tests with different sizes

2024-12-22 09:26 UTC, aobolensk commented on tasks/mpi/vladimirova_j_jarvis_method/func_tests/main.cpp
> +
Please, add fixed data tests

2024-12-23 12:31 UTC, VlJulia commented on tasks/mpi/vladimirova_j_jarvis_method/func_tests/main.cpp
> +
fixed

2024-12-23 12:31 UTC, VlJulia commented on tasks/seq/vladimirova_j_jarvis_method/func_tests/test_val.cpp
> +const std::vector<int> data_10_0 = {
fixed

2024-12-24 16:42 UTC, aobolensk commented
Missing description

2024-12-25 14:07 UTC, VlJulia commented
description added @aobolensk

2024-12-25 18:36 UTC, aobolensk approved these changes

2024-12-25 19:08 UTC, merged