Матюнина Александра. Задача 3. Вариант 15. Задача: Быстрая сортировка с четно-нечетным слиянием Бэтчера.
learning-process/ppc-2024-autumn pull request #688
Opened 2024-12-19 22:03 UTC by erty1909

### 1. Последовательная версия (Sequential)
- Использует классическую быструю сортировку (QuickSort) с нерекурсивной реализацией через стек
- Работает с векторами элементов произвольного типа (шаблонная реализация)

### 2. Параллельная версия (MPI)
  1. Разделение исходного массива между процессами
  2. Локальная сортировка на каждом процессе
  3. Параллельное слияние отсортированных частей

### Тестирование
1. Функциональные тесты:
   - Случайный вектор
   - Пустой вектор
   - Вектор с одним элементом
   - Вектор с повторяющимися элементами
   - Тестовый пример из видео

2024-12-20 09:52 UTC, ermolaevv commented on tasks/mpi/matyunina_a_batcher_qsort/include/ops_mpi.hpp
> +  gatherv(world, local_.data(), local_.size(), global_.data(), sizes, 0);
Above, you actually implemented scatterv, so here you can do the same for the uniformity of the code style.

2024-12-20 09:52 UTC, ermolaevv commented on tasks/mpi/matyunina_a_batcher_qsort/include/ops_mpi.hpp
> +      uint32_t i = low;
Please declare variables outside the loop

2024-12-20 15:15 UTC, Yarik3008 commented on tasks/mpi/matyunina_a_batcher_qsort/func_tests/main.cpp
> +    ASSERT_EQ(sorted, out_seq);
Please create function for this and run tests with this function

2024-12-20 15:15 UTC, Yarik3008 commented on tasks/seq/matyunina_a_batcher_qsort/func_tests/main.cpp
> +}
Same

2024-12-20 18:52 UTC, erty1909 commented on tasks/mpi/matyunina_a_batcher_qsort/include/ops_mpi.hpp
> +  gatherv(world, local_.data(), local_.size(), global_.data(), sizes, 0);
fixed

2024-12-20 18:52 UTC, erty1909 commented on tasks/mpi/matyunina_a_batcher_qsort/include/ops_mpi.hpp
> +      uint32_t i = low;
fixed

2024-12-20 18:52 UTC, erty1909 commented on tasks/mpi/matyunina_a_batcher_qsort/func_tests/main.cpp
> +    ASSERT_EQ(sorted, out_seq);
fixed

2024-12-20 18:52 UTC, erty1909 commented on tasks/seq/matyunina_a_batcher_qsort/func_tests/main.cpp
> +}
fixed

2024-12-20 18:58 UTC, ermolaevv approved these changes

2024-12-22 09:34 UTC, aobolensk requested changes

2024-12-22 09:34 UTC, aobolensk commented on tasks/seq/matyunina_a_batcher_qsort/func_tests/main.cpp
> +std::vector<int> generateRandomVector(size_t size, int min_value, int max_value) {
Please, move test functions to the test module

2024-12-22 11:42 UTC, erty1909 commented on tasks/seq/matyunina_a_batcher_qsort/func_tests/main.cpp
> +std::vector<int> generateRandomVector(size_t size, int min_value, int max_value) {
These functions are already in the test module.

2024-12-24 16:47 UTC, aobolensk approved these changes

2024-12-25 19:09 UTC, merged