Кудряшова Ирина. Задача 1. Вариант 9. Скалярное произведение векторов.
learning-process/ppc-2024-autumn pull request #69
Opened 2024-10-29 18:55 UTC by Irina2004-tech

Описание последовательной задачи
Задача заключается в вычислении скалярного произведения двух векторов. Алгоритм поэлементно перемножает соответствующие элементы векторов, а затем суммирует полученные результаты.

Описание MPI задачи
Параллельная задача решается на нескольких процессах MPI. На момент начала рассмотрения задачи мы имеем двухмерный вектор чисел, который содержит два входных вектора. Эти векторы делятся на сегменты в зависимости от количества процессов. Затем каждый сегмент передается соответствующему процессу для дальнейшей обработки. Каждый процесс получает свой сегмент данных, выполняет поэлементное умножение векторов и суммирует результаты. После этого результаты со всех процессов переходят в корневой процесс, где суммируются для получения результата, который и будет ответом.

2024-10-31 16:49 UTC, allnes requested changes

2024-10-31 16:49 UTC, allnes commented on tasks/seq/kudryashova_i_vector_dot_product/src/vectorDotProductSeq.cpp
> +std::vector<int> kudryashova_i_vector_dot_product::GetRandomVector(int size) {
please move this fucntion to test files

2024-10-31 16:49 UTC, allnes commented on tasks/mpi/kudryashova_i_vector_dot_product/src/vectorDotProductMPI.cpp
> +std::vector<int> kudryashova_i_vector_dot_product_mpi::getRandomVector(int size) {
please move this function to test files

2024-11-01 00:51 UTC, aobolensk commented on tasks/mpi/kudryashova_i_vector_dot_product/func_tests/vectorDotProductMPIFuncTests.cpp
> +}
Please add test with empty vectors and vectors of the length 1

2024-11-01 11:56 UTC, ArinaTs reviewed
add a test for unequal vectors

2024-11-01 14:00 UTC, Irina2004-tech commented on tasks/mpi/kudryashova_i_vector_dot_product/func_tests/vectorDotProductMPIFuncTests.cpp
> +}
done

2024-11-01 14:03 UTC, Irina2004-tech commented on tasks/mpi/kudryashova_i_vector_dot_product/src/vectorDotProductMPI.cpp
> +std::vector<int> kudryashova_i_vector_dot_product_mpi::getRandomVector(int size) {
done

2024-11-01 14:03 UTC, Irina2004-tech commented on tasks/seq/kudryashova_i_vector_dot_product/src/vectorDotProductSeq.cpp
> +std::vector<int> kudryashova_i_vector_dot_product::GetRandomVector(int size) {
done

2024-11-01 14:14 UTC, ArinaTs approved these changes
good job

2024-11-01 21:30 UTC, ascannel requested changes

2024-11-01 21:30 UTC, ascannel commented on tasks/mpi/kudryashova_i_vector_dot_product/func_tests/vectorDotProductMPIFuncTests.cpp
> +
add tests that asserts false when trying to dot product empty vectors

2024-11-01 21:30 UTC, ascannel commented on tasks/mpi/kudryashova_i_vector_dot_product/src/vectorDotProductMPI.cpp
> +  result = 0;
remove the initialization of the resulting value to zero; it is set when you specify result{}

2024-11-01 21:30 UTC, ascannel commented on tasks/mpi/kudryashova_i_vector_dot_product/include/vectorDotProductMPI.hpp
> +#include <string>
remove unnecessary includes

2024-11-02 01:27 UTC, allnes approved these changes

2024-11-02 07:09 UTC, ascannel approved these changes

2024-11-02 07:21 UTC, Irina2004-tech commented on tasks/mpi/kudryashova_i_vector_dot_product/func_tests/vectorDotProductMPIFuncTests.cpp
> +}
done

2024-11-02 12:21 UTC, aobolensk approved these changes

2024-11-02 12:21 UTC, merged