Fix Revert "Строганов Михаил Задача 2. Вариант 3. «Обедающие философы»"
learning-process/ppc-2024-autumn pull request #690
Opened 2024-12-20 10:17 UTC by StroganovM

Исправил Perf_tests
Не правильно передавал значение о количестве философов в тестах

2024-12-21 21:59 UTC, ChastovSlava approved these changes

2024-12-21 21:59 UTC, Kvoks approved these changes

2024-12-22 09:30 UTC, aobolensk commented
Please, increase test coverage

2024-12-22 22:14 UTC, kmichaelk requested changes
The behavior does not seem to be correct

![image](https://github.com/user-attachments/assets/c0e4abad-6331-4d4d-882b-adeb806789f2)

2024-12-29 19:42 UTC, closed without merging