Fix revert. Частов Вячеслав. Задача 1. Вариант 24. Подсчёт числа слов в строке.
learning-process/ppc-2024-autumn pull request #692
Opened 2024-12-20 12:12 UTC by ChastovSlava

Исправил ревёрт #252 
Также была обнаружена и исправлена ошибка, из-за которой на 3х процессах падали тесты: words_300, words_1500, words_7500.

2024-12-21 11:01 UTC, Kvoks requested changes
In func_tests in the mpi version of your task there is a test "words_30" whose contents coincide with the test "words_300". Delete it.

2024-12-21 15:57 UTC, Domovenokkk approved these changes

2024-12-21 16:34 UTC, Kvoks approved these changes

2024-12-22 09:29 UTC, aobolensk approved these changes

2024-12-25 19:10 UTC, merged