Test
learning-process/ppc-2024-autumn pull request #694
Opened 2024-12-20 14:39 UTC by KADCHDR

2024-12-26 23:51 UTC, keshaproger requested changes
add the seq version and perf tests for it to compare the results.

2024-12-27 01:26 UTC, antihype320 commented on tasks/mpi/kovalchuk_a_odd_even_megre_sort/func_tests/main.cpp
> +}
add more tests

2024-12-27 01:26 UTC, antihype320 commented on tasks/seq/kovalchuk_a_odd_even_megre_sort/func_tests/main.cpp
> +}
add more tests

2024-12-27 02:31 UTC, KADCHDR commented on tasks/seq/kovalchuk_a_odd_even_megre_sort/func_tests/main.cpp
> +}
Done

2024-12-27 02:31 UTC, KADCHDR commented on tasks/mpi/kovalchuk_a_odd_even_megre_sort/func_tests/main.cpp
> +}
Done

2024-12-28 20:18 UTC, allnes commented
@KADCHDR please don't change not own files

2024-12-28 20:18 UTC, closed without merging