Ермолаев Владислав. Задача 1. Вариант 14. Минимальное значение элементов матрицы.
learning-process/ppc-2024-autumn pull request #7
Opened 2024-10-12 20:06 UTC by ermolaevv

Описание последовательной задачи
- последовательный обход элементов матрицы

Описание MPI задачи
- при считывании данных из taskData матрица преобразуется в развернутую (объединенную в один вектор)
- развернутая матрица делится на сегменты по числу процессов
- каждый сегмент данных отправляется своему процессу
- каждый процесс находит минимальный элемент в сегменте данных
- reduce проходит по всем процессам и выбирает минимальный из промежуточных результатов

2024-10-19 10:47 UTC, AndreySorokin7 requested changes

2024-10-19 10:47 UTC, AndreySorokin7 commented on tasks/mpi/ermolaev_v_min_matrix/include/ops_mpi.hpp
> +  int res{};
The names of private class fields must end with an underscore ( _ ). Make this change in other classes as well.

2024-10-19 13:06 UTC, ermolaevv commented on tasks/mpi/ermolaev_v_min_matrix/include/ops_mpi.hpp
> +  int res{};
fixed

2024-10-20 08:50 UTC, AndreySorokin7 approved these changes

2024-10-22 16:51 UTC, ermolaevv commented on tasks/mpi/ermolaev_v_min_matrix/func_tests/main.cpp
> +  const int count_columns = 50;
Accepted

2024-10-22 18:19 UTC, Kitos87 approved these changes

2024-10-22 23:39 UTC, aobolensk requested changes

2024-10-22 23:39 UTC, aobolensk commented on tasks/seq/ermolaev_v_min_matrix/src/ops_seq.cpp
> +    vec[i] = gen() % 100;
Please validate on negative values as well

2024-10-22 23:39 UTC, aobolensk commented on tasks/mpi/ermolaev_v_min_matrix/perf_tests/main.cpp
> +    count_columns = 2000;
If you use variables on the process 0 only, it makes more sense to initialize them only there

2024-10-23 18:17 UTC, ermolaevv commented on tasks/seq/ermolaev_v_min_matrix/src/ops_seq.cpp
> +    vec[i] = gen() % 100;
fixed

2024-10-23 18:22 UTC, aobolensk approved these changes

2024-10-23 18:22 UTC, ermolaevv commented on tasks/mpi/ermolaev_v_min_matrix/perf_tests/main.cpp
> +    count_columns = 2000;
fixed

2024-10-25 18:02 UTC, allnes approved these changes

2024-10-25 18:02 UTC, merged