Владимирова Юлия. Задача 1. Вариант 13. Максимальное значение элементов матрицы.
learning-process/ppc-2024-autumn pull request #70
Opened 2024-10-29 21:55 UTC by VlJulia

Задача заключается в нахождении максимального значения элементов всей матрицы
_Алгоритм:_
Работаем с развернутой матрицей (вектор). Находим максимальный элемент путем прохождения по вектору и сравнения текущего максимального значения с элементом вектора, если значение элемента больше, то меняем текущее максимальное значение на этот элемент и продолжаем.
**Описание последовательной задачи**
Находим максимальное значение применив алгоритм ко всей матрице сразу.
**Описание последовательной задачи**
Делим развернутую матрицу поровну между процессами, если поровну разделить не удалось, то остаток забирает процесс ранга 0. Все процессы применяют алгоритм к своей части, из полученных значений оставляем максимальное - это и есть решение.

2024-10-30 20:15 UTC, VasenkovAA approved these changes

2024-10-30 20:15 UTC, VasenkovAA commented on tasks/mpi/vladimirova_j_max_of_vector_elements/src/ops_mpi.cpp
> +  res = INT_MIN;
Зачем? Мы же потом в любом случае перезапишем этот параметр. А если будет ошибка вдруг где-то, то могут быть неверные результаты работы теста, разве нет?

2024-10-31 11:41 UTC, ChernovaNatalya approved these changes

2024-10-31 15:46 UTC, VlJulia commented on tasks/mpi/vladimirova_j_max_of_vector_elements/src/ops_mpi.cpp
> +  res = INT_MIN;
fixed

2024-10-31 16:54 UTC, allnes requested changes

2024-10-31 16:54 UTC, allnes commented on tasks/seq/vladimirova_j_max_of_vector_elements/src/ops_seq.cpp
> +    throw "null size";
please use validation, for this case throw is redudantly

2024-10-31 16:54 UTC, allnes commented on tasks/seq/vladimirova_j_max_of_vector_elements/src/ops_seq.cpp
> +    throw "null size";
please use validation, for this case throw is redudantly

2024-10-31 16:54 UTC, allnes commented on tasks/mpi/vladimirova_j_max_of_vector_elements/src/ops_mpi.cpp
> +bool vladimirova_j_max_of_vector_elements_mpi::TestMPITaskParallel::pre_processing() {
please use all mpi functions only in run()

2024-10-31 16:55 UTC, allnes commented
@ChernovaNatalya yours approve is unacceptable

2024-10-31 20:30 UTC, VlJulia commented on tasks/seq/vladimirova_j_max_of_vector_elements/src/ops_seq.cpp
> +    throw "null size";
fixed

2024-10-31 20:31 UTC, VlJulia commented on tasks/seq/vladimirova_j_max_of_vector_elements/src/ops_seq.cpp
> +    throw "null size";
fixed

2024-10-31 20:31 UTC, VlJulia commented on tasks/mpi/vladimirova_j_max_of_vector_elements/src/ops_mpi.cpp
> +bool vladimirova_j_max_of_vector_elements_mpi::TestMPITaskParallel::pre_processing() {
fixed

2024-11-01 13:29 UTC, ArinaTs approved these changes

2024-11-01 13:29 UTC, ArinaTs commented on tasks/mpi/vladimirova_j_max_of_vector_elements/src/ops_mpi.cpp
> +  for (size_t i = 0; i < m.size(); i++) {
For better code readability the loop in `FindMaxElem` can be replaced by a range loop

2024-11-01 16:33 UTC, VlJulia commented on tasks/mpi/vladimirova_j_max_of_vector_elements/src/ops_mpi.cpp
> +  for (size_t i = 0; i < m.size(); i++) {
fixed

2024-11-01 16:39 UTC, VasenkovAA approved these changes
I think it's okay, I'm fine with it.

2024-11-01 17:10 UTC, VlJulia commented on tasks/mpi/vladimirova_j_max_of_vector_elements/src/ops_mpi.cpp
> +    int div_r = columns * rows % world.size();
was fixed, it is now distributed as: 18/5 =>  3, 4, 4,4, 3;     24/5=>  4, 5, 5, 5, 5;    19/6=>  3, 4, 3, 3, 3, 3

2024-11-01 17:56 UTC, aobolensk requested changes

2024-11-01 17:56 UTC, aobolensk commented on tasks/mpi/vladimirova_j_max_of_vector_elements/include/ops_mpi.hpp
> +std::vector<int> CreateVector(size_t size, size_t spread_of_val);
Please, move test functions to test module

2024-11-01 17:56 UTC, aobolensk commented on tasks/mpi/vladimirova_j_max_of_vector_elements/func_tests/main.cpp
> +  const size_t size = 10;
Please, test empty matrix and small matrices (e.g. 1x2, 3x1, 1x1)

2024-11-02 01:26 UTC, allnes approved these changes

2024-11-02 01:43 UTC, aobolensk approved these changes

2024-11-02 12:20 UTC, merged