Плеханов Даниил. Задача 1. Вариант 20. Интегрирование – метод трапеций
learning-process/ppc-2024-autumn pull request #703
Opened 2024-12-20 21:24 UTC by Dxppi

Последовательный вариант(SEQ)

- В последовательной версии используется метод run() класса
TestTaskSequential, который выполняет интегрирование на заданном отрезке
[a, b] используя epsilon для контроля точности.

Основные этапы работы:

Валидация и подготовка данных: Метод validation() проверяет корректность
входных данных, включая размеры массивов и допустимость значения epsilon
.
Подготовка разбиений: Метод pre_processing() определяет количество
разбиений cnt_of_splits, в зависимости от заданной точности epsilon, шаг
разбиения h, который равен (b - a) / cnt_of_splits, и инициализирует
локальные переменные.
Интегрирование: Метод run() вычисляет площадь трапеций на отрезке [a,
b], проходя по разбиениям и суммируя результаты.
Постобработка данных: В методе post_processing() результат
интегрирования сохраняется в выходной массив.
Параллельный вариант (MPI)

- В параллельной версии используется метод run() класса
TestMPITaskParallel, который распределяет интервал между процессами,
основываясь на epsilon для контроля точности.

Основные этапы работы:

Распределение данных: Метод pre_processing() делит отрезок [a, b] между
процессами, определяя локальные переменные для каждого процесса (начало
отрезка local_a и количество разбиений local_cnt_of_splits). Для
синхронизации используется broadcast().
Локальное интегрирование: Каждый процесс в методе run() выполняет
интегрирование на своем участке и накапливает локальный результат
local_res.
Сбор результатов: Метод reduce() суммирует локальные результаты в
переменную res в процессе с рангом 0.
Постобработка данных: В методе post_processing() результат
интегрирования сохраняется в выходной массив, если процесс с рангом 0.

2024-12-25 18:40 UTC, MikasaAkc commented on tasks/mpi/plekhanov_d_trapez_integration/src/ops_mpi.cpp
> +      return false;
Cover the code with a test, please

2024-12-25 19:56 UTC, Dxppi commented on tasks/mpi/plekhanov_d_trapez_integration/src/ops_mpi.cpp
> +      return false;
fixed

2024-12-25 19:57 UTC, MikasaAkc approved these changes

2024-12-25 20:05 UTC, DaniePlekh approved these changes

2024-12-25 20:35 UTC, aobolensk requested changes

2024-12-25 20:35 UTC, aobolensk commented on tasks/mpi/plekhanov_d_trapez_integration/include/ops_mpi.hpp
> +  double static function_square(double x) { return x * x; }
Please, parametrize the function that i being integrated

2024-12-25 20:35 UTC, aobolensk commented on tasks/mpi/plekhanov_d_trapez_integration/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, cnt_of_splits, 0);
Please, move data transfer to ::run() function

2024-12-25 22:02 UTC, Dxppi commented on tasks/mpi/plekhanov_d_trapez_integration/include/ops_mpi.hpp
> +  double static function_square(double x) { return x * x; }
fixed, pls check func tests

2024-12-25 22:03 UTC, Dxppi commented on tasks/mpi/plekhanov_d_trapez_integration/src/ops_mpi.cpp
> +  boost::mpi::broadcast(world, cnt_of_splits, 0);
fixed

2024-12-28 16:50 UTC, aobolensk approved these changes

2024-12-28 16:51 UTC, merged