Ворошилов Виталий. Задача 3. Вариант 12. Многошаговая схема решения двумерных задач глобальной оптимизации. Распараллеливание путём разделения области поиска.
learning-process/ppc-2024-autumn pull request #705
Opened 2024-12-20 23:17 UTC by vitaliyvoroshilov

### Задача:
Найти минимум заданной функции в заданной области поиска при условии выполнения заданных неравенств-ограничений.

![Постановка задачи](https://github.com/user-attachments/assets/22a45fa3-3286-47fe-ab3f-e5db5362328b)

### Метод решения:
В исследуемой области выбираются точки и в них высчитывается минимизируемая функция-критерий а также проверяется выполнение неравенств-ограничений. Если точка подходит под все ограничения и её значение меньше чем значения всех предыдущих подходящих, точка объявляется минимумом. Так, пройдя все точки, получаем приближение минимума функции в заданной области при заданных ограничениях.

2024-12-21 17:58 UTC, hasanyanovk commented on tasks/mpi/voroshilov_v_bivariate_optimization_by_area/include/ops_mpi.hpp
> +  }
`struct` had `public` modifier as a default, and also you don't need to write constructor like this one, you can create objects using universal initialisation: `Point p{3,4}`

2024-12-21 18:02 UTC, hasanyanovk commented on tasks/mpi/voroshilov_v_bivariate_optimization_by_area/src/ops_mpi.cpp
> +    }
Why u use two `if` operators instead of one?

2024-12-22 06:59 UTC, hasanyanovk approved these changes

2024-12-22 16:28 UTC, 1alron requested changes

2024-12-22 21:15 UTC, vitaliyvoroshilov commented on tasks/mpi/voroshilov_v_bivariate_optimization_by_area/func_tests/main.cpp
> +  ASSERT_NEAR(optimum_mpi, 0.0, eps);
Fixed

2024-12-22 21:16 UTC, vitaliyvoroshilov commented on tasks/seq/voroshilov_v_bivariate_optimization_by_area/func_tests/main.cpp
> +  std::vector<int> steps_vec({250, 250});
Added, also added tests where `steps_x != steps_y`

2024-12-22 22:46 UTC, 1alron approved these changes

2024-12-24 16:56 UTC, aobolensk approved these changes

2024-12-25 19:11 UTC, merged