Мурадов Майк. Задача 3. Вариант 5. Умножение разреженных матриц. Элементы типа double.  Формат хранения матрицы – столбцовый (CCS).
learning-process/ppc-2024-autumn pull request #708
Opened 2024-12-21 12:12 UTC by MikeMuradov

В тесте создаются две матрицы `A_` и `B_`, которые синхронизируются на нулевом воркере для обеспечения согласованности данных. Обе матрицы конвертируются в формат CCS (Compressed Column Storage) для последующей обработки. Алгоритм выполняет транспонирование матрицы `A` в формате CCS, после чего производит оптимизированное умножение с матрицей `B`, постепенно заполняя результирующие массивы `res`. Эти массивы возвращаются в тестовую функцию, где результат умножения в формате CCS сверяется с эталонным значением, полученным через умножение исходных плотных матриц, также переведенных в формат CCS.

2024-12-21 13:05 UTC, korablev-vm reviewed
Несмотря на то, что покрытие кода тестами достаточно высоко, рекомендую добавить тесты на валидацию. Это будет и корректнее, и для собственного спокойствия не повредит.

2024-12-22 11:20 UTC, venn2713 requested changes
И для seq тоже самое что в mpi прописал

2024-12-22 11:20 UTC, venn2713 commented on tasks/mpi/muradov_m_matrix_multiply_ccs/func_tests/main.cpp
> +#include "boost/mpi/collectives/broadcast.hpp"
Это лишнее

2024-12-22 11:20 UTC, venn2713 commented on tasks/mpi/muradov_m_matrix_multiply_ccs/func_tests/main.cpp
Нужны тесты на валидацию, а то проверки есть, а теста нету

2024-12-23 17:40 UTC, venn2713 approved these changes

2024-12-24 11:57 UTC, korablev-vm approved these changes

2024-12-24 17:45 UTC, aobolensk approved these changes

2024-12-25 19:12 UTC, merged