Гусейнов Эмил. 3 Задача. Вариант 31. Маркировка компонент на бинарном изображении  (черные области соответствуют объектам, белые – фону).
learning-process/ppc-2024-autumn pull request #709
Opened 2024-12-21 13:04 UTC by emilien-gus

Sequential:
Получаем бинарную матрицу(изображение), где 1 - фон, 0 - объект, инициализируем выходную матрицу единицами. Мы должны получить матрицу, в которой каждый объект(один пиксель 0 или цепочка соседних пикселей 0) имеет свою числовую маркировку, которые начинаются с 2. Так же мы рассматриваем соседей в 6 направлениях(верх, низ, право, лево, нижний левый и верхний правый). Делаем растровое сканирование изображения, создаём и заполняем в процессе таблицу соответствия для маркировок, Далее мы должны соединить все пересекающиеся элементы в матрице (функция fixTable). Потом мы делаем повторный проход по матрице и каждый раз находя маркировки смотрим в таблице, какая родительская маркировка для нее. Если маркировки отличаются, то меняем на ту, которую найдём в таблице. И последний проход необходим для того, чтобы маркировки шли по порядку появления в матрице. 

MPI:
каждому процессу раздаём строки матрицы, процесс обрабатывает свою часть по тому же алгоритму, что и seq версия. Потом мы собираем строки с корневой процесс, так же собираем таблицы с каждого процесса в корневой процесс (таблицы представлены в виде  std::map<int, std::set<int>>). Для сбора таблиц мы делаем её сериализацию в дочернем процессе и десиарилизацию в корневом, потом собираем таблицу полностью. Делаем новый обход промаркированного изображение, снова собирая информацию о соседях(мы ищем граничные случаи). Потом снова делаем fixTable и очередной проход по изображение для исправления граничных случаев. Делаем последний обход для исправлениях порядка маркировок в изображении.

2024-12-21 19:11 UTC, nCUXe commented on tasks/seq/guseynov_e_marking_comps_of_bin_image/func_tests/main.cpp
> +
Add more complex tests in seq and do some tests for validation

2024-12-22 09:54 UTC, pipidaster2004 commented on tasks/seq/guseynov_e_marking_comps_of_bin_image/func_tests/main.cpp
> +void checkNeighbors(const std::vector<int> &matrix, int rows, int cols) {
if you dont use this function then use it somewhere or remove it

2024-12-22 09:54 UTC, pipidaster2004 commented on tasks/mpi/guseynov_e_marking_comps_of_bin_image/src/ops_mpi.cpp
> +
Can you add some comments in code for you functions

2024-12-23 11:25 UTC, nCUXe approved these changes

2024-12-23 16:50 UTC, pipidaster2004 approved these changes

2024-12-24 17:47 UTC, aobolensk requested changes

2024-12-24 17:47 UTC, aobolensk commented on tasks/mpi/guseynov_e_marking_comps_of_bin_image/include/ops_mpi.hpp
> +std::vector<int> getRandomBinImage(int rows, int cols);
Please, move test function to the test module

2024-12-24 17:47 UTC, aobolensk commented on tasks/mpi/guseynov_e_marking_comps_of_bin_image/perf_tests/main.cpp
> +  const int columns = 500;
Please, increase image size for perf tests

2024-12-25 10:12 UTC, emilien-gus commented on tasks/mpi/guseynov_e_marking_comps_of_bin_image/include/ops_mpi.hpp
> +std::vector<int> getRandomBinImage(int rows, int cols);
fixed

2024-12-25 10:13 UTC, emilien-gus commented on tasks/mpi/guseynov_e_marking_comps_of_bin_image/perf_tests/main.cpp
> +  const int columns = 500;
fixed

2024-12-25 18:39 UTC, aobolensk approved these changes

2024-12-25 19:12 UTC, merged