Соловьев Алексей. Задача 1. Вариант 24. Подсчёт числа слов в строке.
learning-process/ppc-2024-autumn pull request #71
Opened 2024-10-30 02:09 UTC by Alexey-Solovev

Описание последовательного алгоритма:
Алгоритм проходит по строке и увеличивает переменную res на единицу, если символ является пробелом или точкой (в случае если слово в строке последнее)

Описание MPI алгоритма:
В нулевом процессе данные распределяются между всем процессами, каждый процесс выполняет подсчёт в отведенном ему участке строки и увеличивает переменную l_res на единицу, если символ является пробелом или точкой, затем все локальные результаты суммируются в переменную res

2024-10-30 17:26 UTC, AnonimUserUS requested changes

2024-10-30 17:26 UTC, AnonimUserUS commented on tasks/mpi/solovev_a_word_count/include/ops_mpi.hpp
> +#include <utility>
Not being used later in code, may be deleted.

2024-10-31 10:08 UTC, AnonimUserUS approved these changes

2024-10-31 23:15 UTC, Alexey-Solovev commented on tasks/mpi/solovev_a_word_count/src/ops_mpi.cpp
> +bool solovev_a_word_count_mpi::TestMPITaskParallel::pre_processing() {
Fixed

2024-11-02 09:59 UTC, YanLendas commented on tasks/mpi/solovev_a_word_count/func_tests/main.cpp
> +TEST(solovev_a_word_count_mpi, test_0_word) {
add this test and test with small string to seq task

2024-11-02 12:31 UTC, aobolensk requested changes

2024-11-02 12:31 UTC, aobolensk commented on tasks/mpi/solovev_a_word_count/src/ops_mpi.cpp
> +    input_[i] = tmp_ptr[i];
Use std::copy

2024-11-02 12:31 UTC, aobolensk commented on tasks/mpi/solovev_a_word_count/src/ops_mpi.cpp
> +    }
You can rewrite the condition to avoid empty "then" block

2024-11-02 12:31 UTC, aobolensk commented on tasks/seq/solovev_a_word_count/src/ops_seq.cpp
> +std::vector<char> create_text(int quan_words) {
Please move all test functions to the test module

2024-11-03 02:26 UTC, aobolensk approved these changes

2024-11-03 05:03 UTC, YanLendas approved these changes

2024-11-04 00:46 UTC, merged