Николаев Роман. Задача 3. Вариант 3. Умножение плотных матриц. Элементы типа double. Алгоритм Штрассена.
learning-process/ppc-2024-autumn pull request #710
Opened 2024-12-21 15:07 UTC by 1alron

# Реализация алгоритма
Алгоритм Штрассена подразумевает работу с квадратными матрицами, что и проверяется в `validation` обоих версий. Аналогично, для реализации алгоритма необходимо, чтобы число строк (и столбцов) матриц равнялось 2 в какой-либо степени, поэтому если входные матрицы этому условию не соответствовали, они приводились к такому виду путём добавления нулевых элементов (до ближайшего числа $2^n$).
## Последовательная версия
Каждая из расширенных матриц разбиваются на четыре подматрицы `A11`, `A12`, `B21`, `B22`, после чего рекурсивно вычисляются 7 подматриц:
- M1 = (A11 + A22) * (B11 + B22)
- M2 = (A21 + A22) * B11
- M3 = A11 * (B12 - B22)
- M4 = A22 * (B21 + B11)
- M5 = (A11 + A12) * (B11 + B22)
- M6 = (A21 - A11) * (B11 + B12)
- M7 = (A12 - A22) * (B21 + B22)
 
Далее результаты собираются в итоговую расширенную матрицу. Возвращается матрица с актуальным размером.

## Параллельная версия
Поскольку в основе алгоритма лежит идея вычисления 7-ми подматриц, реализация предусматривает эффективное использование максимум 7-ми процессов. Процессы с `rank` > 6 обеспечены полезной нагрузкой не будут. Реализовано это с помощью разбития коммуникатора: 
```cpp
if (world.rank() > 6) {
  world.split(1);
  return {};
}

boost::mpi::communicator active_comm = world.split(0);
```
Каждому процессу с помощью `boost::mpi::broadcast` рассылаются расширенные матрицы и новый, расширенный размер, идет описанное выше разбиение на 4 подматрицы. 
После этого наступает момент вычисления подматриц M1..M7. Эти вычисления происходят все так же рекурсивно, используя seq-версию. В зависимости от количества работающих процессов и их значения `rank`, матрицы распределяются между ними в цикле и посредством использования конструкции `switch`. Если работающих процессов < 7, то один процесс может подсчитывать значения элементов нескольких матриц. Значения элементов остальных матриц в конкретном процессе равны 0.0.
В конечном итоге значения всех подматриц редуцируются в root-процессе c помощью вызовов `boost::mpi::reduce`, после чего собирается результат.

2024-12-21 17:03 UTC, Sean0450 commented on tasks/seq/nikolaev_r_strassen_matrix_multiplication_method/src/ops_seq.cpp
> +  std::vector<double> A11(half * half), A12(half * half), A21(half * half), A22(half * half);
You often use half*half expression. You should add a special variable for it.

2024-12-21 17:07 UTC, Sean0450 commented on tasks/seq/nikolaev_r_strassen_matrix_multiplication_method/src/ops_seq.cpp
> +  std::vector<double> B22(half * half);
You often use half*half expression. You should add a special variable for it.

2024-12-21 17:25 UTC, 1alron commented on tasks/seq/nikolaev_r_strassen_matrix_multiplication_method/src/ops_seq.cpp
> +  std::vector<double> B22(half * half);
Reasonable, fixed

2024-12-21 17:29 UTC, hasanyanovk commented on tasks/mpi/nikolaev_r_strassen_matrix_multiplication_method/src/ops_mpi.cpp
> +         taskData->inputs_count[0] == taskData->outputs_count[0];
It would also be nice to check for data availability in `inputs` for example

2024-12-21 17:30 UTC, hasanyanovk commented on tasks/mpi/nikolaev_r_strassen_matrix_multiplication_method/src/ops_mpi.cpp
> +  std::vector<double> B22(half_squared);
May be unite to static arrays?

2024-12-21 17:34 UTC, hasanyanovk commented on tasks/mpi/nikolaev_r_strassen_matrix_multiplication_method/src/ops_mpi.cpp
> +  boost::mpi::reduce(active_comm, M7.data(), M7.size(), M7_global.data(), std::plus<>(), 0);
May be unite to one static array and after that u can use `reduce` in loop for example
Also u can use just `std::plus()` without triangle brackets

2024-12-21 17:37 UTC, hasanyanovk commented on tasks/mpi/nikolaev_r_strassen_matrix_multiplication_method/func_tests/main.cpp
> +#include <mpi/nikolaev_r_strassen_matrix_multiplication_method/include/ops_mpi.hpp>
After fix validation, try to add test with correct `inputs_count` but empty `inputs` for example

2024-12-22 06:57 UTC, hasanyanovk approved these changes

2024-12-22 06:59 UTC, 1alron commented on tasks/mpi/nikolaev_r_strassen_matrix_multiplication_method/src/ops_mpi.cpp
> +         taskData->inputs_count[0] == taskData->outputs_count[0];
Added

2024-12-22 06:59 UTC, 1alron commented on tasks/mpi/nikolaev_r_strassen_matrix_multiplication_method/func_tests/main.cpp
> +#include <mpi/nikolaev_r_strassen_matrix_multiplication_method/include/ops_mpi.hpp>
Added

2024-12-22 07:00 UTC, 1alron commented on tasks/mpi/nikolaev_r_strassen_matrix_multiplication_method/src/ops_mpi.cpp
> +  boost::mpi::reduce(active_comm, M7.data(), M7.size(), M7_global.data(), std::plus<>(), 0);
Changed using vector

2024-12-22 19:15 UTC, Sean0450 approved these changes

2024-12-24 20:20 UTC, aobolensk requested changes

2024-12-24 20:20 UTC, aobolensk commented on tasks/mpi/nikolaev_r_strassen_matrix_multiplication_method/func_tests/main.cpp
> +std::vector<double> generate_random_square_matrix(int n, double minValue = -200.0, double maxValue = 200.0) {
Please, either make functions here static or wrap with namespace

2024-12-24 20:20 UTC, aobolensk commented on tasks/mpi/nikolaev_r_strassen_matrix_multiplication_method/perf_tests/main.cpp
> +  const size_t N = 256;
Increase perf tests size

2024-12-25 08:48 UTC, 1alron commented on tasks/mpi/nikolaev_r_strassen_matrix_multiplication_method/func_tests/main.cpp
> +std::vector<double> generate_random_square_matrix(int n, double minValue = -200.0, double maxValue = 200.0) {
Fixed

2024-12-25 09:13 UTC, 1alron commented on tasks/mpi/nikolaev_r_strassen_matrix_multiplication_method/perf_tests/main.cpp
> +  const size_t N = 256;
@aobolensk My algorithm for defining Strassen's algorithm uses recursive computations on each process. I tried various optimizations locally, tried changing the exponentiation to bitwise operations, tried creating a single vector to minimize MPI synchronization functions, tried changing num_running in benchmarks (I left it equal to 2 in the last version) to at least increase the execution time, but all this gives only minimal gains. My implementation of the algorithm has an acceptable overall execution time for larger data, but the time for work on one specific process exceeds what you allow. This is probably due to the recursive computations. I do not argue that my parallelization scheme may not be the most efficient, but I thought that for a learning project it would be enough, and besides, it is the most intuitive. Of course, as we know, any recursion can be rewritten iteratively, but this will not be called a classic version of Strassen's algorithm. I don't really understand how to globally change the parallelization scheme either, it seems like a rather complicated task, and there won't be enough time before the deadline.
Again, the current tests don't run for 0.002 seconds, there is a clearly visible increase in productivity depending on the addition of processes, it is also clear that the efficiency stops increasing over time, because no more than 7 processes can be used effectively, as stated in the description. Again, it is probably possible to write a version that uses a larger number of processes effectively, but it seems to be beyond the scope of our introductory course.

2024-12-25 18:40 UTC, aobolensk commented
Please, increase code coverage

2024-12-26 11:58 UTC, 1alron commented
![Screenshot 2024-12-26 145801](https://github.com/user-attachments/assets/1aae61f3-ab80-4100-978a-dd6d8f168435)

2024-12-27 20:42 UTC, aobolensk approved these changes

2024-12-27 20:42 UTC, merged