Суворов Дмитрий. Задача 3. Вариант 16. Сортировка Шелла с простым слиянием.
learning-process/ppc-2024-autumn pull request #712
Opened 2024-12-21 16:49 UTC by suvorovDm-1

Задача "Сортировка Шелла с простым слиянием".
Описание последовательного решения задачи:
В последовательной версией в run() для входного вектора с данными выполняется функция shell_sort, которая реализует сортировку Шелла.
Для проверки корректности были реализованы тесты с следующими вариантами векторов данных:
1. Вектор уникальных элементов.
2. Вектор с повторяющимися элементами.
3. Вектор из 1 элемента.
4. Вектор с отрицательными числами.

Описание решения задачи с использованием MPI:
В параллельном решении входной вектор разбивается на части, части рассылаются вызовом scatterv каждому процессу. Каждый процесс для своей локальной части выполняет сортировку Шелла. Затем все части отправляются с помощью gatherv в 0 процесс. Но в результате все отсортированные части просто устанавливаются подряд друг за другом. Для того чтобы получить результативный отсортированный вектор, выполняется merge для частей получившегося вектора. В итоге мы получаем отсортированный вектор исходных данных.
Тесты для параллельной версии аналогичны указанным выше для последовательного решения.

2024-12-22 06:15 UTC, korablev-vm requested changes
1. Уберите из кода chrono_literals (часть с реализацией) 
2. Perf тесты должны проводиться на обратно отсортированном векторе (об этом говорили на одном из занятий) 
3. В функциональные тесты следует добавить:
a) Отсортированный вектор 
b) Обратно отсортированный вектор 
c) Вектор из одинаковых элементов

2024-12-22 14:06 UTC, Torcna requested changes

2024-12-22 14:06 UTC, Torcna commented on tasks/mpi/suvorov_d_shell_with_ord_merge/src/ops_mpi.cpp
> +}
You should expand your validation, my suggestions are to check:
Negative size of the output vector
Negative size of the input vector
Unequal sizes of the input and output vectors

if any of these -> return false

2024-12-23 12:28 UTC, Torcna commented on tasks/mpi/suvorov_d_shell_with_ord_merge/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
do u really need all for these?

2024-12-23 12:28 UTC, Torcna commented on tasks/mpi/suvorov_d_shell_with_ord_merge/func_tests/main.cpp
> +}
please add test for checking your validation.

2024-12-23 14:51 UTC, suvorovDm-1 commented on tasks/mpi/suvorov_d_shell_with_ord_merge/func_tests/main.cpp
> +}
That's a fair point. In the last commit, tests were added for unequal sizes of input and output vectors (inputs_count, outputs_count)

2024-12-23 14:53 UTC, suvorovDm-1 commented on tasks/mpi/suvorov_d_shell_with_ord_merge/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
In fact, there is no need for any of the headers. This issue has been fixed since the last commit.

2024-12-23 15:10 UTC, korablev-vm approved these changes

2024-12-23 15:53 UTC, Torcna approved these changes

2024-12-27 20:49 UTC, aobolensk approved these changes

2024-12-27 20:49 UTC, merged