Федоров Матвей. Задача 3. Вариант 8. Вычисление многомерных интегралов с использованием пошаговой схемы (метод трапеций)
learning-process/ppc-2024-autumn pull request #713
Opened 2024-12-21 17:05 UTC by Matthewsoul124

2024-12-22 09:55 UTC, KAPUSHA228 requested changes

2024-12-22 09:55 UTC, KAPUSHA228 commented on tasks/seq/fyodorov_m_trapezoidal_method_seq/func_tests/main.cpp
> +TEST(Sequential, Test_Sum_10) {
огромное количество комментариев, почистить

2024-12-22 09:55 UTC, KAPUSHA228 commented on tasks/seq/fyodorov_m_trapezoidal_method_seq/src/ops_seq.cpp
> +  return taskData->outputs_count[0] == 1;
некачественная валидация, переделать

2024-12-23 07:55 UTC, Matthewsoul124 commented on tasks/seq/fyodorov_m_trapezoidal_method_seq/func_tests/main.cpp
> +TEST(Sequential, Test_Sum_10) {
done

2024-12-23 07:55 UTC, Matthewsoul124 commented on tasks/seq/fyodorov_m_trapezoidal_method_seq/src/ops_seq.cpp
> +  return taskData->outputs_count[0] == 1;
fixed

2024-12-23 08:01 UTC, KAPUSHA228 approved these changes

2024-12-23 09:30 UTC, petr1core requested changes

2024-12-23 09:30 UTC, petr1core commented on tasks/mpi/fyodorov_m_trapezoidal_method_mpi/func_tests/main.cpp
> +
Есть предложение добавить тест на неуспешную валидацию, чтобы повысилось покрытие. Как я помню, в последовательной версии валидация такая же и тоже не протестирована
![image](https://github.com/user-attachments/assets/e9fdf8f1-ed19-474b-82c2-1b4d2eb3c3ae)

2024-12-23 09:30 UTC, petr1core commented on tasks/mpi/fyodorov_m_trapezoidal_method_mpi/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
Эта функция не используется в программе и к тому же портит покрытие. Можно её убрать без последствий

2024-12-23 13:12 UTC, Matthewsoul124 commented on tasks/mpi/fyodorov_m_trapezoidal_method_mpi/src/ops_mpi.cpp
> +#include <string>
done

2024-12-23 13:13 UTC, Matthewsoul124 commented on tasks/mpi/fyodorov_m_trapezoidal_method_mpi/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
done

2024-12-23 16:08 UTC, Matthewsoul124 commented on tasks/mpi/fyodorov_m_trapezoidal_method_mpi/func_tests/main.cpp
> +
К сожалению, не получится из-за проблем с инициализацией данных во время тестирования. Но идея хорошая, спасибо)

2024-12-23 16:09 UTC, Matthewsoul124 commented on tasks/mpi/fyodorov_m_trapezoidal_method_mpi/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
done

2024-12-24 12:37 UTC, petr1core approved these changes

2024-12-27 19:12 UTC, aobolensk approved these changes

2024-12-27 19:12 UTC, merged