Комшина Дарья. Задача 3. Вариант 20.Поразрядная сортировка для вещественных чисел (тип double) с простым слиянием.
learning-process/ppc-2024-autumn pull request #714
Opened 2024-12-21 17:48 UTC by MikasaAkc

Последовательная задача:
Метод SortDouble сначала разделяет числа на две группы: положительные и отрицательные.
Отрицательные числа инвертируются  для того, чтобы их можно было сортировать как положительные.
Затем для каждой из групп (положительных и инвертированных отрицательных) применяется сортировка методом подсчёта по байтам (функция CountingSort).

Параллельная задача: 
Алгоритм параллельной сортировки с использованием MPI делит данные между процессами, каждый из которых сортирует свою часть, после чего данные собираются и сливаются на процессе с rank == 0, создавая отсортированный массив.

2024-12-25 19:30 UTC, Dxppi commented on tasks/mpi/komshina_d_sort_radius_for_real_numbers_with_simple_merge/func_tests/main.cpp
> +#include <vector>
Add more tests

2024-12-25 19:30 UTC, Dxppi requested changes
add more tests

2024-12-26 18:34 UTC, Dxppi approved these changes

2024-12-26 18:34 UTC, OnePeaceEnjoyer approved these changes

2024-12-26 20:35 UTC, NeeMiyuki requested changes

2024-12-26 20:35 UTC, NeeMiyuki commented on tasks/mpi/komshina_d_sort_radius_for_real_numbers_with_simple_merge/func_tests/main.cpp
> +  std::vector<double> resSeq(count, 0.0);
add a test with an invalid data(or insufficient data) to see if validation can return false

2024-12-26 20:41 UTC, NeeMiyuki requested changes

2024-12-26 20:41 UTC, NeeMiyuki commented on tasks/mpi/komshina_d_sort_radius_for_real_numbers_with_simple_merge/src/ops_mpi.cpp
> +}
in my opinion validation here returns true in any case(correct me if i'm wrong), and so in can't filtrate invalid data inputs

2024-12-29 19:42 UTC, closed without merging