Сидорина Полина. Задача 3. Вариант 32. Построение выпуклой оболочки для компонент бинарного изображения.
learning-process/ppc-2024-autumn pull request #716
Opened 2024-12-21 19:32 UTC by PolinaSidorina

Алгоритм делает проходы по изображению 1 - сверху вниз и слева направо, 2 - снизу вверх и справа налево и маркирует компоненты. Далее алгоритмом Джарвиса находятся выпуклые оболочки для компонент.

В параллельной версии изображение делится на фрагменты, число которых зависит от количества процессов. В каждом процессе происходят описанные ранее действия, а потом результаты отправляются на основной процесс. Там выпуклые оболочки соединяются и получается изображение.

2024-12-22 20:02 UTC, aortemon requested changes

2024-12-22 20:02 UTC, aortemon commented on tasks/mpi/sidorina_p_convex_hull_binary_image_mpi/func_tests/main.cpp
> +                         ::testing::Values(Params(3, 3, {0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0}),
Please, consider case when image has non-equal width and height. Also it would be nice if you add some tests for larger images

2024-12-22 20:02 UTC, aortemon commented on tasks/seq/sidorina_p_convex_hull_binary_image_seq/func_tests/main.cpp
> +                                           Params(3, 3, {0, 1, 1, 0, 0, 0, 0, 0, 1}, {0, 1, 1, 0, 1, 1, 0, 1, 1})));
Same as in `mpi/func_test/main.cpp`

2024-12-22 20:06 UTC, Ksu04 commented
Please add test when the program receives an empty image

2024-12-22 21:55 UTC, PolinaSidorina commented on tasks/mpi/sidorina_p_convex_hull_binary_image_mpi/func_tests/main.cpp
> +                         ::testing::Values(Params(3, 3, {0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0}),
fixed

2024-12-22 21:57 UTC, PolinaSidorina commented on tasks/seq/sidorina_p_convex_hull_binary_image_seq/func_tests/main.cpp
> +                                           Params(3, 3, {0, 1, 1, 0, 0, 0, 0, 0, 1}, {0, 1, 1, 0, 1, 1, 0, 1, 1})));
fixed

2024-12-22 21:58 UTC, aortemon approved these changes

2024-12-23 01:44 UTC, Ksu04 approved these changes

2024-12-27 20:55 UTC, aobolensk commented
Please, increase test coverage

2024-12-28 12:07 UTC, PolinaSidorina commented
@aobolensk I fixed everything I could. That's all that's left.
![3565442b-18bd-44a0-8e4e-45b35a5a8444](https://github.com/user-attachments/assets/141e0824-d1a2-45a2-88cb-e97e32e718aa)

2024-12-28 16:56 UTC, aobolensk requested changes

2024-12-28 16:56 UTC, aobolensk commented on tasks/mpi/sidorina_p_convex_hull_binary_image_mpi/func_tests/main.cpp
> +std::vector<int> gen(int width, int height) {
Please, move test functions to the namespace

2024-12-28 16:56 UTC, aobolensk commented on tasks/seq/sidorina_p_convex_hull_binary_image_seq/func_tests/main.cpp
> +std::vector<int> gen(int width, int height) {
Please, wrap with namespace

2024-12-28 19:35 UTC, PolinaSidorina commented on tasks/mpi/sidorina_p_convex_hull_binary_image_mpi/func_tests/main.cpp
> +std::vector<int> gen(int width, int height) {
Fixed

2024-12-28 19:35 UTC, PolinaSidorina commented on tasks/seq/sidorina_p_convex_hull_binary_image_seq/func_tests/main.cpp
> +std::vector<int> gen(int width, int height) {
Fixed

2024-12-28 20:39 UTC, merged