Межуев Максим Задача 1 Вариант 8 "Нахождение наиболее отличающихся по значению соседних элементов вектора".
learning-process/ppc-2024-autumn pull request #718
Opened 2024-12-21 22:04 UTC by Domovenokkk

Дана последовательность целых чисел (вектор). Необходимо найти два соседних элемента, разница между значениями которых является максимальной по модулю. В результате работы программы нужно вернуть минимальное и максимальное значения из этой пары элементов.

2024-12-21 23:26 UTC, decl1 requested changes

2024-12-21 23:26 UTC, decl1 commented on tasks/mpi/mezhuev_m_most_different_neighbor_elements/src/mpi.cpp
> +  }
its validation

2024-12-21 23:26 UTC, decl1 commented on tasks/mpi/mezhuev_m_most_different_neighbor_elements/src/mpi.cpp
> +  }
its validation

2024-12-21 23:26 UTC, decl1 commented on tasks/mpi/mezhuev_m_most_different_neighbor_elements/src/mpi.cpp
> +  }
its validation

2024-12-21 23:26 UTC, decl1 commented on tasks/mpi/mezhuev_m_most_different_neighbor_elements/src/mpi.cpp
> +  }
its validation

2024-12-21 23:26 UTC, decl1 commented on tasks/mpi/mezhuev_m_most_different_neighbor_elements/src/mpi.cpp
> +  size_t data_size = taskData->inputs_count[0];
its preproccesing

2024-12-22 11:05 UTC, decl1 approved these changes

2024-12-28 20:19 UTC, allnes approved these changes

2024-12-29 19:41 UTC, closed without merging