Моисеев Артём. Задача 3. Вариант 18. Поразрядная сортировка для целых чисел с простым слиянием.
learning-process/ppc-2024-autumn pull request #719
Opened 2024-12-22 10:38 UTC by MoiseevArt

Описание последовательной задачи: 
Алгоритм решает задачу поразрядной сортировки целых чисел с использованием метода сортировки подсчётом для каждой цифры. Все элементы массива делятся на два списка: отрицательные и неотрицательные числа. Сначала сортируются неотрицательные числа по разрядам с использованием сортировки подсчётом, затем — отрицательные числа в обратном порядке. Итоговый массив составляется из отрицательных чисел, за которыми следуют неотрицательные. Алгоритм работает на одном процессе и выполняет все этапы сортировки на локальном массиве данных.

Описание MPI задачи: 
Задача решается с использованием параллельного алгоритма поразрядной сортировки целых чисел с простым слиянием результатов. Код использует MPI для распределения вычислений на несколько процессов. Главный процесс (rank 0) загружает входные данные и делит массив на равные части для всех процессов. Каждый процесс получает свою часть массива и выполняет локальную сортировку с помощью поразрядной сортировки. После того как все процессы завершили сортировку, результаты собираются с помощью операции gatherv, чтобы сформировать отсортированный массив на главном процессе. В конце главный процесс записывает отсортированный массив в taskData->outputs.

2024-12-22 14:15 UTC, kmichaelk requested changes

2024-12-22 14:15 UTC, kmichaelk commented on tasks/mpi/moiseev_a_bitwise_sort_int_with_simple_merg/src/ops_mpi.cpp
> +  std::vector<int> output(arr.size(), 0);
Won't you overwrite it anyway later?

2024-12-22 14:19 UTC, MoiseevArt commented on tasks/mpi/moiseev_a_bitwise_sort_int_with_simple_merg/src/ops_mpi.cpp
> +  std::vector<int> output(arr.size(), 0);
You right, fixed

2024-12-22 14:19 UTC, kmichaelk approved these changes

2024-12-22 16:20 UTC, 22380240 requested changes

2024-12-22 16:20 UTC, 22380240 commented on tasks/mpi/moiseev_a_bitwise_sort_int_with_simple_merg/src/ops_mpi.cpp
> +    mergebuf.reserve(sz);
```suggestion
    std::vector<int> mergebuf(sz);
```

2024-12-22 17:11 UTC, 22380240 approved these changes

2024-12-27 07:56 UTC, Egor1dzeN-learn approved these changes
good job

2024-12-27 21:00 UTC, aobolensk approved these changes

2024-12-27 21:00 UTC, merged