Бессонов Егор. Задача 3. Вариант 8. Вычисление многомерных интегралов с использованием многошаговой схемы (метод трапеций).
learning-process/ppc-2024-autumn pull request #722
Opened 2024-12-22 12:15 UTC by nCUXe

_validation()_
Проверяет входные данные:
- Размерность интегрирования (dim > 0).
- Корректность нижних и верхних границ для каждой размерности.
- Шаги дискретизации (steps_data > 0).

Seq:
_run_

- Делит точки интегрирования между процессами:
  - Каждый процесс обрабатывает свой диапазон индексов.
  - Для каждой точки рассчитывает вес и добавляет вклад в локальный результат.
- Использует boost::mpi::reduce для сбора локальных результатов всех процессов на процессе 0.
- На процессе 0 умножает итоговый результат на произведение шагов.

Многошаговая схема:

- Разбиение интервала на множество шагов вдоль каждой оси.
- Учет всех точек интегрирования.
- Итерации по точкам с накоплением результата.

2024-12-23 16:38 UTC, emilien-gus requested changes

2024-12-23 16:38 UTC, emilien-gus commented on tasks/mpi/bessonov_e_multi_integration_trapezoid_method/src/ops_mpi.cpp
> +
Please use recursion to calculate integrals, rather than nested loops. And do it in seq and mpi versions.

2024-12-24 07:36 UTC, emilien-gus commented on tasks/mpi/bessonov_e_multi_integration_trapezoid_method/func_tests/main.cpp
> +
Please add tests with larger integrals and more complex functions.

2024-12-24 13:35 UTC, pipidaster2004 commented on tasks/mpi/bessonov_e_multi_integration_trapezoid_method/src/ops_mpi.cpp
> +
To optimize the calculation of the weights of the edge points, you can pre-calculate the weights for all possible positions of the points relative to the boundaries (extreme or internal) and store these values as a cache. This will avoid unnecessary calculations during the integration process.

2024-12-24 16:11 UTC, nCUXe commented on tasks/mpi/bessonov_e_multi_integration_trapezoid_method/func_tests/main.cpp
> +
added

2024-12-24 16:13 UTC, emilien-gus approved these changes

2024-12-24 21:37 UTC, pipidaster2004 approved these changes

2024-12-27 21:21 UTC, aobolensk approved these changes

2024-12-27 21:21 UTC, merged