Сорочкин Данила. Задача 3. Вариант 21. Поразрядная сортировка для вещественных чисел с четно-нечетным слиянием Бэтчера.
learning-process/ppc-2024-autumn pull request #724
Opened 2024-12-22 12:51 UTC by dssss12

**Последовательная версия**
В последовательной версии используется алгоритм поразрядной сортировки, который обрабатывает массив чисел с плавающей точкой. На каждом этапе сортировки числа преобразуются в битовый формат, чтобы обеспечить корректное сравнение их разрядов. Сначала массив сортируется по младшему байту, затем по следующему, и так далее до старшего байта. После каждой итерации производится пересортировка, чтобы сохранить порядок. Для упрощения выполнения и интеграции результат копируется в выходной массив.

**Параллельная версия**
Параллельная версия основывается на использовании библиотеки Boost.MPI для распределения работы между несколькими процессами. Исходный массив разделяется на части, которые передаются разным процессам для локальной поразрядной сортировки. После этого слияние данных между процессами выполняется с помощью распределенного четно-нечетного слияния Бэтчера. Процессы обмениваются частями массивов, чтобы упорядочить данные на местах, следуя алгоритму. Отсортированные части затем собираются обратно в корневом процессе, где формируется итоговый результат.

2024-12-22 23:36 UTC, KoshkinMatvey commented on tasks/mpi/sorochkin_d_radix_sort_batcher_merge_double/perf_tests/main.cpp
> +  // Create Perf attributes
replace the timers with the correct one

2024-12-23 17:54 UTC, aortemon approved these changes
Thought-out work and interesting approach. Seems like there's nothing to mend here

2024-12-23 23:02 UTC, dssss12 commented on tasks/mpi/sorochkin_d_radix_sort_batcher_merge_double/perf_tests/main.cpp
> +  // Create Perf attributes
fixed

2024-12-24 07:54 UTC, KoshkinMatvey approved these changes

2024-12-24 21:33 UTC, Gn4ik requested changes

2024-12-24 21:33 UTC, Gn4ik commented on tasks/mpi/sorochkin_d_radix_sort_batcher_merge_double/perf_tests/main.cpp
> +}
The results should be output only in the root process

2024-12-25 10:45 UTC, Gn4ik approved these changes

2024-12-27 21:49 UTC, aobolensk approved these changes

2024-12-27 21:49 UTC, aobolensk approved these changes

2024-12-27 21:49 UTC, merged