Садиков Иван. Задача 3. Вариант 27. Линейная фильтрация изображения (вертикальное разбиение). Ядро Гаусса 3х3
learning-process/ppc-2024-autumn pull request #725
Opened 2024-12-22 12:59 UTC by Sean0450

Последовательное решение:
Для хранения цветов по всем трем каналам (RGB) был реализован класс Point. 
Эталонные значения для проверки правильности алгоритма были получены путем применения к набору пикселей встроенного размытия по Гауссу в python. 
Ядро Гаусса размером 3х3 задается математическим выражением, зависящим от сигма. В моем случае было выбрано сигма равное 1. После этого ядро применяется к каждому пикселю изображения, причем по краям суммируются только те значения, что попадают внутрь матрицы изображения. Таким образом, после фильтрации изображения граничные пиксели становятся кратно меньше, а центральные изменяются минимально, либо вовсе увеличиваются за счет чего и достигается эффект "размытия".
Параллельное решение:
Матрица изображения поступает на вход в транспонированном виде, благодаря чему её легче разделить по столбцам с помощью scatter. Каждому процессу отправляется минимум 3 столбца на обработку. После применения к матрице ядра Гаусса, все столбцы собираются на корневом процессе при помощи gather, а затем обратно транспонируются для сравнения с эталоном. Тесты производительности показали минимум 7-ми кратное превосходство параллельного решения над последовательным.

2024-12-24 00:43 UTC, aortemon requested changes

2024-12-24 00:43 UTC, aortemon commented on tasks/mpi/Sadikov_I_Gauss_Linear_Filtration/func_tests/mpi_func_tests.cpp
> +#include <mpi/Sadikov_I_Gauss_Linear_Filtration/include/ops_mpi.h>
There's no need to include `ops_mpi.h` as global, use `#include "..."`

2024-12-24 00:43 UTC, aortemon commented on tasks/seq/Sadikov_I_Gauss_Linear_Filtration/include/Point.h
> +  bool operator!=(Point value) {
Some of operators are unused. Removing them will increase coverage

2024-12-24 00:43 UTC, aortemon commented on tasks/seq/Sadikov_I_Gauss_Linear_Filtration/func_tests/seq_func_tests.cpp
> +  std::vector<Point<double>> rectImage2Check{
Add test for images of sizes (0, 0) and (7, 13)

2024-12-24 00:43 UTC, aortemon commented on tasks/seq/Sadikov_I_Gauss_Linear_Filtration/func_tests/seq_func_tests.cpp
> +      Point(200.0, 31.0, 92.0),  Point(75.0, 198.0, 0.0),   Point(206.0, 51.0, 106.0),  Point(78.0, 66.0, 129.0),
**[Advice only]** Your tests are pretty much the same, except for input `rectImage2` and output reference `rectImage2Check`. Parametrized tests will shorten the solution and will make it easier to add new tests.

2024-12-25 00:44 UTC, aortemon approved these changes

2024-12-25 06:48 UTC, kalyakinaa commented on tasks/mpi/Sadikov_I_Gauss_Linear_Filtration/func_tests/mpi_func_tests.cpp
> +    ASSERT_EQ(flag, true);
Please compare the answer with the result of the sequential solution. In this case, your codecov will also improve

2024-12-25 16:56 UTC, Sean0450 commented on tasks/mpi/Sadikov_I_Gauss_Linear_Filtration/func_tests/mpi_func_tests.cpp
> +    ASSERT_EQ(flag, true);
Done

2024-12-25 19:19 UTC, kalyakinaa approved these changes

2024-12-26 21:29 UTC, flashkasi approved these changes

2024-12-28 07:52 UTC, aobolensk requested changes

2024-12-28 07:52 UTC, aobolensk commented on tasks/mpi/example/perf_tests/main.cpp
> +  if (world.rank() != 0 && (argc < 2 || argv[1] != std::string("--full-workers-log"))) {
Please, do not modify common code

2024-12-28 07:52 UTC, aobolensk commented on tasks/mpi/Sadikov_I_Gauss_Linear_Filtration/func_tests/mpi_func_tests.cpp
> +
Please, add some random points test as well

2024-12-28 12:07 UTC, Sean0450 commented on tasks/mpi/Sadikov_I_Gauss_Linear_Filtration/func_tests/mpi_func_tests.cpp
> +
Done

2024-12-28 16:57 UTC, aobolensk approved these changes

2024-12-28 16:57 UTC, merged