Плеханов Даниил. Задача 3. Вариант 27. Линейная фильтрация изображения (вертикальное разбиение). Ядро Гаусса 3х3
learning-process/ppc-2024-autumn pull request #727
Opened 2024-12-22 16:40 UTC by Dxppi

seq версия реализует алгоритм вертикального гауссового размытия изображения последовательно. Она выполняет следующие шаги:

Предобработка (pre_processing):
  Проверяет и инициализирует необходимые данные, включая размеры изображения и массив входных данных.
  Копирует данные матрицы из входных данных в внутреннее представление.
Валидация (validation):
  Проверяет корректность входных данных, включая размерность и количество входных и выходных данных.
Выполнение (run):
  Применяет гауссов фильтр к каждому пикселю изображения, игнорируя пиксели на границах.
  Для каждого пикселя рассчитывает взвешенную сумму значений соседних пикселей, используя заранее определенные 
  веса для гауссового размытия.
Постобработка (post_processing):
  Копирует результаты размытия из внутреннего представления в выходные данные.

MPI версия алгоритма гауссового размытия использует вертикальное разбиение для повышения производительности.

pre_processing:

Проверяет порядок выполнения.
Считывает размеры входного изображения и выделяет память для входного и выходного изображений.
validation:

Проверяет корректность входных данных, включая диапазон значений пикселей и размеры входных/выходных данных.
run:

Распределяет данные между процессами.
Каждый процесс применяет гауссов фильтр к своей части изображения.
Собирает результаты обратно на главный процесс.
post_processing:

Копирует обработанные данные в выходные результаты, если процесс главный.

2024-12-25 10:48 UTC, emilien-gus requested changes

2024-12-25 10:48 UTC, emilien-gus commented on tasks/mpi/plekhanov_d_verticalgaus/func_tests/main.cpp
> +
Add validation tests

2024-12-25 12:20 UTC, Dxppi commented on tasks/mpi/plekhanov_d_verticalgaus/func_tests/main.cpp
> +
fixed

2024-12-25 20:16 UTC, OnePeaceEnjoyer approved these changes

2024-12-25 20:46 UTC, emilien-gus approved these changes

2024-12-28 09:23 UTC, aobolensk approved these changes

2024-12-28 09:23 UTC, merged