Поликанов Виталий. Задача 3. Вариант 6. Решение систем линейных уравнений методом сопряженных градиентов.
learning-process/ppc-2024-autumn pull request #732
Opened 2024-12-22 21:19 UTC by polikanovv

Этот код реализует метод сопряженных градиентов для решения систем линейных уравнений с использованием плоского представления матрицы. Основная функция, `ConjugateGradientMethod`, итеративно уточняет решение, вычисляя невязку и корректируя направление поиска с учетом коэффициентов α и β, полученных через скалярные произведения.
**О функциях:**
`MultiplyMatrixByVector`: умножает матрицу на вектор, используя индексацию в плоском массиве
`DotProduct`: вычисляет скалярное произведение
`VectorNorm`: находит норму вектора

2024-12-23 17:08 UTC, venn2713 reviewed
Код отличный, огрех я не увидел, из тестов лишнего не отправляете, все что надо принимаете, максимально структурированное решение в виде пары формул, достаточно легко понять о чем идет речь. Скачал на локали, поигрался со значениями, все работает, вот только ответьте на впорос один, а то не из головы же вы системы брали, и как поняли что такие ответы

2024-12-23 17:08 UTC, venn2713 commented on tasks/mpi/polikanov_v_gradient_method/func_tests/main.cpp
> +  std::vector<double> expected = {0.09090909, 0.63636364};
А как вы получали ожидаемые значения не подскажите?

2024-12-23 17:25 UTC, tyurinm requested changes

2024-12-23 17:25 UTC, tyurinm commented on tasks/mpi/polikanov_v_gradient_method/include/ops_mpi.hpp
> +  }
please add a test that will check this situation

2024-12-23 17:25 UTC, tyurinm commented on tasks/seq/polikanov_v_gradient_method/include/ops_seq.hpp
> +  }
and here

2024-12-23 17:46 UTC, polikanovv commented on tasks/mpi/polikanov_v_gradient_method/func_tests/main.cpp
> +  std::vector<double> expected = {0.09090909, 0.63636364};
Hello, this is a simple python script. To find solutions I used the **SciPy library**. Specifically, for the conjugate gradient method I used the `scipy.sparse.linalg.cg` function.

2024-12-23 17:46 UTC, polikanovv commented on tasks/mpi/polikanov_v_gradient_method/include/ops_mpi.hpp
> +  }
fix it

2024-12-23 17:46 UTC, polikanovv commented on tasks/seq/polikanov_v_gradient_method/include/ops_seq.hpp
> +  }
and it

2024-12-23 18:03 UTC, venn2713 approved these changes

2024-12-23 18:32 UTC, tyurinm approved these changes

2024-12-28 13:14 UTC, aobolensk approved these changes

2024-12-28 13:14 UTC, merged