Милованкин Максим. Задача 3. Вариант 31. Маркировка компонент на бинарном изображении.
learning-process/ppc-2024-autumn pull request #734
Opened 2024-12-23 04:32 UTC by lizardwizardd

2024-12-26 18:13 UTC, Sean0450 commented on tasks/mpi/milovankin_m_component_labeling/func_tests/main.cpp
Add test cases for empty vector, input image filled with zeroes and input image filled with ones

2024-12-26 18:51 UTC, kmichaelk approved these changes

2024-12-26 19:11 UTC, Egor1dzeN-learn requested changes

2024-12-26 19:11 UTC, Egor1dzeN-learn commented on tasks/mpi/milovankin_m_component_labeling/src/component_labeling.cpp
> +}
Add more checks here to make sure that task data is correct

2024-12-26 20:12 UTC, Sean0450 approved these changes

2024-12-27 07:56 UTC, Egor1dzeN-learn approved these changes

2024-12-28 13:15 UTC, aobolensk approved these changes

2024-12-28 13:15 UTC, merged