Лысов Иван. Задача 3. Вариант 2. Умножение плотных матриц. Элементы типа double. Блочная схема, алгоритм Фокса.
learning-process/ppc-2024-autumn pull request #735
Opened 2024-12-23 08:09 UTC by Ivan-Lysov

seq: стандартное умножение матриц
mpi:
<b>Для работы алгоритма требуется \( q^2 \) процессов. Если число доступных процессов больше, лишние процессы остаются неактивными</b>
Алгоритм:
1. **Разделение матриц:**
   - Матрицы \( A \) и \( B \) делятся на блоки размером K х K.

2. **Параллельные вычисления:**
   - Каждый процесс обрабатывает назначенные ему блоки матриц \( A \) и \( B \).
   - На каждом шаге:
     - Блоки \( A \) передаются по строкам решётки процессов.
     - Процессы умножают переданный блок \( A \) на локальный блок \( B \).
     - Блоки \( B \) циклически передаются по столбцам.

3. **Сбор результата:**
   - Локальные результаты процессов собираются для формирования итоговой матрицы \( C \).

2024-12-23 17:26 UTC, Alexey2013 commented on tasks/mpi/lysov_i_matrix_multiplication_Fox_algorithm/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
remove this using, it is not needed

2024-12-23 17:26 UTC, Alexey2013 commented on tasks/mpi/lysov_i_matrix_multiplication_Fox_algorithm/func_tests/main.cpp
> +TEST(lysov_i_matrix_multiplication_Fox_algorithm_mpi, Test_Multiplication) {
Add a test for the 0 by 0 matrix

2024-12-23 19:36 UTC, ascannel requested changes

2024-12-23 19:36 UTC, ascannel commented on tasks/mpi/lysov_i_matrix_multiplication_Fox_algorithm/include/ops_mpi.hpp
> +#include <vector>
remove unnecessary includes

2024-12-23 19:36 UTC, ascannel commented on tasks/mpi/lysov_i_matrix_multiplication_Fox_algorithm/perf_tests/main.cpp
> +    B = getRandomVector(matrix_size * matrix_size);
i think you should create same data for both tests outside of tests code to correctly measure performance

2024-12-23 19:36 UTC, ascannel commented on tasks/mpi/lysov_i_matrix_multiplication_Fox_algorithm/perf_tests/main.cpp
> +    B = getRandomVector(matrix_size * matrix_size);
same. create same data for both tests

2024-12-23 19:36 UTC, ascannel commented on tasks/mpi/lysov_i_matrix_multiplication_Fox_algorithm/src/ops_mpi.cpp
> +    std::cout << "3" << std::endl;
remove debug couts

2024-12-23 19:36 UTC, ascannel commented on tasks/seq/lysov_i_matrix_multiplication_Fox_algorithm/func_tests/main.cpp
> +                                    1 * 1 + 2 * 0 + 3 * 4, 1 * 2 + 2 * 1 + 3 * 0, 1 * 3 + 2 * 0 + 3 * 1};
maybe use just one int?

2024-12-23 19:36 UTC, ascannel commented on tasks/mpi/lysov_i_matrix_multiplication_Fox_algorithm/perf_tests/main.cpp
> +}
why do you have different functions for generating matrix in seq and parallel perfs?

2024-12-24 01:09 UTC, Ivan-Lysov commented on tasks/mpi/lysov_i_matrix_multiplication_Fox_algorithm/src/ops_mpi.cpp
> +using namespace std::chrono_literals;
thanks, I fixed it

2024-12-24 01:09 UTC, Ivan-Lysov commented on tasks/mpi/lysov_i_matrix_multiplication_Fox_algorithm/func_tests/main.cpp
> +TEST(lysov_i_matrix_multiplication_Fox_algorithm_mpi, Test_Multiplication) {
thanks, I fixed it

2024-12-24 01:09 UTC, Ivan-Lysov commented on tasks/mpi/lysov_i_matrix_multiplication_Fox_algorithm/include/ops_mpi.hpp
> +#include <vector>
thanks, I fixed it

2024-12-24 01:10 UTC, Ivan-Lysov commented on tasks/mpi/lysov_i_matrix_multiplication_Fox_algorithm/perf_tests/main.cpp
> +    B = getRandomVector(matrix_size * matrix_size);
thanks you're right, I fixed it

2024-12-24 01:10 UTC, Ivan-Lysov commented on tasks/mpi/lysov_i_matrix_multiplication_Fox_algorithm/perf_tests/main.cpp
> +    B = getRandomVector(matrix_size * matrix_size);
thanks you're right, I fixed it

2024-12-24 01:11 UTC, Ivan-Lysov commented on tasks/mpi/lysov_i_matrix_multiplication_Fox_algorithm/perf_tests/main.cpp
> +}
You're right. I didn't really notice that I have two different generators. Thank you!

2024-12-24 01:11 UTC, Ivan-Lysov commented on tasks/seq/lysov_i_matrix_multiplication_Fox_algorithm/func_tests/main.cpp
> +                                    1 * 1 + 2 * 0 + 3 * 4, 1 * 2 + 2 * 1 + 3 * 0, 1 * 3 + 2 * 0 + 3 * 1};
thanks, I fixed it

2024-12-24 01:50 UTC, ascannel approved these changes

2024-12-24 04:34 UTC, Alexey2013 approved these changes

2024-12-28 13:16 UTC, aobolensk approved these changes

2024-12-28 13:16 UTC, merged