Дормидонтов Егор Задача 3 Вариант 30 "Повышение контраста полутонового изображения посредством  линейной растяжки гистограммы"
learning-process/ppc-2024-autumn pull request #736
Opened 2024-12-23 10:45 UTC by EgorDormidontov

Задача состоит в реализации знакомой с курсов компьютерной графики y =(y-ymin)*255 / (ymax-ymin)

Как устроена Mpi версия.
1.Найти ymin+ вернуть всем потокам.
2.ymax аналогично.
3.Применить и слить в all reduce через sum.

2024-12-24 17:39 UTC, NikitaKoshkin approved these changes

2024-12-24 17:39 UTC, NikitaKoshkin commented on tasks/seq/dormidontov_e_highcontrast/src/egor_src.cpp
> +    reinterpret_cast<int*>(taskData->outputs[0])[i] = res_[i];
use reinterpret_cast once, but in general it would be better to replace it with std::copy

2024-12-24 17:39 UTC, NikitaKoshkin commented on tasks/seq/dormidontov_e_highcontrast/perf_tests/egor_pref_test.cpp
> +std::vector<int> generate_pic(int heigh, int width) {
since you are working with an image, it makes more sense to use an input vector in the range 0-255

2024-12-24 17:39 UTC, NikitaKoshkin commented on tasks/seq/dormidontov_e_highcontrast/func_tests/egor_func_test.cpp
> +  std::vector<int> tmp(heigh * width);
Since you are working with an image, it makes more sense to use an input vector in the range 0 - 255

2024-12-24 17:39 UTC, NikitaKoshkin commented on tasks/mpi/dormidontov_e_highcontrast/src/egor_src.cpp
> +      reinterpret_cast<int*>(taskData->outputs[0])[i] = res_[i];
use std::copy

2024-12-24 17:39 UTC, NikitaKoshkin commented on tasks/mpi/dormidontov_e_highcontrast/src/egor_src.cpp
> +    reinterpret_cast<int*>(taskData->outputs[0])[i] = res_[i];
use std::copy

2024-12-24 17:39 UTC, NikitaKoshkin commented on tasks/mpi/dormidontov_e_highcontrast/perf_tests/egor_perf_test.cpp
> +std::vector<int> generate_pic(int heigh, int width) {
Since you are working with an image, it makes more sense to use an input vector in the range 0 - 255

2024-12-24 17:40 UTC, NikitaKoshkin requested changes

2024-12-24 17:40 UTC, NikitaKoshkin commented on tasks/mpi/dormidontov_e_highcontrast/func_tests/egor_func_tests.cpp
> +TEST(dormidontov_e_highcontrast_mpi, Test_just_test_if_it_finally_works) {
add more big size tests

2024-12-24 18:25 UTC, Konstantin-Grudzin requested changes

2024-12-24 18:25 UTC, Konstantin-Grudzin commented on tasks/seq/dormidontov_e_highcontrast/func_tests/egor_func_test.cpp
> +TEST(dormidontov_e_highcontrast_seq, test_min_values_by_columns_matrix_3x3) {
rs and cs? matrix? I think, you need change this to names that refers to your task

2024-12-24 18:25 UTC, Konstantin-Grudzin commented on tasks/mpi/dormidontov_e_highcontrast/include/egor_include.hpp
> +inline std::vector<int> generate_halftone_pic(int height, int width) {
move this function to test section

2024-12-25 10:03 UTC, Konstantin-Grudzin approved these changes

2024-12-25 11:39 UTC, EgorDormidontov commented on tasks/seq/dormidontov_e_highcontrast/func_tests/egor_func_test.cpp
> +  std::vector<int> tmp(heigh * width);
I`m not able to implement those changes, because I can`t guarantee  that I can check if code works properly.

2024-12-25 11:39 UTC, EgorDormidontov commented on tasks/seq/dormidontov_e_highcontrast/perf_tests/egor_pref_test.cpp
> +std::vector<int> generate_pic(int heigh, int width) {
I`m not able to implement those changes, because I can`t guarantee  that I can check if code works properly.

2024-12-25 11:39 UTC, EgorDormidontov commented on tasks/mpi/dormidontov_e_highcontrast/perf_tests/egor_perf_test.cpp
> +std::vector<int> generate_pic(int heigh, int width) {
I`m not able to implement those changes, because I can`t guarantee  that I can check if code works properly.

2024-12-25 11:54 UTC, NikitaKoshkin approved these changes

2024-12-28 13:16 UTC, aobolensk approved these changes

2024-12-28 13:17 UTC, merged