Резанцева Анастасия. Задача 3. Вариант 7. Вычисление многомерных интегралов методом прямоугольников.
learning-process/ppc-2024-autumn pull request #737
Opened 2024-12-23 15:04 UTC by AnastasiaRezantseva

**Вычисление многомерных интегралов методом прямоугольников (метод Римана)**
Разбиваем область интегрирования на подотрезки, в которых вычисляем значения функции в центрах этих подотрезков и суммируем площади прямоугольников, чтобы получить приближенную площадь под кривой.

Каждый процесс вычисляет свою часть интеграла, обрабатывая определенное количество точек, и суммирует результаты в локальную переменную. Результаты всех процессов объединяются с помощью reduce, для получения общего результата интегрирования.

2024-12-23 15:07 UTC, Tanya-Yasakova commented on tasks/mpi/rezantseva_a_rectangle_method/func_tests/main_rez_a.cpp
> +TEST(rezantseva_a_rectangle_method_mpi, check_1_dimension_integral) {
add tests with log and cos

2024-12-23 15:07 UTC, Tanya-Yasakova commented on tasks/seq/rezantseva_a_rectangle_method/func_tests/main_rez_a.cpp
> +TEST(rezantseva_a_rectangle_method_seq, check_1_dimension_integral) {
add tests with log and cos

2024-12-23 17:25 UTC, m1likus requested changes

2024-12-23 17:25 UTC, m1likus commented on tasks/mpi/rezantseva_a_rectangle_method/src/ops_mpi_rez_a.cpp
> +
You can use only one check_integration_bounds for both parallel and sequential

2024-12-23 20:32 UTC, Tanya-Yasakova approved these changes

2024-12-24 06:08 UTC, m1likus approved these changes

2024-12-28 13:21 UTC, aobolensk approved these changes

2024-12-28 13:21 UTC, merged