Фролова Елизавета Задача 3 Вариант 9 Вычисление многомерных интегралов с использованием многошаговой схемы (метод Симпсона)
learning-process/ppc-2024-autumn pull request #740
Opened 2024-12-23 20:49 UTC by ElizavetaFrolova

Последовательная версия (seq)
В последовательной задаче используется обычный метод Симпсона для численного интегрирования функции. Этот метод основывается на аппроксимации кривой, описывающей функцию, с помощью парабол. 
Принцип работы метода заключается в следующем:
1. Разбиение интервала: Сначала отрезок интегрирования разбивается на равные подинтервалы.(количество подинтервалов должно быть четным.)
2. На каждом подинтервале выбираются узловые точки, где будет вычисляться значение функции.
3. Для каждой из узловых точек вычисляются значения функции, которые затем используются для формирования параболической аппроксимации.
4. Суммирование: Метод Симпсона использует взвешенную сумму значений функции в этих узловых точках. 

Параллельная версия 
Реализовано численное интегрирование методом Симпсона с использованием параллельных вычислений. 
Выполняется:
1. Разбиение интервала: Происходит разбиение интервала интегрирования на подинтервалы. Каждый процесс получает свою часть интервала для вычисления.
2. Вычисление локальных интегралов: Каждый процесс вычисляет локальный интеграл на своем отрезке с помощью метода Симпсона.
5. Сбор результатов: Результаты локальных интегралов собираются (reduce) на процессе с рангом 0, который суммирует их для получения общего результата.

2024-12-24 21:48 UTC, Alexey2013 commented on tasks/mpi/frolova_e_Simpson_method/include/ops_mpi_frolova_Simpson.hpp
> +double ProductOfSquaresOfXandYandZ(const std::vector<double>& point);
remove these functions to tests

2024-12-24 21:48 UTC, Alexey2013 commented on tasks/seq/frolova_e_Simpson_method/include/ops_seq_frolova_Simpson.hpp
> +double ProductOfSquaresOfXandYandZ(const std::vector<double>& point);
same

2024-12-24 22:05 UTC, Alexey2013 commented on tasks/mpi/frolova_e_Simpson_method/include/ops_mpi_frolova_Simpson.hpp
> +#include <boost/serialization/vector.hpp>
these lines are not needed

2024-12-25 08:32 UTC, Alexey2013 approved these changes

2024-12-25 15:35 UTC, MaxikGuy requested changes

2024-12-25 15:35 UTC, MaxikGuy commented on tasks/mpi/frolova_e_Simpson_method/func_tests/main_frolova_Simpson.cpp
> +TEST(frolova_e_Simpson_method_mpi, one_dimensional_integral_squaresOfX_test) {
Hi! Please add validation tests (cases where validation retutns `false`).

2024-12-25 17:27 UTC, MaxikGuy approved these changes

2024-12-28 20:23 UTC, allnes commented on tasks/mpi/frolova_e_Simpson_method/src/ops_mpi_frolova_Simpson.cpp
> +        }
please calculate it in different process

2024-12-29 07:28 UTC, ElizavetaFrolova commented on tasks/mpi/frolova_e_Simpson_method/src/ops_mpi_frolova_Simpson.cpp
> +        }
fixed

2024-12-29 11:46 UTC, allnes approved these changes

2024-12-29 11:46 UTC, merged