Вершинина Александра. Задача 3. Вариант 1. Умножение плотных матриц. Элементы типа double. Блочная схема, алгоритм Кэннона
learning-process/ppc-2024-autumn pull request #746
Opened 2024-12-24 12:47 UTC by sanya2905

**seq**: реализован класс TMatrix, с помощью которого строки или столбцы матриц виртуально сдвигаются в соответствии с алгоритмом, ответ записывается в результирующую матрицу.

**mpi**: из активных процессов формируется декартова топология, корневой процесс рассылает блоки данных каждому процессу и происходит умножение локальных блоков, затем производится циклический сдвиг строк или столбцов матриц, ответ собирается корневым процессом и записывается в результирующую матрицу.

2024-12-24 15:05 UTC, ermilovad requested changes

2024-12-24 15:05 UTC, ermilovad commented on tasks/seq/vershinina_a_cannons_algorithm/func_tests/main.cpp
> +
res_c уже создается в preprocessing, эта строка не нужна в тестах

2024-12-24 18:43 UTC, odincovm requested changes
убери res_c в перф тестах и запустите их на больших данных

2024-12-24 19:41 UTC, ermilovad approved these changes

2024-12-24 20:39 UTC, odincovm approved these changes

2024-12-28 17:16 UTC, aobolensk commented
Please, increase code coverage

2024-12-28 20:25 UTC, sanya2905 commented
> Please, increase code coverage

fixed

2024-12-28 23:17 UTC, merged