Бурыкин Михаил. Задача 3. Вариант 11. Алгоритм глобального поиска (Стронгина) для одномерных задач оптимизации. Распараллеливание по характеристикам.
learning-process/ppc-2024-autumn pull request #750
Opened 2024-12-24 20:24 UTC by WholeHorse

Последовательный алгоритм:
Работает на одном потоке, где точки интервала обрабатываются одна за другой. На каждой итерации вычисляется значение функции в точках, проверяется сходимость по критерию ϵ, и определяется новая точка для исследования. Это продолжается до достижения заданной точности.

Параллельный алгоритм:
Использует несколько процессов с помощью MPI. Интервал делится между процессами, которые параллельно вычисляют значения функции и обновляют параметры L (параметр Липшица). Главный процесс собирает результаты, выбирает новый интервал и передаёт данные обратно процессам.

2024-12-25 20:11 UTC, ovVrLFg8ks requested changes

2024-12-25 20:11 UTC, ovVrLFg8ks commented on tasks/mpi/burykin_m_strongin/src/ops_mpi.cpp
> +  }
add test for inverted x₀ and x₁ to improve code coverage here
or use sort early like in mpi version

2024-12-25 20:11 UTC, ovVrLFg8ks commented on tasks/seq/burykin_m_strongin/src/ops_seq.cpp
> +  }
add test for inverted x₀ and x₁ to improve code coverage here too

2024-12-26 06:59 UTC, ofuuse requested changes

2024-12-26 06:59 UTC, ofuuse commented on tasks/mpi/burykin_m_strongin/src/ops_mpi.cpp
> +#include <string>
is it used?

2024-12-26 06:59 UTC, ofuuse commented on tasks/mpi/burykin_m_strongin/src/ops_mpi.cpp
> +#include <vector>
clean up includes to make code more readable

2024-12-26 06:59 UTC, ofuuse commented on tasks/mpi/burykin_m_strongin/include/ops_mpi.hpp
> +#include <string>
is it used?

2024-12-26 11:45 UTC, WholeHorse commented on tasks/mpi/burykin_m_strongin/src/ops_mpi.cpp
> +  }
added

2024-12-26 11:45 UTC, WholeHorse commented on tasks/seq/burykin_m_strongin/src/ops_seq.cpp
> +  }
added

2024-12-26 11:45 UTC, WholeHorse commented on tasks/mpi/burykin_m_strongin/src/ops_mpi.cpp
> +#include <string>
fixed

2024-12-26 11:45 UTC, WholeHorse commented on tasks/mpi/burykin_m_strongin/src/ops_mpi.cpp
> +#include <vector>
fixed

2024-12-26 11:45 UTC, WholeHorse commented on tasks/mpi/burykin_m_strongin/include/ops_mpi.hpp
> +#include <string>
fixed

2024-12-26 11:58 UTC, ovVrLFg8ks approved these changes

2024-12-26 12:08 UTC, ofuuse approved these changes

2024-12-28 17:43 UTC, aobolensk requested changes

2024-12-28 17:43 UTC, aobolensk commented on tasks/mpi/burykin_m_strongin/func_tests/main.cpp
> +
Please, add more tests

2024-12-28 17:43 UTC, aobolensk commented on tasks/mpi/burykin_m_strongin/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
Please, move test functions to the test module

2024-12-28 20:45 UTC, aobolensk approved these changes

2024-12-28 21:34 UTC, merged