Кошкин Матвей. Задача 3. Вариант 29. Выделение ребер на изображении с использованием оператора Собеля.
learning-process/ppc-2024-autumn pull request #753
Opened 2024-12-24 21:48 UTC by KoshkinMatvey

SEQ (последовательная реализация): Алгоритм выполняется на одном процессе, используя свертки с ядрами Собеля для вычисления градиентов изображения. Реализованы этапы: подготовка данных, вычисления, проверка и запись результата.

MPI (параллельная реализация): Изображение делится на блоки и обрабатывается несколькими процессами с использованием Boost.MPI. Главный процесс распределяет данные, собирает результаты, а вычисления выполняются локально на каждом процессе с учетом перекрытий.

2024-12-25 22:02 UTC, dssss12 commented on tasks/mpi/koshkin_m_sobel/src/ops_mpi.cpp
> +  return kernel[0][0] * img[(i - 1) * height + (j - 1)] + kernel[0][1] * img[(i - 1) * height + j] +
turn clang-format off here to place each expression on a line to make it more readable

2024-12-25 22:02 UTC, dssss12 commented on tasks/seq/koshkin_m_sobel/src/ops_seq.cpp
> +  return kernel[0][0] * img[(i - 1) * height + (j - 1)] + kernel[0][1] * img[(i - 1) * height + j] +
and this

2024-12-25 22:09 UTC, flashkasi requested changes

2024-12-25 22:09 UTC, flashkasi commented on tasks/mpi/koshkin_m_sobel/src/ops_mpi.cpp
> +    image.resize((width + 2) * (height + 2));
You can use `const int padding = 2`  for resizing image to make your approach more scaleable

2024-12-25 22:09 UTC, flashkasi commented on tasks/mpi/koshkin_m_sobel/include/ops_mpi.hpp
> +}
Seems like it's debug function. You should remove it, it influences on coverage

2024-12-25 22:56 UTC, KoshkinMatvey commented on tasks/mpi/koshkin_m_sobel/src/ops_mpi.cpp
> +  return kernel[0][0] * img[(i - 1) * height + (j - 1)] + kernel[0][1] * img[(i - 1) * height + j] +
fixed

2024-12-25 22:56 UTC, KoshkinMatvey commented on tasks/seq/koshkin_m_sobel/src/ops_seq.cpp
> +  return kernel[0][0] * img[(i - 1) * height + (j - 1)] + kernel[0][1] * img[(i - 1) * height + j] +
fixed

2024-12-25 22:56 UTC, KoshkinMatvey commented on tasks/mpi/koshkin_m_sobel/src/ops_mpi.cpp
> +    image.resize((width + 2) * (height + 2));
fixed

2024-12-25 22:56 UTC, KoshkinMatvey commented on tasks/mpi/koshkin_m_sobel/include/ops_mpi.hpp
> +}
fixed

2024-12-26 12:08 UTC, dssss12 approved these changes

2024-12-26 20:46 UTC, flashkasi approved these changes

2024-12-28 20:28 UTC, allnes approved these changes

2024-12-28 20:28 UTC, merged