Пикарычев Илья. Задача 3. Вариант 27. Линейная фильтрация изображений (вертикальное разбиение). Ядро Гаусса 3x3.
learning-process/ppc-2024-autumn pull request #755
Opened 2024-12-25 09:28 UTC by flashkasi

Версия алгоритма, использующая последовательный подход, реализует метод вертикального гауссова размытия изображения. Алгоритм включает в себя следующие шаги (SEQ):

1. Предварительная обработка (pre_processing):

    1.1. Проверка и инициализация необходимых данных, включая размеры изображения и массив входных данных.
    1.2. Копирование данных матрицы из входных данных во внутреннее представление.

2. Валидация (validation):

    2.1. Проверка корректности входных данных, включая размерность и количество входных и выходных данных.

3. Выполнение (run):

    3.1. Применение гауссова фильтра к каждому пикселю изображения, игнорируя пиксели на границах.
    3.2. Расчёт взвешенной суммы значений соседних пикселей для каждого пикселя с использованием заранее определённых весов для гауссова размытия.

4. Постобработка (post_processing):

    4.1. Копирование результатов размытия из внутреннего представления в выходные данные.

Версия алгоритма, использующая MPI, использует вертикальное разбиение для повышения производительности (MPI).

1. Предварительная обработка (pre_processing):

    1.1. Проверка порядка выполнения.
    1.2. Считывание размеров входного изображения и выделение памяти для входного и выходного изображений.

2. Валидация (validation):

    2.1. Проверка корректности входных данных, включая диапазон значений пикселей и размеры входных/выходных данных.

3. Выполнение (run):

    3.1. Распределение данных между процессами.
    3.2. Применение гауссова фильтра к своей части изображения каждым процессом.
    3.3. Сбор результатов на главный процесс.

4. Постобработка (post_processing):

    4.1. Копирование обработанных данных в выходные результаты, если процесс является главным.

2024-12-26 12:53 UTC, dssss12 approved these changes

2024-12-26 20:46 UTC, KoshkinMatvey approved these changes

2024-12-28 20:31 UTC, allnes commented on tasks/mpi/pikarychev_i_gauss3_vertical/func_tests/main.cpp
> +TEST(pikarychev_i_gauss3_vertical_mpi, PrewittX_3x2) { g3x3t(3, 2, {-1, 0, 1, -1, 0, 1, -1, 0, 1}); }
where gauss kernel? where divison 16? why sobel its not you task

2024-12-28 21:14 UTC, flashkasi commented on tasks/mpi/pikarychev_i_gauss3_vertical/func_tests/main.cpp
> +TEST(pikarychev_i_gauss3_vertical_mpi, PrewittX_3x2) { g3x3t(3, 2, {-1, 0, 1, -1, 0, 1, -1, 0, 1}); }
My solution is generic and supports any possible 3x3 matrix filter, did not think this specific 3x3 kernel is named Gauss 3x3 kernel. I'll add the tests now, but I think a penalty for delay would not be fair

2024-12-28 21:16 UTC, flashkasi commented on tasks/mpi/pikarychev_i_gauss3_vertical/func_tests/main.cpp
> +TEST(pikarychev_i_gauss3_vertical_mpi, PrewittX_3x2) { g3x3t(3, 2, {-1, 0, 1, -1, 0, 1, -1, 0, 1}); }
I added those tests and they passed without requiring me to change the solution, so my solution honestly worked as soon as I submitted it, I solved a more general task

2024-12-28 21:22 UTC, allnes commented on tasks/mpi/pikarychev_i_gauss3_vertical/func_tests/main.cpp
> +TEST(pikarychev_i_gauss3_vertical_mpi, PrewittX_3x2) { g3x3t(3, 2, {-1, 0, 1, -1, 0, 1, -1, 0, 1}); }
Yes, this task has kernels

![image](https://github.com/user-attachments/assets/3e2a157e-718c-45b1-b24a-a9fc32b77f86)

but yours task was create kernek with right functionality, but I didn't see 1/16, all kernels in your solutions isn't your task name

2024-12-28 21:25 UTC, aortemon approved these changes
Good work! You've done even more than you need to

2024-12-28 21:27 UTC, allnes commented on tasks/mpi/pikarychev_i_gauss3_vertical/func_tests/main.cpp
> +TEST(pikarychev_i_gauss3_vertical_mpi, PrewittX_3x2) { g3x3t(3, 2, {-1, 0, 1, -1, 0, 1, -1, 0, 1}); }
> I'll add the tests now, but I think a penalty for delay would not be fair

The solution has been provided for all tasks except the one assigned to you

2024-12-28 21:28 UTC, flashkasi commented on tasks/mpi/pikarychev_i_gauss3_vertical/func_tests/main.cpp
> +TEST(pikarychev_i_gauss3_vertical_mpi, PrewittX_3x2) { g3x3t(3, 2, {-1, 0, 1, -1, 0, 1, -1, 0, 1}); }
I just added the c 1/16 test, I'm just queuing up in actions.

https://github.com/learning-process/ppc-2024-autumn/pull/755/commits/bf26b7445c85c9a2b03847c707816f93ed3ad6ba

2024-12-28 21:32 UTC, flashkasi commented on tasks/mpi/pikarychev_i_gauss3_vertical/func_tests/main.cpp
> +TEST(pikarychev_i_gauss3_vertical_mpi, PrewittX_3x2) { g3x3t(3, 2, {-1, 0, 1, -1, 0, 1, -1, 0, 1}); }
https://github.com/learning-process/ppc-2024-autumn/pull/755#discussion_r1899008541

I understand my mistake and admit it, but I hope for your discretion in this matter.

2024-12-28 21:33 UTC, flashkasi commented on tasks/mpi/pikarychev_i_gauss3_vertical/func_tests/main.cpp
> +TEST(pikarychev_i_gauss3_vertical_mpi, PrewittX_3x2) { g3x3t(3, 2, {-1, 0, 1, -1, 0, 1, -1, 0, 1}); }
I understand my mistake and admit it, but I hope for your discretion in this matter.

2024-12-28 21:38 UTC, Sean0450 approved these changes
Greate changes, you've done big job!

2024-12-28 23:27 UTC, allnes commented
Until there are no meaningful approves, the work will not be accepted, and approves with a good review put as much as you like

2024-12-29 12:02 UTC, venn2713 requested changes

2024-12-29 12:02 UTC, venn2713 commented on tasks/mpi/pikarychev_i_gauss3_vertical/func_tests/main.cpp
> +  ASSERT_EQ(task.validation(), true);
Используйте ASSERT_TRUE()

2024-12-29 12:02 UTC, venn2713 commented on tasks/mpi/pikarychev_i_gauss3_vertical/func_tests/main.cpp
> +    ASSERT_EQ(out, ref);
Используйте EXPECT

2024-12-29 12:02 UTC, venn2713 commented on tasks/mpi/pikarychev_i_gauss3_vertical/include/ops_mpi.hpp
> +        // clang-format off
Тут on

2024-12-29 12:02 UTC, venn2713 commented on tasks/mpi/pikarychev_i_gauss3_vertical/include/ops_mpi.hpp
> +  }
Думаю больше не используется

2024-12-29 12:02 UTC, venn2713 commented on tasks/seq/pikarychev_i_gauss3_vertical/include/ops_seq.hpp
> +        // clang-format off
аналогично on

2024-12-29 14:31 UTC, flashkasi commented on tasks/mpi/pikarychev_i_gauss3_vertical/func_tests/main.cpp
> +  ASSERT_EQ(task.validation(), true);
No difference in this context

2024-12-29 14:31 UTC, flashkasi commented on tasks/mpi/pikarychev_i_gauss3_vertical/func_tests/main.cpp
> +    ASSERT_EQ(out, ref);
No difference in this context

2024-12-29 14:31 UTC, flashkasi commented on tasks/mpi/pikarychev_i_gauss3_vertical/include/ops_mpi.hpp
> +  }
If a test fails this will be used by gtest to print the value

2024-12-29 14:40 UTC, venn2713 approved these changes

2024-12-29 19:44 UTC, merged