Тюрин Михаил. Задача 3. Вариант 17. Сортировка Шелла с четно-нечетным слиянием Бэтчера.
learning-process/ppc-2024-autumn pull request #758
Opened 2024-12-25 10:48 UTC by tyurinm

Данная реализация объединяет алгоритм сортировки Шелла с оптимизированной последовательностью шагов, параллельный обмен данными с использованием MPI и эффективные стратегии слияния для сортировки распределённых данных. Последовательность шагов в сортировке Шелла рассчитана с использованием математической формулы для повышения производительности. Функции swapSortedArrays и алгоритмы слияния обеспечивают эффективное объединение данных между процессами MPI. Такой подход оптимизирует локальные вычисления с помощью сортировки Шелла и синхронизацию между процессами через слияние по схеме Батчера, обеспечивая высокую масштабируемость и эффективность для работы с большими наборами данных.

2024-12-25 11:07 UTC, venn2713 requested changes

2024-12-25 11:07 UTC, venn2713 commented on tasks/mpi/tyurin_m_shell_sort_batcher_merge/func_tests/main.cpp
> +    world.barrier();
Думаю это тут не нужно

2024-12-25 11:07 UTC, venn2713 commented on tasks/mpi/tyurin_m_shell_sort_batcher_merge/func_tests/main.cpp
> +}
Разбейте на отдельные тесты и пропускайте если не подходит под кол-во потоков

2024-12-25 11:07 UTC, venn2713 commented on tasks/mpi/tyurin_m_shell_sort_batcher_merge/perf_tests/main.cpp
> +}  // namespace tyurin_m_shell_sort_batcher_merge_mpi
Не сделайте просто `tyurin_m_shell_sort_batcher_merge_mpi::random_vector`

2024-12-25 12:36 UTC, korablev-vm requested changes
плюс приведите входные данные в перф тестах к одним значениям для удобства сравнения

2024-12-25 12:36 UTC, korablev-vm commented on tasks/mpi/tyurin_m_shell_sort_batcher_merge/src/ops_mpi.cpp
> +}
в return можно сделать world.size() % 2 == 0

2024-12-25 17:55 UTC, polikanovv requested changes

2024-12-25 17:55 UTC, polikanovv commented on tasks/mpi/tyurin_m_shell_sort_batcher_merge/perf_tests/main.cpp
> +  std::uniform_int_distribution<int> dist(0, 100);
change from -100 to 100

2024-12-25 17:55 UTC, polikanovv commented on tasks/seq/tyurin_m_shell_sort_batcher_merge/perf_tests/main.cpp
> +  std::uniform_int_distribution<int> dist(0, 100);
also

2024-12-25 18:00 UTC, polikanovv approved these changes

2024-12-25 18:01 UTC, venn2713 approved these changes

2024-12-25 18:01 UTC, korablev-vm approved these changes

2024-12-28 20:33 UTC, allnes commented on tasks/mpi/tyurin_m_shell_sort_batcher_merge/src/ops_mpi.cpp
> +  return val_n > 0 && val_n % 2 == 0 && world.size() % 2 == 0;
why do you check world.size() % 2 == 0, it would be work for all process

2024-12-29 08:28 UTC, tyurinm commented on tasks/mpi/tyurin_m_shell_sort_batcher_merge/src/ops_mpi.cpp
> +  return val_n > 0 && val_n % 2 == 0 && world.size() % 2 == 0;
The algorithm works correctly only when the number of processes divides the number of elements evenly because each process must handle an equal-sized subarray for the Bitonic merge to function properly. If the division is not exact, subarrays will be uneven, disrupting the parallel execution of the sorting steps and causing inconsistencies during the merging phase. To address this, the algorithm should either be adapted to handle uneven element distribution or restricted to cases where the division is exact.

2024-12-29 11:48 UTC, allnes approved these changes

2024-12-29 11:48 UTC, merged