Кондратьев Ярослав. Задача 1. Вариант 16. Нахождение максимальных значений по столбцам матрицы
learning-process/ppc-2024-autumn pull request #76
Opened 2024-10-30 16:56 UTC by Yarik3008

Описание последовательной задачи
- входящая матрица при считывании транспонируется для удобства использования
- последовательный построчный поиск максимума

Описание MPI задачи 
- входящая матрица при считывании транспонируется для удобства использования
- матрица построчно рассылается доступным процессам. Количество отправляемых строк зависит от ранга процесса (если ранг меньше остатка от деления количества строк на количество процессов, то отправляется step_ + 1)
- каждый процесс последовательно построчно ищет максимумы в полученных данных
- результаты от процессов отправляются в главный процесс, где объединяются и записываются в итоговый ответ

2024-10-30 18:28 UTC, ermolaevv commented on tasks/mpi/kondratev_ya_max_col_matrix/src/ops_mpi.cpp
> +  broadcast(world, remain_, 0);
Do we need to send these values? Wouldn't it be faster to calculate this in each process?

2024-10-30 18:28 UTC, ermolaevv commented on tasks/mpi/kondratev_ya_max_col_matrix/src/ops_mpi.cpp
> +  broadcast(world, remain_, 0);
```suggestion
  if (world.rank() == 0) {
    row_ = taskData->inputs_count[0];
    col_ = taskData->inputs_count[1];
  }

  broadcast(world, row_, 0);
  broadcast(world, col_, 0);
  step_ = col_ / world.size();
  remain_ = col_ % world.size();
```

2024-10-30 18:32 UTC, Yarik3008 commented on tasks/mpi/kondratev_ya_max_col_matrix/src/ops_mpi.cpp
> +  broadcast(world, remain_, 0);
fixed

2024-10-30 18:47 UTC, ermolaevv approved these changes

2024-10-31 10:29 UTC, MikeMuradov commented on tasks/mpi/kondratev_ya_max_col_matrix/src/ops_mpi.cpp
> +  input_ = std::vector(col, std::vector<int32_t>(row));
It is possible to use `resize` better than vector assignment. At a minimum, it increases readability. Also fix it in other places.

2024-10-31 17:20 UTC, allnes commented on tasks/mpi/kondratev_ya_max_col_matrix/src/ops_mpi.cpp
> +    throw std::invalid_argument("Args should be greater then zero");
please use validation, thow is redudant for that

2024-10-31 17:20 UTC, allnes commented on tasks/mpi/kondratev_ya_max_col_matrix/src/ops_mpi.cpp
> +bool kondratev_ya_max_col_matrix_mpi::TestMPITaskParallel::pre_processing() {
please use all mpi functions in run()

2024-10-31 17:21 UTC, allnes commented on tasks/seq/kondratev_ya_max_col_matrix/src/ops_seq.cpp
> +    throw std::invalid_argument("Args should be greater then zero");
same point about thow

2024-10-31 17:27 UTC, Yarik3008 commented on tasks/mpi/kondratev_ya_max_col_matrix/src/ops_mpi.cpp
> +    throw std::invalid_argument("Args should be greater then zero");
This function is called before validation in tests, so validation cannot be used. Also, theoretically, it is impossible to take a zero value, because memory is allocated in the function. There are attempts to allocate vectors of zero size

2024-10-31 17:33 UTC, allnes commented on tasks/mpi/kondratev_ya_max_col_matrix/src/ops_mpi.cpp
> +    throw std::invalid_argument("Args should be greater then zero");
ok please handle empty vector in the task with help validation

2024-10-31 18:03 UTC, Yarik3008 commented on tasks/mpi/kondratev_ya_max_col_matrix/src/ops_mpi.cpp
> +  input_ = std::vector(col, std::vector<int32_t>(row));
fixed

2024-10-31 18:04 UTC, Yarik3008 commented on tasks/mpi/kondratev_ya_max_col_matrix/src/ops_mpi.cpp
> +bool kondratev_ya_max_col_matrix_mpi::TestMPITaskParallel::pre_processing() {
fixed

2024-10-31 19:16 UTC, allnes commented on tasks/mpi/kondratev_ya_max_col_matrix/src/ops_mpi.cpp
> +    throw std::invalid_argument("Args should be greater then zero");
no, please remove throw, and cases with empty vector check in the task

2024-11-02 13:00 UTC, aobolensk requested changes

2024-11-02 13:09 UTC, Yarik3008 commented on tasks/seq/kondratev_ya_max_col_matrix/func_tests/main.cpp
> +}
This test was needed when writing the program. It checks the correct insertion of reference values into the generated data. The function should insert a reference value for the tests into each column of the matrix. He got into the MPI part with a copy-paste from the Seq part. If it is significant, I can delete it

2024-11-02 14:23 UTC, Yarik3008 commented on tasks/seq/kondratev_ya_max_col_matrix/func_tests/main.cpp
> +}
fixed

2024-11-02 14:23 UTC, Yarik3008 commented on tasks/mpi/kondratev_ya_max_col_matrix/include/ops_mpi.hpp
> +void insertRefValue(std::vector<std::vector<int32_t>>& mtrx, int32_t ref);
fixed

2024-11-02 14:23 UTC, Yarik3008 commented on tasks/seq/kondratev_ya_max_col_matrix/src/ops_seq.cpp
> +    throw std::invalid_argument("Args should be greater then zero");
fixed

2024-11-02 14:23 UTC, Yarik3008 commented on tasks/mpi/kondratev_ya_max_col_matrix/src/ops_mpi.cpp
> +    throw std::invalid_argument("Args should be greater then zero");
fixed

2024-11-03 02:41 UTC, aobolensk approved these changes

2024-11-04 00:46 UTC, allnes approved these changes

2024-11-04 00:46 UTC, merged