Ясакова Татьяна. Задача 3. Вариант 14. Быстрая сортировка с простым слиянием.
learning-process/ppc-2024-autumn pull request #768
Opened 2024-12-25 20:30 UTC by Tanya-Yasakova

Алгоритм включает в себя следующие основные этапы:
1. Декомпозиция данных:
    Данные равномерно распределяются между процессами с помощью scatterv.
    Каждый процесс сортирует свою часть данных с помощью итеративной быстрой сортировки.

 2. Взаимодействие между рабочими процессами и мастером:
    Рабочие процессы отправляют свои отсортированные элементы по одному мастеру.
    Перед отправкой каждого элемента рабочий процесс ждет подтверждения от мастера.
    Мастер-процесс использует минимальную кучу для эффективного слияния данных, поступающих от рабочих процессов.
    На каждом шаге мастер извлекает наименьший элемент из кучи, добавляет его в результирующий массив и запрашивает следующий элемент у соответствующего рабочего процесса.

3.  Синхронизация и сбор результатов:
    Функция merge_func вызывает master_function для мастера и worker_function для рабочих процессов.
    Все процессы синхронизируются через барьер, чтобы гарантировать завершение обмена данными.

Таким образом, алгоритм сочетает в себе декомпозицию данных, локальную сортировку и эффективное слияние результатов с помощью минимальной кучи, обеспечивая параллельную обработку и синхронизацию между процессами.

2024-12-25 20:40 UTC, emilien-gus commented on tasks/seq/yasakova_t_quick_sort_with_simple_merge/perf_tests/main.cpp
> +#include <random>
Please, remove all unnecessary headers

2024-12-25 20:40 UTC, emilien-gus commented on tasks/mpi/yasakova_t_quick_sort_with_simple_merge/func_tests/main.cpp
> +
Please, add some tests with sorted data and with big numbers

2024-12-25 20:46 UTC, AnastasiaRezantseva requested changes

2024-12-25 20:46 UTC, AnastasiaRezantseva commented on tasks/mpi/yasakova_t_quick_sort_with_simple_merge/func_tests/main.cpp
> +                                              unsigned random_seed = std::random_device{}()) {
move methods to your namespace

2024-12-25 20:46 UTC, AnastasiaRezantseva commented on tasks/seq/yasakova_t_quick_sort_with_simple_merge/func_tests/main.cpp
> +  std::vector<int> sortedData;
move all methods to your namespace

2024-12-25 20:46 UTC, AnastasiaRezantseva commented on tasks/mpi/yasakova_t_quick_sort_with_simple_merge/func_tests/main.cpp
> +TEST(yasakova_t_quick_sort_with_simple_merge_mpi, test_random_numbers_array) {
add tests with negative numbers

2024-12-26 20:35 UTC, AnastasiaRezantseva approved these changes

2024-12-26 21:28 UTC, emilien-gus approved these changes

2024-12-28 20:46 UTC, allnes commented on tasks/mpi/yasakova_t_quick_sort_with_simple_merge/src/ops_mpi.cpp
> +struct PriorityQueueNode {
please use std::priority_queue

2024-12-29 12:09 UTC, Tanya-Yasakova commented on tasks/mpi/yasakova_t_quick_sort_with_simple_merge/src/ops_mpi.cpp
> +struct PriorityQueueNode {
I already use std::priority_queue in master_function

2024-12-29 13:37 UTC, allnes commented on tasks/mpi/yasakova_t_quick_sort_with_simple_merge/src/ops_mpi.cpp
> +struct PriorityQueueNode {
please remove unused structure

2024-12-29 13:43 UTC, Tanya-Yasakova commented on tasks/mpi/yasakova_t_quick_sort_with_simple_merge/src/ops_mpi.cpp
> +struct PriorityQueueNode {
I use this: std::priority_queue<PriorityQueueNode, std::vector<PriorityQueueNode>

2024-12-29 13:58 UTC, allnes approved these changes

2024-12-29 15:32 UTC, merged