Савченко Максим. Задача 3. Вариант 3. Умножение плотных матриц. Элементы типа double. Алгоритм Штрассена.
learning-process/ppc-2024-autumn pull request #769
Opened 2024-12-25 21:16 UTC by MaxikGuy

# Алгоритм Штрассена.
Алгоритм Штрассена — это метод умножения матриц, который уменьшает количество необходимых умножений по сравнению с классическим методом. 

## 1. Последовательная реализация.

- **Базовый случай:** Если размер матрицы меньше или равен 4, используется стандартное умножение матриц.
- **Преобразование матриц:** Если размер матрицы не является степенью двойки, матрицы дополняются нулями до ближайшей степени двойки.
- **Разделение матриц:** Исходные матрицы A и B разбиваются на четыре подматрицы (A11, A12, A21, A22 и B11, B12, B21, B22).
- **Рекурсивные вызовы:** Вычисляются семь произведений (M[0] до M[6]) с использованием рекурсивных вызовов функции `strassen`, которые комбинируют подматрицы.
- **Сбор результата:** Результаты M[0] до M[6] комбинируются для получения итоговой матрицы C.

## 2. Параллельная реализация.

- Инициализация MPI: Определяется ранг и размер коммуникатора MPI. Если ранг больше 6, процесс завершает выполнение.
- Передача данных: Главный процесс (ранг 0) инициализирует локальные матрицы и передает их всем процессам с помощью `broadcast`.
- Разделение матриц: Как и в последовательной версии, матрицы разбиваются на подматрицы.
- Параллельные вычисления: Каждый процесс вычисляет одно или несколько произведений M[0] до M[6] в зависимости от своего ранга, что позволяет использовать все доступные процессы.
- Сбор результатов: Результаты собираются с помощью `reduce`, и итоговая матрица C формируется только на главном процессе.

2024-12-26 12:32 UTC, SingularityNN requested changes

2024-12-26 12:32 UTC, SingularityNN commented on tasks/seq/savchenko_m_matrix_mult_strassen/src/ops_seq_savchenko_L3.cpp
> +  std::vector<double> local_A(size * size, 0.0);
it is better to save the value in a variable and then use this variable

2024-12-26 12:49 UTC, SingularityNN commented on tasks/seq/savchenko_m_matrix_mult_strassen/src/ops_seq_savchenko_L3.cpp
> +  std::vector<double> local_A(size * size, 0.0);
change every "size * size" construction like that

2024-12-26 20:56 UTC, ArtemMakadrai requested changes

2024-12-26 20:56 UTC, ArtemMakadrai commented on tasks/seq/savchenko_m_matrix_mult_strassen/src/ops_seq_savchenko_L3.cpp
> +
You don't have any tests for the correctness of the input data. Please add them.

2024-12-27 09:26 UTC, ArtemMakadrai approved these changes

2024-12-27 09:46 UTC, SingularityNN approved these changes

2024-12-27 12:24 UTC, MaxikGuy commented on tasks/seq/savchenko_m_matrix_mult_strassen/src/ops_seq_savchenko_L3.cpp
> +
done

2024-12-28 20:50 UTC, allnes approved these changes

2024-12-28 20:50 UTC, merged