Калякина Анастасия. Задача 1. Вариант 2. Вычисление среднего значения элементов вектора
learning-process/ppc-2024-autumn pull request #77
Opened 2024-10-30 18:53 UTC by kalyakinaa

Описание последовательного решения задачи:

- Алгоритм последовательно проходит по всем элементам вектора, подсчитывая их сумму
- Найденная сумма делится на количество элементов

Описание параллельного решения задачи:

- Входной вектор дополняется нулями соответственно количеству процессов
- Данные по возможности равномерно распределяются с помощью функции scatterv
- Каждый процесс подсчитывает сумму элементов переданного ему вектора
- Полученные суммы объединяются сложением с помощью функции reduce
- Итоговая сумма делится на исходное количество элементов (количество до дополнения нулями)

2024-10-30 20:35 UTC, kmichaelk requested changes

2024-10-30 20:35 UTC, kmichaelk commented on tasks/mpi/kalyakina_a_average_value/src/ops_mpi.cpp
> +  boost::mpi::scatter(world, input_vector.data(), local_input_vector.data(), delta, 0);
Using `scatter` with fixed roughly-calculated `delta` results in a situation when you're transmitting more data than you actually have, i.e. if you're processing input data of size 10 with 3 processes, this will give you 4 items per process - it's 12 items totally. 

However, his solution still works - because the "extra" workload is filled with zeroes and adding zeroes does not affect the sum - and the zeros came from the resize of the vector a couple of lines above.

This approach would not work if we needed to calculate not a sum in which adding zero is an idempotent operation, but, for example, the number of occurrences of numbers in which zero is a distinct value.

And, as you transmit more data than is available actually, you also have to process it later, reducing the efficiency.

2024-10-30 20:35 UTC, kmichaelk commented on tasks/mpi/kalyakina_a_average_value/include/ops_mpi.hpp
> +  std::vector<int> input_vector;
I'd move it to `preprocessing` as it is not needed anywhere else and the alive vector is keeping memory from being released

2024-10-31 17:27 UTC, kalyakinaa commented on tasks/mpi/kalyakina_a_average_value/src/ops_mpi.cpp
> +  boost::mpi::scatter(world, input_vector.data(), local_input_vector.data(), delta, 0);
I understand what you mean. I need to take some time to think about the implementation.

2024-10-31 17:28 UTC, kalyakinaa commented on tasks/mpi/kalyakina_a_average_value/include/ops_mpi.hpp
> +  std::vector<int> input_vector;
Your remark makes sense. Thank you, I will definitely take it into account.

2024-10-31 18:19 UTC, kmichaelk approved these changes

2024-10-31 18:33 UTC, vitaliyvoroshilov approved these changes

2024-11-01 14:01 UTC, hasanyanovk approved these changes

2024-11-02 13:16 UTC, aobolensk requested changes

2024-11-02 13:16 UTC, aobolensk commented on modules/core/perf/include/perf.hpp
> -  constexpr const static double MIN_TIME = 0.05;
Please, do not modify common files

2024-11-02 13:16 UTC, aobolensk commented on modules/core/perf/src/perf.cpp
> +  if (time_secs < PerfResults::MAX_TIME) {
Same

2024-11-02 13:16 UTC, aobolensk commented on tasks/mpi/kalyakina_a_average_value/include/ops_mpi.hpp
> +std::vector<int> RandomVectorWithFixSum(int sum, const int& count);
Please move test functions to the test modules

2024-11-02 14:21 UTC, kalyakinaa commented on tasks/mpi/kalyakina_a_average_value/include/ops_mpi.hpp
> +std::vector<int> RandomVectorWithFixSum(int sum, const int& count);
Fixed

2024-11-02 17:46 UTC, kalyakinaa commented on modules/core/perf/include/perf.hpp
> -  constexpr const static double MIN_TIME = 0.05;
Fixed

2024-11-02 17:46 UTC, kalyakinaa commented on modules/core/perf/src/perf.cpp
> +  if (time_secs < PerfResults::MAX_TIME) {
Fixed

2024-11-03 03:52 UTC, aobolensk approved these changes

2024-11-04 00:47 UTC, allnes approved these changes

2024-11-04 00:48 UTC, merged