Савченко Максим. Задача 2. Вариант 17. Ленточная горизонтальная схема - разбиение только матрицы А.
learning-process/ppc-2024-autumn pull request #771
Opened 2024-12-25 21:56 UTC by MaxikGuy

# Ленточная горизонтальная схема
Ленточная горизонтальная схема умножения матриц — это параллельный алгоритм, при котором исходные матрицы разбиваются на горизонтальные (для матрицы A) и вертикальные (для матрицы B) полосы. В данной реализации разбиение происходит только матрицы A.

## 1. Последовательная реализация (классическое умножение матриц)
Классическое умножение матриц основано на тройном цикле, который проходит по всем элементам матриц. Для двух матриц A (размером `m * n`) и B (размером `n * p`), результатом будет матрица C (размером `m * p`). 

## 2. Параллельная реализация 
Параллельная реализация использует библиотеку MPI для распределения вычислений между несколькими процессами. Основные шаги алгоритма:

1. **Инициализация MPI:** Получение ранга и размера коммуникатора.
2. **Рассылка размеров матриц:** Процесс 0 рассылает размер матриц всем процессам.
3. **Распределение матриц:** Матрица A разбивается на блоки по строкам, и каждый процесс получает свою часть. Матрица B рассылается всем процессам.
4. **Локальное умножение:** Каждый процесс выполняет умножение своей локальной части матрицы A на матрицу B и сохраняет результат в локальной матрице результата.
5. **Сбор результатов:** Результаты локальных умножений собираются в процессе 0 с помощью операции `MPI_Gatherv`, которая учитывает количество строк, обработанных каждым процессом.

2024-12-27 13:11 UTC, MaximChizhov reviewed
validation does not check the number of incoming and outgoing vectors.

2024-12-27 13:19 UTC, ElizavetaFrolova requested changes
please increase the dimension of the matrix in perf_tests

2024-12-27 18:10 UTC, ElizavetaFrolova approved these changes

2024-12-27 19:34 UTC, MaximChizhov approved these changes

2024-12-28 20:51 UTC, allnes approved these changes

2024-12-28 20:51 UTC, merged