Наседкин Егор. Задача 3. Вариант 3. Умножение плотных матриц. Элементы типа double. Алгоритм Штрассена.Наседкин Егор. Задача 3. Вариант 3. Умножение плотных матриц. Элементы типа double. Алгоритм Штрассена.
learning-process/ppc-2024-autumn pull request #782
Opened 2024-12-26 10:08 UTC by myffii

2024-12-26 15:14 UTC, dangerulya approved these changes

2024-12-26 15:56 UTC, DSFKnight requested changes

2024-12-26 15:56 UTC, DSFKnight commented on tasks/mpi/nasedkin_e_strassen_algorithm/src/ops_mpi.cpp
> +bool StrassenAlgorithmMPI::validation() {
In validation, there are checks that are not covered by tests. Create tests for them.

2024-12-26 15:56 UTC, DSFKnight commented on tasks/seq/nasedkin_e_strassen_algorithm/src/ops_seq.cpp
> +bool StrassenAlgorithmSEQ::validation() {
Same

2024-12-26 16:45 UTC, myffii commented on tasks/mpi/nasedkin_e_strassen_algorithm/src/ops_mpi.cpp
> +bool StrassenAlgorithmMPI::validation() {
done

2024-12-26 17:24 UTC, DSFKnight approved these changes

2024-12-28 20:58 UTC, allnes commented on tasks/mpi/nasedkin_e_strassen_algorithm/func_tests/main.cpp
> +  int matrixSize = 8;
please check size = 17

2024-12-29 03:45 UTC, myffii commented on tasks/mpi/nasedkin_e_strassen_algorithm/func_tests/main.cpp
> +  int matrixSize = 8;
Added a method for padding matrices and tests for non-2^n x 2^n matrices.

2024-12-29 11:51 UTC, allnes approved these changes

2024-12-29 11:52 UTC, merged