Сдобнов Владимир Задача 3. Вариант 15. Четно-нечетная сортировка слиянием Бетчера
learning-process/ppc-2024-autumn pull request #783
Opened 2024-12-26 10:40 UTC by VladimirSdobnov

Входные данные:
Для последовательного алгоритма: вектор и его размер равный степени двойки
Для параллельного: вектор и его размер
Описание параллельного алгоритма:
Делим вектор между потоками. Каждый поток сортирует свои данные, после чего данные из потоков сливаются.
Процесс слияния:  Процесс получает данные от следующего за ним процесса, объединяет их со своими и сортирует, затем возвращает вторую половину полученного вектора обратно. Пары выбираются поочередно, сначала (0,1), (2,3), (4,5) и тд, затем (1,2), (2,3), (3,4). Число слияний равно числу потоков.
После прохождения слияний все данные собираются в 0 потоке.

2024-12-26 11:16 UTC, venn2713 requested changes

2024-12-26 11:16 UTC, venn2713 commented on tasks/mpi/Sdobnov_V_mergesort_Betcher/src/ops_mpi.cpp
> +  std::sort(local_vec_.begin(), local_vec_.end());
Тут нужно использовать свой quick sort, пока что not match description

2024-12-26 21:33 UTC, emilien-gus commented on tasks/seq/Sdobnov_V_mergesort_Betcher/src/ops_seq.cpp
> +}
Add check that size is multiple of a power of two and do some test for this case in func_tests

2024-12-27 07:46 UTC, emilien-gus commented on tasks/seq/Sdobnov_V_mergesort_Betcher/func_tests/main.cpp
> +TEST(Sdobnov_V_mergesort_Betcher_seq, InvalidInputCount) {
You should change your validation test because this data is already wouldnt pass validation because of size isn't multiple of a power of two(you check this case on other test). Also you can remove all expected_res vectors in other validation tests.

2024-12-27 07:46 UTC, emilien-gus commented on tasks/seq/Sdobnov_V_mergesort_Betcher/func_tests/main.cpp
> +  int size = 10;
Change size to right one. Also do it for every validation test except InvalidInputCountNotPow2

2024-12-27 08:54 UTC, emilien-gus approved these changes

2024-12-27 13:19 UTC, venn2713 approved these changes

2024-12-29 19:47 UTC, merged