Громов Алексей. Задача 3. Вариант 32. Построение выпуклой оболочки для компонент бинарного изображения.
learning-process/ppc-2024-autumn pull request #788
Opened 2024-12-26 16:53 UTC by DSFKnight

**Описание последовательной задачи**
На вход подается изображение в виде матрицы, где каждая ячейка может быть пикселем). 
Цель – выделить соединенные компоненты изображения и для каждой из них вычислить выпуклую оболочку.

**Этапы выполнения:**

- Маркировка компонентов:
Для каждого пикселя выполняется проход сверху вниз и слева направо для поиска соединенных областей.
Используются два прохода: первый присваивает уникальные метки, второй уточняет их, чтобы объединить связные компоненты.
- Построение выпуклой оболочки:
Для каждой выделенной компоненты применяется алгоритм Джарвиса для вычисления её выпуклой оболочки.
- Реконструкция изображения:
Полученные выпуклые оболочки интегрируются обратно в результирующую матрицу.

**Результат:**

На выходе создается новое изображение, в котором выделены только выпуклые оболочки соединенных компонентов.

**Описание параллельной задачи**
Распределение данных:

Исходное изображение разбивается на части, которые распределяются между процессами.
Процесс с рангом 0 отвечает за управление распределением данных и координацию вычислений.
Этапы выполнения:

- Маркировка компонентов:
Каждый процесс выполняет маркировку своей части данных независимо.
Синхронизация меток между процессами происходит через обмен данными на границах распределенных областей.
- Построение выпуклой оболочки:
Процессы вычисляют выпуклые оболочки для своих локальных компонентов.
Полученные результаты отправляются процессу с рангом 0, который объединяет выпуклые оболочки для всех данных.
- Реконструкция изображения:
Процесс с рангом 0 формирует финальное изображение с выпуклыми оболочками.

**Результат:**

На выходе создается новое изображение, где выделены выпуклые оболочки, аналогично последовательной версии, но с использованием параллельных вычислений для ускорения обработки.

2024-12-26 17:31 UTC, WholeHorse requested changes

2024-12-26 17:31 UTC, WholeHorse commented on tasks/seq/gromov_a_convex_hull/src/ops_seq.cpp
> +#include <unordered_map>
is it used?

2024-12-26 17:59 UTC, ofuuse commented on tasks/mpi/gromov_a_convex_hull/func_tests/main.cpp
> +TEST(gromov_a_convex_hull_mpi, Test_With_Zeroes) {
Add more func_tests

2024-12-27 00:07 UTC, WholeHorse approved these changes

2024-12-27 09:44 UTC, ofuuse approved these changes

2024-12-28 21:01 UTC, allnes commented on tasks/mpi/gromov_a_convex_hull/func_tests/main.cpp
> +}
please create different figures

2024-12-29 11:53 UTC, allnes approved these changes

2024-12-29 11:53 UTC, merged