FixRevert. Golovkin Maksim. Task№2. Var№17/ Rowwise Matrix Partitioning
learning-process/ppc-2024-autumn pull request #822
Opened 2024-12-28 13:26 UTC by Mxaqq

2024-12-28 18:49 UTC, kmichaelk requested changes

2024-12-28 18:49 UTC, kmichaelk commented on tasks/mpi/golovkin_rowwise_matrix_partitioning/func_tests/main.cpp
> +  if (world.size() < 5 || world.rank() >= 4) {
What?

2024-12-28 18:53 UTC, Mxaqq commented on tasks/mpi/golovkin_rowwise_matrix_partitioning/func_tests/main.cpp
> +  if (world.size() < 5 || world.rank() >= 4) {
If the size of the MPI world is less than 5 or the process rank is greater than or equal to 4, memory is allocated for matrices A and B, and they are filled with random values using the get_random_matrix function.

2024-12-28 18:57 UTC, kmichaelk requested changes
None of the tests compare the solution with either the reference or the sequential one in a random case

2024-12-28 18:57 UTC, kmichaelk commented on tasks/mpi/golovkin_rowwise_matrix_partitioning/func_tests/main.cpp
> +  if (world.size() < 5 || world.rank() >= 4) {
Limiting communicator size does not sound like a properly implemented solution

2024-12-28 19:04 UTC, kmichaelk requested changes

2024-12-28 19:04 UTC, kmichaelk commented on tasks/mpi/golovkin_rowwise_matrix_partitioning/func_tests/main.cpp
> +  if (world.size() < 5 || world.rank() >= 4) {
I see no reason to resolve this comment. The solution is incorrect and that's why it fails.

Also de facto there were never any functional tests as the tests present here do not verify results.

2024-12-28 19:21 UTC, Mxaqq commented on tasks/mpi/golovkin_rowwise_matrix_partitioning/func_tests/main.cpp
> +  if (world.size() < 5 || world.rank() >= 4) {
The size limit of the communicator was chosen by me because in my current work environment and for testing purposes it is the most convenient and easiest way to manage the participation of processes. This approach allows you to effectively control the number of active processes, avoiding excessive complexity in data distribution and synchronization between them.

2024-12-28 20:06 UTC, kmichaelk commented on tasks/mpi/golovkin_rowwise_matrix_partitioning/func_tests/main.cpp
> +  if (world.size() < 5 || world.rank() >= 4) {
If you want to test on a small number of processes, you simply won't run it with a large one. And such a limit implies that your solution doesn't work on a large one and you know it. Also, the answer sounds like ChatGPT-generated.

2024-12-28 23:13 UTC, Mxaqq commented on tasks/mpi/golovkin_rowwise_matrix_partitioning/func_tests/main.cpp
> +  if (world.size() < 5 || world.rank() >= 4) {
It offends me if you think so. It works for me and it works well. If you want to get to the bottom of my answers, you're not here.

2024-12-29 00:39 UTC, Mxaqq commented on tasks/mpi/golovkin_rowwise_matrix_partitioning/func_tests/main.cpp
> +  if (world.size() < 5 || world.rank() >= 4) {
I fix all test

2024-12-29 08:29 UTC, kmichaelk requested changes

2024-12-29 08:29 UTC, kmichaelk commented on tasks/mpi/golovkin_rowwise_matrix_partitioning/perf_tests/main.cpp
> +    B = new double[rows_B * cols_B]();
You don't fill inputs with random data and multiplying zeros

2024-12-29 08:29 UTC, kmichaelk commented on tasks/mpi/golovkin_rowwise_matrix_partitioning/perf_tests/main.cpp
> +  if (world.size() < 5 && world.rank() >= 4) {
This condition will never pass on 4 processes (max world rank is `world.size() - 1`, so it can't be 4)

2024-12-29 08:29 UTC, kmichaelk commented on tasks/mpi/golovkin_rowwise_matrix_partitioning/perf_tests/main.cpp
> +    auto *expected_res = new double[rows_A * cols_B]();
And you're comparing the answer with absolutely zeroed matrix

2024-12-29 12:26 UTC, KAPUSHA228 approved these changes

2024-12-29 14:07 UTC, Mxaqq commented on tasks/mpi/golovkin_rowwise_matrix_partitioning/perf_tests/main.cpp
> +    B = new double[rows_B * cols_B]();
fix it

2024-12-29 14:07 UTC, Mxaqq commented on tasks/mpi/golovkin_rowwise_matrix_partitioning/perf_tests/main.cpp
> +  if (world.size() < 5 && world.rank() >= 4) {
i fix it

2024-12-29 14:08 UTC, Mxaqq commented on tasks/mpi/golovkin_rowwise_matrix_partitioning/perf_tests/main.cpp
> +    auto *expected_res = new double[rows_A * cols_B]();
fix it

2024-12-29 15:31 UTC, WladislawFilatew approved these changes

2024-12-29 19:56 UTC, closed without merging