Гордеева Таисия. Задача 1. Вариант 16. Нахождение максимальных значений по столбцам матрицы
learning-process/ppc-2024-autumn pull request #83
Opened 2024-10-31 13:06 UTC by TayaGordeeva

**Описание программы.**
Программа вычисляет максимальное значение в каждом столбце матрицы.

_-Последовательная задача:_
- изначально максимальное значение равно первому элементу текущего столбца; происходит сравнение текущего максимального значения с каждым элементом из соответствующего столбца - если значение элемента больше, то оно становится максимальным значением
- результат: вектор с максимальными значениями для каждого столбца

_-MPI задача:_
- матрица разбивается на кол-во процессов
- каждый процесс ищет максимум в каждом столбце своих данных
- результаты процессов отправляются на главный процесс и объединяются 
- результат: вектор максимальных значений для каждого столбца

2024-10-31 22:28 UTC, SergeyBoRss commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/func_tests/main.cpp
> +#include <boost/mpi/environment.hpp>
Not used in the code

2024-10-31 22:28 UTC, SergeyBoRss commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/perf_tests/main.cpp
> +    max_s.resize(cols, INT_MIN);
It is recommended to add #include <climits>

2024-10-31 22:28 UTC, SergeyBoRss commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/func_tests/main.cpp
> +  std::vector<int32_t> global_max(cols, INT_MIN);
It is recommended to add #include

2024-10-31 22:28 UTC, SergeyBoRss commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/func_tests/main.cpp
> +    }
You can compare vectors in their entirety

2024-10-31 22:28 UTC, SergeyBoRss commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/src/ops_mpi.cpp
> +  std::vector<int> tmp_max(local_input_[0].size(), INT_MIN);
It is recommended to add #include <climits>

2024-10-31 22:28 UTC, SergeyBoRss commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/src/ops_mpi.cpp
> +  for (size_t i = 0; i < res.size(); i++) output_matr[i] = res[i];
You can use copying (std::copy)

2024-10-31 22:28 UTC, SergeyBoRss commented on tasks/seq/gordeva_t_max_val_of_column_matrix/include/ops_seq.hpp
> +#include <string>
Not used in the code

2024-10-31 22:28 UTC, SergeyBoRss commented on tasks/seq/gordeva_t_max_val_of_column_matrix/src/ops_seq.cpp
> +#include <thread>
Not used in the code

2024-10-31 22:28 UTC, SergeyBoRss commented on tasks/seq/gordeva_t_max_val_of_column_matrix/perf_tests/main.cpp
> +  std::vector<int> res_vec(rows, 0);
It must be cols

2024-10-31 22:28 UTC, SergeyBoRss commented on tasks/seq/gordeva_t_max_val_of_column_matrix/src/ops_seq.cpp
> +  for (size_t i = 0; i < res_.size(); i++) output_matr[i] = res_[i];
You can use copying (std::copy)

2024-11-01 07:21 UTC, TayaGordeeva commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/func_tests/main.cpp
> +#include <boost/mpi/environment.hpp>
fixed

2024-11-01 07:22 UTC, TayaGordeeva commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/perf_tests/main.cpp
> +    max_s.resize(cols, INT_MIN);
fixed

2024-11-01 07:22 UTC, TayaGordeeva commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/func_tests/main.cpp
> +  std::vector<int32_t> global_max(cols, INT_MIN);
added climits

2024-11-01 07:22 UTC, TayaGordeeva commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/func_tests/main.cpp
> +    }
done

2024-11-01 07:23 UTC, TayaGordeeva commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/src/ops_mpi.cpp
> +  std::vector<int> tmp_max(local_input_[0].size(), INT_MIN);
added climits

2024-11-01 07:23 UTC, TayaGordeeva commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/src/ops_mpi.cpp
> +  for (size_t i = 0; i < res.size(); i++) output_matr[i] = res[i];
rewrote on copy

2024-11-01 07:23 UTC, TayaGordeeva commented on tasks/seq/gordeva_t_max_val_of_column_matrix/include/ops_seq.hpp
> +#include <string>
fixed

2024-11-01 07:23 UTC, TayaGordeeva commented on tasks/seq/gordeva_t_max_val_of_column_matrix/src/ops_seq.cpp
> +#include <thread>
fixed

2024-11-01 07:24 UTC, TayaGordeeva commented on tasks/seq/gordeva_t_max_val_of_column_matrix/perf_tests/main.cpp
> +  std::vector<int> res_vec(rows, 0);
fixed

2024-11-01 07:24 UTC, TayaGordeeva commented on tasks/seq/gordeva_t_max_val_of_column_matrix/src/ops_seq.cpp
> +  for (size_t i = 0; i < res_.size(); i++) output_matr[i] = res_[i];
rewrote on copy

2024-11-01 07:29 UTC, SergeyBoRss approved these changes

2024-11-01 09:01 UTC, maximchhek reviewed
GJ

2024-11-01 09:01 UTC, maximchhek commented on tasks/seq/gordeva_t_max_val_of_column_matrix/func_tests/main.cpp
You should add tests with uncorrect values

2024-11-01 10:54 UTC, TayaGordeeva commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/perf_tests/main.cpp
tests with incorrect values for parallel program are created

2024-11-01 10:54 UTC, TayaGordeeva commented on tasks/seq/gordeva_t_max_val_of_column_matrix/func_tests/main.cpp
tests with incprrect values for sequential program are created

2024-11-01 11:40 UTC, maximchhek approved these changes

2024-11-01 13:45 UTC, SergeyBoRss approved these changes

2024-11-02 13:25 UTC, aobolensk requested changes

2024-11-02 13:25 UTC, aobolensk commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/include/ops_mpi.hpp
> +// std::vector<int> getRandomVector(int sz);
Remove commented out code everywhere

2024-11-02 13:25 UTC, aobolensk commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/src/ops_mpi.cpp
> +  broadcast(world, cols, 0);
Move MPI operations to ::run()

2024-11-02 19:13 UTC, TayaGordeeva commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/include/ops_mpi.hpp
> +// std::vector<int> getRandomVector(int sz);
comments are removed

2024-11-02 19:13 UTC, TayaGordeeva commented on tasks/mpi/gordeva_t_max_val_of_column_matrix/src/ops_mpi.cpp
> +  broadcast(world, cols, 0);
done

2024-11-03 03:53 UTC, aobolensk approved these changes

2024-11-04 00:49 UTC, allnes approved these changes

2024-11-04 00:49 UTC, merged