Мурадов Майк. Задача 1. Вариант 22. Подсчет числа буквенных символов в строке
learning-process/ppc-2024-autumn pull request #84
Opened 2024-10-31 15:26 UTC by MikeMuradov

## SEQ версия

1. Загружается входная строка, переменная `alpha_count_` обнуляется
2. Подсчитывается количество буквенных символов с помощью `std::count_if` и `std::isalpha`
3. Значение `alpha_count_` записывается в `taskData->outputs`

## MPI версия

1.  Процесс с `rank = 0` загружает входную строку, длина `n` передается всем процессам
2. Процесс 0 делит строку на части и передает их каждому процессу с помощью `scatterv`
3. Каждый процесс подсчитывает количество буквенных символов в своей части строки
4. Функция `reduce` суммирует локальные результаты в `total_alpha_count_`
5. Процесс 0 записывает `total_alpha_count_` в `taskData->outputs`

2024-10-31 16:15 UTC, erty1909 reviewed
It is necessary to add more tests for strings of different lengths to check the correctness of the distribution of the string across processes.

2024-10-31 16:16 UTC, korablev-vm reviewed
Even in the latest PR, for some reason they began to swear at the MPI functionality in pre_processing(), move it to run()

2024-10-31 16:16 UTC, korablev-vm commented on tasks/mpi/muradov_m_count_alpha_chars/src/ops_mpi.cpp
> +  std::this_thread::sleep_for(20ms);
you need to remove this slepp

2024-10-31 16:16 UTC, korablev-vm commented on tasks/seq/muradov_m_count_alpha_chars/src/ops_seq.cpp
> +  std::this_thread::sleep_for(20ms);
and this also needs to be removed

2024-10-31 17:20 UTC, MikeMuradov commented on tasks/seq/muradov_m_count_alpha_chars/src/ops_seq.cpp
> +  std::this_thread::sleep_for(20ms);
fixed

2024-10-31 17:22 UTC, korablev-vm approved these changes

2024-10-31 17:24 UTC, allnes approved these changes

2024-10-31 17:36 UTC, erty1909 approved these changes

2024-11-02 00:26 UTC, aobolensk requested changes

2024-11-02 00:26 UTC, aobolensk commented on tasks/mpi/muradov_m_count_alpha_chars/include/ops_mpi.hpp
> +
Please move test methods to the test module

2024-11-02 00:26 UTC, aobolensk commented on tasks/mpi/muradov_m_count_alpha_chars/src/ops_mpi.cpp
> +    input_str_[i] = tmp_ptr[i];
You can use std::copy here

2024-11-02 06:20 UTC, MikeMuradov commented on tasks/mpi/muradov_m_count_alpha_chars/include/ops_mpi.hpp
> +
fixed

2024-11-02 06:20 UTC, MikeMuradov commented on tasks/mpi/muradov_m_count_alpha_chars/src/ops_mpi.cpp
> +    input_str_[i] = tmp_ptr[i];
fixed

2024-11-02 13:26 UTC, aobolensk approved these changes

2024-11-02 13:27 UTC, merged