Лаврентьев Алексей Задача 1 Вариант 5 Нахождение числа чередований знаков значений соседних элементов вектора
learning-process/ppc-2024-autumn pull request #85
Opened 2024-10-31 16:07 UTC by mahor13

Задача заключается в подсчете количества переходов между положительными и отрицательными числами в одномерном векторе целых чисел. Для корректного выполнения алгоритма требуется, чтобы вектор содержал не менее двух элементов, а результатом работы должен быть единственное число.

### Последовательная версия алгоритма:
В этой версии алгоритм проходит по вектору от первого до предпоследнего элемента. Для каждой пары соседних элементов проверяется, произошла ли смена знака. Это делается с использованием операции произведения: если результат меньше нуля, значит, знаки элементов различны. Каждый раз, когда обнаруживается смена знака, увеличивается счетчик. После завершения прохода по вектору значение счетчика представляет собой общее количество чередований знаков.

### Версия алгоритма с использованием MPI:
1. Разделение данных: Процесс с рангом 0 делит входной вектор на блоки. Все блоки, кроме последнего, включают первый элемент следующего блока, чтобы сохранить информацию о возможной смене знаков на границе блоков. Каждый блок отправляется соответствующему процессу.

2. Вычисления: Каждый процесс обрабатывает свой блок данных, подсчитывая количество чередований знаков внутри него.

3. Сбор результатов: Каждый процесс возвращает частичный результат (количество чередований знаков в своем блоке) процессу 0 с помощью операции reduce, которая суммирует все частичные результаты.

4. Обработка результата: Процесс с рангом 0 собирает и возвращает итоговое количество чередований как финальный результат выполнения задачи. 

Таким образом, алгоритм эффективно распределяет вычисления между несколькими процессами, что позволяет ускорить обработку больших векторов.

2024-10-31 17:24 UTC, allnes commented on tasks/mpi/baranov_a_num_of_orderly_violations/func_tests/main.cpp
> -#include <gtest/gtest.h>
please don't remove not own files

2024-10-31 18:35 UTC, KolodkinGrigorii commented on tasks/mpi/lavrentyev_a_alternation_count/src/ops_mpi.cpp
> +    if ((input_[i] * input_[i + 1]) <= 0) {
Not working in case with double zero. In {0,0} this function return 1, but should return 0

2024-10-31 19:29 UTC, KolodkinGrigorii approved these changes

2024-11-02 17:04 UTC, MishaRysev approved these changes

2024-11-03 02:39 UTC, aobolensk requested changes

2024-11-03 02:39 UTC, aobolensk commented on tasks/mpi/khasanyanov_k_average_vector/func_tests/main.cpp
> -#include <memory>
Please, do not modify others' file

2024-11-03 02:39 UTC, aobolensk commented on tasks/mpi/lavrentyev_a_alternation_count/src/ops_mpi.cpp
> +  }
Move MPI data transfer calls to ::run()

2024-11-03 19:10 UTC, mahor13 commented on tasks/mpi/lavrentyev_a_alternation_count/src/ops_mpi.cpp
> +  }
fixed

2024-11-06 16:20 UTC, closed without merging