Ермилова Дарья. Задача 1. Вариант 14. Минимальное значение элементов матрицы.
learning-process/ppc-2024-autumn pull request #86
Opened 2024-10-31 19:27 UTC by ermilovad

Описание последовательной задачи
Последовательно обходятся все элементы матрицы, при нахождении элемента меньше, чем текущий минимум - значение минимума будет обновлено.

Описание MPI задачи
Матрица разбивается на равные части. Каждый процесс получает свою часть матрицы, затем находит минимум в выделенной ему части. После этого все процессы отправляют свои результаты корневому процессу, который собирает их и находит минимум для всей матрицы.

2024-11-02 11:27 UTC, kmichaelk requested changes

2024-11-02 11:27 UTC, kmichaelk commented on tasks/mpi/ermilova_d_min_element_matrix/perf_tests/main.cpp
> +    const int rows = 5000;
Perf test data in parallel and sequential tests should be the same to ensure fair comparison

2024-11-02 11:44 UTC, kmichaelk approved these changes

2024-11-02 12:13 UTC, odincovm approved these changes
Замечаний не вижу, крома лишней библиотеки #include <string> в файле ops_seq.cpp

2024-11-02 12:16 UTC, odincovm approved these changes
Все исправлено апрувлю

2024-11-03 02:42 UTC, aobolensk requested changes

2024-11-03 02:42 UTC, aobolensk commented on tasks/mpi/ermilova_d_min_element_matrix/include/ops_mpi.hpp
> +std::vector<std::vector<int>> getRandomMatrix(int rows, int cols, int upper_border, int lower_border);
Please, move to the test module

2024-11-03 02:42 UTC, aobolensk commented on tasks/mpi/ermilova_d_min_element_matrix/src/ops_mpi.cpp
> +
Please, move MPI related data transfer stuff to ::run()

2024-11-03 13:54 UTC, aobolensk approved these changes

2024-11-04 00:51 UTC, allnes approved these changes

2024-11-04 00:51 UTC, merged