Борисов Сергей. Задача 1. Вариант 11. Сумма значений по строкам матрицы
learning-process/ppc-2024-autumn pull request #90
Opened 2024-10-31 21:02 UTC by SergeyBoRss

SEQ: В последовательной реализации программа считывает матрицу и вычисляет сумму элементов в каждой строке путем простого прохода по всем элементам. Результаты суммирования сохраняются в выходном массиве, где каждый элемент соответствует сумме одной строки матрицы

MPI: В параллельной реализации с использованием MPI матрица распределяется по процессам: главный процесс делит матрицу на части по строкам и отправляет каждую часть соответствующему процессу. Каждый процесс независимо вычисляет сумму своих строк. Затем локальные суммы собираются обратно на главном процессе, который объединяет их в итоговый массив сумм по строкам

2024-11-01 08:08 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_sum_of_rows/func_tests/main.cpp
> +    global_matrix = {INT_MAX, INT_MIN, INT_MAX, INT_MIN};
Already there is

2024-11-01 08:45 UTC, SergeyBoRss commented on tasks/seq/borisov_s_sum_of_rows/src/ops_seq.cpp
> +#include <thread>
fixed

2024-11-01 08:45 UTC, SergeyBoRss commented on tasks/seq/borisov_s_sum_of_rows/include/ops_seq.hpp
> +#include <string>
fixed

2024-11-01 08:47 UTC, TayaGordeeva approved these changes

2024-11-01 14:25 UTC, maximchhek commented on tasks/mpi/borisov_s_sum_of_rows/func_tests/main.cpp
Create test then pre_processing make empty matrix

2024-11-01 14:25 UTC, maximchhek commented on tasks/seq/borisov_s_sum_of_rows/perf_tests/main.cpp
Create test then pre_processing make empty matrix

2024-11-01 16:01 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_sum_of_rows/func_tests/main.cpp
Done

2024-11-01 16:01 UTC, SergeyBoRss commented on tasks/seq/borisov_s_sum_of_rows/perf_tests/main.cpp
Done

2024-11-01 16:02 UTC, maximchhek approved these changes

2024-11-02 13:28 UTC, aobolensk requested changes

2024-11-02 13:28 UTC, aobolensk commented on tasks/mpi/borisov_s_sum_of_rows/func_tests/main.cpp
> +#include <gtest/gtest.h>
Patch test coverage is too low

2024-11-02 13:28 UTC, aobolensk commented on tasks/mpi/borisov_s_sum_of_rows/include/ops_mpi.hpp
> +std::vector<int> getRandomMatrix(size_t rows, size_t cols);
Please, move test functions to the test module

2024-11-02 13:28 UTC, aobolensk commented on tasks/mpi/borisov_s_sum_of_rows/src/ops_mpi.cpp
> +  MPI_Scatterv(sendbuf, sendcounts.data(), displs.data(), MPI_INT, loc_matrix_.data(),
Please, move all MPI functions to the ::run()

2024-11-02 16:07 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_sum_of_rows/include/ops_mpi.hpp
> +std::vector<int> getRandomMatrix(size_t rows, size_t cols);
fixed

2024-11-02 16:07 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_sum_of_rows/src/ops_mpi.cpp
> +  MPI_Scatterv(sendbuf, sendcounts.data(), displs.data(), MPI_INT, loc_matrix_.data(),
fixed

2024-11-02 19:43 UTC, SergeyBoRss commented on tasks/mpi/borisov_s_sum_of_rows/func_tests/main.cpp
> +#include <gtest/gtest.h>
fixed

2024-11-03 03:54 UTC, aobolensk approved these changes

2024-11-04 00:51 UTC, allnes approved these changes

2024-11-04 00:52 UTC, merged