Волочаев Серафим Задача 1. Вариант 27: Подсчет числа несовпадающих символов двух строк
learning-process/ppc-2024-autumn pull request #92
Opened 2024-10-31 22:06 UTC by Svoloch2940194

Последовательный вариант:
Input: 2 строки (могут быть разных длин). Если длины не совпадают, то начальное состояние ответа: разность длин 2 строк, иначе 0. Проходимся линейно по строкам и сравниваем по id. Если буквы на одинаковых позициях не совпадают, то прибавляем к ответу 2, иначе идем дальше до минимальной длины из 2 строк.
pre_processing: Получение данных. Мы берем 2 строки и смотрим на их длину. Если разные, то обрезаем большую до длины меньшей, а разницу в длине помещаем в ответ.
validation: проверяем входные и выходные данные по количеству ( входных должно быть 2, а выходных 1)
run: идем по 2 строкам и сравниваем символы по id. Если не совпадают, то прибавляем 2. Иначе идем дальше.
post_processing: запись результата.

Параллельный вариант:
идея та же, но мы бьем строки на потоки. Если у нас размер минимальной строки size, то мы size делим на world.size() и получаем сколько должен обработать каждый поток символов. далее бьем на потоки таким образом:
1 поток: [0, x]
2 поток: [x+1, 2x]
3 поток: [2x+1, 3*x]
...
n-й поток: [(n-1)x+1,nx]
...

2024-11-01 07:01 UTC, Napkin-AI requested changes

2024-11-01 07:01 UTC, Napkin-AI commented on tasks/mpi/volochaev_s_count_characters_27/func_tests/main.cpp
> +#include <gtest/gtest.h>
add tests (see seq version comment)

2024-11-01 08:07 UTC, Svoloch2940194 commented on tasks/mpi/volochaev_s_count_characters_27/src/ops_mpi.cpp
> +  return taskData->outputs_count[0] == 1;
fix

2024-11-01 08:08 UTC, Svoloch2940194 commented on tasks/mpi/volochaev_s_count_characters_27/src/ops_mpi.cpp
> +    return taskData->outputs_count[0] == 1;
fix

2024-11-01 08:08 UTC, Svoloch2940194 commented on tasks/mpi/volochaev_s_count_characters_27/src/ops_mpi.cpp
> +    for_res = abs((int)tmp1.size() - (int)tmp2.size());
fix

2024-11-01 08:08 UTC, Svoloch2940194 commented on tasks/mpi/volochaev_s_count_characters_27/src/ops_mpi.cpp
> +    auto tmp1 = reinterpret_cast<std::string*>(taskData->inputs[0])[0];
fix

2024-11-01 08:13 UTC, Svoloch2940194 commented on tasks/seq/volochaev_s_count_characters_27/func_tests/main.cpp
> +// Copyright 2023 Nesterov Alexander
fix

2024-11-01 08:22 UTC, Svoloch2940194 commented on tasks/seq/volochaev_s_count_characters_27/func_tests/main.cpp
> +TEST(volochaev_s_count_characters_27_seq, Test_1) {
fix

2024-11-01 08:25 UTC, Svoloch2940194 commented on tasks/seq/volochaev_s_count_characters_27/perf_tests/main.cpp
> +  s.back() = 'a';
fix

2024-11-01 08:26 UTC, Svoloch2940194 commented on tasks/mpi/volochaev_s_count_characters_27/perf_tests/main.cpp
> +    global_vec[1].back() = char(((int)s.back() + 1) % 256);
fix

2024-11-01 08:26 UTC, Svoloch2940194 commented on tasks/mpi/volochaev_s_count_characters_27/func_tests/main.cpp
> +#include <gtest/gtest.h>
fix

2024-11-02 14:41 UTC, Napkin-AI approved these changes

2024-11-02 14:45 UTC, KorotinEgor commented on tasks/mpi/volochaev_s_count_characters_27/src/ops_mpi.cpp
> +  }
You can use std::copy

2024-11-02 14:45 UTC, KorotinEgor commented on tasks/mpi/volochaev_s_count_characters_27/src/ops_mpi.cpp
> +    }
You can use std::copy

2024-11-02 14:45 UTC, KorotinEgor commented on tasks/seq/volochaev_s_count_characters_27/src/ops_seq.cpp
> +  }
Youcan use std::copy

2024-11-02 16:11 UTC, KorotinEgor commented on tasks/seq/volochaev_s_count_characters_27/src/ops_seq.cpp
> +}
There are no functional tests using this feature, which leads to low code coverage

2024-11-03 04:41 UTC, Svoloch2940194 commented on tasks/seq/volochaev_s_count_characters_27/src/ops_seq.cpp
> +}
fix

2024-11-03 04:41 UTC, Svoloch2940194 commented on tasks/seq/volochaev_s_count_characters_27/perf_tests/main.cpp
> +  int ans = 2;
fix

2024-11-03 07:13 UTC, KorotinEgor approved these changes

2024-11-03 09:45 UTC, aobolensk approved these changes

2024-11-04 00:52 UTC, allnes approved these changes

2024-11-04 00:53 UTC, merged