Созонов Илья. Задача 1. Вариант 7. Нахождение наиболее близких соседних элементов вектора.
learning-process/ppc-2024-autumn pull request #93
Opened 2024-11-01 00:57 UTC by sozozzya

**Описание последовательной задачи:**
1. Создаём переменную min и инициализируем её максимальным возможным значением INT_MAX.
2. Проходим по вектору, начиная с первого элемента до предпоследнего, и находим модуль разности между текущим элементом и следующим за ним.
3. Если модуль разности между ними меньше текущего значения min, обновляем min и запоминаем индекс текущего элемента вектора.

**Описание MPI задачи:**
1. Создаем новый вектор diff, состоящий из пар: модуль разности соседних элементов исходного вектора и соответствующего индекса.
2. Полученный вектор пар делится равномерно на сегменты по числу процессов.
3. Каждый сегмент данных отправляется от нулевого процесса остальным.
4. Каждый процесс находит наименьший элемент и соответствующий ему индекс в полученном сегменте данных.
5. После завершения локальных вычислений процессы возвращают результаты корневому процессу, где с помощью коллективной операции reduce находится наименьший модуль разности соседних элементов вектора и соответствующий индекс.

2024-11-01 05:29 UTC, KolodkinGrigorii commented on tasks/mpi/sozonov_i_nearest_neighbor_elements/func_tests/main.cpp
> +#include <gtest/gtest.h>
add test for empty vector

2024-11-01 08:09 UTC, MatveyKurakin commented on tasks/mpi/sozonov_i_nearest_neighbor_elements/func_tests/main.cpp
> +
Add a test on a small non-random vector that checks the correctness of the parallel and sequential algorithm

2024-11-01 18:26 UTC, sozozzya commented on tasks/mpi/sozonov_i_nearest_neighbor_elements/func_tests/main.cpp
> +#include <gtest/gtest.h>
fixed, please check

2024-11-01 18:26 UTC, sozozzya commented on tasks/mpi/sozonov_i_nearest_neighbor_elements/func_tests/main.cpp
> +
fixed, please check

2024-11-01 18:38 UTC, MatveyKurakin approved these changes

2024-11-01 18:50 UTC, KolodkinGrigorii approved these changes

2024-11-02 13:30 UTC, aobolensk requested changes

2024-11-02 13:30 UTC, aobolensk commented on tasks/mpi/sozonov_i_nearest_neighbor_elements/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
Please, move to the test module

2024-11-02 18:43 UTC, sozozzya commented on tasks/mpi/sozonov_i_nearest_neighbor_elements/include/ops_mpi.hpp
> +std::vector<int> getRandomVector(int sz);
fixed, please check

2024-11-03 03:54 UTC, aobolensk approved these changes

2024-11-04 00:53 UTC, allnes approved these changes

2024-11-04 00:53 UTC, merged