Матюнина Александра. Задача 1. Вариант 2. Вычисление среднего значения элементов вектора
learning-process/ppc-2024-autumn pull request #98
Opened 2024-11-01 11:16 UTC by erty1909

seq: На вход получаем вектор из элементов и должны найти среднее значение элементов этого вектора. Складываем значения каждого элемента вектора и записываем в одну переменную, а затем делим на общее число элементов. Таким образом мы найдём следнее значение.
mpi: Делим один большой вектор значений на несколько отрезков и передаём эти отрезки различным процессам, размер отрезков определяется относительно количества процессов на котором мы будем работать. После этого складываем все значения полученные из разных процессов в главном процессе и в нём же делим это число на размер всего вектора.

2024-11-01 11:51 UTC, hasanyanovk commented on tasks/mpi/matyunina_a_average_of_vector_elements/src/ops_mpi.cpp
> +    local_input_ = std::vector<int>(input_.begin(), input_.begin() + delta + remainder);
double intialization, you can unite `if` block and initialize vector in it's own block

2024-11-01 12:17 UTC, erty1909 commented on tasks/mpi/matyunina_a_average_of_vector_elements/src/ops_mpi.cpp
> +    local_input_ = std::vector<int>(input_.begin(), input_.begin() + delta + remainder);
in the example from the teacher, everything is done the same way
![image](https://github.com/user-attachments/assets/6f4c3409-e17b-40e1-83c5-1d0039902bae)

2024-11-01 13:09 UTC, LizochkaSpring commented on tasks/mpi/matyunina_a_average_of_vector_elements/func_tests/main.cpp
> +TEST(matyunina_a_average_of_vector_elements_mpi, Test_99) {
Rename the names of the tests

2024-11-01 13:50 UTC, erty1909 commented on tasks/mpi/matyunina_a_average_of_vector_elements/func_tests/main.cpp
> +TEST(matyunina_a_average_of_vector_elements_mpi, Test_99) {
fixed

2024-11-01 18:36 UTC, LizochkaSpring approved these changes

2024-11-02 13:01 UTC, Cufeed reviewed
you can add a check for the emptiness of the vector. For example in your run func:

if (input_.empty()) {
        return false;
    }

2024-11-02 13:32 UTC, aobolensk requested changes

2024-11-02 13:32 UTC, aobolensk commented on tasks/mpi/matyunina_a_average_of_vector_elements/src/ops_mpi.cpp
> +  broadcast(world, delta, 0);
Please, move MPI functions to ::run()

2024-11-02 13:32 UTC, aobolensk commented on tasks/seq/matyunina_a_average_of_vector_elements/src/ops_seq.cpp
> +    input_[i] = tmp_ptr[i];
use std::copy

2024-11-02 15:17 UTC, erty1909 commented on tasks/seq/matyunina_a_average_of_vector_elements/src/ops_seq.cpp
> +    input_[i] = tmp_ptr[i];
fixed

2024-11-02 15:17 UTC, erty1909 commented on tasks/mpi/matyunina_a_average_of_vector_elements/src/ops_mpi.cpp
> +  broadcast(world, delta, 0);
fixed

2024-11-02 15:55 UTC, Cufeed approved these changes

2024-11-03 03:55 UTC, aobolensk approved these changes

2024-11-04 00:55 UTC, allnes approved these changes

2024-11-04 00:55 UTC, merged